### ISSUE TITLE
cpu usage on latest builds with OS X 10.10.3

### ISSUE THREAD

**Issue by reicheltd** [vifm/vifm#100]
Hi xaizek,
currently I am using stable 0.7.8 again, because the latest builds had significant higher cpu usages.

stable 0.7.8: 0.3 % in idle mode
current master: around 20% idling. Sometimes jumps to 30%

**Comment by xaizek** [comment]
Hello Daniel,

The latest related change I remember was in 4046c873dca0cf48011101f2a333d02681a8eb76, but it actually fixed excessive CPU usage...  Maybe try its parent (4294a022a1d08fd4e8524f157bd7e589a3c72fe8).

I couldn't reproduce the issue yet, but it should be related to view reloading and wrong check for changes in directories.

**Comment by reicheltd** [comment]
Hey! On the latest build f5ec6ea the cpu usage in idle is around 0.1% great stuff! Other builds Ive checked out the last 4 weeks all had high cpu usage. Looking forward to version 0.8! Thanks!
