### ISSUE TITLE
$VARIABLE expansion segfaults.

### ISSUE THREAD

**Issue by Quaddroo** [vifm/vifm#1004]
**How to reproduce:**
```
export EDITOR="/usr/local/bin/nvim -w AAAAAAAAAAAAAAAA"
vifm
:!$EDITOR
```
Fails: "double free or corruption (out)"
contrast with:
```
export EDITOR="/usr/local/bin/nvim -w AAAAAAAAAAAAAAA"
vifm
:!$EDITOR
```
works

some other observations:
```
export EDITOR="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
vifm
:!$EDITOR
```
this works, so it's not just the length of the string that triggers it.
If you type the command directly into the command line, it does not fail, so I thought it misallocates the amount of necessary memory because the $EDITOR text is shorter than what it expands to, but the overall evidence does not support this. Unfortunately, no idea how to debug this further.

Sometimes, depending on the "EDITOR" string, it also throws a segmentation fault or "corrupted double-linked list".
Sometimes, it will not immediately fail - only after you exit the spawned nvim instance and go down a few times (jjjj or something).

This is an actual issue, not just theoretical, I stumbled upon it by having my EDITOR set to "/usr/local/bin/nvim -w /home/qq/documents/vim_keypress_history.txt
"
**Environment**
```
vifm --version
Version: 0.13
Git info: built out of repository
Compiled at: Jul  3 2024 18:56:14

Support of extended keys is on
Parsing of .desktop files is enabled
With GTK+ library
Without magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```
System: Debian 10.
```
nvim --version
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/qq/nvim/source/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/build/src/nvim/auto -I/home/qq/nvim/source/neovim/build/include -I/home/qq/nvim/source/neovim/build/cmake.config -I/home/qq/nvim/source/neovim/src -I/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include -I/home/qq/nvim/source/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
The command, of course, works outside of vifm, but I figured perhaps the nvim version might be useful if someone tries and fails to reproduce.

**Potentially related** 
https://github.com/vifm/vifm/issues/491

**Comment by xaizek** [comment]
Thank you for the report.  Have no trouble reproducing the bug on Slackware current.

Sounds like you have [`'fastrun'`](https://vifm.info/vimdoc.shtml#vifm-%27fastrun%27) set, turning it off should work as a workaround.  The bug is in completion code but `'fastrun'` triggers it.  I was actually thinking of eventually removing the option as one can accidentally run random things when it's on (prefix must be unambiguous but it still be a wrong command) and yet turns out it's on in my config...
