### ISSUE TITLE
[feature request] adding the `<wait>` map argument to `vifm.keys.add()`

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#1007]
hi folks, i got the need to remap `<c-z>` in a lua plugin through vifm.keys.add(),
as `<c-z>` is builtin, i have to mark it as `<wait>` [i believe](http://q2a.vifm.info/1483/how-to-correctly-display-mapping-completions?show=1483#q1483).

but vifm.keys.add() accepts no wait parameter, so is it possible to add it?

i have read some code and know that: vifm.keys.add() invokes vle_keys_foreign_add while `:map` invokes vle_keys_user_add, so they add two kind of keys. i'm not sure that if a foreign key is supposed to have `wait` property enabled, or maybe the `wait` property should be enabled by default.

**Comment by haolian9** [comment]
it's not easy than i thought, i tried
```
diff --git a/src/engine/keys.c b/src/engine/keys.c
index 621055817..8c0ac546d 100644
--- a/src/engine/keys.c
+++ b/src/engine/keys.c
@@ -1015,6 +1015,8 @@ vle_keys_foreign_add(const wchar_t lhs[], const key_conf_t *info,
                                                          : BUILTIN_WAIT_POINT;
        curr->foreign = 1;
        curr->conf = *info;
+       curr->no_remap = 1;
+       curr->wait = 1;
        return 0;
 }
```
and it makes no difference.

**Comment by haolian9** [comment]
ah, it seems that the `<c-z>` is a special one.

**Comment by haolian9** [comment]
as i know more, now i believe this `<wait>` is irrelevant to my real problem. so i'm closing it as i have no concrete usecase for it so far.

**Comment by xaizek** [comment]
> as i know more, now i believe this `<wait>` is irrelevant to my real problem. so i'm closing it as i have no concrete usecase for it so far.

Yes, it is irrelevant.  `<wait>` effectively raises priority of a user mapping over a builtin one, so your guess that it might play a role was justified if it weren't for special handling.
