### ISSUE TITLE
ueberzug plugin: Unable to unmount archive if preview was issued inside archive

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#1013]
## Summary

When using the `ueberzug` plugin, if you run the preview and spawn `ueberzug`
process with the `$PWD` inside the archive, this process prevents you from
exiting the archive and process isn't killed when closing the preview
pane.

## Steps to reproduce

0. Install `ueberzugpp` and enable `ueberzug` plugin
1. Go down into archive with images
2. <kbd>w</kbd> to enable preview
3. <kbd>w</kbd> to disable preview
4. <kbd>h</kbd> to get out from archive

## Expected result

Leaving the archive without any problems.

## Actual result

Error popus shown:

![image](https://github.com/user-attachments/assets/b7273c8c-265c-48c3-9289-740e617c296d)

Unable to leave archive.

## Workarounds

1. `:jobs` to list `ueberzugpp` process
2. <kbd>dd</kbd> to kill it
3. leave the archive
4. profil!

## Code solutions

1) Spawn `ueberzugpp` outside of any archive (in `$XDG_CACHE_HOME/vifm`, for example)
2) SIGTERM `ueberzugpp` on preview pane closing (requires addition Lua API)

**Comment by xaizek** [comment]
Thanks, I've seen that too.  Starting a job needs a way of specifying working directory to prevent this.
