### ISSUE TITLE
Image preview not clearing properly

### ISSUE THREAD

**Issue by TomiCode** [vifm/vifm#102]
Hello.
I just discovered the great function of the image preview using the `w3m` package. While using it, I found that the preview window is not *clearing* while switching to some other files.
Here is an image, of that issue:
![2015-07-17-104310_1366x768_scrot](https://cloud.githubusercontent.com/assets/1648325/8743717/79082e08-2c71-11e5-8c6c-3c39b7e6c4a6.png)

My current setup:
- Arch linux, with bspwm
- Terminal: **urxvt**, *with depth set to 24*
- vifm version: *latest* from github.

**Comment by xaizek** [comment]
Hi,

you're right, it doesn't work in urxvt. There is a fake drawing on the window to convince terminal emulator to clean background, looks like urxvt optimizes that out. Thanks, I'll look for a way to fix this.

**Comment by xaizek** [comment]
Looks like the only robust way of doing this is to call w3m again and ask it to erase the image.

`add-pc-macro` branch provides a way to specify cleanup command, like this:
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ imgt %px %py %pw %ph %c %pc imgc %px %py %pw %ph
```
where `imgc` is:
```bash
#!/bin/bash

W3MIMGDISPLAY="/usr/libexec/w3m/w3mimgdisplay"
FONTH=13 # Size of one terminal row
FONTW=6 # Size of one terminal column

X=$1
Y=$2
COLUMNS=$3
LINES=$4

x=$((FONTW * X))
y=$((FONTH * Y))

erase="6;$x;$y;$(( FONTW*COLUMNS ));$(( FONTH*LINES ))\n3;"
echo -e "$erase" | $W3MIMGDISPLAY
```

This already works in most cases, I'll try to take care of the rest.

There is also a limitation that window background should better match default terminal background because that's the color used for clearing. Don't know if there is a way to work around this.

**Comment by TomiCode** [comment]
Thank You, for taking the time and looking into a *less needed* feature / bug.

I see, there is only one case that the image is not clearing, after switching from an image to a directory, like `../` or `other_directory/`.

And again, Thank You. :+1:

**Comment by xaizek** [comment]
> I see, there is only one case that the image is not clearing, after switching from an image to a directory, like ../ or other_directory/.

Thank you, I didn't see this, it somehow works fine in this case for me. Updated the branch with the fix, please give a try to make sure it actually works.

**Comment by TomiCode** [comment]
Yep, everything works like a charm. Thank You.
