### ISSUE TITLE
viewcolumns value is not validated in vifmrc

### ISSUE THREAD

**Issue by VadimCurca** [vifm/vifm#1022]
When setting the viewcolumns option in vifmrc to an invalid value, such as `windo set viewcolumns=typo`, no error will be displayed during startup. Initially, the file list loads normally, falling back to the `DEFAULT_VIEW_COLUMNS` value. However, as soon as you change directories, the file list disappears (`view->columns->count` becomes 0), leaving the interface blank, as shown in the image below:
<img src="https://github.com/user-attachments/assets/1f55e81e-14e1-4ecc-b11d-d7a27e094d8e" width="400">

**Comment by xaizek** [comment]
It is validated, see `:messages` after startup.  It's not a parsing error, so there is no error dialog.  However, only local value of the option is restored, hence you get `typo` after switching a directory.  Thanks for the report.

**Comment by xaizek** [comment]
By the way, there is no need to use `:windo` in `vifmrc` like that.  It's implicit inside `vifmrc` for `:set` and some other :commands.
