### ISSUE TITLE
&& operator doesn't work

### ISSUE THREAD

**Issue by justpretending2** [vifm/vifm#1023]
I have this in my `~/.config/vifm/vifmrc` (it's the default one created by vifm 0.13):

```
if $DISPLAY && executable('gvim')
...
endif
```

The commands between `if` and `endif` never get executed, though both `$DISPLAY` and `executable('gvim')` are true.

When I use either condition separately, they both work:

```
if $DISPLAY
" this works
endif
```

```
if executable('gvim')
" this works as well
endif
```

This works, too:
```
if $DISPLAY 
if executable('gvim')
    " Open file in existing instance of gvim
    nnoremap o :!gvim --remote-tab-silent %f<cr>
    " Open file in new instance of gvim
    nnoremap O :!gvim %f<cr>
endif
endif
```

```
$ vifm --version
Version: 0.13
Git info: built out of repository
Compiled at: Oct  3 2024 11:16:47

Support of extended keys is on
Parsing of .desktop files is enabled
With GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by justpretending2** [comment]
And this seems to work:

`:if $DISPLAY != "" && executable('gvim')|echo 1|endif`

**Comment by xaizek** [comment]
Something is clearly off.  Thanks for the report!

**Comment by xaizek** [comment]
Hm, actually `if $DISPLAY` shouldn't work either.  In Vim strings are converted to integers when used in expressions (so `"1bla"` is `true`, while `"bla"` and `"0bla"` are `false`), Vifm states the same in the documentation but is doing it only when expression has more than a single term.

**Comment by justpretending2** [comment]
Related:

```
:echo $A
1
:echo $B
2
:if $A && $B|echo 1|endif
<no output>
```

https://github.com/vifm/vifm/blob/6492216f716daea410d73a6d0ba5f8c762a34adc/src/engine/parsing.c#L404

**Comment by xaizek** [comment]
Thanks, those should be conversions to bool.  By the way, I may leave `if $DISPLAY` working as is for now and make it print a warning to give users time to update configurations.

**Comment by ammgws** [comment]
For anyone else who comes across this while searching for the warning message, I found that I had to delete the ~/.config/vifm/config file (I had not customised it anyway) so that vimfm would regenerate it with the updated check for $WAYLAND_DISPLAY

**Comment by xaizek** [comment]
> I found that I had to delete the ~/.config/vifm/config file (I had not customised it anyway)

That's one way of going about it, but it won't work for those who customized the config.  Alternative instructions are available [here](https://q2a.vifm.info/1983/the-waylanddisplay-condition-seems-to-be-relying-on-a-bug?show=1984#a1984).
