### ISSUE TITLE
Off-by-one in the status line when moving files

### ISSUE THREAD

**Issue by justpretending2** [vifm/vifm#1024]
`(hit i for details) Moving: 1687 of 1686; ...`

**Comment by xaizek** [comment]
Not an off-by-one.  Directories aren't accounted for by an estimate.  I might have planned to treat them differently initially because creating/removing them is fast and they can inflate number of operations.  Don't think it's justified anymore.  Thanks for the reminder.

**Comment by justpretending2** [comment]
Thanks. There's no need to add my name to the change log because it's a temporary account.

**Comment by xaizek** [comment]
Won't hurt to have the temporary name.  Even if it becomes a @ghost account, the emails will still have it.
