### ISSUE TITLE
Closing fileviewer which was opened in another pane

### ISSUE THREAD

**Issue by Shamaoke** [vifm/vifm#1025]
Hi.

When entering the file preview mode by using the `:view` command the file under cursor is displayed in another vifm pane. What key and what command can be used to exit this mode?

Thanks.

**Comment by xaizek** [comment]
Hello, 

See [the docs](https://vifm.info/vimdoc.shtml#vifm-%3Aview):
 - `:view` toggles preview
 - there is also [`'quickview'` option](https://vifm.info/vimdoc.shtml#vifm-%27quickview%27) so `:set noquickview` will work as well.
