### ISSUE TITLE
Use of MAX_ARG_STRLEN breaks compilation on AArch64

### ISSUE THREAD

**Issue by hrw** [vifm/vifm#103]
MAX_ARG_STRLEN definition depends on PAGE_SIZE to be defined. But on AArch64 page size can be either 4K or 64K so it is not defined in any system header.

As a result vifm 0.8 fails to build on this architecture.

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1244855

**Comment by xaizek** [comment]
Thanks, added test to `configure` that actually checks whether `MAX_ARG_STRLEN` is usable. This looks like an oversight in kernel headers, providing macro that can't be used is wrong, it's either shouldn't be defined at all or should have a value that won't fail during compilation.
