### ISSUE TITLE
Fileops test changing setuid triggers security alert

### ISSUE THREAD

**Issue by igorepst** [vifm/vifm#1030]
Hello, @xaizek.
Some time ago I built v0.13-592-gcf35d4f74798 version on MacOS via [Homebrew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/v/vifm.rb). The IT department of the organization I work for notified me that the tests triggered a security alert.

    Process-tree:
    Filename:/bin/bash
    CMD: /bin/sh -c cd /private/tmp/vifm-20241027-69036-cy9pch/tests/ &&  /private/tmp/vifm-20241027-69036-cy9pch/tests/bin/fileops -s
    ↓
    Filename: /private/tmp/vifm-20241027-69036-cy9pch/tests/bin/fileops
    CMD: /private/tmp/vifm-20241027-69036-cy9pch/tests/bin/fileops -s
    ↓
    Filename: /bin/bash
    CMD: /bin/sh -c chmod  u+s /private/tmp/vifm-20241027-69036-cy9pch/tests/sandbox/fileops/file
    Investiagation:
    An alert was triggered due regarding a process has modified the permissions or attributes of a file.
    By inspecting the above-mentioned process tree.
    chmod u+s: The chmod command changes file permissions, and u+s sets the setuid bit for the user.
    This means when the file is executed, it will run with the permissions of the file’s owner, regardless of who executes it.
    By setting the setuid bit, it allows any user who runs this file to execute it with the privileges of the file’s owner.

Now, I realize that this is not some sort of "bad behavior". I just would like to know if this test (or maybe all of the tests) may be skipped during compilation, so I would either make a custom Homebrew formula or replace it with shell script.
Thank you in advance

**Comment by xaizek** [comment]
Hi,

It probably comes from this test (suid is index 3 and sgid is index 7 there) https://github.com/vifm/vifm/blob/8499457ead5a7a0cfcb4b5c43441975c2208c81d/tests/fileops/chmod.c#L48

Tests aren't run on build automatically, brew's formula [does it](https://github.com/Homebrew/homebrew-core/blob/503e4ec8d90b3b5eaad6d7a8b4451db32ee56b6f/Formula/v/vifm.rb#L33).  Either remove/comment-out that line or apply the patch to skip toggling that bit, brew has some way to apply patches.  Changing that line to `TEST(every_permission_can_be_reset, IF(windows))` will make it not run on MacOS :)  Could also explicitly list test suits omitting `fileops`, but dropping `make check` is the simplest.

**Comment by igorepst** [comment]
Great. I will probably just skip all the tests, as this is the way it works on my ArchLinux PC: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vifm-git
Thank you, @xaizek!
