### ISSUE TITLE
On Windows, cmd.exe is still the shell for term() and system() calls, even if shell has been set to something else.

### ISSUE THREAD

**Issue by spence91** [vifm/vifm#1033]
Hi - 

I'm trying to run fzf through a `term()` command, which I think is a fairly common use pattern. It works well, except if I'm on a UNC path. Then I see errors. The error message is weird it's as follows:

example:

```
cd /UNCPATH/dir1
: echo term('path\to\fzf.exe')
```

I will see this returned:

```
'\\UNCPATH\\dir1'

CMD.EXE was started with the above path as the current directory.
UNC paths are not supported. Defaulting to windows directory.
Press ENTER or type command to continue
```

I see this *regardless of what shell I have set*. (although, I have only tried powershell). Is this expected? I would have thought that setting shell would mean that `term()` cmds would be run via the set shell?

**Comment by xaizek** [comment]
Hello,

This looks like a bug.  `term()` and `system()` use the value of `'shell'` on non-Windows systems.  Thanks for the report.
