### ISSUE TITLE
`[S` and `]S` to complement `[s` and `]s`

### ISSUE THREAD

**Issue by aksr** [vifm/vifm#1038]
If directory has many files, if some are selected (via `:select` etc.) and the current visible part of directory doesn't have any selected file(s), searching for *next* selected file is usually with `]s` and if that doesn't succeeded, next it `[s`.  We do this usually to deselect some entries or something similar.

There is a way, for "go to next selected entry" to always succeeded (if some files are selected), and that's if *wrapping* is enabled.

I think it would be useful for `[s` and `]s` to have their "wrapped" counterparts `[S` and `]S`.

**Comment by xaizek** [comment]
A complement of finding next/previous selected entry would be finding next/previous entry that's not selected.  I guess you're comparing <kbd>[s</kbd> to <kbd>[r</kbd>/<kbd>[R</kbd> pair.

Do you need to use both variants (wrapping/non-wrapping) at the same time or wrapping is the behaviour you always want to have?
