### ISSUE TITLE
Tabs aren't restored on startup if `tabscope` is set twice (differently) in vifmrc

### ISSUE THREAD

**Issue by aksr** [vifm/vifm#1039]
We have this in `vifmrc`:
1. `set vifminfo=tabs...`
2. `set tabscope=pane`
3. `set tabscope=global`

(`tabscope` is **set twice differently** in vifmrc)

After that we execute inside `vifm`:
1. `:write`
2. `:wqall`
3. Then we start `vifm` again...

Tabs aren't restored.

Not sure if this could be fixed, or if it could be considered bug at all, 
since `vifm` when started again reads the first setting first (and we don't have at that moment `pane` tabs).

**Comment by xaizek** [comment]
> Not sure if this could be fixed, or if it could be considered bug at all,
> since `vifm` when started again reads the first setting first (and we don't have at that moment `pane` tabs).

Right, this isn't a bug, tabs are restored, but you're clearing them by toggling the scope.
