### ISSUE TITLE
vifm scripting - pass function output to shell script

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#104]
Hello again @xaizek,
could you please correct me if I'm wrong but following command should work, right?

````bash
:execute '!script.sh' layoutis('split')
````
I'm sure that couple of days back, when I tried just to echo first script's argument, everything went correctly.
Now it does not actually run the script.sh. And after I run the above command and try to quit `vifm` via `ZZ`, "file pointer" jumps to random file and I have to press quit shorcut couple of times until vifm is exited...

**Comment by xaizek** [comment]
Hi,

The command should work and the following works for me:
```vim
:execute '!echo%S' layoutis('split')
```

What does the script do? It looks like it spawns second (and maybe more) instance of vifm and you end up exiting them one by one.

**Comment by fogine** [comment]
>What does the script do? It looks like it spawns second (and maybe more) instance of vifm and you end up exiting them one by one.

For testing purpose it just save first argument to file.

````bash
echo "$1" > $HOME/vifmtest
````

nothing more..

**Comment by fogine** [comment]
Ok, It's more difficult than I expected. It doesn't work  on the computer where it has worked today at morning neither. The issue described above is caused by one of the following packages:

`(autotools-dev)`
`(libgit2-dev)`
**`libxdo-dev`**
**`xdotool`**
`gobject-introspection`
[`json-glib`](https://launchpad.net/ubuntu/vivid/+source/json-glib)
[`i3ipc-GLib`](https://github.com/acrisci/i3ipc-glib)

I'm mentioning the list of packages in case you would know which package may possibly cause the problem.
I've installed those packages today on the computer in order to use `libxdo` from within `xdotool` for managing "system windows". Unfortunately I've installed the most of the packages from source so it will be difficult to find out which package is causing the problem... I'll probably try to reproduce the issue in `virualbox`.

**Comment by xaizek** [comment]
Hm, this sounds strange. Maybe try reconfiguring vifm with `--without-gtk --without-X11` options and see if the issue disappears. It's quite hard to imaging how any of those packages are related to executing of a command (unless they somehow affect shell).

**Comment by fogine** [comment]
Oh, so here's the situation. I created `$VIFM/scripts` directory a week ago without knowing that `vifm` knows about the directory... and that it's actually added to `path`... I added there vifm related scripts and later when I wanted to simply execute scripts without full path to the scripts directory, I copied scripts to local bin folder (I didn't know that the "scripts" directory is actually in vifm's path at that time)...
The problem was that  in the "scripts" directory there was remaining old version of the script file which vifm kept triggering...

note: I think whole problem was initiated by the fact that there was no "$VIFM/scripts" directory created at vifm installation point, so I supposed that vifm doesn't use it. I would have to read (and remember) all the documentation for vifm so I could know that it's actually used. Could I propose for automatic creation of the directory at installation process?

I'm sorry for the false alarm @xaizek and thank you for support.

**Comment by xaizek** [comment]
> Could I propose for automatic creation of the directory at installation process?

That makes sense to avoid possible confusion, I didn't think that it will conflict this way. Although, not during installation, but probably on automatic `.vifm/` directory creation on the first run. We could create it on every startup if it's not there, but I wonder whether this will annoy people who doesn't use it and don't want to see it.

**Comment by fogine** [comment]
>but I wonder whether this will annoy people who doesn't use it and don't want to see it.

I think most of applications including eg. `atom` are doing it that way (they are not `TUI` apps though)... I would not be doubtful, although it also makes sense to create `.vifm/` only once on the first run in this case and let people decide what they'll do with it...

the `scripts` directory could contain short readme file saying that files in the directory are included in vifm PATH ...

**Comment by xaizek** [comment]
> I think most of applications including eg. atom are doing it that way (they are not TUI apps though)...

And then there is a bunch of empty sub-trees in configuration directories... While removing all those I always wonder why do they create unused directories.

> the scripts directory could contain short readme file saying that files in the directory are included in vifm's PATH or it could contain reference to the section of documentation.

This could justify creation, thanks. I have also remembered that `.vifm/colors/` is created if it doesn't exist, so doing the same with `.vifm/scripts` would be consistent (or behaviour must be changed for `.vifm/colors` as well).

**Comment by xaizek** [comment]
Now `scripts` are created automatically with a readme file, which then can be removed (only created on directory creation, just like `colors` and `colors/Default`).

**Comment by fogine** [comment]
Awesome! Thanks. I'll test it as soon as possible.
