### ISSUE TITLE
possibly a bug with mounting exfat drives

### ISSUE THREAD

**Issue by Shoxx98** [vifm/vifm#1040]
During setup of a new arch install today, I found mounting exfat drives with :media to not be working anymore.
I get the error: 
```
devmon: /usr/bin/udevil --mount /dev/sdc1 --mount-options "noexec,nosuid,nodev,noatime"    # (Ventoy)
fuse: unknown option(s): `-o nonempty'
```
I am pretty sure this is just a setup issue, since I have a cachyos install and it somehow works there. However, fuse seems to not understand this option since version 3: https://gitlab.com/BuildStream/buildstream/-/issues/860. Are there any well known workarounds for this or am I just doing something wrong that I have not read up on yet?

Using fuse2 and exfatprogs, I still get an issue:
```
devmon: /usr/bin/udevil --mount /dev/sdc1 --mount-options "noexec,nosuid,nodev,noatime"    # (Ventoy)
mount: /media/Ventoy: fsconfig system call failed: exfat: Unknown parameter 'nonempty'.
       dmesg(1) may have more information after failed mount system call.
devmon: error mounting /dev/sdc1 (32)
```

**Comment by xaizek** [comment]
I think you want to edit `/etc/udevil/udevil.conf` which in my case has this line that includes `nonempty`:
```
default_options_exfat     = nosuid, noexec, nodev, noatime, umask=0077, uid=$UID, gid=$GID, iocharset=utf8, namecase=0, nonempty
```

**Comment by Shoxx98** [comment]
I think those are the default options - I have them too.

`default_options_exfat     = nosuid, noexec, nodev, noatime, umask=0077, uid=$UID, gid=$GID, iocharset=utf8, namecase=0, nonempty`

**Comment by Shoxx98** [comment]
I also added nonempty to the default options right now and that did not help. I did not restart my pc for that though.

**Comment by xaizek** [comment]
> I also added nonempty to the default options right now [...]

Vifm doesn't specify any options, so those are the options used for mounting.  I meant that you want to remove `nonempty` from the line.

**Comment by Shoxx98** [comment]
thank you very much, that was the solution
