### ISSUE TITLE
File names passed as flags

### ISSUE THREAD

**Issue by Kobaxidze256** [vifm/vifm#1042]
```
if executable('vim')
    set vicmd=vim
elseif executable('nvim')
    set vicmd=nvim
elseif executable('elvis')
    set vicmd=elvis\ -G\ termcap
elseif executable('vile')
    set vicmd=vile
elseif $EDITOR != ''
    echo 'Note: using `'.$EDITOR.'` as an editor'
    let &vicmd = $EDITOR
endif
```
Why aren't commands delimited by `--`...
I bet this leads to command execution when opening files with malicious names, but I don't care enough to check.

**Comment by xaizek** [comment]
No need for `--` if relative paths don't have `-` as their first character (`-bla` becomes `./-bla`).  If you add `--`, you won't gain anything but break use cases when Vifm appends options (e.g., for `:help` with `'vimhelp'` set).

**Comment by Kobaxidze256** [comment]
> No need for `--` if relative paths don't have `-` as their first character (`-bla` becomes `./-bla`). If you add `--`, you won't gain anything but break use cases when Vifm appends options (e.g., for `:help` with `'vimhelp'` set).

Maybe what you said is correct, but it's wrong to act like nothing can be done about it. This is bad behavior.

**Comment by xaizek** [comment]
> `-bla` becomes `./-bla`

This is what Vifm already does, which is why such names cause no problems.  You didn't check, so you don't know that there is no issue to fix :)

**Comment by Kobaxidze256** [comment]
Huh. I remember something breaking, but not exactly what.
