### ISSUE TITLE
Getting entries under the cursor in key mapping commands

### ISSUE THREAD

**Issue by Shamaoke** [vifm/vifm#1045]
Hi. 

I want to create a keybinding by which the Vim editor will be opened, allowing to edit the entry/entries under the cursor. The command should look like the following: `nmap ,r :rename ENTRIES<CR>`. But I don't know how to access the `ENTRIES` under the cursor in the command. Is there any means in Vifm to accomplish the task?

Thanks.

**Comment by haolian9** [comment]
maybe `expand('%f')`?

**Comment by xaizek** [comment]
Hello,

`:rename` processes the selection by default, you don't need to specify list of names for it, although maybe you mean something different by "entries under the cursor" (what?).

> maybe expand('%f')?

Yes, maybe something like this, possibly with a different macro(s):
```vim
nnoremap <silent> ,r :rename <c-r>=expand('%f')<cr><cr>
```

**Comment by Shamaoke** [comment]
By “entries under the cursor” I meant the highlighted file or directory in normal mode or selected files or directories in visual mode. But yes, I realized that there's no need for arguments for `:rename`. So, the key mapping should look like the following.

````
""" Rename selected entries
noremap <silent> ,r :rename<CR>
""" This is the same as...
""" nmap <silent> ,r :rename<CR>
""" vmap <silent> ,r :rename<CR>
```` 

However, I would still like to know how to pass the currently highlighted/selected entries (files or directories) as arguments to a command in keyboard mappings. This could be used for modifying entries in the current directory, preserving a part of their names. E. g.

````
""" Add a leading dot (`.`) to the currently highlighted/selected entries
noremap ,d :rename .ENTRIES<CR>
````

If it's possible, what should be added instead of the `ENTRIES` placeholder?

**Comment by xaizek** [comment]
> If it's possible, what should be added instead of the `ENTRIES` placeholder?

```vim
""" Add a leading dot (`.`) to the currently highlighted/selected entries
noremap ,d :rename <c-r>=expand('%f:gs/^/./')<cr><CR>
```

Although running `:s/^/.` would be simpler.

**Comment by Shamaoke** [comment]
@xaizek @haolian9 Thank you.
