### ISSUE TITLE
command line request

### ISSUE THREAD

**Issue by coachshea** [vifm/vifm#105]
First, thanks for the unbelievable product, and when I've needed assistance (despite your very detailed documentation) you have been very prompt and helpful. 
What I would like to see is the command line, when running external commands, be integrated with the underlying shell/emulator. What I mean is if I called vifm from urxvt/zsh, it would be great if I had my aliases present, instead of everything running as a login shell. Ideally, this could be incorporated with tab completion (zsh in particular has amazing tab completion). I don't know how difficult this might be, or even if it's possible. But I do know that this is a frequent complaint of users when running any program that has a command line function (vim, mutt, vimperator). This type of integration would really separate vifm from all other programs. Thanks for your consideration.

**Comment by xaizek** [comment]
What I can offer you right now:

* [hack for bash and aliases](https://github.com/vifm/vifm/blob/master/FAQ#L126-L142);
* [an old script that exports aliases and functions as scripts](https://gist.github.com/xaizek/79770cfe47da21a65fbe); if you run it pointing at shell config and then move files from `out/` to `~/.vifm/scripts/auto` (`auto` subdirectory is just to keep them separated), you should be able to run commands and complete them (note that it created fork bomb for me once or twice and it still might, not sure it was fixed completely). I didn't use it much, but it was written to make aliases and functions available outside shell, it's far from being perfect.

A different approach would be to add `'shellcmdflag'` option and you could run shell in interactive mode (currently it's run in normal/batch mode, not login mode) by adding `-i`. If there would be a way to specify custom completion function, it would be possible to complete aliases/functions.

Tighter integration is hard to achieve, gluing two standalone applications that are meant to run on their own isn't easy, and shells don't provide embedding interface.

**Comment by coachshea** [comment]
Thank you once again for your prompt and informative response. I will
definitely explore those options. As for the integration, I feared that
would be an issue, but hoped I was wrong. Thank you for your time and
consideration.

**Comment by xaizek** [comment]
Did you close this by mistake? I gave it a thought, but couldn't come up with a working solution so far. Running shell in interactive mode causes various undesirable effects, proper solution seems to require some kind of cooperation between shell and vifm.

**Comment by coachshea** [comment]
No, it wasn't a mistake. I appreciate your efforts and your suggestions, but it
seemed to me that this was a near-impossible idea. I still think it would be a
great feature, but if it can't be done, I didn't want to indefinitely leave open
a hopeless suggestion. We could certainly reopen it if you think it would be
worthwhile.

**Comment by xaizek** [comment]
OK then, I have it tracked locally anyway, but can't really give prognosis of when and how it can be implemented. For now the most viable options seem to be reusing parsing code from bash and zsh in form of plugins or contributing missing functionality (external completion and alias/function execution) to the shells, both of which are nontrivial and require investigation.
