### ISSUE TITLE
Unable to create FUSE mount directory

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#112]
Hello,

When there is an error during establishing a connection to remote server through ssh (e.g: wrong password provided), it's not possible to try connect again because of the error message:
```
"Unable to create FUSE mount directory" - /tmp/vifm_FUSE/001_settings.ssh
```

So far, only machine restart will solve the issue. Do you have any ideas how to solve the issue?

**Comment by xaizek** [comment]
Hello,

could you try `more-robust-fuse-dir-creation` branch? I couldn't reproduce the issue, but imagine that system reported that path doesn't exist for one system call, but said the opposite for the other, which can happen with mounts. New code should be more robust and work as expected.

sshfs mounter probably leaves directory in wrong state, you could try to force unmount, but in practice this shouldn't be a problem if you reboot sometimes (and those broken mountpoints drop).

**Comment by fogine** [comment]
Looks like it's fixed on that branch. It's possible to try connect again if previous connection attempt failed...
Thank you!

**Comment by xaizek** [comment]
Great, pushed to `master`, thanks for testing and reporting!
