### ISSUE TITLE
Cygwin installation error: ./configure - '\r' Command not found

### ISSUE THREAD

**Issue by LoLei** [vifm/vifm#114]
````
$ ./configure
./configure: Line 16: $'\r': Command not found.
./configure: Line 31: Syntax error near unexpected word `newline'
'/configure: Line 31: `     ;;
````

OS: Windows 7 64bit Cygwin
Terminal Emulator: ConEmu

I realize `\r` is probably carriage return, but why would this error occur? Seems like the file can't be parsed correctly.

Am I missing something?

**Comment by xaizek** [comment]
Your git settings seem to cause files to be checked out with CRLF line endings, while Cygwin expects them to be LF.

I confuse which settings change what (too many with overlapping meaning), but looking at `git config --list | grep crlf` might be a start. You can then change configuration in your clone and do `rm -r * && git reset --hard` to update line endings in all files. I guess you have `core.autocrlf` set to `true`, change that to `input` with `git config core.autocrlf input` and do update with the command from previous sentence, but be careful to do not remove something outside repository.

**Comment by LoLei** [comment]
Thank you, I will try these solutions tomorrow.

**Comment by LoLei** [comment]
On second thought, I'd rather not change these settings since this is on my work computer, but thank you for your effort!

**Comment by xaizek** [comment]
The settings will be local to the repository, by default `git config` operates locally and it needs `--global` flag to change global configuration, so it won't mess anything as long as you run commands after cd'ing to the repository.

**Comment by LoLei** [comment]
I did not know that, thanks. I might come back to it at some point, if I do I'll let you know.
