### ISSUE TITLE
vifm and emacs(client)

### ISSUE THREAD

**Issue by dennishamester** [vifm/vifm#116]
I use Emacs and have set `vicmd` to start `emacsclient -nw` to connect to my running Emacs daemon. However, every time I want to edit a file, I get an error from emacsclient:

    *ERROR*: Could not open file: /dev/tty

The second time I try it, it actually crashes my Emacs daemon. A regular `emacs -nw` (no daemon) works though.

I tried digging through your code and see how you start the `vicmd`. Couldn't find anything weird though.

The problem might very well be with Emacs. But since vifm is the only program with which I encountered the problem so far, I wanted to ask here first. So for example, I can start `emacsclient` through other terminal programs just fine, like ranger. Is there anything you could think that might cause this? Maybe ncurses related?

**Comment by xaizek** [comment]
> Is there anything you could think that might cause this? Maybe ncurses related?

This seems to be side effect of #79, or more specifically [this line](https://github.com/vifm/vifm/commit/fcfca76e794df420fb5141e4166bd16026bcc908#diff-b4e786d6df80b61451f7f0933579c79eR745). This causes differences in the output of `strace emacsclient -nw ...`. When original `stdout` refers to `/dev/pts/...`, opening `/dev/tty` doesn't seem to be equivalent from the point of view of `emacsclient`, which then tries to open terminal used by emacs server process, which is probably not available in your case, which leads to the error (if I keep the terminal open then client opens emacs there).

Not sure what's really going on here and how to fix it properly (not reopening terminal when we don't need this won't solve the case when vifm is run like `vifm --chose-files - > files`), but I'll try to figure it out.

Thanks for the report!

**Comment by dennishamester** [comment]
Thanks! I now understand the problem somewhat better. I guess, emacsclient sees that STDOUT (/proc/self/fd/1) is redirected to /dev/tty and tells the daemon to open that one, which obviously fails for the daemon if it has to terminal.

Imo, the solution should be not to redirect to `/dev/tty` but to the corresponding `/dev/pts` entry, which can be used across processes (emacs daemon). I tried this and it works.

That leaves the question on finding out the controlling terminal. There does not seem to be generic working solution. See [here](http://unix.stackexchange.com/questions/187319/how-to-get-the-real-name-of-the-controlling-terminal) for some more information. [ctermid](http://pubs.opengroup.org/onlinepubs/009695399/functions/ctermid.html) in glibc returns always `/dev/tty`. [ttyname](http://pubs.opengroup.org/onlinepubs/009695399/functions/ttyname.html) requires a fd which might be redirected and thus not a terminal.

The sanest solution might be to query the terminal of STDIN with `ttyname` and fallback to `/dev/tty`. What do you think? I can hack together a quick patch if you want to try it out.

**Comment by dennishamester** [comment]
I wrote a quick patch, please have a look and let me know what you think. The patch does not touch Windows specific code, because I have no idea if it is affected too.

**Comment by xaizek** [comment]
Thanks for the information and the patch!

> The sanest solution might be to query the terminal of STDIN with ttyname and fallback to /dev/tty. What do you think?

STDIN might be redirected as well, so I changed the code to check for all three standard handles.
It won't help in this case:
```
ls | vifm --choose-files - - 2> ~/error >| ~/list
```
But it's unlikely that one would do something like this.

> The patch does not touch Windows specific code, because I have no idea if it is affected too.

Windows shouldn't be affected, there are no such paths, only handles basically.

**Comment by dennishamester** [comment]
Great to see this fixed. I can finally switch to vifm now :)
