### ISSUE TITLE
display of move and copy operation is gone

### ISSUE THREAD

**Issue by reicheltd** [vifm/vifm#117]
Hi xaizek,

since the latest releases, whenever I copy or move some large file(s), there isnt any indication in the status bar anymore that something is in progress. There used to be a rotating `|` icon.

Only at the end there is "xxx files successfully processed". Running OS X 10.10.5.

Best regards,
Daniel

**Comment by xaizek** [comment]
Hi Daniel,

should work as before. With `'syscalls'` on it's hard to notice the missing messages.

Thanks,
xaizek

**Comment by reicheltd** [comment]
Thx! Works again!
