### ISSUE TITLE
Renaming files not work with neovim

### ISSUE THREAD

**Issue by kazufukurou** [vifm/vifm#118]
In .vifmrc:
```
set vicmd=nvim
```
When tried to rename multiple files got:
```
nvim: Unknown option argument: "--nofork"
```
Is there a workaround or is it a neovim issue?

**Comment by xaizek** [comment]
I've changed `--nofork` to `-f`, it's just that `--nofork` is far more readable. Now both Vim and nvim should work.

> Is there a workaround

For release version one would need a wrapper script that changes `--nofork` to `-f`.

> is it a neovim issue?

I'd call it a general issue with their approach to remove things that are in use.
I won't be surprised if there are other incompatibilities, which might require different handling.

Thanks for the report!

**Comment by xaizek** [comment]
To mention it here as well: #651 was done couple months ago, so editor-specific options can be handled more gracefully now via Lua plugins.
