### ISSUE TITLE
copying files isn't preserving date timestamps with syscalls

### ISSUE THREAD

**Issue by mvucBmM0** [vifm/vifm#121]
When syscalls setting in on, copying files will not preserve date timestamps.
Not sure if this was intended. I have to turn off syscalls for now.

**Comment by xaizek** [comment]
I realized this afterwards, but wasn't sure if it matters much. If preserving timestamps is important in some use cases, I'll add them, it's not hard. Thanks for bringing this up.

**Comment by mvucBmM0** [comment]
I would appreciate if you would. Thanks.

**Comment by mvucBmM0** [comment]
Thanks for fixing it.
Just one minor note. When doing a background copy with ":copy &", have to ":redraw" for the status to show the real timestamp and size.

**Comment by xaizek** [comment]
<kbd>Ctrl+L</kbd> is quicker than `:redraw`. Can't do much about outdated metadata without using inotify and alike, currently directory timestamp is used to check for updates and it's not updated if files are changed, only if file list is changed. Need to try using inotify.

**Comment by xaizek** [comment]
> When doing a background copy with ":copy &", have to ":redraw" for the status to show the real timestamp and size.

Not updating metadata was bugging me for a while (for example, when you compile something, it can show up as zero sized non executable), so I gave inotify a try. I seems to work nicely, so metadata should be updated just fine at least on GNU/Linux now.

inotify is not utilized as much as it can be (updating only files that were actually changed), that is harder to do right, but file list should reflect state of files more accurately now.

**Comment by mvucBmM0** [comment]
Tested it and it seems to be working so far.
But now i'm getting segfault everytime i change to :only, restart vifm amd tab to the other pane. Not sure if related with this particular commit.

**Comment by xaizek** [comment]
It was related, although didn't appear with my configuration. Works now. Thanks.

**Comment by mvucBmM0** [comment]
Damn, you work fast. Thanks.
