### ISSUE TITLE
using dd without temp dir / adding "put" command

### ISSUE THREAD

**Issue by mvucBmM0** [vifm/vifm#122]
vifm uses the trashdir to pull files from when doing a dd/p. But this is too dangerous and unintuitive imho.
Would it be possible to add an option to simply use a register like with yy, and not using the trash dir at all? (Like it works in ranger)
example:
Press dd and the file is marked to be put. press yy and the file is put. No deleting or temp dirs used.
I know about the yy/P but i guess i'm just to used to using dd/pp.
Maybe also add a 'put' command so we can use it in other mappings.

**Comment by xaizek** [comment]
Actually current behaviour is closer to what Vim does, simply marking file when you do command that clearly says "delete" would be weird, the same for putting file on "yank" command. I don't see reasons to provide this, <kbd>dd</kbd> acts like a shortcut to `:delete` and thus it should "delete".

I thought that you could use `:nnoremap d y`, but it doesn't seem to work, if that's changed you won't need anything else to achieve desired behaviour. I'll look into this, I expected it to work.

As for `:put`, you can use `:normal p` for now, I wanted to add `:put`, but didn't decide on its syntax (I wanted to make it possible to provide new names for files, if I recall correctly).

**Comment by mvucBmM0** [comment]
I understand what you're saying by wanting dd to always delete (like in vim) and not just cut, i guess i'm just too used to ranger's way of doing it... I still think that for a file manager a true cut and paste is better than having the file first 'deleted' and then moved from the trash dir, just to move a file, but i guess i can live with yy/P for that.
Thanks for the :normal p tip, i didn't thought of that at all.
And thanks for the great work. Best file manager there is, no doubt.

**Comment by xaizek** [comment]
I was quite surprised with `dd` at first too and actually mainly use `yy` + `p`/`P` till today, but most users with Vim background seem to find such behaviour quite natural and there isn't many counter arguments, in fact this is more flexible as you can postpone insertion indefinitely, possibly even after removing original directory with source files. And once `:nnoremap d y` remapping works, you will be able to use that, `:nnoremap dd yy` works fine now, and I believe this is the most popular form of the command (you might want to remap `d` in visual mode as well).

**Comment by mvucBmM0** [comment]
I actually remapped dd to <nop> but i guess i will remap it to yy.

As a further related question (not sure if should open new issue but here goes)
I was trying to use the :normal p you tipped me previously to remap putting files like this: "nnoremap p :normal p &" so that the copying or moving would be done in the background (so that copying or moving big files or folders don't freeze vifm) but it does not seem to work. Any way of doing this any other way?

**Comment by xaizek** [comment]
` &` doesn't apply to `:normal`, so it won't work. This is actually a very strong point for adding `:put`, I don't think you can achieve background "putting" files at the moment. Thanks, I missed this.

**Comment by mvucBmM0** [comment]
I will wait for the addition of "put" then. Thanks again for your great work.

**Comment by mvucBmM0** [comment]
Awesome, thanks.

**Comment by xaizek** [comment]
The issue with remapping is fixed now, so you can use:

    nnoremap dd yy
    nnoremap d y

The first command is needed because <kbd>dd</kbd> is a separate mapping, which just overlaps with the second one.

**Comment by mvucBmM0** [comment]
Already did, as well as
```
vnoremap d y
nnoremap p :put & <cr>
nnoremap P :put! & <cr>
```
Thanks again.
