### ISSUE TITLE
multiple buffers and multiple panes

### ISSUE THREAD

**Issue by mvucBmM0** [vifm/vifm#123]
Are there any plans of adding multiple buffers in the future or do you want to just keep it dual-pane only?
And what about multiple panes?

**Comment by xaizek** [comment]
Tabs are likely to be added. Not sure about buffers, i.e. unclear what's the purpose, just to save state of selection/search/etc.?

Multiple panes create a set of issues with source/target definition for operations on command-line as well as for preview (which pane to use). Without clear idea of how to handle such cases, it's not worth trying to add this. This would include at least window identifiers, syntax to specify target window (assuming current one to be the source), reasonable defaults, something for preview, handling of macros (`%C`, `%D`, etc.). And I'm not sure I'm aware of any use cases where multiple windows provide advantages over two panes to be able to figure out how to work with them in practice.

**Comment by mvucBmM0** [comment]
To me tabs or buffers are mostly the same thing, so i'm glad you're considering adding it in the future.
But by buffers i meant, say now you're in :only mode. And you cicle through both buffers with tab. What i was asking was to be able to have more buffers to cycle through.

As for panes. Well, someone who would use more than two panes would obviously not be able to use the source/target operations like copy/move (at least in a pratical way) but would just use yank/put.
It's not something i'd say is that important like tabs/buffers, it's just a sometimes useful convenience for showing all the tabs/buffers at once.

**Comment by xaizek** [comment]
By the way, if you didn't notice, there is [`:dirs`](http://vifm.info/vimdoc.shtml#vifm-%3Adirs) command (along with [`:pushd`](http://vifm.info/vimdoc.shtml#vifm-%3Apushd) and [`:popd`](http://vifm.info/vimdoc.shtml#vifm-%3Apopd)), which was added for similar purpose of working in several locations, but it stores only paths of the views.

**Comment by mvucBmM0** [comment]
If i'm not mistaken, that works like a kind of dual ":marks" i guess. Can't say i have used it yet to be honest.

**Comment by rr-** [comment]
+1 for tabs.

**Comment by Q3CPMA** [comment]
I'm also excited for this. That's probably the only thing I need before switching from ranger (which is quite heavy and can be buggy).

**Comment by xaizek** [comment]
Finally, initial version of tabs is in the `master` branch.

As usually, instead of implementing the whole set of commands present in Vim only the necessary are implemented, others can be added if there is a need.

Specifically, the following things were added:
 * `TabLine`, `TabLineSel` highlight groups.
 * `:qa[ll]`, `:wqa[ll]` and `:xa[ll]` commands.
 * `:tabnew`, `:tabname`, `:tabc[lose]`.
 * <kbd>gt</kbd> and <kbd>gT</kbd> normal mode keys.
 * `'showtabline'` and `'tabscope'` options.

There are actually two kinds of tabs, so if instead of Vim-like tabs that contain layout of windows you prefer pane-specific tabs, they are also there with `set tabscope=pane` (@cosminadrianpopescu).

**Comment by cosminadrianpopescu** [comment]
Wow, this is really wonderful news. I will compile and give you a feedback. 

Thank you for the work.

**Comment by cosminadrianpopescu** [comment]
Absolutely beautiful. Now I can stop crying about MC. It' the last piece of the puzzle. I've tested a little bit at home and is very nice. I will begin working with the options from tomorrow professionally at work. I was thinking that maybe the `tabnew` should take 2 parameters (also the new tab folder) and I would also see a `tabnext` command which would take as an argument the number of the tab to go to. What do you think. I offer to develop the 2 new additions if that's ok with you.

**Comment by xaizek** [comment]
Thanks for the feedback.

> maybe the tabnew should take 2 parameters (also the new tab folder)

Don't know what order you're thinking about, but maybe name should be the second as one is probably more likely to open an unnamed tab in a new directory than a named tab in the same directory.

> What do you think. I offer to develop the 2 new additions if that's ok with you.

Sounds good to me. I'll be happy to receive patches :)

**Comment by cosminadrianpopescu** [comment]
I've just noticed an essential feature missing from the tabs. It doesn't save the tabs configuration in the `vifminfo`. I would actually like to start with this option. What do you think?

**Comment by cosminadrianpopescu** [comment]
Also, a small problem (a null pointer exception) when trying to set the `showtabeline` to `always` in `cygwin 64`. This is the dump stack trace:

```
Exception: STATUS_INTEGER_DIVIDE_BY_ZERO at rip=0010043A885
rax=000000000000004D rbx=0000000100485640 rcx=0000000000000000
rdx=0000000000000000 rsi=000000000000004D rdi=000000000000000B
r8 =000000060030E480 r9 =000000060030E480 r10=0000000000230000
r11=000000010043A5D8 r12=000000060030E470 r13=0000000000000001
r14=000000000022B4B0 r15=000000000022B500
rbp=000000000022B520 rsp=000000000022B490
program=C:\Pgm\my\cygwin64\usr\local\bin\vifm.exe, pid 16564, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
0000022B520  0010043A885 (001803400A8, 0000022B590, 00100440BE0, 007000000EA)
00100440BE0  0010043AB7E (00100432AC3, 006001154F0, 0000000000B, 00000000056)
00000000000  0010043348E (00100438C39, 001004DAC80, 00100439C49, 001004E2340)
00000000000  0010043342D (00000000000, 0000000005B, 00000000000, 001004E2340)
00000000000  001004398BA (00000000001, 000000000B4, 006001154F0, 00000000000)
00000000000  0010043B2A5 (0010049C150, 000000000D3, 00000000000, 00000000000)
0060014CD10  001004267E8 (00100485650, 0010044391C, 000000002BC, 00000000001)
0060014CD10  00100454979 (0000022B8A0, 00000000058, 00010000000, FFFFFFF10000000A)
0060014CD10  00100454E68 (00000000000, 00000000000, 00000000000, 00000000000)
0000022BA80  00100479D16 (0000022CCF0, 0000022CBC0, 00000000000, 00000000000)
0000022CBC0  0010047BA3A (00000000020, 30001000000FF00, 0018004839F, 0000022D680)
0000022CBC0  00180048410 (0000022CCC0, 0000022CCC0, 0000022CCC0, 00000000020)
00000000000  001800460DC (00000000002, 00000000002, 00077251020, 00000230000)
00000000000  00180046174 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  0010047B361 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00100401010 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)
```

**Comment by cosminadrianpopescu** [comment]
But the feature is amazing :+1: 

:)

**Comment by xaizek** [comment]
> Also, a small problem (a null pointer exception) when trying to set the showtabeline to always in cygwin 64.

Damn it, it worked fine, apparently until some last changes. Thanks.

> I've just noticed an essential feature missing from the tabs. It doesn't save the tabs configuration in the vifminfo.

It's missing  because it's a big part which I'm still not sure how to implement. The serialization is complicated, probably should support serialization of two levels of tabs and should consider #290 (although maybe we don't need to save this in `vifminfo`) and #275 to change format of `vifminfo` only once. Since tabs are useful without being saved to `vifminfo` as well, I chose to leave it for later.

If you want to give it a try, here are some notes on the subject:
```
* If vifminfo contains only a single tab and current state also contains a
  single tab, old behaviour should be preserved.

* Seems to be no sane way of merging tabs, so just don't do it and overwrite the
  old state if current instance or contents of `vifminfo` has more than one tab.

* "tui" and "state" of 'vifminfo' should also be part of tab state.

* Also need to encode current tab and current location (avoid hacks like in
  current implementation).

Possible structure (incomplete):

Tc<total number of tabs (all pane tabs, two global tabs = at least 4 pane tabs)>
TN<global tab name (might be empty)> # this begins new global tab
T[<pane tab name (might be empty)> # this begins new left pane tab
Td<escaped path>
Tf<escaped name>
	<relative position>
	<timestamp>

Example:

Tc2
TN
T[
T[d/home/xaizek/dev/projects/cxx11/uncov
T[dfCOPYING
	11
	1451205663
```

**Comment by mvucBmM0** [comment]
Can't believe i missed this (my monitoring script was mistakenly off...).
This is f*ing awesome.
Thanks so much for your work xaizek.
Binded gn to :tabnew, gt to <alt>, put on :only mode, and now i got infinite buffers :). So awesome.

**Comment by pdanc** [comment]
@xaizek I compiled the last version of vifm (source code from here). `vifm --version` ---> Version: 0.9.1. But when I type `:tabnew` ---> Invalid command name.
What am I doing wrong?

**Comment by xaizek** [comment]
Closing this as tabs are there now and restoring them from `vifminfo` is more about `vifminfo` than about tabs.

@pdanc, the beta for v0.10 is out now.

**Comment by ngriffin7a** [comment]
@xaizek I am a long time vifm user and I just found the `:newtab` feature today. I agree with @cosminadrianpopescu that persisting the tab layout would make tabs much much more useful. I would expect that when I execute `:wq` that it would write the state of all the tabs. I'd be very interested to know if you've made any progress towards persisting and restoring the tabs. Thank you for an amazing tool! :) -- Neil

**Comment by xaizek** [comment]
> I'd be very interested to know if you've made any progress towards persisting and restoring the tabs.

The feature is blocked by the format of `vifminfo` file. I did start moving it to TOML (if only as an experiment, although there aren't really many options), but can't say I got far with it.

**Comment by ngriffin7a** [comment]
@xaizek Thanks for the quick reply. +1 from me for persistence of the tabs. `vifm` rocks and I'm grateful to you for all the hard work. :-)

**Comment by xaizek** [comment]
Persistent tabs are available on the `master` branch now. Add `tabs` to `'vifminfo'` option to enable the feature.
