### ISSUE TITLE
Use matching string of a filter-like regexp as a sort key to group less regularly named files

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#128]
For example, you have these files:

```
1-done
2-todo-replace
3-done
4-todo-edit
5-todo-publish
10-bla-todo-edit
11-todo-publish
```

My proposal is a way to sort them by the part starting with "todo" or "done" (note the "10-bla" in one of the names), like this:

```
1-done
3-done
4-todo-edit
10-bla-todo-edit
5-todo-publish
11-todo-publish
2-todo-replace
```

For this, VIFM would accept a regexp like "-(done|todo).*" and use the match as the sort key.

**Comment by aleksejrs** [comment]
Bonus points if VIFM can load multiple sort modes from a file, and apply them sequentially without contradicting the previous sort keys (e.g., sort the files inside the *-publish, *-edit, and *-done groups by size).

**Comment by xaizek** [comment]
Interesting idea.

It shouldn't be hard to implement, although it will imply some slowdown of sorting.

Do I get it right that you want something like
```
" this might be comma-separated list of regular expressions
set sortgroups='-(done|todo).*'
```
?
Such groups would be applied as the top level keys during sorting and position of `name`/`iname` in `'sort'` would be irrelevant or maybe it would be more useful to do this as part of `name`/`iname` sorting? (I.e. should it always act like `<group sorting>,size,name,...` or such sorting might be useful as a key in the middle as well?)

Not sure about loading anything from a file, if new option is a local one, adding auto-commands should be enough (one would be able to do `source .sorting-keys` on entering directory). Auto-commands are not available yet though.
