### ISSUE TITLE
Custom view loses file names with colon characters (:)

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#129]
:touch a b a:b

then

    :.!ls a:b %u

or

    :find a:b

and press Enter on the `a:b` in the results (note that `a:b` is in the results!)

— find/list only `a` or whatever comes before the `:`.

**Comment by aleksejrs** [comment]
It's Vifm 0.8 from source code downloaded from http://vifm.info

**Comment by xaizek** [comment]
Right, it assumes that file names might be followed by line numbers, will add a heuristic for this. One will still be able to construct input that could be parsed in a wrong way, but it will be hard enough so that it shouldn't occur accidentally. Thanks for the report.
