### ISSUE TITLE
Unable to create FUSE mount directory: /tmp/vifm_FUSE/ is from a different user

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#130]
I don't understand how https://github.com/vifm/vifm/issues/112 is the same issue, so here it is (v0.8):

Vifm uses /tmp/vifm_FUSE/ for its mount directories, which is not a user-specific path, so Vifm started by other users cannot create FUSE mounts. It says:

```
Unable to create FUSE mount directory:
/tmp/vifm_FUSE//blabla.tar.gz
Press Return to continue
```

**Comment by xaizek** [comment]
Yes, that issue is about different thing. Looks like such permissions are used from the start, probably most people use only one account and don't ever see this. I'll change creation rights from `0700` to `0777` (as it's just a container for other directories, it's not a big deal), but it still can be affected by umask, so if you want to make this user-specific, set `'fusehome'` to something like:
```vim
set fusehome=~/.vifm/fuse-mounts
```
Or maybe it's better to make this new default location, such change shouldn't cause inconvenience to anyone unless I'm missing something.

Thanks for the report, this wasn't noticed for years.

**Comment by aleksejrs** [comment]
## 0777:
- bad: users can see each other's archive names (though maybe they can already, using process listing)
- bad: maybe they can cause race condition (though there is mktemp to create temporary files/directories avoiding it).

Both are almost solved if the directory names are hashes except for the user name and "vifm_FUSE".

Both are completely solved if the names are completely random (Is Vifm supposed to reuse the directories?  It deletes them right after exiting the mount anyway.).

Some lines from files in /usr/lib/mc:
```
TMPDIR=`mktemp -d "${MC_TMPDIR:-/tmp}/mctmpdir-uha.XXXXXX"` || exit 1
my $template = "/tmp/mcdebfs.run.XXXXXX";
setenv MC_PWD_FILE $TMPDIR/mc-$MC_USER/mc.pwd.$$
setenv MC_PWD_FILE /tmp/mc-$MC_USER/mc.pwd.$$
```

## Using something in ~:
+ good: less likely to run out of space.
+ good: likely no conflicts with other users possible.
+ good: there is at least ~/.cache for this.
- bad: slower.
- bad: more likely to pile up than be cleaned up automatically.

**Comment by xaizek** [comment]
> though maybe they can already, using process listing

That's the case.

> Is Vifm supposed to reuse the directories?

No, just don't mount something over something else.

> less likely to run out of space.

These are all mounts, so space is not an issue, only empty directory is created.

> good: there is at least ~/.cache for this.

Doesn't feel like right place for this, nothing is cached here, just mounted.

> bad: slower than tmpfs.

As it's about mounts, kernel only has to check path before the mount point, which should already be cached.

> bad: more likely to pile up than be cleaned up automatically.

Actually, this can be partially solved by trying to remove directory before creating it. Removal will succeed only for empty directories that are not mount points. Still can get multiple empty directories from several files, but this happen quire rarely, one probably has way more unused empty directories somewhere under `~/.config`. I think I'll change the default then.

Thank you for the analysis!

**Comment by aleksejrs** [comment]
FWIW, I like the ability to enter a mount without reunpacking/reconnecting.
