### ISSUE TITLE
Parent directory not moved during file move

### ISSUE THREAD

**Issue by willemw12** [vifm/vifm#131]
Parent destination directory is not created during file move.
    
For example, try to merge '11' ('a/11') into 'b/11':
    
    test
    ├── a    
    │   └── 11          
    │       └── 111     
    │           └── file1.txt
    └── b    
        └── 11
    
Result:
    
        ┌───────────────────────────────────────────────────── Background Process Error ──────────────────────────────────────────────────────┐        
        │                                                                                                                                     │        
        │ mv: cannot move ‘/home/willem/test/a/11/111/file1.txt’ to ‘/home/willem/test/b/11/111/file1.txt’: No such file or directory         │        
        │                                                                                                                                     │        
        │                                                      Press Return to continue                                                       │        
        └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘        
    
Expected:
    
Directory 'a/11/111' also to be moved into 'b/11'.
    
    test                                                                                                                                               
    ├── a
    └── b
        └── 11
            └── 111     
                └── file1.txt

**Comment by xaizek** [comment]
Thanks! Should be fixed now.

**Comment by willemw12** [comment]
Yes, it is fixed now. Thanks.

**Comment by willemw12** [comment]
"Fixed creation of intermediate directories on merging directories" is not completetly fixed. The file timestamps are not copied to the intermediate directories.

**Comment by xaizek** [comment]
> The file timestamps and the file permissions are not copied to the intermediate directories.

Should they be copied even if that directory existed before merging?

**Comment by willemw12** [comment]
Copying of timestamps and file permissions applies both to vifm move (can be viewed as a copy+delete acion) and vifm copy actions.

`cp -a` copies the file properties even when the files or folders exist. (Tested: copying newer files and folders. Both source and destination folders were not empty.)

**Comment by xaizek** [comment]
Thanks, should work like `cp` now.

**Comment by willemw12** [comment]
Yes, timestamps and file permissions are being copied now. Also file ownership is being copied. Thanks very much.
