### ISSUE TITLE
Support resume/reget/continue when a target file exists during copy/move.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#135]
This would be useful with protocols like FTP if curlftp supports it. Of course, it is also problematic if you don't check if the beginning is from that file (maybe check the first few bytes?).

MC calls it "reget". http://www.midnight-commander.org/ticket/2267
wget calls it "continue", curl calls it "continue/resume".

**Comment by xaizek** [comment]
Isn't it the same as `[o]verwrite`/`[a]ppend to the end`/`[s]kip` options in current dialog on <kbd>p</kbd>? Although you don't get this dialog on command-line commands like `:copy`, which perform all checks beforehand, so this behaviour might be worth changing in some way.

**Comment by aleksejrs** [comment]
(I don't know what `[a]ppend to the end` does: it is not in 0.8)

I mean adding option which skips the beginning of the source file the size of the target file, and only appends the rest.

Я имею в виду: добавить опцию, которая пропускает часть исходного файла в начале размером с существующий файл, и дописывает к существующему остальную часть исходного файла.

**Comment by xaizek** [comment]
> (I don't know what `[a]ppend to the end` does: it is not in 0.8)

It's available since 0.7.8, do <kbd>yyp</kbd> to see a dialog with it.

> I mean adding option which skips the beginning of the source file the size of the target file, and only appends the rest.

That's exactly how `[a]ppend to the end` operates.

**Comment by aleksejrs** [comment]
> - added "[a]ppend the end"… Available only if 'syscalls' option is set


> That's exactly how [a]ppend to the end operates.

OK, thanks. I understand only "resume" and "continue" exactly that way.

**Comment by xaizek** [comment]
> added "[a]ppend the end"… Available only if 'syscalls' option is set

Right, sorry, forget about this condition.
