### ISSUE TITLE
trashdir processes %r/.vifm-Trash without considering directory symlinks.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#136]
Vifm 0.8

If `/home` is on a separate partition from `/`,
`ln -s /home /linkhome`

* files cut from `/home` go into `/home/.vifm-Trash`
* files cut from `/linkhome` go into `/.vifm-Trash`

**Comment by xaizek** [comment]
Thanks, I haven't thought about paths that include symbolic links on file removal.
