### ISSUE TITLE
:autocmd DirExit (something like it)

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#140]
Today I used preview a lot for the first time.
I have a directory with a bunch of text files.

Now that there is `autocmd DirEntry`, I would try to use it with "`view!`", but there is nothing like "DirExit", so I can't get the preview mode to close when I exit that directory, and at the same time stay closed when I enter any other directory (*Or maybe I actually can, by specifying C-w z somehow, but I am not sure that would work in all cases.*).  I guess that "DirExit" would need to be not an event like `DirEntry`, but something like what Vifm does with FUSE mounts (I haven't thought of multiple panes using the same directory though).

**Comment by xaizek** [comment]
Not sure I understand all the details. You want to activate preview on entering a directory and deactivate it upon leaving it? Something like this can do that:
```
autocmd DirEnter ~/tmp view! | autocmd DirEnter !~/tmp autocmd! DirEnter !~/tmp | view
```
but it won't work in the beta (although current `master` is beta+fixes)... I've documented that `|` is taken as part of `:autocmd`, but forgot to mark the command appropriately.

With `DirLeave` event that would look a bit nicer.

> I guess that "DirExit" would need to be not an event like DirEntry, but something like what Vifm does with FUSE mounts

So still an event, but one that should be fired only when going to parent directory of specified path and if the other pane is not in the same subtree?

**Comment by aleksejrs** [comment]
> `autocmd DirEnter ~/tmp view! | autocmd DirEnter !~/tmp autocmd! DirEnter !~/tmp | view`

Seems like it would.

> So still an event, but one that should be fired only when going to parent directory of specified path

I meant that, so that it could keep the state for a subtree.

> and if the other pane is not in the same subtree?

That makes sense, although I may not have been thinking of it (it's too complex with preview to think about at night).

**Comment by aleksejrs** [comment]
`autocmd DirEnter ~/filtered view! | autocmd DirEnter !~/filtered autocmd! DirEnter !~/filtered | view`

doesn't close preview when I leave ~/filtered, and the exit autocmds pile up:

```
DirEnter   /home/fc/filtered
                      view! | autocmd DirEnter !~/filtered autocmd! DirEnter !~/filtered | view
DirEnter   !/home/fc/filtered
                      autocmd! DirEnter !~/filtered | view
DirEnter   !/home/fc/filtered
                      autocmd! DirEnter !~/filtered | view
```

**Comment by xaizek** [comment]
> doesn't close preview when I leave ~/filtered, and the exit autocmds pile up:

Right, I swapped last commands while trying something else and it broke. `view` should precede last `autocmd`:
```
autocmd DirEnter ~/filtered view! | autocmd DirEnter !~/filtered view | autocmd! DirEnter !~/filtered
```

On new `master` (98d5866c8908b3e3a11f09e77d238d0ae8e0768e) `~/filtered/**/*` pattern can be used to affect `~/filtered` and any its subdirectory at any level (`**` was available before, but it couldn't match whole-subtree):
```
autocmd DirEnter ~/filtered/**/* view! | autocmd DirEnter !~/filtered/**/* view | autocmd! DirEnter !~/filtered/**/*
```

**Comment by aleksejrs** [comment]
Can filters and/or sorting be added to that?  I tried `ls` with `%U`, and normal filters (stumbling at http://q2a.vifm.info/88/whats-wrong-with-these-filter-command-definitions ).  (In practice for this case, I could just change some file names, of course.)

**Comment by aleksejrs** [comment]
Maybe I should break lines with `\` to be able understand these lines after editing.  Thanks for what works though.

**Comment by xaizek** [comment]
Yeah, this should be simpler to understand (with such constructs, looks like functions (at least without arguments) should be needed soon):
```
autocmd DirEnter ~/filtered/**/* view!
                             \ | autocmd DirEnter !~/filtered/**/* view
                                                               \ | autocmd! DirEnter !~/filtered/**/*
```
As in Vim commands that consume `|`, can be wrapped with `execute`, e.g.:
```
... execute '!some command' ...
```

**Comment by aleksejrs** [comment]
I couldn't use the following, because exiting the resulting custom view puts me back into ~/filtered, which loads the custom view again (loading the custom view is not processed as entering a non-~/filtered though).
```
autocmd DirEnter ~/filtered/**/* view!
				\ | execute '!ls -f важность-важное важность-неважное-topics срочность-срочное срочность-несрочное generate.sh REPL.py %U'
				\ | autocmd DirEnter !~/filtered/**/* view
								\ | autocmd! DirEnter !~/filtered/**/*
```

**Comment by xaizek** [comment]
> I couldn't use the following, because exiting the resulting custom view puts me back into ~/filtered, which loads the custom view again

Shouldn't happen any more. Technically custom view is in that directory, so nothing should be triggered. Thanks.

**Comment by aleksejrs** [comment]
So [that](https://github.com/vifm/vifm/issues/140#issuecomment-169055685) works, thanks.
