### ISSUE TITLE
Suggested extensions to add to vifmrc for file[x]type:

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#141]
Suggested extensions to add to vifmrc:
* `*.mpeg` (`*.mpg` is there already)
* Rare media formats from /etc/mc/mc.ext: as[fx], divx, fl[icv] mts, ts, r[am], qt
* Audio formats (at least `*.oga` and `*.spx`, but also MIDI which may require different players).
* `*.vym` → [vym](http://www.insilmaril.de/vym/)
* `*.sha1`, `*.sha256`, `*.sha512` (`*.md5` is there already)

Maybe too many programs:
* `*.ora` OpenRaster. https://en.wikipedia.org/wiki/OpenRaster#Application_support

Not very useful, but anyway:
* `*.apkg` is an exported [Anki](http://ankisrs.net) deck.  It is a ZIP file with collection.anki2 and extensionless media files, and all Anki does with it when given at the CLI is say "Please use File>Import to import this file."

**Comment by xaizek** [comment]
If you use some of them, please post corresponding commands here. I don't mind adding them, just don't want to add commands that might not work (not all are easy to verify, need to have both such files and corresponding programs).

**Comment by aleksejrs** [comment]
```
" OpenRaster
filextype *.ora
        \ {Edit in MyPaint}
        \ mypaint %f,
```
```
filextype *.vym
	\ {Open with VYM}
	\ vym %f &,
```


Checksum checkers.
* Without %m (like MD5 currently is), they succeed silently (which is unhelpful with big files) and fail with "press return".
* With %m, they show *two* messages on failure (one supposedly because of the return code).
```
" SHA1
filetype *.sha1
       \ {Check SHA1 hash sum}
       \ sha1sum -c %f %m,

" SHA256
filetype *.sha256
       \ {Check SHA256 hash sum}
       \ sha256sum -c %f %m,

" SHA512
filetype *.sha512
       \ {Check SHA512 hash sum}
       \ sha512sum -c %f %m,
```

You can prepend "`sync && `" to them, if that helps make sure the file on disc is checked.  I am not sure about that, and it is not possible (not useful?) to focus the sync on a single file.

I also have an entry for SHA1SUMS, but it runs a shell script:

```
#!/bin/bash
sync
sha1sum --quiet --check SHA1SUMS
```
I suppose that's why I am not affected by the %m-related issue.  When successful, it only shows a message saying 1 checksum did not match (meaning the SHA1SUMS file itself, but that depends on how it was generated).

**Comment by aleksejrs** [comment]
Why does `:file` also list Zathura for *.vym?

**Comment by xaizek** [comment]
Thanks.

> You can prepend "sync &&" to them, if that helps make sure the file on disc is checked.

That should only slow things down, if there is data in kernel write buffers that await writing to disk then applications will see that instead of what's on the disk (well, unless `O_DIRECT` flag is used, which is uncommon and won't be used by such utilities as it can degrade performance).

> I am not sure about that, and it is not possible (not useful?) to focus the sync on a single file.

There are `fsync()` and `fdatasync()` system calls, but might be no command-line utility. The closest thing is probably `sync -d`.

**Comment by aleksejrs** [comment]
*.rm and *.ra created with ffmpeg are played by ffplay, MPlayer2, MPV (and Dragon Player, but see below).

A problem with Dragon Player: "dragon 1.rm" makes Dragon Player start with "http://1.rm", and I can only play the file through the GUI.

**Comment by aleksejrs** [comment]
Same with *.asf (MPEG-4 part 2 Microsoft variant version 3, Windows Media Audio 2).

* *.oga is Vorbis (tested with a renamed .ogg file),
* *.opus is Ogg Opus (tested with a piece of "Hypnotic torture clock" from http://opus-codec.org/examples/ )
* *.spx is Speex
 — played by ffplay, MPlayer2, MPV. Dragon Player also plays .oga and .spx, but I couldn't find a menu item for Opus (but the player is not used in Vifm for audio anyway).

**Comment by aleksejrs** [comment]
.apkg was simply added to the list of ZIP extensions and worked in 0.8.

**Comment by aleksejrs** [comment]
.ts and .mts (same output from ffmpeg) are played by ffplay, MPlayer2, MPV.

**Comment by aleksejrs** [comment]
Another Ogg extension is .ogx

I don't have module or MIDI files and don't know what people are used to play them with.

**Comment by xaizek** [comment]
Thanks.

> A problem with Dragon Player: "dragon 1.rm" makes Dragon Player start with "http://1.rm", and I can only play the file through the GUI.

Maybe `dragon ./1.rm` or full path (`dragon $CWD/1.rm`) will work?

**Comment by aleksejrs** [comment]
Full path `:!dragon %d/%f` works

**Comment by aleksejrs** [comment]
> The closest thing is probably sync -d.

There seems to be no options in coreutils' `sync`.

**Comment by xaizek** [comment]
> There seems to be no options in coreutils' sync.

```
+[~]$ sync --version
sync (GNU coreutils) 8.24
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jim Meyering and Giuseppe Scrivano.
+[~]$ sync -d
sync: --data needs at least one argument
```
Mine has them, make sure you're not calling builtin command of your shell. And as it requires file path, it looks like it's exactly what you want.

**Comment by aleksejrs** [comment]
> sync (GNU coreutils) 8.24
> Mine has them

OK, Debian still has 8.23, and "sync no longer ignores arguments" in 8.24 (2015-07-03).

**Comment by xaizek** [comment]
> With %m, they show two messages on failure (one supposedly because of the return code).
> ...
> I suppose that's why I am not affected by the %m-related issue.

Now I understand what you meant, it's not an issue. `md5sum` and alike tools print their output in both `stdout` and `stderr`. With `%m`, menu is constructed from `stdout`, but encountered errors are displayed in a dialog. There are at least two ways to deal with this:
* Redirect `stderr` to `stdout` with `2>&1` and use `%m`.
* Use `%S`, so that results are displayed on the status bar (menu seems a bit overkill), it also conveniently drops `stderr`. Although for big lists menu might be a better choice.
