### ISSUE TITLE
":!/etc/init.d/cryptdisks reload" → askpass hangs using 99.5% CPU

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#142]
`:!/etc/init.d/cryptdisks reload` starts `cryptdisks` (from the `cryptsetup` package), which finds an unmounted encrypted container and runs `/lib/cryptsetup/askpass` to ask for a password.  Normally (or now without Vifm) it processes the password correctly, but now, when I press Enter, `askpass` hangs, loading the whole CPU.

```
[info] sdxe (starting)...
Pass_sdc:
```
htop:
```
23645 root       20   0  4204   704   628 R 99.8  0.0  0:43.02 /lib/cryptsetup/askpass Pass_sdc:
```
A simple `killall cryptdisks` kills it, but not a simple `killall askpass`.

```
Version: 0.8.1-beta
Git info: v0.8.1-beta-11-g66ee57588fac-dirty
Compiled at: Jan  3 2016 23:26:11
```

**Comment by aleksejrs** [comment]
Actually, my Debian testing/stretch fails to shutdown, apparently trying to unmount something encrypted.  Maybe it's related to this issue, and/or to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=791944  I'll look at it later.

**Comment by xaizek** [comment]
Could be similar to #138 (changes there don't affect root), did it work with 0.8?

**Comment by aleksejrs** [comment]
It worked with 0.8, but I hadn't started the script from Vifm for a couple of days or more, and yesterday was also the second time Debian crypto unmount has hung.

**Comment by aleksejrs** [comment]
It doesn't work with 0.8.

**Comment by aleksejrs** [comment]
(Now with the master build.  Note that askpass hangs no matter if it's in X or in a VC.)

In Vifm, `:.!/etc/init.d/cryptdisks reload`

End of the output after pressing Enter:
```
vroot@d:~# vifm
(…)
[warn] sdxe: device '/dev/sdc' is not a LUKS partition, skipping ... (warning).
[FAIL(failed)...failed.
[info] sdxe (starting)...
Pass_sde:
```

* Entering "`123`", pressing `<Enter>`.  askpass hangs.
* In a different shell, `pkill -u root vifm`

Vifm is killed, the output with the same part skipped:
```
vroot@d:~# vifm
(…)
[warn] sdxe: device '/dev/sdc' is not a LUKS partition, skipping ... (warning).
Vifm killed by signal: 15 (Terminated).
root@d:~# 123starting)...
bash: 123: command not found
root@d:~# 
```

**Comment by aleksejrs** [comment]
The password-in-command-line thing is not caused by Vifm:

`root@d:~# /etc/init.d/cryptdisks reload`
…enter "123", do not press Enter…
`root@d:~# pkill cryptdisks`
```
[info] sdxe (starting)...
Pass_sde:Terminated
root@d:~# 123
```
The "123" is actually in the shell.

**Comment by aleksejrs** [comment]
Forgot: when I kill vifm, the hung askpass is still running and loading the CPU.

**Comment by aleksejrs** [comment]
"`/lib/cryptsetup/askpass hello`" prints "hello", gets a string, and prints the string (without \ns).  It does that OK with Vifm.

**Comment by xaizek** [comment]
Thanks for the details, I reproduced the hang and should be able to do something about it now.

> By the way, http://wiki.vifm.info/index.php?title=How_to_set_shell_working_directory_after_leaving_Vifm

Thanks, changed version.

**Comment by xaizek** [comment]
Should work now, thanks. Don't know why, but it wanted `stdout` to be opened in read-write mode, shell opens it the same way, which is something I didn't expect.

**Comment by aleksejrs** [comment]
Thanks, it works.

The Debian shutdown problem is tracked here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792552
