### ISSUE TITLE
screenshot page description expansion

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#145]
It is not clear from http://vifm.info/gallery.shtml how to achieve the layout at the bottom on http://vifm.info/screenshots/features.png.  It says “Classify, ls-like and multicolumn view in visual mode”, but the keyword for the multicolumn view is “`viewcolumns`”, while “multicolumn” and “multiple columns” is used more for `lsview`.

**Comment by xaizek** [comment]
It wasn't meant to be very precise, but updated description a bit, thanks.

For completeness, that setting is similar to the following (it's relatively old screenshot, so might not be an exact match):
```
set viewcolumns=-{name}..,20{perms},{uname},{gname},15{size}.,{mtime}
```

**Comment by aleksejrs** [comment]
Thanks.

**Comment by aleksejrs** [comment]
“`{groups}`” shows the first sortgroup only.

**Comment by xaizek** [comment]
> “{groups}” shows the first sortgroup only.

That's intentional, either nothing or match of the first group. Can't create separate column for each group (can't get their number in regexp, libregex doesn't provide such information), so it's unclear how to display more than one match (well, maybe comma/semicolon separated list? if that won't be too ambiguous).

**Comment by aleksejrs** [comment]
> Can't create separate column for each group (can't get their number in regexp, libregex doesn't provide such information),

I have almost no idea why libregex would *have* such information.  Does any other program have a similar sorting feature?

> so it's unclear how to display more than one match (well, maybe comma/semicolon separated list? if that won't be too ambiguous).

Can the separators be colored differently?

**Comment by xaizek** [comment]
> I have almost no idea why libregex would have such information. Does any other program have a similar sorting feature?

Not aware of such applications.

> Can the separators be colored differently?

No, at least not at the moment (it's very inconvenient to implement and might be hard to get right with all cropping and aligning options).
