### ISSUE TITLE
“File Sourcing Error” half-blank on subsequent tries when “relativenumber” is on.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#146]
Vifm 0.8.1

1. Make a file called `t` with contents `:set sortgroups=(не нужно)`.  The space in “`не нужно`” makes the command invalid.
2. Run “`:source t`”.  You get an error message “File Sourcing Error Error in t at line 1”.
3. Press `Enter` to close the message.
4. Run  “`:source t`” again (possibly by pressing `.`).  You get the same message, but the half over the pane with the file is not visible.  Subsequent attempts give the same result until I change directory.

**Comment by xaizek** [comment]
Couldn't reproduce it yet and don't see what might be causing this, but there were similar redrawing issues in the past. Might depend on some settings or directory content.

**Comment by aleksejrs** [comment]
Sorry, yes; it is caused by `:set relativenumber`.

**Comment by xaizek** [comment]
Now I see it, thanks.
