### ISSUE TITLE
wincmd {direction} does not change focus to desired pane

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#149]
After I updated  (from 0.8) to the newest repository state , command `wincmd {direction}` does not work anymore and focus is still kept at original pane. But `active cursor` is drew at both, original pane and pane focus should be changed on.

Xubuntu 14.04

**Comment by xaizek** [comment]
Thanks, should work again with current master.

**Comment by fogine** [comment]
Thank you for the fix @xaizek .
However this command which previously worked still behaves the same way as described above:
`:if paneisat('left') == 0 | execute "wincmd h" | endif`

Command `:wincmd h` works well though.

**Comment by xaizek** [comment]
This time should work from command list separated with `|`. Also hit two more bugs in command processing while testing, which are now fixed, thanks.
