### ISSUE TITLE
%m menu does not abbreviate the line in the title.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#151]
To execute `command! wd cd .. && ./do.sh %f:p %m`, Vifm expands the `%f:p`, which fills half the screen with full paths of 36 files.  That results in that list being the background of the `%m` menu, refilling on scrolling whatever the menu text does not cover.

**Comment by xaizek** [comment]
Thanks, fixed.

**Comment by aleksejrs** [comment]
Verified with 0.8.1a.
