### ISSUE TITLE
Quick file view: last line shows the next line, too (concatenated with the last one).

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#152]

**Comment by aleksejrs** [comment]
When the file fills the whole height.

Is it intentional?

**Comment by xaizek** [comment]
> Is it intentional?

No, I also can't reproduce it. Say `echo &lines` outputs 37, minus title, statusline, statusbar and two empty lines I'm left with 32 lines. File contains 32 lines (numbers from 1 to 32) and they are all on separate lines. Maybe there is some additional condition for file contents, encoding or line endings?

**Comment by aleksejrs** [comment]
`$ yes|head -n40>abc`

Preview shows “y” on every line except the last line, which shows “yy”.

**Comment by xaizek** [comment]
So `'tuioptions'` should not contain `p`. Now I see it, thanks.

**Comment by aleksejrs** [comment]
My tuioptions is empty.
