### ISSUE TITLE
user home paths fail in `bmark!`

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#153]
First of all, thank you for developing Vifm. I've been using Vim and mc for many years. mc is great, but I always missed a Vim-like file manager. Now I'm trying Vifm 0.8.1 on Rasbian (=Debian for Raspberry Pi) and I'm so impressed that I'm already using it instead of mc, while improving the configuration file.

Well, one issue I've found is home paths with "~" cause trouble in `bmark!`. For example, this command:

```
  :cd /tmp
  :bmark! ~/bin xxx
```

creates the following unusable bookmark, as shown by `bmarks`:

```
  /tmp/~/bin: [xxx]
```

Of course it works fine with the absolute path:

```
  :bmark! /home/user/bin xxx
```

Is it a bug, or am I missing something?

**Comment by xaizek** [comment]
It's a bug, tilde expansion is missing in the code. Thanks for the report.
