### ISSUE TITLE
suggestion: `filetype!`, inverse version of `filetype`

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#154]
I'm trying to configure some `filetype` entries in order to compress files not already compressed (and thus making the files menu smarter and tidier), so I need to match files which don't have certain filename extensions. So far I'm having trouble with [regex lookaround](http://www.regular-expressions.info/lookaround.html), while other methods produce very long expressions and don't work in all cases. Maybe someone has already achieved this and would like to share the regex?

I've searched the manual, but found no way to invert the meaning of a `filetype` entry, which would be a very simple solution for globs. Example:
```
filetype! *.zip,*.gz,*.xz
```
That entry would *exclude* files which match any of the given globs. The proposed syntax `filetype!` would be analougus to `filter!`.

**Comment by xaizek** [comment]
There is no such inversion as of now, not a very common thing to do. Lookarounds aren't part of POSIX normal or extended regular expressions, so I'd not expect them to work (POSIX regexp API is employed by Vifm).

Thanks for the suggestion.

**Comment by programandala-net** [comment]
Thanks for confirming lookarounds don't work.

I think a similar effect may be achieved by associating all files to external shell programs (one program for every compressor), which compress or decompress them depending on the filename extension. This is more or less the way the menu config of mc works, except the shell commands are included in the menu config file.

**Comment by xaizek** [comment]
Implemented it in a different way: instead of making negation property of a command, it's now property of a pattern. To omit ambiguity it requires explicit specification of pattern type, but it shouldn't cause much inconvenience. A couple of examples:
```
!* -- files starting with "!" (because there is no {} or //)

!{*.zip,*.gz,*.xz} -- files that have extensions other than "zip", "gz" or "xz"
```
This way negation is automatically available in `:highlight`, `:filetype`, `:filextype` and `:fileviewer` commands as well as in `'classify'` option. Thanks.
