### ISSUE TITLE
Trying to mix files and directories in the sort order

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#155]
I've read #36, and the current manual explains the same method: adding `type` at the end, in order to avoid its default initial position in the sort order when it's ommited:

> Type key is somewhat similar in this regard but it’s added implicitly: when "type" is
> not specified, sorting behaves as if it was the first key in the list. That’s why if
> one wants sorting algorithm to mix directories and files, "type" should be appended
> to sorting option, for example like this:
> 
> set sort+=type
> 
> or
> 
> set sort=-size,type

But it doesn't work for me: directories are always on the top of the list. Then I realized there's a sorting key called `dir`, and it works:

```
set sort=+name,dir
```
So it seems the method changed since #36, but the manual was not updated? But it seems `dir` works differently than other keys, only `dir` or `+dir` being useful to turn the directory grouping *off* (a bit counter-intuitive).

But I'm not sure to understand how sorting keys work combined with `dir`, or perhaps something is broken. For example `set sort=+dir,+size` lists first all directories and then all files sorted by increasing size, while `set sort=-dir,+size` does the same except files are sorted by *name*. `set sort=+size,+dir` works as expected: directories and files are mixed and sorted by size, but `set sort=-size,+dir` groups directories at the top...

**Comment by xaizek** [comment]
> So it seems the method changed since #36, but the manual was not updated?

Right, there was a rename, will update the docs, thanks.

> dir works differently than other keys, only dir or +dir being useful to turn the directory grouping off (a bit counter-intuitive).

It supposed to work just as any other key. `-dir` works for me just as expected. When you use it with `size`, look at directory sizes, which are small and often identical so directories tend to cluster. As for files being sorted by names, this will happen for files of identical size.

**Comment by xaizek** [comment]
> But I'm not sure to understand how sorting keys work combined with dir, or perhaps something is broken. For example set sort=+dir,+size lists first all directories and then all files sorted by increasing size, while set sort=-dir,+size does the same except files are sorted by name. set sort=+size,+dir works as expected: directories and files are mixed and sorted by size, but set sort=-size,+dir groups directories at the top...

I noticed reversed order of keys (`dir` before `size`) only now. Keys are applied from left to right, so here's what happens for `set sort=-dir,+size`:
1. List of files is divided into "files" and "directories" groups.
2.1. "files" group is sorted according to `+size`.
2.2. "directories" group is sorted according to `+size`.
3. Those groups are concatenated (they are not in code, but the result is equivalent). 

Thus if you want to do not group directories, the `dir` key should be the last one, where it will have the lowest weight and won't affect position of files unless all other sorting properties are equal. Documentation already says that `dir` should be appended to achieve such result, so I'm closing this.
