### ISSUE TITLE
`%-` macro is not translated in `rulerformat` or `statusline`

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#156]
The manual reads the `%-` macro can be used in `rulerformat` or `statusline` to represent the number of filtered out files, but it doesn't work in 0.8.1. Is it a bug or maybe the macro changed and the manual is outdated? In fact, '%-' can be part of a kind of negative field width. An example can be found in the manual: `%10u:%-7g`, but it has nothing to do with the '%-' macro.

**Comment by xaizek** [comment]
See the [note there](http://vifm.info/vimdoc.shtml#vifm-%27rulerformat%27):
```
Note ambiguity with number of filtered out files, which can be resolved with the help of width field ("%0-").
```

**Comment by programandala-net** [comment]
>  Note ambiguity with number of filtered out files, which can be resolved with
>  the help of width field ("%0-").

Thanks, I didn't see that. So `%0-` must be used. But wouldn't it be
simpler a letter name for this macro?

**Comment by xaizek** [comment]
> But wouldn't it be simpler a letter name for this macro?

Probably, I don't really remember why it's `-`. I guess it's to do not conflict with Vim's `'statusline'` values and do not use completely unrelated letter.
