### ISSUE TITLE
suggestion: `{lname}` for `viewcolums`

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#157]
I have created several mappings to change `viewcolums` on the current pane or on both panes, depending on what file information I need to see at the moment. Sometimes I miss a way to inspect where all symbolic links lead to, especially when some of them are broken, and then I have to open a shell, or use `:!!ls -l`, or inspect them individually with the `cl` mapping. I've searched the manual but I think there's no way to show this information on the files listing yet.

I suggest `{lname}` (or maybe better `{lpath}`) as an additional key for `viewcolums`; it would show the whole path a symbolic link leads to, or nothing if it's not a symbolic link.

**Comment by xaizek** [comment]
Thanks. Named it `{target}` as it's basically link target path, while "link name" or "link path" might be a bit confusing because they refer to link itself.

**Comment by programandala-net** [comment]
> Thanks. Named it `{target}` as it's basically link target path, while
> "link name" or "link path" might be a bit confusing because they refer
> to link itself.

Right, `{target}` is a better name. Thank you.

-- 
Marcos Cruz
http://programandala.net
