### ISSUE TITLE
Default associations of `filetype` in the `file` menu

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#158]
I get default entries at the bottom of the `:file` menu I don't need. For example, by default text files (*.txt) or Forth source files (*.fs) are associated to LibreOffice, Leafpad and Abiword, programs which I rarely use insead of Vim. I get strange associations too, e.g. compressed source files `.fs.xz` to the Evince viewer!

I have not found where those associations came from or how I can remove them.  I've found no reference in the manual. I've searched the installation directory of Vifm, and */etc/* as well, but found no clue.

The default entries don't dissapear when I create a custom `:filetype` entry for the same glob in the config file.

How and when these default associations are set by Vifm? How can I remove them?

**Comment by xaizek** [comment]
These are not default entries. They are from `*.desktop` files you have installed. They can be disabled by configuring with `--disable-desktop-files` option.

**Comment by programandala-net** [comment]
> These are not default entries. They are from *.desktop files you have
> installed.

I see.  They never bothered before because my environment is most
"anti-desktop" -- I use Ratpoison as window manager, and a Screen
session in it, that's all.

Now, searching the manual for "desktop", I find the answer:

> Filetype menu

>     Commands from vifmrc or typed in command-line are displayed above
>     empty line. All commands below empty line are from .desktop files.

The confusion was the actual name of the menu command is `file`, not
`filetype`, and so I expected the info under `:file`, and forgot
searching also for `menu`.

Anyway, I don't understand some strange associations caused by
automatically created .desktop files. I will explore that.

> They can be disabled by configuring with --disable-desktop-files
> option.

Ok.

Thank you.
