### ISSUE TITLE
Feature suggestion: vim-like " V`] " aka reselect last selection

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#160]
I've found myself sometimes missing this feature .

> V`]

 Reselects last made selection.

**Comment by xaizek** [comment]
> >   V`]

>Reselects last made selection.

Are you sure?
```
']  `]			To the last character of the previously changed or
		       	yanked text.  {not in Vi}
```
It also doesn't work in Vim that way for me and aren't you asking about [<kbd>gv</kbd> key](http://vifm.info/vimdoc.shtml#vifm-gv)?

**Comment by fogine** [comment]
yeah, I'm sorry @xaizek  I missed it in the doc. I meant the `gv` key combination, it was apparently too late for me yesterday to post a feature suggestion... should have postpone it to other day. I ended up copying something else from my `vimrc`.

What is a difference (other than selecting files individually) between tag file `t` and selecting multiple files in visual mode `v`.
Would it be possible to include last tagged group of files in "selection" history. So that if I tag couple of  files with `t`, then hit `ESC` following by hiting `gv`, it would restore last tagged group of files?

**Comment by xaizek** [comment]
> What is a difference (other than selecting files individually) between tag file t and selecting multiple files in visual mode v.

Visual mode selection is usually contiguous associated with visual mode. That's how <kbd>gv</kbd> works in Vim.

> Would it be possible to include last tagged group of files in "selection" history. So that if I tag couple of files with t, then hit ESC following by hiting gv, it would restore last tagged group of files?

There is [<kbd>gs</kbd> key](http://vifm.info/vimdoc.shtml#vifm-gs) for this kind of selection.

<kbd>gs</kbd> and <kbd>gv</kbd> are different not only in mode you're in after using them, but also in that <kbd>gv</kbd> remembers only first and last files (i.e., start and end of the range, `'<` and `'>` marks), while <kbd>gs</kbd> remembers each file individually (set of last selected files is reset on changing directory).
