### ISSUE TITLE
Warning! Delete confirmation needed.

### ISSUE THREAD

**Issue by Losiara** [vifm/vifm#165]
I nearly broke my home folder. I even don't remember what I pushed, but all unlocked files from home moved to trash folder. Restore command didn't work so was much pain to restore manually. Please add delete confirmation by default and the "shfit(alt)" command to delete without confirmation.

**Comment by xaizek** [comment]
I'd expect single hit of <kbd>u</kbd> key to restore everything, were there any message why it didn't? There are no confirmation since it's not irreversible operation, it's basically a move. Current behaviour seems to be consistent as there is no confirmation for moving files either. If you would use <kbd>D</kbd>, you would be asked for confirmation.

You probably hit <kbd>da</kbd> combination. Actually, I started removing files by accident too, so maybe it's worth changing `'confirm'` to affect <kbd>d</kbd> and always prompt on <kbd>D</kbd>.

**Comment by aleksejrs** [comment]
> Actually, I started removing files by accident too

Me too, almost: I press Esc to close MPlayers, and it sometimes reaches Vifm.

**Comment by Losiara** [comment]
I cant repr what I've done, may be command like ":%d"
Command ":restore" didnt work.
So confirmation by "D" and non-confirm by "d" is good idea I think.

**Comment by xaizek** [comment]
> Command ":restore" didnt work.

It works only inside trash directory.

**Comment by Losiara** [comment]
> It works only inside trash directory.
I ran it inside trash dir. No result. When I run it inside other dir, thereis error message, but this time just no result.

**Comment by mvucBmM0** [comment]
In my opinion I think this should be kept optional. Having to now press an additional 'y' for every file I delete is rather annoying.

**Comment by xaizek** [comment]
@mvucBmM0, it is optional, did you try the following?
 ```
set noconfirm
```

**Comment by mvucBmM0** [comment]
Yep, it isn't working.

**Comment by xaizek** [comment]
So you don't want confirmation on <kbd>D</kbd> and `:delete!`?

**Comment by mvucBmM0** [comment]
I preferred to have the option to not use it, yes.
I have been using
nnoremap <delete> :delete! &
nnoremap DD :delete! &

so It was kinda like confirmation in a way.
I just preferred it that way.

**Comment by xaizek** [comment]
Changed `'confirm'` to set to make it extensible and allow for all possible configurations. The change is not compatible, but it should affect very few users who changed the option to `noconfirm` (I don't expect many people doing this).

**Comment by mvucBmM0** [comment]
Thanks xaizek.
Sorry if that sounded like a picky request. I blame my brain and it's little obsessions...

**Comment by xaizek** [comment]
That was reasonable request, I didn't like to make configuration less flexible anyway, but also didn't want to change option if I could get away without such change.
