### ISSUE TITLE
Ranger FM like Jump List for Bookmarks + Other Commands

### ISSUE THREAD

**Issue by santhoshr** [vifm/vifm#166]
Is it possible to bring quick jump list on pressing certain keys like ' for marks, d for delete operation, instead of bottom up popup list like ranger, VIFM can use the other view to show quick help, but if only one view (:only) is active, then vifm should show the popup list. I found this handy in ranger fm, to quickly see pressing which key activates which function.

**Comment by xaizek** [comment]
Not possible at the moment, but [likely to appear](http://q2a.vifm.info/101/command-autocompletion-option-suggestions-descriptions?show=101#q101). I'd go with popup list at the bottom because it will provide consistency, you won't need to remember where too look when (also concealing more of the screen can hide something from context in which you're operating).

**Comment by xaizek** [comment]
It's there now.

> I'd go with popup list at the bottom

This is configurable via `'suggestoptions'` option, because displaying only popup hides too much of the screen for no good reason (there is a lot of empty space).

**Comment by santhoshr** [comment]
Dude you are awesome! This is so fast! Haven't checked out will do...

**Comment by xaizek** [comment]
> how do I get the bleeding edge version for windows...should I do some compilation/linking?!

Yes, although [it's not that easy](http://wiki.vifm.info/index.php?title=Obtaining_Vifm#Windows).

64-bit executable from current `master` is [here](https://vifm.info/vifm-w64-v0.8.1a-115-g48a61bc79e29.zip).

Maybe I'll try to setup automatic Windows builds for `master` branch (full package, not just executable), it shouldn't be hard to do.

**Comment by santhoshr** [comment]
How do I toggle 'suggestoptions' ? tried setting value (thinking it should be boolean) didn't work then tried setting value to 1/true/0, nothing worked, what value should be there ? 

Automatic builds would be great, but if 'master' executable will always be available, that would be enough, since not many people would want bleeding edge for everyday use.

**Comment by xaizek** [comment]
It's not boolean. Corresponding help is [here](https://github.com/vifm/vifm/blob/5ee69df242572f7056f68b4070c56e84fc5200dd/data/vim/doc/app/vifm-app.txt#L3140-L3150). Hm, I forgot to document `delay` value...

> 'master' executable will always be available, that would be enough

For most cases and it's worth starting just with executables, but like in this case you didn't get updated documentation, for example. I suspect that all parts are already there, just need to pull them out into separate script to build Windows package on GNU/Linux.

**Comment by santhoshr** [comment]
(Ah! there is auto complete that works even for setting values, somehow I didn't try it and missed it.)
It is very confusing suggestoption, with many options, view/otherpane/delay did not work for me, I guess delay will open suggestions when user stuck for few mins. Normal works fine. What is the purpose of Visual, when normal works fine ?. Also suggestion disappears after few mins and it is annoying.

**Comment by xaizek** [comment]
> view/otherpane/delay did not work for me

`view` works in view mode.
`otherpane` displays in second pane.
`delay` waits for about 1/4 of a second by default I think.

> It is very confusing suggestoption. ... Normal works fine. What is the purpose of Visual, when normal works fine ?

`visual` is for visual mode. `otherview` and `delay` need to be combined with others, e.g.

    set suggestoptions=normal,visual,view,otherpane,delay

> Also suggestion disappears after few mins and it is annoying.

That might happen if directory is changed, I didn't put much effort in fixing it because I wouldn't expect suggestions to be relevant after more than, say, 10 seconds.

**Comment by xaizek** [comment]
@santhoshr, Windows builds (just executables at the moment) should appear [here](http://builds.vifm.info/) when I push to `master` branch.

**Comment by durcheinandr** [comment]
Is there a way to customize colors in suggestoptions?
![vifm](https://cloud.githubusercontent.com/assets/9393265/13987575/81c6c278-f108-11e5-8c8d-4dcda9aad25d.png)

**Comment by xaizek** [comment]
> Is there a way to customize colors in suggestoptions?

It's part of color scheme, `SuggestBox` highlight group:
```
" black on white, no bold
hi SuggestBox ctermfg=white ctermbg=black cterm=none
```

**Comment by durcheinandr** [comment]
Thanks. Looks much better now.

**Comment by xaizek** [comment]
Some changes:
 * changed colors to default foreground and background;
 * more configurable (delay duration) and more granular (particular suggestions can be enabled);
 * @santhoshr, suggestions shouldn't disappear anymore.

So those who already uses this feature might want to change option value to something like this (add `keys`, `marks` and `registers`):

```
set suggestoptions=normal,visual,view,otherpane,delay,keys,registers,marks

**Comment by santhoshr** [comment]
Thanks for the windows build. 

- Does vim style addition supported for set ? for e.g.
current set suggestoptions=normal, can I do set suggestoptions+=marks, (to append. Tried, does not work)

- keys, registers, marks: options are not available when doing tab-autocomplete

- when displaying in otherpane, is there way to scroll autocomplete, like using (shift-tab in view), so tab scrolls down, shift tab scrolls up ? or tab can be replaced with space key, this should apply even when popup is being displayed and longer...

- popup does not work reliably in delay mode, does not appear, or disappear quickly

- is there a way to minimize delay option wait time length, it takes more than 2 sec to appear

**Comment by xaizek** [comment]
> Does vim style addition supported for set ? for e.g.  current set suggestoptions=normal, can I do set suggestoptions+=marks, (to append. Tried, does not work)
> keys, registers, marks: options are not available when doing tab-autocomplete

`+=` works.  If you don't see these completion items then you must be using wrong version, which also explains why `+=marks` doesn't work.

> when displaying in otherpane, is there way to scroll autocomplete, like using (shift-tab in view), so tab scrolls down, shift tab scrolls up ? or tab can be replaced with space key, this should apply even when popup is being displayed and longer...

No, and it's not really possible because it will conflict with keys (if you have space or shift-tab mapped).

> popup does not work reliably in delay mode, does not appear, or disappear quickly

It can disappear if timeout is out and key was ambiguous (for example, when you press <kbd>,</kbd> and have <kbd>,a</kbd> mapping; `,` is picked after a delay).

> is there a way to minimize delay option wait time length, it takes more than 2 sec to appear

For example, use `delay:100` for 100ms.
