### ISSUE TITLE
$ENV editor

### ISSUE THREAD

**Issue by Losiara** [vifm/vifm#167]
Feature request. Add $PATH or other &ENV edit commands. Edit localy(inside current folder), globaly, persist (via .bashrc, or .profile).

**Comment by xaizek** [comment]
If you want to use some vifm-specific scripts, you can put them to `~/.vifm/scripts`.

`$PATH` can be appended via `:let` command, e.g.:

    let $PATH .= ':'.$HOME.'/bin'

I thought that it's enough for most use cases.
