### ISSUE TITLE
Windows 10 64 bit + ConEmu -> Multiple rename does not work

### ISSUE THREAD

**Issue by santhoshr** [vifm/vifm#168]
Multiple rename does not work. 0 files renamed.

**Comment by xaizek** [comment]
What's so specific about "Windows 10 64 bit + ConEmu" configuration, does it work in other configurations?

**Comment by santhoshr** [comment]
Nothing specific, I just wanted you to know the environment.It doesn't work in cmd either or even with cmd with admin rights.

**Comment by xaizek** [comment]
This is another toolchain related issue... You can use [vifm-w32-0.8.1a-binary](https://sourceforge.net/projects/vifm/files/vifm-w32/vifm-w32-0.8.1a-binary.zip/download), which is not affected. Thanks for the report.

**Comment by xaizek** [comment]
Correction, [vifm-w32-se-0.8.1a-binary.zip](https://sourceforge.net/projects/vifm/files/vifm-w32/vifm-w32-se-0.8.1a-binary.zip/download) works fine too. Only 64-bit version exposes incorrect behaviour.
