### ISSUE TITLE
Renamed files will not overwrite files, fails almost silently

### ISSUE THREAD

**Issue by rbong** [vifm/vifm#169]
Situation: duplicating a backup file that is in the same directory as the original file. I paste the backup into the folder and it asks me if I wish to overwrite it. I select rename, and name it as the original file is named. It asks me if I wish to overwrite it, and I select overwrite. At the bottom, it says that 0 files have been inserted. If not paying attention to the bottom bar, everything seems to have gone well and I don't notice that the copy has failed without knowing about this error.

Example:

``` touch file1 file2```

In vifm:

```
/file1<CR>yypr<BS>2<CR>o
```

output:

```0 files inserted.```

Is this intended behaviour?

**Comment by xaizek** [comment]
> Is this intended behaviour?

No, I'd expect destination file to be overwritten. Thanks, I'll look into this.
