### ISSUE TITLE
Progress bar for copying/moving files

### ISSUE THREAD

**Issue by reicheltd** [vifm/vifm#17]
Hi xaizek,

is there a demand to add a progress bar to the command line?

When I copy or move 1 big file and it says "Copying files 1/1" in the command line. I never really know how long it still needs to finish.

Perhaps other user would find a progress bar useful as well.

Best regards,
Daniel

**Comment by fogine** [comment]
Maybe it would be better, in some situations, to have an option to push files to queue instead of immediately triggering asynchronous transfers of files.

**Comment by xaizek** [comment]
> Maybe it would be better, in some situations, to have an option to push files to queue instead of immediately triggering asynchronous transfers of files.

Might be useful (and should be faster for multiple copies on the same drive), I agree. Will add this to the TODO list, thanks.

**Comment by fogine** [comment]
>Will add this to the TODO list, thanks.

I thank you, very much, for your incredible work. Finally I've something which I can use instead of total commander :) And it's even much better!

**Comment by robcsi** [comment]
Vifm - (the) Very Indispensable File Manager ;).

**Comment by xaizek** [comment]
> Vifm - (the) Very Indispensable File Manager ;).

Nice alternative interpretation :-).

**Comment by rr-** [comment]
Hmm, @xaizek got this function implemented, shouldn't the issue be closed?

**Comment by xaizek** [comment]
@rr-, yeah, I think we can close this, main stuff is done long time ago.

I still didn't write chown/chgrp/chmod implementations on syscalls (encoding their arguments is very inconvenient) and kept this as a reminder, but it has no effect, better to add separate TODO entry for it.
