### ISSUE TITLE
Add ability to save grep search results into the file.

### ISSUE THREAD

**Issue by gtors** [vifm/vifm#171]
After `grep` is completed, then there is no way to save search results into the file. At least I have not found one.

**Comment by xaizek** [comment]
Do you mean short-term (during the session, so you can return to it) or long-term (e.g. export to a file) save? There is a [todo item](https://github.com/vifm/vifm/blob/97c0c6b2026707f562f5efff685373c399c5683f/TODO#L50) for the former one. And I think the latter one was previously discussed in a form of feeding menu lines into arbitrary external command (so `cat` could be used to save all the lines).

Right now you can load results into Vim's quickfix list by pressing <kbd>v</kbd> key and do something with that. For example, this should format the list in a new buffer:
```
:ene | for i in getqflist() | $put = bufname(i['bufnr']) . ':' . i['lnum'] . ':' . i['text'] | endfor | 1d
```

**Comment by gtors** [comment]
To be more clear: https://asciinema.org/a/9wv5pmodf8try1h2fhwxdcvgj

**Comment by xaizek** [comment]
Thanks, added `:write` command.

**Comment by gtors** [comment]
Good news. Thanks.
