### ISSUE TITLE
No `:select` to select/unselect files by pattern/regex?

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#175]
I have created the following mappings to select/unselect files:

```
" All Selected
nnoremap as ggVG<cr>
" None Selected
nnoremap ns :nohlsearch<cr>
" Invert Selection
nnoremap is :invert s<cr>
```
It was surprising that `:nohlsearch` has this effect. Is it intended? It seems to me that unselecting files has nothing to do with the original function of `nohlsearch`. In Vifm it has both functions.

Anyway, I find no command to select/unselect only the files that match a pattern/regex. It seems the current way to select/unselect is only visual. I think `:select` would be very useful to automatize tasks. Without a regex, `:select` would select the current file, and it could be mapped to any key as usual (the "t" mapping would not need to be hardcoded anymore). Unselection would be done with `:select!`, like `:filter!`. Selections and unselections would preserve the currently un/selected files, unless they match the new regex.

**Comment by xaizek** [comment]
> It was surprising that :nohlsearch has this effect. Is it intended?

Executing most of :commands has such effect. You could do:
```
nnoremap ns <esc>
```

> Anyway, I find no command to select/unselect only the files that match a pattern/regex.

Adding `:[un]select` is [planned](https://github.com/vifm/vifm/blob/97c0c6b2026707f562f5efff685373c399c5683f/TODO#L92) quite long time ago actually... Probably time to finally implement it, thanks for reminding about it.

> It seems the current way to select/unselect is only visual.

Also, if `'hlsearch'` option is on, then searching a pattern selects matches and unselects non-matches.

**Comment by programandala-net** [comment]
> Adding `:[un]select` is
> [planned](https://github.com/vifm/vifm/blob/97c0c6b2026707f562f5efff685373c399c5683f/TODO#L92)
> quite long time ago actually... Probably time to finally implement it,
> thanks for reminding about it.
> 
> > It seems the current way to select/unselect is only visual.
> 
> Also, if `'hlsearch'` option is on, then searching a pattern selects
> matches and unselects non-matches.

I suggest a different variable for this, maybe `'selectsearch'`.  Both
functions (highlighting and selecting) are useful either combined or on
their own.

**Comment by xaizek** [comment]
`'hlsearch'` controls only selection of matched items, search match highlighting is always on (it shouldn't harm anything and also because its name is already taken). I would prefer not renaming `'hlsearch'` as it will change behaviour and current situation seems to be OK in general.

By the way, selection commands are ready, will push them now.
