### ISSUE TITLE
gA on ".." does something outside the current directory

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#176]
Pressing `gA` on `..` occupies the HDD much more than on all the contents of the current directory.

0.8.1a+

**Comment by xaizek** [comment]
This isn't very surprising, since `..` refers to parent directory (unless in `/`). But usefulness is questionable I agree, can filter-out `..` entries.

**Comment by aleksejrs** [comment]
In mc, Ctrl-Space on `..` calculates the size of everything in the current directory.

**Comment by xaizek** [comment]
> In mc, Ctrl-Space on `..` calculates the size of everything in the current directory.

Implemented this, thanks.
