### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by onovy** [vifm/vifm#184]
Hi,

can you enable Travis please? Travis config is in repo, but it looks like not linked to Travis CI: https://travis-ci.org/vifm/vifm

Thanks

**Comment by xaizek** [comment]
It's [here](https://travis-ci.org/xaizek/vifm/builds) as it was before organization creation, didn't see much sense in moving it.

**Comment by xaizek** [comment]
> didn't see much sense

OK, I got it, building pull requests. Should be active now.

**Comment by onovy** [comment]
yep, that was my point. according to this PR: https://github.com/vifm/vifm/pull/187 it's working. thanks!
