### ISSUE TITLE
vifm 0.8.2~beta build failure

### ISSUE THREAD

**Issue by onovy** [vifm/vifm#191]
Hi,

I'm trying to build new package for Debian, and unit tests is failing for me:

```
------------------------ filetype/filetype.c -------------------------

pattern_list:
   (-) filetype/filetype.c:158
       in test body
       Expected "prog" but was <NULL>

                           13 run  1 failed

------------------------- filetype/viewers.c -------------------------
   (-) filetype/viewers.c:102
       in test body
       Expected "prog1" but was <NULL>

                           6 run  1 failed

============================ STIC v0.5.2 =============================

                           Failed 2 checks
                             35 tests run
                               in 15 ms
```

Thanks for fixing.

**Comment by xaizek** [comment]
Hi,

Could you apply the following and see how output is changed?
```diff
 tests/filetype/filetype.c | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/tests/filetype/filetype.c b/tests/filetype/filetype.c
index 4f4286b..66466d7 100644
--- a/tests/filetype/filetype.c
+++ b/tests/filetype/filetype.c
@@ -150,9 +150,12 @@ TEST(zero_length_match)
 	assert_null(prog_cmd = ft_get_program("git"));
 }
 
+#include "../../src/int/file_magic.h"
 TEST(pattern_list, IF(has_mime_type_detection))
 {
 	set_programs("<application/octet-stream>{binary-data}", "prog", 0, 0);
+	assert_string_equal("application/octet-stream",
+			get_mimetype(TEST_DATA_PATH "/read/binary-data"));
 
 	assert_string_equal("prog",
 			ft_get_program(TEST_DATA_PATH "/read/binary-data"));
```
I tried various sources of mime-types and they all give this result, I don't understand how you get different one. It's easy to work around in tests, but I'm wondering what does it return (maybe it's more  subtle issue and not just tests should be updated).

**Comment by jubalh** [comment]
Just as a side note:
All tests pass for me (on openSUSE Tumbleweed). No problems at all so far.

**Comment by onovy** [comment]
after patch:
```
------------------------ filetype/filetype.c -------------------------

pattern_list:
   (-) filetype/filetype.c:159
       in test body
       Expected "application/octet-stream" but was "image/x-tga"
   (-) filetype/filetype.c:162
       in test body
       Expected "prog" but was <NULL>

                           13 run  2 failed

------------------------- filetype/viewers.c -------------------------
   (-) filetype/viewers.c:102
       in test body
       Expected "prog1" but was <NULL>

                           6 run  1 failed
```

Maybe I'm missing any dependency?

**Comment by xaizek** [comment]
@jubalh, thanks for the note, have stable results on various systems too, so this got me surprised.

@onovy, thanks, there is just something in mime database that determines 00-01-02-... kind of data as TGA. I'll either try file filled with zeros (still can fail, so probably won't do this) or query mime-type in tests instead of hard-coding it.

**Comment by xaizek** [comment]
@onovy, please see if f3a94c1a5c347d973db591da27601deb7730c3c1 fixes tests for you. It should, but as I had to emulate the failure, changes might be incomplete.

**Comment by onovy** [comment]
this commit fixies tests for me and i built sucessfull on amd64. I uploaded it to Debian experimental, and let's see what happens on other archs

Thanks for really fast response and fix.
