### ISSUE TITLE
Request for fzf integration.

### ISSUE THREAD

**Issue by Losiara** [vifm/vifm#192]
There is nice command line fuzzy search - fzf.
Is it possible to integrate it in vifm?
Does anybody has experience?

**Comment by xaizek** [comment]
There is related question at [q2a site](http://q2a.vifm.info/156/use-external-program-to-find-and-select-a-file), see if answer there does what you want.

**Comment by Losiara** [comment]
Thanks!

**Comment by Losiara** [comment]
When I do this command, fzf works, but after that arrow keys on keyboard are broken. Arrow up tries to rename file, right arrow try to move etc.

> `command! fzf :execute '!fzf 2>&0 %%U' | normal! gf`

**Comment by xaizek** [comment]
You're right, didn't notice that fzf breaks them. Pushed a small patch that seems to restore the keys. There are still some side effects after using fzf (copy of screen is left after quitting), but not sure how to work around those. It actually shouldn't leave terminal in changed state in the first place, but it does, which affects curses.

**Comment by xaizek** [comment]
Didn't want to do this initially, but have no other choice but to add a couple of new macros to be used with interactive commands (`%Iu` and `%IU`, which work the same as `%u` and `%U`). fzf doesn't do anything wrong, it uses curses correctly and ruby bindings for it is fine, apparently previous application that used curses should give up the terminal or it won't be able to restore it properly afterward.

Thus the command to use with development version or the next release is this:
```
command! fzf :execute '!fzf 2>&0 %%IU' | normal! gf
```
