### ISSUE TITLE
Mapping for dialogs

### ISSUE THREAD

**Issue by sassanh** [vifm/vifm#194]
How can I apply a mapping to dialogs? For example when I hit `<c-m-s>` and it opens sort order dialog, I want to be able to exit the dialog with \` instead of `<esc>`.

**Comment by xaizek** [comment]
That's not possible at the moment. To quit dialogs <kbd>q</kbd> or <kbd>Ctrl-C</kbd> can be used as well.

Each dialog basically defines its own mode with keys having different meaning, so one common set of mapping commands is likely to produce conflicts when used and adding separate set of commands per dialog seems to be overkill. The third solution is to use different syntax, but that would be inconsistent. Given the flaws and low usefulness this wasn't implemented yet.

**Comment by sassanh** [comment]
I see, I think if we add a new mode "dialog" (`dmap`, `dnoremap`, etc) and warn users that they should only use mappings for this mode if they absolutely know what they're doing and then apply mappings in this mode on top of mappings of all dialogs it solves the problem. This way for example when I map ` to `<esc>`, if it breaks anything in an dialog I'd know it's my own fault. It just opens options for users to customize things currently is impossible to customize.

A first level easier implementation would be to add an option to apply "menu" mode mappings to dialogs to.

**Comment by xaizek** [comment]
You're probably right, there is already `mmap` command for all menus even though menus are of different kind and everything is fine.

**Comment by sassanh** [comment]
Sorry, I didn't get it, is `mmap` supposed to work on dialogs now? It doesn't seem to apply on dialogs.

**Comment by xaizek** [comment]
No, I was just pointing out that current situation with menu mappings is similar to proposed `dmap` commands.
