### ISSUE TITLE
Image preview support with ITerm

### ISSUE THREAD

**Issue by sassanh** [vifm/vifm#195]
Thanks for this great application.
It'd be great if vifm could support image preview with ITerm. ITerm 3 has a more robust image preview in terminal support (comparing to w3m method).

**Comment by xaizek** [comment]
If it doesn't conflict with curses, it should be possible to do it with external scripts just like with w3m. I don't want to hardcode something like this that works only on one platform in code. And as I'm not using OS X can't really help in implementing it, though all data to display the image should be present, just might need a way to get image/font dimensions and compose valid string containing escape sequences.

**Comment by sassanh** [comment]
I see, makes sense, thanks.

**Comment by sassanh** [comment]
@xaizek I tried to find out why ITerm's imgcat doesn't work with vifm, reading the source code I found out that you're writing data provided by the viewer program to stdout using functions like `view_stream` which uses`esc_print_line` which takes care of things like character width and escape code handling, etc. Is there anyway to print raw data provided by viewer at the desired position in screen? ITerm's protocol is straight forward and simple but it needs the ability to write raw data on screen.

**Comment by xaizek** [comment]
> Is there anyway to print raw data provided by viewer at the desired position in screen?

That's curses constraint, it doesn't pass escape codes directly to terminal that's why they are transformed into curses calls.

> ITerm's protocol is straight forward and simple but it needs the ability to write raw data on screen.

Wouldn't printing to `/dev/tty` instead of stdout work in this case?

**Comment by sassanh** [comment]
> Wouldn't printing to /dev/tty instead of stdout work in this case?

How can I check it? I think it should work if it passes all escape codes directly to terminal.

**Comment by xaizek** [comment]
Try redirecting imgcat output stream:
```bash
imgcat args... > /dev/tty
```

**Comment by sassanh** [comment]
It works.

**Comment by sassanh** [comment]
@xaizek Do you mind if I reopen this issue? Or should I create another one for supporting passing escape codes to terminal?

**Comment by xaizek** [comment]
> Or should I create another one for supporting passing escape codes to terminal?

I think this can't be done meaningfully in general case. Any escape sequence passed unbeknownst to curses can mess up the screen. At each moment in time curses should know it's exact state and if the invariant is broken, any further operations will lead to unpredictable state of the screen.

There are `putp` and `tputs` functions in the API, but I'm not sure if they can be used for this (didn't work for me with terminal title). Open a new issue if you wish, I'm not 100% sure whether passing escape codes is possible or not (except that it probably cannot work on Windows).
