### ISSUE TITLE
Function keys don't work in iterm2 - 3

### ISSUE THREAD

**Issue by sassanh** [vifm/vifm#197]
I can't map function keys, function keys work in vim, but not in vifm. It'd be great if there were a way to see the code vifm receives when pressing a key.
This is what pressing F1 to F10 produces in command mode:
```
:ĉĊċČčĎďĐđĒ
```

**Comment by sassanh** [comment]
But even mapping `ĉ` for example doesn't seem to work.

**Comment by xaizek** [comment]
> It'd be great if there were a way to see the code vifm receives when pressing a key.

vifm gets preprocessed results from curses, so it wouldn't be that helpful.

> :ĉĊċČčĎďĐđĒ

The codes match `265, 266, ...` which I see in ncurses header, so they should work if extended keys weren't disabled during the build. What's the output of
```bash
vifm --version | grep extended
```
?

**Comment by sassanh** [comment]
> What's the output of
> 
> vifm --version | grep extended
> ?

It's `Support of extended keys is on`. I've installed it via homebrew.

**Comment by xaizek** [comment]
And why do you think they don't work? They show up in command-line mode because they aren't mapped there and in this case treated as text. But mappings like
```vim
:nmap <f1> k
```
should still work fine.

**Comment by sassanh** [comment]
Yes there are working when I write the nmap directly in vifm. But there are these lines in my vifmrc:
```
nnoremap <f3> :!less %f<cr>
nnoremap <f4> :edit<cr>
nnoremap <f5> :copy<cr>
nnoremap <f6> :move<cr>
nnoremap <f7> :mkdir<space>
nnoremap <f8> :delete<cr>
```
And these are not working, If I copy one of these lines and write it down in vifm, then the related function key works. While it's reading other parts of vifmrc it's not applying these lines.

**Comment by sassanh** [comment]
@xaizek oh, never mind, I was overwriting these lines at the bottom of the vifmrc as I copied some parts of my vimrc to vifmrc. My bad. Thanks for all quick replies :-)
