### ISSUE TITLE
Inconsistent behavior for trailing spaces in maps

### ISSUE THREAD

**Issue by sassanh** [vifm/vifm#198]
If I add `nnoremap <c-a> :grep ` (notice the trailing space) to my vifmrc after hitting `<c-a>` it opens command line with `:grep` (no trailing space) but if I add `nnoremap <c-a> :grep\ ` (backslash added) after pressing `<c-a>` it'll open command line with `:grep\ ` (notice trailing space.). Is it a bug or is it following some rule? Vim itself adds trailing space in both cases.

**Comment by xaizek** [comment]
> Is it a bug or is it following some rule?

[Not really a bug](https://github.com/vifm/vifm/blob/f3fb64e3628fd8cd1f690e9add0e1644cb551b7c/data/vim/doc/app/vifm-app.txt#L3536-L3540), trailing spaces are always removed, but when you escape them, they become part of the command and thus are preserved. You can use `<space>` to make presence of the space obvious.

> Vim itself adds trailing space in both cases.

I'm not sure if we should follow Vim on this.  Command-line parsing is very inconsistent there, vifm generally parses arguments more like shell does (you can escape with `\`, use single or double quotes) with exceptions for some commands.

**Comment by sassanh** [comment]
I see, thanks for info then I think `nnoremap <c-a> :grep\ ` should result in `:grep ` not `:grep\ `, the backslash should be omitted if it's escaping space.

**Comment by sassanh** [comment]
Using `<space>` as you suggested and is well documented is indeed better way to achieve this.

**Comment by xaizek** [comment]
> I see, thanks for info then I think nnoremap <c-a> :grep\ should result in :grep not :grep\, the backslash should be omitted if it's escaping space.

Hm, that's actually an inconsistency with argument processing. Escape sequence affects spaces, but is not replaced. And we shouldn't actually replace anything in RHS of a mapping, so looks like `nnoremap <c-a> :grep\ ` (with a space) should be `:grep\` (without a space) in this case.

**Comment by sassanh** [comment]
I see, I think generally it's better to encourage using `<space>` as you mentioned and the inconsistency with argument processing is not really that important. I guess we can close this if you think so too.

**Comment by xaizek** [comment]
Agreed. Thanks for pointing this out. It will appear in the BUGS file then, so it can be fixed at some point.
