### ISSUE TITLE
ifm: filelist.c:2437: add_to_trie: Assertion `error == 0 && "Duplicated file names in the list?"' failed.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#199]
Vifm 0.8.2-1 from Debian.

1. Have files named like "41.jpg", "42.jpg" etc up to "79.jpg".
Example: `touch {4,5,6,7}{0,1,2,3,4,5,6,7,8,9}.jpg`
2. Starting Vim to rename them (cw).
3. Select a block with all the numbers.
4. Enter 1, 0, then Ctrl-X, then ZZ.

Files are renamed, but Vifm crashes:

```
vifm: filelist.c:2437: add_to_trie: Assertion `error == 0 && "Duplicated file names in the list?"' failed.
```

**Comment by xaizek** [comment]
Asserts for me only with Ctrl-A, but it's the same error. It doesn't fail if doing the same from vifm though. Thanks for the report.
