### ISSUE TITLE
Select in different folders

### ISSUE THREAD

**Issue by jubalh** [vifm/vifm#200]
If I use `t` to select a file, then go some directories up and select two more.
Then use `yy` to yank them and then go to the destination folder and paste them via `p` it only pastes the recently selected ones.

I suppose that this behaviour is intended. But it would be useful to select files from multiple directories.

Maybe I used something wrongly?

**Comment by xaizek** [comment]
That's how it should work. Selection is a property of current view. If you want to collect files instead, then do:
1. <kbd>"ayy</kbd> (lowercase register) in first directory
2. <kbd>"Ayy</kbd> (uppercase register) in others
3. Then paste all files using <kbd>"Ap</kbd>, <kbd>"ap</kbd> or just <kbd>p</kbd> (if you didn't copy anything more to any other register).
This is the same as appending to registers in Vim.

Alternatively you could use `:tree` and work with files in multiple directories for a while (mind that depth can't be controlled yet, so whole file system sub-tree will be loaded, thus you probably don't want to do this near `/`).

**Comment by jubalh** [comment]
Thank you! That suites my use case.
`:tree` is only available after 0.8.2 I suppose. Will do a git build soon.

**Comment by aca** [comment]
@xaizek Is it still impossible to do this action?
I think it is very natural to select multiple files while navigating directories and do some operations for all selected ones.

By the way, thanks for the great program.

**Comment by xaizek** [comment]
Selections is still part of the state of a view. I'm not sure if adding support for files in multiple location is feasible, it might need very different handling of selection compared to how it's done now.

You can collect files in a register and then construct a custom view out of them for further processing using something like `:!printf '%%s\n' %ra %u` (`%ra` is expanded to contents of register `a`).
