### ISSUE TITLE
vifm --remote --select doesn't update status bar

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#202]
While `vifm --remote --select FILE` does select the target file, the file number in the status bar is not updated. It's updated only after I move to another file for example with <kbd>j</kbd> or <kbd>k</kbd>.

**Comment by xaizek** [comment]
Yes, I can reproduce it, ruler is updated only when `--select` picks file outside current directory. Thanks for the report.

**Comment by rr-** [comment]
Thanks
