### ISSUE TITLE
Ability to target specific vifm instance with --remote

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#203]
I think the following interface would be reasonable:

- add optional `--remote-pid` which is used to disambiguate vifm instances
- add `pid` variable that can be used in commands, bindings etc.

**Comment by xaizek** [comment]
> add optional `--remote-pid` which is used to disambiguate vifm instances

There is already [`--server-name`](https://vifm.info/vimdoc.shtml#vifm---server-name) option. You can use it both when starting vifm and when sending command to already running instance.

> add pid variable that can be used in commands, bindings etc.

Querying `--server-name` value isn't available though.

**Comment by rr-** [comment]
Being able to query it would be awesome, plus making server name random if there's none passed.

**Comment by xaizek** [comment]
There is `v:servername` as in Vim now. If you want to use its value in commands and bindings, it might be easier to do with environment variable, which can be set in `vifmrc` like this:
```vim
let $SERVER_NAME = v:servername
```
