### ISSUE TITLE
Slow startups with full remote trash

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#204]
This is a bit exotic, but having many files in trash for a SSHFS share results in slow startup and exit. `strace` reveals that vifm is calling `lstat` on each file.

I've emptied the trash so this is a non-issue for me anymore, but I thought it was worth reporting here anyway.

**Comment by rr-** [comment]
This also affects `--remote --select`.

**Comment by xaizek** [comment]
Do I get it right that your setup involves permanently mounted sshfs directory and you removed some files within that mount?

`lstat()` is used to check for file existence so that if file is removed by another instance or any other application it doesn't stay in `vifminfo` nor it's shown by `:lstrash` or (indirectly) by `:trash`. Maybe `access()` + `lstat()` can be used for optimization. Can't just throw away the check because then vifm knowledge about the trash can diverge from its actual state and postponing such validation doesn't sound like a really good idea (this delay will happen at some point anyway).

**Comment by rr-** [comment]
>Do I get it right that your setup involves permanently mounted sshfs directory and you removed some files within that mount?

Yep

Can't it be performed in a background thread?

**Comment by xaizek** [comment]
> Can't it be performed in a background thread?

Well, everything can be done in background thread :), but it's very strange to put check for file existence in background and will significantly complicate code for relatively small benefit.

By the way, how many files do you have in the trash?

**Comment by rr-** [comment]
>By the way, how many files do you have in the trash?

A few thousands small files is pretty normal; I started to make a habit of using `:d!` but it's less convenient than `dd` + occasional `:empty`.

**Comment by rr-** [comment]
Hmm, maybe I could script vifm to prune the files in the recycle bin that match certain regex?

(:D)

**Comment by xaizek** [comment]
> A few thousands small files is pretty usual here;

That suggests why you might experience slowdown... After adding some checks for dealing with symbolic links, complexity of adding new item to trash became O(n<sup>2</sup>) in file system operations, it's bad in general, yet not significant for local trash, but seems to be awfully slow with sshfs. I'll optimize this and see if it'll become usable with sshfs.

> I started to make a habit of using `:d!`

There is <kbd>DD</kbd> key with the same effect.

> Hmm, maybe I could script vifm to prune the files in the recycle bin that match certain regex?

No means for doing this at the moment (although you could disable `'trash'` option for a subtree), and it won't help the general case.

**Comment by xaizek** [comment]
Ended up removing file existence checks. Seems to be way faster without them. Now trash can show already removed files, but `:empty` should clean everything up.

**Comment by rr-** [comment]
Thanks :+1:

**Comment by rr-** [comment]
Oh man, it's blazing fast once again. :+1:
