### ISSUE TITLE
Auto mount other partitions or devices

### ISSUE THREAD

**Issue by blurm** [vifm/vifm#206]
Since I just use linux for a short time, nautilus under ubuntu is an easy choise. 
It will display all the partitions in different file systems, like NTFS in windows.
When you open it, it will be automatically mounted

Is there any way vifm can auto mount devices when opened?
I check the Automatic FUSE mounts part in manual, still quite confused

Right now all  i can do is define key mapping for mount command under shell

**Comment by xaizek** [comment]
There is nothing builtin like that. The closest thing might be to use autofs (not sure how well suited it is in this case though).

Managing media was [requested before](https://sourceforge.net/p/vifm/feature-requests/30/) on SourceForge and I remember exploring ways to do this. The upshot was that every system tends to do this differently and there is no easy way to handle all of them. There were some libraries, but their abilities weren't enough or they did way too much. And so it was left unimplemented.

**Comment by blurm** [comment]
Thanks for the reply, guess I will stick with manually mount right now, will check autofs later
