### ISSUE TITLE
Could't find the correct script for Image Preview

### ISSUE THREAD

**Issue by blurm** [vifm/vifm#207]
The image preview doesn't work. When the cursor below img file, only text info showed
I guess I didn't get vifm configured properly, the script wasn't invoked at all, but I couldn't find where the problem is. 
Would  you please help me out?

#### w3m worked well
The path is /usr/lib/w3m/w3mimgdisplay
I run:
```
echo '5;screenshot.jpg' | /usr/lib/w3m/w3mimgdisplay
```
print:1680,1050

#### The scripts
I copied from https://wiki.vifm.info/index.php?title=How_to_preview_images
Created `imgc.sh` and `imgt.sh` under ~/.config/vifm/scripts
Here is the `imgt.sh`, basically just change the w3m path:
```shell
#!/bin/bash
#
# Based on script by z3bra -- 2014-01-21
 
W3MIMGDISPLAY="/usr/lib/w3m/w3mimgdisplay"
FONTH=15 # Size of one terminal row
FONTW=7 # Size of one terminal column
 
X=$1
Y=$2
COLUMNS=$3
LINES=$4
FILENAME=$5
 
read width height <<< `echo "5;$FILENAME" | $W3MIMGDISPLAY`
if [ -z "$width" -o -z "$height" ]; then
    echo 'Error: Failed to obtain image size.'
    exit 1
fi
 
x=$((FONTW * X))
y=$((FONTH * Y))
 
max_width=$((FONTW * COLUMNS))
max_height=$((FONTH * LINES))
 
if [ "$width" -gt "$max_width" ]; then
    height=$((height * max_width / width))
    width=$max_width
fi
if [ "$height" -gt "$max_height" ]; then
    width=$((width * max_height / height))
    height=$max_height
fi
 
w3m_command="0;1;$x;$y;$width;$height;;;;;$FILENAME\n4;\n3;"
 
echo -e "$w3m_command" | $W3MIMGDISPLAY
```

#### The Config
The img part:
```
" Images
filextype *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
        \ {View in sxiv}
        \ sxiv %f,
        \ {View in gpicview}
        \ gpicview %c,
        \ {View in shotwell}
        \ shotwell,
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ imgt %px %py %pw %ph %c
         \ %pc
         \ imgc %px %py %pw %ph
```

**Comment by xaizek** [comment]
Can you show `ls -l ~/.config/vifm/scripts`? Or just check that scripts have executable bit set.

**Comment by blurm** [comment]
Thanks for the hint.. damn I'm so stupid. The preview script worked

- The preview area is not exactly in another pane
- If I change to other image or directory, all of them overlapped

Then I changed `$FONTH` and `$FONTW` to 20 and 10 in imgt.sh, leave them as 15 and 7 in imgc.sh, now it looks fine.
But still not quite sure imgc.sh executed

**Comment by xaizek** [comment]
The `$FONTH` and `$FONTW` should be the same in both scripts and match parameters of your font (there is a way to figure them out automatically, but it didn't work reliably if I remember correctly). And you don't need the imgc.sh if clearing works without it (like in xterm).

**Comment by blurm** [comment]
I removed imgc.sh from config, it worked just the same.
Btw, i'm using gnome-terminal.

Thanks for your great work. This is really a better choise for a vimer than mc!

**Comment by blurm** [comment]
Another quick question if you don't mind, is there any way I can cancel an background process, like copy something in big size?

**Comment by xaizek** [comment]
> is there any way I can cancel an background process, like copy something in big size?

Only by quitting... It shouldn't be hard to add though, at least for implementation on system calls the cancellation code is there, just not plugged to the interface (<kbd>dd</kbd> in `:jobs` menu probably should do this).

**Comment by blurm** [comment]
> dd in :jobs menu probably should do this
That's a good idea, hope it can be used in next release:)
