### ISSUE TITLE
Opening pdf files with vifm problem

### ISSUE THREAD

**Issue by jbelmont** [vifm/vifm#21]
I am using a macbook with MAC OS X 10.7 and mac terminal program.
I successfully compiled newest version of vifm. Here is my configured options:

```
Version: 0.7.5-beta
Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
```

Here is the pdf snippet in my .vifm/vifmrc file for the pdf opening option

```
filetype *.pdf acrobat %f& (where acrobat is symbolic link to /Applications/Adobe Acrobat X Pro/Adobe Acrobat Pro.app
```

when I press enter which I have enabled in vifmrc  with set norunexec
vifm goes back to terminal shell but does not open any pdf file. 
How should I set pdf files for mac os x so that when I press enter it will open with my
specified application.

Sincerely,

Jean-Marcel Belmont

**Comment by acsdev** [comment]
I could do it by change my vifmrc like this.

filextype *.pdf xreader %f
fileviewer *.pdf xreader-previewer
