### ISSUE TITLE
Ability to set :fileviewer per directory

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#211]
Trying to use:
```
fileviewer *.txt cat
autocmd DirEnter hub :fileviewer *.txt tac
```
as well as more reasonable 
```
autocmd DirEnter hub :fileviewer *.txt tac
autocmd DirEnter !hub :fileviewer *.txt cat
```

doesn't seem to work. The file is always shown normally, not through `tac` regardless of the directory I'm in or I start with, one pane or both panes.

In fact, `:fileviewer` seems to work only if I don't use `autocmd`. `autocmd` itself works though, which can be seen if I use some other command such as `:quit`. This theory can be further backed by this example:
```
fileviewer *.test tac
fileviewer *.test cat
```
Here, `*.test` files are shown using `tac` regardless of the later declaration that inuitively should override the prior one.

Also for this to work reliably, we probably need a way to set `:fileviewer` separately for each pane; using `:setg` and `:setl` would make most sense. (`:fileviewer` could fallback to `:setg fileviewer` for backwards compatibility.)

**Comment by xaizek** [comment]
`:fileviewer` appends to the list of viewers (use `:fileviewer *.txt` to see the current list) and as long as first command is available, the rest won't be used. That's why you observe such effects. It needs some form like `:fileviewer!` to remove previous definitions to do what you want.

> Also for this to work reliably, we probably need a way to set :fileviewer separately for each pane

Yes, but why do you want to have different viewers in different directories? I can't think of a situation where I'd need such setup.

> using :setg and :setl would make most sense

I'd disagree, `:setlocal` and `:setglobal` work only with options and already have quite complex syntax. `:fileviewer` should be used almost always from `vifmrc`, so there shouldn't be much use for global version after startup.

**Comment by rr-** [comment]
Regarding the use case, I want to query files via a certain API. The API is relevant only for specific kind of files, that are put only in specific directory.
I made a script that performs such queries outside vifm for selected files, but it's cumbersome to manage the files afterwards - I need to look at the output and copy my actions to vifm. It'd be pretty cool if I was in vifm, and had the file already selected to begin with.

I forgot about the cycling properties of `:fileviewer` - maybe I could make a wrapper that does `exit 1` if `$1` doesn't contain `"hub/"`?

**Comment by xaizek** [comment]
> maybe I could make a wrapper that does exit 1 if $1 doesn't contain "hub/"?

It won't work. Commands aren't executed until first one succeeds (these could easily fire up multiple programs at the same time), they are just checked for presence in `$PATH` or by relative/absolute path.

You could have one `:fileviewer` with a wrapper command and check for `hub/` in that wrapper. Or, if you can add new files to current directory, create `custom-viewer` script there and do `:fileviewer *.txt ./custom-viewer`.

**Comment by rr-** [comment]
Thanks, I'll implement one of these solutions (I'll probably go with a single wrapper approach since the script works on a few machines, so it'll be easy to version it)
