### ISSUE TITLE
vifm file preview matching mime type gets messed up with certain symlinks

### ISSUE THREAD

**Issue by aroig** [vifm/vifm#213]
I did the following steps with the gtk code-path for the mime-type disabled (`--without-gtk`) in order to constrain the problem.

## Steps to reproduce

Setup a directory tree like this

        A/A.mp3
        B/B.mp3

where the second file is a symlink to the first.

Add a fileviewer configuration based on mime type

        fileviewer <audio/*,video/*> echo 'HELLO'

When opening vifm on `B/`, and triggering a file preview with 'w', nothing is shown. On the other hand, if the symlink is placed in `A/B.mp3`, the preview works fine.

Trying to get the mime type with `file` tells me `inode/symlink`, so I'm not even sure why this works sometimes. Maybe libmagic works for the `A/B.mp3` symlink and fails for `B/B.mp3`, falling back to `file`?

I assume that resolving symlinks before trying to determine the mime type would be a good idea anyways, and would probably fix this bug.

**Comment by xaizek** [comment]
Thanks for the report. Symbolic links are resolved before checking for file viewer, but there are pieces of some old code which discarded directory name leaving only base name, which isn't enough for determining mime-type as it needs to open the file.
