### ISSUE TITLE
vifm crashes trying to preview certain symlinks with long target file

### ISSUE THREAD

**Issue by aroig** [vifm/vifm#214]
vifm crashes when previewing certain symlinks. This is what I found up to this point. It looks like somewhere a buffer is overflown.

I think it is the code path shelling out to file that triggers this, but I have no time to dig it further right now.

## Steps to reproduce

I use arch linux. Arch compiles its binaries with with FORTIFY_SOURCE=2. And this is what seems to detect the overlow. So, compile vifm with this, and disabling the gtk backend:

        export CPPFLAGS="-D_FORTIFY_SOURCE=2"
        ./configure --without-gtk --with-libmagic
        make

Then configure a fileviewer based on mime type, for example

        fileviewer <audio/*,video/*> echo 'HELLO'

Now setup a directory structure like this:

        A/11111111111111111111111111111111111111111222222222222222222222222222222222223333333333333333333333333333.mp3
        B/123.mp3

Where the second is a symlink to the first. Then open vifm on B/ and trigger a file preview with w.

On my machine it crashes with the folowing stack trace

        #0  0x00007ffff73c304f in raise () from /usr/lib/libc.so.6
        #1  0x00007ffff73c447a in abort () from /usr/lib/libc.so.6
        #2  0x00007ffff7400c50 in __libc_message () from /usr/lib/libc.so.6
        #3  0x00007ffff7488f17 in __fortify_fail () from /usr/lib/libc.so.6
        #4  0x00007ffff7487050 in __chk_fail () from /usr/lib/libc.so.6
        #5  0x00007ffff74863b2 in __strcpy_chk () from /usr/lib/libc.so.6
        #6  0x0000000000417cf7 in strcpy (__src=<optimized out>, __dest=0x6cbb40 <mimetype> "cannot open `B/' (No such file or directory)") at /usr/include/bits/string3.h:110
        #7  get_magic_mimetype (buf=0x6cbb40 <mimetype> "cannot open `B/' (No such file or directory)", filename=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3")
    at int/file_magic.c:133
        #8  get_mimetype (file=file@entry=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3") at int/file_magic.c:66
        #9  0x0000000000440308 in matcher_matches (matcher=0x868430, path=path@entry=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3") at utils/matcher.c:330
        #10 0x000000000044092e in matchers_match (matchers=0x85cb20, path=path@entry=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3") at utils/matchers.c:178
        #11 0x0000000000464b70 in find_existing_cmd (record_list=record_list@entry=0x6e8170 <fileviewers>, file=file@entry=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3")
    at filetype.c:106
        #12 0x0000000000464c6d in ft_get_viewer (file=file@entry=0x993780 '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3") at filetype.c:91
        #13 0x00000000004375d0 in qv_get_viewer (path=path@entry=0x7fffffffaa50 "/home/abdo/opt/tmp/test/test2/B/../A/", '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3")
    at ui/quickview.c:682
        #14 0x0000000000437740 in view_file (path=0x7fffffffaa50 "/home/abdo/opt/tmp/test/test2/B/../A/", '1' <repeats 28 times>, '2' <repeats 27 times>, '3' <repeats 29 times>, ".mp3") at ui/quickview.c:203
        #15 view_entry (entry=entry@entry=0x9993e0) at ui/quickview.c:188
        #16 0x00000000004379e8 in quick_view_file (view=view@entry=0x6bdbe0 <lwin>) at ui/quickview.c:145
        #17 0x00000000004367ca in fview_position_updated (view=view@entry=0x6bdbe0 <lwin>) at ui/fileview.c:1640
        #18 0x00000000004669b8 in flist_set_pos (view=<optimized out>, pos=1) at flist_pos.c:139
        #19 0x000000000040febf in execute_mapping_handler (key_info=..., keys_info=keys_info@entry=0x7fffffffbd70, info=<optimized out>) at engine/keys.c:1129
        #20 0x0000000000410372 in dispatch_key (key_info=..., keys_info=keys_info@entry=0x7fffffffbd70, curr=curr@entry=0x849ed0, keys=keys@entry=0x7fffffffbe24 L"") at engine/keys.c:623
        #21 0x0000000000410991 in execute_next_keys (curr=curr@entry=0x849ed0, keys=keys@entry=0x7fffffffbe24 L"", key_info=key_info@entry=0x7fffffffbcb0, keys_info=keys_info@entry=0x7fffffffbd70, 
    has_duplicate=<optimized out>, no_remap=no_remap@entry=0) at engine/keys.c:610
        #22 0x0000000000410d6b in dispatch_keys_at_root (keys=0x7fffffffbe24 L"", keys_info=keys_info@entry=0x7fffffffbd70, root=<optimized out>, key_info=..., no_remap=no_remap@entry=0) at engine/keys.c:424
        #23 0x0000000000410edf in dispatch_keys (keys=<optimized out>, keys@entry=0x7fffffffbe20 L"Ă", keys_info=keys_info@entry=0x7fffffffbd70, no_remap=no_remap@entry=0, prev_count=-1) at engine/keys.c:328
        #24 0x0000000000410fc8 in execute_keys_general (keys=0x7fffffffbe20 L"Ă", timed_out=<optimized out>, mapped=0, no_remap=0) at engine/keys.c:296
        #25 0x00000000004112c7 in execute_keys_general_wrapper (no_remap=0, mapped=0, timed_out=0, keys=keys@entry=0x7fffffffbb90 L"Ā ") at engine/keys.c:276
        #26 vle_keys_exec (keys=keys@entry=0x7fffffffbe20 L"Ă") at engine/keys.c:245
        #27 0x0000000000454d44 in event_loop (quit=quit@entry=0x48ee9c <quit>) at event_loop.c:230
        #28 0x000000000040568d in main (argc=<optimized out>, argv=<optimized out>) at vifm.c:293

## Weird things

* I can only make it crash with a symlink that "goes back one directory" AND the symlink target is large. I couldn't make it crash with either one of them separately.

* Only the `fileviewer` thing seems to crash. The `filextype` thing with the same mime pattern opens the file allright.

* It may be related to #213, however I'm pretty sure the overflow is independent of #213, and fixing it first would probably mask this problem, because either gtk or libmagic would handle the mime type.

EDIT: I had posted the wrong stack trace previously
EDIT2: Reposted the stack trace again, now using the same file names as in the issue.

**Comment by xaizek** [comment]
Very detailed description, thanks! #213 is related in the following way: because it causes libmagic to work on nonexistent file it didn't just return failure, but provided error message stating "can't open file &lt;long file name here&gt;", which was too long for small static buffer, which was supposed to hold only short mime types.

**Comment by aroig** [comment]
Aha! So, both are the same thing after all.
