### ISSUE TITLE
Capture stdout of a program into a :view

### ISSUE THREAD

**Issue by svenn71** [vifm/vifm#217]
Looking at a file in :view mode, I suddenly got the wish to do a :!git log %c and capture the output of that command into the :view pane. How can this be done? I tried :!git log %c %u but got a message that the file list is empty. %u/%U is expecting a file list, I read from the manual.

**Comment by xaizek** [comment]
Such functionality isn't available at the moment, although `%m` is quite close. It's in the [TODO list](https://github.com/vifm/vifm/blob/a386171f02325728e4a710aa90d44b85b8809630/TODO#L126) as far as I remember for a similar reason, but I wanted to do `git status`. Now I think that maybe it should be view mode instead (like the one on pressing <kbd>e</kbd>), because with `:view` it's not clear when to reset it to usual state (you might want to go to a different file and either left that information in the view or display that different file there).

**Comment by svenn71** [comment]
I didn't know about the 'e' function, but that one is replacing the current pane with the view pane in my configuration. I really like the 'w' version of viewing files as I move up and down filelist/hierarchy in one pane, and look at the contents of that file in the other pane. git log -- file or git blame -- file is something I use quite frequently on a large number of files, and then the replacement of filelist with the contents as in 'e' is a bit tedious. I am generally using the program tig for git diff/status/add/commit things.

Even more useful for svn things as there are few good svn tools for command line, and svn log file on command line needs the extra |less at the end to see the current log entries.

I don't know, but maybe a generic way of putting the stdout of *any* program to the other pane in view mode would solve most feature requests of the kind I am asking for here.

**Comment by xaizek** [comment]
> I didn't know about the 'e' function, but that one is replacing the current pane with the view pane in my configuration.

Yes, but there can be two macros to put output of a program to either of two panes.

Actually `:view` can work fine too, it will just dismiss the output on selecting different file.

**Comment by svenn71** [comment]
Will a 'git log' :view be presistent? By that I mean will I be able to move up and down between files and see the git log of the files, or will I have to invoke a macro each time to view the git log instead of the file contents? I see that I have mapped 'w' to :view<cr> and that one is persistent accross files. When I do git log and git blame, I am normally doing this on various files for a while and it would be nice if it is possible to stay in that mode when switching file and not need to invoke the macro each time. But I can live with retyping macros if vifm doesn't support such a persistent mode.
Dismissing the output of 'git log/blame/diff -- %c'  when changing files is wanted behaviour I think.

**Comment by xaizek** [comment]
> will I be able to move up and down between files and see the git log of the files, or will I have to invoke a macro each time to view the git log instead of the file contents?

The latter. Unless there will be an auto-command event for cursor movement, which would enable rerunning the command automatically.

**Comment by xaizek** [comment]
`%q` macro has been added, so you can now do (if you use development version):

     :!git log --color -- %c

If there is a lot of output, use one of <kbd>CTRL+W</kbd> combinations (e.g. <kbd>CTRL+W</kbd><kbd>CTRL+W</kbd>) to activate that pane and be able to scroll and search there. Leave the view in a similar way with <kbd>CTRL+W</kbd> (<kbd>q</kbd> will discard the output).

The macro makes sense on it's own so I implemented it, but command is not permanent. Useful auto-command or something else might be added later (auto-command just won't conflict with anything else, albeit it might not be the best solution, hence the hesitation).

One possible way of using new macro is this:
```vim
" 1. Execute this to "remember" the command
"     :preview git log --color -- %%c
" 2. Go up and down with j/k
" 3. Reset the command by running
"     :preview
command! preview : if '%a' == ''
               \ |     nunmap j
               \ |     nunmap k
               \ | else
               \ |     execute 'nnoremap j j:!%a %%q<cr>'
               \ |     execute 'nnoremap k k:!%a %%q<cr>'
               \ |     execute '!' expand('%a') '%%q'
               \ | endif
```
But there is flickering, same issue might be with the auto-command.

**Comment by svenn71** [comment]
When I do
:!git log --color -- %c
I see nothing exciting in the view pane.
If I do
:!git log --color -- %c %q
The git log is showing up in the view pane. That looks like what the third execute line in the preview macro does.

**Comment by xaizek** [comment]
My bad, it should be with `%q` of course.

**Comment by xaizek** [comment]
I think I found a better solution than introducing an autocommand. We can introduce a local option that will have priority over preview programs set via `:fileviewer`.

This way running `:setl previewprg='git log %c'` will set this command to do previewing until directory is changed and running `:set previewprg='git log %c'` will make it work across directories until the option is reset back to an empty string. This seems to be more manageable than autocommands, while providing the desired persistence.
