### ISSUE TITLE
windows 10: vifm does not adjust size right when the terminal size changes

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#218]
Finally, on windows 10, the size of the default terminal program can be dynamically adjusted. Yet, vifm seems not take it into account: once the terminal size is changed, vifm would show a black screen. When hit `ga`, vifm will force the terminal to go back to its original size. It would be good if vifm knows how to handle terminal size change: at least it is the default behavior on linux.

Thanks.

**Comment by xaizek** [comment]
The solution isn't perfect and has a glitch (when terminal height shrinks quickly, scroll appears, but vifm later adjusts its size to window size), but seems to be better than before anyway and should work properly unless you try to break it intentionally. I have an idea what might fix the glitch, but it's too much of a crutch, so using official way of handling terminal resize.

Builds with these changes: [32-bit](http://builds.vifm.info/builds/vifm-w32-se-v0.8.2-417-g19435b9c3283.exe), [64-bit](http://builds.vifm.info/builds/vifm-w64-se-v0.8.2-417-g19435b9c3283.exe).
