### ISSUE TITLE
Case insensitive autocomplete

### ISSUE THREAD

**Issue by alegen** [vifm/vifm#221]
In my shell I use case insensitive autocomplete, especially for the cd command. I was trying to get the same behavious in vifm and I could not find anything in the help file.

While going through the code, I noticed that there is a function called strnoscmp in src/utils/str.c, line 355 which calls the platform specific function. I believe the intention is to use strncmp for WIN32 and strncasecmp for other platforms, but the code was the opposite.

Function strncasecmp in turn allows the case insensitive autocomplete I was looking for.

**Comment by alegen** [comment]
Link to submitted pull request which fixes this issue - https://github.com/vifm/vifm/pull/220

**Comment by xaizek** [comment]
As I mentioned in #220, changing `strnoscmp()` will affect too much. Only completion should be changed, but before that we need to figure out the exact behaviour you wish to have. Should completion be case insensitive only for paths or for everything? The default behaviour won't be changed (while sometimes convenient, usually completion of paths is case-sensitive on *nix systems), but need to know the scope of configuration option.

P.S. You don't need to cross link, GitHub adds the link in opposite direction automatically.

**Comment by alegen** [comment]
Yes I see your point. In principle I was trying to get completion for cd to be case insensitive, but things like globbing would also be nice. I will poke some more through the code and see how far I get in the meantime.

Thanks for the quick reply and for the pro-tip :+1: :)

**Comment by xaizek** [comment]
Globbing is already always case insensitive. In general there are these kinds of completion:
- `:commands`
- Arguments of `:commands`.
- `'option'`s.
- Values of `'option'`s.
- Current value of `'option'`.
- `:!external` commands
- File/directory names.

There was vim/vim#991 where Bram mentioned more granular control over case sensitivity. He's talking about several options, but I think that there can be one option that controls case sensitivity of different things. I want to be able to control case sensitivity of <kbd>f</kbd>/<kbd>F</kbd> to make it ignore `'ignorecase'`/`'smartcase'` options for a long time, the same option can be used to control completion of paths and maybe other things (those that are useful). Not sure about the syntax of the option yet, but as we have at least two use cases, it's probably worth adding.

If you really want to see it in the code, look at `src/cmd_completion.c` file.

**Comment by xaizek** [comment]
Implemented `'caseoptions'` option, put the following to your `vifmrc` to get case insensitive path completion:
```vim
set caseoptions=p
```
