### ISSUE TITLE
vifm does not open files that contain a colon in the filename

### ISSUE THREAD

**Issue by aroig** [vifm/vifm#222]
When I try to open a file whose name contains a colon, vifm just opens a web browser, instead of the file with the associated program.

To reproduce, just create a file `A:B.txt` and try to open it from within vifm.

This happens with current master.

**Comment by xaizek** [comment]
What's the output of
```
:filetype A:B.txt
```
?

**Comment by aroig** [comment]
Yes, it is `xdg-open`. And yes, he is guilty! I was misled because tested xdg-open through a shell shortcut that resolves symlinks on the arguments. It turns out xdg-open swallows colons if path is absolute.

So, maybe a way in vifm to get absolute paths for the external commands would be enough.

**Comment by aroig** [comment]
Ok, I'm doing

    filetype * realpath -z %f | xargs -0 xdg-open

and declare victory. I close this issue then... sorry for the noise.

**Comment by xaizek** [comment]
Haven't thought about prepending `./`, will know the workaround now, thanks.
