### ISSUE TITLE
$PWD at startup

### ISSUE THREAD

**Issue by durcheinandr** [vifm/vifm#223]
There are a few ways I start vifm. `vifm`, `vifm .`, `vifm /path` and `vifm /path1 /path2`. Sometimes I want to quickly go back to the directory from which vifm was started. Easy Task I thought, but unfortunatly calling `:echo system ('echo $PWD')` just echoes the directory of the actual window. Any hints how to jump quickly to the directory from which vifm was started?

**Comment by xaizek** [comment]
> :echo system ('echo $PWD')

`$PWD` is set before invoking external applications, but inside vifm it isn't changed*, so

```vim
:echo $PWD
```
will probably give you original directory and
```vim
execute 'cd' $PWD
```
will navigate to it.

-------------
\* Turns out that `execute 'cd' $PWD` is not equivalent to `cd $PWD`, which is a bug, thanks!

**Comment by durcheinandr** [comment]
Sorry for being a little bit late...

Working as expected. Thanks for fixing it (and thanks for vifm).
