### ISSUE TITLE
Integration with Screen is not enabled every other time

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#224]
I use Vifm 0.8.2 (compiled from latest sources on 2016-10-03) in a Screen session on Raspbian. I have the `screen` command in .vifm/vifmrc. The problem is integration is not enabled every other time (exactly), so I have to enter the `screen` command manually or quit and run Vifm. Currently `screen` is the last command in the config file; I have tried moving it around, just in case other config command could affect it, but it makes no difference. This problem happened also with all the previous versions I have used, from 0.7.8, I think.

Any clue? Could it be a bug of Vifm or related to my Screen configuration?

**Comment by xaizek** [comment]
That's a side effect of how the command works, which is confusing. `:screen` *toggles* multiplexer support, but its state is also stored in vifminfo file. So vifm loads previous value every time before sourcing `vifmrc` and then `:screen` reverses it. I dropped it from my `vifmrc` for this reason.

I think it should be handled just like `:view`, where there is a `:view!` form which always enables preview. So one could put `:screen!` in vifmrc to avoid this unusual behaviour (disabling would take `:screen! | screen`, but it's usually not needed). In principle, we could turn it into an option, but for now `:screen!` seems to be enough and it's good idea to keep it consistent with `:view` command anyway, which is very similar.

**Comment by programandala-net** [comment]
Thank you. I think I was so convinced `screen` _activates_ the multiplexer support, that I didn't confirmed it in the manual when I realized this problem the first time. Removing `screen` from the config file fixes this issue.

Adding `screen!` seems a good idea as you say.
