### ISSUE TITLE
Hardware cursor position not set

### ISSUE THREAD

**Issue by tspivey** [vifm/vifm#225]
When moving through the file list, the position of the system cursor stays on the bottom line of the screen.
Ideally, it should be on the line containing the currently selected file, within the active pane (on the first character of/before the filename).
This would make it easier for screen readers and braille displays to track the currently selected item.

**Comment by xaizek** [comment]
Makes sense. It'd also be useful for copy-mode in terminal multiplexers, which currently requires more keystrokes for initial navigation than it should in most cases.
