### ISSUE TITLE
Building on ARM issue

### ISSUE THREAD

**Issue by Losiara** [vifm/vifm#226]
Try to build on armbian no gui. 
- Installed libncurses-dev.
- ./configure ... --without-X11 ...
OUTPUT:
checking for library containing curs_set... none required.

when "make", *.o files are compiled, but when cd to src/plugin dir it simple leaves directories and stops compiling without warnings or errors.

**Comment by xaizek** [comment]
Are there a package named `libncursesw5-dev`? On Debian-based system that's how it's usually called. Or maybe `libncursesw-dev` (note `w` before the dash).

**Comment by Losiara** [comment]
Yep, `libncurses-dev` was installed like `libncursesw5-dev`. 
`./configure` cmd found it, but `curs_set` not found.

**Comment by xaizek** [comment]
Is there a package like `libtinfo`? `curs_set` is usually provided by `libcurses`, but it can also be in `libtinfo`. I expect both libraries to come from one package, which might be incorrect.

**Comment by Losiara** [comment]
Yes, they are also available. libtinfo5 and libtinfo-dev.

**Comment by xaizek** [comment]
Does installation of `libtinfo-dev` solve the build issue?

**Comment by Losiara** [comment]
No It was installed in the begining and the same result.

**Comment by xaizek** [comment]
That's weird. It must be somewhere (unless it's a macro...). What's the output of the following command?
```
grep curs_set /usr/include/curses.h
```

**Comment by Losiara** [comment]
Realy weird. Grep seems shows as it must be.
`grep curs_set /usr/include/curses.h`
`extern NCURSES(int) curs_set (int) /*implemented*/`
`extern NCURSES(int) NCURSES_SP_NAME(curs_set) (screen*, int);  /*implemented*/`

**Comment by xaizek** [comment]
Can you post `config.log` after failed build here? Maybe use https://gist.github.com/ to upload it in full (it's not always easy to find the relevant part of it).

**Comment by Losiara** [comment]
https://gist.github.com/Losiara/ff4e2c45ef22af6626520e8ee710f23f

**Comment by xaizek** [comment]
OK, `curs_set` is fine. `none required` means that `curs_set` is part of `libcurses`, that's all. `config.log` doesn't even mention it and also seems to be incomplete.

I thought that's the last line of configuration output, but it clearly isn't. Please provide `log` file obtained like this:
```
make distclean
( ./configure && make ) > log 2>&1
```

**Comment by Losiara** [comment]
Done https://gist.github.com/Losiara/438b8f631177d395eb725139a0482b79

Not sure if it's ok to run ./configure without turn off X11 explicitly.

**Comment by xaizek** [comment]
> Not sure if it's ok to run ./configure without turn off X11 explicitly.

It's perfectly fine, that's what configure script is for: to adjust application to environment where possible.

The output shows that vifm has been built without issues. Why do you think it's broken? It can be run with `src/vifm` without installation to check if it works.

**Comment by Losiara** [comment]
I am very sory. It's my stupid mistake. It works.

**Comment by xaizek** [comment]
Prefix is used only for installation, so you need to do `make install` or rather [`checkinstall`](https://wiki.debian.org/CheckInstall) (for packaging) to get the binaries and all other files in the right places.
