### ISSUE TITLE
All file operations cause "mv: write error: Bad file descriptor"

### ISSUE THREAD

**Issue by mkollaro** [vifm/vifm#227]
I get this error when I try to rename, delete, copy, or do whatsoever else with any file in any directory (I tried several). I can modify the files just fine in thunar. I don't have any configuration for vifm, this is on a recently installed system (unless it uses something in .vimrc). I'm using Debian testing (stretch) and vifm 0.8.2.

**Comment by xaizek** [comment]
This seems to be the same issue as in vifm/vifm.vim#6 (it's not about the plugin, just in the wrong repository). [The fix](https://github.com/vifm/vifm/commit/19473f2) was made after 0.8.2 release.

You can work around it by setting `set syscalls` in `~/.vifm/vifmrc` file, which will switch to system API calls for file operations, which are not affected by the issue. By default cp/mv and alike are used for historical reasons and also for their universality, syscalls implementation has progress and works faster on large amount of files.

**Comment by xaizek** [comment]
I'm closing this as I'm pretty sure it's the same issue as mentioned above.
