### ISSUE TITLE
Shell color scheme is reset after editing in Vim

### ISSUE THREAD

**Issue by Shamaoke** [vifm/vifm#228]
I load a shell color scheme from an initialization script at a session start. This scheme replaces a virtual terminal color scheme which is defined in terminal settings. However, after finishing a file edit in Vim inside Vifm, for some reason, the shell scheme is reset to the terminal one.

Interestingly, when I set the TERM environment variable to “screen-256color”, this behavior isn't exposed.

Here's a [video](https://youtu.be/_Kh95EOrNCw) with demonstration of the issue.

At the start of the video I run Vifm to show how it should look. Then I run the “colortest” program which shows the colors used in the terminal. Then I start a new terminal window, run Vifm in it and open an arbitrary file in Vim. After I close the file, the shell scheme is replaced by the terminal one. I run colortest again in order to show that colors was changed.

At the second part of the video I export the TERM environment variable with the value: “screen-256color” and do the aforementioned actions again. At this time scheme resetting doesn't happen.

vifm 0.8.2; zsh 5.2; vte terminals: gnome terminal (3.22), rox terminal (3.3.2)

**Comment by xaizek** [comment]
Downloaded ubuntu 2016.10 image and got these versions: vifm 0.8.2; zsh 5.2; gnome terminal 3.20.2. I don't see the issue with this configuration.

I'm not sure from which version on libvte provides true-colors, but they could break something while introducing it. The reset seems to happen when ncurses restores terminal settings after running external application and I wouldn't expect it to reset such terminal settings.

Does this happen if you run any other application like shell (`:shell`) or `less` (`:!less %c`)?

**Comment by Shamaoke** [comment]
Yes, Vifm exposes the same behavior when I run `:shell` or `:!less %c` — the color scheme _is_ [reset](https://youtu.be/6vjbGv30tMM).

I use [Base16-shell](https://github.com/chriskempson/base16-shell) to maintain shell colors. Could you check will colors be reset when using Base16-shell?

Here's how to install it:

1.  Clone the repo: `git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell`;

2.  Add the following to `~/.zshrc` to load a scheme at shell initialization: 

        BASE16_SHELL=$HOME/.config/base16-shell
        [ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

3. Reload the shell: `exec zsh`;

4. Specify a color scheme by running the command: `base16_monokai`. From now on this scheme will be loaded at every shell run.

Also I want to note, that color reset started to happen since recent system upgrade. This behavior wasn't exposed before in the same environment: gnome terminal, zshell, base16-shell, vifm.

**Comment by xaizek** [comment]
Base16-shell works fine for me, no colors are reset.

I think this happens on invocation of [reset_prog_mode](https://linux.die.net/man/3/reset_prog_mode) function, which curses invokes implicitly on first screen redraw after external application finishes. Or `def_prog_mode()` fails to save current colors (I don't actually know if it's supposed to save them). As behaviour depends on `$TERM`, which affects which codes ncurses sends to terminal, this seems plausible.

You can also try non-libvte based terminal with vifm or vte-based  terminal with another application that employs ncurses and can invoke external applications (e.g., `ranger` might do, it calls curses through python, but it shouldn't mess anything up).

**Comment by Shamaoke** [comment]
I tried it with urxvt — all works just fine, colors aren't reset regardless of the TERM value. However, it's the same story with the ranger manager, the scheme is lost after launching an external command.

I don't know if it's relevant or not, but I use the 3.22 version of the gnome terminal, but you said that yours is 3.20. May be the issue exposed itself on the very recent versions of the terminal and auxiliary stuff.

Anyway, the fact that urxvt isn't affected by this issue direct me onto the idea that I can borrow its TERM value and use it in the gnome terminal. I set `env TERM=rxvt-unicode-256color zsh` as a [custom launching parameter](https://dl.dropboxusercontent.com/u/20481401/issues/gnome_terminal_launching_command.png) and it worked, the colors stopped from being reset. So, I stayed at this solution at the meantime.

**Comment by xaizek** [comment]
> it's the same story with the ranger manager

OK, so vifm (and any other curses application) doesn't cause this.

Downloaded Fedora 24, but they have gnome-terminal 3.20.3 and everything is fine there too.
The issue must be related to gnome-terminal 3.21 and/or 3.22. Or it might be libvte issue, 0.44.2 works fine.

Actually there were at least two similar issues before: [1](https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1191238), [2](https://bugzilla.gnome.org/show_bug.cgi?id=705985).

I'm closing this, as there is nothing to be fixed in vifm. You probably want to report the bug in tracker of your distribution ([list](https://wiki.gnome.org/Bugsquad/TriageGuide/NonGnome#Bug_trackers_for_distributions)) as their [weird policy](https://wiki.gnome.org/Apps/Terminal/ReportingBugs) suggests.
