### ISSUE TITLE
[ChangeLog] confusing entry: "Consider trailing slash for directories or symbolic links …"

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#230]
https://github.com/vifm/vifm/blob/master/ChangeLog#L90 says:

`Consider trailing slash for directories or symbolic links that point to
directories for patterns in 'classify'.`

That doesn't sound like a change.

**Comment by xaizek** [comment]
Why not? In 0.8.2
```
set classify=[::*/::]
```
Doesn't decorate directories as `[dir-name]`, while on current `master` branch it does. The wording is somewhat unclear, I agree.
