### ISSUE TITLE
View file(s) from single-pane mode more easily

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#234]
Currently, had the single-pane mode enabled, we can't view files with `:view` and have the error message. So, to enable view for some peeps, we have to go through the steps:
1. Split the window to get the second pane.
2. Enable `:view`.

But what if instead of showing the error message `:view` could split the window for us? The rules to pick the splitting method could be like:
1. Split the longest side.
2. Split vertically, if the window is square.

**Comment by xaizek** [comment]
I think the main reason of current behaviour is that otherwise this won't be toggling of the state.

By the way, you can define a command (`:v` here) to do what you suggest (this doesn't account for font metrics, but vifm can't do it either):
```
command v : if layoutis('only')
         \|     if &lines == &columns || &lines < &columns
         \|         vsplit
         \|     else
         \|         split
         \|     endif
         \| endif
         \| view
```

**Comment by sudo-nice** [comment]
Oh, I've underestimated the flexibility of vifm. Your solution is very nice, thank you!

**Comment by sudo-nice** [comment]
Lately I've noticed, `:view` mode stays switched on after `:only` execution. Although this can be a feature, sometimes it's not. Please, consider this example from vifm man:
```
" automatically split vertically before enabling preview
:nnoremap w :if layoutis(’only’) | vsplit | endif | view<cr>
```
Let's split it into steps:
1. We have `:only` enabled and `:view` disabled.
2. Hit <kbd>w</kbd>
3. Run `:only` again. -> `:view` stays enabled
4. Hit <kbd>w</kbd>   -> `:view` is disabled and we have to hit <kbd>w</kbd> again.

Kind of `&view` option could help us here, but I've failed to find any mention of it in the manual. Could you give a hint, please?

**Comment by sudo-nice** [comment]
> Technically there shouldn't be no issues adding it as an option if there is need for that.
I see now, there is no need for this option. Thank you very much!
