### ISSUE TITLE
Implementing :siblnext and :siblprev commands

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#236]
Given the directory structure as example:
![1](http://i.imgur.com/LiqjwmF.png)
Currently, being in `IMG_1` directory we need three keypresses <kbd>hjl</kbd> to get to `IMG_2`. Or <kbd>hkl</kbd> to get from `IMG_2` to `IMG_1`. But we could to it three times more effectively with a single command/keypress.

Some options to consider:
1. These commands should not be affected by `set sort+=dir` and so should jump between directories separated with files in file list.
2. Optional wrapping for the top/bottom directory.
3. Symlinks to directories should be treated like usual directories in PWD.

So, the exact algorithm for `:siblnext` could be similar to this:
```
     1	GET TO THE PARENT DIR
     2	if we are at the very bottom of the file list
     3	  if wrapping is enabled
     4	    WRAP AND GET TO THE TOP OF THE FILE LIST
     5	    DISPLAY WARNING LIKE 'hit BOTTOM, continuing at TOP'
     6	  else
     7	    DO NOTHING
     8	  end
     9	else
    10	  if the next item is a directory or a link to a directory
    11	    CD INTO IT
    12	  else
    13	    PROCEED FROM THE LINE 2
    14	  end
    15	end

```

What do you think?

**Comment by xaizek** [comment]
I think it might be quite counter intuitive in general case, because you don't see where you're going. Here you have directories numbered in a predictable way, but usually it's not so.

The next version will provide tree-view, which allows you to see multiple directories as a tree (right now you can view them as a list with something like `:!find %u`):

![tree view](https://cloud.githubusercontent.com/assets/459736/21503109/6b7c15f0-cc5d-11e6-9732-f883d5751907.png)

Does this solve your use case? We can consider commands like `:siblnext` if not.

**Comment by sudo-nice** [comment]
> right now you can view them as a list with something like :!find %u

This kind of commands will fail to help, as it leads us from the current directory down to its **inner** content, as I understand. But the main point of the issue is to be able change look through the **outer** directory.

>The next version will provide tree-view, which allows you to see multiple directories as a tree

Is I understand, this tree-view mode will display only inner directories as well, so it is out of the issue scope.

>I think it might be quite counter intuitive in general case, because you don't see where you're going.

I'm absolutely agree with you, and at the moment I can't suggest any acceptable way to have implemented this preview of parent directory.
The whole idea has originated from ranger workflow, but there are three panes there by the concept (as you could know already). Had three panes, there is no problem to see three points: the past, the present, the future. Recently ranger has implemented two-pane mode (like mc and vifm have now), so may be someday vifm will evolve to have three-pane mode support, as the tree-pane concept is extremely effective sometimes, and vifm (after vi) tends to get effectiveness on its board.

Back to the point, sometimes the efficiency of fast moving beats the disadvantage of blind navigating. E.g., the directory, contains subdirectories of images, you traverse sequentially.

So, please, feel free to close it, or to implement the suggested commands, if you are convinced with the arguments. Thank you anyway. :smile:

**Comment by xaizek** [comment]
> This kind of commands will fail to help, as it leads us from the current directory down to its inner content, as I understand. But the main point of the issue is to be able change look through the outer directory.

> Is I understand, this tree-view mode will display only inner directories as well, so it is out of the issue scope.

That's right, but if you do this in the parent directory you'll see all sibling directories with their files or get list of all files in the parent. It's not exactly what you want as it gives all the files at the same time instead of per directory, but you will be able to navigate through them (e.g., to preview them).

I can see that in ranger it doesn't feel that unusual.

**Comment by sudo-nice** [comment]
>but if you do this in the parent directory you'll see all sibling directories with their files or get list of all files in the parent

This will cost us a keypress to get to the parent directory right? And a keypress to enable tree-view. And a key press to pick next directory. And a keypress to enter it. Or you suggest to enable preview of parent directories in the second pane permanently?
Actually, what I really suggest, is to change the directory to the next/previous sibling with a minimal effort — a single keypress. If we can't preview parent directories at the moment, it's OK.
To make sure we understand each other, could you, please, run ranger with some directories in the leftmost pane and press <kbd>[</kbd> and <kbd>]</kbd> several times? Doesn't it feel very simple? If we imagine there is no the leftmost pane at all, we will get exactly the same experience we could have with vifm (only two vertical panes, but instantaneous siblings navigation).

**Comment by xaizek** [comment]
> This will cost us a keypress to get to the parent directory right? And a keypress to enable tree-view. And a key press to pick next directory. And a keypress to enter it. Or you suggest to enable preview of parent directories in the second pane permanently?

I assumed that you know beforehand whether you need only one directory or whole directory tree and can load tree and then go through files.

> To make sure we understand each other, could you, please, run ranger with some directories in the leftmost pane and press [ and ] several times? Doesn't it feel very simple? If we imagine there is no the leftmost pane at all, we will get exactly the same experience we could have with vifm (only two vertical panes, but instantaneous siblings navigation).

Yes, I understood how it supposed to work (feels somewhat weird though). About three-pane mode, it could be implemented by splitting current pane into two areas and using the other pane for preview; this would allow seeing where we came from.

**Comment by sudo-nice** [comment]
>About three-pane mode, it could be implemented by splitting current pane into two areas and using the other pane for preview; this would allow seeing where we came from.

That might be useful!

**Comment by sudo-nice** [comment]
Real life example, where I miss `:siblnext` and `:siblprev` a lot:
```
torrents
├── complete
└── incomplete
```

**Comment by sudo-nice** [comment]
Thank you!
