### ISSUE TITLE
Learning the path of invisible pane(s)

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#237]
#### Approach 1 (implementing %D for statusline)
With this feature we could use %D (full path to other file list directory) inside the statusline. This would let us know the other pane's path without switching to it forth and back.
Or maybe this macro could take its place inside TopLineSel (e.g., separated with color).
Maybe this macro should be visible only while `:only` mode is on (not to waste space).

#### Approach 2 (more general, considering perspectives)
If you are planning to implement multiple panes, we could have an additional line, e.g. at the very top of the window, similar to [vim-buftabline](https://github.com/ap/vim-buftabline). This buftabline could be visible only if we had invisible pane(s).

**Comment by xaizek** [comment]
> Approach 1

> With this feature we could use %D (full path to other file list directory) inside the statusline. This would let us know the other pane's path without switching to it forth and back.
> Maybe this macro should be visible only while :only mode is on (not to waste space).

Seems reasonable. Although at the moment you can create a mapping that just runs:
```
:echo 'Other pwd:' expand('%D')
```

> Approach 2

> If you are planning to implement multiple panes

That should be done at some point (#123), I tried to add tabs, but something didn't work out (with directory history if I remember correctly) and it was postponed for later again. This will be tabs rather than buffers/panes because I don't see a way of integrating multiple panes into existing setup (with some commands relying on both panes), there is too much assuming a pair of windows. But a bunch of tabs in only mode is essentially buffers, so the difference is not that big. And as second window refers to the same tab, it shouldn't really appear in title.

**Comment by sudo-nice** [comment]
>Although at the moment you can create a mapping that just runs...

Thank you.

>This will be tabs rather than buffers/panes because I don't see a way of integrating multiple panes into existing setup (with some commands relying on both panes)

Just a thought: commands could imply pane numbers. E.g. we have three panes, then standard command (like `:move` or `:copy`) could take effect between the current pane and the other pane with the minimal number. So, with three panes setup, commands run between `pane1 <-> pane2` (the cursor is inside pane 1 or pane 2) or between `pane1 <-> pane3` (the cursor is inside pane 3). In this terms we can call pane1 as master pane. Imagine, we could open four panes (one is the master) and move files from the slave panes into the master pane with a minimal effort.

To run commands between `pane2 <-> pane3`, the command should get the receiving pane explicitly, (e.g. `:move 2` - move from the current pane to the pane2). Or panes could have names instead of numbers. And the names could be assigned permanently or on the fly... And we could run commands like: `:move images` - move to the pane named 'images')... I can't stop dreaming. :yum:

If you like the concept, we can move into separate issue.

**Comment by xaizek** [comment]
> Just a thought: commands could imply pane numbers. ...

You're not the first one who proposes naming thing :-). It might be part of a solution. Although I still can't understand what's the point of seeing more than two panes, but working with only two of them at a time. It's still in the [todo list](https://github.com/vifm/vifm/blob/28314dac669f5ee03b380504f892fa141080100a/TODO#L84) though, just sounds too crazy and quite exotic (if tabs are implemented, this will bring part of code that is needed for multiple panes as well).

**Comment by sudo-nice** [comment]
>Although I still can't understand what's the point of seeing more than two panes, but working with only two of them at a time.

We could use additional panes to display additional info (remember https://github.com/vifm/vifm/issues/236)

**Comment by xaizek** [comment]
> (remember #236)

You don't need a full featured pane for that and it's not enough on its own as position synchronization and some implied relation between panes is required.

**Comment by sudo-nice** [comment]
Thank you! :smile:
