### ISSUE TITLE
Yanking a file, and choosing "rename", removes source file

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#240]
1. Create file `a` in directory `x`
2. Create file `a` in directory `y`
3. Yank file `a` in directory `x` with <kbd>Y</kbd>
5. Paste the file into directory `y` with <kbd>P</kbd>
6. The file naturally exists, choose "rename"
7. Type `b`
8. We now have `y/a` and `y/b`, but `x/a` gets removed.

I think this is because the dialog is shared with movement operation (<kbd>dd</kbd>), for which renaming indeed makes sense.

**Comment by xaizek** [comment]
Why do you use <kbd>P</kbd> and not <kbd>p</kbd> if you don't want to move source file? Source file is not removed, but moved.

**Comment by rr-** [comment]
Oh wow
<kbd>P</kbd> must be a habit from vim.
I subconsciously assumed these keys were just doing the same thing (pasting stuff from register) with no additional logic. Sorry for the noise.

Happy new year :-3

**Comment by xaizek** [comment]
I'm surprised you didn't figure out this difference earlier :-)

Happy new year!
