### ISSUE TITLE
View mode does not work properly under rxvt-unicode-256color

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#241]
vifm version: 0.8.2
os version: Debian Jessie

When vifm is used under rxvt with 256-color turned on, keybindings under view mode do not work properly: even keys like PgUp, PgDn do not work. For instance,

    :view      # activate quick-view panel when on a long text file
    Shift-Tab  # turn on view mode
    PgDn       # no effect when under rxvt-unicode-256color

It is confirmed that vifm works correctly under xterm. Since most common keys like PgUp, PgDn work greatly at normal mode under rxvt-unicode-256color. I wonder whether it is a vifm or rxvt-unicode-256color issue. Thanks.

**Comment by durcheinandr** [comment]
Can't reproduce problems. Works fine.

```
~
[I]%> echo $TERM
rxvt-unicode-256color
                                                                                                                                                                                                                          
~
[I]%> vifm -v
Version: 0.8.2
Git info: v0.8.2-604-gb771372c524e
Compiled at: Dec 29 2016 15:13:50

Support of extended keys is on
Parsing of .desktop files is enabled
With GTK+ library
Without magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
                                                                                                                                                                                                                          
~
[I]%> cat /etc/issue 
Debian GNU/Linux 8 \n \l
```

**Comment by xaizek** [comment]
Hm, PgUp and PgDn work for me, but Home and End don't work in any mode. Home and End are mapped to some completely unrelated functional keys. urxvt seems to do some weird stuff here ([somewhat related arch wiki page](https://wiki.archlinux.org/index.php/Home_and_End_keys_not_working#URxvt.2FRxvt)), it sends unusual key codes which confuse applications.

vifm relies on curses to map key codes properly, which in turn uses terminfo database to look up key codes for specific terminal named in `$TERM`. If curses fails to do this task, vifm can't really help it.

I have only one idea so far as to why behaviour might be different in view mode: it doesn't have Esc key mapped to anything. I don't see how that would affect key processing that much though. Apart from that view mode doesn't reconfigure the terminal or does anything special with it (at least I don't remember and don't see it in the code). Although... is there any viewer involved here? It could be that an application invoked for file preview messed up terminal state a bit.

What version of urxvt do you have, by the way?

**Comment by randomizedthinking** [comment]
Thanks for the prompt replies. The urxvt version is: `rxvt-unicode (urxvt) v9.20 - released: 2014-04-26`.

The problem is now resolved. Since I am updating a few configuration files, sorry that I am not sure what exactly attributed to this.
