### ISSUE TITLE
Prefix 'change file permissions' map with count

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#243]
Currently, if we hit something like <kbd>777cp</kbd>, the 'change file permission' dialog is opened as the only effect. But it could change the file permissions and don't open the dialog at all, if the count is provided. Please, see the cases:

Keys | Open the menu? | New permissions
---: | :---: | :---:
<kbd>cp</kbd> | yes | as we set from the menu
<kbd>7cp</kbd>    | no | 0007
<kbd>47cp</kbd>   | no | 0047
<kbd>247cp</kbd>  | no | 0247
<kbd>1247cp</kbd> | no | 1247
<kbd>7777cp</kbd> | no | 7777

I beleive, the `:chmod` should be affected by this change too.
I'm not sure whether this feature should work on windows too, and if so, how exactly. Maybe, windows users can advice the way count should map to attributes.

What do you think?

**Comment by xaizek** [comment]
Somewhat different from commands like <kbd>10dd</kbd>, where count specifies number of files to be processed, but it's probably fine as <kbd>cp</kbd> doesn't accept motions either.

> I believe, the `:chmod` should be affected by this change too.

It should already accept argument in numerical form.

> I'm not sure whether this feature should work on windows too, and if so, how exactly. Maybe, windows users can advice the way count should map to attributes.

They don't map to any numbers, so just current behaviour on Windows.

**Comment by sudo-nice** [comment]
Nice, thank you!
