### ISSUE TITLE
Can't view readlink output

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#245]
Create a symlink to /dev/null: `ln -s /dev/null foo`
Read it with readlink: `readlink foo` - see `/dev/null`

Add this to vifmrc: `fileviewer <inode/symlink> readlink -- %c`
Try to view it and get:
![scr](http://i.imgur.com/UWIqC1N.png)

Why not?

--- ADD:
The same with: `fileviewer <inode/symlink> echo '/dev/null'`
Looks like `/dev/null` triggers vifm.

**Comment by sudo-nice** [comment]
The same with: `fileviewer <inode/symlink> echo '/dev/null'`
Looks like `/dev/null` triggets vifm.

**Comment by xaizek** [comment]
If I remember correctly, symbolic links are automatically resolved when files are matched by mimetype, this way files and symbolic links to them are treated equivalently (differentiating between them is usually not very useful). In your example vifm reads from `/dev/null` (and `readlink` or `echo` are not run at all).

**Comment by sudo-nice** [comment]
You are right, I see now. Isn't it dangerous to resolve symlinks?
For example: if we create symlink to an image and open it with sxiv, then delete that image from sxiv, we will lose the file and only get the broken symlink.

**Comment by sudo-nice** [comment]
Hm, looks like it's standard thing to resolve symlinks, my bad, sorry for that.

**Comment by xaizek** [comment]
> For example: if we create symlink to an image and open it with sxiv, then delete that image from sxiv, we will lose the file and only get the broken symlink.

That won't happen. They are resolved only to determine file type handler, viewer will get path of the link.

**Comment by sudo-nice** [comment]
You're right again, thank you. There is something strange with (my) sxiv, as it resolves symlinks.
Anyway, vifm is above suspicious.
