### ISSUE TITLE
It seems like 'iec' is just a dummy

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#247]
Here (on vifm 0.8.2) this option just changes `M` to `MiB` and doesn't recalculates the values.

*And if you will consider this a bug, and will decide to dig into it, may I hope you will remember [this entry](https://github.com/vifm/vifm/blob/master/TODO/#L101).* :wink:

**Comment by xaizek** [comment]
It affects naming only. And both `K` and `KiB` are measured in powers of 1024, but the description of the option incorrectly says `KB`, thanks.

> And if you will consider this a bug, and will decide to dig into it, may I hope you will remember this entry.

I remember this one :wink:. With `iec` controlling just suffix, we need also an option for size units. But with what states? These four?
 * friendly, base 1000
 * friendly, base 1024
 * precise, base 1000
 * precise, base 1024

**Comment by sudo-nice** [comment]
> But with what states? These four?

There always be people, who will not be satisfied with any restricted number of options, I think. To get the most flexible solution, there could be a new option:

#### The look
`set roundsize=potato`, where `potato` means maximal length of meaningful digits after dot (who cares about trailing meaningless zeros?)

#### The math
We could take [numfmt](http://man7.org/linux/man-pages/man1/numfmt.1.html) as the relevant point. The only flaw of it, I can name, the lack of option to drop trailing zeros.

#### Examples
To check the following values, you can use numfmt like:
numfmt --suffix=B --to=**si _or_ iec-i** --format=%.**potato**f *value of Bytes*

File size in Bytes | `potato=2` and `noiec` | `potato=2` and `iec` | `potato=3` and `iec`
--- | --- | --- | ---
111 | 111B | 111B | 111B
1000 | 1KB | 1000B | 1000B
1030 | 1.03KB | 1.01KiB | 1.006KiB
1030000 | 1.03MB | 1005.86KB | 1005.86KiB (*note dropped zero*)
10301024 | 10.31MB | 9.83MiB | 9.824MiB

**Comment by xaizek** [comment]
> sizefmt

This sounds nice.

> Had this, we could deprecate iec at all, as I think it's unlikely one wants to toggle si <-> iec on the fly, but rather set it on common basis.

`'iec'` is not meant to toggle between SI and IEC, only between `K` and `KiB` suffixes for IEC.

**Comment by xaizek** [comment]
Just noticed that examples in your table don't include spaces after a number. Is this accidental (because `numfmt` prints like this) or you want to be able to format size without the space?

**Comment by sudo-nice** [comment]
That was after `numfmt`, I think, to have the space is good for readability.
