### ISSUE TITLE
Sometimes tilde is not expanded relatively to the home directory

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#250]
Always works:
```
filetype *.torrent /home/user/foo.sh %f,
```

Works only from `:file` menu. And with <kbd>Return</kbd> or <kbd>l</kbd>, opens vith `vicmd` instead:
```
filetype *.torrent ~/foo.sh %f,
```

Not a big deal, but kind of confusing.

**Comment by xaizek** [comment]
Thanks. That's not a bug of running the command, but checking whether it exists (so this one is not found and the next command is used, when it exists).
