### ISSUE TITLE
On windows 7 x64 bookmarks don't work.

### ISSUE THREAD

**Issue by Losiara** [vifm/vifm#251]
When I add mark to directory with` :mark` it works ok. When I `:bmark` dir, it fails because drive saved in lower-case format (like `h:\dir\`) When I try to go to bookmark there is message 
`File h: doesn't exists`

PS
lower-case format is not a reason. Manually editing bookmarks with big letter causes the same effect.

**Comment by xaizek** [comment]
> lower-case format is not a reason.

Yes, drive names are not case-sensitive.

> File h: doesn't exists

Thanks for the report, this is already fixed by 45f06b067206c546c9d21f8d94cd2e1e05b5137a, not specifically for bookmarks, but for menus in general.

If you need this working right now, recent Windows builds are available [here](http://builds.vifm.info/).

**Comment by Losiara** [comment]
Thanks for this very good program!
