### ISSUE TITLE
Don't stay in view mode after exiting editor

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#252]
Currently:
1. Explore file in the current pane (<kbd>e</kbd>).
2. Edit it from the view-mode (<kbd>v</kbd>).
3. Exit the editor.
4. And we have to exit view mode by the hands.

Do we really need that step 4?

**Comment by xaizek** [comment]
You can remap <kbd>v</kbd> to get rid of the last step:
```vim
qnoremap v vq
```

`less` doesn't close itself after <kbd>v</kbd> and as you still have old version of the file you might want to do something else with it (e.g., go to next occurrence of a pattern).

**Comment by sudo-nice** [comment]
I see, thank you!
