### ISSUE TITLE
Weird filtering with zM

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#253]
1. :touch foo
2. :filter /^foo$/
3. <kbd>z</kbd><kbd>O</kbd> - the file is displayed
4. <kbd>z</kbd><kbd>M</kbd> - the file is hidden

But if we change previous step 3 to:

3. <kbd>z</kbd><kbd>M</kbd> - the file is displayed and now we can hide it only manually: <kbd>z</kbd><kbd>f</kbd>
Looks like <kbd>z</kbd><kbd>M</kbd> needs <kbd>z</kbd><kbd>O</kbd> before it, or acts wrong?

**Comment by xaizek** [comment]
Not absolutely wrong: without <kbd>z</kbd><kbd>M</kbd> it's just considered that previous filter is empty and restoring an empty filter is the same as removing the filter.

But we can handle this case better by doing nothing instead of resetting current value, thanks.
