### ISSUE TITLE
Miller columns mode for a pane

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#254]
Since we have `flat` and `lsview` modes, could we have [`millers` mode](https://en.wikipedia.org/wiki/Miller_columns) too?

It's very handy on preview unfamiliar directory structures when you don't know exactly what you are looking for. I've used this concept for years and can say vifm will gain a lot of universality with it.

Had it implemented on a pane basis we preserve all the vifm file commands and logics, I guess.
I believe, I'm [not the only one](https://q2a.vifm.info/28/displaying-content-of-selected-directory-folder-2nd-column) who miss this concept.

**Comment by xaizek** [comment]
Is this request just a separate issue for [this comment](https://github.com/vifm/vifm/issues/236#issuecomment-269475182) or you want to be able to see miller columns in each of two panes simultaneously?

**Comment by sudo-nice** [comment]
I think, it's appropriate to have `millers` mode for every pane, just like `lsview` mode. This will keep the consistency for any of current (or future) view-modes.

**Comment by xaizek** [comment]
Hm, then maybe we need two kinds of miller columns, because each pane has preview, that preview won't have the features of a normal preview (like scrolling and searching) and I'd imagine them being useful.

Also, I noticed that siblings on `:sibl*` include files that would otherwise be filtered out or hidden, which probably isn't the right behaviour.

**Comment by sudo-nice** [comment]
> Hm, then maybe we need two kinds of miller columns, because each pane has preview, that preview won't have the features of a normal preview (like scrolling and searching) and I'd imagine them being useful.

I wasn't clear, sorry. I think, miller-columns mode should have no difference from any other mode (like `lsview` or `tree`) except the appearance. So, when preview is activated, we should see the preview all over the pane.

> Also, I noticed that siblings on :sibl* include files that would otherwise be filtered out or hidden, which probably isn't the right behaviour.

I think, you are right!

**Comment by xaizek** [comment]
So you meant only that option should be view-specific and not having three columns in the same pane?

Something like this? With left half being one pane and right one being the second pane, plus activated preview. Ignore wrong highlighting, it's just a quick prototype.

![vifm-miller](https://user-images.githubusercontent.com/459736/28175524-29ee9568-67fd-11e7-8ac3-d6782d5c76a9.png)

**Comment by sudo-nice** [comment]
To keep things more simple, let's conside **only one** pane.
I think, we should have three columns in the same pane, if we are viewing files list:

![tree-panes](http://i.imgur.com/jC4y7Tw.png)

And there should be only the current file view all over the pane (just like the right pane from your picture above), if we are viewing a file or a directory (with <kbd>e</kbd>):

![file-view](http://i.imgur.com/rSghAhP.png)

**Comment by xaizek** [comment]
And if second column is currently on a file, should the third one display the preview?

**Comment by sudo-nice** [comment]
I think, no. We can preview explicitly in the other pane with `:view` That is the point where vifm having two panes takes over ranger.

When a second column is currently on a file, there could be options:
1. Keep the third column blank (simple, but waste of space).
2. Merge the second and the third columns into one and display the content of the second column there (more interesting variant, but may be more complicated to implement).
3. Something else?..

**Comment by xaizek** [comment]
OK, I initially thought you want preview in the third column for files too. Second option is not harder to do than the first one, but I don't like that view will resize back and forth like crazy while going through files.

**Comment by sudo-nice** [comment]
> but I don't like that view will resize back and forth like crazy while going through files

I'm not trying to force you, but I believe the second options is the most rational way.
We have UI jumps while navigation on one hand, and more space to display valuable information, on the other hand. What to choose?
I haven't checked other file managers, but ranger took that way in particular. Maybe you could give it another try to check out pros and cons?

**Comment by xaizek** [comment]
Actually, it won't be as horrible as in ranger because here we won't have the third column resized when moving between one file to another, only between file and directory. It needs testing either way.

**Comment by sudo-nice** [comment]
Thank you!
