### ISSUE TITLE
New macro to display a symlink path in statusline

### ISSUE THREAD

**Issue by sudo-nice** [vifm/vifm#257]
Since symlinks are resolved by default (https://github.com/vifm/vifm/issues/245#issuecomment-270395363) and it's tricky sometimes to define if a symlink is relative or absolute, or even where it leads to (need to jump forth and back), maybe it worth to have a macro for statusline? It could be prepended with `->` symbol to make it more easy to understand we deal with a symlinked path.

So, possible values to display could be:
`-> /absolute/path/to/a/symlinked/file.ext`
`-> ../../file.ext`

**Comment by xaizek** [comment]
> need to jump forth and back

<kbd>Ctrl-G</kbd> shows it as well.

> It could be prepended with `->` symbol

That can be added with `%[`/`%]` pair or macros (`%[ -> %X%]` if target path is expanded by `%X` macro, `X` is just as an example).

I think such a macro can be added.
