### ISSUE TITLE
Feature request: open file from menu list

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#261]
One scenario frequently surfaced when using vifm is that I would like to find then open certain files based on their content. The `:grep` command in vifm is convenient yet limited at times. For such cases, I relied on another program `recoll` to search for files. I managed to define a command then dump the output (which is a list of filenames) to the vifm menu list using the command macro `%m`. Yet found out that the menu list is only for displaying that I can't open a file from the menu list.

Here I'd like to request to add a feature such that files can be opened from the menu list. This request is mostly on how to integrate outside programs with vifm naturally. If there is other better solution, please let me know.

**Comment by aleksejrs** [comment]
`%u`, or `%U`, or `b` in the menu

**Comment by randomizedthinking** [comment]
Thanks, @aleksejrs and @xaizek. The approach works great for my purpose.
