### ISSUE TITLE
A 255-character file name is truncated to 254 when renaming with an editor.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#262]
Create a file with a 255-character name:

touch "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345"

Now I can rename it with Vifm itself, but if I try renaming it with Vim, the last character is lost, so I am renaming a different file (if it exists).

**Comment by xaizek** [comment]
Thanks! Fixed this particular place and some other places where this could also happen.
