### ISSUE TITLE
Pressing "y" or "n" in the "Error while Deleting" dialog crashes with "Unexpected response."

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#263]

**Comment by xaizek** [comment]
What error message? An `assert`?

Is it enough to do `btrfs subvolume create subv` and then try to delete it? Should I delete it as a regular user or as root?

**Comment by aleksejrs** [comment]
ifm: ops.c:1061: dispatch_error: Assertion `0 && "Unexpected response."' failed.

**Comment by xaizek** [comment]
Thanks!
