### ISSUE TITLE
Polish characters 'ą' and 'ć' can not be typed

### ISSUE THREAD

**Issue by mb1986** [vifm/vifm#264]
Hi,

I set `setxkbmap pl` and I can type Polish characters in terminal using RIGHT alt key, e.g., `Alt-o` (ó), `Alt-l` (ł), `Alt-a` (ą), `Alt-c` (ć) etc. Using vifm I can type nearly all polish chars except 'ć' (`Alt-c`) and 'ą' (`Alt-a`). The same problem occurs in 'pure' console.

Best,
Michał

**Comment by xaizek** [comment]
Hi,

Thanks for the report.

I believe this is the same issue that was described [here](http://q2a.vifm.info/208/ignores-scaron-cacute-backspace-while-trying-rename-files). I can't type 'ć' (`Alt-c`) and 'ą' (`Alt-a`) in v0.8.2, but everything is fine in development version.

So I assume you're using v0.8.2 (or probably any previous version), where this isn't fixed, and close this. Feel free to reopen if that's not the case.

**Comment by mb1986** [comment]
Yes, you are right, I'm using version 0.8.2 (arch official repository). I'll try development version. Thanks for clarification.

**Comment by mb1986** [comment]
I've tested development version from github and everything works like a charm :)
Thanks for your work.

Best,
Michał
