### ISSUE TITLE
Last visited directories feature

### ISSUE THREAD

**Issue by melihovv** [vifm/vifm#266]
Hello. Thanks for such cool file manager, it is awesome!
I used total commander before I switched to vifm. And I missing last visited directories feature in vifm. I use very often such feature in total commander, vim and other programs. I think it will be useful to have ability to quickly jump to recent directory in vifm too. I like ui of bookmarks feature and I think ui of last visited directories feature should be the same. What do you think?

**Comment by xaizek** [comment]
Hello, nice to here you find vifm useful.

Your description seems to match [`:history`](https://vifm.info/vimdoc.shtml#vifm-:history) command a lot, have you tried it?

**Comment by melihovv** [comment]
Oh, I didn't know about it. That is it! Thanks)
