### ISSUE TITLE
A command for searching doesn't work.

### ISSUE THREAD

**Issue by rbmz** [vifm/vifm#271]
This command for searching works in vim but not in vifm:

```
:execute "normal! /filename\<cr>"
```
It shows while it's performing the search but it gets canceled. Couldn't find a variation that works.

**Comment by xaizek** [comment]
The reason it doesn't work is that `\<cr>` is not recognized as a keycode, such sequences just aren't supported. `<cr>` is equivalent to `\r` escape sequence, so this should work for you:
```vim
:execute "normal! /filename\r"
```

**Comment by rbmz** [comment]
That worked, thanks.

**Comment by xaizek** [comment]
> rbmz reopened this an hour ago

So it doesn't work at the end?

**Comment by rbmz** [comment]
It works. Thought the milestone and self-assignment meant that you would add support for keycodes like ```\<cr>``` for version 0.9 so I reopened.
Feel free to close as you see fit.

**Comment by xaizek** [comment]
I added milestone to bind the issue to a time frame, it's easier to recognize a version instead of a date.

Do you need other sequences, which aren't available at the moment?

**Comment by rbmz** [comment]
Not at all, thanks.
