### ISSUE TITLE
Can't open audio or video

### ISSUE THREAD

**Issue by piotryordanov** [vifm/vifm#272]
I'm on mac and whenever I click `enter` or `e` to open or preview a picture or music file, I just converts to some jiberrish ascii output. 
I tried fiddling around with the .vifm config file, but nothing worked. Any tips?

**Comment by xaizek** [comment]
[vifmrc-osx](https://github.com/vifm/vifm/blob/85393f6dfcdf8fe11b1e1c3c29072845b36880e6/data/vifmrc-osx) contains:
```
" Audio
filextype *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus
        \ {Play using MPlayerX}
        \ open -a MPlayerX.app,
        \ {Open in iTunes}
        \ open -a iTunes.app,
        \ {Open in QuickTime Player}
        \ open -a QuickTime\ Player.app,
fileviewer *.mp3 mp3info
fileviewer *.flac soxi

" Video
filextype *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
         \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
         \*.as[fx]
        \ {Open in VLC}
        \ open -a VLC.app,
        \ {Open in QuickTime Player}
        \ open -a QuickTime\ Player.app,
        \ {Open in MPlayerX}
        \ open -a MPlayerX.app,
fileviewer *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
          \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
          \*.as[fx]
         \ ffprobe -pretty %c 2>&1
```

You don't necessary have programs for the preview, but I'd expect at least one of the programs for opening audio and video to be present.

You can actually type `:filetype test.mp3` or `:filetype file.avi` (`test.mp3` or `file.avi` don't need to exist) to see what associations are registered.

> .vifm config file

It's supposed to be a directory.  Look at the output of `:echo $MYVIFMRC`, it will print exact location of configuration file.  Sample vifmrc should have been installed at `~/.config/vifm/vifmrc` on the first run (you can move it to `~/.vifm/vifmrc` if you wish).

**Comment by piotryordanov** [comment]
That's how it is setup under `~/.config` right now. But, if I run the `filetype` commands, I get `NO Program matches test.mp3`.

Also, which key should I pressed to open externally?

**Comment by xaizek** [comment]
> That's how it is setup under ~/.config right now. But, if I run the filetype commands, I get NO Program matches test.mp3.

If you created `~/.vifm`, it takes precedence. That's why I mentioned `:echo $MYVIFMRC`, it will show which file you should edit.

> Also, which key should I pressed to open externally?

<kbd>Enter</kbd> and <kbd>l</kbd> make use of file associations.

**Comment by piotryordanov** [comment]
so `:echo $MYVIFMRC` shows `/Users/macuser/.config/vifm/vifmrc`

And, that's what I have in this file:

```
" Audio
filextype *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus
        \ {Play using MPlayerX}
        \ open -a MPlayerX.app,
        \ {Open in iTunes}
        \ open -a iTunes.app,
        \ {Open in QuickTime Player}
        \ open -a QuickTime\ Player.app,
fileviewer *.mp3 mp3info
fileviewer *.flac soxi

" Video
filextype *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
         \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
         \*.as[fx]
        \ {Open in VLC}
        \ open -a VLC.app,
        \ {Open in QuickTime Player}
        \ open -a QuickTime\ Player.app,
        \ {Open in MPlayerX}
        \ open -a MPlayerX.app,
fileviewer *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
          \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
          \*.as[fx]
         \ ffprobe -pretty %c 2>&1
```

I still get some gibberish output when I press either `enter` or `l`

**Comment by xaizek** [comment]
Hm, do you have `$DISPLAY` environment variable defined in shell? I just realized that it might be absent on macs, which makes me wonder why it works for other people.

Try changing `filextype` to `filetype` (no `x` in the middle).

**Comment by piotryordanov** [comment]
I fixed the typos. Thx!

`$DISPLAY` is empty. Now, if I try to open a file though, I get this: `Unable to find application named 'MPlayerX.app'`.
Any chance I can open video/audio with `mpc` ? I already use it for `[mpsyt](https://github.com/mps-youtube/mps-youtube)`

P.S. is there a way to switch from `vifm` to a term located in the current directory? (it's kind daunting to read the manuals at first, and I have some old lazy `mc` habits)

**Comment by xaizek** [comment]
> I fixed the typos.

Those aren't typos. I actually asked for it to be this way while reviewing #84, and I was wrong about it, because graphical environment isn't detected properly on macs. So thanks, I'll update it.

> Now, if I try to open a file though, I get this: Unable to find application named 'MPlayerX.app'.

That's another issue on OS X... The `open` thing breaks detection of existing applications.  You probably want to do this instead:

```
filetype *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus
        \ mpc
```

Description of `:filetype` is [here](https://vifm.info/vimdoc.shtml#vifm-%3Afiletype).  The format is basically pattern followed by list of programs to try to run.

> is there a way to switch from vifm to a term located in the current directory?

Yes, [`:shell`](https://vifm.info/vimdoc.shtml#vifm-:shell) command.

> it's kind daunting to read the manuals at first

In case you didn't see it, there is a cheatsheet for normal mode keys [over here](https://vifm.info/cheatsheets.shtml).  Might help to get started.

**Comment by piotryordanov** [comment]
Alright, I made it work like that:
`filetype *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus
        \ mplayer
`

I did check the cheatsheet, but it is not searchable :(

**Comment by xaizek** [comment]
> I did check the cheatsheet, but it is not searchable :(

PDF version is. I might look for a way to generate HTML from LaTeX, but not sure it will yield meaningful output.

**Comment by piotryordanov** [comment]
Will look into the PDF then.

You can just spit the commands into HTML after the pic. A list is good enough to search without the pic ;)
