### ISSUE TITLE
Is there a way to quickly jump between directories?

### ISSUE THREAD

**Issue by piotryordanov** [vifm/vifm#273]
Hello,

I apologize if this question is a basic one. I'm learning `vifm` and things are a big overwhealming :)
I am used to doing two things to jump dirs:

1. On Terminal: I use [fasd](https://github.com/clvv/fasd)
2. With Finder: I am used to run commands like `dwn` in [alfred](https://www.alfredapp.com/) which would, in this case, open the download folder. 

I am aware that there are bookmarks in vifm, but I didn't get the chance to play with them. Are they the way to go, or is there a better way to do so?

- - - -

Also, since I'm asking questions, I know that `:shell` will open up the shell for me in the current dir. Is there a way to go back other than invoking `vifm` again?

Cheers and thank you so much for this project!

**Comment by xaizek** [comment]
Both [marks](https://vifm.info/vimdoc.shtml#vifm-m) and [bookmarks](https://vifm.info/vimdoc.shtml#vifm-%3Abmark) can be used to navigate to predefined set of files/directories, but there is no indexing/fuzzy searching functionality.

Marks are useful for temporary locations and the most frequently used ones, e.g. <kbd>'</kbd><kbd>d</kbd> for downloads folder.

The limitation of marks is that there are only 52 of them and one quickly runs out of mnemonics for single-character names. Here's where bookmarks come in handy. They allow specifying long names and associating multiple names with the same path.

I have this mapping for bookmarks:
```vim
nnoremap b :bmgo<space>
```
which takes me to specified tag as long as it's unambiguous.

-------

> Is there a way to go back other than invoking vifm again?

Just exit the shell. You don't leave vifm with `:shell`, vifm is waiting for it to finish.

**Comment by piotryordanov** [comment]
I'll look into bookmarks. Thx!

Can I change the vimf directory from the `:shell` ?

**Comment by xaizek** [comment]
> Can I change the vimf directory from the :shell ?

It's possible to do, but in somewhat contrived way. In general, vifm can't query current directory of a shell (it's private to that process), but if you're using new beta version or building from master, then something like this could do it:
1. In `vifmrc`:
```vim
nnoremap s :let $VIFM_INSTANCE = v:servername
          \|shell
          \|let $VIFM_INSTANCE = ''<cr>
```
2. In `.bashrc`:
```bash
if [ -n "$VIFM_INSTANCE" ]; then
    trap 'vifm --server-name '"$VIFM_INSTANCE"' --remote $PWD' EXIT
    # don't let this propagate to child processes
    unset VIFM_INSTANCE
fi
```
And then use <kbd>s</kbd> to invoke shell.

**Comment by piotryordanov** [comment]
- I installed using homebrew so I'm on 0.8.2. Would this hack work for me?
- Can I add a bookmark without specifing a tag?
- So, there is no way of checking a history of previously opened directories?

**Comment by xaizek** [comment]
> I installed using homebrew so I'm on 0.8.2. Would this hack work for me?

Not yet, wait about a week, I think homebrew is quick to update to a new release.

> Can I add a bookmark without specifing a tag?

No, the point was to ease accessing/memorizing bookmarks. Plain list of path doesn't need builtin support. You can use directory name or a bogus tag, say, "tag".

> So, there is no way of checking a history of previously opened directories?

There is `:history` command, but it will show only directories visited inside vifm. We can't look inside shell process to figure out its location. I think `mc` is always between user and a shell, so it might be possible there, but vifm just spawns a shell and waits for it to finish.

**Comment by piotryordanov** [comment]
- Awesome, i'll wait for the update then!
- Tags are fine I guess :)
- the `:history` command is pretty useful for now.

I am kinda using the shell to use `facd` to change the directory. it's a hack, so I don't think it's important and I will wait for the update and implement ur hack so that it becomes more native. `mc` is great, but i am absolutely turned on by being able to use natively vim bindings in `vifm` :)

**Comment by xaizek** [comment]
> I am kinda using the shell to use facd to change the directory.

If `facd` has an option to just print target directory out and you don't need its completion, then something like the following command could work:
```vim
" facd needs some option here
command! facd :execute 'cd' system('facd -d %a')
```
Then you could type `:facd something` directly in vifm.

If it doesn't have such option, you could do `'fact -d %a && echo $PWD'`.

**Comment by chongchonghe** [comment]
I have a simple tool that works perfectly for this purpose (tested on macOS and linux). Look for the *Usage in vifm* section in the README.
https://github.com/chongchonghe/mOve
