### ISSUE TITLE
Display Questions

### ISSUE THREAD

**Issue by piotryordanov** [vifm/vifm#274]
Hello, I have a couple of questions.

1. If a file name is too long, it get cut in the beginning. Is there a way to have cut in the middle?
2. How can I show the year in the date?
3. Is there a way to display detailed file info (Date created, date modified, owner, sharing options etc...)

I always try to check the docs before asking questions. But, when I don't find the answer, I group them into an issue. I hope that's fine :)

**Comment by xaizek** [comment]
> I always try to check the docs before asking questions. But, when I don't find the answer, I group them into an issue. I hope that's fine :)

Fine with me. Although, this also generates emails for all who watch repository, so maybe consider [q2a site](https://q2a.vifm.info/) for usage questions.

> If a file name is too long, it get cut in the beginning. Is there a way to have cut in the middle?

You can cut at the end with `set viewcolumns=*{name}..,10{}.` (`*` does it), but no modifier to cut in the middle.

> How can I show the year in the date?

Modify `'timefmt'` to include `%Y`.

> Is there a way to display detailed file info (Date created, date modified, owner, sharing options etc...)

<kbd>Ctrl-G</kbd> on a file?

**Comment by piotryordanov** [comment]
I haven't aware of the Q&A. I'll make sure my questions go there then. Apology about the noise!

- I set `set viewcolumns=*{name}..,10{}` and it sill cuts in the beginning! I'm fine with cutting it at the end, but this command doesn't do it!
- The `timefmt` worked. Thank you!
- `Ctrl-G` does exactly what I was looking for!

**Comment by xaizek** [comment]
> I set `set viewcolumns=*{name}..,10{}` and it sill cuts in the beginning! I'm fine with cutting it at the end, but this command doesn't do it!

In case of misunderstanding, try `set viewcolumns=-{name}..,10{}` (cuts on the opposite side). This option is view-specific, so if you just typed the command and didn't put it into `vifmrc`, this might explain, why you didn't see the effect in the other pane.
