### ISSUE TITLE
Compilation error: ‘WK_ESCAPE’ undeclared here

### ISSUE THREAD

**Issue by bearcatsandor** [vifm/vifm#276]
When trying to compile using portage on Gentoo, i get the error:
```
modes/view.c:294:3: error: ‘WK_ESCAPE’ undeclared here (not in a function)
  {WK_ESCAPE L"[Z",            {{&cmd_q}, .descr = "leave view mode"}},
   ^~~~~~~~~
modes/view.c:294:13: error: expected ‘}’ before string constant
  {WK_ESCAPE L"[Z",            {{&cmd_q}, .descr = "leave view mode"}},
             ^~~~~
```
A full build log is here: https://gist.github.com/bearcatsandor/98dcf70ef808daa4062023895d4abea5
Any assistance would be appreciated, and if i bug i'll gladly help test.

**Comment by xaizek** [comment]
Thanks for the report, fixed. Old macro name left after rename. The issue happens only when building with `--disable-extended-keys`, which shouldn't really be necessary if you're using ncurses, as it provides a way to disable delay on <kbd>Esc</kbd>.
