### ISSUE TITLE
Using fzf with vifm

### ISSUE THREAD

**Issue by EvilDroidMax** [vifm/vifm#279]
I'm trying to make fzf work with vifm. So far I got it working with everything that uses a menu like :history and :locate but the problem is that I have to run :!vifm to change dir bcz the only way to get it to work is by pasting menu's output to a file then read it with cat | fzf and change dir to that. But that way I have to duplicate a vim instance so its not efficent.

Is there any way to input commands paths on :cd  or something to indentiy a vifm instance and kill it via so I can only keep 1 instance

**Comment by xaizek** [comment]
There is already an answer on [Q&A](https://q2a.vifm.info/264/using-cd-with-stdout-from-external-command?show=265#a265):
```vim
execute 'cd' system('fzf')
```

**Comment by EvilDroidMax** [comment]
That works for cd but the problem is that I can't run it on terminal .
The way I made fzf work is having a part of shortcut run on terminal. Like for example with :history

:history <cr> :write test<cr> q :!!vifm $(cat ~/test | fzf) <cr>

This way after the fzf interaction I change dir to the one from fzf.

**Comment by xaizek** [comment]
This mapping seems to work:
```vim
nnoremap ,h :history<cr>:write ~/test<cr>q:execute 'cd "'.system('fzf < ~/test 2>/dev/tty').'"'<cr>
```

**Comment by EvilDroidMax** [comment]
Is it possible to wrap that up on a command because I keep getting errors for it. Would like to make something like fzf-locate fzf-history commands.

Also is there anyway like this to make it work for fasd and fzf?
The only way  I can get it to work is using :!vifm $(fasd -dl | fzf)

**Comment by xaizek** [comment]
```vim
:command! fzfhistory :execute "normal! :history\r:write ~/test\rq" | execute 'cd "'.system('fzf < ~/test 2>/dev/tty').'"'
```

With fasd it should be the same:
```vim
:command! fasd :execute 'cd "'.system('fasd -dl | fzf 2>/dev/tty').'"'
```

**Comment by EvilDroidMax** [comment]
That works , I got everything worked out as I wanted.
Here's the code (maybe someone needs it to setup fzf with vifm too xD )

-- Fast way to add bmark without having to type the fodler name (shortcut)
command! fzfbmark :execute 'bmark "' .system('echo "${PWD##*/}"').'"'

-- Locate files with fzf. I made so I run 1st script every startup (So I could rebuild the file without having to wait on vifm everytime) then read from the locate file via fzf.

1 - locate --null * | xargs -r0 sh -c 'for i do [ -d "$i" ] && printf "%s\n" "$i"; done' sh {} +. {} | egrep -v "cache|log|functions|icons|odules|help|fonts" > ~/.vifm/fzf-read/locate
2 - command! fzfD :execute 'cd "'.system('cat ~/.vifm/fzf-read/locate |  fzf 2>/dev/tty').'"'

-- Reading bookmarks with fzf

command! fzfbookmarks :execute "normal! :bmarks\r:write ~/.vifm/fzf-read/bookmarks\rq" | execute 'cd "'.system('cat ~/.vifm/fzf-read/bookmarks | sed "s/:.*//" |  fzf 2>/dev/tty').'"'

-- Using fasd with fzf and vifm

command! fzfDrecent :execute 'cd "'.system('fasd -dl | grep -v cache | fzf 2>/dev/tty').'"'

Thanks for the help :)

**Comment by valmormn** [comment]
This is what I do

`!$EDITOR $(fzf)`

If $EDITOR is not set

`!neovim $(fzf)`

or 

`!vim $(fzf)`

**Comment by Voovs** [comment]
I found @EvilDroidMax's answer nearly worked, though upon exiting vifm, the shell didn't properly restore itself
<img width="804" alt="shrink_screenshot_out" src="https://user-images.githubusercontent.com/29561440/147510891-ca6c3523-1677-4e32-81bf-72512fd1a249.png">

If you're on tmux +3.2, using fzf-tmux solves this and supports popup windows. If you don't use tmux or have an older version, replace `system` with `term` to stop the ncurses issue:
<img width="670" alt="shrink_screenshot_out" src="https://user-images.githubusercontent.com/29561440/147511468-30e35173-c244-416a-9902-8503af25ac9c.png">

You an extend this to essentially any shell program. Below we use `fd` to navigate via fzf into a child directory

```vim
    " Write the current bookmarks to a file (same as EvilDroidMax)
command! fzfreadbmarks :exe "normal! :bmarks\r:write ~/.config/vifm/fzf-read/bookmarks\rq"

" Fzf through bookmarks
if $TMUX
    " Use popup window. Requires tmux 3.2 and up
    command! fzfbmarks :execute 'cd "'.system('cat ~/.config/vifm/fzf-read/bookmarks | fzf-tmux -p 90,30 | sed "s/:.*//" ').'"'
    command! fdcddir :execute 'cd "'.system('fd -HE ''.git'' -t d . | fzf-tmux -p 90,30').'"'
    command! fdeditfiles :execute 'edit "'.system('fd -HE ''.git'' -t f . | fzf-tmux -p 90,30').'"'
else
    " Use full-screen. Works even without tmux
    command! fzfbmarks :execute 'cd "'.term('cat ~/.config/vifm/fzf-read/bookmarks | fzf 2>/dev/tty | sed "s/:.*//" ').'"'
    command! fdcddir :execute 'cd "'.term('fd -HE ''.git'' -t d . | fzf 2>/dev/tty').'"'
    command! fdeditfiles :execute 'edit "'.term('fd -HE ''.git'' -t f . | fzf 2>/dev/tty').'"'
endif

  " Read in latests bookmarks before fzfinding through them
command! fzfmarks :fzfreadbmarks | fzfbmarks

  " fzfind bookmarks
nnoremap <space>r :fzfmarks<cr>
  " cd to child directory
nnoremap <space>e :fdcddir<cr>
  " edit file from child directory in vim
nnoremap <space>f :fdeditfiles<cr>
```

**Comment by SylEleuth** [comment]
I tried to modify this line:
```
command! fdcddir :execute 'cd "'.term('fd -HE ''.git'' -t f . | fzf 2>/dev/tty').'"'
```
To search for file instead of directories I changed the "-t" flag to "d". It shows files and search among them as it should but when I choose a file I get an error:
```
"Destination doesn't exist or isn't a directory".
```
Can someone help me with this?

**Comment by darianmorat** [comment]
For me, none of the solutions above worked... But this does exactly what I was looking for:
```
command! RipGrepFiles : set noquickview
                    \| let $FZF_PICK = term("rg --column --line-number --color=always --smart-case . | fzf --ansi --color 'hl:-1:underline,hl+:-1:underline:reverse' --delimiter : --preview '' --border 'none' --no-bold --color='gutter:-1' --layout=reverse --height 100%% 2>/dev/tty | cut -f1 -d:")
                    \| if $FZF_PICK != ''
                    \|     execute system('[ -f "$FZF_PICK" ] && echo goto || echo cd') fnameescape($FZF_PICK)
                    \| endif

command! FZFFiles : set noquickview
                 \| let $FZF_PICK = term("rg --files --smart-case . | fzf --ansi --color 'hl:-1:underline,hl+:-1:underline:reverse' --preview '' --border 'none' --no-bold --color='gutter:-1' --layout=reverse --height 100%% 2>/dev/tty | cut -f1 -d:")
                 \| if $FZF_PICK != ''
                 \|     execute system('[ -f "$FZF_PICK" ] && echo goto || echo cd') fnameescape($FZF_PICK)
                 \| endif

command! FZFDirectories : set noquickview
                 \| let $FZF_PICK = term("rg --files --null | xargs -0 dirname | sort -u | fzf --ansi --color 'hl:-1:underline,hl+:-1:underline:reverse' --preview '' --border 'none' --no-bold --color='gutter:-1' --layout=reverse --height 100%% 2>/dev/tty | cut -f1 -d:")
                 \| if $FZF_PICK != ''
                 \|     execute system('[ -f "$FZF_PICK" ] && echo goto || echo cd') fnameescape($FZF_PICK)
                 \| endif
```
My personal remap:
```
nnoremap <space>fd :FZFDirectories<cr>
nnoremap <space>ff :FZFFiles<cr>
nnoremap <space>fw :RipGrepFiles<cr>
```
