### ISSUE TITLE
Ability to query variables with `--remote`

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#293]
I'm trying to read stuff from vifm such as `%c` etc with `--remote`.
I can't do it normal way since `--remote` works in "fire and forget" fashion (plus exit status).

I was about to use temporary files, but...

```console
rr-@tornado:~/src/dotfiles$ ~/test
+ rm /tmp/tmp.txt
+ vifm --remote -c 'execute "!echo " "derp" ">/tmp/tmp.txt"'
+ cat /tmp/tmp.txt
cat: /tmp/tmp.txt: No such file or directory
+ sleep 0.1
+ cat /tmp/tmp.txt
derp
```

...at this point I need to deal with race conditions which is a little too much...
Can it be done any simpler way?

**Comment by xaizek** [comment]
I see a way, but not that it's much better...
```bash
mkfifo /tmp/pipe
vifm --server-name test --remote -c '!echo %c >/tmp/pipe'
cat /tmp/pipe
rm /tmp/pipe
```
This is probably the closest you can get to Vim's `--remote-expr` at the moment.

**Comment by rr-** [comment]
Thanks for the tip, I don't have to make my script asynchronous any longer.
