### ISSUE TITLE
Different remap for files/folders

### ISSUE THREAD

**Issue by GhostValk** [vifm/vifm#297]
It's possible to give different remaps to a key depending on if you are currently selecting a file or a folder?

**Comment by xaizek** [comment]
Yes, you need to embed if-else statement into the mapping:

```vim
nnoremap x : if filetype('.') == 'dir'
          \|     echo 'on a directory'
          \| else
          \|     echo 'on a file'
          \| endif<cr>
```

**Comment by GhostValk** [comment]
Thanks a lot, will try it later!

**Comment by GhostValk** [comment]
It didn't work..

What i'm trying to do is to bind a tmux sequence keys to open the selected file in another tmux panel containing a vim/nvim runnig app; my sequence is:

`nnoremap <Right> :!tmux send-keys -t t2:0.1 Escape :e %c:p Enter<cr>`

Which works perfect when is binded like that, but whon i try to bind it inside that if statement, it doesn't work (it does nothing)

**Comment by xaizek** [comment]
[Commands](https://vifm.info/vimdoc.shtml#vifm-%3Abar) that take the rest of the line as their arguments (and ignore `|`) need to be executed via `:execute`, which will prevent them messing up other commands on the same line.

See if this works:
```vim
nnoremap <right>
          \: if filetype('.') == 'dir'
          \|     execute 'normal! l'
          \| else
          \|     execute '!tmux send-keys -t t2:0.1 Escape :e %c:p Enter'
          \| endif<cr>
```

**Comment by GhostValk** [comment]
Nope, still not working; when on a directory, it behaves "correctly" but with delay due to detecting it as a multiple key binding, so shows the options shortcuts, and when over a file, it uses the normal "Open" command to open it with the binded vifm app.

**Comment by xaizek** [comment]
My bad, sorry.  I removed required space while formatting the code, there has to
be a space before `:` or `<right>:` was the key sequence.

```vim
nnoremap <right>
      \ : if filetype('.') == 'dir'
      \ |     execute 'normal! l'
      \ | else
      \ |     execute '!tmux send-keys -t t2:0.1 Escape :e %c:p Enter'
      \ | endif<cr>
```

> What is the command to move inside the selected directory?

`:normal! l` or `:cd %c`.

**Comment by GhostValk** [comment]
Nope.. can't get it to work, the command opens it instead with the default vifm bind app (same behaviour as before)

**Comment by xaizek** [comment]
I don't see why it wouldn't work. Do you see the command in menu on `:nnoremap <right>`?

**Comment by GhostValk** [comment]
Look at my last comment, my mistake, didn't see the fix u made of the space, now is working as expected, thanks a lot =)!

**Comment by xaizek** [comment]
Oh, GitHub didn't show me the update while the page was open. Glad it works.
