### ISSUE TITLE
Posibility of having a top menu bar like Midnight Commande?

### ISSUE THREAD

**Issue by AndreaHasani** [vifm/vifm#298]
Is it possible to make vifm show a top bar like MC does. The reason for this is that bacause sometime I forget the commands I have on vifm and have to go to config to see the shortcut for X command. I think it would be quite useful If we had an option to show a menu which we can toggle with a shortcut lets say | F1 | and we would get commands listed there.

Thanks

**Comment by xaizek** [comment]
In the presence of modes and especially command-line mode, menus seem to be redundant. They do have an advantage of being easy to find, but this doesn't seem to be enough to justify implementing them. They also have some disadvantages: finding something in them is not always easy, they won't contain all commands and will just provide an additional way of running some existing commands.

> have to go to config

I don't know how you do this, but an easy way is to run `:e $MYVIFMRC`.

> to see the shortcut for X command

Do you have comments in your configuration file that are necessary for finding the mappings? If not, `:nmap` should display them all for you along with builtin commands in a searchable menu (`:nmap` is for normal mode, `:vmap` is for visual, etc.).

Does this cover your use cases?

**Comment by AndreaHasani** [comment]
I know how to get on my config , its just that because I use terminal apps too much I get confused when switching between them. the nmap feature is useful but I don't think thats a good way to use that everytime I forget a key. Is there any way to make the suggestion list smaller like only show the 2 first keys then show the third if I use that shortcut for example.

map ,mD move to download
map ,md move to documents
map ,mh move to home
map ,mm move to music

What I would like to try is having pressing a shortcut and only show ,m key first and if i press that the D-d-h-m keys suggestion shows up (this is how it works now but only the second part). This way I could map a few keys to a shortcut and not be worried about the suggestion list.

**Comment by xaizek** [comment]
So given those four mappings, something like the following should happen?
1. Suggestions after pressing <kbd>,</kbd>:
```
m    { 4 mappings folded }
```
2. Suggestions after pressing <kbd>m</kbd>:
```
D    move to download
d    move to documents
h    move to home
m    move to music
```

**Comment by AndreaHasani** [comment]
Yeah thats what I was trying to say. Right now I have most of my commands mapped to , (which acs as a leader key) and when the suggestion list shows up it takes nearly 80% of my view. Most of them are same commands which can easly be folded into 1. If possible I was thinking of a use of a dummy command which should just be there for the fold. For example having
nmap ,m echo "Change Directory Commands"

**Comment by xaizek** [comment]
> If possible I was thinking of a use of a dummy command which should just be there for the fold. For example having `nmap ,m echo "Move To Directory Commands"`

That alone won't work because introducing mappings changes the way keys are processed. It would require some special mechanism, something like an ability to provide description for mappings that would also cover such incomplete mappings.

**Comment by AndreaHasani** [comment]
Okey. Its fine if its hard to do. I think il just map my most used commands to a different key so I access them fast.
Thanks

**Comment by xaizek** [comment]
> Its fine if its hard to do.

It's just something that was not considered before when key handling was implemented.

> I think il just map my most used commands to a different key so I access them fast.

That's generally a good idea. This doesn't eliminate the need for folding though, or does it?

> is it possible to use conditional to check selected filetype and having mappings only for that filetype?

What do you mean by filetype? Whether selected entry is a file or directory like `filetype('.')` returns (see #297), or something else?

**Comment by AndreaHasani** [comment]
Well it doesn't really eliminate it. The folding would be quite useful since for example I have to mappings for unzip commands (one for unzip to a dir and another one to unzip all files in the current dir). If there was folding I could easly map the commadns that make sense to a F1 F2 F3. Like file commands to F1 and folder commands to F2 so I wouldn't need to remember all of them. If its possible to implement without messing up other things I think it would be a good feature.
Yeah thats exactly what was I looking. I want to try and see if I can hide some commands when they are not needed for example no reason to show an unzip command from files that are not compressed

**Comment by xaizek** [comment]
> Well it doesn't really eliminate it.

OK. Just wanted to make sure I understood correctly.

> I want to try and see if I can hide some commands when they are not needed for example no reason to show an unzip command from files that are not compressed

This won't do that, it can only make the mapping do nothing on a wrong file. If a mapping is registered, it will appear in suggestions. There actually was an idea of making mapping availability depend on some condition, but it was not implemented (new implementation of key processing that would address limitations of the existing one might do it, but it's only planned).

**Comment by AndreaHasani** [comment]
I see. Well I guess for now I make do with remebering the commands by name.
Thanks anyways :D

**Comment by xaizek** [comment]
Hey, I'll close this after adding that folding.

**Comment by AndreaHasani** [comment]
ok :) Thanks
