### ISSUE TITLE
iterm2 imgcat pictures

### ISSUE THREAD

**Issue by piotryordanov** [vifm/vifm#299]
Hello,

I have [imgcat](https://github.com/egoist/imgcat-cli) installed, and I have this in my rc:
```
 fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ /usr/local/bin/imgcat %d/%c > /dev/tty
```

The first picture I preview gets loaded, but then, i can't load anymore pictures. Sometimes, I can't even preview the first picture.

Any idea what I should do to make this work?

**Comment by xaizek** [comment]
Hi,

Does this command work any better?

```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
    \ /usr/local/bin/imgcat --width %pw --height %ph %c:p > /dev/tty && echo %px %py > /dev/null
```

Vifm determines whether preview is graphical by existence of both `%px` and `%py` macros in the command, since your command doesn't have them the output is treated as a text. `imgcat` doesn't seem to support positioning, so echo is redirected to `/dev/null`, but there are options for dimensions, so I added them.

**Comment by piotryordanov** [comment]
No, I'm afraid this doesn't really solve it.
I no longer get random lines added everywhere, but the preview remains dark.

**Comment by xaizek** [comment]
Since there is no positioning, do you open preview on the left side where the picture will be drawn?

**Comment by piotryordanov** [comment]
So if i switch to the right pane, making the left one the preview one, then yeah, i can start seeing pictures. But, they overlap with the right pane :P

**Comment by xaizek** [comment]
Maybe this will work better:

```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
    \ tput cup %py %px > /dev/tty && /usr/local/bin/imgcat --width %pw --height %ph %c:p > /dev/tty
```

**Comment by piotryordanov** [comment]
Yes! This does the job wonderfully. Thank you so much!

**Comment by yanzhang0219** [comment]
@xaizek Hello, does the script above still work? It shows `device not configured: /dve/tty` on my end. 
![image](https://user-images.githubusercontent.com/11582667/103155966-f9e28c00-4758-11eb-980c-989a14b39839.png)

Thank you very much.

**Comment by xaizek** [comment]
Hi, @yanzhang0219.

Are you building from `master`? I think so and it won't work there without changes as viewers are now detached from the terminal. The fix should be simplification of the command and using `%pd` macro:

    fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm /usr/local/bin/imgcat --width %pw --height %ph %c:p %pd

**Comment by yanzhang0219** [comment]
@xaizek Thank you for your quick response.
I change the line to 
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
    \ tput cup %py %px %pd && /usr/local/bin/imgcat --width %pw --height %ph %c:p %pd
```
but the image showing is weird (attached below)
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/11582667/103157669-47b3c000-476a-11eb-859d-6f73ca99813b.png">

The original image should be
![dracula](https://user-images.githubusercontent.com/11582667/103157674-51d5be80-476a-11eb-838e-1d50847663fd.png)

Thanks a lot.

**Comment by xaizek** [comment]
It's some other viewer, you can see which one (marked as `[present]`) in `:fileviewer bla.png` menu. You don't need `tput` part with `%pd`. I tried with [this imgcat](https://iterm2.com/utilities/imgcat), on v0.11 and `master` and the effect seems to be the same (the image just flashes for me, but I never tried viewing images in iTerm before and may be missing something).

**Comment by yanzhang0219** [comment]
Yeah. I removed the `tput` part and changed the code to
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm /usr/local/bin/imgcat --width %pw --height %ph %c:p %pd
```
I attached a GIF below. Is this abnormal output the same as yours?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/103158127-6a94a300-476f-11eb-87a6-2759223e55a9.gif)

When I run `imgcat dracula.png` directly in terminal:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/11582667/103158156-b21b2f00-476f-11eb-9828-94cfc61414e5.png">

My vifm version: 0.1.1 (the latest master)
The imgcat version: 2.5.0

Thanks.

**Comment by xaizek** [comment]
No, my output looks different. What `imgcat` are you using? Did it work for you before or you're just trying to set it up for the first time?

**Comment by yanzhang0219** [comment]
I installed `imgcat` using `homebrew`, its repo is https://github.com/eddieantonio/imgcat.
This is my first time trying to set up the image preview in vifm on macOS.
Thank you.

**Comment by xaizek** [comment]
Don't they have any imagination? So many different things called `imgcat`...

Looks like in case of this specific tool you need to additionally specify `--iterm2` to take advantage of OSC1337 sequence, otherwise it approximates image and that doesn't always work inside Vifm's TUI.

**Comment by yanzhang0219** [comment]
Thank you very much.

I changed the config to 
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm /usr/local/bin/imgcat --width %pw --height %ph --iterm2 %c:p %pd
```

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/103161683-6cc02700-479a-11eb-9305-3efeca667029.gif)


But the height is stretched to match the height of the window, and there is a number flashing at the top-left corner of the preview area. In addition, when I move the cursor among some images, the preview showing is very sluggish. Probably `imgcat` does not have a good performance regarding to the startup speed. 

**Do you know some other decent way to implement the image preview on macOS?** So said that w3m is not supported on macOS.

**Comment by xaizek** [comment]
I've never been an OS X user, so can't help much.

According to protocol [docs](https://iterm2.com/documentation-images.html) aspect ratio should be preserved by default.

You can try doing `:se previewoptions+=graphicsdelay:0` in an attempt to remove the delay, it might help.

Not sure about the extra characters. They are probably part of the output, but it shouldn't really show up.

**Comment by yanzhang0219** [comment]
Okay. I will try to dig into it more. Thank you for your help.

**Comment by BMomani** [comment]
the only thing that worked for me is 
note I use iterm and I installed iterm Shell Integration 

there is a blinking issue but its better than nothing

```
fileviewer {*.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm},<image/*>
       \ /Users/balmomani/.iterm2/imgcat  --width %pw --height %ph %c:p %pd
```
