### ISSUE TITLE
visiting a directory followed by opening a file changes sort order of directory

### ISSUE THREAD

**Issue by awhan** [vifm/vifm#300]
I have the following in my vifmrc
`set sort=mtime,dir`
however when i descend into a directory and open a file I find that the sort order of the directory has changed. I do not modify the file in question.

Steps to reproduce:
- mkdir foo && echo 'foo' > foo/foo.txt
- mkdir bar && echo 'bar' > bar/bar.txt
- vifm .
- i find that foo precedes bar in the directory listing
- navigate to foo and open foo.txt in default application
- close application *without* modifying foo.txt
- navigate back up to ../foo
- i now find bar precedes foo in the listing

`uname -a` on up to date archlinux is `Linux zero 4.14.5-1-ARCH #1 SMP PREEMPT Sun Dec 10 14:50:30 UTC 2017 x86_64 GNU/Linux`

`vifm --version` is

```Version: 0.9
Git info: built out of repository
Compiled at: Jun 24 2017 14:02:00

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
Thanks for the detailed report. However I can't reproduce the behaviour.

Not excluding possibility of a bug in vifm, but I suspect that `vim` just created swap-file there, which updates modification date of a directory. Try doing `ls -a foo/` while editor is open in another terminal to whether there are any extra files.

**Comment by awhan** [comment]
@xaizek you were absolutely correct. vim indeed creates a hidden swap file which in turn changes the modification time of the directory. Thanks so much!
