### ISSUE TITLE
Show current sorting mode (or ideally just an arbitrary expression) in the status line

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#304]
I realized I miss the current sorting mode in the statusline, like `+name` or `+mtime`, etc. We could probably add one more macro to the list of supported macros to `statusline`, but I think it would be better to support arbitrary vifm expressions, to get much more flexibility, like `%{<expression>}`. Then I'd use `%{&sort}` and that's it.

What do you think?

**Comment by xaizek** [comment]
Sounds like a reasonable request and I agree that `%{...}` is a nice way of doing this. There is no point in adding a new macro for things which can be evaluated via expressions.

**Comment by dimonomid** [comment]
Ok, cool!
