### ISSUE TITLE
Regression: --remote doesn't work anymore

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#305]
After the commit https://github.com/vifm/vifm/commit/dfb2ae63e50c570 remote directory change doesn't work anymore; this is the command I used to reproduce:

```
$ vifm --server-name vifm1 --remote "+cd /home"
```

**Comment by xaizek** [comment]
Are you sure you're not using two different versions of vifm, one with and one without the change? I decided that it's not worth supporting such interaction, so this might be the reason.

**Comment by dimonomid** [comment]
Ah damn, silly me!

You're right, I run a development version of vifm which is outside of `$PATH`, and the command I use to change dir externally of course just uses `vifm`...

Sorry for the noise.
