### ISSUE TITLE
List commands from cmdline history which begin from what's already typed

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#308]
I failed to find a proper term for that feature, but in Vim, when type e.g. `:se` and hit `<ctrl-p>`, only commands starting from `se` will be fetched from the history; I find it extremely useful. Does it sound good to implement it in vifm?

**Comment by xaizek** [comment]
It's already implemented, but only when you use Up/Down arrow keys. I don't remember exactly, but maybe it was done this way to keep two ways of listing history accessible, since
```vim
cnoremap <c-p> <up>
cnoremap <c-n> <down>
```
can always be used to get this behaviour for `<ctrl-n/p>`.

**Comment by dimonomid** [comment]
Ah. Thanks. :)
