### ISSUE TITLE
Hitting ctrl+c when fzf is called by vifm

### ISSUE THREAD

**Issue by mateusz28** [vifm/vifm#309]
I am calling fzf inside vifm using command: 
` command! fzf :execute '!fzf 2>&0 %%IU' | normal! gf`
It works like a charm until the file I'm looking for does not exists in a search scope. When I hit ctrl+c to exit from fzf I would expect going back to vifm without taking any further action but instead "Ignoring empty list of files" pop-up shows. What is worse and annoying, the "gf" command is executed on a file that cursor had been pointing previously.
Is there any way I could catch empty list exception and than ignore "| normal! gf" part command?

**Comment by dimonomid** [comment]
Here's the sort-of-working ugly solution I use:
```
command! fzf :execute '!FZF_RES=$(fzf); if [[ "$FZF_RES" != "" ]]; then vifm --server-name' v:servername '--remote "+cd $FZF_RES/.."; vifm --server-name' v:servername '--remote "+normal! /$(basename $FZF_RES)"; vifm --server-name' v:servername '--remote "+normal! n"; fi'
```
The biggest problem with it (other than being super-ugly) is that it pollutes search pattern.

Actually there's only one (little?) thing which prevents us from using a clean solution: we need a command to go to specific file, like `:goto /foo/bar/baz` should first do `cd /foo/bar`, and then put a cursor on `baz`. With that in place, we'll be able to use `:goto term('fzf 2> /dev/tty')`

Maybe @xaizek will enlighten us in some way (I wouldn't be surprized if some equivalent of `:goto` is already implemented and I just missed it ;) )

**Comment by dimonomid** [comment]
Btw I realized that we can use that trick with custom view you shared, but even though this command works for me:

```
:let $TMP_FILE=term('fzf 2> /dev/tty') | if $TMP_FILE != '' | execute '!echo $TMP_FILE %IU' | normal! gf| endif
```
Placing it under command results in a complaint `Unmatched if-else-endif`. :(
```
command! fzf :execute ":let $TMP_FILE=term('fzf 2> /dev/tty') | if $TMP_FILE != '' | execute '!echo $TMP_FILE %IU' | normal! gf| endif"
```

**Comment by xaizek** [comment]
@dimonomid, you can pass multiple commands at once:

```vim
command! fzf :execute '!FZF_RES=$(fzf); if [[ "$FZF_RES" != "" ]]; then vifm --server-name' v:servername '--remote "+cd $FZF_RES/.." "+normal! /$(basename $FZF_RES)" "+normal! n"; fi'
```

> I wouldn't be surprized if some equivalent of :goto is already implemented and I just missed it ;)

Not this time, I did think about something like `:goto` because of questions about `fzf`, but it didn't seem like a good justification for adding a new command. Now I see that there seems to be quite a lot of `fzf`-users to actually add the command, even if it won't be used for anything else.

@mateusz28, here's a possible "solution":
```vim
command! fzf :execute '!fzf 2>&0 %%IU || echo %c' | normal! gf
```

Or in 0.9.1 using `term()` with more straightforward logic:
```vim
command! fzf : let $FZF_RES = term('fzf 2>&0')
            \| if $FZF_RES != ''
            \|     execute "!echo '".$FZF_RES."' %%U"
            \|     execute 'normal! gf'
            \| endif
```

**Comment by xaizek** [comment]
> Placing it under command results in a complaint Unmatched if-else-endif. :(

You need to use `:execute` for `:normal` too. Some form of functions are probably needed after all, there `:execute`, `|` and `%%` wouldn't be needed and mappings would look nicer.

**Comment by dimonomid** [comment]
Thanks! The snippet you posted works fine for me.

**Comment by xaizek** [comment]
Here's version of `fzf` command for the next release:
```vim
command! fzf : let $FZF_RES = term('fzf 2>&0')
            \| if $FZF_RES != ''
            \|     goto $FZF_RES
            \| endif
```
