### ISSUE TITLE
After "amended" (non-contiguous) selection, gv restores only the latest selection region

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#311]
My understanding is that if I selected a few non-contiguous files, then e.g. copied them somewhere, so that the selection clears, then I type `gv` and all previously selected files should again become selected, not just the latest region.

What do you think?

**Comment by xaizek** [comment]
Well, <kbd>gv</kbd> doesn't just re-selects them, it also enters visual mode, so it might look a bit strange if files outside last range would get selected. In case you just want to restore last selection exactly, there is also <kbd>gs</kbd>, which might or might not be what you're looking for depending on exact use case.

**Comment by dimonomid** [comment]
Hmm, fair enough. Okay, I guess `gs` will do the trick for me in the most cases.

**Comment by xaizek** [comment]
In principle, there could be a new mapping (say, `aV`) that would essentially do `gs` and then `gv`, but without resetting the rest of selection. I just think that doing this on `gv` might not be what's expected.

**Comment by dimonomid** [comment]
Right, fair enough. Thanks for the clarification.
