### ISSUE TITLE
Regular expression in colorscheme stopped working

### ISSUE THREAD

**Issue by perglr** [vifm/vifm#312]
```
Pattern error: /Makefile/     cterm=none      ctermfg=172     ctermbg=237: Failed to parse flags. 
```
Archlinux,
```
% vifm --version
Version: 0.9.1
Git info: built out of repository
Compiled at: Feb  7 2018 18:39:41
```

**Comment by xaizek** [comment]
How does the command look in color scheme? This:
```
highlight /Makefile/     cterm=none      ctermfg=172     ctermbg=237
```
doesn't produce an error for me neither in color scheme nor when I run it interactively.

**Comment by perglr** [comment]
Indeed, this is the configuration line and I now made a conf file version with just this line and still the error is produced.

Maybe vifm uses some external dependency to parse the regexp, which may be somehow broken on my system?

![2018-02-12-121636_912x208_scrot](https://user-images.githubusercontent.com/4477111/36094585-29cb4cda-0fef-11e8-924e-45abd710b3b6.png)

**Comment by perglr** [comment]
I dropped a note on https://aur.archlinux.org/packages/vifm-git/ in case this is some Arch-specific quirk.

**Comment by xaizek** [comment]
After looking at the code I have a question, does your command use spaces or tabs? Tabs don't work there and I don't think they ever did (probably should though).

**Comment by perglr** [comment]
Bingo! It were the tabs. The tricky thing is that they mattered just in the regexp line and previously, it worked fine (although I cannot swear if the line was parsed correctly or just ignored). I will close this issue and create a new specific one based on this revelation. @xaizek, thank you very much for your help and the excellent file manager!

**Comment by xaizek** [comment]
Great, thanks for the report, will fix that.
