### ISSUE TITLE
RFC: Do not clear terminal screen when opening file in Quick Look on macOS

### ISSUE THREAD

**Issue by kiryph** [vifm/vifm#314]
I am on macOS Sierra 10.12.6, terminal is iTerm2 3.1.5, and the shell is zsh 5.4.2 (x86_64-apple-darwin16.7.0). The version of vifm is:
```
❯ vifm --version
Version: 0.9.1
Git info: built out of repository
Compiled at: Feb  6 2018 05:20:28

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

I like the configuration under https://github.com/vifm/vifm/blob/master/data/vifmrc-osx#L363-L364:
```VimL
" View preview in Quick Look
nnoremap q :!qlmanage -p %f > /dev/null 2>&1<cr>
```
which allows the user to have a quick look into files such as `pdf`, `docx` and other files which cannot be displayed in the terminal.

However, I find it distracting that the terminal screen is cleared as long as the Quick Look window is open. (And it is quite slow compared to pressing Spacebar in the Finder.)

Is there a possibility to keep the output of vifm visible in the terminal?

**Comment by xaizek** [comment]
Try this mapping:
```vim
nnoremap q :!qlmanage -p %f > /dev/null 2>&1 &<cr>
```
It runs external command in background by adding `" &"` at the end of `:!` command.

**Comment by kiryph** [comment]
Thanks, yes this looks like what I had in mind.

I expect that you cannot do anything to reduce the delay until Quick Look has opened.

My alias on the command line:
```sh
❯ alias ql
ql='qlmanage -p "$@" 2> /dev/null > /dev/null'
```
feels a little bit snappier.

**Comment by xaizek** [comment]
I'm not sure where delay is coming from.

If `!qlmanage -p %f > /dev/null 2>&1 &` works faster than the mapping, the reason might be conflicting mappings which cause one second delay, in which case you might try using different key instead of `q` or change other mappings that start with `q`.

`nnoremap q` shows user-defined mappings first and then builtin mappings after a blank line, if there are more than one user-defined mapping, there will be a delay.

**Comment by kiryph** [comment]
I think there was a delay due to the two-letter mappings `q/`, `q:`, `q=`, and `q?`.

I just mapped the space bar to open Quick Look and I will use the Tab key to switch panes.
Since I do not know how to measure the delay exactly, I have to resort to my impression and yes it feels faster (not a second, but I think noticable 😁 ).

Do I have to unmap the space bar first or is it sufficent to just add a new mapping to .vifm/vifmrc:
```
nnoremap <Space> :!qlmanage -p %f > /dev/null 2>&1 &<cr>
```

**Comment by xaizek** [comment]
Actually those four shouldn't matter as user-defined mappings have priority over builtin ones. So maybe nothing has changed. One way to test it is to run `:se timeoutlen=5000` to have 5 second delay and see if `q` becomes significantly slower. If this wasn't a conflict, then vifm shouldn't introduce any delays.

> Do I have to unmap the space bar first ...

No, new mapping just overrules builtin one (which can't be unmapped).

**Comment by kiryph** [comment]
Yes, you are right there is no delay due to `:se timeoutlen=5000`.
My impression was incorrect and nothing has changed 😆.

Anyhow, it is not too bad. I still like the space bar mapping for quick look.

Thanks for developing and maintaining `vifm`. I like the dual pane file manager with vim style keybindings. That's more or less the reason why I prefer it over midnight-commander or ranger.

**Comment by xiruizhao** [comment]
@xaizek 
I tested on vifm 0.10.1 (macOS 10.15.2) and confirm that timeoutlen is responsible for the delay before quicklook.
1. before ![](https://raw.githubusercontent.com/xiruizhao/archive/master/vifm%20q.gif) 
2. after ![](https://raw.githubusercontent.com/xiruizhao/archive/master/vifm%20q%20timeoutlen5000.gif)

suggestion: in [data/vifmrc-osx](https://github.com/vifm/vifm/blob/master/data/vifmrc-osx), drop `nnoremap q`, instead, `nnoremap <space> :!qlmanage -p %f &> /dev/null &<cr>`

**Comment by xaizek** [comment]
Thanks, yes, it does now, because of these lines which weren't there in 2018:
```vim
" Unhide builtin q* keymaps
nnoremap q: q:
nnoremap q/ q/
nnoremap q? q?
nnoremap q= q=
```
I'm not sure if `<space>` is a good choice, maybe `Q` would be better, there is no builtin mapping for it.

**Comment by xiruizhao** [comment]
Q is mapped to "Ex" mode in vim while `<space>` doesn't map to anything. `<space>` is also the default macOS way to launch quicklook in Finder.app. Anyway, users can modify `vifmrc` themselves.

**Comment by xaizek** [comment]
> Q is mapped to "Ex" mode in vim while `<space>` doesn't map to anything.

Space moves to the next character in Vim.

> `<space>` is also the default macOS way to launch quicklook in Finder.app.

That explains the choice, I didn't know this.
