### ISSUE TITLE
Long tmux window name when using :screen option in vifm

### ISSUE THREAD

**Issue by mateusz28** [vifm/vifm#318]
Hi,
I often use vifm when dealing with projects having complicated directory tree. I am also using integration with tmux so I can easily edit file in a new tmux window. 
One thing I find inconvenient is a new tmux window naming by vifm.
Example:
![long_name](https://user-images.githubusercontent.com/27509173/36725461-aae1808c-1bb6-11e8-8221-20933a60a693.PNG)
When directory structure is complicated using full path of file in window name makes no sense.
I've dealt with this issue by adding simple patch (3 lines) to vifm 0.9.1-beta sources:

[0001-short-tmux-names.txt](https://github.com/vifm/vifm/files/1762330/0001-short-tmux-names.txt)

It changes tmux window name to the name of the currently edited file instead of using its full path. 

Could you consider adding similar feature to next release? If someone finds full-path window naming it could be configurable. 

tmux version: 2.3
vifm version: 0.9.1-beta

**Comment by xaizek** [comment]
Hi,

I think too long names bothered me a couple of times too, although in general as long as tab titles fit on the screen it's fine with me. Hard to say whether this should be a default behaviour or not, so it's probably better to add a new flag to `'shortmess'` to control this. Thanks for the suggestion.
