### ISSUE TITLE
Trivial Manual Issue

### ISSUE THREAD

**Issue by john9631** [vifm/vifm#321]
*mix directories and files, "dir" should be appended to sorting option, for example like this:*

*set sort+=dir*

Should be set sort=+dir I think.

**Comment by john9631** [comment]
mix directories and files, "dir" should be appended to sorting option, for example like this:

  set sort+=dir

Should be set sort=+dir I think.

**Comment by xaizek** [comment]
I think everything is correct. `+=` appends to an option, just like the text says. Say, you have `sort=-size`, then `sort+=dir` will result in `sort=-size,+dir`. `+` is the default and is optional.

The second example
```
or
 set sort=-size,dir
```
shows how to append it manually, which requires knowing previous content of the option.

`set sort=+dir` will drop existing value and sorting will be `+dir,+name` and therefore won't achieve desired effect of mixing directories and files.

**Comment by john9631** [comment]
Thanks xaizek.   Reading error on my part.
