### ISSUE TITLE
Leaving a directory with a name ending with ".." (two or more dots) adds "/.." to the current path

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#323]
Vifm 0.9.1.

1. Go to `/tmp`
2. Create a directory called `test..`
3. Enter the directory.
4. Press `←` or `→` to return to `/tmp`.

Expected results:
* You are in `/tmp`
* Current path is `/tmp`

Actual results:
* You are in `/tmp`
* Current path is `/tmp/test../..`
* Repeating adds more `/..`
* Root directory has a `..`, and trying to leave it using that or `←` adds another `/..`
* To reset the path, use `cd` to go somewhere directly.

**Comment by xaizek** [comment]
Thanks!
