### ISSUE TITLE
:undolist menu - ability to change the current position of what undo will undo.

### ISSUE THREAD

**Issue by mini-turtle** [vifm/vifm#326]
(Feature request)
thanks

**Comment by xaizek** [comment]
Hm, I'm worried that doing this on <kbd>l</kbd> now will lead to unexpected results as it is being used to leave the menu. Will need to find a different key for moving current position (<kbd>space</kbd> is an option).

**Comment by mini-turtle** [comment]
I'm happy with [space or enter] to select and stay on the menu so you can see the current value. And then the usual [esc] to leave menu. But of course I'll leave it up to your experience to decide how to do it.

Thanks again.
