### ISSUE TITLE
Assigning mapping to Insert key

### ISSUE THREAD

**Issue by j-xella** [vifm/vifm#327]
Hi,

I am unable to assign any mapping to Insert key. In vim, this is possible with 

`:map <Insert> ...`

But does not work in vifm, and I could not find any alternative ...

I use Version: 0.9.1

**Comment by xaizek** [comment]
Hello,

Indeed, `<insert>` isn't handled as a special sequence. I can still map the key though by pressing Insert key in command-line mode. If you then hit <kbd>Ctrl-g</kbd>, you'll be able to copy the key code to your configuration (it might not work in every terminal, but might do for now).

I'll add handling of `<insert>`, thanks for letting me know it doesn't work.
