### ISSUE TITLE
Smart cd of zsh

### ISSUE THREAD

**Issue by j-xella** [vifm/vifm#328]
This is a feature request, it would be great to have smart `cd` (and `pushd`, for that matter) command that is available in zsh.

For example, in zsh, if you are in a folder, say,

`/path/to/foo/bar`

then doing `cd foo baz` would cd you into `/path/to/baz/bar`, assuming such folder exists.

Now, I understand that `cd xxx yyy` has certain meaning in vifm (cd for both panels). Maybe a new command could be created, for example `cds` - **cd** with **s**ubstitute?  It could be used similar to `s` :

`cds /foo/baz/`

**Comment by xaizek** [comment]
Nice, I was thinking about navigating to a parallel directory structure a couple of times, didn't know zsh has a nice way of doing this.

> Maybe a new command could be created, for example cds - cd with substitute? It could be used similar to s

A new command is probably needed, I don't see how to do both things in one command. Not sure whether slashes around arguments are actually needed if there will be no regular expressions.

**Comment by xaizek** [comment]
> if

I just don't remember a case where I'd want to use them for this situation.

Using regexps won't actually preclude form with spaces (it doesn't work in vim, but works in vifm, probably because of `:filter` command).

**Comment by j-xella** [comment]
Technically, there exists a workaround if you use zsh as a subshell and set up to follow subshell folders as described in #329.
