### ISSUE TITLE
Different logic between :select ! and %u

### ISSUE THREAD

**Issue by j-xella** [vifm/vifm#331]
When you use `%u` to load the results of the external command as a view, vifm is actually pretty clever in how it processes the output of the command. As I understood, if a file name is the first thing on the line, it can be followed by arbitrary stuff, which will be discarded. So, for example, the output of `grep` would work just fine, without the need for `grep -l`.

I wonder why the same logic is not applied in case of `:(un)select !`. Here, the output of the shell command after `!` must be pure file names only. Not a big deal, as the command can be adjusted to return just file names, but I see no reason why the logic should be different.

**Comment by xaizek** [comment]
> As I understood, if a file name is the first thing on the line, it can be followed by arbitrary stuff, which will be discarded.

Vifm tries to parse each line as usual format of `<file>[:[<line>:[<col>:]] <anything>]` and `<file>` is taken from that.

> I wonder why the same logic is not applied in case of `:(un)select !`.

I don't think there is a particular reason. If we aren't strict with `%u`, we might do the same with `:[un]select !`. This just wasn't noticed before, thanks.
