### ISSUE TITLE
Problems with filename beginning with equal sign (=)

### ISSUE THREAD

**Issue by agguser** [vifm/vifm#333]
Try `:!!ls %c`, for example, when current file has name beginning with `=`, versus when not. (Tested on Linux.)

**Comment by xaizek** [comment]
Could you please elaborate on expected vs. actual behaviour? I don't see any difference, file name is printed fine in both cases. Maybe it's something command specific (have you tried `:!!echo %c`?) or depends on vifm's version (which one are you using?).

**Comment by agguser** [comment]
vifm 0.9.1 on Arch Linux.

With `:!!ls %c` (or `:!!echo %c`):
- when current filename does not begin with =, filename is printed, "Press return ..." is displayed, waiting for `<CR>` key.
- when current filename begins with =, screen flicks, but nothing happens.

**Comment by xaizek** [comment]
This seems to be zsh-specific (from `man zshexpn`):

```
   `=' expansion
       If a word begins with an unquoted `=' and the EQUALS option is set, the
       remainder of the word is taken as the name of a command.  If a command
       exists by that name, the word is replaced by the full pathname of
       the command.
```

You're right that `=` isn't escaped at the moment. Thanks for the report!
