### ISSUE TITLE
Crash on ui_cancellation_enable()

### ISSUE THREAD

**Issue by cdlscpmv** [vifm/vifm#338]
Steps to reproduce:
1. `mkdir test`
2. `touch test/foo`
3. `chmod a-w test`
4. Add the `%{system(<any command>)}` macro to statusline.
5. Now try to remove `test` and hit `a` to abort.

As I see it, `ui_cancellation_enable()` is first called from `exec_io_op()`, then statusline update happens  via `ui_stat_update()`, which triggers`execute_cmd()`,
which, in turn, calls `ui_cancellation_enable()` the second time (and the assertion fails).

**Comment by xaizek** [comment]
Thanks, I'm able to reproduce it.

**Comment by xaizek** [comment]
Your explanation of what goes wrong is also correct, thanks for it.

**Comment by cdlscpmv** [comment]
You are welcome! I thought I would fix it myself, but then realized that it requires someone familiar with the codebase to look at it.
