### ISSUE TITLE
add -autoexit to ffplay in vifmrc

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#339]
ffplay without -autoexit in vifmrc as a default player for mp3 files is a bad idea, especially when playing audio from a fuse remote filesystem (e. g. sshfs) as the player does not exit automatically after playback. ctrl-c works but is also propagated to fuse and results in unusable fuse mount.

https://github.com/vifm/vifm/blob/c3806023707f16d3c5aac58df7257fce14a12905/data/vifmrc#L194

**Comment by xaizek** [comment]
Will add `-autoexit`, thanks!
