### ISSUE TITLE
Status line does not refresh properly after entering visual append mode

### ISSUE THREAD

**Issue by psmolak** [vifm/vifm#340]
After entering into visual append mode by pressing `av` from inside visual mode, the status line shows `--VISUAL--` instead of `--VISUAL-- (append)`. Though it does refresh after moving to another file inside the view.

To recreate first enter visual mode by pressing `v`, then `av`.

Perhaps not that important, although very annoying.

**Comment by xaizek** [comment]
I'm able to reproduce it, thanks for the report.

**Comment by psmolak** [comment]
It works now, thank you.
