### ISSUE TITLE
Suggestion box disappears after timeoutlen miliseconds

### ISSUE THREAD

**Issue by psmolak** [vifm/vifm#341]
Let's say I have these lines inside my vifmrc
```vim
nunmap t

nnoremap tw :set wrap!<cr>
nnoremap tn :set number!<cr>
nnoremap tr :set relativenumber!<cr>

```
then, whenever I press `t` I would expect Vifm to show suggestion box with possible mappings - which it does - however the suggestion box disappears after `timeoutlen` milliseconds and single keystroke mapping `t` is invoked which selects current file. It seems like there is no way to clear default mappings. Using `nmap t <nop>` doesn't work either.

I could set `timeoutlen` to something bigger as a simple workaround since I don't relay on this anyway.

**Comment by xaizek** [comment]
> It seems like there is no way to clear default mappings.

That's correct.

> [...] the suggestion box disappears after `timeoutlen` milliseconds and single keystroke mapping `t` is invoked which selects current file.

Yes, that's how ambiguity of common prefixes between user defined and builtin commands is resolved.

I'm actually not aware of any way to make something like this work in Vim too. Maybe a special sequence similar to `<silent>` could be invented to make user defined mappings ignore conflicting builtin ones, e.g. (`<wait>` in the example as Vim's `<nowait>` is close to have the meaning which is opposite to what's needed here):
```vim
nnoremap <wait> tw :set wrap!<cr>
nnoremap <wait> tn :set number!<cr>
nnoremap <wait> tr :set relativenumber!<cr>
```
