### ISSUE TITLE
random lock ups after invoking external command

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#342]
i cannot see any pattern but the frequency of the problem is annoying enough to raise an issue here. sometimes after i call an external command using :!! and when it finishes instead of getting back to vifm it just stops responding. here is an example console output after running josm:
```
...
2018-07-14 20:29:35.858 INFO: Loading 000136.jpg using default toolkit
2018-07-14 20:29:35.912 INFO: Loaded 000136.jpg with dimensions 1 920x1 080 memoryTaken=7m exifOrientationSwitchedDimension=false
Press return ...
^M^C^Z^M^C^C^C^M^R^M^Q^S^A^C

```
you can see i did press Enter several times (^M), yet there's no reaction. the only way out is to kill vifm and start a new session. i'd like to debug it somehow but have no idea where to start.

**Comment by xaizek** [comment]
The first thing I would try on such a hang is running `pstree` and looking for that instance of vifm to see whether it has shell running as a child process.

This `Press return...` message comes from a trivial [vifm-pause script](https://github.com/vifm/vifm/blob/0e7e1403586059b2547f7418cd9123b15d977d63/src/vifm-pause):
```bash
#!/bin/sh

echo "Press return ..."
read dummy
```
Assuming that it hangs, to see whether it did read something or not, I'd add an `echo` after `read`. If it's not the script (I think it could hang if terminal state is messed up), then maybe vifm fails to detect that child process has finished running in which case running it with `--logging` could give some information (there isn't much logging, but could be something useful).

**Comment by jose1711** [comment]
thank you, messed up terminal really looks like the cause here. i added set -x and echo after read and after a short test i got into this:
```
+ echo 'Press return ...'
  Press return ...
    + read dummy
        ^M^M^M
```
will try with logging turned on

**Comment by xaizek** [comment]
If it hangs in the script, logging won't show anything new. Vifm doesn't get control between application ending and `vifm-pause` starting. Terminal state can be dumped with `stty -a`. Maybe adding it to `vifm-pause` and comparing the outputs with and without hang will show the difference.

**Comment by jose1711** [comment]
indeed there's a difference in a few flags. these three seems to be responsible:
working fine:
```
icrnl onlcr isig
```
stuck:
```
-icrnl -onlcr -isig
```
test case:
```
➜  ~ read foo

➜  ~ stty -icrnl -onlcr -isig
➜  ~ read bar
^M^M^C^C^C :-(
```

**Comment by xaizek** [comment]
Thanks for debugging this. I guess we need to put terminal in a reasonable state by enabling those flags ourselves or doing something equivalent (<kbd>Ctrl-J</kbd> works even in this broken state, by the way). And since `stty` is being needed either way we can also implement other stuff using it:

1. Clear input stream before pausing.
2. Return to the old behaviour of accepting any single key press instead of requiring enter (`read -n` is not part of POSIX).

**Comment by jose1711** [comment]
thank you for <kbd>Ctrl-J</kbd> tip. i can live with this workaround for now.

**Comment by xaizek** [comment]
Since you have already edited `vifm-pause` you can just add `stty icrnl onlcr isig` before `read`.
