### ISSUE TITLE
Segmentation fault with vifmrc containing UTF-8 encoded character

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#346]
my vifmrc contains a mapping that allows me to use insert for tagging and moving one item down:
```nnoremap  tj```
it works as expected until you change ```LC_ALL``` to ```C```. then you get a segmentation fault. you should be able to reproduce using these steps:
```
# add nnoremap line
echo 'bm5vcmVtYXAg7oWLIHRqCg==' | base64 -d >>~/.vifm/vifmrc
LC_ALL=C vifm
```

**Comment by xaizek** [comment]
I've confirmed this a while ago, but haven't addressed it yet. It fails in `:map`, typing the same command in a session causes segfault too. Failure to convert to Unicode isn't handled properly, but it should be, crashing isn't an option. I was thinking about enforcing use of UTF-8 on such failure, but maybe that's too much and input should be expected to match current locale. Thanks for the report.
