### ISSUE TITLE
fileviewer enabled for mime-type causing fuse errors (archivemount)

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#351]
if i put the following into vifmrc
```
fileviewer <xyz> cat %c
filetype *.7z,*.xz,*.gz,*.tar,*.tar.gz,*.tgz,*.rpm,*.deb,*.cpio
        \ FUSE_MOUNT|archivemount %SOURCE_FILE %DESTINATION_DIR
```
then start vifm and navigate to a directory with couple of archives (tgz, deb) while view mode is enabled and start to navigate into the archives (causing fuse mount call)  and back shortly after i start getting errors such as:
```
FUSE MOUNT ERROR
FUSE UMOUNT ERROR - Can't unmount .... It may be busy
```
error log is not very specific:
```
18.07.20 20:40 at int/fuse.c:229 (fuse_mount)
               Load stage: 3
               FUSE mount command: `archivemount /home/jose/somefile.tar.xz /home/jose/.local/share/vifm/fuse//somefile.tar.xz 2> /tmp//vifm.errors_29413904_00`
18.07.20 20:40 at background.c:362 (bg_and_wait_for_status)
               errno: No child processes
               Failed waiting for process: 915
18.07.20 20:40 at int/fuse.c:252 (fuse_mount)
               FUSE mounter didn't exit!
18.07.20 20:40 at event_loop.c:88 (event_loop)
               Entered into this function
```
despite the error the filesystem is mounted. if i remove the fileviewer line, fuse mounts works normally. the problem does not manifest itself with view mode disabled.

**Comment by xaizek** [comment]
Thanks for the report. Didn't manage to reproduce this yet, but I think I know what might be causing it since both preview and mounting run external process, but probably do this a bit differently.

This happened on 0.9.1, right? Also, were archives big, i.e. should it take long time to open them?

**Comment by jose1711** [comment]
yes, this problem has been spotted on 0.9.1

**Comment by xaizek** [comment]
Still couldn't reproduce it and staring at the code doesn't help in seeing what could go wrong (handling of `SIGCHLD` looks correct and I thought it's the cause). I've pushed `issue351` branch with some extra logging for this issue, please give it a try when you can, maybe something interesting will show up in the log.

**Comment by jose1711** [comment]
i am sorry but i can no longer reproduce this (neither with 0.9.1 nor with current HEAD) - was trying really hard to make it fail again. maybe i hit some other problem which has already been fixed by update. thank you for time, will close it now.
