### ISSUE TITLE
copy and move operations automatically skipping files already present on target

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#352]
at the moment if vifm detects that one of the tagged source file is already on the target it will cancel the whole copy/move operation. copy! or move! is not ideal either because it could be io intensive. running compare is timeconsuming. one can still do ```:!!rsync -av %d/ %D``` but i wish there's more elegant way. maybe imove/icopy (i for ignore files already present)

**Comment by therealmaxmoon** [comment]
Have you found a solution yet? 

And could you figure out how to get the --progress from rsync into vifm?

**Comment by jose1711** [comment]
Nah, I still run `rsync` in a separate terminal window

**Comment by xaizek** [comment]
If it's of any use, you can do
```
:!rsync -av --progress %d %D %i 1>&2 & 
```
and then view progress in the error stream of the job (open `:jobs` menu and press <kbd>e</kbd>).

> maybe imove/icopy (i for ignore files already present)

I think this makes a case for options for :commands, Vim has `++opt`. Alternatively, this might be a subset of recurring question about `:copy` and `:move` not liking conflicts. But in this case for backward compatibility it should also be controlled by an option or be different commands.

By the way, with `:put`/<kbd>p</kbd>/<kbd>P</kbd> you have the "Skip all" option for conflicts.

**Comment by therealmaxmoon** [comment]
> and then view progress in the error stream of the job (open `:jobs` menu and press e).

Those are a lot of steps to see what is going on. If it's a long job, you even have to scroll down/go to the bottom and those are even more key presses.

Is there a way to show the progress in the status bar, like `:copy &` is doing it?

**Comment by xaizek** [comment]
> Is there a way to show the progress in the status bar, like `:copy &` is doing it?

No, there isn't.
