### ISSUE TITLE
vifmrc examples

### ISSUE THREAD

**Issue by Aetet** [vifm/vifm#359]
Hey, @xaizek . 
Could you provide your vifmrc file? 

As long as I use vifm, as clear I realize how less I know about vifm and its features.
It would be useful see some tips and tricks for everyday use.

I found https://github.com/xaizek/dotvifm but it feels outdated

**Comment by xaizek** [comment]
Hi there.

Things tend to stabilize, so it's not really that outdated and mostly matches current version, although I did forget to commit changes. I've pushed some updates now that don't require use of development version of vifm.

**Comment by Aetet** [comment]
Thanks!
