### ISSUE TITLE
Copying files does not preserve file ownership

### ISSUE THREAD

**Issue by willemw12** [vifm/vifm#361]
Version 0.9.1. Linux. Default vifmrc file used.

When running vifm as root, for example to restore files from backup which are only accessible by root,                                                                  
then a file copy does not copy the file ownership. The copied files are owned by root.          

I understand that running as root is not the normal use case.

Same result whether "set syscalls" is enabled or disabled.

**Comment by xaizek** [comment]
> This used to work:

I'm not sure, nothing is being copied by 0.8 or 0.8.1 versions. And that issue is about moving, which does preserve owner when on the same mount.

**Comment by willemw12** [comment]
I agree. Please ignore my comment about that it used to work. I'll remove that comment.
