### ISSUE TITLE
[Request] Enable hints in ruler 

### ISSUE THREAD

**Issue by FirasSadiyah** [vifm/vifm#362]
Many thanks for the amazingly useful app and the fantastic documentation.

Currently, hints are displayed in the `statusline` which is quite busy displaying properties of selected directory/file. I tried to move hints to the ruler using `set rulerformat` but the `%z%`  is not recognisable. 

Is it possible to use the left side of the ruler to display hints?

**Comment by xaizek** [comment]
Glad to hear you find vifm useful.

> Is it possible to use the left side of the ruler to display hints?

It needs to be allowed in the code. I've tried it:

![screenshot](https://user-images.githubusercontent.com/459736/44954246-b16b7a00-ae8e-11e8-8fbd-8aef8e0db29f.png)

As you can see it moves input field to the left (where `g` is) and it will also make `Press ENTER or type command to continue` message to appear more often (as available width for messages shrinks), but I suppose `%z` can be allowed there, in wide terminals its affects are less noticeable.

**Comment by FirasSadiyah** [comment]
Many thanks for trying it out. I think if it is going to affect the input field and still requires a wide terminal to display the message, then I would rather keep the original implementation. Much appreciated.
