### ISSUE TITLE
vifm.info does not open 

### ISSUE THREAD

**Issue by Aetet** [vifm/vifm#363]
I live at Russian Federation. And I cannot open vifm.info from my browser it sends 504 Gateway Time-out. But if I switch on proxy at England, it opens without any trouble.

I talked to my provider, but they don't know reason. Because they don't block site with Roscomnadzor.

It doesn't open with different providers too.

Any ideas why?

**Comment by xaizek** [comment]
It still could be Roscomnadzor's censorship of some IP network. Maybe tool or site mentioned in [this post](https://www.linux.org.ru/news/opensource/14174235) will be of some use.

Or it could be a temporary connectivity issue on the way between Russian Federation and Germany where the server is located, in which case it should be resolved after some time. Or is the site unreachable for you for long time already?

**Comment by Aetet** [comment]
I found [judgement desicion](https://www.sudact.ru/regular/doc/vfrPvtBn8lJs/?regular-txt=&regular-case_doc=+2-2636%2F2016&regular-lawchunkinfo=&regular-doc_type=&regular-date_from=02.03.2016&regular-date_to=02.03.2016&regular-workflow_stage=&regular-area=&regular-court=&regular-judge=&_=1536210085788)
This site unreachable for a long time already.

**Comment by xaizek** [comment]
Right, it was easier to find it in the list than I thought. Thanks for bringing this up. It seems that the site has been successfully migrated to a different data center and now has a different IP which isn't on that list. Try it out, it might take some time for updated DNS records to propagate.

**Comment by Aetet** [comment]
Thanks a lot. It's open!
