### ISSUE TITLE
Strange bookmarks behaviour (switched order)

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#364]
please consider this scenario. in my case neither bookmarked directories did not exist. this test was run on arch linux 64bit, vifm v0.9.1-321-g820b64974e5a-dirty.
* `useradd -m foouser`
* `su - foouser`
* `id` => 2003
* `:bmarks`
* delete all bookmarks if needed
* `:bmark! /var/run/media/foouser/ foo1`
* `:bmark! /run/user/2003/gvfs/ foo2`
* `:bmarks`
  ```
  Bookmarks
  /run/user/2003/gvfs/: [foo2]
  /var/run/media/foouser/: [foo1]
  ```
* select the 1st bookmark (`foo2: /run/user/2003/gvfs/`) and step into it
* receive an error message about foo1
  ```
  File "/var/run/media/foouser/" doesn't exist
  ```

**Comment by xaizek** [comment]
Didn't create a new user, the bug can be reproduced without it at least here.

By the way, `:delbmarks!` removes all bookmarks.

Thanks!
