### ISSUE TITLE
Preview of files in millerview

### ISSUE THREAD

**Issue by Svadkos** [vifm/vifm#365]
Can you add option to enable preview of files in `millerview`?

**Comment by Svadkos** [comment]
Or maybe make previews of directories in `view` to look more like the third panel of `millerview`?

**Comment by xaizek** [comment]
A value to `'milleroptions'` could probably be added. Need to think which way (modifying miller view or preview when in miller view) would work better.

**Comment by xaizek** [comment]
I haven't actually thought about it much. I just tried to draw third column on the other pane, it seems to work, but less-like viewing won't work in this case, which is inconsistent. I need to see if preview in the same view works, in particular with graphics. The latter option is probably preferable as it seems to lead to less inconsistencies in behaviour.

**Comment by xaizek** [comment]
To enable it:
```
set milleroptions+=rpreview:all
```

**Comment by TomJansen** [comment]
Awesome! Thanks!
Don't forget to update https://vifm.info/manual.shtml :)

**Comment by xaizek** [comment]
> Don't forget to update https://vifm.info/manual.shtml :)

It will be updated on the next release, online docs don't track development version (or people might find there things which aren't available yet).

**Comment by SearyBlue** [comment]
Is there any way to toggle this behaviour?

**Comment by xaizek** [comment]
> Is there any way to toggle this behaviour?

I don't really like to invoke external command to do this simple check, but this should work:

```vim
nnoremap <silent> ,f : if system('echo '.&milleroptions.' | grep rpreview:all')
                    \|     set milleroptions-=rpreview:all
                    \| else
                    \|     set milleroptions+=rpreview:all
                    \| endif<cr>
```

I'll probably make `set milleroptions^=rpreview:all` work to make this task easier.
