### ISSUE TITLE
Set shell working directory after leaving Vifm

### ISSUE THREAD

**Issue by Svadkos** [vifm/vifm#366]
I know about [that](https://wiki.vifm.info/index.php/How_to_set_shell_working_directory_after_leaving_Vifm) wiki page, but with this script i can't chose directory in which vifm should start with `vifm /path/to/directory`.

Is there a better way to do that, something that i can put in config file?

**Comment by durcheinandr** [comment]
**Since 0.8:**

Just change the `local dest..`-line with

```
local dst="$(command vifm "$@" --choose-dir - )"
```

or use the vifm-command and the shell-function **prior 0.8**.

Both should work

**Comment by Svadkos** [comment]
You're right, thank you.
