### ISSUE TITLE
How to make `neovim` as default editor of vifm when opening files?

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm#368]
I can't seem to find anything on the man page,  basically How can I make vifm open files using neovim instead of vim?

**Comment by xaizek** [comment]
There is [`'vicmd'` option](https://vifm.info/vimdoc.shtml#vifm-%27vicmd%27). Setting it to `nvim` in `vifmrc` should work:
```vim
set vicmd=nvim
```

**Comment by cevhyruz** [comment]
Thanks for fast response! It works now.
