### ISSUE TITLE
How to source another .vifm file in vifmrc?

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm#370]
I want to source an external .vifm file in vifmrce is this possible? I can't seem to find it in the man page.

**Comment by xaizek** [comment]
Yes, use [`:source` command](https://vifm.info/vimdoc.shtml#vifm-%3Asource) for that.

Also, [q&a site](https://q2a.vifm.info/) might be a better choice for such usage questions.

**Comment by cevhyruz** [comment]
Thnks!
