### ISSUE TITLE
Vifm manual: Command examples use curly quotes

### ISSUE THREAD

**Issue by mwgkgk** [vifm/vifm#373]
See https://vifm.info/manual.shtml#Commands - many examples, like this:
```vim
" command to enter .git/ directory of git-repository (when ran inside one)
command! cdgit :execute ’cd’ system(’git rev-parse --git-dir’)
```
Should be:
```vim
" command to enter .git/ directory of git-repository (when ran inside one)
command! cdgit :execute 'cd' system('git rev-parse --git-dir')
```

Just want to add that it always blows my mind how much can this system do. Fzf + vifm is something out of this world :)

**Comment by xaizek** [comment]
Seems to happen only when converting to HTML, will check how to prevent that. Thanks for pointing it out!

**Comment by xaizek** [comment]
Done. In case anyone else will need to figure out the same thing: replace `'` with `\(aq` before converting to HTML (`sed "s/'/\\\\(aq/g" | groff -Thtml -man`).
