### ISSUE TITLE
Color manager used before it's initialized

### ISSUE THREAD

**Issue by nbuwe** [vifm/vifm#374]
`setup_ncurses_interface` calls into color manager (via `cs_load_defaults`)
https://github.com/vifm/vifm/blob/f23325ba05809b2186d4250d521cf9a9d4cf3301/src/vifm.c#L278
before color manager is initialized a bit later in https://github.com/vifm/vifm/blob/f23325ba05809b2186d4250d521cf9a9d4cf3301/src/vifm.c#L293

By luck it just silently fails to do anything.

**Comment by xaizek** [comment]
Thank you!
