### ISSUE TITLE
Tab colors with tabscope=pane

### ISSUE THREAD

**Issue by mwgkgk** [vifm/vifm#377]
There is no highlight group for active tabs with `tabscope=pane`. Inactive tabs use `TopLineSel` & `TopLine` depending on which pane is selected. I didn't find the matching group in the manual.

LOVE this release.

**Comment by xaizek** [comment]
Have you tried setting `TabLineSel`? This does change color for current tab's tip with `tabscope=pane` for me:
```vim
hi TabLineSel ctermfg=red
```

**Comment by mwgkgk** [comment]
Correct. I got self-bamboozled with overlapping colors.
