### ISSUE TITLE
vifmrc: adding xsel in. proposal

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#379]
Don't you mind to add any example with xsel (working with clipboard)?
It took me a while to come up with this:
`nnoremap yf :!echo -n %c:p | xsel --input --primary %i && echo -n %c:p | xsel --clipboard --input %i<cr>`
`echo -n`: for disable output of trailing newline;
`xsel --input`: to make it work;
`&&` and `xsel --clipboard`: to make possible to paste not only via the middle mouse button but and with <C-S-v> in a terminal emulator. Don't know more elegant way.

**Comment by chelovechishko** [comment]
Okay, accidentally i saw a https://wiki.vifm.info/index.php/How_to_copy_path_to_current_file/directory_to_system_clipboard
So, proposal now applied to the site, i guess?

**Comment by xaizek** [comment]
> So, proposal now applied to the site, i guess?

It could be added there for sure. But maybe it's worth adding `yd`/`yf` to sample files too with checks for what command is available, it will also demonstrate how to do such checks.
