### ISSUE TITLE
about root and dirs extensions

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#382]
Don't know anything about dirs extensions, but `viewcolumns=5{fileext},-{root}` makes a directory "`Е. В. Стругова, Н. С. Шефтелевич`" looks like "`Е. В. Стругова, Н. С`".
If with `{root}` a directory has to have an extension, could you add another `{something}` to display dirs as they can not has an extension?

**Comment by xaizek** [comment]
`{root}` is related to `:r` filename modifier, so that's why it doesn't differentiate between files and directories.

> If with `{root}` a directory has to have an extension,

Since there is `{fileext}`, it makes sense to keep `{root}` as is.

> could you add another `{something}` to display dirs as they can not has an extension?

I think I was contemplating adding `{fileroot}`, but wasn't sure there is a need for that.
