### ISSUE TITLE
using of atool

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#386]
```vim
filetype *.7z,*.bz2,*.cab,*.cpio,*.deb,*.gz,
        \*.msi,*.pkg,*.rar,*.tar,*.tgz,*.xz,*.zip
        \ als %f | less
command extract aunpack %f &>/dev/null &
nnoremap ex :extract<CR>
```
Don't know better binding of course.
atool is too verbose for me and --verbosity=0 don't work (about stdout)
and gives me `Wide character in setenv at /usr/bin/aunpack line 33` (about stderr)
And backgrounding it to remove flicker.
I wrote just several extensions for example.
For those who use it.

**Comment by xaizek** [comment]
Made a [wiki page](https://wiki.vifm.info/index.php?title=How_to_use_atool_to_work_with_archives&action=edit&redlink=1) out of this as it's a more appropriate place for such things.

**Comment by laggardkernel** [comment]
The preview doesn't work well on my side. `.rar` and `.7z` archivers are displayed as mojibake in the preview. Do you have similar problem with these two extensions?

**Comment by xaizek** [comment]
Do you mean quickview/view mode? For that you need to use `:fileviewer` instead of `:filetype` above:
```vim
fileviewer *.7z,*.bz2,*.cab,*.cpio,*.deb,*.gz,
          \*.msi,*.pkg,*.rar,*.tar,*.tgz,*.xz,*.zip
          \ als %f
```

**Comment by laggardkernel** [comment]
How stupid I'm. I don't realize it's `filetype` in this example but not `fileviewer` 😳.
