### ISSUE TITLE
Open files with default application

### ISSUE THREAD

**Issue by sschellhoff** [vifm/vifm#387]
Is there a way to configure vifm to use the default applications to open specific files? Like you don't have to tell Nautilus or Dolphin or whatever filemanager you use what programs to use for what filetypes. I don't want to configure this for every type by hand. So is there a way that vifm just uses the defaults from the os?

**Comment by chelovechishko** [comment]
As the `vifmrc` said:

> " Open all other files with default system programs (you can also remove all
> " :file[x]type commands above to ensure they don't interfere with system-wide
> " settings).
> " For *nix:
> " filetype * xdg-open

**Comment by jubalh** [comment]
Yes, `xdg-open` is the way to go on Linux.

**Comment by sschellhoff** [comment]
Thank you alot :) Could not find this option in the vifmrc before.
