### ISSUE TITLE
<c-g> and small screen

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#388]
After `<c-g>` if the information can not fit inside the screen [of a terminal emulator], then the end of information is unreadable. If space before every line is needed, then maybe add a possibility to scroll the information?

**Comment by xaizek** [comment]
I think empty lines were added just because the dialog looks somewhat empty otherwise.

#316 might actually result in this dialog being done some other way, but until then it could make sense to do something too. If height is small, empty lines can just go away and then get scrolled if it's needed.
