### ISSUE TITLE
Can't open files in vifm

### ISSUE THREAD

**Issue by svemoe** [vifm/vifm#390]
Hello,

I'm having problems opening files (or basically launching any application) from inside vifm.
When I try to open a file (no matter what file) with enter, the terminal just flickers, but nothing happens.
When I type :e on a text file, the edit error "can't edit selection" appears.

I'm using dwm on archlinux, I tried urxvt, termite, st, and xterm as terminal emulators.
When using xterm it worked just fine. But when I tried it with a tmux session inside xterm it also did'nt work.
I tried it in tty without graphical environmen, it didn't work.
But when I run vifm as root I worked in every Terminal.

As far as I can tell, the shell makes no difference, I tried bash and zsh and got the same results.
I ran vifm with the --no-configs flag to see if I configured something wrong and it's the same.
The other text-based filebrowser that i tried (ranger, nnn, lf) worked just fine.

I really don't know whats going on here, I didn't find the problem in the Internet.
And it's very hard to pin down what is the problem.
Maybe someone has a clue.

Thanks :smile:

**Comment by xaizek** [comment]
Hi,

> But when I run vifm as root I worked in every Terminal.

Different users have different settings, I'm guessing that there is something in environment which causes this and it somehow doesn't affect `xterm`.

You can try running `vifm` in a terminal where it doesn't work like this:
```
env - TERM=$TERM HOME=$HOME PATH=$PATH LANG=$LANG vifm
```
This should reduce environment variables to the bare minimum and maybe it will start.

You also didn't mention whether running commands like `:!vim` work in all terminals, do they? Editing could be just a special case of the issue.
