### ISSUE TITLE
Q: cannot access zsh shell function at vifm command line

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#393]
This is not to report an issue, but ask a question. How to make shell aliases and functions work in vim is the last item in the vifm FAQ: https://github.com/vifm/vifm/blob/master/FAQ -- quoted below.

> Q: How to make shell aliases and functions work in vifm when running them like ":!foo"?
> A: Here is solution for bash, other shells should allow to do something similar.
>    1. Add the following lines to ~/.bashrc
>       shopt -s expand_aliases
>       unset BASH_ENV
> 
>    2. Add the following line to \~/.vifm/vifmrc
>         let $BASH_ENV='\~/.bashrc'

I tried to follow the instruction for `zsh` but to no avail. By default, zsh always expands aliases. I searched online and tried various things but none worked. I wonder what configuration is required to access zsh functions at vifm command line.

**Comment by xaizek** [comment]
> ask a question

There is also https://q2a.vifm.info/ available.

> By default, zsh always expands aliases.

I suspect that only when it's run in interactive mode. If you set `'shell'` to point to a script that does
```
zsh -i "$@"
```
it might work.

Better way of doing it would be to add `'shellcmdflag'` option to allow specifying `-i`, but setting it to `-ic` caused some weird behaviour, so it wasn't added. Maybe it makes sense to make it work.

**Comment by randomizedthinking** [comment]
Will ask such question at q2a site in the future.

I don't  think vifm has `shellcmdflag` option?

For now, I will use `zsh -i` to add one layer of indirection. Thanks!

**Comment by xaizek** [comment]
> I don't think vifm has shellcmdflag option?

>> so it wasn't added

I probably used its value in too many context, which broke interaction with the shell in a weird way (vifm gets through in background and doesn't really come back).

**Comment by stephencheng** [comment]
@xaizek I am hitting the issue of using zsh function same as above.

I am not clear of your conversation and what the steps are to make it work. And I couldn't understand clearly of the code change and man page to make it work.

Could you brief a few steps ?

For example, if I am using zsh and have a _zlua function

1. what the change is reuired in vifmrc?
2. what the command line looks like?
eg.
command mycmd :execute 'cd' "'".term("dir=$(_zlua|sort -nr|awk '{print $2}' |  fzf 2> /dev/tty); echo $dir")."'"

Thanks

**Comment by xaizek** [comment]
You'd just do `set shellcmdflag=-ic`, but #471 points out that it causes issues in other places.

For your command you can try adding `zsh -ic` before `_zlua`:

```vim
command mycmd :execute 'cd' "'".term("dir=$(zsh -ic _zlua|sort -nr|awk '{print $2}' | fzf 2> /dev/tty); echo $dir")."'"
```

**Comment by stephencheng** [comment]
Thanks, I guess it will be heavy job to load zshrc and loads of irrelevant functions in order to call this command. I gave up. In stead I did some preprocess every time vifm starts up. Pretty happy about it.

**Comment by mustaqimM** [comment]
Hey @xaizek, I'm having trouble using this. I have it as:
```zsh
set shellcmdflag=-ic
command! extract :execute extract %c
nnoremap x :extract<cr>
```
where extract is this [function](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/extract); how do I call the function in background on a file?

**Comment by xaizek** [comment]
You're using `:command` incorrectly. Calling external command in background looks like this:
```vim
command! extract extract %c &
```
