### ISSUE TITLE
can't find vifm-help.txt

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm#397]
I installed vifm version 0.10 using the method described in INSTALL file but it seems I don't have the `vifm-help.txt` whenever I run `:help` it gives me an error.

**Comment by xaizek** [comment]
Strange, if you have `groff` or `mangen` it should be generated, installed and copied on startup (provided that correct binary is used, i.e. one which refers to `vifm-help.txt` at the path at which it was installed).

You can also try setting `set vimhelp`. Maybe this will work.

> it gives me an error.

What's does the error message say? Does it appear inside vifm or in Vim?

**Comment by cevhyruz** [comment]
okay, it seems I just missed the `make install` part as I was just skimming the INSTALL file (afterall I'm really sleepy that time).. thanks for the response anyway..
