### ISSUE TITLE
Highlighting file extensions won't "overwrite" executable hightlight setting

### ISSUE THREAD

**Issue by TomJansen** [vifm/vifm#398]
Like the title says. For example if `highlight Executable` is set to yellow, a .zip will also turn up yellow, even when I defined it another color. This even happen when I fully comment out the Executable setting

**Comment by xaizek** [comment]
Is this issue done or you think something needs to be changed?

**Comment by TomJansen** [comment]
This can be closed, you explanation made sense :). Zip file highlighting works.
