### ISSUE TITLE
problems with preview

### ISSUE THREAD

**Issue by agguser** [vifm/vifm#403]
1. `%py` in `fileviewer` in `vifmrc` causes erasing preview text when switching to preview pane (e.g. with <kbd>Ctrl-W w</kbd> or <kbd>Shift-Tab</kbd>).
```sh
$ cat ~/.vifm/vifmrc
…
fileviewer *.1 sh -c 'file "$1"' -- %c %px %py %pw %ph
fileviewer *.2 sh -c 'file "$1"' -- %c %px     %pw %ph
…
$ touch t.0 t.1 t.2
$ vifm
- :view! (to turn on preview)
- j (to navigate to t.1), Ctrl-W w (to switch to preview pane), notice that the text is erased (BUG??)
- Ctrl-W w, j (to navigate to t.2), Ctrl-W w, notice that the text is NOT erased
```

2. `fileviewer` is called many times when starting `vifm` with preview mode active.
```sh
$ cat ~/.vifm/vifmrc
…
fileviewer *.3 date +%%s | tee -a /tmp/v
…
$ touch t.3 /tmp/v
open another terminal $ tail -f /tmp/v
$ vifm
- :view!
- navigate to t.3 (notice on another terminal that only a single line is added to /tmp/v)
- :q
$ vifm
- (notice on another terminal that MANY lines are added to /tmp/v)
```

**Comment by xaizek** [comment]
1. It's not `%py`, but a combination of `%px` and `%py` that triggers this. It's not documented, but vifm uses presence of both `%px` and `%py` as a marker for graphical preview as they don't really make sense for text preview. Or at least that's what I thought, how did you find this?

2. Yeah, it's called more than once on `:view` too. Every time quickview window is redrawn. Some kind of caching might be needed to account for the redraws. Ideally there shouldn't be so many of them, but it might be hard to archive (although in this case I see 8, which is too much; maybe `<silent>` mechanics could be used to reduce number of redraws at startup).

**Comment by agguser** [comment]
I use a generic script for fileviewer that run specific command for specific file extension,  so I pass all `%p*` arguments, i.e.
```
fileviewer * my_fileviewer.sh %c %px %py %pw %ph %pc clear
```
That's how I discovered the bug.

**Comment by xaizek** [comment]
Not sure this can work well in general. You can probably notice extra flicker yourself.

However, currently view mode just doesn't draw output of the graphical previewer, that's why it's empty. I can make it being displayed, and I think it is for quickview, so it's an inconsistency.

**Comment by xaizek** [comment]
I did some things. The first bullet was easy, but there were more changes for the second one. I'm not exactly sure if all of these changes are safe (i.e., don't break anything else), so they might be revised or even reverted if it turns out otherwise. But on startup there is now only one invocation of a text previewer and two for the graphical one. During the session there should be fewer screen updates as well.
