### ISSUE TITLE
How to use bat as a fileviewer

### ISSUE THREAD

**Issue by CharlesGueunet** [vifm/vifm#404]
Hello,

I have tried to use [bat](https://github.com/sharkdp/bat), as a fileviewer, however it always seems vifm fallback to cat.
The line I have tried is the following (for c and cpp file only first)
```
fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --wrap never --pager never %c -p
```
Do you have any idea of what could prevent `bat` to work ?

**Comment by xaizek** [comment]
Does it work if you do `:!bat %c %q` on some file?

**Comment by CharlesGueunet** [comment]
The result is similar to a cat, no colors, no line numbers. However, the output is correct if I call `bat` on the same file directly in my terminal (not in vifm), with colors and numbered lines.

**Comment by xaizek** [comment]
Then it works, but probably auto-detects that output doesn't go to a terminal and disables everything. Try with:

    fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --color always --decorations always --wrap never --pager never %c -p

**Comment by CharlesGueunet** [comment]
That's it ! your suggestion works :) thanks for the help !

**Comment by mimadrid** [comment]
Sorry to comment to this closed bug but the colors are not working for me
There are not almost colors and they are very different compared to a bat terminal output
In  left panel I'm using this fileviewer config and in the right calling bat directly from terminal
I tested also with the last master branch from vifm and bat
Thanks a lot in advance and I hope to be useful
Don't hesitate to request more information
![vifm-bat](https://user-images.githubusercontent.com/3269878/53297606-eb578080-3820-11e9-8a6d-979c6a1f30d5.png)

**Comment by xaizek** [comment]
After writing stuff below, I thought that your `$TERM` might be wrong. So try running this first:

    echo $TERM
    tput colors

The output you show might occur because `bat` uses 256-color palette, but `$TERM` doesn't communicate support for 256 colors to `vifm`.

*****

Are you sure it's being used? See what `:fileviewer bmarks.c` will give you. If `bat` will be on the first line, try doing:

    fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --color always --wrap never --pager never %c -p && echo Bat got called

Then check that `Bat got called` appears in the preview. If that's fine, show

    bat --color always --wrap never --pager never /tmp/vifm/src/bmarks.c -p | head | cat -A

**Comment by mimadrid** [comment]
@xaizek thanks a lot for all your help and support  :+1: 

I'm using alacritty with tmux and the output is:
```
screen-256color
256
```
I forgot to say that :!bat bmarks.c is working fine 
I checked that bat got called and the output is:
bat --color always --wrap never --pager never /tmp/vifm/src/bmarks.c -p | head | cat -A
```
^[[38;2;117;113;94m/*^[[0m^[[38;2;117;113;94m vifm^[[0m$
^[[38;2;117;113;94m * Copyright (C) 2015 xaizek.^[[0m$
^[[38;2;117;113;94m *^[[0m$
^[[38;2;117;113;94m * This program is free software; you can redistribute it and/or modify^[[0m$
^[[38;2;117;113;94m * it under the terms of the GNU General Public License as published by^[[0m$
^[[38;2;117;113;94m * the Free Software Foundation; either version 2 of the License, or^[[0m$
^[[38;2;117;113;94m * (at your option) any later version.^[[0m$
^[[38;2;117;113;94m *^[[0m$
^[[38;2;117;113;94m * This program is distributed in the hope that it will be useful,^[[0m$
^[[38;2;117;113;94m * but WITHOUT ANY WARRANTY; without even the implied warranty of^[[0m$
```
Many thanks again

**Comment by xaizek** [comment]
> ```^[[38;2;117;113;94m```

These are 24-bit colors, instead of 256 color palette, which looks like `^[[38;5;117m` and `^[[48;5;117m`.

I don't see an option for `bat` to control palette, so I guess it depends on a theme? Either way, `vifm` can't handle 24-bit colors at the moment (`ncurses` added it in 6.1, so it might be possible in the future) and you need to change output of `bat` somehow.

**Comment by mimadrid** [comment]
My fault, you are right
https://github.com/sharkdp/bat#terminals--colors
I will try with a mapping to :!bat %c or with another external tool with a 16/256 palette like  highlight, coderay or rougify
Thanks so much, you and vifm are awesome!

**Comment by xaizek** [comment]
> Make sure that your truecolor terminal sets the COLORTERM variable to either truecolor or 24bit. Otherwise, bat will not be able to determine whether or not 24-bit escape sequences are supported (and fall back to 8-bit colors).

Maybe just try undefining `$COLORTERM`? I guess, that's why it works for @CharlesGueunet. E.g.:

    fileviewer *.[ch],*.[ch]pp,*.[ch]xx env -uCOLORTERM bat --color always --wrap never --pager never %c -p

**Comment by mimadrid** [comment]
That works perfect! :100: 
Thanks a lot, you are incredible

**Comment by jbgriesner** [comment]
I'm sorry to open again this issue, but I've the same problem to use `bat` together with `vifm`, and the suggested above solutions seem to fail on my system.
Whereas `bat` works perfectly outside of `vifm` (my terminal is `st`), I still fail to make `vifm` show the correct output on the side preview panel.

I think my system is ok:
```shell
>  echo $TERM
st-256color
> tput colors
256
```

However if I add this in my `vifmrc`:
`fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --color always --wrap never --pager never %c -p && echo Bat got called`
Then I don't observe the "Bat got called" sentence.

Any help would be welcome :)

**Comment by xaizek** [comment]
Assuming that you're using 0.10.1, if you do `:fileviewer file.cpp` do you see `[present]` in front of `bat` command in the menu that pops up?

**Comment by jbgriesner** [comment]
Indeed:
```shell
> vifm --version
Version: 0.10.1
```

And I see `[present]` as well in the menu that pops up:
![2020-04-18-191456_789x62_scrot](https://user-images.githubusercontent.com/33450151/79644174-71faba00-81a7-11ea-9e43-e2941795b326.png)

Thanks for your help btw :)

**Comment by xaizek** [comment]
This means that `bat` is available in `$PATH`. If `Bat got called` isn't shown at the bottom, then `bat` must be exiting with non-zero code. You can probably replace `&&` with `;` or `||` to get the message.

> I still fail to make vifm show the correct output on the side preview panel.

I should have asked what is shown there at present? Is it not colored? I thought it's not being run at all.

Another modification of the command might be
```vim
fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --color always --wrap never --pager never %c -p | head | cat -A
```
to see any special sequences in the output of `bat`.  You might want to try it even if there is no visible output, in case it's black on black or something like that.

**Comment by jbgriesner** [comment]
I confirm `Bat got called` isn't shown at the bottom (I double check).
I try to replace `&&` with `||` as you suggested, but still didn't get the message...

> I should have asked what is shown there at present? Is it not colored? I thought it's not being run at all.

It displays the "standard preview", _ie_ without any color, just like `cat` does.

And I'm afraid to say I also try your command 
```shell
fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat --color always --wrap never --pager never %c -p | head | cat -A
```
but still nothing appears....

**Comment by xaizek** [comment]
If you run `:execute 'fileviewer' expand('%c')` with cursor on the file you're trying to preview, what's in the menu?

**Comment by jbgriesner** [comment]
Then it outputs this message:
```shell
No viewers match <filename>
```

(I tried on different files, with different extensions...)

**Comment by xaizek** [comment]
`fileviewer *.[ch],*.[ch]pp,*.[ch]xx bat ...` registers `bat` for files that match specified list patterns (`*.[ch],*.[ch]pp,*.[ch]xx`). Maybe you want to use `fileviewer *[^/] bat ...` to cover all files (I assume that `bat` doesn't preview directories).

**Comment by jbgriesner** [comment]
You're right.
It outputs something different:
![2020-04-18-231134_455x281_scrot](https://user-images.githubusercontent.com/33450151/79671135-489e5600-81c8-11ea-80e1-1fef1b0b538e.png)

**Comment by xaizek** [comment]
Drop the `| head | cat -A` part, it was just for debugging to see how colors are encoded, which is what on the screenshot.

**Comment by jbgriesner** [comment]
It works! Thanks a lot! I thought at the beginning it was related to `truecolor` or `256color` or something like that. I wasn't expecting to receive such a fast solution. So thanks again for your help!

**Comment by kevincojean** [comment]
Extra information: 
I had trouble getting `bat` to work with Vifm ; but that's because `bat` was installed under the executable name `batcat`.  
So I adjusted my `fileviewer` command for `bat` to use the `batcat` executable name.
