### ISSUE TITLE
Strange blinking output. 

### ISSUE THREAD

**Issue by belad0** [vifm/vifm#407]
Hi, 

I tried compiling vifm on Tinycorelinux. 

I loaded the usual compile tools and gc, ncurses-dev autoconf and automake. 

I ran: autoreconf && ./configure --without-libmagic --without-gtk --without-X11 --without-dyn-X11 --disable-remote-cmds --disable-desktop-files && make && make install

The program runs OK but directory sizes and some other characters such as are displayed wrong and blink. See the video.

Any ideas what could cause this?

https://github.com/vifm/vifm/files/2911197/vifm.build.log

https://1drv.ms/v/s!AvXghu3umSrJgTlCyUvRCbmD8Dow

**Comment by xaizek** [comment]
Hello,

In what terminal are you running vifm and what is the value of `$TERM`? If it's incorrect, that might be the reason.

**Comment by belad0** [comment]
I found the solution, I was using compiling with ncursew but had ncurses loaded. 
During compilation I unloaded ncurses and used the --with-curses=/usr/local option.
