### ISSUE TITLE
keymap q in normal mode shadows other keymaps

### ISSUE THREAD

**Issue by laggardkernel** [vifm/vifm#409]
```vim
" View preview in Quick Look
nnoremap q :!qlmanage -p %f > /dev/null 2>&1<cr>
```

The keybinding `q` for `qlmanage` shadows `q:`, `q=`, `q?` etc.

**Comment by xaizek** [comment]
Correct, that's how it works in Vim. There are <kbd>ZZ</kbd> and <kbd>ZQ</kbd> and if you do
```vim
nnoremap Z j
```
<kbd>ZZ</kbd> and <kbd>ZQ</kbd> will be shadowed.

You can bring `q*` them back by defining identical user-defined mappings, which will make conflict resolution via timeout kick in:
```vim
" View preview in Quick Look
nnoremap q :!qlmanage -p %f > /dev/null 2>&1<cr>
" Unhide builtin q* keymaps
nnoremap q: q:
nnoremap q/ q/
nnoremap q? q?
nnoremap q= q=
```

**Comment by laggardkernel** [comment]
Thank. Your solution is helpful. Maybe we should add these as default settings. Because the `q` for `qlmanage` exists in the default config.

**Comment by xaizek** [comment]
> Maybe we should add these as default settings. Because the `q` for `qlmanage` exists in the default config.

Makes sense. I didn't recognize it's in sample vifmrc for OS X, thanks.
