### ISSUE TITLE
Suggestion: tabs titles and sessions

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#412]
Tabs are great and have made Vifm even more powerful. After using them a lot, I have two suggestions for your consideration:

Sometimes the current path is not adequate or even legible as a tab title, no matter the option, especially when many tabs are open and the directories belong to the same project tree. A method to set an explicit tab title, like GNU Screen's `title` command, would be useful, e.g. ":title src", ":title target", etc.

Explicit tab titles would be even more useful if sessions could be saved and restored (or even manually created) using config files, more or less like the way Vim does with `mksession`.

**Comment by xaizek** [comment]
Tabs titles are already there. See [`:tabname` command](https://vifm.info/vimdoc.shtml#vifm-%3Atabname).

> Explicit tab titles would be even more useful if sessions could be saved and restored (or even manually created) using config files, more or less like the way Vim does with `mksession`.

There was a small discussion of something along those lines in #378. Having something like `mksession` command should be a good start even without any kind automatic session management.

**Comment by programandala-net** [comment]
xaizek escribió en/skribis je/wrote on/scrit ye 2019-03-14 12:00:

> Tabs titles are already there. See `:tabname`

Sorry. I don't know how I missed it, I usually search the docs for all
new things of every version. It's great, very useful.  Thanks.

> There was a small discussion of something along those lines in #378.
> Having something like `mksession` command should be a good start even
> without any kind automatic session management.

Yes, a `:mksession` to save the current status in a source file would be
enough, so the `:source` command could restore it.  Then the user could
simply associate certain filename pattern (e.g. "*_session.vifm") to be
open with ":source".  That would be very useful.

I'll take a look at that thread.  Thanks again.

-- 
Marcos Cruz
http://programandala.net

**Comment by xaizek** [comment]
> so the `:source` command could restore it

I doubt it could work this way. vifm's scripting capabilities probably aren't enough for that and I don't think they need to be extended in this direction. It would probably be format of `vifminfo` instead (although current one is bad, so it should be a better version of it).
