### ISSUE TITLE
Corrupted highlighting in millerview

### ISSUE THREAD

**Issue by cdlscpmv** [vifm/vifm#413]
Steps to reproduce:
``` 
set millerview
set dotdirs=rootparent
highlight Selected cterm=reverse ctermfg=none ctermbg=none
```
Now try to select the first file in the view in the visual mode. Highlighting of the other two millerview panes gets corrupted.

**Comment by xaizek** [comment]
Thanks for the report. `dotdirs=rootparent` or visual mode isn't necessary, but it makes it easier to see.
