### ISSUE TITLE
Cannot open $CONIN on windows

### ISSUE THREAD

**Issue by dancread** [vifm/vifm#414]
Is reading a file list from STDIN currently supported in Windows? I cannot get it to work. For example:
```
dir /b /s *.h | vifm -
Failed to open CONIN$.
```
Am I understand this feature correctly?
```
vifm --version
Version: 0.10
Git info: v0.10-0-gd11799214d36
Compiled at: Nov 11 2018 17:23:16

Support of extended keys is on
Parsing of .desktop files is disabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
Without file program
With remote command execution
```

**Comment by xaizek** [comment]
> Am I understand this feature correctly?

Yes, you do.

> Is reading a file list from STDIN currently supported in Windows?

Yes. I tried all three Windows binaries of 0.10 release as well as development version, inside bash and cmd.exe. They all worked on Win7.

What OS and terminal (e.g. ConEmu) are you using? Maybe there is something specific about how they handle terminal input/output (things they do might break stuff).

**Comment by dancread** [comment]
Hello,
You are correct about it working in Windows 7. I did some testing on a Windows 7 system and everything worked fine. The issue in question is happening in Windows 10.   I tried starting a plain Command Prompt and Administrator Command Prompt in Windows 10 and I am still getting a "Failed to open CONIN$." message. I am not sure how to get more information on the Windows 10 version. Let me know if additional OS information is required.

**Comment by dancread** [comment]
Assuming this error is coming from here:
https://github.com/vifm/vifm/blob/master/src/utils/utils_win.c#L659
I was looking at the doc here:
https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew

>dwCreationDisposition | You should specify OPEN_EXISTING when using CreateFile to open the console.

I really have no idea why that would make it work or break it on Windows 10, but it was the only thing I can could find that could be opening the console input incorrectly.

**Comment by xaizek** [comment]
Thanks, you're right, that was the issue. Apparently the note was there all along, I missed it, and then they hardened checks. Here's a 64-bit executable of vifm v0.10 + this fix applied: [vifm-win10-fix.zip](https://github.com/vifm/vifm/files/2989387/vifm-win10-fix.zip).

**Comment by dancread** [comment]
Awesome. It is working for me as well. Thanks for the quick turn around!
