### ISSUE TITLE
It is possible to try to move files into the same directory you just yanked them from.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#416]
Version: 0.10
Git info: built out of repository

1. Yank something using "y".
2. Press "P" to move it into the current directory, which is still the same.

Actual results:
"File Conflict", "What to do?". Fortunately, only [r]ename actually does anything.

Expected results:
nothing

**Comment by xaizek** [comment]
> Fortunately, only [r]ename actually does anything.

It wasn't this way before v0.8... This was that data loss case I mentioned in #408. You had to confirm the overwrite.

> Expected results:
> nothing

I think this would make me wonder why nothing has happened and I would try to do it again. Maybe say that it's the same file and leave only rename, skip and skip all options?

**Comment by aleksejrs** [comment]
> I think this would make me wonder why nothing has happened and I would try to do it again. Maybe say that it's the same file and leave only rename, skip and skip all options?

That would also work. The point is that nothing gets lost and thus that nothing suggests that it would.
