### ISSUE TITLE
Half-window movements do not keep in sync selected lines

### ISSUE THREAD

**Issue by zsugabubus** [vifm/vifm#421]
1. Compare two directories.
2. `G<C-U><C-D><C-D>` or `<C-D><C-D><C-D>...<C-U>` or `<C-D>j<C-D>`... etc.
3. The selected line in the other pane gets out of sync.

**Comment by xaizek** [comment]
If you're using v0.10, then it's already fixed:
https://github.com/vifm/vifm/blob/73bfa5f1d40837dbb6b8d93a755518d1ca89e3b9/ChangeLog#L91-L92

**Comment by zsugabubus** [comment]
Thanks! Next time I will look into the change log, too.
