### ISSUE TITLE
vifm-convert-dircolors colorscheme make vifm slow

### ISSUE THREAD

**Issue by Gomme-** [vifm/vifm#422]
Hello,

I followed the manpage and set the output of `vifm-convert-dircolors -e` as my default colorscheme. Afterwards, I remark vifm was really slow (unusable) when scrolling through a directory containing many files. 

I turns out the problem is the "file name specific highlight" part of the colorscheme.
After replacing the default 
`highlight /.*\.ext1$|.*\.ext2$|...|.*\.extn$/I`
by
`highlight /^.*\.(ext1|ext2|...|extn)$/`
the scrolling is way more smooth.

They might be an even better choice of file name matching,  I didn't try other format. It could be interesting to change the default formatting of vifm-convert-dircolors.

I use vifm version 0.10.

**Comment by xaizek** [comment]
Hello,

Please post output of `vifm-convert-dircolors -e` here to test against the same highlight groups you were using.

Also how many files are in directories where slowdown is noticeable? Number of files shouldn't actually matter as results are cached, unless there are files which weren't matched. Absence of matches might not be cached and this could be part of the reason behind slowdown.

**Comment by Gomme-** [comment]
The directory contains 331 files, mostly pdf & djvu.

Here is the output of `vifm-convert-dircolors -e`
```
" generic file types
highlight BrokenLink cterm=bold ctermfg=red ctermbg=black
highlight Device cterm=bold ctermfg=yellow ctermbg=black
highlight Directory cterm=bold ctermfg=blue ctermbg=default
highlight Executable cterm=bold ctermfg=green ctermbg=default
highlight Fifo cterm=none ctermfg=yellow ctermbg=black
highlight Link cterm=bold ctermfg=cyan ctermbg=default
highlight Socket cterm=bold ctermfg=magenta ctermbg=default

" file name specific highlight
highlight /.*\.aac$|.*\.au$|.*\.flac$|.*\.m4a$|.*\.mid$|.*\.midi$|.*\.mka$|.*\.mp3$|.*\.mpc$|.*\.oga$|.*\.ogg$|.*\.opus$|.*\.ra$|.*\.spx$|.*\.wav$|.*\.xspf$/I cterm=none ctermfg=cyan ctermbg=default
highlight /.*\.7z$|.*\.ace$|.*\.alz$|.*\.arc$|.*\.arj$|.*\.bz$|.*\.bz2$|.*\.cab$|.*\.cpio$|.*\.deb$|.*\.dwm$|.*\.dz$|.*\.ear$|.*\.esd$|.*\.gz$|.*\.jar$|.*\.lha$|.*\.lrz$|.*\.lz$|.*\.lz4$|.*\.lzh$|.*\.lzma$|.*\.lzo$|.*\.rar$|.*\.rpm$|.*\.rz$|.*\.sar$|.*\.swm$|.*\.t7z$|.*\.tar$|.*\.taz$|.*\.tbz$|.*\.tbz2$|.*\.tgz$|.*\.tlz$|.*\.txz$|.*\.tz$|.*\.tzo$|.*\.tzst$|.*\.war$|.*\.wim$|.*\.xz$|.*\.z$|.*\.zip$|.*\.zoo$|.*\.zst$/I cterm=bold ctermfg=red ctermbg=default
highlight /.*\.bmp$|.*\.gif$|.*\.jpeg$|.*\.jpg$|.*\.mjpeg$|.*\.mjpg$|.*\.mng$|.*\.pbm$|.*\.pcx$|.*\.pgm$|.*\.png$|.*\.ppm$|.*\.svg$|.*\.svgz$|.*\.tga$|.*\.tif$|.*\.tiff$|.*\.xbm$|.*\.xpm$/I cterm=bold ctermfg=yellow ctermbg=default
highlight /.*\.asf$|.*\.avi$|.*\.cgm$|.*\.dl$|.*\.emf$|.*\.flc$|.*\.fli$|.*\.flv$|.*\.gl$|.*\.m2v$|.*\.m4v$|.*\.mkv$|.*\.mov$|.*\.mp4$|.*\.mp4v$|.*\.mpeg$|.*\.mpg$|.*\.nuv$|.*\.ogm$|.*\.ogv$|.*\.ogx$|.*\.qt$|.*\.rm$|.*\.rmvb$|.*\.vob$|.*\.webm$|.*\.wmv$|.*\.xcf$|.*\.xwd$|.*\.yuv$/I cterm=bold ctermfg=magenta ctermbg=default
```

**Comment by xaizek** [comment]
Thanks, I still don't notice the slowdown, but it seems to be measurable. Your version of the regex appears to be two times faster.

**Comment by Gomme-** [comment]
> Thanks, I still don't notice the slowdown

Mmh that's strange. Here it is clearly noticeable.
I am using an old Thinkpad X220, maybe it plays a role.
Anyway, I don't know what to do to help you here.
Tell me if there is anything I can do.

**Comment by xaizek** [comment]
Since I measured it via perf tool, I didn't need to observe it directly. Also you already tested proposed solution and confirmed that it works. Thanks for reporting this.

However I later lowered frequency of my CPU and confirmed it again as well as that incomplete caching was also to blame. With code update even slow regex seems to work fine, so combined they work even faster.
