### ISSUE TITLE
Fileviewer keeps running even if suggestion box is show

### ISSUE THREAD

**Issue by ks1c** [vifm/vifm#424]
Fileviewer keeps running even if suggestion box is show, causing ueberzug image to be displayed on top of suggestion box. If fileviewer stops to run when suggestion box is been show, this would not happen. Is it possible to add a flag to show file preview only when suggestion box is not been displayed?

using:
vifm 0.10-1
python-ueberzug 18.1.3-2
termite 14-2

![ezgif com-optimize](https://user-images.githubusercontent.com/45995919/55923784-06196500-5bd5-11e9-9ae0-ba4c57418cdd.gif)
![ezgif com-optimize(1)](https://user-images.githubusercontent.com/45995919/55923988-02d2a900-5bd6-11e9-9270-9ab419de2541.gif)

**Comment by xaizek** [comment]
Thanks for the report. I doubt there needs to be an option for this, proposed behaviour makes sense to be the default.

The second gif shows the behaviour you get if previewer changes the file, which vifm then detects and updates screen, which causes file to be updated again, etc. Flicker of suggestions is annoying, but not sure it's easy to get rid of it.
