### ISSUE TITLE
Background Process Error

### ISSUE THREAD

**Issue by philFernandez** [vifm/vifm#425]
I have vifm installed on Mac OS Mojave, via Homebrew. I've been using it without any issues for the past month or so. Now I cannot create, copy, or delete any file without getting an error popup on screen. I'll include a screenshot of the exact error. This happens when trying to delete via dd or DD, paste via p or touch with command :touch. 

![Alt text](https://imgur.com/AhCBsle.png "Optional title")

**Comment by xaizek** [comment]
Maybe your shell value contains something unexpected? See what's the output of `:set shell?` in vifm.  If `'shell'` value is fine, maybe it's something about standard commands like `rm`, `cp`, etc.  I'm guessing this is something external, because I don't see where `&&` could come from inside vifm. Also the error is quite cryptic, so something weird is going on.

You can probably do `:set syscalls` to get rid of this, I guess this option is off at the moment, but it would be nice to know why it happens as well.

**Comment by philFernandez** [comment]
I'm using the version of zsh which ships with Mac OS, and I'm thinking it must be the root of the problem. Upon your suggestion I ran `:set shell?` inside vifm and as expected it returns `/bin/zsh`. I opened up a bash shell, and set `export SHELL=/bin/bash` then opened vifm from bash. Everything works fine there. 

When I access vifm from bash, with `SHELL=/bin/bash` there are no problems, but when accessing vifm from zsh things are broken. In addition to the things that I mentioned already, the trash is also not working. If/when I `dd` to delete a file, and then run `:lstrash` it says trash is empty, or if I press `u` after `dd`ing a file, it says register empty. I can navigate to `.local/share/Trash` and see the file there, but it's not accessible from inside vifm. 

It is strange because I haven't changed anything with my zsh configuration. I even renamed my zshrc, and loaded up plain zsh without any of my config files, and the problem persists. It seems to be some problem which zsh is creating. I'll climb down that rabbit hole now and see if I can determine what the problem is. 

Thank you

**Comment by philFernandez** [comment]
I was able to track down the problem, and it has nothing to do with vifm. I have my zshenv file set up to source some functionality when `$VIMRUNTIME` or `$VIFM` is set so that it is available inside the shell that is spawned when running `:shell` inside vim and/or vifm. One of the files that is sourced is the aliases that are available via the git plugin from oh my zsh. That plugin was recently updated, and something inside of it is causing the problem. When I comment out that line in my zshenv file, the problem goes away. 

Thank you for pointing me in the right direction, and sorry for bringing the problem here when it had nothing to do with this software... oops
