### ISSUE TITLE
Image preview in terminal (catimg or pixterm)

### ISSUE THREAD

**Issue by echuraev** [vifm/vifm#428]
Hi!

First of all, thank you for awesome FM!

I'm trying to enable image preview in tmux. As far as I understand in the latest versions of tmux image preview doesn't work. So, I'm trying to use some tools for ascii graphics such as [catimg](https://github.com/posva/catimg) and [pixterm](https://github.com/eliukblau/pixterm). I have tried both these tools.

I can preview file in terminal:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/5525113/56473329-8a3fd800-6472-11e9-83fe-311bd87c6047.png">

I added the following line to my vifmrc:
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
            \ catimg -w 80 %c:p
```
I expected to see the same picture in vifm but I see the following picture:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/5525113/56473355-f589aa00-6472-11e9-90c3-916ddf3393ed.png">

Could you please help me? What should I do to force catimg to work in vifm?

Thank you in advance!

**Comment by xaizek** [comment]
Hello.

> As far as I understand in the latest versions of tmux image preview doesn't work.

Things like w3mimg or [Ueberzug](https://github.com/seebye/ueberzug) should work (w3mimg depends on the terminal).

> What should I do to force catimg to work in vifm?

Try low resolution mode. High resolution probably tries to overwrite character with another one and inside a curses application this doesn't work.

**Comment by echuraev** [comment]
I'm working on Mac OS machine, so, I'm not able to use w3mimg or Ueberzug. This is why I'm trying to find another solutions. catimg works fine for terminal but it doesn't work for vifm.

Low resolution mode doesn't help me to solve this problem. The result you can see on the screenshot:
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/5525113/56474447-bc593600-6482-11e9-8051-19d5d2fe6bed.png">

**Comment by xaizek** [comment]
It's not because of resolution, but because it tries to use true color. `-t` switch prevents that, but the quality is even worse then. ([Related comment.](https://github.com/vifm/vifm/issues/404#issuecomment-466786602))

Also issue #299 was about images on OS X.

**Comment by echuraev** [comment]
@xaizek Thank you very much for your support. I understood about true colors and found that [termpix](https://github.com/hopey-dishwasher/termpix) is a better solution it could display images without using true color. And for a simple image it looks fine:
![image](https://user-images.githubusercontent.com/5525113/56484211-1257c900-64d7-11e9-87cc-b154ef0b7906.png)

But for more difficult it looks ugly: 
![image](https://user-images.githubusercontent.com/5525113/56484169-e1779400-64d6-11e9-92cf-e7af7e1910e5.png)

Yes I have read issue #299 and imgcat is working for me. But it doesn't work in tmux and sometimes it works really slow. So, I'm just trying to find another solution that should work in tmux > 2.3 (I'm using tmux 2.7).

So, looking on the results, I think that maybe it is not a good idea try to display image using 8-bit colors.

**Comment by xaizek** [comment]
I think original [imgcat script](https://iterm2.com/utilities/imgcat) does work in tmux. See there at the top (detection of tmux might need to be updated). That is, unless they broke something, but I don't think the pass-through escape sequence got removed.

**Comment by echuraev** [comment]
Yes, it works! Thank you very much! I just tried to work with imgcat from npm repository.
Original imgcat works well.

**Comment by echuraev** [comment]
Just the end of the story with image preview in tmux with imgcat. Original imgcat script worked for me but only for small image and only one time. For the second time it started to print garbage to the terminal. Tmux has some limitations on size of buffer: https://github.com/tmux/tmux/issues/1502#issuecomment-429710887
And I decided to disable image preview in tmux. For me preview works only when I run vifm outside of tmux.

**Comment by pmilosev** [comment]
I ran upon this ticket having experienced similar issues as OP.
For future reference the following worked for me on MacOS with default Terminal app:
- `$ brew install catimg`
- in vifmrc: `fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif catimg -w $((%pw * 2)) -ct -r 2 %c`

Initially (while still playing around with different catimg options) I had the rendering issue as in the original post here (even after running :restart), but closing vifm completely and re-opening it solved the issue once I had it configured as mentioned above.
