### ISSUE TITLE
dim inactive pane?

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm#429]
Is it possible to dim inactive pane? just like with [vim-diminactive](https://github.com/blueyed/vim-diminactive)

**Comment by xaizek** [comment]
No, but something like `OtherWin` highlighting group could probably be added to customize background for inactive panes.

**Comment by cevhyruz** [comment]
can I work on this? any pointers?

**Comment by xaizek** [comment]
Sure. I put my notes for this task [at the wiki](https://wiki.vifm.info/index.php/Adding_new_highlight_group). The use of the group would be similar to that of `OTHER_LINE_COLOR` and should all be in `src/ui/fileview.c`. The uses of `WIN_COLOR` there need to have new group mixed in as is done with `OTHER_LINE_COLOR`:
```c
	if(cs_is_color_set(&cs->color[OTHER_LINE_COLOR]))
	{
		cs_mix_colors(&col, &cs->color[OTHER_LINE_COLOR]);
	}
```
