### ISSUE TITLE
fileviewer wont work for files with js extension

### ISSUE THREAD

**Issue by flux242** [vifm/vifm#430]
vifm 0.9.1

in my first attempt to colorize some files types in preview I have defined this in my vifmrc:
```
fileviewer *.[ch],*.[ch]pp,*.md,*.js,
           \Makefile,Makefile.*,*.patch,
           \*.html,*.htm,*.css,
           \ highlight -O xterm256 -s olive %c
```
strangely, it works for all defined file types except for 'js'. I've figured out that highlight won't be called at all for js files. Please let me know what did I do wrong

**Comment by xaizek** [comment]
If other files get highlighting, js-files should get it too. You can change the command to
```
fileviewer *.[ch],*.[ch]pp,*.md,*.js,
           \Makefile,Makefile.*,*.patch,
           \*.html,*.htm,*.css,
           \ echo %c; highlight -O xterm256 -s olive %c
```
And see if file name appears at the top for js-files. It could be that `highlight` doesn't highlight it for some reason.

> I've figured out that highlight won't be called at all for js files.

How did you check this? I see js-files highlighted in 0.9.1 with your command.

**Comment by flux242** [comment]
with this
```
$ cat bin/highlight.sh 
#!/bin/bash

echo $@
highlight $@
```
and by changing the call string in the vifmrc. So, no arguments are printed by echo

**Comment by flux242** [comment]
oh, it doesn't work for js files starting with dot

**Comment by flux242** [comment]
could it be that in this case extension is not properly detected? Ex: .test.js - the extension should be detected as js and not test.js

**Comment by xaizek** [comment]
Globs don't match hidden files unless it's explicit. From the [docs](https://vifm.info/vimdoc.shtml#vifm-globs):

    * means any number of any characters (possibly an empty substring), with one
    exception: asterisk at the pattern beginning doesn't match dot in the first
    position.

Shell patterns work the same by default as required by [POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_13_03):

    If a filename begins with a period ( '.' ), the period shall be explicitly matched by using
    a period as the first character of the pattern or immediately following a slash character.
    The leading period shall not be matched by:

        * The asterisk or question-mark special characters

You just need to explicitly specify `.*.js` pattern. If hidden code files are a common thing for you, using regular expressions (`fileviewer /\.([ch](pp)?|md|js)$/ ...`) could reduce duplication at the cost of readability.

**Comment by flux242** [comment]
ah, good to know, thanks
