### ISSUE TITLE
Mount AppImage as a squashfs archive with an offset

### ISSUE THREAD

**Issue by flux242** [vifm/vifm#431]
would it be possible to fuse mount an AppImage with vifm? An AppImage can be mounted this way:
```
squashfuse -o offset=$(filename.AppImage --appimage-offset) filename.AppImage mountpoint
```
so, an equivalent of the bash's  parameter substitution would be needed, because the offset is not known and cannot be hard coded into vifmrc

**Comment by flux242** [comment]
well, ok, a small wrapper script does the trick

**Comment by xaizek** [comment]
This seems to work for me (although there is inconvenience of having to use `:file` to enter the file):
```
" AppImage
filetype *.AppImage
       \ {Mount with squashfuse}
       \ FUSE_MOUNT|squashfuse -o offset=$(%SOURCE_FILE --appimage-offset) %SOURCE_FILE %DESTINATION_DIR
```

**Comment by xaizek** [comment]
I assume this is resolved.
