### ISSUE TITLE
Per-directory sort option

### ISSUE THREAD

**Issue by Waces** [vifm/vifm#434]
Probably just me missing stuff that was written on the man page, I don't know

Anyway, as someone that used Dolphin mostly, I'm used to being able to set sorting options per folder (so for example, ~ would be organized alphabetically while /downloads and /pictures would automatically be sorted by modification time) so wanted to know if I can do this with some configuration or script here

**Comment by cdlscpmv** [comment]
Thank you for bringing this up! I've just added similar lines to my config file as well:
```
autocmd DirEnter * set sort=+name
autocmd DirEnter ~/downloads set sort=-mtime
```
You can customize it whatever you want. To get more information read the `:autocmd` part of the man page.

**Comment by xaizek** [comment]
Similar question was asked recently on [vifm's Q&A site](https://q2a.vifm.info/469/can-i-specify-sorting-per-directory). The answer is to use [:autocmd](https://vifm.info/vimdoc.shtml#vifm-%3Aautocmd) with [:setlocal](https://vifm.info/vimdoc.shtml#vifm-%3Asetlocal):

```vim
autocmd DirEnter ~/downloads,~/pictures setlocal sort=-mtime
```

**Comment by Waces** [comment]
Oh thanks, then sorry for the duplicate :P
