### ISSUE TITLE
Increase performance of status line

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#436]
Hi!

I'm having a great time with vifm, thanks for your work!

I have customized vifm's status line to include a file's [extended attributes](https://en.wikipedia.org/wiki/Chattr) or — if it's a directory — the number of files inside the directory:

![status line screenshot for file](https://i.imgur.com/wVdfWPI.png)

Here's the config from `vifmrc`:

    highlight User1 ctermbg=none ctermfg=none cterm=none
    highlight User2 ctermbg=none ctermfg=none cterm=reverse
    set statusline="%1*%A %2* %u:%g %1* %10E %2* 👉 %d %1* %{system('~/.config/vifm/file_info.sh ' . expand('%c'))}%=💽 %a"

This is `~/.config/vifm/file_info.sh`:

    #!/bin/bash

    # Take care of symbolic links
    cur_file=$(realpath "$1")

    if [ -f "$cur_file" ]; then
      file_length=${#cur_file}
      file_name_with_attributes=$(lsattr -l "$cur_file")
      # Remove the file name that precedes the attributes
      attrs=${file_name_with_attributes:$file_length}
      # Remove leading whitespace. From here:
      # https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable#3352015
      attrs="${attrs#"${attrs%%[![:space:]]*}"}"

      echo "$attrs"

    elif [ -d "$cur_file" ]; then
      number_of_files_in_dir=$(ls -A -1 "$cur_file" | wc -l)
      echo "$number_of_files_in_dir"
    fi

The issue is that this status line slows vifm down. When I browse through files with vifm by holding down `j`, for example, I can see that this creates lag: When I release the key, vifm's cursor moves one or two files below the file where I released the key.

I'm wondering how to speed things up while still displaying the extended attributes and the directory's file count. My first idea was to only update the status line when the user has released the key, but I don't know if that's possible with the current implementation of vifm.

I'd be glad to hear your thoughts on this.

**Comment by xaizek** [comment]
Hello!

> ~/.config/vifm/file_info.sh

You should be able to put `file_info.sh` to `~/.config/vifm/scripts` and just use `file_info.sh` instead of full path.

> My first idea was to only update the status line when the user has released the key, but I don't know if that's possible with the current implementation of vifm.

Terminal handles input and I don't think there is a way to catch key release event.

The solution seems to require an in-process cache, which could have something like the following interface:
```vim
" extcache(path, external_cmd)
" caches output of external_cmd per path
" (invokes external_cmd only if file modification is detected)
extcache(expand('%c'), 'file_info.sh ' . expand('%c'))
```
Caching inside the script is also possible, but might not significantly improve the performance as running external script is relatively slow.

**Comment by xaizek** [comment]
This seems to work faster, especially once the result is cached:
```vim
set statusline="%1*%A %2* %u:%g %1* %10E %2* 👉 %d %1* %{extcached('file_info', expand('%c'), 'file_info.sh ' . expand('%c'))}%=💽 %a"
```
