### ISSUE TITLE
How to get the syntax highlight in preview window

### ISSUE THREAD

**Issue by taigacute** [vifm/vifm#437]
how to get the go python html css etc. file highlight in preview window. maybe need highlight bat etc plugins? dot know how to set. help.

**Comment by xaizek** [comment]
If you have [highlight](http://www.andre-simon.de/doku/highlight/en/highlight.php) installed, you can add something like this to your `vifmrc`:
```
fileviewer *.html,*.go,*.css highlight -O xterm256 -s dante %c
```
Modify list of patterns as suits you and change the command to invoke highlighter you prefer.

**Comment by taigacute** [comment]
works! thanks bro

**Comment by taigacute** [comment]
@xaizek  another question. how can i use iterm2 to preview image?

**Comment by xaizek** [comment]
See #299.
