### ISSUE TITLE
vifm-media for Mac OSX?

### ISSUE THREAD

**Issue by von** [vifm/vifm#438]
Looks like [vifm-media](https://github.com/vifm/vifm/blob/master/data/vifm-media) doesn't support OSX currently. Before I jump in, anyone already working on this?

To the maintainers: assuming I do this, would you want this added as another if/then block to the current script, or do you mind if I make it a separate python script? Similar to the recently added support for `udisksctl`, python (with its good regex support) is my desired implementation.

TIA

**Comment by xaizek** [comment]
> Looks like vifm-media doesn't support OSX currently.

That's correct. I don't think udevil/udisks/udisks2 are available on OS X.

> Before I jump in, anyone already working on this?

I'm not aware of anyone trying to do it.

> do you mind if I make it a separate python script?

Having it as `vifm-media-osx` would be fine. Then `'mediaprg'` could point at it on OS X by default.

**Comment by von** [comment]
Initial stab: https://gist.github.com/von/edc512df2faeca050c2cc359c3d48ade

I'll use it for a while to shake the bugs out.

**Comment by xaizek** [comment]
Three weeks have passed, do you think it's ready for a pull request?

Also, why did you write
```python
    try:
        print("label=" + node["VolumeName"])
    except KeyError:
        pass
    try:
        print("mount-point=" + node["MountPoint"])
    except KeyError:
        # Unmounted disk
        pass
```
instead of this?
```python
    if "VolumeName" in node:
        print("label=" + node["VolumeName"])
    if "MountPoint" in node:
        print("mount-point=" + node["MountPoint"])
```

**Comment by von** [comment]
Yes, it seems to be working for me. I'll put in a pull request this weekend.

Regarding if/in versus try/except, just stylistic. Let me know what you prefer.

**Comment by xaizek** [comment]
> Regarding if/in versus try/except, just stylistic. Let me know what you prefer.

I don't have a strong opinion about that and was just wondering.

**Comment by von** [comment]
@xaizek: I'm looking at doing a PR and it appears the script should go into data/subdir, and get added to dist_pkgdata_SCRIPTS in src/Makefile.am. Presumably I should then run automake to regenerate Makefile.in as it looks like you have that file in the repo as well?

If so, it's been a while since I've used automake and autoconf, and I'm not set up for it. I tried installing automake via homebrew just to see if it would be easy, and homebrew installs a latter version than what you are apparently using (1.16.1 vs 1.15) and it errors out with a version mismatch when I try to use it.

So doing a full PR correctly is apparently going to take me non-trivial effort for me to get automake working. Do you mind if I just do a simple PR with the script and ask you to handle the needed changes under src/?

**Comment by xaizek** [comment]
Sure, just provide `data/vifm-media-osx` in the pull request, I'll add whatever else is necessary.
