### ISSUE TITLE
where is key for creating file/dir/link?

### ISSUE THREAD

**Issue by icyhat** [vifm/vifm#447]
As a `file manager` with modal mechanism like vi, basically about `file`, we have `CRUD`, firstly

1. create
    1. file
    2. directory
    3. link

what are the key bindings?
I tried every key from a-z A-Z every symbol, and nothing seem to be `create`, I checked cheatsheet on official site, also nothing found, I searched doc on official site, nothing found..

**Comment by aleksejrs** [comment]
1. Search the man page for "creat.*director". You'll find "`mkdir`".
2. Search the example vifmrc file for "map". You'll find "`nnoremap`" (mappings for normal mode).
3. Run "`:nnoremap`" in vifm. You'll get a list of all mappings.
4. Search (`/`) the list for "`mkdir`".
5. Search the list for "link".
6. Which way of creating a file are you talking about? There is a `:e filename` to start an editor on a file.

**Comment by xaizek** [comment]
Creating empty files or directories isn't very common operation compared to navigation or moving files and creating a link needs a target file, so there are no builtin shortcuts for that. Here are related commands:

* for files: [`:touch`](https://vifm.info/vimdoc.shtml#vifm-%3Atouch)
* for directories: [`:mkdir`](https://vifm.info/vimdoc.shtml#vifm-%3Amkdir)
* for links: [`:alink`](https://vifm.info/vimdoc.shtml#vifm-%3Aalink), [`:rlink`](https://vifm.info/vimdoc.shtml#vifm-%3Arlink), [<kbd>al</kbd>](https://vifm.info/vimdoc.shtml#vifm-al), [<kbd>rl</kbd>](https://vifm.info/vimdoc.shtml#vifm-rl)

And if you want to shorten something, you can always create mappings as @aleksejrs suggests. If you open `vifmrc`, there is an example one for `:mkdir`:
```vim
nnoremap <f7> :mkdir<space>
```

**Comment by xaizek** [comment]
I assume this is resolved.

**Comment by icyhat** [comment]
Thanks for your detail help.

I use `vifm` for a `net model` wiki based on directories, link and files. Traditional `tree model`, notes or mindmap will cause too much same keywords in different branches to maintain.That's why I wanna use `vi like` file manager with fast `CRUD` operations on directories and symbolic links to build a `net model` database and fill in all my notes and files with well structured and low redundant advantages.

Is there any better solution ?

**Comment by xaizek** [comment]
If you want to squeeze up maximum out of graph representation, you probably need to look at specialized tools.  I remember there was a notes application, which was representing them as a graph, but I couldn't find it later. It was either on https://inconsolation.wordpress.com/ or at the second site where author reviewed console tools every day or week. Probably it was on the second one, because I searched inconsolation several times. The problem is that I forgot how that second site is called...

**Comment by icyhat** [comment]
hahaha, thx..
