### ISSUE TITLE
Set window title

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#457]
Hi!

I'd like to change the title of the window vifm's running in.

Vim offers the `title` and `titlestring` options for that. I use them in my `vimrc` to set the window title to the name of the current file:

    set title
    " Change the title when switching or renaming buffers
    augroup WindowTitleGroup
      autocmd!
      autocmd BufEnter,BufFilePost * let &titlestring = expand('%:t')
    augroup end

Is there something similar in vifm? Ideally I could change the window title each time I change directory.

Thanks!

**Comment by xaizek** [comment]
Hi!

There is [`'title'` option](https://vifm.info/vimdoc.shtml#vifm-%27title%27), but no `'titlestring'`. If you wanted to display current directory, that's what is printed there.

**Comment by mb720** [comment]
Thanks for your quick response!

Adding `set title` to my vifmrc doesn't have an effect on the window title when I start vifm or change a directory: The title remains the directory from which I launched vifm.

I'm using i3 as my window manager and termite for my terminal emulator.

Please let me know how to debug this, thanks!

---

I have this in my `~/.bashrc` to set the window title to the current directory after each command:


    # After each command finishes, we set the terminal window title to the
    # current working directory. If, for example, Vim sets the window title
    # to the file's name and we exit Vim, the window title becomes the
    # current directory again.
    # There has to be a space between $(pwd) and \007 so the sequence is ended properly,
    # otherwise the window title would only be changed sometimes.
    # These escape sequences are documented in man 4 console_codes.
    # \033 is octal for ESC in ASCII, \007 is BEL
    PROMPT_COMMAND="$PROMPT_COMMAND;echo -ne \"\033]0;\$(pwd) \007\""

This has worked fine in combination with Vim, Mutt, `cd`, and other programs.

I suspected that it might interfere with vifm somehow, so I removed the line, sourced `~/.bashrc`, and restarted vifm. But it still behaves the same with regard to the window title.

**Comment by xaizek** [comment]
There is a list of `$TERM` values for which terminal title is known to be supported, I suspect that your `$TERM` just isn't one of these:
```
"xterm", "xterm-256color", "rxvt", "rxvt-256color", "rxvt-unicode", "aterm", "Eterm"
```

**Comment by mb720** [comment]
Indeed, it's `xterm-termite` :-)

Is this something I can add to vifm?

**Comment by xaizek** [comment]
It's hardcoded in source and isn't configurable, that is unless you want to make a patch. I guess everything that starts with `xterm-` and `rxvt-` should have support for setting title.

**Comment by mb720** [comment]
Thanks for implementing this! I'm using vifm 0.10.1 with termite and it works great.
