### ISSUE TITLE
Tarballs on GitHub

### ISSUE THREAD

**Issue by jubalh** [vifm/vifm#459]
Hello!
0.10 had several tarballs uploaded to GitHub. 0.10.1 only the GH autogenerated once. And it seems the only way to download the other tarballs now is from Sourceforge.

Just wanted to open this issue to see if this is intended or was forgotten.

**Comment by xaizek** [comment]
Hi!

Thanks for noticing, they were "uploaded", but then didn't appear. GH doesn't play nice with extensions like RequestPolicy. Updated the release.
