### ISSUE TITLE
Dont install osx specific files in all cases

### ISSUE THREAD

**Issue by jubalh** [vifm/vifm#460]
Maybe it would make sense to not install `vifm-media-osx` and `vifmrc-osx` on non OS X machines.
Is there a way to change the Makefile accordingly?
For now I patched it out of the openSUSE package.

**Comment by xaizek** [comment]
> Maybe it would make sense to not install `vifm-media-osx` and `vifmrc-osx` on non OS X machines.

It never bothered me, but if it's not really useful, they can be removed.

> Is there a way to change the Makefile accordingly?

Yes, but it requires changing `configure.ac` as well to do it properly (basically define a variable like `@DATA_VERSION@` that would be empty everywhere, but on OS X).

**Comment by jubalh** [comment]
So for now I just remove the files so they dont get installed in the rpm.
It's not a big deal I can leave it like this. Just thought I'll open this issue in case it's a thing that could generally be nicer for others as well. Though the few bytes probably won't hurt anybody :-)

**Comment by onovy** [comment]
I had same problem and used same solution: Removed that file from Debian package.
