### ISSUE TITLE
Additional fields support for colorschemes

### ISSUE THREAD

**Issue by AntonGepting** [vifm/vifm#461]
Hello,

first of all I would like to thank you and all contributors for creating this promising file manager for the fans of the vim-like-techniques.

My proposal is to **add some more fields to the colorschemes** supporting mechanisms, to make it possible to set up color not only of the entire file line, but for other file parameters selectively:
- Line number
- File / Directory Name
- Extension
- Size
- Owner
- Group
- Attributes
- Timestamp
- ...

**Motivation:**
Allow more customization in the user's coloroschemes and improve the readability of the long file lists.

Of course it's not so important as other improvements at the moment, but I posted it anyway to save it somewhere as a possible bullet for the future releases. Thank you, I hope this isn't a duplicate of some other issue. 

**Examples:**

Current state:
![current](https://user-images.githubusercontent.com/43881729/62281742-9c0c2080-b44e-11e9-9cbd-4b16675a2e70.png)

I would prefer something like this:
![suggestion](https://user-images.githubusercontent.com/43881729/62281758-a4fcf200-b44e-11e9-8625-0513a935451a.png)

**Comment by XVilka** [comment]
I think https://github.com/vifm/vifm/issues/453 should be implemented first, so adding new fields would be way easier.

**Comment by xaizek** [comment]
Hello,

> first of all I would like to thank you and all contributors for creating this promising file manager for the fans of the vim-like-techniques.

Credit for the actual creation goes to @ksteen :) I was also very grateful to him upon discovering vifm, and still am today.

> I hope this isn't a duplicate of some other issue.

No, but this was essentially requested before, so you're not the only one who wants this.

https://github.com/vifm/vifm/blob/224df4b048acd7c1ca10a7022b198f7a0a66be3c/TODO#L107

***

Initially I incorrectly thought that you would like to take #289 to another level and colorize files according to arbitrary expressions, but you primarily want to set color per column.

@XVilka, maybe you made the same mistake? I don't really see that #453 would make a difference here. Column names would still be in a separate "namespace" from files.

**Comment by AntonGepting** [comment]
> Credit for the actual creation goes to @ksteen :)

surely I was meaning every participant, who was involved in development, creating in a broad sense.

> but you primarily want to set color per column

I think you got it right. I was adjusting few colors in my colorscheme, and thought it would be nice to have the possibility to make unimportant information about a file a little bit darker. Something like "opacity" for the line fragments. On the one hand it vanishes not completely so user can still perceive this information and on the other the list is getting cleaner and is not overfilled. But I understand now, this brings it to some kind of collision, if files were already colored using expressions depending on their extension, creation time etc... and uh "opacity" in the terminal... Anyway that was just an idea.

The settings can be used in colorschemes like:
```
" my_colorscheme.vifm
...
highlight Directory cterm=none ctermfg=yellow ctermbg=default
highlight Link cterm=none ctermfg=blue ctermbg=default
"highlight LineNumber ...
"highlight FileAttributes ...
...
```

**Comment by xaizek** [comment]
> this brings it to some kind of collision, if files were already colored using expressions depending on their extension

Not really, existing file highlighting rules affect only file name column for items that aren't under cursor and aren't selected. And highlighting is already organized into a hierarchy to make it well defined. New rules would just be placed at some level in that hierarchy and everything should work fine.

**Comment by XVilka** [comment]
@xaizek yes, you are right, it is unrelated. Sorry for the noise.
