### ISSUE TITLE
"gf" can break on relative symlinks (because of non-canonicalized $PWD ?)

### ISSUE THREAD

**Issue by emarsk** [vifm/vifm#463]
It appears that `gf` doesn't canonicalize the current working path before resolving the target symlink.

An example is probably better than my poor attempt at an explanation. Let's say I have this structure:
```
~/
├── A/
│   ├── B/
│   │   └──c -> ../C
│   └── C/
└── b -> A/B
```
If, within vifm, I enter into `~/b/`, I am "really" in `~/A/B/`, therefore `c`, which points to `../C`, is actually pointing to `~/A/C`, but if I use `gf` on `c`, it incorrectly brings me to `~/` instead of `~/A/`; in other words, it resolves the `../` part of the symlink as if relative to `~/b/` instead of `~/A/B/` (and of course there's no `C` there).

As far as I can tell, only `gf` is broken: entering a symlinked directory, editing a symlinked file, and the preview pane all work as expected.

**Comment by xaizek** [comment]
Thank you for the report and a very nice explanation. Your guess about missing resolution of symbolic links in path to the link is correct.
