### ISSUE TITLE
:move path fails in background

### ISSUE THREAD

**Issue by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [vifm/vifm#465]
":move path" will correctly move files to a relative subdirectory in the opposite panel. Attempting to do so in the background (:move path &) will rename the file to "path/path". Attempting to move multiple files in the background will fail and create "path/(null)".

Debian 10, ext4 filesystems, and running with --no-configs, if relevant.

Version: 0.10.1
Git info: built out of repository
Compiled at: Aug 14 2019 20:25:21

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution

**Comment by xaizek** [comment]
Thank you for the report. Second issue manifests somewhat differently for me, but that just what memory handling bugs tend to do.
