### ISSUE TITLE
Can't select files in user commands and then grab them with %f macro

### ISSUE THREAD

**Issue by gcmt** [vifm/vifm#466]
I've been trying to use fzf to quickly filter files in the current directory [[script here](https://github.com/gcmt/dotfiles/blob/master/vifm/scripts/vifm-fzf-filter)]. As I needed to pass the files in the current view to the fzf script, the most intuitive solution I could come up with is the following:

    command! ff :1,$select | execute term('vifm-fzf-filter %f')

The problem is that the `%f` macro is not expanded as expected and always expands to the current selected file unless I use the command with a range: `%ff`. A workaround would be to simply create a mapping such as 

    nnoremap f :%ff<cr>

but needing to create a mapping for all such commands would be a little annoying.

The strange thing is that calling the same program (using `expand('%f')`) from the command line works as expected.  Built-in commands seem to also be able to grab the selection just fine: `command! delfoo :select *.foo | delete`.

**Comment by xaizek** [comment]
Try:
```vim
command! ff :%%select | execute term('vifm-fzf-filter %%f')
```
Macros are always expanded in the right-hand side of user-defined commands and thus other uses of `%` (including macros whose expansion should be delayed) need to be escaped by doubling it. It looks like this isn't really clear from the documentation.

**Comment by gcmt** [comment]
Thanks for the tip! I managed to make it work:

```vim
command! ff :%%select | !vifm-fzf-filter %%f
```

It wasn't very clear I had to escape the macro too. Unfortunately, by using `execute term('vifm-fzf-filter %%f')`  the macro doesn't get expanded at all and the string `%f` simply gets passed as argument.

**Comment by xaizek** [comment]
You can use [`expand()`](https://vifm.info/vimdoc.shtml#vifm-expand%28%29):
```vim
command! ff :%%select | execute term(expand('vifm-fzf-filter %%f'))
```

**Comment by gcmt** [comment]
It works! Thanks again!
