### ISSUE TITLE
Version 0.10.1 doesn't work on Windows 10

### ISSUE THREAD

**Issue by nandox** [vifm/vifm#469]
I downloaded both the vifm-w64-se-0.10.1-binary.zip and vifm-w32-se-0.10.1-binary.zip, installed them in folders and tested them with the same result: there is a message about lack of permissions and then the vifm.exe file gets deleted. I tried to run it using admin permissions, and it didn't work. Version 0.10 works fine.

**Comment by xaizek** [comment]
Tested it only now, I don't see anything like that. File being deleted suggests that some kind of antivirus software might be doing it. It happened before due to use of sockets for implementation of IPC (changed since then), but I'm not sure what could cause it for 0.10.1.

**Comment by nandox** [comment]
You were right, it was the Panda Dome antivirus I have in my computer. I disabled it and I was able to use version 0.10.1. I don't understand why this antivirus didn't have problems with version 0.10 though. After I ran the app I enabled again the antivirus and it didn't complain anymore about version 0.10.1

Thanks again for this great app and your great support.

**Comment by xaizek** [comment]
VirusTotal didn't show any hits (Panda antivirus is present there):

* [`vifm.exe` from `vifm-w32-0.10.1-binary.zip`][win32]
* [`vifm.exe` from `vifm-w32-se-0.10.1-binary.zip`][se32]
* [`vifm.exe` from `vifm-w64-se-0.10.1-binary.zip`][se64]

I guess some heuristics caused this false positive (being downloaded from the Internet and not being signed can be one of them). If Panda uses Windows origin tracking (via alternative file streams), then maybe you used different browser or archive manager to extract the zip-file compared to 0.10, which this time preserved the origin metadata.

[se64]: https://www.virustotal.com/gui/file/417a1892fc53dd9057c4adfa21946c087a25e3b43da267437954d07ee29debf2/detection
[se32]: https://www.virustotal.com/gui/file/504a1debc752db5742f4fb45e10c3abc22bbdd37ce37341115881eaaaacc09ef/detection
[win32]: https://www.virustotal.com/gui/file/34e7d10bc9d055cc688a93c8ee9ded72e3846c2a27a0ba271436becb579997a6/detection
