### ISSUE TITLE
request for new macro and/or event

### ISSUE THREAD

**Issue by ratnamhof** [vifm/vifm#470]
Subject: Feature request (not an issue report)

Firstly, let me thank you on my hands-and-knees for this software: Vifm is awesome and I cannot see myself use any other filemanager software on linux ever again (I'm using v0.9.1 on ubuntu18.04).

However ...

There is a small thing that could be improved in my opinion, related to the limited persistence of restoring selections with the command 'gs'. I find myself making selections and accidentally pressing h/left going to the parent directory or pressing l/right launching the selections. When correcting my mistake by going back into the child directory or by closing all launched application I cannot restore the selection with 'gs' any more as it was wiped from memory. Trying to create my own workaround for selection-restore-with-persistence (for the previous N folders) I've come across some features that prevent straightforward implementation. Two opportunities that could improve vifm functionality in this respect in my opinion are:

1) Extended macro behaviour:

Trying to map new keys to ":select! !my_selection_script(%d,%c,%f)" uses macros with behaviour:
* %c = item under cursor
* %f = all selected items or item under cursor in case that there are no other selections
I would think that a useful extension is:
* %\<something> = all selected items or empty in case that there are no other selections

With the current implementation the situations of "no item selected" and "one item selected and cursor at location of selected item" cannot be distinguished. With the additional macro it can.

2) Extended event behaviour:

Currently I believe that there is only one event that one can assign to: 'DirEnter'. It seems very useful to have a 'SelectionChanged' event that triggers every time that the selection is changed, either in normal mode with 't', visual mode and/or command line mode with ":select".

For clarity: Vifm is great! The features above may make it a little bit greater.

**Comment by xaizek** [comment]
> %<something> = all selected items or empty in case that there are no other selections

That could be useful. When I needed to check for selection I did `expand('%c') == expand('%f')`, which has the drawback that single file selection can't be distinguished from no selection.

> 'SelectionChanged' event

You'll end up saving selection on every change, which seems to be excessive, but would do the job.

Given that the situation seems to be that you select files on purpose and do something you didn't intend, have you considered strategy of doing nothing on <kbd>h</kbd> and <kbd>l</kbd> when there is a selection? It seems better in that you don't have to undo the action, but it might not fit your workflow if you often select files to run them.

**Comment by ratnamhof** [comment]
Hi xaizek,

Thank you for your reply and suggestion! I really appreciate your feedback!

I am not entirely certain about what you mean with "doing nothing on `h` and `l` when there is a selection"? Do you mean to remap `h`/`l` to something else when a selection is present? I didn't know that was possible ... How could I implement that?

BTW, just for completeness I would like to add that I have no problems with the default behaviour of `h` and/or `l`: the workaround that I'm referring to in the original message is not a workaround for vifm behaviour, but for my own clumsiness.

This would be an exemplary situation: In a folder with large amount of items (e.g. holiday pictures on camera micro SD) I would go through an arduous process of selecting the files I want to backup, and then at some point (by finger misalignment or involuntary finger movement or so) accidentally press an incorrect key that disables the selection (e.g. by going to the parent directory). In those cases I get upset with myself, but looking forward to restoring the selection with `gs` I find it is not possible due to the nature of my mistake.

These mappings are a sufficiently good workaround for me:
```
nnoremap x :select! ! /usr/local/lib/vifmStoreSelection.py %d %f<CR>
nnoremap <m-x> :select! ! /usr/local/lib/vifmStoreSelection.py %d %f<CR>j
nnoremap gx :select! ! /usr/local/lib/vifmStoreSelection.py restore %d<CR>
```
where vifmStoreSelection.py is a simple python script that saves (and outputs) the current selection in a file in the ~/.cache directory for the last N directories where a selection was made, or outputs the previously stored selection if the first argument is the string 'restore'. With the proposed macro I could also get toggling of a single file (with nothing else selected) to work (using additional input `%c`). With the OnSelectionChanged event I could bind the script to that instead to also store selections that are made in visual mode (or some other :select command).

The mappings above with a python script are ugly and hacky, but sufficiently usable for me. Therefore, the feature request is actually not even a request, but just a low-priority proposal. Please feel free to ignore the proposal if it is a high-effort implementation or if you fear excessive behaviour as with the event.

**Comment by xaizek** [comment]
Hello,

> Do you mean to remap h/l to something else when a selection is present? I didn't know that was possible ...

Yes, exactly. You can try this (not very pretty and uses that expansion "trick", but does the job):
```vim
nnoremap h : if expand('%c') == expand('%f')
          \|     let $CMD = 'normal! h'
          \| else
          \|     let $CMD = 'normal! gs'
          \| endif
          \| execute $CMD<cr>
nnoremap l : if expand('%c') == expand('%f')
          \|     let $CMD = 'normal! l'
          \| else
          \|     let $CMD = 'normal! gs'
          \| endif
          \| execute $CMD<cr>
```

**Comment by ratnamhof** [comment]
Cool! That's pretty awesome! I've learned something new today! A switching command ... neat little trick! I can see myself using this. Thanks for the tip!

**Comment by mb720** [comment]
I too have this issue of losing selections sometimes (and share the sentiment about Vifm being great^^).

I can see this improved two different ways:

  1. Give `gs` a memory so it remains useful after leaving the current directory, like you discussed.
  2. Selections are automatically restored when returning to a directory. This way, we don't have to use `gs` at all when returning to the original directory.

**Comment by xaizek** [comment]
> Selections are automatically restored when returning to a directory.

This is likely to cause more trouble than to solve. If you intentionally leave the directory without clearing selection, next time you enter it, selection won't be empty, but you might not notice it. And since many commands behave differently when selection exists, weird things will happen.

> Give `gs` a memory

This is better. For N (say, 5-10) last directories as you probably will never return farther than several previous locations to restore selection anyway.

**Comment by savchenko** [comment]
> For N (say, 5-10) last directories as you probably will never return farther than several previous locations to restore selection anyway.

FWIW, <kbd>gs</kbd> doesn't seem to restore selection after the directory change in v0.10.1.

Steps to reproduce:
1. Select some files with <kbd>t</kbd>
2. Change the directory
3. Press <kbd>Tab</kbd> to go back (aka <kbd>Ctrl</kbd>+<kbd>i</kbd>)
4. Press <kbd>gs</kbd>
5. Nothing happens

**Comment by xaizek** [comment]
> FWIW, <kbd>gs</kbd> doesn't seem to restore selection after the directory change in v0.10.1.

Because it wasn't implemented.

**Comment by xaizek** [comment]
Made <kbd>gs</kbd> remember 10 last directories and added new macros for selection (`%l`, `%L`), because they are useful for other purposes.
