### ISSUE TITLE
Tabline should be able to show both the tab name and the current path

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#473]
Before using `:tabname`, any tabline shows the `%d` (path of the current file list), which is updated when switching between lists. After using `:tabname`, it only shows the tab name. But `:tabname` does not seem to support macros, so the tab line becomes less useful, in a way.

Debian stable, Vifm
```
Version: 0.10
Git info: built out of repository
```

**Comment by xaizek** [comment]
> `:tabname` does not seem to support macros

I was thinking about adding an option to define format of the tip of a tab one day. Allowing macros is an alternative, but I guess one would generally prefer to configure this once in `vifmrc` and to not have to define a custom command to do that.
