### ISSUE TITLE
bug: bookmarks can not be saved

### ISSUE THREAD

**Issue by stephencheng** [vifm/vifm#474]
I have attempted a few ways to try to save bookmarks, but none worked. Every time if vifm is restarted, the added bookmarks are gone.

```
Version: 0.10

Git info: built out of repository
Compiled at: Jul 27 2019 23:44:52

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

What I have tried:

1. save before quit by using :w
2. use: set vifminfo=bookmarks,chistory,shistory,phistory,dirstack,registers and remove this line

I did compare for each test before quitting vifm, and there is no bookmars saved to vifminfo file

I also tested the marks, they can be saved and there are saved data in vifminfo file

Also tested the latest release, it is not working

```
Version: 0.10.1
Git info: built out of repository
Compiled at: Aug  1 2019 13:13:13

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
From ['vifminfo' docs](https://vifm.info/vimdoc.shtml#vifm-%27vifminfo%27):

     bmarks    - named bookmarks
     bookmarks - marks

"bookmarks" was already there when `:bmark` was added, hence the ambiguity.

Just adding "bmarks" as one of values of `'vifminfo'` should make it work.

**Comment by stephencheng** [comment]
cool, that resolves the problem. I have spent so much time on this.

Thanks so much
