### ISSUE TITLE
setting: disable Space Bar as toggles between the two file list

### ISSUE THREAD

**Issue by stephencheng** [vifm/vifm#475]
Basically I'd like to use space bar as Leader key same as I do in vim, but not sure how this is possible.

Is there any setting for this?

Thanks

**Comment by xaizek** [comment]
You  can't get rid of it completely, but it can be mapped to do nothing via

```vim
nnoremap <space> <nop>
```

Then map other things:
```vim
nnoremap <space>a a
nnoremap <space>b b
```

Alternatively, do:
```vim
nnoremap <wait> <space>a a
nnoremap <wait> <space>b b
```

But in this case if you press wrong key after space, panes will be switched and
then that key is executed.

**Comment by stephencheng** [comment]
Thanks, nop is exactly what I need.

BTW, I have been using vifm years. It's a great software I can't live without it. Thanks
