### ISSUE TITLE
Mounted HDD filesystem files do not obey filextype conditions

### ISSUE THREAD

**Issue by marcosrdac** [vifm/vifm#478]
I recently bought an SSD and put Arch and vifm into it. The later is working very well (your software is just amazing!) for the files inside the SSD. I am also using my HDD for big non-essential files (books, music, etc.). When I try to open, say, a PDF or a video from the HDD, vifm shows me these errors, respectively:

File type: PDF --> usually goes to zathura, in SSD.
```
/home/marcosrdac/tmp/los_201909.pdf: line 1: fg: no job control
/home/marcosrdac/tmp/los_201909.pdf: line 2: fg: no job control
/home/marcosrdac/tmp/los_201909.pdf: line 3: 1558: command not found
/home/marcosrdac/tmp/los_201909.pdf: line 52832: warning: here-document at line 4 delimited by end-of-file (wanted `/Linearized')
/home/marcosrdac/tmp/los_201909.pdf: line 52832: syntax error near unexpected token `newline'
/home/marcosrdac/tmp/los_201909.pdf: line 52832: `<< /Linearized 1 /L 12581650 /H [ 3206 594 ] /O 1562 /E 2908947 /N 62 /T 12572029 >>'
```

In my vifmrc I have:

```
filextype  *.pdf zathura %c %i &, apvlv %c, xpdf %c
```

File type: mkv --> usually goes to mpv, on SSD.

```
/bin/bash: /home/marcosrdac/series/twin_peaks/TPS01E01.mkv: cannot execute binary file: Exec
format error
```

In my vifmrc I have:

```
filextype *.avi,*.mp4,*.wmv,*.dat,*.3gp,*.ogv,*.mkv,*.mpg,*.mpeg,*.vob,
         \*.fl[icv],*.m2v,*.mov,*.webm,*.ts,*.mts,*.m4v,*.r[am],*.qt,*.divx,
         \*.as[fx]
        \ {View using mpv}
        \ mpv -- %f
        \ {View using ffplay}
        \ ffplay -fs -autoexit %f,
        \ {View using Dragon}
        \ dragon %f:p,
        \ {View using mplayer}
        \ mplayer %f,
```

(Sorry, looks like the text formating is not being well shown when I comment...)
I really don't have a clue about what could be going wrong :c. Do you?

**Comment by xaizek** [comment]
> (Sorry, looks like the text formating is not being well shown when I comment...)

Use triple back-quotes, like this:

    ```
    your text
    ```

> I really don't have a clue about what could be going wrong :c. Do you?

I guess you have FAT or NTFS partitions on your HDD and with default mount options all files are treated as executables. Executable permission has priority over file name, so instead of opening `zathura` or `mpv`, data in your media files is processed as a shell script (for PDFs; you can actually open them in Vim and see textual structure highlighted) or executables (for videos; these are binary formats).

Maybe [this superuser question](https://superuser.com/questions/512393/why-is-every-file-marked-as-an-executable-on-my-mounted-ntfs-partition) will help you. Vifm doesn't have means to work around this situation, but normally you don't want your data files to be marked as executables anyway.

**Comment by marcosrdac** [comment]
Hi, @xaizek ! It was my bad that I didn't say it, but both my HDD and SSD are ext4 formated. I didn't really know my mount options could cause files to become executable. Thanks for the help!

I tried some mount options, but haven't had much success. Anyway, disabling unsetting "runexec" in vifmrc hapenned to serve to my goals.

Now when I press enter in a video file or a pdf inside the HDD, for example, they are called from mpv or zathura, respectively.

Again, thanks! I'm closing this issue.

**Comment by marcosrdac** [comment]
Hey, needed to inform: I've forgotten the ending comma for mpv in filextype!

Also, I didn't know much about file and folder permissions. Mounting the HDD (which is EXT4 formated, btw) as non-executable could be done with:

sudo chmod -R ugo-x+X folder

Everyting is working fine now!
