### ISSUE TITLE
[FR] CTRL-{6,^} mappings (alternate file)

### ISSUE THREAD

**Issue by laur89** [vifm/vifm#479]
As we have in [v]im, could switching between alternate file be implemented. Should default to same shortcuts as for vim. See help:

```
							*CTRL-^* *CTRL-6*
CTRL-^			Edit the alternate file.  Mostly the alternate file is
			the previously edited file.  This is a quick way to
			toggle between two files.  It is equivalent to ":e #",
			except that it also works when there is no file name.
```

**Comment by xaizek** [comment]
What would "alternate file" mean in vifm? File that was previously selected in the same directory? 

If yes, then when #290 is implemented, it should be trivial to add. I thought that it would require changing how history is stored and thus needs a new format of vifminfo, but it probably doesn't need to be permanent and span multiple directories, which makes it way easier to implement.

**Comment by laur89** [comment]
I would interpret it as alternate buffer, i.e. previous directory. Eg
- cd to `a/`
- jump around with gg, G, n, N
- cd to `b/`
- jump around with gg, G, n, N
- press CTRL-6  - changes pwd back to `a/`
- press CTRL-6 again - changes pwd back to `b/`

At least that's what feels intuitive for myself.

**Comment by xaizek** [comment]
Then you're describing behaviour of <kbd>''</kbd> and you can either use that or map it to <kbd>Ctrl+^</kbd>:
```vim
nnoremap <c-^> ''
```

**Comment by laur89** [comment]
That's exactly what I meant, cheers.

**Comment by laur89** [comment]
Sorry for continuing with this, but is there a reason `''` doesn't behave similar to vim, jumping to "the position before the latest jump"?
Eg say we're on a file `X`, and jump to mark `a` - coming from vim i'd expect `''` to go back to file `X`.

**Comment by xaizek** [comment]
Because there is no jumplist, this is what #290 is about.
