### ISSUE TITLE
Add user hook to location change

### ISSUE THREAD

**Issue by ezh** [vifm/vifm#480]
Is it possible to add user hook to 
```C
/* Perform actions on view location change.  Force activates all actions
 * unconditionally otherwise they are checked against cvoptions. */
static void
on_location_change(view_t *view, int force)
```
The reason: There are different console tools like `fasd` that are doing navigation tracking. Such information is used for fuzzy search, quick jumps, etc...

It would be nice to execute user command on directory change so even outside vifm we will have locations history.

**Comment by xaizek** [comment]
Are you looking for [`DirEnter` autocommand](https://vifm.info/vimdoc.shtml#vifm-%3Aautocmd)?

**Comment by ezh** [comment]
@xaizek thank you very much!
