### ISSUE TITLE
Use functions in vifmrc

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#482]
Hi!

I have been integrating FZF into Vifm with some exciting results.

For example, I can use FZF and [fd](https://github.com/sharkdp/fd) to change to another directory in Vifm:

    " Command to change directory by picking it via FZF
    " From https://github.com/vifm/vifm/blob/33db3f50b389024014449302b57b14ba1726b3b3/data/vim/doc/app/vifm-app.txt#L4579
    command! fzfcdFromTextDir :execute 'cd' "'".term('fd --type d --hidden --exclude .git --full-path ~/text/ | fzf 2> /dev/tty')."'"
    command! fzfcdFromConfigDir :execute 'cd' "'".term('fd --type d --hidden --exclude .git --full-path ~/config/ | fzf 2> /dev/tty')."'"

    nnoremap <space>T :fzfcdFromTextDir<cr>
    nnoremap <space>C :fzfcdFromConfigDir<cr>

While this works, there's a lot of duplication: The only thing that changes is the directory where the search starts (`~/text/` and `~/config` respectively).

Is there a way to get rid of this duplication by using parameters for `command!` or by having functions like in `.vimrc`?

Thanks in advance,
Matthias

**Comment by xaizek** [comment]
Hi,

you can try using [`%a` macro](https://vifm.info/vimdoc.shtml#vifm-%25a) like this:

```vim
" Command to change directory by picking it via FZF
" From https://github.com/vifm/vifm/blob/33db3f50b389024014449302b57b14ba1726b3b3/data/vim/doc/app/vifm-app.txt#L4579
command! fzfcdFromDir :execute 'cd' fnameescape(term('fd --type d --hidden --exclude .git --full-path %a | fzf 2> /dev/tty'))

nnoremap <space>T :fzfcdFromDir ~/text/<cr>
nnoremap <space>C :fzfcdFromDir ~/config/<cr>
```

I also used [`fnameescape()` function](https://vifm.info/vimdoc.shtml#vifm-fnameescape%28%29) for proper escaping (will update docs too).

**Comment by mb720** [comment]
Hi!

The following mapping only works when I'm in my home directory. When I'm somewhere else, fzf has no input (directories) to choose from:


    command! fzfcd :execute 'cd' fnameescape(term('fd --type d --hidden --exclude .git --full-path %a | fzf 2> /dev/tty'))

    nnoremap <c-d> :fzfcd ~/docs/<cr>

I'm unsure how to debug this, any help would be appreciated.

**Comment by xaizek** [comment]
Hello,

maybe `fd` prints relative paths or something like that? You could insert `| tee ~/vifm-debug ` to store its output in that file.

**Comment by mb720** [comment]
This was just me being tired and using `fd` the wrong way. The command should have been:

    command! fzfcd :execute !file=$(fd --type d . %a --hidden --exclude .git | fzf 2> /dev/tty)

The dot before `%a` means to search for all directories in the start directory `%a`.

This works when I choose a directory with fzf, but if I cancel the search, I end up in my home directory because only `cd` is executed, without an argument.

To fix that nuisance, I have now this command in my vifmrc:

    command! fzfcd :execute 'cd' fnameescape(term('dir=$(fd --type d . %a --hidden --exclude .git | fzf 2> /dev/tty); if [ -n "$dir" ]; then echo "$dir"; else echo .; fi'))

In case I cancel fzf, the command that vifm executes is `cd .`, keeping me in the directory I'm currently in.

Thanks for your time and let me know if you see something to improve in the command above.

**Comment by xaizek** [comment]
You could do the check in Vifm:
```vim
command! fzfcd : let $FZF_RES = term('fd --type d . %a --hidden --exclude .git | fzf 2> /dev/tty')
              \| if $FZF_RES != ''
              \|     execute 'cd' fnameescape($FZF_RES)
              \| endif
```

**Comment by mb720** [comment]
For anybody with a similar use case: Vifm's `goto` command is very useful for this, as described in the [Wiki](https://wiki.vifm.info/index.php/How_to_integrate_fzf_for_fuzzy_finding).

This is my current command to search for files and directory with fzf and fd. Then make Vifm switch to the selected file's parent directory and move Vifm's cursor to the selected file:

    " %a is the argument: In which directory to search
    " fd's -E is short for for --exclude
    command! FZFfind :set noquickview | :execute 'goto' fnameescape(term('fd . %a --hidden -E .git -E .stversions | fzf 2> /dev/tty'))

Here are some mappings for inspiration:

    nnoremap <space>gd :FZFfind ~/docs/<cr>
    nnoremap <space>gc :FZFfind $XDG_CONFIG_HOME<cr>
    " Search in the current directory
    nnoremap <space>gh :FZFfind .<cr>
