### ISSUE TITLE
remote commands cannot run correctly in menu mode

### ISSUE THREAD

**Issue by kangshugang** [vifm/vifm#484]
I experienced this issue, when I tried to send "goto" command to VIFM to jump to the given folder. If currently VIFM is in menu mode (for example, showing a grep results). Then the UI get mess up.

Here is my fix to this issue as shown below:

![Screen Shot 2019-10-10 at 11 25 41 PM](https://user-images.githubusercontent.com/19381920/66629213-f267af00-ebb5-11e9-89e0-c8d677c2e76f.png)

I wish this issue can be fixed in the future versions.

**Comment by kangshugang** [comment]
The above changes does not work well for the second time. 
Here is a better changes, it work consistently for many times:
![Screen Shot 2019-10-10 at 11 55 57 PM](https://user-images.githubusercontent.com/19381920/66630868-ea117300-ebb9-11e9-9dd7-eff15a0eac15.png)

**Comment by xaizek** [comment]
Thanks.
