### ISSUE TITLE
Bug with --choose-files?

### ISSUE THREAD

**Issue by urbainvaes** [vifm/vifm#485]
Assume we are in a directory with directories directories `bar` and `foo` and nothing else, and that we want to choose a file `FILE` that is located in `foo`, by running `vifm --choose-files -`.

If I move in my move down in my two-item list by pressing `j`, until the highlight is on `foo`, the diretory will open and let me select `FILE`, printing the absolute path to stdout. However, if I seach using `/foo` and click `Enter`, `vifm` will exit and print the absolute path of the directory.

**Comment by xaizek** [comment]
Check if `'hlsearch'` option is on for you. I guess that it is, so after the search `foo` is selected and hitting <kbd>Enter</kbd> when there is a selection constitutes choosing of a file.

**Comment by urbainvaes** [comment]
Many thanks, this fixes the problem. Is there a way to specify settings via command line arguments when launching `vifm`, overwriting what is defined in `.vifmrc`?

**Comment by xaizek** [comment]
Yes, same as in Vim, either of the two options:
```bash
vifm +'set nohlsearch'
vifm -c 'set nohlsearch'
```

**Comment by urbainvaes** [comment]
Thank you very much! In hindsight, I see this wasn't too hard to find in the manual, so sorry for the low-effort question.
