### ISSUE TITLE
Triggering previews cause delay

### ISSUE THREAD

**Issue by Cybolic** [vifm/vifm#486]
In both st and kitty, using the preview/`:view` functionality causes about half a second to two seconds of delay wherein the UI stays frozen after every move to a new file.

Testing with `vifm -c 'fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm echo %c:p %pc echo clear' -c 'cd /home/cybolic/Pictures/' -c 'view' --no-configs` shows that this happens even when no file is actually read.

I'm running the latest Arch (though this issue has been with me since I started using vifm); let me know if I can provide any more details.

**Comment by xaizek** [comment]
File previewing is synchronous, so it must be waiting for external process to finish. What's your shell? Could launching it be this slow?

**Comment by Cybolic** [comment]
Ah yes, that would definitely be it. I'm running quite the bloated zsh setup that does take a second or two to launch. Is there any way I can set vifm to use bash instead?

**Comment by xaizek** [comment]
You can set [`'shell'` option](https://vifm.info/vimdoc.shtml#vifm-%27shell%27) to `/bin/bash`:
```vim
set shell=/bin/bash
```
`$SHELL` value will still be used by `:shell` command, so if you have it set to `/bin/zsh` you'll still get zsh there, but things like file previews will be run by bash.

**Comment by Cybolic** [comment]
Excellent! I knew about the `shell` option, but I thought that would change it for `:shell` as well.
Everything is peachy then; thanks for the help!
