### ISSUE TITLE
feature request: status spanning multiple lines

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#492]
status line is sometimes short for my needs. for instance consider a status line configured as follows:
```
 xpdfrc              -rw-r--r--     root:root     3.479 KB  │okt 16 2019 18:20
 sort mode: +name | size selected: 3.45 KB | free space: 160.095 GB
```
this is impossible to implement in 80-column mode as `vifm` does not allow newline character in its definition. i wonder if it would be possible to implement this.

**Comment by xaizek** [comment]
> i wonder if it would be possible to implement this.

It should be. Currently it's just hard-coded as `1` around the code base, but position of UI elements in general is computed, so height of the status bar might as well be dynamic.
