### ISSUE TITLE
Don't reread source after copy operation

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#495]
Please consider a mount point for which it takes several minutes to list its files (e. g. a mounted NAS on slow network with thousands of files). Once the files are loaded to `vifm` a file is copied to a local filesystem. Even though there is no apparent reason once the file is copied again, the whole source is reread again and this results in a significant delay.

Could `vifm` only update the target side thus making the workflow more effective?

**Comment by xaizek** [comment]
> Could `vifm` only update the target side thus making the workflow more effective?

Yes, this should work when source and destination differ.

**Comment by xaizek** [comment]
You mentioned copying, isn't there a delay when moving files as well? It might be smaller, but looking at the code there should also be a delay after a move.

**Comment by jose1711** [comment]
Yes, I believe there is a delay too.

**Comment by xaizek** [comment]
There will be a delay even after doing `:echo 'hi'` if at least one file is selected. The condition is somewhat weird, maybe I just tried to reload more often than needed just in case. I guess disabling that and seeing whether anything gets broken is possible. I don't like these useless reloads anyway.
