### ISSUE TITLE
Set border size

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#497]
Hi!

Is there a way to set the size of the border between two Vifm windows?

I currently have these options pertaining the border:

    # No side borders
    set tuioptions=u

    highlight Border cterm=reverse ctermfg=none ctermbg=none

Specifically, I'd like to reduce the size of the border.

Thanks!

**Comment by xaizek** [comment]
Hi,

I guess you're talking about middle border being two characters wide to make both windows have equal width (you probably noticed that whether this happens or not depends on width of the terminal window).

A new flag needs to be added to `'tuioptions'` to allow this.

**Comment by mb720** [comment]
Yes, it's the middle border. It would be great if `tuioptions` would allow to set the size in pixels.

**Comment by xaizek** [comment]
> [...] set the size in pixels.

That's not possible, curses works with characters. The flag would just prevent middle border from ever becoming two characters wide.

Have you seen [`'fillchars'` option](https://vifm.info/vimdoc.shtml#vifm-%27fillchars%27)? Maybe you want to do something like:
```vim
set fillchars='vborder:|'
```

**Comment by mb720** [comment]
Thanks for reminding me about `fillchars`! :-)

This issue is moot for me now after adding this to `vifmrc`:

    set fillchars='vborder:│'


![screenshot with new border](https://i.imgur.com/2KHwtGa.png)

The vertical bar is U+2502 from the [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).

The colors for the border are simply:

    highlight Border cterm=none ctermfg=none ctermbg=none
