### ISSUE TITLE
What is the correct spelling of the project name?

### ISSUE THREAD

**Issue by alexherbo2** [vifm/vifm#502]
Is it written “vifm” or “Vifm”?

**Comment by xaizek** [comment]
Either one of them. I think I use "vifm" more often, probably to type both shell command and name in the same way, but "Vifm" is more similar to how Vim's name is capitalized.

**Comment by alexherbo2** [comment]
You don’t have a preference / recommendation?

**Comment by xaizek** [comment]
There isn't much difference. It's the same thing either way. I tend to use "vifm" (might capitalize it at the beginning of a sentence), but "Vifm" looks a bit better as a proper name especially next to other proper names like Vim. In general use whatever you like. I think I was considering using mostly "Vifm", but probably just didn't feel like updating anything to make the transition, it's not important enough.
