### ISSUE TITLE
vifm fails to display appropriate size of files over 4GB

### ISSUE THREAD

**Issue by allora** [vifm/vifm#504]
When I view a folder containing any files larger than 4GB, the file size information for these files is the difference of the total size of the file minus 2^32 . Which seems to me to say, the value is 32bit and wraps back around to 0 once we hit 4GB in file size.

**Comment by xaizek** [comment]
Are you using an old version of vifm on a 32-bit system? The type used for size is `uint64_t` and `#define _FILE_OFFSET_BITS 64` is present, so there shouldn't be an issue. And what OS are you using? Maybe `_FILE_OFFSET_BITS` is ignored there.

**Comment by allora** [comment]
Its a win 10 64bit box, the install file was: vifm-w64-se-0.10.1-binary.zip, so ideally this should have been a 64bit build...

**Comment by xaizek** [comment]
It is a 64-bit build. However, there is a bug since 0.8.1, introduced by 0b6574af11. Thanks for the report!

**Comment by xaizek** [comment]
You can get build from `master` at https://builds.vifm.info/builds/vifm-w64-se-v0.10.1-62-g5a4048c5f3f1.exe if you don't mind pulling in other changes since 0.10.1. Or I can upload a binary just with this fix alone.
