### ISSUE TITLE
Don't return directory when operating with --choose-files

### ISSUE THREAD

**Issue by sjhorst** [vifm/vifm#505]
If I enter vifm with --choose-files I'll often have to parse through several directories to get to my desired file. If that directory is in the middle of a long list, the quickest way to get there is through a / search of the first few characters. However, after completing that search and hitting Enter, vifm will return the directory name rather than descend into the directory.

Since there is a separate --choose-dir flag, I would think the behavior for --choose-files should be to descend into selected directories upon pressing Enter rather than returning them as the chosen selection.

**Comment by xaizek** [comment]
Check if you have `'hlsearch'` option set. It automatically selects search matches, which makes vifm accept it as a selection on pressing <kbd>Enter</kbd>. Turning the option off should give you the behaviour you expect.

**Comment by sjhorst** [comment]
Thank you, that worked. You can close this ticket.
