### ISSUE TITLE
No way to reverse a filter

### ISSUE THREAD

**Issue by opennota** [vifm/vifm#506]
`:filter` command takes a regular expression, and hides the matching files. There's no way to do the reverse: show only the files that match and hide all others.

**Comment by xaizek** [comment]
> `:filter` command takes a regular expression, and hides the matching files.

By default. Or shows matching files by default if `'cpoptions'` doesn't include `f` flag.

> There's no way to do the reverse: show only the files that match and hide all others.

Just add `!` to revert the match. That is
```vim
:filter! abc
```
yields the complement of `:filter abc`.

**Comment by opennota** [comment]
Or `:invert`. Thanks!
