### ISSUE TITLE
add word 'preview' to vifm doc for :view

### ISSUE THREAD

**Issue by m-fonseca** [vifm/vifm#508]
While using vifm I usually use a single pane for most things and haven't turned on preview for a quite a while and basically forgot.  I must have spent 10-15 minutes trying to go through the docs to try to remember how to turn back on file previews.  vifm uses :view for this which is fine, but it would be nice if a search of 'preview' actually brought you to the :view command in the docs.

I realize this is extremely minor, but I was aggravated enough to log into github and enter this :) 

Thank you

**Comment by xaizek** [comment]
Thanks for the suggestion.
