### ISSUE TITLE
Ask for password in mapping

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#510]
Hi!

I've created a mapping that asks for a password with [`read`](https://linux.die.net/man/2/read) and then uses the password to create an encrypted archive with [`7z`](https://linux.die.net/man/1/7z) of the currently selected file (`%c`):

    map acp :!read -s -p "Enter password: " pass && 7z a %c.zip %c -p"$pass"; unset pass<cr>

The password is stored in the `pass` variable.

This works for me, but I was wondering if you have a better (more secure, more elegant) way of doing that.

Thanks!

**Comment by xaizek** [comment]
Hello,

I think you've over complicated it. This should work too and not display password in process listing (it also asks for confirmation of password):

    noremap acp :!7z a %c.zip %c -p<cr>

**Comment by mb720** [comment]
Oh, right :-)
Thanks for this!

Out of curiosity: How would I be able to sniff the password using the process listing?

**Comment by xaizek** [comment]
> Out of curiosity: How would I be able to sniff the password using the process listing?

For example, using `ps`:
```sh
ps a | grep 7z
```

**Comment by mb720** [comment]
By the way, this conversation inspired a [question](https://unix.stackexchange.com/questions/563718/sniff-password-entered-with-read) about password sniffing.
