### ISSUE TITLE
Copying file is an blocking process

### ISSUE THREAD

**Issue by therealmaxmoon** [vifm/vifm#511]
I am new to vifm and was really glad to find a file manager for the terminal, which works with vim keys. But after I tried to move a huge file to an external disk, I couldn't do anything else, the copying process blocked the file manager.

The progess bar is very nice, but it would be much nicer if you could continue working or even put more copying tasks on the copying work stack.

**Comment by xaizek** [comment]
You can copy large files using `:copy &` to do not wait. However, you'll lose ability to undo/redo that operation. There is no fs- or device-based queuing.

**Comment by therealmaxmoon** [comment]
So what would be the recommended way to copy or move a file the "nice way"?

Would it be to put the blocking vifm to the background with `Ctrl-Z`, start a new one with `vifm` and then checking the blocking one with `fg 1` again?

**Comment by xaizek** [comment]
`:copy &`, `:move &` or `:put &`. You'll sill get the progress at the bottom and can stop the copying from `:jobs` menu (by pressing <kbd>dd</kbd>).

**Comment by therealmaxmoon** [comment]
It works really good!

I've just put the & to the existing key bindings in the vifmrc:
```
nnoremap <f5> :copy &<cr>
nnoremap <f6> :move &<cr>
```
