### ISSUE TITLE
Move directory and file count in preview to the top

### ISSUE THREAD

**Issue by AtomToast** [vifm/vifm#514]
At the moment the amount of files and directories (for example ` 2 directories, 42 files` ) in the preview window of a selected directory (for example through pressing w, e or using :view) are located at the bottom of the tree view.  
This makes them disappear off the screen when looking at large directories which especially then would be a useful information to have.

**Comment by xaizek** [comment]
Makes sense, thanks for the suggestion.

**Comment by xaizek** [comment]
On second thought, it might be better to make this optional. Current implementation allows viewing top of huge trees fast because it quits upon filling window, but printing files and directories stats at the top will require visiting whole directory tree anyway.

**Comment by AtomToast** [comment]
That makes sense I guess, I am all for options and configurability
