### ISSUE TITLE
Unable to bulk rename files

### ISSUE THREAD

**Issue by sdushantha** [vifm/vifm#515]
Hello :)

I was trying to bulk rename a few files, but had no success.

I selected the files using <kbd>v</kbd> and then used <kbd>j</kbd> to select more files.
Then I pressed <kbd>cw</kbd>, but got represented with this:
```
/usr/bin/nano: invalid option -- 'f'
Type '/usr/bin/nano -h' for a list of available options.
Press return ...
```

and then:
```
┌─────────────────── Error Editing File ────────────────────┐
│                                                           │
│ Editing of file "/tmp//vifm.rename_3058130587_00" failed. │
│                                                           │
│                 Press Return to continue                  │
└───────────────────────────────────────────────────────────┘
```

Not really sure why that happened.

Also, quick question, would it be possible to use `vim` to do the bulk renaming?

**Comment by xaizek** [comment]
It should be using Vim by default. Have you configured Vifm to use `nano` instead using `'vicmd'` option? Something Vim-like is expected that can accept Vim's options, `nano` doesn't.

**Comment by sdushantha** [comment]
I have this set:
```
set vicmd=$EDITOR
```
And my `$EDITOR` is `nvim`:
```
$ echo $EDITOR
nvim
```

**Comment by xaizek** [comment]
I guess you're setting `$EDITOR` in your shell's configuration, but start Vifm outside of shell (e.g., `xterm -e vifm`)? In this case Vifm won't see `nvim` in `$EDITOR`. You might need to set `$EDITOR` in `~/.profile`, in which case it should have the correct value for the whole login session.

**Comment by sdushantha** [comment]
![image](https://user-images.githubusercontent.com/27065646/74928662-3c6d6680-53da-11ea-8160-443a3e440214.png)

**Comment by xaizek** [comment]
Have you checked the value inside Vifm with `:echo $EDITOR`? You can also do the same in gVim, which is probably run with no help from the shell.

**Comment by sdushantha** [comment]
Ah yes, that return `/usr/bin/nano. How can I change this?

**Comment by chelovechishko** [comment]
> Zsh runs ~/.zprofile, not ~/.profile, when it is invoked as a login shell. The reason is that zsh has enough incompatibilities with standard shells to break scripts.

https://superuser.com/a/187673

**Comment by sdushantha** [comment]
@chelovechishko Thank you so much, that fixed the issue!
