### ISSUE TITLE
Couple of questions from a new user

### ISSUE THREAD

**Issue by matcharles** [vifm/vifm#520]
Thanks for making such a wonderful program. I have been using it full time now for a couple of days and I am never looking back. That said, I have a couple of quirks that I would like to know if you can help me out with.

1) Is there a way to remove the delete confirmation prompt? I am aware of the DD to permanently remove the file, but I am talking about the prompt to move to the trash. I have stumbled on #165 , but I am not sure I understand the `noconfirm` option. I have tried :set noconfirm in vifm, `set noconfirm` and `noconfirm` in my vifmrc without any luck.

2) Is it possible to remove the hints at the bottom? Again, I have tried `statusline stl ""` but it still shows up.

3) The `yf` yank filename doesn't seem to work for me. It does show up in the menu when I press `y`, but the clipboard doesn't register. I have xclip 0.13-2 installed. I'm not sure how to diagnose this?

4) Is it possible to have the cursor move to the next file when you tag an item? This way you can press `t` for instance 3 times to select three items in a row instead of having to move down with `j`?

Thanks a lot for your time. I am still very much a beginner with computers.

**Comment by xaizek** [comment]
1. Do
    ```vim
    set confirm=permdelete
    ```
    It's not a boolean option anymore (see [the docs](https://vifm.info/vimdoc.shtml#vifm-%27confirm%27)).
2. Use something like this:
    ```vim
    set statusline=" %t %= %A %10u:%-7g %15s %20d "
    ```
3. You probably just need to change the command in `vifmrc` to
    ```vim
    nnoremap yf :!echo %c:p | xclip -selection clipboard %i<cr>
    ```
    I guess you're using <kbd>Ctrl+V</kbd> and not middle button on your mouse, which is where it's copied by default (`-selection clipboard` changes that).
4. Do
    ```vim
    nnoremap t tj
    ```

**Comment by matcharles** [comment]
Wow thanks so much! All working as I wanted. You're the best!

**Comment by matcharles** [comment]
Oh one last thing! 

If for instance I do `noremap gt :lstrash` it will enter the command at the bottom instead of actually doing the action. Like I'll have to type enter after, is this intented behavior or am I doing this wrong?

**Comment by xaizek** [comment]
It's intended, add `<cr>` at the end to execute it from a mapping:

```vim
noremap <silent> gt :lstrash<cr>
```
(I've added `<silent>` to not see `:lstrash` appearing on command-line.)

**Comment by matcharles** [comment]
Damn you're a good dev. Thanks a bunch!
