### ISSUE TITLE
Error dialog is broken on Windows

### ISSUE THREAD

**Issue by GeneZharov** [vifm/vifm#521]
The man page says:

> :[range]!command &
> ...
> Programs that write to stdout like "ls" create an error message showing partial output of the command.

But on my Windows machine, any output of a background process breaks the UI and the dialog window does not appear. When the bug happens, vifm can't be repaired with `:redraw` or `<C-l>`.

This is how it looks:
![Screenshot (7)](https://user-images.githubusercontent.com/12275402/75717305-eeae0380-5ce1-11ea-988b-82fbc39dfbca.png)
![Screenshot (8)](https://user-images.githubusercontent.com/12275402/75717308-f077c700-5ce1-11ea-81c6-c3e31d3260d9.png)
![Screenshot (9)](https://user-images.githubusercontent.com/12275402/75717312-f2418a80-5ce1-11ea-9769-c1da86c89eb6.png)
![Screenshot (10)](https://user-images.githubusercontent.com/12275402/75717318-f40b4e00-5ce1-11ea-87fc-767dc78c8a97.png)

I see this bug in any kind of Windows terminal: standalone vifm.exe, ConEmu, PowerShell, cmd.exe.

My vifm instance was installed by Chocolatey (cinst vifm).

```
PS C:\Users\genez> vifm --version
Version: 0.10.1
Git info: v0.10.1-0-g546be4ebeff7
Compiled at: Jul 29 2019 16:35:50

Support of extended keys is on
Parsing of .desktop files is disabled
Without GTK+ library
Without magic library
Without X11 library
Without dynamic loading of X11 library
Without file program
With remote command execution
```

**Comment by xaizek** [comment]
Thank you for the report. You're testing it for stderr output and this is how it should work, the manual incorrectly mentions stdout. Another thing that the manual gets wrong is that it was never implemented for Windows...

I didn't remember this and just checked versions back to 0.7.6, neither of which produced any dialogs (UI does restore after switching panes and redraw I think). Looking at the code made everything clear.

So at the moment `2>NUL` is needed to ignore error stream (`>NUL` to ignore standard output).

**Comment by GeneZharov** [comment]
Actually, it is not about the incorrect help manual. Vifm becomes almost unuseful for daily work on Windows (If you have to launch anything in the background ). Visual artifact on the bottom of the screen is not the main problem. All the UI is actually shifted to the top, but not redrawn. And the only way to recovery that I know is to open and quit the `:shell`.

**Comment by xaizek** [comment]
Switching active pane and pressing <kbd>Ctrl+L</kbd> seems to restore UI too. And as I mentioned you can add `2>NUL` and `>NUL` when running background command to ignore its output (assuming that the output doesn't contain anything important).
