### ISSUE TITLE
Frequent need to redraw the screen

### ISSUE THREAD

**Issue by pglira** [vifm/vifm#522]
I'm a heavy vifm user. However, around 10 times a day I need to redraw the screen (:redraw or ^l) in order to remove artefacts remaining from a previous screen:
![image](https://user-images.githubusercontent.com/14214284/75851963-38cedc00-5deb-11ea-9185-e13d87df58eb.png)

This happens on three different computers, all running ubuntu (18.04-19.04). I'm using the lastest version of vifm (0.10.1).

**Comment by xaizek** [comment]
Is there any pattern to when this happens? Maybe always after a preview or running a particular command? You're also talking about previous screen, does that screen come from vifm itself?

**Comment by pglira** [comment]
Unfortunately I can't see any pattern. In the beginning I thought it happens after filtering the file/dir listing (=...). But it also happens sometimes when I simply move between different folder. The artefacts always stem from a previous view of vifm itself.

**Comment by xaizek** [comment]
What's your terminal emulator and value of `$TERM` inside of it? (Maybe do `:echo $TERM` in vifm itself to know the value it sees for sure.) And are you running vifm inside a terminal multiplexer?

**Comment by pglira** [comment]
- terminal emulator is lxterminal
- ``:echo $TERM`` gives ``xterm-256color ``
- vifm is running inside of tmux

I will try vifm without tmux now for a while and see if that solves the problem.

**Comment by xaizek** [comment]
> tmux
> xterm-256color

This is wrong, you need it to be `tmux-256color` or `screen-256color` (first one is better). Read message at the top of [tmux's FAQ](https://github.com/tmux/tmux/wiki/FAQ) and possibly ["TERM strings" post](https://sanctum.geek.nz/arabesque/term-strings/).

**Comment by pglira** [comment]
Thank you, that solved my problem! No visualization problems anymore with `screen-256color`.
