### ISSUE TITLE
Git-for-windows bash returns /C: /C: Is a directory

### ISSUE THREAD

**Issue by TiagoDillenburg** [vifm/vifm#526]
Hi, I'm runing vifm 0.10.1 on Windows 10 using cmder as emulator, git-for-windows bash as shell and cygwin as terminal. When I try to edit a file using ":e %c" or edit the $VIFMRC using ",c" the terminal flashes and returns "/C: /C: Is a directory". This was not happening on version 0.10 and back.

**Comment by xaizek** [comment]
Hello.

This must be due to new `'shellcmdflag'` option. It's `/C` on Windows by default and doesn't change when you set `'shell'` in your `vifmrc`. Set it to `-c` there as well.

**Comment by TiagoDillenburg** [comment]
I've set shellcmdflag to `-c` in `vifmrc` but the problem persists.

**Comment by xaizek** [comment]
My bad, that's only part of it. I forgot that non-cmd shells got broken in 0.10.1. You can use a newer binary from https://builds.vifm.info/, `v0.10.1-78` or newer should do (78 has fewer changes since the release).

**Comment by TiagoDillenburg** [comment]
Ok, it's working now. Thanks
