### ISSUE TITLE
Is there a way to remove the "Press Return ..." dialog when force quitting an application launched by vifm? 

### ISSUE THREAD

**Issue by matcharles** [vifm/vifm#527]
I'm getting this from various applications, and I noticed it only pops up when I force quit the app. I understand it isn't a bug perse, but I would rather not have to do so if given the chance. Couple of screenshots
![DeepinScreenshot_select-area_20200312080030](https://user-images.githubusercontent.com/16296847/76625133-fd2fc280-650c-11ea-9d00-b6361ef41092.png)
![DeepinScreenshot_select-area_20200312080046](https://user-images.githubusercontent.com/16296847/76625140-002ab300-650d-11ea-80e3-56cfcdc0da91.png)
![DeepinScreenshot_select-area_20200312133357](https://user-images.githubusercontent.com/16296847/76625141-002ab300-650d-11ea-9c62-7bbae85eb8b1.png)

Apps are gpicview, audacity and mpv. Thanks!

**Comment by xaizek** [comment]
It appears if application exits with an error to let you read its output. For graphical applications you probably want to open them in background by appending ` &` (there is space before ampersand) this will get rid of this. You could also copy `vifm-pause` to `$VIFM/scripts` and edit it to exit immediately, but this will break `:!!cmd` as well. There is no option to disable pausing after failure.

**Comment by matcharles** [comment]
Thanks a lot for this, will just use the background function instead! Much appreciated :+1:
