### ISSUE TITLE
closing wrong file-descriptor in registers_shared_memory

### ISSUE THREAD

**Issue by verdult** [vifm/vifm#528]
This is probably an unwanted typo in `vifm/tests/misc/registers_shared_memory.c`

<img width="580" alt="image" src="https://user-images.githubusercontent.com/4438710/77334048-97b9ae00-6d24-11ea-925d-1a2b296c6426.png">

**Comment by xaizek** [comment]
Yes, closing it twice is useless. Thanks.

**Comment by verdult** [comment]
@xaizek Well actually I think the `close(out_pipe[1]);` should be `close(out_pipe[0]);` since `fdopen()` failed. It is similar to the `fdopen()` on the `in_pipe` code that is written above this part. There it actually closes the correct file descriptor.

**Comment by xaizek** [comment]
Yeah, I got it, just phrased my response poorly. `out_pipe[0]` also isn't closed in the `if` above.
