### ISSUE TITLE
`nnoremap <c-\> :exit<cr>` is not triggered immediately

### ISSUE THREAD

**Issue by mroavi** [vifm/vifm#530]
I have the following mapping in my `vifmrc`:
```
nnoremap <c-\> :exit<cr>
```
The problem I'm facing is that I need to press `<c-\>` followed by any other key so that the command gets triggered. Any idea how to fix this? I noticed that this also happens with 
```
nnoremap <c-b> :exit<cr>
``` 
but it doesn't happen with 
```nnoremap <c-j> :exit<cr>```

I'm using `tmux`: 
```
❯ tmux -Version
tmux 2.6
```
and this version of `vifm`:
```
❯ vifm --version
Version: 0.9.1
Git info: built out of repository

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
Looks like you have other mappings that start with `<c-\>`. Try doing `:nnoremap <c-\>` to list them.

**Comment by mroavi** [comment]
Apparently not: It outputs `No mappings found`.

**Comment by xaizek** [comment]
> tmux

Does it happen outside of tmux? I think <kbd>Ctrl+B</kbd> is its default prefix key, <kbd>Ctrl+\\</kbd> might also be handled by it in some way.

**Comment by mroavi** [comment]
I just found out that I missed a very important point in the description of the problem. Yesterday, I was observing this issue in both normal `vifm` and also in Vim's `vifm` plugin. Today I'm seeing that this only occurs with Vim's `vifm` plugin. I should probably move this issue to the `vifm` Vim plugin.

**Comment by mroavi** [comment]
Could you transfer this issue to https://github.com/vifm/vifm.vim?

**Comment by xaizek** [comment]
```
Special in the terminal window:			*t_CTRL-W_.*  *t_CTRL-W_N*
...
	CTRL-\ CTRL-N   go to Terminal-Normal mode, see |Terminal-mode|
```
So if you run vifm inside tmux inside Vim, that explains issues with both keys.

**Comment by mroavi** [comment]
Oh wow. Great catch. I didn't even know about the existence of this `Terminal-Normal` mode.

**Comment by xaizek** [comment]
I don't think it's possible, you have to always type it using `'termwinkey'`, so <kbd>Ctrl+W</kbd><kbd>Ctrl+\\</kbd> if you haven't changed the option.

**Comment by mroavi** [comment]
Vim has two mappings for the exact same thing. What a shame that I cannot unmap the latter one:
```
	CTRL-W N	go to Terminal-Normal mode, see |Terminal-mode|
	CTRL-\ CTRL-N   go to Terminal-Normal mode, see |Terminal-mode|
```

**Comment by xaizek** [comment]
The first one depends on the value of `'termwinkey'`, the second one is always there. I guess the second one is meant to be used in user mappings.

**Comment by mroavi** [comment]
Clear. Thanks a lot @xaizek. It's now clear to me why I can't close Vim's `vifm` plugin with <C-Bslash>. I will close this issue.
