### ISSUE TITLE
Default color scheme of other pane

### ISSUE THREAD

**Issue by dschrempf** [vifm/vifm#532]
The default color scheme for the other pane seems to be faulty. When opening `vifm` for the first time, it shows the default color scheme, which is nice:

![20200405_18h06m46s_grim](https://user-images.githubusercontent.com/5596239/78503709-9d71b380-7768-11ea-862e-96bc7957c123.png)

However, it saves a default confgi in `~/.config/vifm/colors/Default.vigm`, which contains the following line:
```
highlight OtherWin cterm=bold,underline,reverse,standout,italic ctermfg=default ctermbg=default
```
and leads to this scheme for all following calls:

![20200405_18h06m30s_grim](https://user-images.githubusercontent.com/5596239/78503702-9480e200-7768-11ea-952f-389e5f2167ea.png)

Is this intended? If so, can it be changed? It nearly scared me away from this awesome program!

EDIT: Something is wrong with GitHubs image system. Let me know, if you cannot see the images. In essence, the ugly image has the other pane with reversed colors (white background, black foreground).

**Comment by xaizek** [comment]
Thanks for the report, but it's already fixed by c3c58abccf3f08d3edcdcbe97f8ce1ebb450a2b2. It was reported outside of GitHub. Dropping that line or changing it to remove `cterm` is a workaround for now.
