### ISSUE TITLE
dotfiles status not saved between sessions

### ISSUE THREAD

**Issue by yusufaktepe** [vifm/vifm#533]
Version: `master`

Vifm won't remember the status of dot files visibility, unlike stable version.

vifminfo:
```
set vifminfo=dhistory,savedirs,chistory,state,tui,shistory,
	\phistory,fhistory,dirstack,registers,bookmarks,bmarks,tabs
```

**Comment by xaizek** [comment]
Thank you, due to a typo state of filter inversion is used to initialize dotfiles filter.

**Comment by yusufaktepe** [comment]
Hi @xaizek , sorry for bothering you again.
This commit fixed the issue between sessions, but if I reload with `:write | restart` it still doesn't remember the status.

**Comment by xaizek** [comment]
Do you have more than one tab open? I suspect that's the case. `:restart` doesn't discard current tabs and doesn't load tabs either in this case. Without tabs it keeps you where you are (doesn't change directory and cursor position, keeps layout), but with tabs there is no way of doing that as tabs can't be matched to each other in a meaningful way. You don't need to match them after `:write`, but `:restart` doesn't know that.

To make `:write | restart` work with tabs something like `:restart!` (or `:restart full`) that doesn't try to preserve anything needs to be added.

**Comment by yusufaktepe** [comment]
Thanks for the clarification.

**Comment by xaizek** [comment]
Added `:restart full`. This should work as expected:
```vim
command! reload :write | restart full
```
