### ISSUE TITLE
How can I remove the file count?

### ISSUE THREAD

**Issue by sdushantha** [vifm/vifm#535]
Hey,

Is it possible to remove the file count that is under the status bar?
![shot_20-04-08_at_20-14-03](https://user-images.githubusercontent.com/27065646/78818961-c34fc000-79d5-11ea-9015-cb1ed9c10951.png)

**Comment by xaizek** [comment]
Hi,

you can make it empty with
```vim
set rulerformat=
```

**Comment by sdushantha** [comment]
@xaizek Thank you! That fixed it :)
