### ISSUE TITLE
Setting window title in the Alacritty terminal emulator.

### ISSUE THREAD

**Issue by m-kru** [vifm/vifm#536]
Placing `set title` in vifmrc in case of Alacritty terminal does not work. This is probably because `$TERM` for Alacritty is `alacritty`, which seems to not be supported. I think it is doable to add such support as vim `:set title` works correctly with Alacritty.

**Comment by xaizek** [comment]
[Terminfo for Alacritty](https://github.com/alacritty/alacritty/blob/f14d24542c3ceda3b508c707eb79cf2fe2a04bd1/extra/alacritty.info#L108) does define `tsl` and `fsl` capabilities. Should make vifm use those when they are present. Thanks!
