### ISSUE TITLE
vifm displays nothing - literally.

### ISSUE THREAD

**Issue by m-kru** [vifm/vifm#537]
I was navigating inside vifm and suddenly it stopped displaying anything. I have restarted the terminal, run vifm again, but with no success. I have even restarted my machine, but still nothing.
![vifm](https://user-images.githubusercontent.com/26227737/79048439-50388a80-7c1d-11ea-8066-cb475bc931e9.png)

**EDIT**
If i specify the directory at run everything works. It always happens when I am navigating inside `/dev` directory. I think `vifm` may not be handling correctly some aspects of device files.

**Comment by xaizek** [comment]
Not sure what might be causing this for you. I have no trouble going to `/dev/`, `/sys/` or `/proc` and loading every file it in using `:tree`.

Do you have preview enabled? This can cause trouble on certain files for sure.

**Comment by m-kru** [comment]
You are right. There is a problem when the preview is enabled. Nevertheless, it would be good if such cases were handled in more graceful way. Can I help somehow in discovering what is going on?

**Comment by xaizek** [comment]
It is handled for non-regular files (so for character and block devices too) by not previewing them (it prints message like "File is a Character Device").

Looks like I know what's wrong. I got it to hang by going into `/dev/fd` or by putting cursor on `/dev/stderr`, all of which are symbolic links to devices. The code currently misses the case of symlink targets being non-regular files. Resolving symlink target before the checks should take care of this. Thanks for reporting! This explains why happened only for some files.
