### ISSUE TITLE
Simple mistake can result with big damage.

### ISSUE THREAD

**Issue by m-kru** [vifm/vifm#539]
When `set runexec` is set, an executable file can be run when user press `Enter`. However, it is also executed when user presses the `l` key. This creates a dangerous situation, as the `l` key is under the ring finger in home position. Probability of pressing it by mistake is much higher than pressing the `Enter` keyword by mistake. Today I have mistakenly run the script this way. 

What is more this is not what is said in the example vifmrc:
```
" If you would like to run an executable file when you
" press return on the file name set this.
```

In my humble opinion this behavior should be fixed as soon as possible.

**Comment by xaizek** [comment]
There is a mistake in the comment, thanks. <kbd>l</kbd>, <kbd>Enter</kbd> and <kbd>Right</kbd> are identical in most contexts.

Breaking the symmetry for running executables would be weird. You can map <kbd>l</kbd> to be safer in this regard:

```vim
nnoremap <silent> l : if filetype('.') == 'exe'
                    \|     execute 'normal! i'
                    \| else
                    \|     execute 'normal! l'
                    \| endif<cr>
```

I agree that you can run something by accident, but you can bind any key to a destructive operation and press it accidentally, so <kbd>l</kbd> isn't really special. Changing the behaviour by default would also be a backwards incompatible change, however there could be a flag for it in `'cpoptions'` which wouldn't be reset in sample `vifmrc` file, so new users would get new behaviour.

**Comment by m-kru** [comment]
I am also happy with the remap solution. I have totally forgotten that I can remap keys just like in vim.
