### ISSUE TITLE
:help command fails if vim not installed

### ISSUE THREAD

**Issue by Keating950** [vifm/vifm#540]
**Version: 0.10.1**

Running `:help` from inside vifm doesn't work if vim is not installed (i.e., if you use Neovim). Instead, it results in the following output:

```
zsh:1: command not found: vim
Press return ...
```

**Comment by Keating950** [comment]
Nevermind, just found the config setting.

**Comment by xerus2000** [comment]
What is the setting called?

**Comment by Keating950** [comment]
I believe it’s `set vimhelp`.

**Comment by xaizek** [comment]
It's [`'vicmd'` option](https://vifm.info/vimdoc.shtml#vifm-%27vicmd%27).
