### ISSUE TITLE
Weird three digits prefix for trash

### ISSUE THREAD

**Issue by yanzhang0219** [vifm/vifm#544]
Hi,

vifm version: the latest
macOS version: 10.15.4

Question-1:
When I use `dd` to delete one file, it is moved to ~/.local/share/vifm/Trash/, but after it is moved into the Trash folder, its filename is prefixed by three digits. And if I use `P` in a certain folder to move this file there, its filename restores. For example, if the file name is `test.md` and after I delete it, its name becomes to 000_test.md in Trash folder. What does this prefix mean and can I use some setting to get rid of them?

Question-2: an issue after I change `trashdir`
I tried to change the `trashdir` from the default location (\~/.local/share/vifm/Trash/) to the location of the macOS builtin Trash Bin (~/.trash/). I put `set trashdir='~/.trash'` into my vifmrc. Then when I use `dd` to delete a file, say test.md, it is moved to the macOS builtin Trash Bin with a three digits prefix on its filename. However, if I use `P` to move it to a certain folder, its filename doesn't restore, i.e., it is moved to that folder with a filename 000_text.md. How can I make it have a correct filename after movement? 

Thank you very much!

**Comment by xaizek** [comment]
Hi,

> What does this prefix mean and can I use some setting to get rid of them?

The prefix is there to make it possible to delete multiple files with the same name. It's not configurable as it's something internal to Vifm.

> it is moved to the macOS builtin Trash Bin with a three digits prefix on its filename.

Works fine for me. Is `~/.trash` a regular directory? Or maybe it's a symbolic link?

**Comment by yanzhang0219** [comment]
Hello,

Okay, I got it. Thank you. 

> Is ~/.trash a regular directory

Oh man!. The macOS trash bin path should be `~/.Trash`, not `~/.trash`. Now it works. :) I'm so sorry. It's my carelessness.

Thanks.
