### ISSUE TITLE
Multiple lines config for classify cause an error

### ISSUE THREAD

**Issue by yanzhang0219** [vifm/vifm#547]
Hi,

Thank you for fixing the %a stuff on macOS. And a new error showed up after I rebuilt it. 

After I git pull the latest commit from the master and rebuilt it, and when I tried to open vifm, an error popped up:
![image](https://user-images.githubusercontent.com/11582667/80998777-625eb080-8df8-11ea-9512-f1d9f9ee192b.png)

The icons file is [here](https://github.com/yanzhang0219/dotfiles/blob/master/.config/vifm/icons). And if in the icons file I appended an empty line (or a line of comment) at the end, this error was fixed. 
![image](https://user-images.githubusercontent.com/11582667/80999037-d39e6380-8df8-11ea-8e9d-495c37ceb29c.png)

Thanks.

**Comment by xaizek** [comment]
Hi,

thank you for the report. Will fix it soon and with some luck won't introduce some new bug at the same time.

By the way, I think you have a typo in one of the patterns [here](https://github.com/yanzhang0219/dotfiles/blob/2e7a476ca3be60a262678978b256f8339ee19814/.config/vifm/icons#L48). `.*.bz2` should probably be `*.bz2` (no leading dot).

**Comment by yanzhang0219** [comment]
Thanks. Sorry about my carelessness. I will correct it. :)
