### ISSUE TITLE
Computed directory size cached after directory removal

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#550]
```
mkdir -p vifm_test/{big/dir,small/dir}
dd if=/dev/zero bs=1M count=100 of=vifm_test/big/dir/file
dd if=/dev/zero bs=1M count=10 of=vifm_test/small/dir/file
vifm vifm_test/big vifm_test/small 
move cursor to big/dir
gA
observe computed size (100 MB)
delete directory (dd)
switch to second panel (tab)
move to small/dir
copy directory from small to big (:copy)
see how vifm_test/big still shows as 100 MB
```
Ideally `vifm` either recomputes the size or displays the default value for directories (e. g. 4k).

**Comment by xaizek** [comment]
Thanks for the report. Probably makes sense to check validity of cache entry by comparing inode numbers. Still not perfect, but will fail in much fewer cases.

> the default value for directories (e. g. 4k).

It's not default value, it's how much space directory is using for storing its list of files.
