### ISSUE TITLE
Opening filetypes doesn't work in wayland (swaywm)

### ISSUE THREAD

**Issue by mhdzli** [vifm/vifm#551]
I assign applications to filetypes in vifmrc and it doesn't have any problem in xorg (dwm). But I couldn't get it working on wayland (swaywm).

**Comment by xaizek** [comment]
I guess you're using `:filextype` command. Vifm checks for `$DISPLAY` to see if it's running in a graphical environment. Defining `$DISPLAY` to some non-empty value might work (I'm not sure whether it will break the applications), alternatively you can use `:filetype` command.

Looks like Wayland defines `$WAYLAND_DISPLAY` instead, will add check for it, thanks!

**Comment by mhdzli** [comment]
Yes I was using `:filextype`. Thanks. everything works perfectly. I just need to manage a way to enable image preview in `wayland` since `ueberzug` depends on `X`.

**Comment by h31di** [comment]
do you already found a solution for image preview in sway?

**Comment by mhdzli** [comment]
@h31di 
Using `icat` on `Kitty` and `sixel` on `foot` which I'm using right now. But I think there is a script for using swayimage in with any terminal emulator

**Comment by storopoli** [comment]
https://github.com/artemsen/swayimg
