### ISSUE TITLE
The "z" mark doesn't work fine

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#552]
I use Vifm 0.10.1. on Debian.

Three years ago I realised that my `mark z ~/mydir` in my config file didn't work fine: when I used the mark, I got an error: "Mark is not set". I didn't pay much attention: I just did `:restart` and problem "solved". Now I have finally done some checks in order to find out the error conditions:

- The problem happens only with "z" (I have many marks in the config file, almost the whole alphabet in lower and uppercase, and no one else ever failed.)
- The position of `mark z` in the config file doesn't make any difference.
- The target of the mark doesn't make any difference.
- It seems  the "z" mark is updated only for the current pane.
- `restart` fixes "z" for the current pane, but deletes it from the other pane.
- The `mz` command creates the "z" mark in the current pane, but doesn't change it in the other pane, i.e. each pane keeps its own "z" mark with different targets.

(Beside using the mark, I have used the `marks` command in order to confirm the result after every test.)

When I saw this strange behaviour, I even doubted whether marks are local to panes or not, but the documentation says nothing about that, and this only happens with "z" anyway, so I guess it's a bug. I hope these details help to find out its cause.

Edit: I forgot to mention the problem seems to affect all of the open tabs the same way at the same  time.

**Comment by xaizek** [comment]
Thank you for the report! By mistake `'z` is treated as a special mark (like `'<`), which are bound to panes.
