### ISSUE TITLE
Build failure on Mac OS X

### ISSUE THREAD

**Issue by mvanier** [vifm/vifm#553]
I'm trying to compile vifm from scratch because the homebrew version isn't behaving well.  The configure script doesn't report any problems except missing gtk-2 libs.  But make fails immediately:

  -> make
  CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/mvanier/_/src/vifm/build-aux/missing aclocal-1.15
  /Users/mvanier/_/src/vifm/build-aux/missing: line 81: aclocal-1.15: command not found
  WARNING: 'aclocal-1.15' is missing on your system.
           You should only need it if you modified 'acinclude.m4' or
           'configure.ac' or m4 files included by 'configure.ac'.
           The 'aclocal' program is part of the GNU Automake package:
           <http://www.gnu.org/software/automake>
           It also requires GNU Autoconf, GNU m4 and Perl in order to run:
           <http://www.gnu.org/software/autoconf>
           <http://www.gnu.org/software/m4/>
          <http://www.perl.org/>

I have aclocal installed:

  -> aclocal --version
  aclocal (GNU automake) 1.16.2

Similarly "make clean" and "make distclean" also fail.  Is this a bug, or am I missing something?  Thanks!

**Comment by mvanier** [comment]
Ah, it was my fault.  I needed to do "aclocal", then "automake", then "configure", then "make".  Closing.

**Comment by xaizek** [comment]
Well, actually all you need to do in this case is:

https://github.com/vifm/vifm/blob/608b1af1ace3e5defa62f2bd2757bf257f40e8e9/INSTALL#L25-L26

This way none of the autotools needs to be installed just like with the tarballs.
