### ISSUE TITLE
Improve displaying of files containing newline characters 

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#554]
```
mkdir /tmp/dir
cd /tmp/dir
touch 'foo'$'\n'$'\n'$'\n''bar1' 'foo'$'\n'$'\n'$'\n''bar2' 'foo'$'\n'$'\n'$'\n''bar3'
vifm /tmp/dir
```
cursor is split between two lines and partially hides the other files. file selection and navigation is not easy. midnight commander for instance converts `\n` to a dot (`.`) so maybe `vifm`'s behaviour could be changed in this direction?

**Comment by xaizek** [comment]
I think `.` would be confusing. Even `\n` can be taken for actual part of the name, although it's much less common.

Ideally, special sequences would be displayed in some unambiguous way. There is no way for that at the moment (like using different color) and it might have weird effects on search highlighting (although less weird than it is now), hence it was left as is.

Having said that, I recently realized that some filenames are displayed in a bad way right now anyway (things like `M-^` and similar), so working around `\n` and alike shouldn't make things much worse. Will need to see effect on the search though.

**Comment by jose1711** [comment]
Since slash is a forbidden character for filename how about something like this?
```
foo/\n\n\n/bar
```
That is: put slashes around special characters.

**Comment by xaizek** [comment]
Nice idea for file names, but custom views can contain paths and such escaping will cause even more confusion.

**Comment by iSeeU816** [comment]
What about question mark `?` as how `ls` command display files contain newline
character in their names. Same thing how macOS Finder handle it.

I don't name files with newline character but I came cross one, and I was to
report it but this issue take care of that with a good recipe. Thanks.

**Comment by xaizek** [comment]
Question mark can is quite ambiguous. The approach taken (at least for now) in view titles and statusline is `^M` kind of escapes. These are more rare to come by. However, two characters will mess up search highlighting for files in views, so `?` could actually be better there. Or maybe correcting for extra characters isn't that big of a deal. This really needs to be tried.

**Comment by xaizek** [comment]
Displayed like this now:
```
foo^J^J^Jbar1
foo^J^J^Jbar2
foo^J^J^Jbar3
```

**Comment by jose1711** [comment]
thank you for fixing it!
