### ISSUE TITLE
utils/rel_symlinks.c tests fail on macOS 

### ISSUE THREAD

**Issue by jtdreisb** [vifm/vifm#559]
The unit tests for vifm-0.10.1 fail on macos 10.15.5.

make check output: https://gist.github.com/jtdreisb/466cb7cf88f8f9fe1be77df9b0ec42b7

Looking at the code in make_rel_path() it appears that:
1. path = '/home/a' and base = '/home/'
2. `/home`'s realpath is `/System/Volumes/Data/home`
3. The common subpath is computed to be `/System/Volumes/Data/`
4. Then relative path is computed to be `../../../../home/a`  instead of `a`

```
[I] ➜ vifm-0.10.1> realpath /home
/System/Volumes/Data/home
```

```
[I] ➜ vifm-0.10.1> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101
```

**Comment by xaizek** [comment]
Thanks for the report and analysis. Will change that to use path that's unlikely to exist.
