### ISSUE TITLE
Bug?: Different results with `--remote-expr` and `--remote` options

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#561]
Hello,

## Steps to reproduce

Note: Only one instance of ViFM is running to do these tests.

**Round 1 (`--remote-expr`)**

1. A fresh ViFM config.
   - First pane path is `/tmp/project`.
   - The other pane have three items (location is `/tmp/tools`):
     - `foo/`.
     - `bar baz/`.
     - `qux.txt`.
   - Select the first two folders `foo` and `bar baz` with `t`.
   - But let `qux.txt` highlighted by jumping to it with `j`.
2. Create a script inside `~/.config/vifm/scripts/` folder with the name `test.sh`.

    ``` bash
    #!/bin/bash

    vifm --remote-expr 'expand("%f:p")'
    ```

3. Make the script executable `chmod +x <script_path>`.
4. Add this line at the end (or anywhere) in `.vifmrc` file:
   - `nnoremap F :!!test.sh<cr>`
5. Launch ViFM.
6. **Result 1a (this is fine):**
   1. Make sure things are how listed in step 1 state.
   2. Run this from within ViFM command line.
      - `:!!vifm --remote-expr 'expand("%f:p")'`.
   3. It should work fine by output the full paths to the two folders.
      - `/tmp/tools/bar baz /tmp/tools/foo`.
7. **Result 2a (Fine too):**
   1. Make sure things are how listed in step 1 state.
   2. Run the script from a terminal (not from inside ViFM):
      - `~/.config/vifm/scripts/test.sh`.
   3. The output is the same as result 1a output except escaping any special
      characters.
      - I noticed that the selection not cleared out as other ways. Great!
8. **Result 3a (Bug?):**
   1. Make sure things are how listed in step 1 state.
   2. From ViFM call this command: `:!!test.sh` and hit Enter.
   3. The output is on the highlighted (not selected) item:
      - `/tmp/tools/qux.txt`.
9. **Result 4a (Same 3a; bug?):**
   1. Make sure things are how listed in step 1 state.
   2. In normal mode, call `F`.
   3. The output is the same as result 3a output.

**Round 2 (`--remote`)**

Here we focus on `--remote` option.

Remember to delete any files in `/tmp/project` before test any result way down
below; to make sure the result as they listed below.

1. Same step 1 from `--remote-expr` section above.
2. Here the script have `vifm --remote -c "copy"` instead of `vifm --remote-expr…` line.
   - Name it `test2.sh`.
3. Same step 3.
4. Map a key for it `nnoremap B :!!test2.sh<cr>`.
5. Launch ViFM.
6. **Result 1b (Bug?):**
   1. Make sure things are how listed in step 1 state.
   2. Run this command:
      - `:!!vifm --remote -c "copy"`.
   3. It copied `qux.txt` which is wrong as it should copied the two folders
      that were selected.
7. **Result 2b (Fine):**
   1. `~/.config/vifm/scripts/test2.sh` works as it should be.
8. **Result 3b (Same 1b; bug?):**
   1. Running `:!!test2.sh` result as 1b.
9. **Result 4b (Same 1b; bug?):**
   1. In normal mode, call `B`. Also, same as result 1b.

## Description

I put a question mark as I don't know if this behavior is OK, I mean that remote
options should be used outside ViFM only; not sure.

Anyway, what I wanted to accomplish and I fall in this bug is to have a list of
selected items in ViFM to loop through them.

Something like `nnoremap <silent> <F5> :copy & | !<script_name>.sh "arg1"`. This
script then checks every copy operation process ID (PID) to wait until all of
them finished, lastly show an alert of what copied and how much time this
process took. Very handy for long file operations tasks.

Thanks!

## Software info

- macOS Mojave 10.14.6.
- iTerm 3.3.2.
- ZSH 5.8.
- TMux 3.0a.
- ViFM 0.10.1 (stable); 0.10.1-642-g1467dee43c77 (master).

**Comment by xaizek** [comment]
Hello,

I'm sure it's a valid bug as what you describe shouldn't work (and it doesn't for me). When you do `:!vifm --remote-expr` to communicate to current instance, the only result you should get is `Evaluating expression remotely failed.` because instance that waits for external command to finish doesn't process remote requests.

In addition to that:

 *  in `:copy & | !<script_name>.sh "arg1"`, `:copy` "consumes" selection and there will be none by the time second command is run
 * `:!!vifm --remote-expr 'expand("%f:p")'` should have `%%` to avoid substitution *before* running the command.

**Comment by iSeeU816** [comment]
Thank you for the info.

I did a few tests with two instances of ViFM, and things become clearer now.

*I think this should be closed.*

**Comment by xaizek** [comment]
By the way, to implement your idea you can try something like this (with `echo` being used for demonstration):
```vim
command! copyextra :copy & | !echo %a%%S
nnoremap <silent> <F5> :copyextra %f:p<cr>
```

**Comment by iSeeU816** [comment]
That's help me a lot, now I'm getting the selected items.

1. A script named `test3.sh` located in `$VIFM/scripts` folder:

``` bash
#!/bin/bash

vifm_selection=$(echo "${1}")
echo "${vifm_selection}"
```

2. Add this to `vifmrc`, similar to what @xaizek suggested above:

``` vim
command! getselection :!!test3.sh %a
nnoremap <silent> ,v :getselection '%"f:p'<cr>
```

3. Reload `:reload` or restart ViFM to make the changes made to `vifmrc` accessible.
4. Select some items (files) in ViFM.
5. Trigger `,v` in normal mode.

Thank you!
