### ISSUE TITLE
Feature: UI suggestions (alternate row colors, …)

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#566]
Hello,

## Alternate row colors

Reading a column's metadata for an item that not selected by `CurrLine` color
needs tracing from item's name to columns metadata either gazing slowly, move to
it or by a mouse cursor. This is even hard in horizontal split layout.

I think alternate row colors will help.

Maybe too (not important), a vertical and horizontal grid lines. The former
between columns, and the latter between items (files).

**Examples (pics from the web):**

Check [this](https://discuss.binaryage.com/t/alternate-row-color-and-vertical-grid-lines/5322) for screenshots.

These screenshots are for [Path Finder](https://cocoatech.com) app, which you
can download a trial version to check it out. Once launching the app, click
`View > as List`. Then `cmd-j` to show the view options, there you can find
`Alternate row colors`, `Show vertical grid` and `Show horizontal grid` options.

## Tab's number color

- To distinguish it from tab's name.
  - Sometimes, the tab's name started with a number.
- This will help to glance it to navigate to it fast.
  - One of my maps to navigate 1-9 tabs.
    - `nnoremap ,1 :tabnext 1<cr>`.
- A user might wants to dim the number color to give the tab's name more
  attention.

## Job's count

A count for running jobs would be very handy in the status line. This can be a
thing once the status line becomes dynamic.

Thanks.

## Software info

- macOS 10.14.6
- ViFM 0.10.1 (stable); 0.10.1-680-g75bc075755b8 (master).

**Comment by xaizek** [comment]
Hi,

> horizontal grid lines

This is terminal, it will effectively half height of the window. You can do this though:
```vim
hi Win cterm=underline
```

> vertical

This might be possible with the idea from [this question](https://q2a.vifm.info/343/mc-like-look?show=346#c346):

```vim
set viewcolumns=*{name}..,│,12{size},│,6{}.
```

> Alternate row colors
> Tab's number color

Can be done with new highlight groups.

> A count for running jobs would be very handy in the status line.

Just number of lines of `:jobs` menu or something more specific? There are several kinds of tasks: external apps, background operations (like file copying) and unimportant background operations (computing size of directories). It can be exposed as a variable and inserted into `'statusline'` using `%{}` syntax.

**Comment by iSeeU816** [comment]
**Horizontal grid lines:**

- It worked, but not inside TMux.
  - iTerm 3.3.2
    - `echo $TERM` output is `xterm-256color`.
  - ZSH 5.8
  - TMux 3.0a, 3.1a, and 3.1b
    - `echo $TERM` output is `screen-256color`.
    - Only this line in `.tmux.conf`:
      - `set -g default-terminal "screen-256color"`.
  - ncurses 6.2.20200212
- Tested with a fresh ViFM config.
- Setting `xterm-256color` for tmux is [not recommended](https://github.com/vifm/vifm/issues/522#issuecomment-594640755).

**Vertical:**

Add my vote to it.

**Jobs count:**

Yes, just a simple count of what inside `:jobs` menu.

Thank you!

**Comment by xaizek** [comment]
> Horizontal grid lines:

Works for me with `TERM=screen-256color` or `TERM=tmux-256color`.  However, looks like `Win` affects way too much (all dialogs and menus), so it's not very usable anyway.

**Comment by iSeeU816** [comment]
It might be something on my end. Anyway, I'm not very concern about it, as alternate row should be enough.

As for the sharpe lines, there is an opacity for underline color in iTerm `Color` tab inside profiles section.
That might help.

**Comment by iSeeU816** [comment]
Sorry for late feedback.

I didn't expected it to be this soon, thank you very much!

I did *kinda* deep test on this, and I have some enhancement requests, if you
don't mind.

**Tab number color:**

I would like the background color of tab's number to inherit tab's background
color. As of now (in master), one can't let tab's number background color
matches both active and inactive tabs' background colors. You have to choose one
over the other.

Trying this `hi TabNr cterm=bold ctermfg=red` results a black background color
behind tab's number of the active tab, contrary in other tabs which things look
good.

I have two approaches (suggestions) to handle this:

1. `CurrTabNr`:
  - An extra tab number color group for active tab.
  - This makes it look nice without the ugly background color box.
2. A new attribute:
  - It job is to match the color of a called group.
  - Something like: `hi TabNr cterm=bold ctermfg=red ctermbg=currline.bg`.
  - The new attribute format is `<group_name_in_lowercase><dot><bg/fg/…>`.

I tend to the first one as it's much easier now to implant.

**Alternate row color:**

Test this: `hi OddLine cterm=none ctermfg=231 ctermbg=24` on a fresh setup of
both iTerm and ViFM. Can we have an opacity so colors don't get in the way?

I mean, to focus more on the content rather than the color itself. Try not to
get dizzy while moving fast with `jjjjjjjjjjj` in horizontal split with long
list of items.

I said earlier that there is an opacity capability in iTerm, but that affect the
whole app. What I want here is an opacity for just ViFM's colors.

**Notes:**

- I hope it's Okay to write here as this is relate to this issue track.
- `:colorscheme?` output in this fresh setup is `Default-256`.
  - Which I think it's `near-default.vifm` color scheme.
    - My favorite!

Thank you again!

**Comment by xaizek** [comment]
> `CurrTabNr`

OK, can add that.

> Try not to get dizzy while moving fast with `jjjjjjjjjjj` in horizontal split with long list of items.

Can try making this independent of offset from the top so that it's always 2nd, 4th, etc. *visible* lines that are highlighted.

> Can we have an opacity so colors don't get in the way?

No, not in a terminal. It might be possible with True-color support, but 256-color palette doesn't allow for transparency.

> * Which I think it's `near-default.vifm` color scheme.

`Default-256` is derived from `near-default`, that's correct. New sample config uses `Default-256` when terminal supports it.

**Comment by xaizek** [comment]
The new highlight group is named `TabNrSel` similar to existing highlight groups.

**Comment by iSeeU816** [comment]
I have tested `OddLine` (alternate row) in different views, and it's much better now.

As for the tab number color, it looks sharp now, great!

Thanks!

**Comment by xaizek** [comment]
#571 was conflicting with `TabNr` and `TabNrSel` and they were removed. Highlighting tab number is still possible, but got more complicated (it's also significantly more flexible now):  https://github.com/vifm/vifm/blob/0facaaadf031c920c7d20498226f30992afde35e/data/vim/doc/app/vifm-app.txt#L3981-L3987

**Comment by iSeeU816** [comment]
I don't mind flexibility.

Thank you for your recent implantation, very excited stuff.
