### ISSUE TITLE
Bug: `:reload` resets directory history on master version

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#567]
Hello,

I found a bug on how master version resets directory history when `:reload`
command is called.

## The bug

These steps applied on a fresh ViFM setup to make sure it can be reproduce on
any device.

1. Launch ViFM with `vifm /tmp ~`.
2. Create two directories: `:mkdir foo bar`.
3. Navigate to `foo` directory.
4. Create a new tab: `:tabnew`, then navigate back to `/tmp` then inside `bar`
   directory.
5. You can check directory history with `:hist d` to make sure everything is OK.
6. Switch to the first tab with `gt`.
7. As the master version have tabs persistent feature, then this step splits
   into two scenarios:
   - **Scenario A:** No `tabs` value in `vifminfo` option, as the default.
     1. Call `:reload`.
     2. Check the directory history of both tabs.
     3. First tab: OK.
     4. Second tab: NOT OK. The directory history resets, and only `/tmp/bar` was left.
        - This occurs because this tab was inactive.
   - **Scenario B:** Make sure to repeat the steps from the start.
     1. Call `:set vifminfo+=tabs` to add `tabs` to `vifminfo`.
     2. Call `:reload`.
     3. Check the directory history of both tabs.
     4. Both tabs: NOT OK. First tab only have `/tmp/foo`, and the second have `/tmp/bar`.

**Notes:**

- `:reload` is an alias for `:write | restart` as in the sample config.
- Stable version (v0.10.1) doesn't have this issue, as `:reload` doesn't resets
  any history, even for inactive tabs.
- The suspect command is `restart`.
  - [Related comment](https://github.com/vifm/vifm/issues/533#issuecomment-613135910).
- If we skip step 7 and just quit `:qa`, the directory history is preserved with
  or without `tabs` value.

Thanks.

## Software info

- macOS Mojave 10.14.6.
- ViFM 0.10.1 (stable); 0.10.1-680-g75bc075755b8 (master).

**Comment by xaizek** [comment]
Hi,

>     * Stable version (v0.10.1) doesn't have this issue, as `:reload` doesn't resets
>       any history, even for inactive tabs.

It does, but it's harder to notice. v0.10.1 reloads history of current tab and clones it to every other tab.

While implementing persistent tabs I got rid of that behaviour, but then I accidentally introduced complete resetting of histories as part of a bug fix.

Thank you for the bug report.
