### ISSUE TITLE
Tagging files/folders

### ISSUE THREAD

**Issue by prometheus94** [vifm/vifm#568]
Hello, 
I was wondering if there is a way to 'tag' files or folders so that all files/folders with the same tag could be easily accessed from one list. I suppose this could be achieved by just symlinking said files/folders to a 'tag' directory but maybe there is a more elegant way ...
Any help is much appreciated.

**Comment by xaizek** [comment]
Hello,

You can mark paths with tags using [`:bmark` command](https://vifm.info/vimdoc.shtml#vifm-%3Abmark). Then list them with [`:bmarks` command](https://vifm.info/vimdoc.shtml#vifm-%3Abmarks) and turn the menu into file list by invoking [<kbd>b</kbd> shortcut](https://vifm.info/vimdoc.shtml#vifm-m_b).

**Comment by prometheus94** [comment]
Perfect! Thank you!
