### ISSUE TITLE
Freez when previewing password encrypted *.7z archive

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#569]
It's no `vifm` fault, but its **default config**. When `7z l *` tries to list files in password protected archive, its wait password from `stdin` and `vifm` does not renders and does not handles keys. Default config states:
```vifm
fileviewer *.7z 7z l %c
```

I tried pass `< /dev/null` to `7z` to prevent reading, or find some parameters, but it does not works.
Also there are similar problems for other password encrypted filetypes.

Will be nice if fix this in default `vifm` config.

`Vifm` build:
```
Version: 0.10.1
Git info: built out of repository
Compiled at: Jul  7 2020 21:30:10

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
Try using this instead:
```vim
fileviewer *.7z setsid 7z l %c
```

> It's no `vifm` fault, but its **default config**.

`setsid` should really be done inside Vifm to don't let viewers hang. If they insist so much on reading input when they shouldn't, they should just fail (`setsid` gives this effect).

**Comment by xaizek** [comment]
I was too optimistic. It can be done programmatically, but it's significantly harder to do it without losing the ability to cancel viewer on <kbd>Ctrl+C</kbd>. So explicit use of `setsid` is a workaround for now (although I'm not sure about adding it to sample `vifmrc`).

**Comment by PRESFIL** [comment]
Thanks for quick reply and this workaround.
But, in my opinion, chance of hanging the whole `vifm` is more annoying than not being able to stop the child process. In my case, it displays `7z`'s *stdout* and I immediately understand that the archive has a password.

Although, yes, if `7z` had its own additional parameter, it would be even better.

**Comment by xaizek** [comment]
This got fixed by doing all previews in background in their own session (`setsid`).
