### ISSUE TITLE
Separators between columns in column view

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#570]
Is there a `fillchars` equivalent for column separator? I get a bit lost when the separator is space. It would be nice to have that feature added if it is absent.

The screenshot on the left show what I would like (it is what I have in Midnight Commander) and on the right what Vifm is like now.

![08-11:57:26](https://user-images.githubusercontent.com/62444221/89713608-2a26bb00-d96f-11ea-87bd-4f7aad5d7640.png) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ![08-12:07:18](https://user-images.githubusercontent.com/62444221/89713696-d10b5700-d96f-11ea-9d07-edaad4a97583.png)

Thank you!

**Comment by xaizek** [comment]
There isn't, although it was asked for several time.

Until now the plan was to allow specifying arbitrary columns in `'viewcolumns'`. Using `'fillchars'` instead is something to consider, thanks.
