### ISSUE TITLE
Is there a way to make vifm execute a command on file open without quitting?

### ISSUE THREAD

**Issue by pushqrdx** [vifm/vifm#574]
I am trying to make vifm execute a command on file open without exiting vifm itself, is this possible?

**Comment by iSeeU816** [comment]
Yes. Add `&` at the end of the command, e.g. `:!open %c &`.

> To run a command in the background
    you must set it as a background command by appending & at the end of the
    commands action (e.g., :com rm rm %f &).

Reference: [vifm-:command](https://vifm.info/vimdoc.shtml#vifm-%3Acommand)

If you meant to open an editor in the terminal, then you need to be in TMux (or similar tool) session.
And must have `screen!` in your `vifmrc` file. Read more [about it](https://vifm.info/vimdoc.shtml#vifm-%3Ascreen) in the doc.

**Examples:** For one file use `:!vim %c`, and for multiple files use `:!vim -p %f`.

- `%c` acts on the file under the cursor, and `%f` on the selected items.
- `-p` in Vim command is to open tabs for each file.

---

Note to @xaizek: In the quote above, `rm` is duplicated; maybe you need to fix that.

**Comment by exoticus** [comment]
@iSeeU816 yeah i was talking about terminal use, i wonder if there's a way to execute a terminal command on file choose but without quitting vifm, also without a multiplexer.

**Comment by iSeeU816** [comment]
I'm not aware of a way, I'm afraid.

Can you give us an example of the command you want to run?

In addition, check [command macros](https://vifm.info/vimdoc.shtml#vifm-macros), maybe something there might interest you.
Like if you want the output of a command to display inside ViFM, use `%S` macro;
e.g., `:!ls %c %S`. Or use `%m` macro to see the output in menu list.

I hope that helps.

**Comment by xaizek** [comment]
There are various ways to run commands on files, but you need a multiplexer if you wish to run several interactive applications simultaneously. Please explain what kind of application you're trying to execute.

> Note to @xaizek: In the quote above, `rm` is duplicated; maybe you need to fix that.

It's not a typo. The first `rm` is internal command's name and the second one names external application.

**Comment by exoticus** [comment]
@xaizek @iSeeU816  Alright here's my use case maybe it helps with finding a way to achieve it. I am trying to use vifm in a vim terminal split so that vifm acts as a file drawer. So far it works pretty well but once a file is opened (with drop command) vifm closes. I want it to persist. Just run the drop command or some how notify vim that a file has been selected and stay open

**Comment by xaizek** [comment]
Then this is more about the plugin. There was a similar issue (vifm/vifm.vim#36) which contains a workaround using `tmux`. The plugin and probably Vifm itself need to be modified to allow passing multiple files, at the moment they are built for opening a file and disappearing (before introduction of builtin terminal it couldn't be any other way).

**Comment by pushqrdx** [comment]
i haven't found a good way around that, i wish there were a way for vifm to just notify or execute certain command on file open without actually exiting, but i am closing this anyway

**Comment by xaizek** [comment]
Didn't remember about Vim's [terminal API](https://vimhelp.org/terminal.txt.html#terminal-api) until now. If you have it (at least Vim v8.0.1647, NeoVim didn't have it the last time I checked), you can define in `vimrc` things like:
```vim
function! Tapi_Split(buf, args)
    execute 'split' a:args
endfunction
```
And then inside Vifm call that function like this to open files:
```
:!echo -e '\e]51;["call", "Tapi_Split", %"c:p]\a'
```

**Comment by pushqrdx** [comment]
@xaizek there's one issue with this, idk why it happens but vifm flickers, i think it redraws for some reason

**Comment by xaizek** [comment]
Try doing

    :!echo -e '\e]51;["call", "Tapi_Split", %"c:p]\a' > /dev/tty &

**Comment by pushqrdx** [comment]
@xaizek welp, this worked! now i am becoming greedy, i want to bind file open of Vifm to that command so that the Vifm becomes the perfect file drawer for vim
