### ISSUE TITLE
Vifm doesn't recognize fbpad to support 256 colors

### ISSUE THREAD

**Issue by AtomToast** [vifm/vifm#575]
I am trying to use vifm inside of fbpad (a framebuffer terminal) and vifm keep claiming that my colorscheme is not supported. Even though it should be

TERM is fbpad-256 and `tput colors` does return 256.

What is preventing this from working? In neovim I can even use termguicolors

**Comment by xaizek** [comment]
If `tput` works, I would say that Vifm should too (both use ncurses). Check that `:echo $TERM` inside Vifm gives you `fbpad-256`. You can also check that something like `:hi win ctermbg=123` works.

**Comment by AtomToast** [comment]
Huh, this is weird. Inside of vifm it reports to me that \$TERM is `linux`. The highlight command also doesn't work

When using `:echo $TERM` from inside of nvim it does report `fbpad-256`. Is there some difference about how the alt-screen works?

**Comment by xaizek** [comment]
> Is there some difference about how the alt-screen works?

I think alt-screen is orthogonal to color space.

Check that you don't set `$TERM` somewhere inside `vifmrc`. Maybe start Vifm with `--no-configs` option to exclude configs (quit with `:q!` to do not overwrite your `vifminfo` file).

**Comment by AtomToast** [comment]
No, nothing in there and even with --no-configs it stays as `linux`

**Comment by xaizek** [comment]
And right before invoking `vifm` `echo $TERM` says `fbpad-256` in the terminal? You can also try `TERM=fbpad-256 vifm`.

**Comment by AtomToast** [comment]
Yeah, it does and also with `TERM=fbpad-256 vifm` the behaviour stays the same. This is really bizarre

**Comment by xaizek** [comment]
Could it be that `vifm` is an alias or a function? Try `type vifm` for information and `command vifm` or `/usr/bin/vifm` to run the executable.

**Comment by AtomToast** [comment]
Oh, indeed. It is an alias for vifmrun since I am using the vifmimg script.

How does this affect this? If I escape the alias it works absolutely fine.

This should be fine for me since I intend to create my own image previews for the framebuffer with fbvis anyways.

**Comment by xaizek** [comment]
I don't see how [the script](https://github.com/cirala/vifmimg/blob/master/vifmrun) can mess it up. There are no explicit modifications of the environment.

**Comment by AtomToast** [comment]
Maybe it's somehow in the nature of it being a script? But why would that be different than being a binary

**Comment by xaizek** [comment]
A script shouldn't be treated in a special way. You can try debugging it a bit by adding `echo $TERM` inside the script in various places.

**Comment by AtomToast** [comment]
It seems to be `linux` right at the very top. Also in other scripts. No matter whether it is bin/env bash, bin/bash or with `sh` instead of bash. (that is dash for me)

Somehow scripts do seem to have a different \$TERM value

**Comment by xaizek** [comment]
What does `env | grep TERM=` show? All this looks very weird because doing `bash script.sh` shouldn't process any `.profile`/`.bashrc` files (although it might process `$BASH_ENV`).

**Comment by AtomToast** [comment]
Just running that in fbpad gives me both `TERM=fbpad-256` and also `TERM=linux`

\$BASH_ENV is empty and afaik there is no place I set TERM manually in any config in

**Comment by xaizek** [comment]
> Just running that in fbpad gives me both `TERM=fbpad-256` and also `TERM=linux`

Two values at the same time?

**Comment by AtomToast** [comment]
Yeah, in two seperate lines.
If I just look at `env` alone it contains first `TERM=fbpad-256` then the `PATH`, the `INVOCATION_ID` and then `TERM=linux`

**Comment by xaizek** [comment]
This explains it then. Two different values. `libc` uses the first one it finds (`fbpad-256`), but `bash` normalizes environment leaving only the last value and so you get `TERM=linux`. The bug is in the application that adds `TERM` entry instead of updating it. `fbpad` seems to be [to blame](https://repo.or.cz/fbpad.git/blobdiff/b43126f3034dc3e916299cbf2be9fc829f8fe796..52b6bed1d8ce6357992e8fff6d53fef3c9fb047c:/term.c) (`TERM` that's already in `environ` isn't skipped on copying).

**Comment by AtomToast** [comment]
Indeed, if I actually `export TERM=fbpad-256` before launching fbpad I have two `TERM` both set to 256-color and the vifmrun script works fine.
I know this is out of scope of this project but do you reckon there is an easy fix to make it overwrite or delete the old TERM value? Otherwise I'll try contacting the dev of fbpad

**Comment by xaizek** [comment]
Vifm run via `vifmrun` sees only one value and can't do much. fbpad is the place to fix this.

**Comment by AtomToast** [comment]
Alright, I think then this issue could be closed
