### ISSUE TITLE
Resizing terminal cause panic when moving large file

### ISSUE THREAD

**Issue by aca** [vifm/vifm#576]
It happens quite often when moving large files between different volumes.

```
(hit i for details) Moving: 1 of 2; 1.2 G/54 G ( 2%) bigfile.txtvifm: ui/cancellation.c:57: ui_cancellation_reset: Assertion `!ui_cancellation_enabled() && "Can't reset while active."' failed.
                       fish: “vifm” terminated by signal SIGABRT (Abort)
```
```
134 λ  vifm --version
Version: 0.10.1
Git info: built out of repository
Compiled at: Jul 26 2020 19:06:34

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution

λ  uname -a
Linux rok-tp6 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux
```

**Comment by xaizek** [comment]
To reproduce the issue you just start a long operation and resize the terminal or create new tmux windows?

**Comment by aca** [comment]
@xaizek  both. When resizing terminal and creating new tmux pane at current window.

**Comment by xaizek** [comment]
Looks like I called panes "windows" there, I meant doing splits.

I guess tmux doesn't have much to do with it. Can you reproduce the panic outside of tmux? Also, both Vifm's panes contain just lists of files without previews or trees or anything? (I can't reproduce it, hence the guessing.)

**Comment by aca** [comment]
@xaizek you are right, it's not tmux issue. Just resizing cause panic when moving larger than 20G file.
tested on alacritty, xterm.

**Comment by aca** [comment]
Here's my whole vifmrc. It's not so different from example configuration.
https://github.com/aca/dotfiles/blob/master/vifm/.config/vifm/vifmrc

**Comment by xaizek** [comment]
Thanks for reporting! Fixed it.
