### ISSUE TITLE
User mappings aren't resolved by suggestions

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#578]
I separated the configs of vifm into several files. One file includes all of my keybindings,. including this:
```im
noremap w <C-w>
```
This is a part of my file-hierarchy:
`~/.config/vifm/vifmrc`
`~/.config/vifm/settings/mappings.vifm`
So in `vifmrc` is this line which includes the mapping:
```vim
" mappings
source ~/.config/vifm/settings/mappings.vifm
```
If I set the keybinding in the vifmrc instead, than I can use `w` as `<C-w>` as expected. So do I have to set everything in the vifmrc or is it possible to split the vifmrc into different files? If yes: What am I doing wrong?

**Comment by xaizek** [comment]
You can split it whichever way you like. It's something else that's going wrong. See if menu on `:nmap w` shows anything.

**Comment by TornaxO7** [comment]
Ok, so I have this in my `mapping.vifm`:
```
nnoremap w <C-w>
```
And this is the output of `:nmap w`:
![image](https://user-images.githubusercontent.com/50843046/90429028-3a543e00-e0c5-11ea-9f75-d95ce2177a5e.png)

When I'm typing `:nmap <C-w>` than I'm getting this:
![image](https://user-images.githubusercontent.com/50843046/90429067-4b04b400-e0c5-11ea-93e0-bceef9a7f0d5.png)

**Comment by xaizek** [comment]
Is `source ~/.config/vifm/settings/mappings.vifm` located before `nnoremap w :view<cr>` in `~/.config/vifm/vifmrc`? One can cancel the other.

**Comment by TornaxO7** [comment]
Well `nnoremap w :view<cr>` isn't even in my `~/.config/vifm/vifmrc`. I just put it there to test if the mapping works if I put it directly into my `vifmrc`.

**Comment by xaizek** [comment]
Can you provide a minimal example that doesn't work? I did this:
```term
$ tree ~/.config/vifm
~/.config/vifm
├── settings
│   └── mappings.vifm
└── vifmrc
$ cat ~/.config/vifm/vifmrc 
" mappings
source ~/.config/vifm/settings/mappings.vifm
$ cat ~/.config/vifm/settings/mappings.vifm 
noremap w <C-w>
```
And everything works.

**Comment by TornaxO7** [comment]
Oh god.... I found the issue....
![image](https://user-images.githubusercontent.com/50843046/90547311-9a151c80-e18b-11ea-9d3a-1556d2abd2d2.png)
This was in my `mappings.vifm` as well below the `noremap w <C-w>`... I'm sorry for that.... Anyway the preview panel doesn't work, when I'm typing `w`. <br>
When I'm typing `<C-w>` than this pops up on my right panel:
![image](https://user-images.githubusercontent.com/50843046/90547523-f2e4b500-e18b-11ea-816a-3fe8dc8d5dd7.png)
But this doesn't popup up when I'm typing `w`, do you have an idea what I should do?
<br>
Should I change the title, create a new issue or should I ask that in the Q&A of `vifm`?

**Comment by xaizek** [comment]
Thanks. Resolving user mappings wasn't done for suggestions. Fixed it.
