### ISSUE TITLE
Bug: Mid-cancel of group mapping suggestions execute last pressed key

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#580]
Hello,

**Note:** This was produced on a fresh ViFM setup.

## Mid-cancel of group mapping suggestions

1. Add this to `vifmrc` config:

    ``` vim
    " Show directory history.
    nnoremap ,hd :hist d<cr>
    " Show command line history.
    nnoremap ,hc :hist c<cr>
    ```

2. `:reload`.
3. Press `,h` which shows this group mapping suggestions pop-up.
4. I changed my mind and I don't want to run any command, so I press `<esc>` key
   to dismiss suggestions pop-up; `<c-c>` acts the same too.

**Expected Results**

Suggestions pop-up should dismissed and nothing happen.

**Actual Results**

Last pressed key, which here is `h`, sent to ViFM and do whatever it programmed
to do. In our example here, ViFM will jump back to parent directory of current
path.

This annoyed me a lot as I expect `<esc>` to cancel whatever in-front of me.

**A workaround**

Add a new map for each group mapping which suffixes with `<esc>` key to do
nothing `<nop>`. Example: `nnoremap ,h<esc> <nop>`.

Thank you.

## Software info

- macOS Mojave 10.14.6
- ViFM 0.10.1 (stable); 0.10.1-713-g93654865dde5 (master).

**Comment by xaizek** [comment]
Hi,

I don't see a bug here. Hitting <kbd>Esc</kbd> or <kbd>Ctrl+C</kbd> doesn't cancel input, it just resolves ambiguity and starts processing of keys. In this case execution of <kbd>,</kbd>, <kbd>h</kbd> and <kbd>Esc</kbd> is triggered. <kbd>,</kbd> and <kbd>Esc</kbd> just don't have any visible effect for you in this case and so it appears that only <kbd>h</kbd> is executed.

**Comment by iSeeU816** [comment]
I thought ViFM should handle custom group mapping how it handled built-in ones.
For example, hitting `gu` then `<esc>` will not trigger `u` as the undo command.

But after reading you response, I tested `gug` then `g` (which doesn't included
in this group mapping) and the cursor jumps to the top of items' list.

I think will use my workaround to handle this.

Sorry for the noise.

**Comment by xaizek** [comment]
> I thought ViFM should handle custom group mapping how it handled built-in ones.

I believe it does and that this matches behaviour of Vim (at least I don't remember significant differences).

> For example, hitting `gu` then `<esc>` will not trigger `u` as the undo command.

That's because there is no <kbd>g</kbd> command. This leads to <kbd>gu</kbd> being glued and discarded together.

> But after reading you response, I tested `gug` then `g` (which doesn't included
> in this group mapping) and the cursor jumps to the top of items' list.

Note that <kbd>gugg</kbd> is a valid command and you probably changed case of some files. List of suggestions after <kbd>gug</kbd> doesn't include selectors though, might need to fix this.

**Comment by iSeeU816** [comment]
Thank you for the info.

Don't worry, I was testing on dump files. My test was on a lowercased filename
so I didn't notice that last `g` changed the item's case.

What did you mean by `selectors`?

**Comment by xaizek** [comment]
> What did you mean by `selectors`?

Motions and text objects like `gg`. I collectively call them selectors in Vifm because they select files to be operated on.
