### ISSUE TITLE
Feature: Percentage of cursor position in list and preview

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#581]
Hello,

In Emacs, there is an indicator of cursor position in the buffer, Emacs refer to
it as `Buffer Relative Position`. ViFM has similar idea, which is what in the
bottom right in command line bar. But that only show the cursor position/the
total.

It will be helpful to have something like what Emacs provides, which is this:

- **Top:** The cursor position is in the top portion of the window.
- **N%:** A percentage of how the cursor position related to the top of the window.
- **Bot:** The cursor position is in the bottom portion of the window.
- **All:** When the content of the window is all visible.

This indicator could be positioned next to `position/total` but left side of it,
or could be a variable to be positioned by the user in status line. I said left
side so numbers don't look they belong to each other; I mean something like
`127/429 27%`, I find `27% 127/429` is better. Maybe separate them with Unicode
character, e.g., `27% ● 127/429`; `Top ● 1/429`.

I'm requesting this because I want to know my position when previewing a file.
Also, it could be helpful to know how long current path list is.

If only percentage can be implant, that will be enough for me.

Thank you.

## Software info

- macOS Mojave 10.14.6.
- ViFM 0.10.1 (stable); 0.10.1-713-g93654865dde5 (master)

**Comment by xaizek** [comment]
It's `10/200 Top` in view mode, because width of the percentage part is fixed. In the ruler you can place it anywhere using `'rulerformat'`.
