### ISSUE TITLE
Nerdfont support

### ISSUE THREAD

**Issue by Laks0** [vifm/vifm#582]
Hi, I've been using Vifm for a wile and i tried to add devicons using [this script](https://github.com/cirala/vifm_devicons), but vifm looks all messed up.
![Screenshot_20200820_122709](https://user-images.githubusercontent.com/35859490/90792144-7ca59700-e2e0-11ea-8f8b-866b4730d952.png)
I'm using Hack Nerd font and devicons works great in vim, I don't understand why they don't work in vifm.

**Comment by xaizek** [comment]
Hello,

Looks like an encoding issue. Does encoding of your configuration file match encoding of the terminal?

**Comment by Laks0** [comment]
Sorry for the ignorance but what exactly should I be checking? The terminal is encoding in UTF-8, but is there a separate encoding configuration for vifm? I couldn't find anything in the vifmrc

**Comment by xaizek** [comment]
Look at the output of `:set fenc?` when you open configuration file with Nerdfont symbols in Vim.

And maybe check output of `locale` in your terminal. It should also be UTF-8.

**Comment by Laks0** [comment]
Sorry, my locale was wrong, seting it to US-utf8 fixed it. Thanks!
