### ISSUE TITLE
how can i increase time display for suggestion keyboard?

### ISSUE THREAD

**Issue by windwp** [vifm/vifm#584]
Hi
I use this mapping 
``` vim
nnoremap <space>n :!touch<space>
nnoremap <space>N :mkdir<space>
nnoremap <space>x :!chmod +x %f<cr>
nnoremap <space>o :!%f && read <cr>
...
```
When i press a <space> key it display a suggestion keyboard in another panel. but it is too short.
I only want to increase time display it. it will better if it only hide when we press another key. Thank

**Comment by xaizek** [comment]
Hi,

See `delay:` in [`'suggestoptions'`](https://vifm.info/vimdoc.shtml#vifm-%27suggestoptions%27).

> it will better if it only hide when we press another key.

If it disappears, it means that a command is executed (<kbd>space</kbd> in this case). You can use `<wait>` to prevent that:
```vim
nnoremap <wait> <space>n :!touch<space>
...
```

**Comment by windwp** [comment]
many thank

**Comment by windwp** [comment]
@xaizek  is there anyway to add a description for keymap on suggestion box.
I see the default keybinding have a description but how do i do it on my keybinding?

**Comment by xaizek** [comment]
No, there isn't at the moment.

**Comment by windwp** [comment]
ok thank
