### ISSUE TITLE
Directory sometimes disapears from view

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#585]
I have directory `~/VirtualBox VMs` and it disapears from start to start. Also a got situation, when on first panel it present, but not on second:
![изображение](https://user-images.githubusercontent.com/20644917/92039236-4a764980-ed64-11ea-963f-52275e86dd38.png)
In `modline-competion` works, and competes this path for me:
![изображение](https://user-images.githubusercontent.com/20644917/92039297-611ca080-ed64-11ea-9707-35ef740ba9c9.png)

I don't use _filters_, (one time i switched `zo`). On switching `zo`/`zm` state keeps (if folder gone - it no show, if present - it stay shown).

`stat VirtualBox\ VMs/ Nextcloud/ GOG\ Games/ go/`:
```
  File: VirtualBox VMs/
  Size: 82        	Blocks: 0          IO Block: 4096   directory
Device: 33h/51d	Inode: 41294       Links: 1
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ presfil)   Gid: ( 1001/ presfil)
Access: 2020-07-21 19:39:53.312159631 +0300
Modify: 2020-07-21 22:49:02.225337954 +0300
Change: 2020-07-21 22:49:02.225337954 +0300
 Birth: 2020-04-27 13:18:53.868206712 +0300
  File: Nextcloud/
  Size: 10        	Blocks: 0          IO Block: 4096   directory
Device: 33h/51d	Inode: 101931      Links: 1
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ presfil)   Gid: ( 1001/ presfil)
Access: 2020-07-21 19:39:53.305492964 +0300
Modify: 2020-07-10 01:05:48.138341048 +0300
Change: 2020-07-10 01:05:48.138341048 +0300
 Birth: 2020-04-27 20:14:41.603056594 +0300
  File: GOG Games/
  Size: 16        	Blocks: 0          IO Block: 4096   directory
Device: 33h/51d	Inode: 2440009     Links: 1
Access: (0700/drwx------)  Uid: ( 1000/ presfil)   Gid: ( 1001/ presfil)
Access: 2020-08-10 22:00:32.297470546 +0300
Modify: 2020-08-10 22:00:32.297470546 +0300
Change: 2020-08-10 22:00:32.297470546 +0300
 Birth: 2020-08-10 22:00:32.297470546 +0300
  File: go/
  Size: 6         	Blocks: 0          IO Block: 4096   directory
Device: 33h/51d	Inode: 2673174     Links: 1
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ presfil)   Gid: ( 1001/ presfil)
Access: 2020-08-26 22:13:51.065692208 +0300
Modify: 2020-08-26 22:13:51.065692208 +0300
Change: 2020-08-26 22:13:51.065692208 +0300
 Birth: 2020-08-26 22:13:51.065692208 +0300
```

There are a few more directories with spaces in their names, but with them everything is ok.

---

`Vifm` build:
```
Version: 0.10.1
Git info: built out of repository
Compiled at: Jul 26 2020 19:06:34

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
Not sure why that could happen. I'll take a close look at the code, but that might lead nowhere. I have exactly the same directory and it seems to always be there.

> Also a got situation, when on first panel it present, but not on second:
> On switching `zo`/`zm` state keeps (if folder gone - it no show, if present - it stay shown).

This makes it even weirder. You can try running `:filter?` just to make sure you didn't exclude the file by accidentally pressing <kbd>zf</kbd>.

***

See https://github.com/vifm/vifm/issues/557#issuecomment-642801973 about the bug with color of the other pane (it's not supposed to be white or underlined).

**Comment by PRESFIL** [comment]
It's looks like i was typed `zf` accidentally some time ago. You was right, thanks.
And I was still waiting to see if it was a permanent bug or not. ;D Looks like it just _permanent filter_.

**Comment by PRESFIL** [comment]
Permanent filter can be pane-specific?

**Comment by xaizek** [comment]
> Permanent filter can be pane-specific?

All filters are pane-specific except that setting them in `vifmrc` applies their values to all panes.
