### ISSUE TITLE
Is there any way to add an expanded macro to a map?

### ISSUE THREAD

**Issue by programandala-net** [vifm/vifm#586]
I'd like to define a map to go to a variant of the current directory, edited by the user. Such a map is useful when you need to go to another branch of a parallel identical hierarchy, e.g. from </path/to/AAA/0/1/2/3/4/5/> to </path/to/BBB/0/1/2/3/4/5/>. In those cases it's faster to edit the current path than to navigate all the way up and down.

Say I need the following map, but forcing `%d:p` to be *expanded before building the command*, in order to let the path be edited by the user:

```
:nnoremap C :cd %d:p
```

I've read the documentation about macros, but found no way to expand a macro that way.

**Comment by xaizek** [comment]
There might be a way, but have you seen [`:cds` command](https://vifm.info/vimdoc.shtml#vifm-%3Acds)? You should be able to use:
```
:cds AAA BBB
```
to get the desired behaviour.

**Comment by programandala-net** [comment]
I didn't know the `cds` command. It's not exactly the same than editing the path by hand, but it will be very useful to me in many cases. Thank you.

Nevertheless, I think a syntax to expand macros explicitily would be useful to build commands and let the user edit them before pressing Enter.

**Comment by xaizek** [comment]
> Nevertheless, I think a syntax to expand macros explicitily would be useful to build commands and let the user edit them before pressing Enter.

In Vim one does this via expression register, I guess the same is needed here. Would look like:
```vim
:nnoremap C :cd <c-r>=expand('%d:p')<cr>
```

**Comment by programandala-net** [comment]
2020-09-11 09:56: xaizek escribió/skribis/wrote/scrit:

> In Vim one does this via expression register, I guess the same is
> needed here. Would look like:
>
> ```vim
> :nnoremap C :cd <c-r>=expand('%d:p')<cr>
> ```

Yes, it would be great to do it exactly like Vim. I didn't remember that
Vim function.

-- 
Marcos Cruz
http://programandala.net

**Comment by xaizek** [comment]
Added expression register in 5ecaeaab08a6f4fc81ae11bc7763e193ba4cf395, so the mapping above will work in the next release.

Not sure why I didn't mention this way of doing it earlier:
```vim
nnoremap C :cd <c-x><c-x>d
```
