### ISSUE TITLE
Sixel image wont be cleared workaround needed

### ISSUE THREAD

**Issue by flux242** [vifm/vifm#588]
Hello,

I'm testing sixel support implemented for libvte (not officially released yet)

first  problem is that previous picture leftovers are visible in the preview if the new image height is smaller. Second problem is that the last viewed picture stays behind the text after leaving the preview mode. If terminal window is resized then image disappears. 

So, on what side this problem needs to be addressed - on vifm or on the terminal?
Is there a workaround on vifm side? Like forcing vifm to clear the whole pane on the new file selection or at least on leaving the preview mode

I'm using
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ img2sixel -S -w $((%pw*9)) %c %pd,
         \ convert -identify %f -verbose /dev/null
``` 
note $((%pw*9)) above. The terminal cell width is 9 and not 8

**Comment by xaizek** [comment]
Hi,

It works fine as is in `xterm` and `mlterm`, so my *guess* is that `libvte` needs to do clearing in this case. 

You can use `%pc` to specify clear command (e.g., try with `clear`: append ` %pc clear` to your `:fileviewer` command). The command is invoked on leaving preview mode or when you go from viewing text to viewing graphics or vice versa.

#419 mentions that [patched st](https://github.com/charlesdaniels/st) has similar issue. Using `%pc clear` or `%pc reset` doesn't fix it for me. Adding code to do extra clearing doesn't help either. So I guess it's up to the terminal to drop the image at the right time.

**Comment by flux242** [comment]
you mean like this:
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ img2sixel -S -w $((%pw*9)) %c %pd %pc clear
```
no, that doesn't work

I don't know how do you clear the area but I have tried to erase a line using escape sequences https://imgur.com/l3v6EEx.png

The printf sequence just below the sixel picture didn't clear the line inside of the picture but the one at the bottom did. So I believe that the picture can't just simply be cleared.

Can there be another type of a workaround I can have on the vifm side?
Those vte people are really conservative and they were rejecting sixel integration since 2017 simply because they don't like sixel format. Now I'm happy that something's happening even in its current form

**Comment by xaizek** [comment]
Since using certain escape sequences work for you, you can try emitting them in `%pc`.

I've tried with that `st` and `wclear()` call seems to help. I guess it might work for `libvte` as well, but it's relatively heavy-weight way of clearing the screen. I mentioned potential `'previewoptions'` in  #481 (and actually forgot about it), some of its values control presence of `wclear()`.

**Comment by xaizek** [comment]
Now you can do:
```vim
:set previewoptions=hardgraphicsclear
```
It does make images disappear in patched `st` (there are other problems with it, but those are implementation issues).

**Comment by savchenko** [comment]
> :set previewoptions=hardgraphicsclear

In case someone stumbles upon this issue: `previewoptions` exists in man page since ~v0.10, however the option itself is not accessible in any released version just yet.

Compiling from master (`v0.11-274-gcce811cd9f8b` at the time of writing) makes it usable.

**Comment by xaizek** [comment]
> `previewoptions` exists in man page since ~v0.10

I don't think so, documentation might be outdated sometimes, but it can't contain things from the future. Also `previewoptions` would be [here](https://vifm.info/manual.shtml) (version for v0.11) then. Maybe you looked at a man-page that doesn't match your binary. `ChangeLog` should be a reliable way to see in what version something was added.

**Comment by savchenko** [comment]
@xaizek ,

OK, think I know what has happened :) `vifm` is installed from the official Debian repository via normal `apt install vifm`:

```bash
$ vifm --version
Version: 0.10.1
Git info: built out of repository
```

```bash
$ apt show vifm # trimmed
Package: vifm
Version: 0.10.1-4
Maintainer: Ondřej Nový <onovy@debian.org>
```

...However...


With manpage opened in vim:
```vim
:cd %:p:h<cr>:pwd<cr>
/home/savchenko/.vim/plugged/vifm.vim/doc/app 
```
Further, header states:
```
*vifm-app.txt*    For Vifm version 0.11  Last change: 2021 Jan 21
```

Mystery solved.
