### ISSUE TITLE
A simpler use of visual amend?

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#589]
Say I have a directory with some hundreds of files from which I want to delete some of them. For example, the ones marked with `X`:

```
  ...
X file1
  file2
X file3
X file4
X file5
X file6
  file7
X file8
  ...
```

Since there is no obvious pattern in the files to be selected, I use visual mode and amend to manually select them. However, I find it a bit cumbersome to {<kbd>v</kbd>(select range 1)<kbd>Enter</kbd>(skip to range 2)<kbd>av</kbd>(select range 2)<kbd>Enter</kbd>...}. I believe it would be easier for users to replace both <kbd>Enter</kbd> and <kbd>av</kbd> with a single <kbd>v</kbd>. Users can still reject a selection with <kbd>Escape</kbd> or <kbd>Ctrl+C</kbd>.

Is my suggestion any good? And as always, thanks a ton for Vifm!

**Comment by xaizek** [comment]
That would be quite significant change in behaviour, which also differs from how Vim treats selection. I don't think the builtin is worth changing, but you can easily remap it the way you want:
```vim
nnoremap v av
vnoremap v <cr>
```
Also you might want to use `nnoremap T tj`, select most files and then unselect a few or use `:select`/`:unselect` with patterns.

**Comment by DieSpinne** [comment]
Thank you Xaizek, I guess you are right. I have many mappings but totally forgot I could map that too!
