### ISSUE TITLE
Virus reported by Panda Antivirus when trying to run Vifm beta version 0.11

### ISSUE THREAD

**Issue by nandox** [vifm/vifm#590]
Virus reported by Panda Antivirus when trying to run Vifm beta version 0.11

![image](https://user-images.githubusercontent.com/7716558/93382508-6fb48e80-f81f-11ea-913b-cc7d5f989e6a.png)

**Comment by xaizek** [comment]
Not the first false positive.  There are two more for all three files on VirusTotal:
 * [win32](https://www.virustotal.com/gui/file/e14fd44083b57b7e7c2eacb7a3ef29ed85ed21db9251741be79570f641432c1a/detection)
 * [win-32-se](https://www.virustotal.com/gui/file/53da898a5ce1b72a900f8ef215309c4ae77da2554be2db38a971521e2eee83f8/detection)
 * [win-64-se](https://www.virustotal.com/gui/file/4ac74de72d577b92614f0e4524eeef4d79404869c9288c32305f6261ce2ef18f/detection)

Probably heuristics went wrong. If there was an actual issue, number of hits would be much higher.

**Comment by xaizek** [comment]
I checked that the executable in the archive Panda is complaining about is identical to the one I have on my Linux machine, where it was build. I'd be very surprised if my cross-build environment had a virus in it.
