### ISSUE TITLE
Python error when opening program in background on windows

### ISSUE THREAD

**Issue by bartlibert** [vifm/vifm#592]
On windows, my vicmd is set to `gvim\ -f &`, this used to work exactly as expected, but from vifm 0.11 on, this give a python error:

```
Background Process Error
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized    
OSError: [WinError 6] The handle is invalid      
Current thread 0x000025b0 (most recent call first):
<no Python frame> 
```

If I change the command to `gvim\ -f` it's all ok.

I have the same issue with any command that has a "&" at the end.

Extra observation, I have the following mapping in my vifmrc:

```
nnoremap o :!gvim --remote-tab-silent %f &<cr>
```
I get the same error if I press "o" on a file, however, if gvim is already running (so vifm does not have to start it again), the issue is gone and the file is opened in the already open gvim instance.

My system:
OS: Windows 10 (unfortunately I'm forced to use this at work)
Vifm version: 0.11 (issue does not occur on vifm 0.10)
Python version: 3.8.6

**Comment by xaizek** [comment]
> (issue does not occur on vifm 0.10)

What about 0.10.1? Or that's the version you meant?

I suspect this is due to #521 being fixed. I've installed Python 3.8.6 and I don't get the error, so it could be that it was always there for you, you just didn't know until now.

> I have the same issue with any command that has a "&" at the end.

*Every* command complains about Python? That would be very weird. Even things like `:!echo bla &`?

As a workaround you might try ignoring errors by appending `2>NUL`.

**Comment by bartlibert** [comment]
I'm sorry, it was indeed 0.10.1 that I meant.

And not every command complains apparently, just the ones I tried, but for
example the echo one does not give the issue.

The 2>NUL workaround removes the error dialog, but the program does not
open. Might be related to python being installed via scoop, I'll check a
bit further.

Op vr 25 sep. 2020 om 18:47 schreef xaizek <notifications@github.com>:

**Comment by bartlibert** [comment]
I did a full uninstall and reinstall of python and the issue seems to be gone now. Sorry for the issue, but vifm seemed a likely culprit, while it was just exposing the error.

**Comment by bartlibert** [comment]
The issue reappeared and I found out it was just "fixed" before due to some python-based plugin I had removed from vim. I did some further digging and the minimal reproduction scenario on my side is:

- execute `:!gvim &`  in vifm
- execute `:pythonx print('test)` in gvim

I searched around a bit and found [this](https://github.com/ninia/jep/issues/242), indicating it could be related to stdout and stderr not being correctly setup or initialized.

**Comment by xaizek** [comment]
Still can't reproduce. By the way, do you even need `gvim` here or `:!python &` also fails?

> I searched around a bit and found this, indicating it could be related to stdout and stderr not being correctly setup or initialized.

Or stdin. However, the code sets all three of them (stdin = stdout = NUL, stderr = pipe). And they seem to be working fine. I looked at Python sources and `can't initialize sys standard streams` corresponds to a whole bunch of errors, so I don't know what exactly goes wrong.

**Comment by bartlibert** [comment]
I I just do `!python &', I get another error:

```
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Op wo 30 sep. 2020 om 14:16 schreef xaizek <notifications@github.com>:

**Comment by xaizek** [comment]
That's not an actual error. It initialized itself successfully and printed a prompt. It's weird that `gvim` in the middle changed the outcome. Although `gvim` uses Python as a library, which could use a different code path. What's your Vim version?

**Comment by bartlibert** [comment]
I'm using Vim 8.2, with patches 1-1770. +python/dyn and +python3/dyn (but
only python3 is installed)

Op wo 30 sep. 2020 om 14:42 schreef xaizek <notifications@github.com>:

**Comment by xaizek** [comment]
Vim seems to be the reason, see  vim/vim#7053.

**Comment by bartlibert** [comment]
Thanks for this great investigation and apologies (again) for blaming it on vifm (again) ;)

**Comment by seisdr** [comment]
im trying to run program that runs fine with wine but using vncserver i get this error 
```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle

Current thread 0x00000009 (most recent call first):
```
no idea what is going on program program has python files i dont know how to update python  like copying files?

**Comment by xaizek** [comment]
@selsdr, updating python probably won't fix it. You need to make sure that standard streams are connected to a terminal somehow. I don't know how vncserver runs commands and can't really help.
