### ISSUE TITLE
Please help with image preview using viu

### ISSUE THREAD

**Issue by Crandel** [vifm/vifm#593]
There is a cool cli tool [viu](https://github.com/atanunq/viu) for displaying images in terminal and I woul like to use it as preview tool in vifm.
I use [tilix](https://github.com/gnunn1/tilix) terminal
Here how it looks in my terminal
![Grimshot 2020-09-29 10-14-56](https://user-images.githubusercontent.com/4005032/94531978-cd3bd880-022c-11eb-93c5-b20e3797dccb.png)

And here how it looks in **vifm**
![Grimshot 2020-09-29 10-14-09](https://user-images.githubusercontent.com/4005032/94532119-fb211d00-022c-11eb-807b-727aca8076f9.png)

I use this lines in my `~/.config/vifm/vifmrc` file

```
fileviewer *.png,*.jpeg,*.jpg
  \ viu -w %pw -h %ph -s %c
```

**Comment by Crandel** [comment]
This issue could help probably
https://github.com/atanunq/viu/issues/6

**Comment by xaizek** [comment]
You can try (in case truecolor gets in used):
```vim
fileviewer *.png,*.jpeg,*.jpg
  \ env -u COLORTERM viu -w %pw -h %ph -s %c
```
If that doesn't work, please attach sample output of the tool, e.g.:
```
COLORTERM= viu -w 50 -h 50 -s ~/Pictures/wallpaper.jpg > wallpaper.esc
```

**Comment by Crandel** [comment]
Your solution works perfectly, thank you very much. I guess we could update wiki and include this tool as an option, because it easy to install and works perfectly even without clearing terminal
