### ISSUE TITLE
lstrash does not work when trashdir is set to a symbolic link

### ISSUE THREAD

**Issue by chongchonghe** [vifm/vifm#594]
On my macOS where I'm the only user, trashdir is default (~/.local/share/Trash), and it has files/ and info/, which makes sense. However, on my cluster running scientific linux running vifm 0.11 where I set trashdir to /lustre/my_name/Trashdir, deleted files have 3-digit number in front. 'Restore' and 'undo' work as expected. However, there are no files/ or info/ directories. I understand the 3 digits are there to distinguish files with same name, but how can vifm remember the original path of a file that I deleted? I need to understand how it works before I can trust it to deal with my important data.

Also, when trashdir is set to a symbolic link, lstrash does not work: no files in Trash, although deleted files are in trashdir. I would expect it to work seamlessly.

Many thanks for creating such a great tool!

**Comment by xaizek** [comment]
Metadata on files in Vifm's trash is stored as part of application's state (`vifminfo.json` file since v0.11).

> Also, when trashdir is set to a symbolic link, lstrash does not work: no files in Trash, although deleted files are in trashdir. I would expect it to work seamlessly.

Thanks, looks like you've found a bug. Some care was taken to handle broken links inside trash directories and doesn't play well with trash itself being a symbolic link.
