### ISSUE TITLE
highlight partial search results

### ISSUE THREAD

**Issue by cevhyruz** [vifm/vifm#595]
Is it possible to highlight partial results of the regex search while typing? 
I tend to do this with nerdtree when i just want to quickly find a file/directory without having
to always hit enter. as hitting enter in vifm will select all matches

**Comment by xaizek** [comment]
> Is it possible to highlight partial results of the regex search while typing?

Maybe you have [`'incsearach'`](https://vifm.info/vimdoc.shtml#vifm-%27incsearch%27) turned off?

> as hitting enter in vifm will select all matches

Only if [`'hlsearch'`](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27) is set.

**Comment by cevhyruz** [comment]
Oh I forgot about that. will close this now. :)
