### ISSUE TITLE
Terminal commands from vifm

### ISSUE THREAD

**Issue by Nova-Striker** [vifm/vifm#596]
How/Is it possible  to do terminal commands while in vifm like creating a new file while Vifm is opened using 
```
:touch newfile.txt 
```

**Comment by xaizek** [comment]
There is internal [`:touch` command](https://vifm.info/vimdoc.shtml#vifm-%3Atouch), so `:touch newfile.txt` is a valid command that creates a file. You can execute an arbitrary command using [`:!`](https://vifm.info/vimdoc.shtml#vifm-%3A%21) as in Vim:
```vim
:!your command
```
