### ISSUE TITLE
"--remote -c cd dir" misbehaves for right panel

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#597]
1. Start a Vifm instance.
2. Navigate both panels to some random directories.
3. Leave the focus on the right panel.
4. In a new terminal, issue `vifm --remote -c cd ~`.

Expected: Right panel lists the user home directory.
Verified: Both right and left panels list the user home directory.

Curiously, if the focus were on the left panel, only the left panel directory would change (as expected).

**Comment by xaizek** [comment]
Your command should be `vifm --remote -c 'cd ~'` (mind the quotes).

`-c cd ~` executes `:cd` in the current pane and sets path of the left pane to `~`. If the left pane is active, you change directory to `~` twice for the left pane.

**Comment by DieSpinne** [comment]
Oh, shame on me! You are right, sorry and thanks for your time.
