### ISSUE TITLE
Confirmation dialog/prompt for file overwriting

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#599]
I miss a dialog in Vifm to confirm or reject the overwriting of a file, such as this one Midnight Commander features:

![12-19:21:15](https://user-images.githubusercontent.com/62444221/95795317-728c8d00-0cc0-11eb-9d1a-9c74381aa855.png)

In the picture, trying to copy all the regular files from the left panel to the right panel, which already contains those files, prompts for confirmation for each clash (`fil` and `file`). That is especially handy when various tagged files are being copied. In Vifm, unless I missed something, either you don't overwrite any file with `:copy` (and in case of a clash no file is copied) or overwrite all files with `:copy!`. The dialog with `Yes/No/All` would be a great addition, in my opinion, so I leave this suggestion to the development team.

Thanks for Vifm!

**Comment by yusufaktepe** [comment]
See https://github.com/vifm/vifm/issues/573#issuecomment-674037371
