### ISSUE TITLE
Flag for executing command with selected file/directory

### ISSUE THREAD

**Issue by rosshadden** [vifm/vifm#60]
Do you think it would be useful to have a flag for running a passed-in command with a selected file?  That is, something like `vifm --command="readlink -f %f"`, or `vifm --command="cp %c ."`.  This command would override what happens when you "open" a file with vifm, via `<enter>` or `l`, et al.

Where I see this possibly being useful is in using vifm from other programs, as a method of choosing a file or folder for some purpose to be defined by that program.  I don't really have a great example... it would be perfect to launch vifm in place of the native OS file picker (used by Chrome, Firefox, etc.).  But I don't think that's possible, and thus is not a good example.

**Comment by xaizek** [comment]
It's there now, and it's called `--on-choose`. There are also `--choose-files <path>|-` and `--choose-dir <path>|-`. `--on-choose` somewhat clashes with those options, but it's more flexible, while effect of those options is more well defined and doesn't depend on anything except vifm itself.

**Comment by EvilDroidMax** [comment]
Sorry for reopen this issue. But do you know how to make this work with browser for them to open the folder and and select the file (If possible). Right now chrome and firefox open my home dir when I download files and click "Open folder"
