### ISSUE TITLE
`:media` command doesn't work

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#600]
Hello! I saw this part about `media`: https://vifm.info/vimdoc.shtml#vifm-%3Amedia
Now I've tried to use it by entering this in `vifm`: `:media` but this comes up:
```vim
No media found
```
Why am I getting this? I even tried it out when I was inside a directory which got mounted.

**Comment by xaizek** [comment]
Hi,

if you're not getting an error, I suspect that you have more than one device manager installed and Vifm ends up using the "wrong one". The interaction is handled by [`vifm-media` script](https://github.com/vifm/vifm/blob/master/data/vifm-media). You can try editing it to leave only `udisks2` for example (copy the file `'mediaprg'` points to (or copy from the link above), edit and set the option explicitly to use your version).

**Comment by TornaxO7** [comment]
Well actually I don't think that I even have a device manager (at least I couldn't find anything about device manager for Arch Linux).
Where do I have to put the script file? Under `~/.config/vifm/scripts`?

**Comment by TornaxO7** [comment]
Ok I saw that the `vifm-media` script is in `/usr/share/vifm/vifm-media` and I don't have the `udisks` command.

**Comment by TornaxO7** [comment]
Strange.... if I comment everything out in `/usr/share/vifm/vifm-media` except this line:
```bash
echo "Hello there! - General Kenobi"
```
and type `:media` in `vifm`, than this pops up:
```bash
No media found
```

**Comment by xaizek** [comment]
https://vifm.info/vimdoc.shtml#vifm-%27mediaprg%27

> list subcommand is assumed to always succeed, while exit code of mount
> and unmount is taken into account to determine whether operation was
> performed successfully.

However, if you didn't have `udevil`, `udisks` or `udisks2` installed, you'd still got an error message. You just need to write it to the error stream:
```bash
echo "Hello there! - General Kenobi" 1>&2
```

**Comment by TornaxO7** [comment]
Yeah! Using `echo "Hello there! - General Kenobi" 1>&2` works! By the way I found out that I've `udisks2` installed on my system.

**Comment by xaizek** [comment]
`list` is the argument for the script, not for the command.

**Comment by TornaxO7** [comment]
Ok, so the issue is somewhere in the last `elif` clause, because if I add `echo "Hello there! - General Kenobi" 1>&2` under this `elif` clause:
```bash
elif python2 -c 'import dbus' &>/dev/null ||
     ${python3:=python3} -c 'import dbus' &>/dev/null &&
     type -P udisksctl &>/dev/null; then
    python=${python3:-python2}
```
than it's printed out. I'll take a look at the python code and try to figure out what causes the issue if I have some time.

**Comment by TornaxO7** [comment]
I'm actually pretty irritated.... How does the script work? Why do I need to use `<<<` to let it print out? When is the function `list` called? I can't find anything related to that. Are there manuals?

**Comment by xaizek** [comment]
Interaction is described at https://vifm.info/vimdoc.shtml#vifm-%27mediaprg%27

Just copy the lines between `<<` and `EOF` into a separate file and add a shebang to make things simpler. The python script is embedded to avoid calling one script from the other. The python is there because authors of udisks are nowhere near bright enough to make usable cli interface instead of a dbus-abomination you see. And working with dbus through `dbus-send` is even worse (that is if it's possible to parse its output at all).

**Comment by TornaxO7** [comment]
Do you mean with
> lines between `<<` and `EOF` the whole Python-Code?

**Comment by TornaxO7** [comment]
Ok so I've compied the python code into an external file and executed it. It works! But I'm still getting `No media found`.

**Comment by xaizek** [comment]
You can add some debug output to `devs()` function to see if it finds any devices at all and if it does, why they get filtered out. Maybe condition should allow some more values.

**Comment by TornaxO7** [comment]
It's working fine. I added this:
```bash
udisks2 list 1>&2
```
inside of the second `elif` clause in your script and it's printing out a device:
![image](https://user-images.githubusercontent.com/50843046/96282909-9d862200-0fdb-11eb-8d72-2eae5c4e94ec.png)

But after that it prints that there are no devices.

**Comment by xaizek** [comment]
There mustn't be any spaces around `=`:
```python
        print('device=%s' % device)
        print('label=%s' % label)
```
Vifm doesn't recognize the lines because of the space before `=` (that's intentional to avoid interpreting unrelated lines).

**Comment by TornaxO7** [comment]
Oh man... I've got it now... It's working "now" or let's rather say that it has worked all the time... I just didn't plug a USB stick into my PC because I though that it lists *all* devices, so I was wondering why it said that there weren't any devices although I had both hard drives plugged in... Sorry!

Anyway is it possible to list *all* devices? Because it can't detect my WD-Drive for example. (I'll close this since my original question has been solved)

**Comment by xaizek** [comment]
> Anyway is it possible to list all devices?

It's supposed to list all removable devices, but I tested it only with USB sticks. Maybe it fails to detect something. Now that I look at [udisks2 docs](http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-property-org-freedesktop-UDisks2-Block.IdUsage), there is a note:

>  Applications should not rely on the value in this or the "IdType" property

So maybe try this patch:

```
diff --git vifm-media vifm-media
index 9b6f7338b..78b4033e4 100755
--- vifm-media
+++ vifm-media
@@ -85,14 +85,13 @@ def devs():
     om = dbus.Interface(ud_manager_obj, 'org.freedesktop.DBus.ObjectManager')
     for v in om.GetManagedObjects().values():
         drive_info = v.get('org.freedesktop.UDisks2.Block', {})
-        usage = drive_info.get('IdUsage')
+        fs = v.get('org.freedesktop.UDisks2.Filesystem', {})
         hint = drive_info.get('HintSystem')
         ro = drive_info.get('ReadOnly')
-        if usage == "filesystem" and not hint and not ro:
+        if fs is not None and not hint and not ro:
             device = drive_info.get('Device')
             if device is not None:
                 device = decode(device)
-                fs = v.get('org.freedesktop.UDisks2.Filesystem', {})
                 yield (device, drive_info.get('IdLabel'), fs)
 
 def list_usb():
```

**Comment by TornaxO7** [comment]
Thanks for this patch! It's listing more partitions now, but it doesn't list my main-devices like `/dev/sda`:
![image](https://user-images.githubusercontent.com/50843046/96288617-fbb70300-0fe3-11eb-9266-600c77575f0b.png)

`/dev/sdg` is my WD-Passport and I can't mount it:
![image](https://user-images.githubusercontent.com/50843046/96288673-17220e00-0fe4-11eb-9abc-6029e637fa0d.png)

That's the error message I'm getting:
```python
ERROR:dbus.connection:Unable to set arguments ({},) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty dict
Traceback (most recent call last):
  File "<stdin>", line 56, in <module>
  File "<stdin>", line 44, in mount
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty dict
```
Probably the reason is that I'm using a LVM-Partition on my WD-Passport.

**Comment by TornaxO7** [comment]
Anyway thank you for your time and help! c(^-^)c

**Comment by xaizek** [comment]
`/dev/sda` is probably a system drive. You wouldn't be able to mount it anyway. The list actually looks weird with both `/dev/sdg` and `/dev/sdg1` being listed.

I don't know about mounting LVM stuff and whether it works with udisks2, but maybe replacing `{}` for Mount/Unmount calls with `dbus.Dictionary({}, 'sv')` will work? I don't know much about dbus.
