### ISSUE TITLE
vifm 0.11 build issue

### ISSUE THREAD

**Issue by chenrui333** [vifm/vifm#601]
👋 I tried to bump vifm to the latest per https://github.com/Homebrew/homebrew-core/pull/63061

but it looks like `vifm-media-osx` is not included in [the release artifact](https://github.com/vifm/vifm/releases/download/v0.11/vifm-0.11.tar.bz2)?

Here is a detailed error log:

```
Processing /private/tmp/vifm-20201018-989-4jjmvg/vifm-0.11/src/../data/vim/doc/app
  CC       viewcolumns_parser.o
make[1]: *** No rule to make target `../data/vifm-media-osx', needed by `all-am'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC       vifm.o
Updating build revision
make: *** [all-recursive] Error 1
```

Can you take a look? Thanks!

**Comment by xaizek** [comment]
Caused by e220cdb0a771149f25f824d59d4105e24634bcc6 for #460. You can probably apply a patch that adds `data/vifm-media-osx` and `data/vifmrc-osx` inside the formula.

I've also added `vifm-osx-0.11.tar.bz2` archive which should have this fixed, so you can use it for this version.

**Comment by chenrui333** [comment]
Thanks for the new artifact, it works well for me on my local.

**Comment by chenrui333** [comment]
Looks like it suffers some code style check issue, https://github.com/Homebrew/homebrew-core/runs/1277934787 

```
==> FAILED
Formula/vifm.rb:4:3: C: https://github.com/vifm/vifm/releases/download/v0.11/vifm-osx-0.11.tar.bz2 looks like a binary package, not a source archive; homebrew/core is source-only.
  url "https://github.com/vifm/vifm/releases/download/v0.11/vifm-osx-0.11.tar.bz2"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by xaizek** [comment]
It probably doesn't like `-osx` suffix. It's just a faulty check, I don't think it will prevent merging, just add a comment that's the failure is bogus.

**Comment by chenrui333** [comment]
Yeah, I think that check is not very ideal, but I wonder if you can upload an artifact with removing `-osx`? Thanks!

**Comment by xaizek** [comment]
Changing released archive is a bad idea, can only make an extra release and was hoping to avoid it as the issue didn't seem to be serious enough.

**Comment by xaizek** [comment]
This is closed because it's fixed on `master`, we can still discuss it.
