### ISSUE TITLE
Entering console mode within a running vifm instance

### ISSUE THREAD

**Issue by paniash** [vifm/vifm#603]
I recently switched from lf to vifm and I'm trying to replicate a behaviour which is very necessary to my workflow. I have a key-binding in my window manager that launches `vifm` and I intend to go to a particular directory and enter my shell through this `vifm` instance.

There is an option close to this in `vifmrc` as:
```vim
" Open console in current directory
nnoremap ,t :!xterm &<cr>
```

However, this opens a new xterm window. I wish my current vifm instance to enter console mode. How do I do it?

I've looked into: https://wiki.vifm.info/index.php/How_to_set_shell_working_directory_after_leaving_Vifm

But it assumes that I have a shell running which then invokes `vifm`. I wish to enter console mode within a running `vifm` instance. This behaviour is there in `ranger` and `lf` but I can't seem to find it in `vifm` after hours of reading the manual.

I'd be glad if someone could help. Thanks!

**Comment by yusufaktepe** [comment]
There is a mapping in default vifmrc:
https://github.com/vifm/vifm/blob/0510441013f053b1f83a49be41e9313a837897ee/data/vifmrc#L411

**Comment by paniash** [comment]
@yusufaktepe Ok, now I feel a bit stupid XD. Thanks a lot!

**Comment by outcastdreamer** [comment]
For others who are dumb like me in using vim, you just have to go to the directory you like in vifm and type <pre>:shell</pre> to get that directory to your cmd/terminal.
