### ISSUE TITLE
Count to dd is ignored because of a particular statusline

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#604]
The bug was reported [in Vifm Q2A](http://q2a.vifm.info/736/dd-dd-for-deleting-does-not-acknowledge-count):

> Using a [count] with dd or DD does not apply to [count] files after the selected one. If I press 3dd, I expected three files to be deleted, and although the three files show up in the confirmation dialog, after pressing y to confirm deletion, only one file has been deleted.

The cause has been tracked down to a statusline with `expand`, e.g.:

```
set statusline="%{expand('%c:p')}"
```

**Comment by xaizek** [comment]
Thanks for tracking it down.

**Comment by DieSpinne** [comment]
You are welcome. Actually, it also happens with `system` for me, e.g.:
```
:set statusline=:"%{system('stat --printf=%A '.expand('%d'))}"
```

**Comment by xaizek** [comment]
That's because of `expand('%d')`.
