### ISSUE TITLE
Vifm reading directory for too long

### ISSUE THREAD

**Issue by Nova-Striker** [vifm/vifm#605]
I have been a vifm user for months now and today it suddenly froze when I was using it. Since all the vifm commands were totally unusable , I had to manually close the terminal. But after that , when I open vifm , it says :
`Reading Directory` and its been showing that for the last 15 minutes , which I think is pretty long (considering it used to open a directory in mere milliseconds)

![Screenshot from 2020-10-24 13-31-24](https://user-images.githubusercontent.com/64089730/97071325-3d0b6c00-15fd-11eb-9ace-7b24dc8d8d59.png)

P.S : I was in last in `/dev` folder when I manually closed it. The problem might be because vifm is trying to open back in that same directory where it last froze. 

So is there a way to fix this , like by deleting the memory cache of vifm so as to open in some other directory ?

Edit : Okay , I fixed it by using `vifm /home` in terminal. 

But if anyone is interested in reproducing it,  use vifm to navigate to `/dev/char`

**Comment by xaizek** [comment]
What version of Vifm do you have? A bug related to device files and preview was fixed in 0.11 (see #537).

**Comment by Nova-Striker** [comment]
@xaizek  , I am using version 0.10.1 . Need to upgrade it then
