### ISSUE TITLE
Possible to set the padding between the icons and names?

### ISSUE THREAD

**Issue by yanzhang0219** [vifm/vifm#607]
Is it possible to set the padding/gap between the icon and the folder/file name? The current padding is too small so that the icon and the name are too close.
For example, the Desktop icon is very close to its name. 
![image](https://user-images.githubusercontent.com/11582667/97612605-de673900-19d4-11eb-8323-59c85decfa91.png)

Thank you.

**Comment by xaizek** [comment]
You can add extra space to the values of `'classify'` option.
```vim
" old
set classify=' :dir:/'
" new
set classify='  :dir:/'
```
However, the gap will be as wide as a character. Can't really have a fraction of that, except for using some font with different widths of the "icons".

**Comment by yanzhang0219** [comment]
Okay. I got it. 
Thanks!
