### ISSUE TITLE
Opening empty file prevents other files in the same directory from opening

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#608]
Steps to reproduce:

1. Launch Vifm with `vifm --no-configs`.
2. Enter a directory with one totally empty file and other non-empty files.
3. Press `l` or `Enter` on the empty file.
4. Close the just opened editor.
5. Press `l` or `Enter` on another file in the directory.
  - The empty file is opened again instead of the selected file.

If one changes directory before step (5), the correct file is opened.

Vifm version 0.11, compiled with patch [`950d6fe`](https://github.com/vifm/vifm/commit/950d6fe7d8d5fd647f436015b5743911038b783f).

**Comment by xaizek** [comment]
Thanks, can reproduce it on `master`, that commit must be causing it.

**Comment by DieSpinne** [comment]
In case extra information is helpful: I have stumbled upon the same behavior with a particular file, that I send as an attachment. Very mysterious. It should be related to its size, because the bug also occurs if some characters are replaced by others.
[attachment.txt](https://github.com/vifm/vifm/files/5497958/attachment.txt)

**Comment by xaizek** [comment]
Thanks, but file size doesn't matter. The bug is caused by state of file entries.
