### ISSUE TITLE
Question about key sequences

### ISSUE THREAD

**Issue by dschrempf** [vifm/vifm#612]
Hi! I have a short question about key sequences. What I want to achieve is the behavior of, let's say `y?` mappings, where `?` is a placeholder for many keys, such as `a` to yield `ya` which selects all files. When I press `y` the first time, a dialog pops up showing the possible completions. This dialog stays until I press the next key which completes the key sequence.

This behavior, for example, is different when using `,` as the first key. Then, the dialog vanishes after roughly one second. The dialog also vanishes when I define two new key sequences using `e` as the first key which is by default bound to `explore`:

```
" Edit file with VIM or Emacs.
nnoremap ee :!emacsclient -n %f<cr>
nnoremap ev :!vim %f<cr>
```

After pressing `e`, the dialog showing the completions `e` and `v` is showing up, but closes after a second, and the `explore` action is executed exploring the file at point. I don't want the `explore` action to execute at all, I would like to continue watching the dialog, to see which options I have so that I can complete the sequence.

Do I make myself clear? Thanks for your patience!
Dominik

**Comment by xaizek** [comment]
Hello,

Looks like you want to use [`<wait>` modifier](https://vifm.info/vimdoc.shtml#vifm-mappings):

```vim
nnoremap <wait> ee :!emacsclient -n %f<cr>
nnoremap <wait> ev :!vim %f<cr>
```

**Comment by dschrempf** [comment]
Thanks,

that was exactly what I was looking for.

What is a little weird though is that I either have to specify `<wait>` for all
sequences starting with `e` (or `,`). The other way around, if specification of
`<wait>` is enough once, I change the behavior of other key sequences, which is
probably also not beneficial.

**Comment by xaizek** [comment]
Not sure I understand what you mean. Here is how it works: if any of the candidates of key press resolution has `<wait>` on it, there will be no timeout. By specifying `<wait>` on every mapping with common prefix you're making this explicit.

**Comment by dschrempf** [comment]
Yes. I just meant that by specifying `<wait>` once, I change the behavior of all
other key sequences with the same prefix, which is somewhat weird. It was more
of a quick thought written down.

**Comment by xaizek** [comment]
Yeah, it is weird. But since the prefix is common you have to treat all candidates in the same way until ambiguity is resolved. So the only alternative is to ignore `<wait>` unless all such mappings have it, which is even weirder.
