### ISSUE TITLE
Mount Removable media

### ISSUE THREAD

**Issue by desgua** [vifm/vifm#617]
First of all THANK YOU SO MUCH FOR THE BEST FILE MANAGER EVER!

I want to contribute to the project. I made a simple script to help mount and unmount removable devices on Linux. 
1. Place the script on $PATH and make it executable
2. Edit ~/.config/vifm/vimrc to add a shortcut like (change $USER/.local/bin accordingly):
```
"mount and unmount removable media
command! mount dash -c "/home/$USER/.local/bin/desguamount mount"
command! unmount dash -c "/home/$USER/.local/bin/desguamount unmount"
```
3. The script:
```
#!/bin/dash
#
# by desgua 2020/11/17
# 

if [ "$1" = "mount" ]; then
    blocksavailable="$(lsblk -l | sed 's/ /\n/g' | grep -Ew 'sd[b|c|d][1-9]')"
    
    if [ "$blocksavailable" ]; then
        for dev in $blocksavailable ; do
            echo "Mounting $dev "
            udisksctl mount -b /dev/$dev
        done
    else
        echo "No device found."
    fi
    exit 0
fi

if [ "$1" = "unmount" ]; then
    blocksmounted="$(lsblk -l | grep 'media' | sed 's/ /\n/g' | grep -Ew 'sd[b|c|d][1-9]')"
    if [ "$blocksmounted" ]; then
        for dev in $blocksmounted ; do
            echo "Unmounting $dev "
            udisksctl unmount -b /dev/$dev
        done
    else
        echo "No device found."
    fi
    exit 0
fi

echo "This script will detect and mount or unmount removable devices."
echo "Usage $(basename $0) [mount|unmount]"
exit 0

```

**Comment by xaizek** [comment]
Have you seen [`:media` command](https://vifm.info/vimdoc.shtml#vifm-%3Amedia)? [Sample script](https://github.com/vifm/vifm/blob/master/data/vifm-media) also works with `udisks2` even though it requires Python to be installed (because `udisks2` is pain in the ass).

**Comment by desgua** [comment]
That is an awesome script, I haven't seen it before. Thank you!

**Comment by xaizek** [comment]
I'll close this then.
