### ISSUE TITLE
Up Arrow key stops working for cmd history after running :shell via vifm 

### ISSUE THREAD

**Issue by outcastdreamer** [vifm/vifm#620]
I am unable to access my cmd history after running the :shell command to jump to a directory in my cmd.
It kind of hinders productivity with the usage of such a great feature. 
I am unable to locate any sources to fix on the same.

**Comment by PRESFIL** [comment]
`:shell` command spawns new shell process, therefore you cannot share command history with your old shell.
Bash, by default, flushes command history on disk when exits. You can [change](http://aloop.org/2012/01/19/flush-commands-to-bash-history-immediately/) this behavior, but it can increase disc wear. Zsh, seems, have special setting.

You can also send `vifm` to background and get your first shell, buy CWD also will be as it was before `vifm` execution.

**Comment by PRESFIL** [comment]
Do you want to close issue?

**Comment by xaizek** [comment]
I assume this is resolved. Thanks, @PRESFIL.
