### ISSUE TITLE
"filetype ... %c &" executes for each selected file

### ISSUE THREAD

**Issue by DieSpinne** [vifm/vifm#621]
Steps to reproduce:

1. Create some files: `touch a b c`;
2. Start a clean Vifm with `vifm --no-configs`;
3. Issue `:filextype * xmessage %c &`;
4. Select the three files with `t` or visual selection and press Enter.

- Expected: The command is only triggered for the file under the cursor (as per `%c` description), causing only one Xmessage window to spawn.
- What happens: The command is triggered for each selected file, causing three Xmessage windows to spawn.

**Comment by xaizek** [comment]
The scenario you describe should launch only one `xmessage` and it does for me. However, you will get three `xmessage` instances if your filetype command is a background one.

In addition to `%c` there is also [section on running selection](https://vifm.info/vimdoc.shtml#vifm-selection).

**Comment by DieSpinne** [comment]
Sorry Xaizek, I missed that latter section of the docs. I admit I still find the behavior intriguing, but since it is documented, I guess this should be closed.
