### ISSUE TITLE
[help]how to make vifm to select file from result of external command?

### ISSUE THREAD

**Issue by windwp** [vifm/vifm#624]
Hi  i know it is not an issue of vifm but maybe somebody can help
Is there anyway to tell vifm to select or focus on a list of file from another command?
Example:
I have a folder with too many image and i want to delete some image of it
i use command `:!sxiv %d -o<cr>` and select all image i want to delete after that sxiv will output all file path to vifm but I don't know how to tell vifm to select the file i choose from sxiv?

Thank

**Comment by xaizek** [comment]
Hello,

look at the `%u` and alike macros in [the documentation](https://vifm.info/vimdoc.shtml#vifm-%25u). Adding `%u` will build a file list out of `sxiv`'s output.

**Comment by windwp** [comment]
Thank it work :+1:
