### ISSUE TITLE
<C-h> not work in iTerm2 on macOS

### ISSUE THREAD

**Issue by yanzhang0219** [vifm/vifm#626]
Hello, 
I was using Alacritty (vifm on Alacritty works perfectly) and just wanted to test vifm on iTerm2, more or less on the whim. And I found `C-h` mapping doesn't work well. 

I have a mapping `noremap <C-h> <C-w>h` and then when I press `Ctrl` and `h`, it does nothing. (Other 3 corresponding mappings related to moving cursor around panes work normal.)

BTW, in neovim, I have the same mapping and it works well.

Thank you very much.

**Comment by xaizek** [comment]
Hi,

There is a section in [the docs](https://vifm.info/vimdoc.shtml#vifm-mappings) (above "Whitespace") , which mentions issues with `<c-h>` and `<bs>`. Basically, repeating the mapping with `<bs>` should make it work everywhere.

Unlike Vifm, Vim (and therefore neovim) doesn't use curses, only terminfo part of it, hence it works somewhat differently. Curses exposes a separate key for <kbd>Backspace</kbd>, sometimes it matches <kbd>Ctrl+H</kbd> sometimes it doesn't, sometimes they are independent and I don't know of a good workaround in the implementation.

**Comment by yanzhang0219** [comment]
Wow, great! I should have searched for the answer in the docs first. Sorry about that. 
Thank you.
