### ISSUE TITLE
Ability to Customize directory preview?

### ISSUE THREAD

**Issue by risingtiger** [vifm/vifm#628]
Is there a way to ability to customize the directory preview? Currently, it shows all levels and shows all dot files. Its a really cool feature and I can see it being really useful. However, the bummer is that it always shows my .git directory which swamps out every other sub file/folder, and renders the feature much less useful. And it would be nice to set the -L levels. 

Is there a way to intercept directory/folders with a Preview option in vifmrc?

I'm really stoked about vifm, much better than nnn (for me at least:)

**Comment by xaizek** [comment]
You can match a directory with trailing slash in a pattern, like here:
```vim
fileviewer */ tree -L 2 -I .git %c
```

**Comment by PRESFIL** [comment]
I thought about this for a very long time, but for some reason it seemed to me that the tree does not use `tree` (despite the fact that the *stdout* is identical) :worried:. @xaizek, thanks!

**Comment by xaizek** [comment]
> it seemed to me that the tree does not use `tree`

@PRESFIL, you got it right. It doesn't, there is builtin code for drawing a tree since v0.8.1 (because `tree` isn't always installed by default on Linux and its equivalent on Windows caused trouble). Builtin implementation is used only if no viewer matches directories (`*` pattern matches all files including directories).

**Comment by PRESFIL** [comment]
Then you can do this:

```viml
if executable('tree')
    fileviewer */ tree -L 2 -I .git %c
endif
```

**Comment by xaizek** [comment]
I should have said that as usual only viewers that exist are considered, so you don't need an explicit check.

**Comment by risingtiger** [comment]
awesome. really liking the flexibility on this.

**Comment by PRESFIL** [comment]
I recently noticed that `*/` does not match hidden folders (*dotdirs*) and they handled with default handler. `/.*/` does the trick. But it's not entirely clear how.

Now:

```viml
if executable('tree')
    fileviewer /.*/ tree -L 2 -I .git %c
endif
```

`/.` mentioned [here](https://unix.stackexchange.com/questions/329339/bash-pattern-to-match-directories-whose-names-begin-with-a-dot-period-by-bein).

**Comment by xaizek** [comment]
`.*` is an undecorated pattern which means file name glob for `:fileviewer` command, `/.*/` is an explicit regular expression `.*` for file name which actually matches *everything*.

What you want can be done with two globs like this:
```vim
if executable('tree')
    fileviewer */,.*/ tree -L 2 -I .git %c
endif
```
See docs [on patterns](https://vifm.info/vimdoc.shtml#vifm-patterns) and [globs](https://vifm.info/vimdoc.shtml#vifm-globs) in Vifm.

**Comment by PRESFIL** [comment]
I just figured it out myself. Thank you.
