### ISSUE TITLE
Optional setting for using $EDITOR as the primary editor

### ISSUE THREAD

**Issue by verdsveven** [vifm/vifm#633]
I know the file manager is called vifm, implying use with vi, vim or neovim. I also know the :help command relies on a vim-like editor. However, it would be nice, if it was possible, to have vifm follow the EDITOR environmental variable for the default editor (optionally) so as to be able to switch editors unilaterally across a system. This is just a humble (and hopefully minimal request). Thank you.

**Comment by xaizek** [comment]
I see no need for a new option, when you can do this:
```vim
if $EDITOR != ''
    let &vicmd = $EDITOR
endif
```

**Comment by verdsveven** [comment]
Thank you @xaizek . This does exactly what I wanted. I didn't realise you could script in the vifmrc. Is the language simply shell script? Sorry for wasting your time with my ostensibly useless request.

**Comment by PRESFIL** [comment]
It is an vifm's native scripting language, insiperd vim's `viml`, AFAIK. You should put it inside `vifmrc` or include script into `vifmrc` with `source` operator.

**Comment by xaizek** [comment]
Yeah, it's a very small "subset" of VimL. Basically it includes `:let`, `:if` (and related) and some operations and builtin functions. You can't do much in it, only simple conditions in configuration, mappings or custom :commands.
