### ISSUE TITLE
Unable to qmap c-up/down, c-home/end ?

### ISSUE THREAD

**Issue by mckellygit** [vifm/vifm#634]
Hi,

Thank you for vifm, it is awesome.
I have added many qmaps to my liking to match my vim and less preferences, and its great!
I cannot however figure out how to map:
\<c-up\>, \<c-down\>, \<c-home\>, \<c-end\>
I try these qmaps and they do not work.
I have tried the correct esc-codes as well but still nothing.
I am on Ubuntu 18.04 with the latest master vifm built with ENABLE_EXTENDED_KEYS set.
Any ideas ?  Do you think this possible without source changes ?

thx for any help,
-m

**Comment by xaizek** [comment]
Hello,

If you can't find a particular angle-bracket notation in [the documentation](https://vifm.info/vimdoc.shtml#vifm-mappings), then it's not supported. curses almost doesn't expose keys with modifiers and I'm reluctant to hard-code them.

However, mapping escape codes should work. For `<c-up>`:

    :qnoremap <esc>[1;5A j

**Comment by mckellygit** [comment]
Hi,
The esc-code mapping also does not work here.  I will double check my config.
But I've seen this before with (n)curses, when extended key support is enabled then <c-up> and others actually return a keycode above the KEY_MAX value, instead of the esc-code sequence.
I had to loop though the keyname()s of kDN5, kUP5, etc. to get the keycode for each, and use that to know what was pressed.
thx,
-m

**Comment by xaizek** [comment]
Without `keypad(window, TRUE)` arrows and other grey keys don't work, so it's on unless you specify `--disable-extended-keys`:

https://github.com/vifm/vifm/blob/master/src/ui/ui.c#L256-L258

I haven't observed the behaviour you describe. Maybe that's an extension of a particular curses implementation?

**Comment by mckellygit** [comment]
Yes, arrow keys work fine unless I build with --disable-extended-keys.
Its just ncurses-6.2
Does the esc-code mapping for \<c-down\> (\<esc\>[1;5B) work for you when you have --enable-extended-keys ?
extended-keys adds KEY_DOWN for \<down\> etc. - that is all fine, but [at least in my case] it doesn't have a specific keycode for \<c-down\> - and here is the rub, it still returns a 5000+ value (> KEY_MAX).  This is the case for several keys.

All I am saying is I can try:
1). build with --disable-extended-keys and add many esc-code mappings for \<up\>, etc. to my vifmrc
or
2). build with --enable-extended-keys and add a little source code to handle the dozen or so keys that return a keycode > KEY_MAX that are not defined by a curses key name - because an esc-code will not work for these when keypad is set.

thx again,
-m

**Comment by mckellygit** [comment]
I'll send a 5 line example PR to show what I mean.
We can either disable the unsupported extended unnamed keycodes so esc codes work or we can figure out what they are (5001 == kDN5 == \<c-down\> etc.  I did this same thing for tig.
thx again,
-m

**Comment by xaizek** [comment]
I think I get the idea, I'm just wandering why it's different for you.

I just tried with ncurses-6.2 and escape-code mappings work fine. What terminal are you using? Do you see the same behaviour in, say, `xterm`?

**Comment by mckellygit** [comment]
Perhaps its the way I built ncurses ?  Although I just did a configure without any special options.
I have tried alacritty, kitty, urxvt and xterm and they are all the same.
This simple change below -
```
#ifdef ENABLE_EXTENDED_KEYS
	keypad(status_bar, TRUE);
#endif /* ENABLE_EXTENDED_KEYS */

#if defined(NCURSES_EXT_FUNCS) && NCURSES_EXT_FUNCS >= 20081102
#ifdef HAVE_SET_ESCDELAY_FUNC
	/* Use ncurses specific function to make delay after pressing escape key
	 * unnoticeable.  Used to be zero, but in some corner cases multiple bytes
	 * composing a functional key code might be handled to the application with a
	 * delay. */
	set_escdelay(5);
#endif
    // new code here -----------------------------------
    // Disable extended keys so that esc-codes will be received
    // instead of extended key values (> KEY_MAX).
    // Then these keys can be mapped in .tigrc etc.
    int i;
    for (i=KEY_MAX; i<2000; i++) {
        keyok(i, false);
    }
    // new code here -----------------------------------
#endif
```
makes it work fine - because those few keycodes like \<c-down\> now no longer return an unsupported keycode value.
I'll work on the other method of handling these keycode values, but that is a little bit more code.
thx,
-m

**Comment by mckellygit** [comment]
Almost all esc-code mappings work fine as is.  Its just that there are a handful of 'special' keys that will emit a keycode value > KEY_MAX instead of an esc-code when NCURSES_EXT_FUNCS is set - at least in my ncurses build.  And for these few we should either disable this like above with the keyok(false) so they return esc-codes or figure out what these keycode values mean via a separate lookup from the terminfo capability names.
Anyway, thank you again for awesome vifm!
-m

**Comment by mckellygit** [comment]
These are a few of the keycode values I get that are above KEY_MAX (511) when keypad(true) is called and keyok() is not disabled for them:
```
531 kDN5 (c-down)
574 kUP5 (c-up)
568 kRIT5 (c-right)
553 kLFT5 (c-left)
529 kDN3 (a-down)
572 kUP3 (a-up)
566 kRIT3 (a-right)
551 kLFT3 (a-left)
542 kHOM5 (c-home)
536 kEND5 (c-end)
```
thx,
-m

**Comment by xaizek** [comment]
I was testing ncurses-6.2 built like this, which doesn't seem to enable anything special https://github.com/vifm/vifm/blob/0fe858dad72bc44a865053615ca993348d18ff81/pkgs/AppImage/genappimage.sh#L39-L49

I like `keyok(i, false);` somewhat more than an alternative because this way it should work the same for all configurations with the same `vifmrc`. I'll try to figure out where this comes from in ncurses. Thanks!

**Comment by mckellygit** [comment]
PR https://github.com/vifm/vifm/pull/636 created if its helpful.
