### ISSUE TITLE
Error while putting. Failed to setup file permissions

### ISSUE THREAD

**Issue by lucasmsoares96** [vifm/vifm#635]
I get an "Error while putting. Failed to setup file permissions" every time I manipulate a file on the exfat partition.
I mounted the partition with the following command:
sudo mount -t exfat -o umask=000 /dev/sda3 /mnt/files

vifm --version

```
Version: 0.11
Git info: built out of repository
Compiled at: Oct  7 2020 19:22:04

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```
uname -a
```
Linux ArchLinux 5.10.7-arch1-1 #1 SMP PREEMPT Wed, 13 Jan 2021 12:02:01 +0000 x86_64 GNU/Linux
```

**Comment by xaizek** [comment]
This issue is similar to #616, but with `'syscalls'` set. See my comment there, which might work for `exfat` as well: https://github.com/vifm/vifm/issues/616#issuecomment-765370972

**Comment by lucasmsoares96** [comment]
uid=1000,gid=1000 works. Thank you.
