### ISSUE TITLE
vifm leaves zombie processes when previewing files with vifmimg

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#639]
I compiled a fresh version of `vifm-git`. I remember that you made `setsid` for all processes ([commit](https://github.com/xaizek/vifm/commit/d09adddf4e8f7f4cf7c26f688837a9d08d43743d)).

Now, after each preview process, there is a zombie:
![image](https://user-images.githubusercontent.com/20644917/106176953-d368a400-618f-11eb-8828-5d20f7f7958c.png)

These zombies remain until the exit of the `vifm`.
I don't know if this is related, but collecting zombies is the responsibility of the parent. That's why I'm writing to you.

I use `vifmimg` for previewing.

---

`vifm` version: `v0.11-247-g845b0b514909-dirty`
`ueberzug` version: `18.1.9-1`
`vifm` version: `r36.afe4f15-1`

**Comment by xaizek** [comment]
Thanks for reporting, it's not because of `setsid`. I dropped handling of `SIGCHLD` to avoid deadlocks (95f91946c25e2f0b8d3ab8ac6c2557aeb8bf3182), now need to add ripping of children for which `waitpid` isn't called (forgot about them).

**Comment by PRESFIL** [comment]
Okay, I'll wait for you to bring it back to check it out!

**Comment by PRESFIL** [comment]
OK, it is now fixed. Thanks!

**Comment by xaizek** [comment]
Thanks for confirming it.
