### ISSUE TITLE
Request: Add UNC paths to list of drives from :vol command

### ISSUE THREAD

**Issue by PhilRunninger** [vifm/vifm#640]
Thanks for the fantastic program. Lately, I've been doing a lot of work on several different servers, and I have drives mapped to each of them. The drive letters are not in any particular order, and I don't want to put forth the effort to memorize where they go. It would be really handy if the `:vol` command would show the drive letters' corresponding network paths.

I did a little digging and came up with the following sample C++ code that can be used as a starting point for modifying [volumes_menu.c](https://github.com/vifm/vifm/blob/master/src/menus/volumes_menu.c). (I would have put this in a pull request, but my machine isn't set up to compile the program.)
```c++
int main()
{
    char c;
    char unc_path[PATH_MAX + 1];
    char vol_name[PATH_MAX + 1];
    char file_buf[PATH_MAX + 1];
    DWORD max_len = PATH_MAX;

    for(c = 'a'; c <= 'z'; ++c)
    {
        if(drive_exists(c))
        {
            const char drive[] = { c, ':', '\\', '\0' };
            const char drive_no_backslash[] = { c, ':', '\0' };
            cout << drive;

            long rc_unc = WNetGetConnectionA(drive_no_backslash, unc_path, &max_len);
            long rc_vol = GetVolumeInformationA(drive, vol_name, sizeof(vol_name), NULL, NULL, NULL, file_buf, sizeof(file_buf));

            if (rc_unc == 0) {
                cout << "  " << unc_path;
                if (rc_vol != 0 && strlen(vol_name) > 0) {
                    cout << "  <==>  " << vol_name;
                }
            }
            else if(rc_vol != 0) {
                cout << "  " << vol_name;
            }
            cout << endl;
        }
    }
}
```
Using the `WNetGetConnectionA` function requires you to also link in the `mpr.lib` file. Here is the output produced by the code above:
```
c:\  Windows
k:\  \\server1\SharedData  <==>  SHARED
l:\  \\company.server2.com\CompanyData
x:\  \\server3\c$
y:\  \\server4\c$  <==>  OS
z:\  \\server5\c$  <==>  Boot
```
I briefly played around with the `QueryDosDeviceA` function to handle drive letters created by the `SUBST` DOS command, for example `SUBST H: C:\Users\Phil`. My goal was to print the following lines;
```
c:\  Windows
h:\  C:\Users\Phil
```
however, the string needed to be parsed to get the desired information, and I wasn't sure how consistent that format was. This is what comes back for `c:` and `h:`:
```
c:  -->  \Device\HarddiskVolume3
h:  -->  \??\C:\Users\Phil\
```
Does the presence of `??` always indicate a drive created by `SUBST`? I wasn't sure, so I abandoned that idea. (I don't think `SUBST` is used much, and anyone who does use it probably knows where that drive goes anyway.)

**Comment by xaizek** [comment]
Thanks! Will add this.

> Does the presence of `??` always indicate a drive created by `SUBST`?

I don't think it even always implies a user-space path. Windows Internals also mentions "\??\Volume{X} (where X is a GUID)" and I guess "\DosDevices\C:" might also appear if you create two drives with the same name. But if it works fine in most cases after dropping prefix and references to devices (by checking for `X:\*` patern), adding it shouldn't hurt.

**Comment by xaizek** [comment]
In case you want it now, master builds for Windows are available [here](https://builds.vifm.info/).

**Comment by PhilRunninger** [comment]
Awesome! That's perfect, @xaizek .
