### ISSUE TITLE
Append to `cterm=style` instead of overwriting it

### ISSUE THREAD

**Issue by savchenko** [vifm/vifm#641]
Currently, it is possible to define `cterm` on per-highlight-group basis, but every record overwrites the previous one.
For example, it is (as far as I know) impossible to append "bold" for `hi CurrLine`, only re-define it.

It would open some good UX opportunities if something like `hi CurrLine cterm+=bold` is allowed.
Consider the following listing:
![image](https://user-images.githubusercontent.com/300146/106372393-093f9f80-63bf-11eb-942c-98e8e7f23847.png)
Moving cursor one line below would invariably remove `italic` from the "broken_symlink" entry.

**Comment by xaizek** [comment]
Thanks.

The syntax I chose is to add a pseudo-attribute "combine", because `+=` is confusing: initially I thought that you just want to modify previous `:highlight` definition more conveniently.
