### ISSUE TITLE
Filename column without extension

### ISSUE THREAD

**Issue by savchenko** [vifm/vifm#643]
In `windo` command, it is possible to use `{name}` and `{ext}` constructs, however there seem to be nothing that represents "file name without an extension".

Would it be possible to add one?

**Comment by xaizek** [comment]
There are `{root}` (complements `{ext}`) and `{fileroot}` (complements `{fileext}`) already. And they are values of `'viewcolumns'` option, not really related to `windo`. In case you use `windo set` to set option for both panes in `vifmrc` outside a mapping or a command, it's not necessary since v0.8.1.

**Comment by savchenko** [comment]
Thank you! Turns out there _is_ "Column name" section in the manual :) I shall note that `{root}` strips endings after <kbd>.</kbd> on folders (which may be well-expected behaviour). Here is an example:

`{name}`
![image](https://user-images.githubusercontent.com/300146/106696046-c6ceca80-662b-11eb-8b97-4355a8ceac53.png)

`{root}`
![image](https://user-images.githubusercontent.com/300146/106696075-d221f600-662b-11eb-8e53-023d9ced174c.png)


`{fileroot}` works as expected.

> In case you use windo set to set option for both panes in vifmrc outside a mapping or a command, it's not necessary since v0.8.1.

Inside the command:
```vim
" Column views
command! simple :windo set viewcolumns=-{name}..
command! detailed :windo set viewcolumns=-{fileroot}..,9.9{fileext}..,7.5{size}...,17.15{mtime}..
nnoremap <c-w>s :simple<cr>
nnoremap <c-w>d :detailed<cr>

```
