### ISSUE TITLE
File name with invalid encoding is cut off

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#644]
Hi!

From time to time, I receive files whose name seems difficult to render.

Here's how Vifm in kitty renders the file name:

![Vifm in kitty](https://i.imgur.com/eSwxIlg.png)

In Bash, when using `ls`, the file name looks like this:

![File name in Bash](https://i.imgur.com/GI5dyNb.png)

As you can see, the file suffix ".pdf" is cut off.

This is what I get when piping the ouput of `ls` to Neovim:

    Lsungswege und Testflle.pdf

In my setup of Neovim, this looks like this:

![File name in Neovim](https://i.imgur.com/QWGhWwZ.png)

The file name is supposed to say "Lösungswege und Testfälle.pdf", meaning `ö` is represented as <94> and `ä` is represented as <84>.

[Here](https://cloud.mb.sb/s/FgM4KTr5XqB4CQq/download) is an archive that contains the file whose name is encoded incorrectly.

I guess it's not easy to handle these issues that I presume stem from encoding. I'm wondering though whether there's a way around Vifm cutting off the last parts of the file name.

---

As an encore, Firefox' file browser makes it evident that the file name uses invalid encoding:

![Firefox' file browser shows "(invalid encoding)"](https://i.imgur.com/W8vAJBR.png)

**Comment by xaizek** [comment]
Hi.

Thanks for the great report.

It looks differently for me in xterm:
![vifm-test](https://user-images.githubusercontent.com/459736/108134228-81e07480-70be-11eb-9012-e24667e40d57.png)
So cutting off the extension is hard to explain. Could be something about kitty's terminfo that makes curses print `~T` and `~D`.

Invalid UTF-8 bytes are quite well defined and shouldn't be hard to correct for, although they will look like something they're not.

**Comment by mb720** [comment]
Interesting! Thanks for your response.

I observe that different terminal emulators show the same issue on my machine.

Vifm in xterm:

![Vifm in xterm](https://i.imgur.com/7zASIXL.png)

When starting xterm, I get this error, but I'm not sure it's related:
>xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"

Vifm in Alacritty:

![Vifm in Alacritty](https://i.imgur.com/5OUVX8W.png)

I'm curious where our setups differ. Could it be an issue with Wayland or Sway?

The output of `locale` seems normal:

    LANG=en_US.utf8
    LC_CTYPE="en_US.utf8"
    LC_NUMERIC="en_US.utf8"
    LC_TIME="en_US.utf8"
    LC_COLLATE="en_US.utf8"
    LC_MONETARY="en_US.utf8"
    LC_MESSAGES="en_US.utf8"
    LC_PAPER="en_US.utf8"
    LC_NAME="en_US.utf8"
    LC_ADDRESS="en_US.utf8"
    LC_TELEPHONE="en_US.utf8"
    LC_MEASUREMENT="en_US.utf8"
    LC_IDENTIFICATION="en_US.utf8"
    LC_ALL=

I have this in `.bashrc`:

    export LANG="en_US.utf8"

**Comment by xaizek** [comment]
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

It looks the same for me in xterm, mlterm, urxvt and native console... Just two blanks. I don't really know what can account for the difference.

**Comment by xaizek** [comment]
Not sure if issues like this one are completely solved (probably not), but they should be handled better now.
