### ISSUE TITLE
Activating session leads to problems with searching files.

### ISSUE THREAD

**Issue by acroobat** [vifm/vifm#645]
`:session default` 
Loaded session: default

Next search somefile:
`/somefile`
Strange behavior while searching files: status line is just repeating  `Loaded session: default` if no files are founded.
 'Go to next file' ("n" key) is not working if multiple files are founded.

**Comment by xaizek** [comment]
I can't reproduce it (tried with v0.11 and version from master). Does it happen with a specific session or with any that you create?

**Comment by acroobat** [comment]
Also tried git version. Recreating default session through `:delsession default` solved the problem.
