### ISSUE TITLE
Possible to remap ctrl-a increment functionality 

### ISSUE THREAD

**Issue by rwtallant13** [vifm/vifm#646]
I would like to be able to remap ctrl-a to another function but still be able to use the default ctrl-a incremental functionality either by remapping that or manually in command mode but i cant find a way to do that in the manual.

**Comment by xaizek** [comment]
You need to use no-remap kind of a mapping command to get access to original <kbd>Ctrl+A</kbd> (noremap doesn't expand user-mappings), for example:
```vim
" your mapping that shadows original <c-a>
noremap <c-a> ga
" map original <c-a> to A
noremap A <c-a>
```

**Comment by rwtallant13** [comment]
Thank you, that's admittedly very obvious not sure how I overlooked it.
