### ISSUE TITLE
Use highlight colors in other columns too

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#649]
Vifm can color file names according to their type (regular file, directory, FIFO, etc.), but it does not color the remaining columns (size, permission, etc., as set in `viewcolumns`).

I believe this would be a nice addition because, in a sense, it works as a "ruler", making it visually easier to associate the files with their respective attributes in other columns. In case it is not clear, it is the same principle of a spreadsheet with alternating row colors.

**Comment by xaizek** [comment]
I think it was this way at some point and someone didn't like (too colorful), so needs to be configurable.

> In case it is not clear, it is the same principle of a spreadsheet with alternating row colors.

You can do exactly that with:

    hi OddLine ctermbg=236

**Comment by xaizek** [comment]
To enable:
```vim
set hloptions=filehi:allrows
```
