### ISSUE TITLE
Segfault when perform tab-compeletion of unknown command in Command-line mode

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#650]
I enter the command `:file<Space>` and press `<Tab>` - everything works as it should, the completion options appears.
Now I type `:file<Space>` and press `<Tab>` - `vifm` crashes with **SEGFAULT**.

---

`vifm-git` version: `v0.11-294-g4aa9fa75e63d-dirty`

**Comment by xaizek** [comment]
Thanks! Broke it in 8105b7998a671d0ca7697b9f4005494a4d22c86e.
