### ISSUE TITLE
set vicmd is limited

### ISSUE THREAD

**Issue by ghost** [vifm/vifm#651]
I use the vis text editor. But setting vicmd to vis does not work. For :help, it seems that vifm tries to still use -c flag even though there is no guarantee that it would work with the changed editor. For bulk renaming, :rename, it seems like it tries to use the -f flag. Am I missing some other option?

**Comment by xaizek** [comment]
You're right, there are implicit assumptions about arguments that `vicmd` accepts. And there is no way to customize those. At this point, your only option seems to be writing a wrapper that will throw away or translate Vim-specific options and then invoke Vis.

For help you probably won't be able to make use of Vim's tags anyway and might as well disable [`'vimhelp'`](https://vifm.info/vimdoc.shtml#vifm-%27vimhelp%27) option.
