### ISSUE TITLE
UTF-16 in Preview window

### ISSUE THREAD

**Issue by PhilRunninger** [vifm/vifm#652]
When pressing `w` or `e` to preview a UTF-16 file, it is not displayed correctly, as shown in the screenshot below. Notepad shows the encoding as `UTF-16 LE`. 

![image](https://user-images.githubusercontent.com/5598066/109658439-97c94d00-7b34-11eb-89fd-25d7b0341e3a.png)

**Comment by xaizek** [comment]
There is no encoding detection, output is interpreted as UTF-8-compatible or at least 8-bit. In this case it probably stops at first zero byte.

You might want to use some tool that detects encodings and converts to UTF-8. Even if Vifm will try to detect UTF-16, there will be files which give false positives as there is no sure way for doing it. Specialized tools should be smarter at this, but they too fail.

**Comment by PhilRunninger** [comment]
I see. From your comment, and others I've read, determining the file encoding is a guessing game. Fair enough.

**Comment by PRESFIL** [comment]
You cat try to setup [iconv](https://sourceforge.net/projects/gettext/files/libiconv-win32/1.9.1/) for Windows. And use `iconv -t UTF-8` as previewer. But only I do not know how to set it as the default viewer.

**Comment by xaizek** [comment]
> But only I do not know how to set it as the default viewer.

By adding this as the last `fileviewer` command in `vifmrc` (`%"c` is for Windows):

```vim
fileviewer *[^/] iconv -t UTF-8 %"c
```
