### ISSUE TITLE
system() and term() functions not working in Windows 10

### ISSUE THREAD

**Issue by fwy** [vifm/vifm#653]
Since using vifm on a Windows 10 system, I have found that custom commands relying on the system() and term() functions do not work.  Specifically, they don't seem to pass any input to the shell or cause any shell commands to execute.

Here is a simple made-up example added to my vifmrc file.  I am using the Windows cmd.exe shell.

command! test :execute 'cd' fnameescape(system('echo %D'))

This command should switch the active pane to the directory location of the other pane.  It works on Linux, but on Windows it switches to the home directory -- a straight 'cd' command.  In other cases I have tried, the system() and term() functions don't seem to be communicating with the cmd shell at all.

Is this a real Windows 10 issue, or am I doing something wrong here?

**Comment by xaizek** [comment]
Try
```vim
command! test :execute 'cd' fnameescape(system(expand('echo %%D')))
```
Your version expands `%D` before running `:execute` command and can mess things up if path contains something unusual. Doubling `%` and performing expansion explicitly avoid this.

**Comment by fwy** [comment]
Thanks for the reply, but it still doesn't work -- no change in results.

I also have a few other commands in my vifmrc with no macros in the command text to be expanded, and they are not being processed either.  Example:

command! FZFfind :set noquickview | :execute 'goto' fnameescape(term("fzf | sed.exe -b -e 's/\\/\//g'")) | redraw

This one returns the error 'Too few arguments' when run.

**Comment by xaizek** [comment]
Can you try running `vifm --no-configs` (quit with `:q!` to not overwrite `vifminfo` file), adding a command interactively and using it? Maybe you have incorrect option set, like `shellcmdflag`, while defaults should work.

**Comment by fwy** [comment]
Thanks, I indeed had an incorrect option in vifmrc left over from a previous vifm installation.  I had prefixed the PATH environment variable with an invalid string.  I am not sure how that caused the problem, but removing the settings seems to have fixed it.

I'm still having some problems creating custom commands that work correctly on Windows, but will post separate questions if needed.  Thanks again!
