### ISSUE TITLE
Unwanted persistence preview when `millerview` and `milleroptions=preview:all` is set

### ISSUE THREAD

**Issue by CosmosAtlas** [vifm/vifm#656]
I'm using `vifmimg` to preview images in `millerview` mode. When I leave the current directly, the previewed imaged sticks in the terminal and does not disappear. 

The save behaviour does not exist when previewing with `:view`. 

My mild guess is that when `milleroptions=preview:all` is set, `%pc` is not working correctly to execute the command `vifmimg clear`. For example, when the preview sticks in the terminal, I can manually run `vifmimg clear` to remove the preview.

**Comment by xaizek** [comment]
I see the same behaviour with `w3m` preview which doesn't need `%pc` part for me, so there must be no clearing on leaving directory at all.

Thanks for the report. Looks like this wasn't noticed for quite a while.
