### ISSUE TITLE
Issues in sorting by name

### ISSUE THREAD

**Issue by randomizedthinking** [vifm/vifm#657]
I would like to sort files (including directories) by name, and noticed that the result does not seem right.

Please see the attached screenshot. Notice the sorting option is by name: `[a-z] n Name`.

![image](https://user-images.githubusercontent.com/5283430/113227033-74cead80-9246-11eb-9f2b-b9697b7bc95e.png)

**Comment by xaizek** [comment]
You have [`'sortnumbers'` option](https://vifm.info/vimdoc.shtml#vifm-%27sortnumbers%27) set and `2013 < 201301`.

**Comment by randomizedthinking** [comment]
Thanks for pointing it out. Good to know one bit of more information about vifm.
