### ISSUE TITLE
Opening a file inside a .tar archive with Vim without editing it creates an .orig file

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#658]
I only view the file, not change it. Vifm 0.10.? and 0.11.

**Comment by xaizek** [comment]
Are you sure Vim doesn't create swap-file next to the file?

**Comment by aleksejrs** [comment]
It does.

**Comment by xaizek** [comment]
Then that's counted as an archive modification by the FUSE mounter, which then creates a backup. It's not Vifm that does this.

For `archivemount` you can disable write support with `-o readonly` option.

You might also want to tell Vim to put swap files somewhere like in `~/.vim/data/swap`.

**Comment by aleksejrs** [comment]
> You might also want to tell Vim to put swap files somewhere like in `~/.vim/data/swap`.

Is there a way to do that only in this case?

**Comment by xaizek** [comment]
You can check whether `$VIFM_FUSE_FILE` is non-empty in `vimrc`, Vifm sets it for commands run inside a FUSE mount.

**Comment by aleksejrs** [comment]
Thanks, this works (the directory must exist; check with `swapname`).

```vim
if $VIFM_FUSE_FILE != ""
	set dir=~/.cache/vim
endif
```
