### ISSUE TITLE
Add keybindings to permissions dialog

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#659]
I believe the permissions dialog could benefit from some shortcuts for common operations or/and a layout change. For example, a single keypress {r,w,x} to set/unset all read/write/execute bits (normally I'd just like to do `cpx` to make a script executable), or/and maybe a 2D layout such as
```
       Read  Write  Execute  Special
Owner  [ ]    [ ]     [ ]      [ ]
Group  [ ]    [ ]     [ ]      [ ]
Other  [ ]    [ ]     [ ]      [ ]
```
so as to make navigation more convenient with {h,j,k,l} instead of only a vertical navigation with {j,k}.
I have suggested "Special" for SetUID, SetGID and Sticky but there may be some better description for that.

**Comment by xaizek** [comment]
Sounds like a great suggestion that makes the dialog much more usable. Thanks!
