### ISSUE TITLE
Feature: search highlighting

### ISSUE THREAD

**Issue by willemw12** [vifm/vifm#66]
Vifm supports highlighing. However, I could not find support for search highlighting of files.

Have the whole line or the whole filename highlighted, or the line marked with some indicator character.

It would be nice to also have the search strings highlighted. Filenames can be truncated in the window pane, so not all of them will be visible.

**Comment by xaizek** [comment]
It's in the `master` branch now.

Only first match is highlighted. Highlighting all would require slower search as well as carrying more data about search results, while benefits are questionable.

Characters of search match have inverted `underline` and `reverse` flags, marks (`<<<` or `>>>`) have inverted `reverse` flag.

Ellipsis might be highlighted as part of matches, but if ellipsis are not confusing in file name, it won't be confusing in match highlight either.

Highlighting is reset on:

 * `:noh[lsearch]`;
 * <kbd>Esc</kbd> and <kbd>Ctrl-C</kbd>;
 * actions that reload list of files (this is implicit, but I though that it's more useful than odd, you don't need to constantly reset highlight manually; most of the time highlight is useful only for a short period of time).

And this is what it looks like:

![vifm-search-highlight](https://cloud.githubusercontent.com/assets/459736/7550796/8a9db540-f678-11e4-9cb1-9cf45a6601e9.png)
