### ISSUE TITLE
Allow file overriding between compared panels

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#661]
Sometimes I miss the ability to override a file by the matched one in a `:compare` view. E.g., in
```
Pane 1 | Pane 2
a      | a
b      | b
```
I would like to select `b` in Pane 1 and issue `:copy!`, overriding `b` in Pane 2 by `b` in Pane 1.

I guess file operations are not allowed because they would possibly wreck the comparison view, but, specifically, the state after an `:copy!` is quite controlled: The overriden file and its pair become equal while the whole rest of each panel remains unaltered.

Am I missing something? Does my suggestion look good? Thanks!

**Comment by qsmodo** [comment]
As an alternative or addition, perhaps all operations could be allowed, provided that the user consents to re-execute `:compare` after each operation, even though it may take some time for large directories, I guess.

**Comment by xaizek** [comment]
Have you seen [<kbd>dp</kbd>/<kbd>do</kbd> shortcuts](https://vifm.info/vimdoc.shtml#vifm-dp)? It sounds like that's what you want to use.

**Comment by qsmodo** [comment]
I could swear I had tried them, and I did. But since I have `nnoremap d dd` it obviously did not work. Thank you for pointing the solution.
