### ISSUE TITLE
[Question] How to put selected filenames to stdin of extermal program with :!

### ISSUE THREAD

**Issue by PRESFIL** [vifm/vifm#662]

**Comment by qsmodo** [comment]
Something like `:!echo %f | externalprogram`? By the way you can use [Vifm Q&A](https://q2a.vifm.info/) for general purpose questions.

**Comment by PRESFIL** [comment]
This is not a bad way, but it can run into the limited length of `argv` (Am I correct in understanding that this is not a built-in `vifm`'s `echo`, but `/usr/bin/echo` ?).

I recently came across this. If `vifm` itself passed these lines directly to the program, there would be no restrictions. Then this behavior could be used as in `vim` (without reading stdout into the panel, of course).

**Comment by xaizek** [comment]
No, shell's `echo` is used.

There is no equivalent of Vim's `:write !cmd`. And the command name is already taken, so probably need something like `:pipe` (or maybe `:pipeto`/`:pipeout` so that we could add `:pipefrom`/`:pipein` later).

**Comment by PRESFIL** [comment]
> No, shell's echo is used.

I wonder if the shell builtins have a limitation on argv ...

**Comment by PRESFIL** [comment]
@qsmodo , I just now realized that `echo` prints file names *separated by spaces* and not through newlines, so this is not suitable in its pure form. :smiley:

**Comment by xaizek** [comment]
You can do `:!printf '%%s\n' %f | externalprogram` to get one file name per line.

> I wonder if the shell builtins have a limitation on argv ...

They might, for consistency with real executables.

**Comment by PRESFIL** [comment]
Okay, on my system, the maximum number of arguments for the shell builtin command is ~3400. It is possible that it also depends on the length of the names.

I was wondering if it is possible to redirect a list of files to `sxiv` like [here](ranger/ranger/pull#2307).

The use of `%f` has the same limitation on the content of newlines in the filename.
Hopefully it doesn't have the same limitation on the contained spaces in the filename.

But you can use `vifm`'s filters and sorting to select a specific subset of files. If there was a built-in command to redirect the list of files to stdin, there would be no such restrictions.

p.s. In some cases, null-delimited output like in `find . -print0` is required.

**Comment by xaizek** [comment]
You can try `stdin-pipe` branch:
```vim
" \n-delimited
:!sxiv %|l &
" null-delimited
:!sxiv %|z &
```
That WIP commit is only for backgrounded applications run via `:!`. Foreground commands work differently and need to think how to make it work there (probably by running them as-if in background).

**Comment by PRESFIL** [comment]
> You can try stdin-pipe branch:

Tried it - works in background, doesn't work in foreground as intended.

>  %|l &

It looks like ancient magic :) :mage:  but it seems there are no other options. `:|z!` `:|l!` ? `:!z` and `:!|` not allowed

**Comment by xaizek** [comment]
Alternatives also include `%Pl`, `%Pz`.

**Comment by PRESFIL** [comment]
> Alternatives also include %Pl, %Pz.

I think than It still looks like magic because it looks like a wildcard pattern, but it doesn't work the way it looks. It would not be bad for this to use a separate command group like `:!`, but this multiplies the number of such commands by 4 times: for `\n` and for `\l`.

Maybe you can come up with some flags like `!` `&` `?`?

**Comment by xaizek** [comment]
It's not just `:!`. It makes sense for user-defined `:commands` and `:file[x]type` handlers as well, that's why I did it via macros instead of a `:command`.

**Comment by xaizek** [comment]
That branch is now part of `master` with macros renamed to `%Pl` and `%Pz`. It works for background commands in `:!`, `:file[x]type` and user-defined :commands.

**Comment by PRESFIL** [comment]
Thank you! Should I close the issue because this will not only work with background processes, or just leave it open?

p.s. Didn't know that file filex was running in the background...

**Comment by xaizek** [comment]
> Thank you! Should I close the issue before this will work with forground processes too, or just leave it open?

We can leave it open. Presumably it's useful for foreground too.

> p.s. Didn't know that file filex was running in the background...

If you specify " &", it does.

**Comment by PRESFIL** [comment]
> We can leave it open. Presumably it's useful for foreground too.

It's very helpful. But I would like to leave the issue open, because at the moment this function has a strange behavior: if you yes start a process in the foreground, *`vifm` hangs*, and you *have to kill this child process* using a third-party program to get the `vifm` back. This is somewhat counterintuitive (at least for a new user).

**Comment by xaizek** [comment]
It hangs or that program wants for input? `%Pl` and `%Pz` should have no effect on foreground commands (e.g., on `:!sxiv %Pl -`).

**Comment by PRESFIL** [comment]
> It hangs or that program waits for input?

`sxiv` hangs. vifm passes the terminal to it. Apparently this is a `sxiv`'s issue. Maybe he's like a `sponge` waiting for the stdin to close. But it's hard for me now to find a similar program to test.

I'll write some script and check if the flow is for the foreground process or not.

p.s. I insert the template at the very end, I don't know if it makes any difference ... But I tried both ways to start `sxiv`: `:!sxiv %Pl -` and `:!sxiv - %Pl`.

p.p.s. Ooooh, now I understand. The foreground process takes its stdin from the terminal. So I cannot redirect the stream to it from `vifm`. I can also kill this process from the same terminal via `^C` and not worry that I accidentally kill `vifm`. Eureka! :brain:

**Comment by PRESFIL** [comment]
> p.p.s. Ooooh, now I understand. The foreground process takes its stdin from the terminal. So I cannot redirect the stream to it from `vifm`. I can also kill this process from the same terminal via `^C` and not worry that I accidentally kill `vifm`. Eureka! :brain:

If I understand correctly, then this is a conceptual problem, not a `vifm` problem and nothing can be done about it...

1) Some kind of check can be added, which will report an warning.
2) Or you can make it so that `%Pl` / `%Pz` makes the process call in the background forcibly.

**Comment by xaizek** [comment]
Input can be redirected independently from output, which can still be connected to the terminal.

**Comment by PRESFIL** [comment]
> Input can be redirected independently from output...

Yes, but without any redirections and pipelines both of them are directed to terminal emulator. This is the reason `sxiv` was not responding. And what I forgot about. Now it is clear to me that the problem is not with `vifm`.

**Comment by PRESFIL** [comment]
Thanks! :rocket:
