### ISSUE TITLE
Is there a way to remap "u" to "uu"?

### ISSUE THREAD

**Issue by matcharles** [vifm/vifm#665]
I'm trying to figure this out on my own but having a hard time. Thanks a lot!

**Comment by xaizek** [comment]
```vim
nnoremap <wait> uu u
```
and maybe
```vim
nnoremap u <nop>
```

**Comment by matcharles** [comment]
Works flawless, thanks a lot! I had the remap thing working, but couldn't find how to "disable" the inital u. Much appreciated!
