### ISSUE TITLE
Vifm displays wrong size of directory

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#666]
![image](https://user-images.githubusercontent.com/50843046/115915381-8be27300-a473-11eb-901c-14d86b41960d.png)
So as you can see, vifm shows that my `Download` directory is 4.1 KB big but if I go into the directory, I get this:

![image](https://user-images.githubusercontent.com/50843046/115915445-a0bf0680-a473-11eb-9d85-e33dd939c59e.png)
The `Test.pdf` file is `10.15 MB` big which is greater as 4.1 KB. Why does vifm show only 4.1 KB for my Downloaddirectory?

**Comment by iSeeU816** [comment]
You need to hit `ga` or `gA` (I always use the latter) to calculate a directory size.

Note that `gA` might take longer if the directory contains many items.
You can run `:jobs` command to check if it finished or not.
I have jobs count in the status line by having this `%{v:jobcount}` in `statusline` value.

See [ga](https://vifm.info/vimdoc.shtml#vifm-ga) and [gA](https://vifm.info/vimdoc.shtml#vifm-gA) for more info.

I'm not aware of any method to have directories calculated automatically, 
I _think_ it will affect the performance; so I do it manually when I needed to.

**Comment by xaizek** [comment]
Directory is a list of references to files and unless you calculate size of a directory explicitly (as @iSeeU816 nicely explained), you see amount of space taken up by the list.

**Comment by TornaxO7** [comment]
ok thank you for this information!

**Comment by xaizek** [comment]
By the way, see [`'dirsize'`](https://vifm.info/vimdoc.shtml#vifm-%27dirsize%27) option in case you find default behaviour confusing (you can show number of hardlinks, which corresponds to number of direct file entries + 2).
