### ISSUE TITLE
Vifm window raises Tmux activity flag

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#669]
To reproduce the problem, please

1. Start a plain Tmux and enable activity monitoring.
   ```
   tmux -f <(echo 'set -g monitor-activity on')
   ```
2. Now in Tmux, start a plain Vifm with `screen` integration.
   ```
   vifm --no-configs +screen
   ```
3. Select a raw text file and press Enter.

   - Expected: Vim opens in Tmux window 2 and that's all.
   
   - Actual: Vim opens in Tmux window 2 and Tmux raises the activity flag (`#`)
   of window 1 (Vifm's).

The activity flag is distracting and requires either making an effort to
ignore it or making a round trip 2->1->2 to set off the flag.

The flag is also raised if the file being edited is saved (`:w` in Vim).

I'm assuming that Vifm does take an UI action after step 3, otherwise this
would be a Tmux bug.

**Comment by xaizek** [comment]
I'm not sure that `monitor-activity` option makes sense for TUI applications. For step 3 update is probably [here](https://github.com/vifm/vifm/blob/master/src/running.c#L881. For `:w` it's an after directory change detection. At best, number of cases when this shows up can be reduced, but not eliminated.

**Comment by qsmodo** [comment]
I see. I don't think such minor benefit would warrant overhauling that
function; even less given your assessment that the issue cannot be completely
eliminated. Thank you for chiming in.
