### ISSUE TITLE
Use to browse to select a file, and write that filename to stdout?

### ISSUE THREAD

**Issue by bradparks** [vifm/vifm#67]
Hey... is there anyway I could invoke `vifm` to browse for a file, and output the "selected" filename to stdout on exit? Kind of like a command line "File Open" dialog?

I've posted a StackExchange question on this here, and was hoping Vifm might be used to do this...

http://unix.stackexchange.com/questions/171907/use-netrw-or-nerdtree-in-zsh-bash-to-select-a-file-by-browsing

It'd be really sweet if I could configure it (via an alias or bash script) to write the selected filename to stdout on hitting the `enter` key, or abort and write nothing if hitting the `esc` key...

Thanks!

**Comment by BMomani** [comment]
Hello 
the solution in https://unix.stackexchange.com/a/173692/149059 
did not work for me on Mac (iTerm and zsh)
they were talking about escaping and redirecting problems they fixed offline, 

could someone share the snippet that I need to use with these issues handled 
thanks a million

**Comment by xaizek** [comment]
Hi @BMomani,

That's an old answer, try this version instead:
```zsh
function insert_files() {
    local files=$(vifm --choose-files - < /dev/tty)
    while read path; do
        LBUFFER+="$(printf %q $path) "
    done < <(echo "$files")

    zle reset-prompt
}
zle -N insert_files
bindkey '^t' insert_files
```

The main difference is the use of `--choose-files` option, while old approach was hard-coding path to the output file for `-f` option and you might have configuration in a different place (under `~/.config` probably).
