### ISSUE TITLE
Command breaks when 'screen' is turned off.

### ISSUE THREAD

**Issue by BioBox** [vifm/vifm#670]
Vifm is easily one of the most important programs I use on the computer. So much so that I've decided to use it as my music player. I did this by writing dozens of commands and mappings to interface with [mpc](https://www.musicpd.org/clients/mpc/). However this bit of code only works when `screen` is on:

```vim
command mpcinsert mpc search filename "$(realpath --relative-to=$HOME/music %f)" | mpc insert %i
command mpciaplay :mpcinsert | if system('mpc | sed -ne 2p -- | cut -d " " -f 1') != '' | execute '!mpc next &' | else | execute '!mpc toggle &' | endif
```

When the playlist is empty, ```!mpc toggle &``` doesn't get executed.
When the playlist is _not_ empty, the song to be inserted will appear **one spot after** it's supposed to, and then `next` is called. So essentially it'll play the next song in the playlist as if it wasn't altered and you'll have to execute `mpc next` _again_ to play the song you actually want.
When `screen` is on it works exactly as intended.

You should be able to recreate this yourself by installing mpc with some public domain tracks, but I imagine there's a simpler example. I use the newest version of tmux btw.
Any ideas?

EDIT: I'm asking this because I have a seperate vifm session for music with the preferance that `screen` be set to off.

**Comment by xaizek** [comment]
Sounds and looks like a race condition. You're executing several external commands in background with no guarantee that they will be executed sequentially. It's probably sheer luck that it works with terminal multiplexer, although I'm not sure how it can influence this. I suspect that removing `%i` from your first command will fix everything. This version should also ignore output, but won't cause a screen redraw which is probably the reason behind using `%i`:

```vim
command mpcinsert :let $IGNORE = system(expand('mpc search filename "$(realpath --relative-to=$HOME/music %%f)" | mpc insert'))
```

**Comment by BioBox** [comment]
That's a neat little trick! I'm so used to using `%i` for everything that I didn't catch the race condition.
I more or less have all the functionality of a basic music player now, so I'll post everything onto the wiki after another week or so of use. Thanks.
