### ISSUE TITLE
Image Preview on Windows 10

### ISSUE THREAD

**Issue by jiDOK** [vifm/vifm#671]
I am using Vifm on Windows 10, loving it so far!

I'm trying to get Imgcat working with it (it is this one: [https://github.com/danielgatis/imgcat](https://github.com/danielgatis/imgcat))
Imgcat works fine in Windows terminal on its own, but I can't seem to get it to work as Vifm file preview.

I tried:
```
fileviewer {*.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm}
         \ imgcat %"c
```
but I get an error message in the preview pane: 
```failed to get the console state: The handle is invalid.```

I also tried:
```
fileviewer {*.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm}
         \ "C:\Users\jiDOK\scoop\apps\imgcat\1.0.5\imgcat.exe" %"c
```
but then I get:
```'C:\Users\jiDOK\scoop\apps\imgcat\1.0.5\imgcat.exe" "test.png' is not recognized as an internal or external command, operable program or batch file.```

also tried with ```%"f``` and also without the ```"``` with similar results.

Thank you!

**Comment by xaizek** [comment]
> it is this one

I suspect there are 10 `imgcat`s already. As if it's so hard to use some other name...

> failed to get the console state: The handle is invalid.

It's from the correct executable ([source file](https://github.com/danielgatis/imgcat/blob/2301caa726da29b10e8d4b85e1e18c6db08034a2/main_windows.go)).

The code assumes printing directly to the console, but by default Vifm captures output of the previewer to display it. You can try adding `%pd` macro and maybe it will work (I'm surprised to even hear about images in Windows console, so who knows).

**Comment by jiDOK** [comment]
Thanks a lot for your answer. Unfortunately it does not work, I get the same error messages, just not in the preview but after closing Vifm.
I am going to head over to danielgatis/imgcat and ask there, since it is related to the output of imgcat if I understand you correctly. Maybe he has an idea how to do it, if not I'm gonna be content with what is possible. Or maybe Alacritty will add image preview one day. Thanks again!

**Comment by xaizek** [comment]
> I get the same error messages

Right, my bad. With `%pd` output is still captured, it's just that it's printed to the console as is.

I looked at `imgcat` again and it prints 24-bit escape codes, which Vifm doesn't interpret. So if requirement about output being directly to the console is lifted, you'll still need to add `%pd`.

**Comment by jiDOK** [comment]
Danielgatis kindly provided a fix, alas, the preview only nearly works. Because of the 24-bit issue you mentioned the images look like this:

![Imgcat01](https://user-images.githubusercontent.com/31440442/117209590-d3afb580-adf6-11eb-96e4-00eb1e3ce0fe.PNG)

Adding %pd leaves the preview pane black and instead prints what I assume are the escape codes in console in the background as text. I can see them when I exit Vifm to the console.

I'm curious, is there a specific reason 24-bit codes are not supported? Do other preview tools do it differently?

**Comment by xaizek** [comment]
Image preview can also use 256-colors palette, which works (I think only in ConEmu on Windows). True color support just wasn't implemented, ncurses added it several years ago. However, on Windows [PDCurses](https://github.com/wmcbrine/PDCurses) is used and I don't think it has support for true colors.

**Comment by jiDOK** [comment]
Oh ok, I understand. Well thanks for your help anyway! I'll close the issue.
