### ISSUE TITLE
Cannot change case of a filename on HFS+ volume

### ISSUE THREAD

**Issue by dmlemos** [vifm/vifm#672]
Renaming the case of a filename doesn't work. `test` -> `Test`
Error:
```
mv: cannot move '/Volumes/Data/test' to a subdirectory of itself, '/Volumes/Data/Test/test'
```
Vifm 0.11

Using finder, the case changes successfully.
This bug is similar to #367, but on a different filesystem.

**Comment by xaizek** [comment]
> mv: 

I don't know how to make `mv` perform case change on case-insensitive FS. You can try `set syscalls`, then it should work on OS X.

**Comment by dmlemos** [comment]
> I don't know how to make mv perform case change on case-insensitive FS. You can try set syscalls, then it should work on OS X.

Could you point out how could I do that?

**Comment by xaizek** [comment]
Execute `:set syscalls` command to test and put it to `vifmrc` if it works as expected.

**Comment by dmlemos** [comment]
It works a treat :)

Any reason why wouldn't this be the default? I'd like to understand if there is any risk of losing data, or any other I should be aware of.

**Comment by xaizek** [comment]
Well, it's on by default for new users for the last 3 years. Options is turned off internally, but sample `vifmrc` contains `set syscalls`.

Standard tools might be better tested and can be more portable. However, in terms of safety, I would say that bugs can be both in invocation of external tools and in native implementation, so turning it on shouldn't make much difference in this regard.

The option itself is there for 6.5 years, me and others are using it for this long without trouble. Some bugs show up only when it's either on or off, but in all 3 cases of data loss bugs over the years it didn't make any difference (for better or for worse).
