### ISSUE TITLE
Opening the wrong file when searching

### ISSUE THREAD

**Issue by sfpvk** [vifm/vifm#673]
Hello,  when searching for file in directory which contain more than one match then attempt to open file will select wrong name. I have write commands for reproducing, first part - from console, second - from vifm.
```
/ $ cd /tmp
/tmp $ mkdir test
/tmp $ cd test
/tmp/test $ touch file_{1,2}
/tmp/test $ vifm

/file<Enter>
n
l
```
Expected: file_2 will be opened (because of cursor points to it). But in fact file_1 is opened.

**Comment by xaizek** [comment]
Hi.

Disable [`'hlsearch'` option](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27). What happens is that search selects two files and when you press <kbd>l</kbd>, *both* are opened, you just see the first one initially (Vim has `:next` and `:previous` command to switch between files specified on command line).

**Comment by sfpvk** [comment]
Thanks a lot, sorry for the inattention.
