### ISSUE TITLE
Change Default Text Editor

### ISSUE THREAD

**Issue by Raghav-Dixit** [vifm/vifm#674]
I realize that the program is vim focused, but is there a way to change the default text editor in vifm?
I tried to use the same format as the other file types, but it does not seem to work.
```
filetype {*.txt}, <text/*>
    \ kak,
```
I use Kakoune as my text editor.

**Comment by xaizek** [comment]
Set [`'vicmd' option](https://vifm.info/vimdoc.shtml#vifm-%27vicmd%27). However, mind that not everything will work as Vim-compatible arguments are assumed in some places (#651).

Your `filetype` command probably didn't work because you placed it after `filetype *` in `vifmrc`.
