### ISSUE TITLE
Documents directory not showing up

### ISSUE THREAD

**Issue by alexb7711** [vifm/vifm#677]

**Comment by alexb7711** [comment]
Apologies on closing/reopening. Just got a new split keyboard and I fat fingered the heck out of this issue.

The issue I'm having is that my Documents directory does not show up in vifm. I can't find anything in the manual that deals with hiding directories/files. I was hoping someone would be able to shed some light on the situation.

**Comment by xaizek** [comment]
Run `:filter?`. You probably filtered the directory out with [<kbd>zf</kbd>](https://vifm.info/vimdoc.shtml#vifm-zf) or [`:filter ...`](https://vifm.info/vimdoc.shtml#vifm-%3Afilter) at some point.

**Comment by alexb7711** [comment]
Yup, that is it. Much appreciated!
