### ISSUE TITLE
Specify a positive filter on command line

### ISSUE THREAD

**Issue by pgimalac** [vifm/vifm#678]
Hi, I'm trying to open `vifm` and specify it, on command line, to only display files that matches a regex (specifically this regex `^.*\.PKGBUILD$`).

I know that doing `=^.*\.PKGBUILD$` in `vifm` works, so I tried `vifm -c "=^.*\.PKGBUILD$" <directory>`, without success...

Does `-c` works with `=` commands ? Or is it just `:` ? I know that `vifm -c ":filter ^.*\.PKGBUILD$" <directory>` works and does the exact opposite of what I'm trying to do.

I also tried `vifm -c ':filter ^(?!.*\.PKGBUILD)$' <directory>`, without success either since the syntax is invalid... I couldn't find documentation about the regex used, so I don't know if there is an accepted way to write negative lookaround ?

How can I see in an instance of `vifm` what filters are applied ? I want to check that my shell doesn't change anything to my command, and that the filter is really received by vifm.

Thank you very much.

**Comment by xaizek** [comment]
Hello,

> Does `-c` works with `=` commands ?

It doesn't, it's just `:commands`. The colon there is optional.

> I couldn't find documentation about the regex used, so I don't know if there is an accepted way to write negative lookaround ?

It's not supported. [Filters](https://vifm.info/vimdoc.shtml#vifm-filters):

    Note: vifm uses extended regular expressions.

See `man 7 regex` for what it means.

> I know that `vifm -c ":filter ^.*\.PKGBUILD$" <directory>` works and does the exact opposite of what I'm trying to do.

Invert the pattern by adding `!` ([docs](https://vifm.info/vimdoc.shtml#vifm-%3Afilter)):

    vifm +'filter! {*.PKGBUILD}' <directory>

> How can I see in an instance of `vifm` what filters are applied ?

```vim
:filter?
```

**Comment by pgimalac** [comment]
This https://vifm.info/vimdoc.shtml#vifm-filters was exactly the documentation I looked for without success.

> Invert the pattern by adding `!` ([docs](https://vifm.info/vimdoc.shtml#vifm-%3Afilter)):
`vifm +'filter! {*.PKGBUILD}' <directory>`

This is so much more readable than my regex :)

> :filter?

And this was exactly what wanted too

You answered each of my questions, thank you very much
