### ISSUE TITLE
[Question] How to use ripgrep for :find command?

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#679]
I tried to set it with:
```vim
set findprg="rg --files | rg %s"
```
but I'm getting this error message if i use it:

![image](https://user-images.githubusercontent.com/50843046/119537162-0e6b9480-bd8a-11eb-87a4-2ec7e237f851.png)

What am I doing wrong?

**Comment by TornaxO7** [comment]
Oh hold on, I just found out that this `--max-count` belongs to ripgrep... well... sorry!

**Comment by TornaxO7** [comment]
Hm.. ok, I still can't find a way, how to fix this. Does anyone has an idea?

**Comment by xaizek** [comment]
How do you invoke the `:find` command?

**Comment by TornaxO7** [comment]
```bash
:find main
```
for example.

**Comment by xaizek** [comment]
And running `rg --files | rg main` works? In shell and via `:!` in Vifm.

**Comment by TornaxO7** [comment]
![image](https://user-images.githubusercontent.com/50843046/119576187-9072b200-bdb8-11eb-9247-c2612b81248d.png)

Yes

**Comment by xaizek** [comment]
What actually gets run is `rg --files | rg . -name main` and `-n` is probably a short form of `--max-count`. Try:
```vim
set findprg="rg --files %s | rg %p"
```
This should work assuming that `rg --files` can accept list of paths.

**Comment by TornaxO7** [comment]
Yeah!!! It works. Thank you c(^-^)c
