### ISSUE TITLE
Compare directories, ignore filtered (or binary) files?

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#683]
Suppose one compares two directories with different versions of a C project to find out which `.[ch]` files are different. If the code has been compiled, the compare view becomes much less usable because Vifm will also (correctly) mark the binary files (e.g. `.o`) as different.

Hence an option to disable comparison of binary files might be very handy. Or maybe make the comparison heed filters such as `:filter !/.*\.o/`?

**Comment by xaizek** [comment]
> Or maybe make the comparison heed filters such as `:filter !/.*\.o/`?

This makes more sense because dot-file filter is already obeyed by `:compare`. Don't remember why `:filter` isn't, maybe for no particular reason.

**Comment by qsmodo** [comment]
I'll look into implementing this, can you please let me know if my reasoning below is correct?

Besides dotfiles filter, both local and permanent filters should be honored. Moreover, the filters of the pane 1 must be combined with the corresponding filters of pane 2. I.e., given

```
       | !{*.o}  |         | !{*.bak}
Pane1  | Pane1   |  Pane2  | Pane2
o1.o   |         |  o2.o   | o2.o
b1.bak | b1.bak  |  b2.bak |
c1.c   | c1.c    |  c2.c   | c2.c
```
The `:compare` should result in
```
Pane1  |  Pane2
c1.c   |  c2.c
```

**Comment by xaizek** [comment]
> Besides dotfiles filter, both local and permanent filters should be honored.

Yes, there is `filters_file_is_visible()` function in `filtering.c` that checks if a path passes those filters.

> Moreover, the filters of the pane 1 must be combined with the corresponding filters of pane 2.

No, filtering can be done per view (as dotfiles filter is used). This way you compare what you see.
