### ISSUE TITLE
:goto does not work on Windows with subdir

### ISSUE THREAD

**Issue by Grueslayer** [vifm/vifm#685]
If you enter a path on Windows with `:goto` if will not switch to that dir, e.g.

```
:goto c:\\windows\\system
```
The path is correctly validated: If you enter an invalid path you'll receice an error.

But the directory keeps the same and file (if given) will not be marked.

If you use the *wrong* path seperator, it is working:

```
:goto c:/windows/system
```

This is a problem if not usisng by hand but an output from an external call.

**Comment by xaizek** [comment]
Yes, looks like a bug, thanks for the report.

> If you use the _wrong_ path seperator, it is working:

It is uncommon, but it's not wrong. Windows API recognizes both `\` and `/` even though not all applications (or even builtins of `cmd.exe`) handle both variants.

**Comment by Grueslayer** [comment]
Therefore in italics 😁

**Comment by xaizek** [comment]
> Therefore in italics

I believe it should be in quotes instead. Italics emphasizes text without drawing too much attention to it (as opposed to bold).

You can download dev-build with the fix from [here](https://builds.vifm.info/) if this bug bothers you.
