### ISSUE TITLE
Hostname in sshfs options

### ISSUE THREAD

**Issue by willemw12** [vifm/vifm#69]
Question:

The host in the ssfs options has to be an ip-address, not a hostname:

    <user>@<host>:/ -p <port> -o follow_symlinks

Being able to specify a hostname, will this be possible in a future release of vifm?

I mean DNS hostnames, not static hostnames in /etc/hosts.

**Comment by xaizek** [comment]
Erm, not sure I follow. Why would you assume that? I do use it with hosts defined in `/etc/hosts`, `~/.ssh/config`, IP-addresses and DNS-names. Vifm doesn't depend on this information because it just forwards it to a FUSE mounter.

Maybe something affects mounting in case of DNS-names. You can try debugging it by starting vifm with `--logging` option and searching for `FUSE mount command:` in `~/.vifm/log` after failed mount try. Maybe the command is messed up in some way, that would cause a failure.

**Comment by willemw12** [comment]
Ignore this issue. It is an issue with sshfs I have. It has nothing to do with vifm.

**Comment by xaizek** [comment]
OK, I'll close it then. In case it will be useful for you, here is information about my `sshfs`, which doesn't have this issue:
```
$ sshfs --version
SSHFS version 2.2
FUSE library version: 2.8.5
fusermount version: 2.8.5
using FUSE kernel interface version 7.12
```

**Comment by willemw12** [comment]
Problem solved. It was just a typo in the hostname.

**Comment by xaizek** [comment]
> You cannot enter a password.

Do you have `%FOREGROUNG` somewhere in your `:filetype` command for `*.ssh` files? If not, add it. It clears screen and disables tracking of cancellation requests, in other words it lets third-party program accept user input without interference.

> Expected a password prompt (on the status bar).

Not sure if this is possible. `ssh` is very picky about passwords, e.g. you can't just redirect it or pass it as a parameter. There are some ask-pass programs, so vifm would need to provide one to hijack password enter request, then it would interact with vifm instance and return result to `ssh`. It might be problematic to implement on its own (although I didn't try it) and `ssh-agent` or `gpg-agent` make this even worse by remembering TTY at which they were launched.

**Comment by willemw12** [comment]
filetype *.ssh
       \ {Mount with sshfs}
       \ FUSE_MOUNT2|sshfs %FOREGROUNG %PARAM %DESTINATION_DIR,

I don't see any difference. Doesn't clear the screen and doesn't allow me to enter a password.

If you want to enter a password for an ssh connection, you could always mount your own sshfs (outside vifm).

**Comment by xaizek** [comment]
Sorry, this time I made a typo, it's `%FOREGROUND` (**D** at the end, not **G**).

**Comment by willemw12** [comment]
Still makes no difference (vifm 0.7.8). Putting `%CLEAR` before `sshfs` clears the screen, so I am editting the correct filetype definition.

**Comment by xaizek** [comment]
> vifm 0.7.8

That explains it. I thought you're using development version, where `%FOREGROUND` obsoletes `%CLEAR` and fixes #62.

**Comment by willemw12** [comment]
With the latest development version: screen is cleared and there is a password prompt. However, the password is not accepted (there is not special to see in the 'log').

**Comment by xaizek** [comment]
That's strange. It should be the opposite: input is not accepted and Ctrl-C cancels prompt with 0.7.8 and input is accepted (and Ctrl-C works, but differently) for `master`.

**Comment by willemw12** [comment]
Correction, entering a password works.
