### ISSUE TITLE
How do donate

### ISSUE THREAD

**Issue by MDingas** [vifm/vifm#692]
I've only found one issue that is more than a year old about this. Is there a way to donate to the project? Vifm has easily become my most used tool and I'm sure of the same for others too, and I'd love to contribute.

**Comment by xaizek** [comment]
Thanks, I appreciate it, but that issue is up to date. There is no way at the moment and I'll comment in #509 if something changes (I can always accept BTC I guess, but it doesn't seem to be generally usable).
