### ISSUE TITLE
creating a new file suggestion/question

### ISSUE THREAD

**Issue by GummyGun** [vifm/vifm#693]
**Is there any key that you can press so that you create a file directly in current folder?**
if not i would suggest adding a keymap in the "o" key that does this, maybe even "O" to create and enter directly to edit it.
something like the "%" in netRW

**Comment by xaizek** [comment]
You can do a mapping yourself:
```vim
nnoremap <silent> o :touch<space>
```

**Comment by GummyGun** [comment]
hate to bother but I'm lost trying to find a way to minimize vifm through sigSTOP, in vim you can use the `:stop` command. 
I've tried `nnoremap <a-e> <c-z>` but found no success 
and...
how can i map <a-a> to close the command-line like <Esc>
