### ISSUE TITLE
Problem with long vimcmd

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#696]
Put this into your `.bashrc` or `.zshrc`:
```zsh
export EDITOR="neovide --multiGrid"
```

Put this into your `.vifmrc`:
```vim
set vicmd="$EDITOR"
```

# Error
I'm getting the following error message:

```
zsh:1: command not found: neovide --multiGrid
```

But if I use this instead:
```vim
set vicmd="neovide --multiGrid"
```
then everything works fine.

**Comment by xaizek** [comment]
Vifm doesn't expand environment variables in `'vicmd'`, it just runs `$EDITOR path` and unlike Bash, Zsh doesn't like it:
```
$ EDITOR='vim -p'
$ $EDITOR disowntty.c
zsh: command not found: vim -p
```
Use this instead:
```vim
let &vicmd = $EDITOR
```

**Comment by TornaxO7** [comment]
Thank you! It's working! :)
