### ISSUE TITLE
[Question] Preview stuff with icat

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#699]
Just a little question if you know someting about it:

I switched to the `kitty` terminal and I'd like to use the builtin [icat](https://sw.kovidgoyal.net/kitty/kittens/icat/) image previewer. Do you think that this is possible?

Currently I have this (`~/.config/vifm/scripts/kittyimg`):
```bash
#!/bin/bash

test_support="kitty +kitten icat --detect-support $5"
$test_support 2> /dev/null

# if the file is not supported => cancel!
if [ ! $? -eq 0 ]; then
    exit
fi

# otherwise preview the file
kitty +kitten icat --clear
kitty +kitten icat --place "$1"x"$2"@"$3"x"$4" $5
```

And I have this in my `vifmrc`:
```vifm
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.xpm,*.gif
        \ kittyimg %pw %ph %px %ph %f
```

but somehow vifm is getting corrupted:

![image](https://user-images.githubusercontent.com/50843046/127640951-1fa6053d-5405-4183-93e3-d9afec82fa74.png)

**Comment by xaizek** [comment]
Try adding [`%pd` macro](https://vifm.info/vimdoc.shtml#vifm-%25pd), because it seems to be printing out the image. Not sure how well it will work though (it might remember position which you specify).

**Comment by TornaxO7** [comment]
Hm... doesn't work either. I think that I'll have to stick to ueberzug then. Thank you for your quick response! :)

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/issues/1308

**Comment by TornaxO7** [comment]
@kovidgoyal Thank you for answering :D It works now!
