### ISSUE TITLE
"Press return ..." message appearing terminal/iterm on mac osx

### ISSUE THREAD

**Issue by reicheltd** [vifm/vifm#7]
Hi xaizek,

when I open a file through vifm in my terminal, e.g. with my editor (vim) or another application (via followlinks) and I close the file / or go back to vifm, it gives me the "Press return ..." in my terminal window. I use iterm2, but its the same in the terminal. It just looks like this....

```
~vifm                                                                                                                                 
Press return ...
```

In the changelog 0.7.3a to 0.7.4 there is,
- Fixed "Press return..." message appearing always on OSX.

Was is about this issue? I am running the newest version.

Best regards,
Daniel

**Comment by arings** [comment]
Hello xaizek!

Same bug happens under Ubuntu 16.04.3 LTS, bash, urxvt, also tested in gnome-terminal.

It happens upon opening or viewing file. I did some experiments with different mappings:

```
" nnoremap <f3> :!less %f<cr> <-- bug 100%
" nnoremap <f4> :edit<cr> <-- bug 50%
" nnoremap <f4> :!vim %f<cr> <-- bug 100%
" nnoremap <f4> :!nvim %f<cr> <-- no bug!
```

Interesting, that in first case with `less` command, after exiting by pressing "q", and getting "press return..." -- after pressing return selector is in opposite pane, like I would press "tab". Same thing happens if I will swap/exchange panels.

That happens only with `less` -- not with `edit` or `vim` (version 8.0)

No such bug happens with `neovim`.

I tested that with `vifm` from ubuntu repositories, and with latest, compiled from sources.

Thanks!

**Comment by xaizek** [comment]
Hi arings!

I've downloaded VM with that version of Ubuntu, but can't reproduce the behaviour, installed all updates and urxvt, still the same.

Does it occur if you run `vifm --no-configs` and do `!less %f` (exit vifm with `:q!` to don't overwrite `vifminfo`)? And if you run `less`/`vim` on command line, what's their return code (`less something; echo $?`)?

**Comment by arings** [comment]
Yes, same occurs with `vifm --no-configs` and `!less %f`, but not each time, it's like 50% attempts, and there is no pane switching.

`less/vim` both exit code is 0.

**Comment by xaizek** [comment]
> and there is no pane switching.

So maybe it's caused by something in `vifmrc`, although nothing comes to mind.

> Yes, same occurs with vifm --no-configs and !less %f

Please try logging what's going on by passing `--logging` switch (`--no-configs` shouldn't be needed), the log will be at `~/.vifm/log`. It should be quite short to post, but you can also attach it to the message.

**Comment by arings** [comment]
In `vifmrc` I have only those mapping attempts and in the end of file only `set syscalls`, the rest is default.
I forgot to tell that I'm using `i3wm` also, maybe it will shed some light.

Here is the log:

```
18.01.07 21:44 ===== Started vifm =====
18.01.07 21:44 at ui/ui.c:550 (update_geometry)
               Load stage: 0
               New geometry: 90x75
18.01.07 21:44 at modes/modes.c:99 (init_modes)
               Entered into this function
18.01.07 21:44 at signals.c:178 (setup_signals)
               Entered into this function
18.01.07 21:44 at trash.c:212 (create_trash_dir)
               Entered into this function
18.01.07 21:44 at trash.c:229 (try_create_trash_dir)
               Entered into this function
18.01.07 21:44 at ui/ui.c:550 (update_geometry)
               Load stage: 2
               New geometry: 90x75
18.01.07 21:44 at ui/ui.c:444 (resize_all)
               Load stage: 2
               screen_y = 75; screen_x = 90
18.01.07 21:44 at event_loop.c:88 (event_loop)
               Entered into this function
18.01.07 21:44 at modes/modes.c:211 (modes_redraw)
               Entered into this function
18.01.07 21:44 at ui/ui.c:550 (update_geometry)
               Load stage: 3
               New geometry: 90x75
18.01.07 21:44 at ui/ui.c:444 (resize_all)
               Load stage: 3
               screen_y = 75; screen_x = 90
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/utils.c:95 (vifm_system)
               Load stage: 3
               Shell command: less testfile
18.01.07 21:45 at ui/ui.c:550 (update_geometry)
               Load stage: 3
               New geometry: 90x75
18.01.07 21:45 at ui/ui.c:444 (resize_all)
               Load stage: 3
               screen_y = 75; screen_x = 90
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/fs.c:328 (get_link_target)
               Entered into this function
18.01.07 21:45 at utils/utils.c:95 (vifm_system)
               Load stage: 3
               Shell command: less testfile
18.01.07 21:45 at utils/utils_nix.c:223 (get_proc_exit_status)
               No child processes
               waitpid()
18.01.07 21:45 at running.c:842 (shellout)
               Subprocess (less testfile) exit code: 255 (0xff); status = 0xffffffff
18.01.07 21:45 at utils/utils_nix.c:223 (get_proc_exit_status)
               No child processes
               waitpid()
18.01.07 21:45 at ui/ui.c:550 (update_geometry)
               Load stage: 3
               New geometry: 90x75
18.01.07 21:45 at ui/ui.c:444 (resize_all)
               Load stage: 3
               screen_y = 75; screen_x = 90
```

First time viewing the file was correct, second time -- with `press return...`

**Comment by xaizek** [comment]
Thanks, it looks like this exact issue, however the fix is still there and I don't get how behaviour can depend on application that is being run...

> In vifmrc I have only those mapping attempts and in the end of file only set syscalls, the rest is default.

Then maybe sample settings cause it somehow, don't see how would they, though.

> I forgot to tell that I'm using i3wm also, maybe it will shed some light.

Works fine inside i3wm for me.

By the way, I assumed that you're using 64-bit system, is this correct?

Otherwise, I'm pretty much have no more ideas for now. Except for maybe trying to run vifm as a different user (guest/root) where environment is different, it's weird that you get the issue repeatedly, but I can't make it happen.

**Comment by arings** [comment]
64-bit system, correct.

I did logged as a different user, there is no such weird behavior! It's narrowed down now, need to check what is wrong with my environment.

Thank you very much!
