### ISSUE TITLE
Windows compile error

### ISSUE THREAD

**Issue by joshaw** [vifm/vifm#70]
The INSTALL instructions give info for compiling on windows. Using these, I am getting compile errors relating to the use of the function `strdup`:

```
gcc -c -Wall -Werror -MMD -DPDC_WIDE -D_XOPEN_SOURCE  -include ../config.h -D_FILE_OFFSET_BITS=64 -g -O0 cfg/config.c -o cfg/config.o
cfg/config.c: In function ‘init_config’:
cfg/config.c:120:2: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
  cfg.time_format = strdup(" %m/%d %H:%M");
  ^
cfg/config.c:120:20: error: incompatible implicit declaration of built-in function ‘strdup’ [-Werror]
  cfg.time_format = strdup(" %m/%d %H:%M");
                    ^
cc1: all warnings being treated as errors
Makefile.win:120: recipe for target 'cfg/config.o' failed
make: *** [cfg/config.o] Error 1
```

I believe theses are warnings that are treated as errors by the `-Werror` flag, but I don't know how to give any more useful information. I'm using win7 with cygwin.

**Comment by xaizek** [comment]
`strdup()` is declared in `<string.h>`, which is included by `cfg/config.c`, so I'm not sure why it's complaining. It might be that some feature define (like `_XOPEN_SOURCE`) is missing.

**Anyway**, it appears to me that you're trying to compile in Cygwin by following instructions provided for MinGW. For Cygwin one should use instructions given for Unix systems as that's what Cygwin emulates. Just proceed with regular `./configure [some options here] && make`. `Makefile.win` is specifically for version that uses Windows native API.

**Comment by joshaw** [comment]
Well that was a lot simpler than I had made it. I had assumed the windows instructions applied to any compilation method on a windows machine and hadn't thought about cygwin affecting that.
Thanks for the quick reply and this program, most helpful.

**Comment by joshaw** [comment]
Much obliged for the reference.
