### ISSUE TITLE
Display issues with umlauts (macOS)

### ISSUE THREAD

**Issue by 0xDP** [vifm/vifm#700]
Hello,

I have issues with the display of umlauts in some places. To demonstrate this, I've created a directory with umlauts. After starting with `vifm --no-configs` the statusline still looks correct.

<img width="797" alt="1" src="https://user-images.githubusercontent.com/40469443/128634313-fc993a15-f3d6-4db6-a54d-df6d7a33e593.png">

 If I set a custom statusline with `:set statusline=%t`, garbage is displayed instead of the filename.

<img width="798" alt="2" src="https://user-images.githubusercontent.com/40469443/128634324-f0a34a98-18b2-44e7-9809-c118efee0515.png">

The same happens with the topline when I change to this directory.

<img width="798" alt="3" src="https://user-images.githubusercontent.com/40469443/128634333-b5cf09b5-95d0-43d3-a81b-6109429063c0.png">

It seems to be that in some places umlauts are not handled correctly.

Dennis

**Comment by xaizek** [comment]
Hi,

What's your locale (output of `locale` command in terminal)?

**Comment by 0xDP** [comment]
```
% locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL="en_GB.UTF-8"
```

**Comment by xaizek** [comment]
Is it possible that your drive is mounted using non-UTF8 encoding? Maybe `mount` will help, unless default value for some mount option is non-UTF8.

**Comment by 0xDP** [comment]
It's a standard macOS installation and everything looks fine in the first screenshot, so I don't think the disc is mounted incorrectly.

**Comment by xaizek** [comment]
First screenshot doesn't prove much, because there is no processing of the file name. `%t` on status line of the second screenshot appends text and title on the third screenshot has ellipsis. If encoding is wrong, it might not show up unless you change the string in some way. I also don't know what else can be the reason, because Vifm doesn't care about encoding unless it conflicts with UTF8 (local encodings with character codes > 127 cause conflicts and that's where umlauts would be).

**Comment by 0xDP** [comment]
The disc is formatted as apfs and also mounted with this option.When I do `:set viewcolumns=-9{name}..` the dots above the A are missing. Can you reproduce this when a file or directory name contains öäüßÖÄÜ?

<img width="400" alt="4" src="https://user-images.githubusercontent.com/40469443/128637895-cf9c1adb-c02d-48c8-9ae3-65937a8c8043.png">

**Comment by xaizek** [comment]
Everything looks fine on Linux. However, I do see all the issues on OS X with hfs partition. In Unicode dots of umlauts can be printed as a separate character, that could explain why they disappear.

Will look into what might be the reason. Thanks for the report.

**Comment by 0xDP** [comment]
I can confirm that the issue is no longer reproducible.
