### ISSUE TITLE
Full-screen view mode while keeping the vertical split

### ISSUE THREAD

**Issue by BioBox** [vifm/vifm#704]
Is there any option to have the view mode use the entire screen _without_ switching to the one window view beforehand? My moniter's a bit samll, and it would be nice not having to run `:vs!` before and after I view each file. I want it to go back to the two-window mode when I'm finished viewing a file.

**Comment by xaizek** [comment]
There is no option, but you can make a mapping (<kbd>w</kbd> in this case):
```vim
nnoremap <silent> w : execute 'normal e'
                   \| if layoutis('vsplit')
                   \|     execute 'qnoremap w q:vsplit|qunmap w<lt>cr>'
                   \|     only
                   \| elseif layoutis('hsplit')
                   \|     execute 'qnoremap w q:split|qunmap w<lt>cr>'
                   \|     only
                   \| endif
                   \| <cr>
```

**Comment by BioBox** [comment]
Yep, it works, but I would use `normal! e` instead.
And since I use `q` to quit view mode I had to modify that as well. So here's what I'm using (same key):
```vim
nnoremap <silent> w : execute 'normal! e'
                   \| if layoutis('vsplit')
                   \|     execute 'qnoremap q q:vsplit|qunmap q<lt>cr>'
                   \|     only
                   \| elseif layoutis('hsplit')
                   \|     execute 'qnoremap q q:split|qunmap q<lt>cr>'
                   \|     only
                   \| endif
                   \| <cr>
```
Thanks for your help. I wouldn't have known how to escape the `<`.
