### ISSUE TITLE
Add mode bits (e.g. 755)

### ISSUE THREAD

**Issue by iSeeU816** [vifm/vifm#707]
Hello,

Could you add mode bits in these areas?

1. Status line.
   - This is what I care about the most now.
2. A Column field.
3. `Ctrl-G` (detailed information dialog).
   - Before: "Permissions: drwxr-xr-x".
   - After: "Permissions: drwxr-xr-x (755)".
   - I think moving "Permissions" near "Owner" and "Group" makes sens as
     they are somehow related.

----------------

As side note, "About" description for this project needs minor treatment
like in [this commit](https://github.com/vifm/vifm/commit/8ec9aaec3763f28f0b143b7821dd216c4ba61bea).

Thank you!

**Comment by xaizek** [comment]
Hi.

> A Column field.

This one is already there actually, "mode" column.
