### ISSUE TITLE
Improved zip command config

### ISSUE THREAD

**Issue by gerazov** [vifm/vifm#709]
Currently the default setting maps zip as:
```vim
command! zip zip -r %f.zip %f
```
If `%f` is a selection of files this ends up recursing file by file or? :thinking: 

There's a nice [Q&A](https://q2a.vifm.info/410/how-zip-selected-files-in-vifm) by xaizek on defining zip:
```vim
command! zip if [ -n "%a" ]; then
           \     zip -r '%a.zip' %f;
           \ fi
```
which allows the user to give the name of the archive and if none is provided doesn't zip.

It would be nice to expand this to zip the files to a zip archive with the name of the current folder like in Dolphin, so I rewrote this like so:
```vim
command! zip if [ -n "%a" ]; then
           \     zip -r '%a.zip' %f;
           \ else
           \     zip -r '%d.zip' %f;
           \ fi
```
but it doesn't seem to work, any help?

**Comment by xaizek** [comment]
```vim
command! zip if [ -n "%a" ]; then
           \     zip -r '%a.zip' %f;
           \ else
           \     zip -r %d:t.zip %f;
           \ fi
```
This is really a question for Q&A site though (you can login via GitHub there).

**Comment by gerazov** [comment]
I agree, but was thinking it can get included in the new default rc.

**Comment by xaizek** [comment]
It's still quite fragile and will break for arguments with quotes, but I'll fix the command to handle multiple files like this:
```vim
command! zip zip -r %c.zip %f
```

**Comment by gerazov** [comment]
I think having `%d:t` makes more sense, e.g. you're in an images folder called `backgrounds/` and you want to pack a few for sending.

**Comment by xaizek** [comment]
Then `%d:t` will be used for single files as well.

**Comment by gerazov** [comment]
Oh I see ... it would be ok if you can check the length of %f, or limit %f to mean selected files only, but that sounds like too much work :slightly_smiling_face:

**Comment by xaizek** [comment]
One can use `%c == %f` to check for multiple files, I'm just not sure about embedding specific shell syntax in simple sample commands.

**Comment by gerazov** [comment]
So the final (complex) version would be:
```vim
command! zip if [ -n "%a" ]; then
           \     zip -r '%a.zip' %f;
           \ elseif [ %c == %f ]; then
           \     zip -r %c.zip %c;
           \ else
           \     zip -r %d:t.zip %f;
           \ fi
```

**Comment by gerazov** [comment]
ok added it to the Q&A :+1:

**Comment by amigthea** [comment]
> So the final (complex) version would be:
> 
> ```viml
> command! zip if [ -n "%a" ]; then
>            \     zip -r '%a.zip' %f;
>            \ elseif [ "%c" = "%f" ]; then
>            \     zip -r %c.zip %c;
>            \ else
>            \     zip -r %d:t.zip %f;
>            \ fi
> ```

I can't get this to work, it gives me the error:

```
zsh:1: parse error near `zip'
Press return ...
```

**Comment by xaizek** [comment]
> I can't get this to work, it gives me the error:
> 
> ```
> zsh:1: parse error near `zip'
> Press return ...
> ```

Replace `elseif` with `elif`.  Bash allows both even though its man page mentions only `elif`.
