### ISSUE TITLE
Does vifm use a tmp directory for file transfers?

### ISSUE THREAD

**Issue by ootput** [vifm/vifm#71]
I ask as I'm experiencing slow writes between panes when both source and dest paths are on the same local filesystem - and the window is virtually unusable during the transfer. At the shell, the transfer is instantaneous. I can't find any documentation in vifm help regarding this matter.

**Comment by xaizek** [comment]
Generally, it doesn't. However, depending on value of `'trashdir'` option vifm might copy file to trash and then copy it back. This can happen if you delete file with `dd` in one pane and `p` in another one. Could you post output of `:set trashdir` here?

As for UI responsibility, screen is not always updated during blocking operations, which is generally OK unless you trap on long running operation which you don't expect. I agree that this should be improved.

**Comment by ootput** [comment]
Currently its:

 trashdir=/home/ootput/.vifm/Trash

**Comment by xaizek** [comment]
Try configuring it like this:
```
set trashdir=%r/.vifm-trash,$HOME/.vifm/trash
```
It probably should become the default value.
