### ISSUE TITLE
Release  a new version

### ISSUE THREAD

**Issue by flosker** [vifm/vifm#710]
On Fedora 34, current version of Vifm (v0.11) is from 27 Jan 2021.

I see there are lots of (like 600+) new commits have happened since then. So it would be great if you released a new version., so users could enjoy the latest Vifm.

Also, this is my fav. file manager, there is nothing which can compare Vifm's power & performance. Thank you very very much for creating this Awesome project :)

**Comment by xaizek** [comment]
v0.11 was released on 24 Sep 2020. v0.12 should be out this month. There are still some bugs to fix and a couple of small changes.

**Comment by xaizek** [comment]
Beta for v0.12 is out.
