### ISSUE TITLE
hborder: Horizontal separator for horizontal split

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#712]
Vifm uses `vborder` to fill the borders of the window and also to separate the left and right views on a vertical split.

In my opinion it would make sense to also separate the bottom and top views on horizontal splits with a `hborder` character, useful for those who don't color the background of the top-line, such that it is not always obvious where one view ends and the other begins:

![08-08:32:18](https://user-images.githubusercontent.com/75080827/132502149-098f5062-6917-4fc9-ad67-b716b71bf0b4.png) ![08-08:32:11](https://user-images.githubusercontent.com/75080827/132502201-0ea865b9-4353-40ea-b2b4-b2d508b2d031.png)

**Comment by xaizek** [comment]
I noticed this too. Showing it optionally (if `hborder` is set) is a good idea, otherwise it might look like two borders in some color schemes.

**Comment by qsmodo** [comment]
Would it be good to respect `tuioptions=v` to possibly double the border height to equalize the panes' height?

**Comment by xaizek** [comment]
There is no border at the moment and 0*2 = 2. And if you count topline of the bottom pane as such, then you'll get the desired visual separator only when terminal height allows it.

**Comment by qsmodo** [comment]
I don't understand. Can you elaborate?

My understanding is that if one decides to respect `tuioptions=v ` for the horizontal view, then if `hborder` is also set, one might get a double line separator in the middle of the view, just as with `hborder`. This seems a bit wasteful to me, since we usually have more columns than rows, but for consistency one might want to implement it that way.

Hence my question in the last comment.

**Comment by xaizek** [comment]
I thought the question was about using `tuioptions` instead of `hborder`.

`v` in `tuioptions` is an old behaviour which was made configurable (this is why it's on by default), it doesn't need to be respected for horizontal border.
