### ISSUE TITLE
Different ellipsis characters in UTF-8 environment

### ISSUE THREAD

**Issue by 0xDP** [vifm/vifm#714]
Hi,

It would be nice if one could configure the characters for ellipsis via vifmrc. Then one could use e.g. `…`, which saves two screen positions. Alternatively, in an UTF-8 environment `…` could be used automatically instead of `...` as ellipsis.

I use something like this:

```
--- vifm-master/src/ui/column_view.c	2021-09-10 14:00:14.000000000 +0200
+++ vifm-master_r1/src/ui/column_view.c	2021-09-11 14:37:50.000000000 +0200
@@ -91,7 +91,7 @@ static column_desc_t *col_descs;
 /* Column print function. */
 static column_line_print_func print_func;
 /* String to be used in place of ellipsis. */
-static const char *ellipsis = "...";
+static const char *ellipsis = "…";

 void
 columns_set_line_print_func(column_line_print_func func)
```

but it would be nice if this could be done out of the box.

Dennis

**Comment by xaizek** [comment]
Hi

> it would be nice if this could be done out of the box.

[Surprise](https://vifm.info/vimdoc.shtml#vifm-to-u)! :)

```vim
:set tuioptions+=u
```

I'm not sure that usage of a UTF-8 locale guarantees that such characters will be displayed correctly, so it's not done automatically.

**Comment by 0xDP** [comment]
> :set tuioptions+=u

Oha,  very nice :-)
