### ISSUE TITLE
How to use new truecolor feature?

### ISSUE THREAD

**Issue by anuvyklack** [vifm/vifm#717]
I am trying the new 0.12-beta version, and I can't understand how to use the truecolor.

I'm tried

```
highlight Border cterm=none ctermfg=default ctermbg=137 gui=none guifg=default guibg=#a89984
```

but received `Trailing characters` error.

When I try

```
highlight Border  gui=none  guifg=default  guibg=#a89984
```

I don't get any errors, but no effect also.

I am using tmux inside kitty, my environment variables are:

```
$TERM        tmux-256color
$COLORTERM   truecolor
```

**Comment by xaizek** [comment]
https://github.com/vifm/vifm/blob/master/data/vim/doc/app/vifm-app.txt#L1980-L1985

> received Trailing characters error.

Thanks, there is inappropriate limit on number of arguments.

**Comment by anuvyklack** [comment]
Tmux recommends using `tmux` and `tmux-256colors` values for `$TERM` [(link)](https://github.com/tmux/tmux/wiki/FAQ). In my case, `tmux-direct` value just broke everything.

The other way to check truecolor support is `$COLORTERM` [environment variable](https://github.com//termstandard/colors#true-color-detection).

**Comment by xaizek** [comment]
> In my case, `tmux-direct` value just broke everything.

I don't have `tmux-direct` terminfo entry, so maybe there just isn't one.

> The other way to check truecolor support is `$COLORTERM` [environment variable](https://github.com//termstandard/colors#true-color-detection).

That's not up to me. `$COLORTERM` is a convension for applications that print escape codes on their own. Curses-applications use terminfo and can't use 24-bit colors without terminfo entry that supports 24-bit colors. `$TERM` specifies terminfo entry.
