### ISSUE TITLE
Scroll preview

### ISSUE THREAD

**Issue by AckslD** [vifm/vifm#720]
Apologies if this is already mentioned somewhere, I tried to look in issues and documentation but couldn't find if there is a way to scroll the preview? For example like `S-Down` in `fzf`s preview.
I tried the following inputs but nothing seems to scroll the preview:
* `S-Down`
* `PgDn`
* `C-d`
* mouse-scroll

**Comment by mckellygit** [comment]
Hi,

I either go to the preview window with <C-w>w and then scroll as mapped with my qmaps, or I have a few keys like -
nnoremap \<Esc\>k        \<C-w\>w5k\<C-w\>w
nnoremap \<Esc\>[6;5~   \<C-w\>w10j\<C-w\>w

and then M-k (alt-k) etc can scroll the preview without leaving the current window.

thx,
-m

**Comment by mckellygit** [comment]
But I have not been able to get the shift-arrows such as \<S-Down\> or \<Esc\>[1;2B to work in vifm.
Many other ctrl or alt or ctrl+alt mappings work fine tho.  Not sure if its my local config or what.
I will try to see if any ctrl+mouse wheel can also work for this.

**Comment by AckslD** [comment]
Oh great! Thanks @mckellygit! I added:
```vim
nnoremap <PageDown>  <C-w>w5j<C-w>w
nnoremap <PageUp>    <C-w>w5k<C-w>w
```
which works great :+1:
