### ISSUE TITLE
Directory Preview Only Works for "Dot Directories"

### ISSUE THREAD

**Issue by atomdmac** [vifm/vifm#722]
# Description

When using the preview mode, `vifm` will show a nice tree preview of the directory structure of the selected directory.  However, (at least on my machine) this only happens if the directory name starts with a `.` (i.e. a "dot").  For all others, the preview pane remains blank.

## Setup

OS: MacOS 10.14.6
vifm: `0.11`

**Comment by xaizek** [comment]
Check for something like this in your `vifmrc`:
```vim
fileviewer * your-command
```
`*` matches directories, but not files that start with a dot. You can then change it to process only files of all kinds like this:
```vim
fileviewer *[^/],.*[^/] your-command
```

**Comment by atomdmac** [comment]
Thanks @xaizek 

In the screenshots below, both the `.colors` and `colors` directories have the exact same contents.  As you can see, the "dot-directory" version shows the preview on the right but the other does not.

![image](https://user-images.githubusercontent.com/1461736/135085490-27d2acd5-6b62-44c1-b0d7-287ab6bf80ed.png)
![image](https://user-images.githubusercontent.com/1461736/135085541-137c0de2-e51b-4873-be45-4a287ec7f0bc.png)

I also tried playing with other methods for previewing (like you suggested above).  However, the following example suffers from the same issue.

```
fileview *[^/],.*[^/] ls -alF
```

**Comment by atomdmac** [comment]
Ah yep, that's exactly what it was.  I was using a regex that was a little too permissive up above in my config:

```
fileview * highlight -O xterm256 -s dante --syntax c %c
```

Revising it to this solved the problem:

```
fileview *[^/],.*[^/] highlight -O xterm256 -s dante --syntax c %c
```

Thanks @xaizek
