### ISSUE TITLE
Image preview with 0v12 is factor 5 slower as with the 0v11

### ISSUE THREAD

**Issue by flux242** [vifm/vifm#727]
Same settings, same terminal emulator, same img2sixel binary
The 0v12 is started from an Appimage which shouldnt cause this effect I suppose

Preview code
```
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.gif,*.xpm
         \ img2sixel -S -w $((%pw*11)) %c %pd %pc clear,
         \ convert -identify %f -verbose /dev/null
```
Has it something to do with the changes from https://github.com/vifm/vifm/issues/588 maybe?
Thank you

**Comment by xaizek** [comment]
> Has it something to do with the changes from #588 maybe?

Depends on the value of the option in your configuration. `hardgraphicsclear` isn't set by default.

I don't see any performance difference compared to v0.11 either with AppImage or with a binary. Seems to take the same amount of time. Not sure why would it.

**Comment by xaizek** [comment]
There could be more directory updates (hard to keep track of that), but result should be cached the first time anyway.

I don't know why AppImage would change the behaviour, it basically unpacks itself and runs the app.

**Comment by xaizek** [comment]
By the way, rather than using part of an AppImage you can just [build from sources](https://wiki.vifm.info/index.php/Obtaining_Vifm#From_sources). Not sure it will make any difference.
