### ISSUE TITLE
Unrecognized command: 'yori.exe'

### ISSUE THREAD

**Issue by LinArcX** [vifm/vifm#728]
Os: windows
Shell: yori

I want to use [yori ](https://github.com/malxau/yori) instead of cmd. So i've added this line to `vifmrc`:
```
set shell=yori.exe
```
But if i run `:shell`

Vifm won't recognize yori. (absolutely yori is inside PATH)

EDIT: if i remove that line, everything will work without any problem.(vifm will use cmd)

**Comment by xaizek** [comment]
It was working, `Unrecognized command: ` is a message from Yori. It just didn't like single quotes around arguments. I've added initial support for it (seems to work, but I didn't test too much), so it can be used now.

See https://builds.vifm.info/ for a development build if you want to try it out:

 * https://builds.vifm.info/builds/vifm-w32-se-v0.12-290-g9e21dd988ebf-dirty.exe
 * https://builds.vifm.info/builds/vifm-w64-se-v0.12-290-g9e21dd988ebf-dirty.exe
