### ISSUE TITLE
Background coloring inconsistency on startup (minor)

### ISSUE THREAD

**Issue by hofheinz** [vifm/vifm#73]
With a non-black "Win" background and with one pane in "view" mode, the background color of that view pane will be black on startup, but will become blue as soon as that pane is changed.

This is easier to describe with a minimal working example: suppose an otherwise empty setup (current master branch on linux) with vifmrc as follows:
  highlight Win ctermbg=blue
  set vifminfo=tui
(Second line makes vifm remember that one pane was in view mode.)

Proceed as follows:
 1) start up vifm with the above vifmrc (but otherwise empty config)
 2) change one pane to view mode with ":view"
 3) exit vifm with ":q"
 4) restart vifm
Expected behavior: two panes with blue background during all steps (including after restart).
Actual behavior: as expected, except that after restart, the view pane has a black background. (After operations that change the view pane -- e.g., pressing space to change panes --, the pane background becomes blue.)

(Maybe this isn't even the expected behavior, but at least it seems to be an inconsistency.)

I suspect the following (but am not sure): when starting up, first a default colorscheme (with black background) is loaded. Initializing a view pane window doesn't set curses background attributes (maybe because that background is set to transparent internally?). If this is correct, then a possible change could be to explicitly set the background of view panes to the "Win" background (or something similar).

**Comment by xaizek** [comment]
Thank you! Should be fixed in `fix-view-bg-update` in case you would like to test it. Simpler way to reproduce: run `:highlight Win ...` while view/explore window is visible, hiding it or switching to another file caused different results.

**Comment by hofheinz** [comment]
(Yes, a simple `:highlight Win ...` does the same. So my example wasn't really minimal :-)) Your patch works here as well. Thank you, also for the quick reply!
