### ISSUE TITLE
Can't display images using kitty terminal

### ISSUE THREAD

**Issue by Danielgb23** [vifm/vifm#732]
I tried to display previews with:
```
" Pictures
filetype *.bmp,*.jpg,*.jpeg,*.png,*.xpm open -a Preview %f &
fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.xpm
   "\ tty >> ~/teste &&
    \ kitty +kitten icat --clear --transfer-mode=file --place=%pwx%ph@%pxx%py %c 
    \ %pc
    \ kitty +kitten icat --transfer-mode=file --place=%pwx%ph@%pxx%py --clear

```
But it didn't work. It turns out icat needs to be executed from the terminal window's process that it's being called from. But vifm calls it from  itself. I tried running tty from the preview (commented line) and it responds `not a tty` confirming the issue. Its there a way to run a command put in the config from the terminal window or a hack to trick it into thinking that?

**Comment by xaizek** [comment]
Please see discussion in issue #731.
