### ISSUE TITLE
Cursor keys not working when in neovim terminal (at least on MS Win)

### ISSUE THREAD

**Issue by Grueslayer** [vifm/vifm#733]
If running vifm in a neovim terminal (`:term`) (qt or console version) the cursor keys are non functional. Using vanilla VIM everythings runs fine.

**Comment by Grueslayer** [comment]
Nightly build from 2021-10-30 (which still says 0.11 in `:ver`, filename is: `vifm-w64-se-v0.12-32-ged28b6fddcd3-dirty.exe`) fixes that problem for me.

**Comment by xaizek** [comment]
Weird, there were no changes related to key processing.

> which still says 0.11 in `:ver`

Thanks, it's cached in a file. Should be fixed for future builds.
