### ISSUE TITLE
vicmd can't set by environment variable anymore

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#734]
Hi! I used to have
```
let &vicmd=$EDITOR
```
but now I'm getting the following error message:
```bash
zsh:1: command not found: decode_data.rs
Press return ...
```

do you know how I can fix this?

**Comment by xaizek** [comment]
Hi,

Have you checked value of `$EDITOR`? See output of `:echo $EDITOR`. It's probably is empty.

**Comment by TornaxO7** [comment]
That's strange, if I do `echo $EDITOR` in my shell, then I'm getting `neovide` as expected, but if I run `:echo $EDITOR` in vifm, then I'm getting nothing back.

**Comment by xaizek** [comment]
Even if you execute `vifm` in that shell? If Vifm is started from a shortcut, maybe you're setting `$EDITOR` in shell configuration rather than in `.profile`.

**Comment by TornaxO7** [comment]
I'm setting `EDITOR` in my `~/.zshrc`:
```zsh
# some other stuff...

# This just checks if we're in the TTY or using a virtual terminal.
if [ -t 0 ]; then
    EDITOR="neovide"
else
    EDITOR="nvim"
fi

# ....

**Comment by xaizek** [comment]
And how do you start Vifm? `.zshrc` is loaded only by interactive shell, so if you want `$EDITOR` to be set for applications that you don't start manually from such a shell, it needs to be set in `.profile` which is sourced by login shell.

**Comment by TornaxO7** [comment]
I tried it with the following alias:
```zsh
alias v="vifm ."
```

**Comment by TornaxO7** [comment]
![image](https://user-images.githubusercontent.com/50843046/139911273-46361352-c893-4b47-bafe-109b17d45ff3.png)

here's also a screenshot to show, that `$EDITOR` is set.

**Comment by xaizek** [comment]
Try making `let &vicmd = ...` the first line in `vifmrc`. Also check that `vifm` isn't some wrapper script you forgot about.

Wait... don't you need to have `export EDITOR`? Check that `EDITOR` is present in the output of `$ env`.

**Comment by TornaxO7** [comment]
oh yes, I have to export `EDITOR`. Strange....

**Comment by TornaxO7** [comment]
thank you for your help! But I wonder why I needed to do that :thinking:

**Comment by xaizek** [comment]
Variables inherited from parent of the shell are exported automatically. So if you had `$EDITOR` set in, say, `/etc/profile`, but an update removed that line, your `$EDITOR` will stop being exported as a consequence of that.
