### ISSUE TITLE
How to display total size of selected folders?

### ISSUE THREAD

**Issue by gerazov** [vifm/vifm#735]
Related to #63 and [Wiki](http://wiki.vifm.info/index.php?title=FAQ#How_to_get_total_size_of_selected_files.3F), `%E` doesn't show the size of the contents of the folders.

I tried mapping:
```vim
nnoremap <Space>z :!for d in %f ; do du -s $d; done | awk '{sum += $1} END {printf sum/1024 "M"}'<CR>
```
But I can't see the printout - I have to suspend vifm and then go back.

**Comment by xaizek** [comment]
You can use [`%S` macro](https://vifm.info/vimdoc.shtml#vifm-%25S) for your mapping to see the output. But you probably want to compute sizes of directories with [<kbd>ga</kbd>/<kbd>gA</kbd>](https://vifm.info/vimdoc.shtml#vifm-ga).

**Comment by gerazov** [comment]
Awesome :sunglasses:, maybe add `gA` in the Wiki?

**Comment by xaizek** [comment]
Updated the Wiki, thanks.

`%S` is a macro for external commands and should appear after `:!`:
```vim
nnoremap <Space>z !for d in %f ; do du -s $d; done | awk '{sum += $1} END {printf sum/1024 "M"}' %S<CR>
```

**Comment by gerazov** [comment]
Good catch :sweat_smile: thanks!

**Comment by xaizek** [comment]
If you want to update size again, then yes, do `gv` afterwards. Probably all non-navigation commands in visual mode switch to normal mode.

**Comment by gerazov** [comment]
Ah ok, so you can do `ga` on the `..` and then select what you want to sum up :+1:
