### ISSUE TITLE
Haiku doesn't provide the function fdatasync

### ISSUE THREAD

**Issue by Begasus** [vifm/vifm#737]
Looking into bumping our version for vifm on Haiku when I stumbled into this.
Removing the check in configure.ac and replacing fdatasync with fsync in the line: https://github.com/vifm/vifm/blob/84ab7ba0ebef5d05612ff3edd8b4e4b940639f20/src/compat/os.c#L360 works, but asking here if this is a good thing to do (not a developer here).

**Comment by xaizek** [comment]
`fsync()` is `fdatasync()` + some metadata synchronization, so the replacement is correct. Thanks, I'll make check for `fdatasync()` optional, thought it should be present everywhere by now.

**Comment by Begasus** [comment]
Thanks for replying, went along the way and pushed my changes to our haikuports repository.
If you look at the patchset there maybe a `elif defined(__HAIKU__) `could be inserted there?

**Comment by xaizek** [comment]
> If you look at the patchset there, maybe a elif defined(__HAIKU__) could be inserted there?

The patch is already specific for HaikuOS and a general fix can just act differently if `fdatasync()` isn't found.

**Comment by Begasus** [comment]
> The patch is already specific for HaikuOS and a general fix can just act differently if `fdatasync()` isn't found.

For the record, it's `Haiku` (not `HaikuOS`) :) aside from that, looking forward to see a fix for this, thanks! :+1:

**Comment by Begasus** [comment]
Thanks! I'll check it out in a minute :)
