### ISSUE TITLE
Enter key never opens a file, simply moves it to the next pane.

### ISSUE THREAD

**Issue by zoj613** [vifm/vifm#738]
How can I stop this behaviour? setting `set runexec` does not seem to help at all. Anytime I press the "Enter" key on a selected file, it just moves it to the other pane instead of opening.

**Comment by xaizek** [comment]
Maybe you have mapped <kbd>Enter</kbd> to something? Check output of `nmap <cr>`, this isn't a normal behaviour.

**Comment by zoj613** [comment]
> Maybe you have mapped Enter to something? Check output of `nmap <cr>`, this isn't a normal behaviour.

It turns out that there is a mapping that maps `:move<cr>` to the `Enter` key. removing it worked. Not sure how that ended up there because I already have `:move<cr>` mapped to `C-m` in the config file. Thanks for the help.
