### ISSUE TITLE
Image preview covers popup menu

### ISSUE THREAD

**Issue by heelsleeh** [vifm/vifm#739]
If I have :view enabled and try to delete an image, the popup is shown, but then the image redraws on top of it.
i use ueberzug preview the picture.
![141672113-458b597c-9432-481c-a01c-409eeb83d776](https://user-images.githubusercontent.com/24011272/142755891-5be758be-a40e-42ff-9c12-be3dda37c1b7.png)

**Comment by xaizek** [comment]
That's expected. Images aren't really supported by terminals. Even if they support drawing them directly, images won't mix with other content in any predictable way. And in the case of Ueberzug images are drawn on top of the terminal window, so it's absolutely impossible to draw anything over them.

**Comment by heelsleeh** [comment]
got it, thanks for  reply and many thanks for  the great work.

**Comment by PRESFIL** [comment]
@xaizek , only `vifm` knows when he will initiate a dialogue.
`vifm` also controls the launch of preview. It would be possible to
close the preview and reopen it when the dialog disappears.

**Comment by xaizek** [comment]
@PRESFIL, you're right, thanks. There must be a redraw after dialog is closed anyway, so only need to clear images before displaying it (and probably avoid drawing them on terminal resize too).

**Comment by heelsleeh** [comment]
works fine now, thanks

**Comment by PRESFIL** [comment]
It seems like it's not over yet. I can break the behavior by launching
preview and then running the `:chmod` command . It may now only
work for Vim-keys, but not for Ex-commands.

**Comment by xaizek** [comment]
It's not related to dialog origin. I wrote "dialogs", but meant "message dialogs". Will do the rest, thanks.

**Comment by PRESFIL** [comment]
Thanks! Looks good but, I'm not that good at `vifm` to check all of them.
