### ISSUE TITLE
Changing ruler color

### ISSUE THREAD

**Issue by cdlscpmv** [vifm/vifm#74]
The ruler used to be transparent (default color), but with recent changes it has become black, and there is no way to change that. Maybe there should be a highlight option for ruler as well?
Thanks!

**Comment by xaizek** [comment]
Thanks, that's second report on this issue for today :-) And it's almost fixed. Generally, color of the ruler is controlled by `CmdLine` highlight group.  And the group is `ctermfg=white ctermbg=black` by default, so I'm not sure why it would be transparent unless you setup it that way via color scheme.

**Comment by xaizek** [comment]
Should be fixed on `master` now.

**Comment by cdlscpmv** [comment]
Thanks for a quick fix! It looks all right now.

I don't know if I should open another issue, but there is one more problem I've encountered with colors recently. Somehow the default color (which should be the background color of the terminal) has become black for _some_ highlight groups, for example,  Win, TopLine, TopLineSel, CmdLine, Border. For the other ones, it works as it supposed to work: black is black, default is default. I didn't notice such a behavior in version 0.7.8.

**Comment by xaizek** [comment]
Chances are high that the issue with transparent colors is fixed now as well. There were some substantial changes in the way colors are displayed, which allowed for file-name specific highlights and other additional highlighting to be added in the future. Such bugs are the cost of those changes, thanks for helping to find them.

**Comment by cdlscpmv** [comment]
The issue is gone. Thank you for your work!
