### ISSUE TITLE
scroll preview pane 

### ISSUE THREAD

**Issue by laoshaw** [vifm/vifm#740]
after I open vifm by default I'm on the left pane, I want to preview the content on the left pane file, so I select one, and hit ctrl ->, it does preview the file(I use 'bat' for syntax highlight)

the problem is that I can not scroll it. I can only scroll it if I hit enter key to enter 'edit' mode of that file.

can I scroll the preview directly? ctrl-E ctrl-Y etc per the document does not work for me.

**Comment by xaizek** [comment]
Maybe https://github.com/vifm/vifm/issues/720#issuecomment-925748102 is what you're looking for?

**Comment by laoshaw** [comment]
Thanks. Works well.
