### ISSUE TITLE
cborder: vertical separator for columnss

### ISSUE THREAD

**Issue by shenqshuoh** [vifm/vifm#741]
Current `vborder` separates panes only. It would be nice to have a `cborder` option to separate columns in millerview.

**Comment by xaizek** [comment]
`cborder` might be somewhat confusing as there are columns in table-view (`'viewcolumns'`). Other than that, it can be added.

**Comment by xaizek** [comment]
Called it `millersep`.  By the way, I forgot to mention `AuxWin` highlight group that can be used for the similar purpose of visually separating miller columns (it applies to left and right columns).
