### ISSUE TITLE
Symlinked colorschemes are not found

### ISSUE THREAD

**Issue by olmokramer** [vifm/vifm#743]
I have a colorscheme in `~/.config/vifm/colors/colors.vifm` which is a symlink to some other path, but when I try `:colorscheme colors` I get the error message "Cannot find colorscheme colors", even though the symlink points to the correct path: when I `cat` the symlink I get the expected file contents.

When `~/.config/vifm/colors/colors.vifm` is a regular file it does work.

I have tried this on commit 569fcc8bd41bbdaebb9165d27bf888b9ff536332 (tag v0.12) and c0c24785757d8f0653f6c6ed4358625e4e88a358 (master at the time I'm writing this). Below is the output of `vifm --version` running the v0.12 tag, for the latest master build only the "Compiled at" differs. I'm running vifm on Linux.

```
Version: 0.12
Git info: built out of repository
Compiled at: Sep 29 2021 09:58:06

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
Seems to work fine. What's the path of your symlink? I tried relative and absolute, they both work. Symlink to symlink works too. Also tried leaving just one colorscheme. You can try creating symlink to a file in `~/.config/vifm/colors/` and see if it works.

**Comment by olmokramer** [comment]
Thank you for your response! It turns out that symlinks do work, but that a symlink to a symlink seems to break for me. I have `~/.config/vifm/colors/colors.vifm` which is a symlink to `/nix/store/zc2p9zlg3q2a5hzr32c2n0ixmcih9ma2-home-manager-files/.config/vifm/colors/colors.vifm` which is a symlink to `/nix/store/1cvhl9wqchyl54674kjxp5ay0d8dh1bx-hm_colors.vifm` which is the actual file containing my colorscheme.

But I can also reproduce it if I run the following commands:

```
cd ~/.config/vifm/colors
touch xxx.vifm
ln -s xxx.vifm yyy.vifm
ln -s yyy.vifm zzz.vifm
```

After running those commands, only `xxx` and `yyy` show up in the colorscheme selector that you get when calling `:colorscheme` with no arguments. Also `:colorscheme zzz` gives me the error "Cannot find colorscheme zzz" again.

Looking at the source code of [`is_regular_file` in `src/utils/fs.c`](https://github.com/vifm/vifm/blob/513c44ed8c7bbf30d081d3dff80dc2aeb22bc03b/src/utils/fs.c#L505-L530) I think this would make sense, as symlinks are only dereferenced once before `is_regular_file_noderef` is called.

**Comment by olmokramer** [comment]
I've quickly tried to patch `is_regular_file` to call itself recursively until it is not passed a path to a symlink, and indeed that seems to solve the issue. This is the patch I made:

```diff
diff --git i/src/utils/fs.c w/src/utils/fs.c
index c1cb59fb5..34cbecd81 100644
--- i/src/utils/fs.c
+++ w/src/utils/fs.c
@@ -523,10 +523,12 @@ is_regular_file(const char path[])
 		}
 		free(symlink_base);
 
-		path = resolved_link;
+		return is_regular_file(resolved_link);
+	}
+	else
+	{
+		return is_regular_file_noderef(path);
 	}
-
-	return is_regular_file_noderef(path);
 }
 
 int
```

**Comment by xaizek** [comment]
Thanks, I've messed up during creating symlink to symlink in my tests. Updated code to use `realpath()`, not sure why it wasn't there from the start.

**Comment by olmokramer** [comment]
Thanks! Yeah that seems sensible. I've updated my vifm to 6e9706a226459ade5cf3cb62e29e26f11b0e5caf and can verify that it fixes the problem.
