### ISSUE TITLE
The sort order dialog flickers when the current directory is written to

### ISSUE THREAD

**Issue by opennota** [vifm/vifm#745]
Open some directory in vifm. Open sort order dialog by typing `:sort<Enter>`. In another console `cd` to the same directory and run `while true; do echo 1 > test; sleep 1; done`. The dialog will flicker every second.

**Comment by xaizek** [comment]
I can hardly see it in v0.12, so it depends on a terminal. Either way, 3491456 disables directory updates when dialogs are open and indirectly addresses this.
