### ISSUE TITLE
goto command doesn't work properly when run on startup

### ISSUE THREAD

**Issue by toan2406** [vifm/vifm#747]
Hi, when I start vifm with -c option and `goto` command, like this

```
vifm -c "goto path/to/my/file.txt"
```

It starts vifm and goes to the right folder, but the cursor doesn't highlight `file.txt` as I expected. The `goto` command however does highlight correctly if I run it inside vifm.

I'm using vifm 0.12. I'm not sure if I miss anything.

**Comment by xaizek** [comment]
Hello,

this looks weird. It's equivalent with `--select` works fine though:
```
vifm --select "path/to/my/file.txt"
```

**Comment by toan2406** [comment]
Thanks! I completely missed that arg. I'm using vifm as file explorer for my vim. With this option it's much easier to locate current buffer.
