### ISSUE TITLE
vifm crashes when running :file

### ISSUE THREAD

**Issue by dalvand** [vifm/vifm#749]
I am using `vifm-v0.12-x86_64.AppImage` in Ubuntu 20.04. Vifm crashed everytime I run `:file`. Here is the error:
```
:filefile: Compiled magic version [538] does not match with shared library magic version [536]
file: could not find any valid magic files! (No such file or directory)
Segmentation fault (core dumped)
```
Is this a bug or it is related to my system?

**Comment by xaizek** [comment]
Thanks. That's an issue with AppImage. As a workaround you can uncompress [magic.mgc.gz](https://github.com/vifm/vifm/files/7774419/magic.mgc.gz) and do
```
export MAGIC=/path/to/magic.mgc
````

`file: Compiled magic version [538] does not match with shared library magic version [536]` will still be printed at least in file info dialog, but Vifm won't crash.

**Comment by dalvand** [comment]
This solved the issue. In fact the error is completely gone. Thank you.
