### ISSUE TITLE
fuse-zip mount not working on OSX

### ISSUE THREAD

**Issue by madders** [vifm/vifm#75]
When I try to open a zip file with fuse-zip I get a FUSE MOUNT ERROR.
I've checked the log, and the error is that the directory doesn't exist. So for some reason vifm is not creating the directory first, or it expects fuse-zip to do it, and it doesn't on OSX. Even if I create the directory first myself, this doesn't work because vifm is generating a unique directory name by prefixing a number.

**Comment by xaizek** [comment]
Vifm should create it, as usual with mounting, destination directory must exist in file system tree before it can be used as a mount point. If vifm fails to create directory, the message should say `Unable to create FUSE mount directory`, otherwise it should be there, *but* it's removed on mount failure (removed after error dialog, so you should see directory until dialog is dismissed).

What does the error message from the log say?

One thing you could try is running mount command (search for `FUSE mount command` in the log) manually, maybe even using same path under `'fusehome'`. Maybe the command is not syntactically correct.

**Comment by madders** [comment]
I've ran the command manually and I get the error - directory does not exist. If I create the directory first, then run the command manually it works fine.

Here are the errors I see (the file is called templates.zip in /Users/mmaddern/Downloads).

In vifm:
```FUSE MOUNT ERROR
/Users/mmaddern/Downloads/templates.zip
Press Return to continue```

In ~/.vifm/log:
```15.02.03 15:00 at fuse.c:225 (fuse_mount)
               Load stage: 3
               FUSE mount command: `fuse-zip /Users/mmaddern/Downloads/templates.zip /tmp/vifm_FUSE//001_templates.zip 2> /var/folders/vj/9s3srzwx0pl785513c14dqp40000gn/T//vifm.errors_8630237981_00````

There is no vifm.errors_8630237981_00 file.

When I try the commands manually:
``` fuse-zip /Users/mmaddern/Downloads/templates.zip /tmp/vifm_FUSE//001_templates.zip```
```fuse: bad mount point `/tmp/vifm_FUSE//001_templates.zip': No such file or directory```

```mkdir /tmp/vifm_FUSE//001_templates.zip```
```fuse-zip /Users/mmaddern/Downloads/templates.zip /tmp/vifm_FUSE//001_templates.zip```

Works okay

I also checked the the /tmp/vifm_FUSE directory while the dialog box was open in vifm, and the directory wasn't there.

**Comment by madders** [comment]
Thanks for your help with this. The value of shell is /bin/bash.

I've reproduced the issue on the branch. What I've seen is that it creates the directory and does the mount. And the mount works. But the error still appears. On the new branch it leaves the directory there even after the dialog is closed. The error file still doesn't exist. So I don't think there is any error, but for some reason vifm thinks fuse-zip failed, when it didn't.

**Comment by xaizek** [comment]
> On the new branch it leaves the directory there even after the dialog is closed.

There must be a race, now `fuse-zip` has time to actually mount the archive before vifm removes the mount point (when it's mounted, directory removal will fail as it's busy).

> The error file still doesn't exist. So I don't think there is any error,

At least not from `fuse-zip`. In general, it's not how shells work, they do all preparations beforehand (before spawning child process), so if you redirect to a file, that file must be created before command is started. For example, `echo test 2> error` doesn't output anything to error stream, yet `error` file is always created. Also, `vifm.errors...` file doesn't exist, but what about directory where it should be created, is it there?

> for some reason vifm thinks fuse-zip failed, when it didn't

It analyzes exit code, which must be in log now. You should see `FUSE mount command exit status: ???` and maybe `FUSE mounter didn't exit!` messages on the branch. Such failure doesn't mean that `fuse-zip` failed, might be that shell did. Maybe something is wrong with error file, e.g. shell fails to open output file, but for some reason still runs `fuse-zip`. By the way, if you run `fuse-zip` manually, try running `echo $?` right after that, maybe it always returns error.

**Comment by madders** [comment]
Yes sorry you're right- there is more information in the log file with the exit status:

15.02.03 17:08 at fuse.c:226 (fuse_mount)
               Load stage: 3
               FUSE mount command: `fuse-zip /Users/mmaddern/Downloads/templates.zip /tmp/vifm_FUSE//003_templates.zip 2> /var/folders/vj/9s3srzwx0pl785513c14dqp40000gn/T//vifm.errors_214136244_00`
15.02.03 17:08 at fuse.c:236 (fuse_mount)
               FUSE mounter didn't exit!
15.02.03 17:08 at fuse.c:238 (fuse_mount)
               FUSE mount command exit status: 255
15.02.03 17:08 at event_loop.c:62 (event_loop)
               Entered into this function

When I run it manually, it appears to exit straight away and  $? is 0.

**Comment by xaizek** [comment]
Error file should be there according to the log, I'm just an idiot that didn't push commit that would preserve it long enough for you to see it.

Finally, I think I know what's wrong! Have no idea why OS X is so special about it (or why it works fine on GNU/Linux, probably kernel differences), but it happened before in #7 (the common thing for these issues is that external application is spawned). Also added some more logging, just in case. And the issue should be reproducible with any FUSE mounter, not just `fuse-zip`. 

Please check updated branch, chances are high that the issue will be gone.

**Comment by madders** [comment]
Ok - so it's a bit better now, but there are still problems.

When I press enter on the zip file, there is no error and goes to the zip file directory, but it's empty.

The I press ```../``` and it get a FUSE MOUNT ERROR ```Can't unmount /Users/mmaddern/Downloads/templates.zip.  It may be busy.```

I press enter and the directory refreshes so now I can see the contents of the zip file, and can navigate okay. However whenever I try to leave the zip file directory, I get the unmount error.

This is log entry when I open the zip file:

15.02.04 12:01 at fuse.c:226 (fuse_mount)
               Load stage: 3
               FUSE mount command: `fuse-zip /Users/mmaddern/Downloads/templates.zip /tmp/vifm_FUSE//005_templates.zip 2> /var/folders/vj/9s3srzwx0pl785513c14dqp40000gn/T//vifm.errors_1732922570_00`

Still no error file (although I guess this is because there is no error dialog, so the file gets deleted).

This is the unmount error:

15.02.04 12:02 at fuse.c:469 (fuse_try_unmount)
               Load stage: 3
               FUSE unmount command: `fusermount -u /tmp/vifm_FUSE/005_templates.zip/ 2> /dev/null`
15.02.04 12:02 at event_loop.c:62 (event_loop)
               Entered into this function

I think the problem here is that with OSXFUSE, there is no fusermount, you just use umount. Although if that's the case, I'm surprised no one has seen this issue running vifm on OSX?

**Comment by xaizek** [comment]
> Ok - so it's a bit better now, but there are still problems.

Well, that's something.

> When I press enter on the zip file, there is no error and goes to the zip file directory, but it's empty.

Maybe there is a delay inside FUSE and vifm opens directory faster that it's properly mounted. I'm not sure how to work around this OSXFUSE implementation detail if this is the case and directory change isn't detected by vifm. I'll give it a try if I successfully install OSXFUSE on OSX VM.

> I think the problem here is that with OSXFUSE, there is no fusermount, you just use umount.

Thanks, added fallback to `umount` if `fusermount` isn't available, so this one might work now.

> Although if that's the case, I'm surprised no one has seen this issue running vifm on OSX?

I don't remember any related issues, maybe some FUSE implementations for OS X provide `fusermount` command.

**Comment by madders** [comment]
Great thank you. It's almost perfect now. ```sshfs``` is working perfectly. ```fuse-zip``` mounts the zip, but shows an empty directory, then I have to hit ```CTRL+L``` to refresh the screen and I see the contents. When I move out of the directory, it's automatically unmounted and the directory in /tmp/vifm_FUSE is removed. I can see in the log the unmount command is now umount:

```
FUSE unmount command: `umount /tmp/vifm_FUSE/006_templates.zip/ 2> /dev/null`
```

So the only issue is having to press ```CTRL+L```

With regards to the FUSE implementation for OSX, I'm not aware of any others. OSX FUSE is the homebrew version, and the official successor to MacFUSE. Check out question 4.8 in the FAQ about fusermount:

https://github.com/osxfuse/osxfuse/wiki/FAQ

**Comment by xaizek** [comment]
Great, thanks for testing and reporting in the first place, seems like a few people use FUSE with vifm on OSX.

As for <kbd>Ctrl-L</kbd>, looks like it can be emulated on GNU/Linux by appending ` &` to mount command, the result is the same: empty directory. I added device&inode numbers in check for directory modification (in the branch), seems to work, but one needs to wait a bit or press something anyway. I'll try to come up with something better, but if this is caused by `fuse-zip` or MacFUSE, will have to leave it as is. Maybe it will go away if directories are monitored in a different way, but I'm not sure if using knotify can help, it will probably appear exactly the same way to a user (i.e. delay won't go away).

> With regards to the FUSE implementation for OSX, I'm not aware of any others.

I looked it up on Wikipedia, it mentions two obsolete implementations (Fuse4X and MacFUSE), which might differ. It was just a guess.

**Comment by madders** [comment]
It's working perfectly now! It populates the directory straight away, I don't need to wait or press ```CTRL+L```

Thank you for fixing this so quickly. 

I often have to look at XML logs which are stored in zip files on a remote server. Without vifm I have to ssh onto the server, find the zip file, scp it to my local machine, unzip it, then find the XML. With vifm I can browse the server directly using sshfs then look straight into the zip file, and if I want the XML I can just copy it. The FUSE mount feature is really very useful for me.

**Comment by xaizek** [comment]
That was quite unexpected :-) Great to hear it finally works, I'll merge the change into `master` later after doing a bit of cleaning up.
