### ISSUE TITLE
Disable preview cache

### ISSUE THREAD

**Issue by b0x4it** [vifm/vifm#750]
Is there a way to disable preview cache in vifm? If I set an external app as a file previewer for imsges, it works but only once for each image. In subsequent previews the external app doesn't get executed because vifm just uses the cache. The cache should be empty because the previewer is an external app and doesn't show anything on the vifm pane. I am hoping that by disabling the preview cache, I can force vifm to execute the external previewer app every single time.

Thank you.

**Comment by xaizek** [comment]
There isn't. Are you just sending file name to some other app? I haven't really considered this use case, might have to add a macro to inhibit caching.

**Comment by b0x4it** [comment]
Yes, here is what I am doing:
1. Send %c to external app
2. Change the window of the external app to always on top
3. Return focus to vifm

This works fine especially if the external app has the --remote option. But, I can't use it because of the caching issue I explained. 

A macro would be great to inhibit caching. 
Thank you

**Comment by dalvand** [comment]
Are you able to include this in next version?

**Comment by xaizek** [comment]
> Are you able to include this in next version?

Sure, it a small change.
