### ISSUE TITLE
Run vifm --remote using hotkey

### ISSUE THREAD

**Issue by b0x4it** [vifm/vifm#751]
Hello,

I am trying to run the following command using a hotkey in XFCE. It does not work.

`vifm --server-name mmd --remote +'winrun , cd ~'`

Other bash commands (e.g. `notify-send hello`) work fine, but not vifm --remote commands.

The only way I can get it to work is by changing the command to the following:

`xterm -e bash -c "vifm --server-name mmd --remote +'winrun , cd ~'"`

This works, but it opens up xterm and closes it immediately. It also slows down the hotkey because it has to load xterm as well.

My understanding is that vifm is a terminal application and it has to be executed inside a terminal. But, then I am using other applications/commands like wmctrl that they work just find without xterm.

Is there any way to run vifm without terminal, as least when it is used with --remote command?

Thank you

**Comment by xaizek** [comment]
Hi,

> My understanding is that vifm is a terminal application and it has to be executed inside a terminal. But, then I am using other applications/commands like wmctrl that they work just find without xterm.
`--remote` shouldn't require terminal. XFCE might not break command into arguments or does it wrong, try keeping shell but not `xterm`:
```
bash -c "vifm --server-name mmd --remote +'winrun , cd ~'"
```

**Comment by b0x4it** [comment]
I tried `bash -c` before and now again. It does not work. I tried it in other gui apps by creating toolbar shortcuts. It didn't work either.

Other commands work like `bash -c "notify-send hello"`, but not with vifm. 

Do you have any other suggestions?

**Comment by xaizek** [comment]
You were right, `--remote` "needs" terminal since 0.11 (default value of one option depends on terminal and it's initialized before processing of `--remote`). Needs to be fixed, thanks for finding this. As a workaround try setting `TERM=`:
```
bash -c "TERM=xterm vifm --server-name mmd --remote +'winrun , cd ~'"
```

**Comment by b0x4it** [comment]
Setting `TERM=` solves the issue. Thank you for being so responsive. I am looking forward for the next release.
