### ISSUE TITLE
vifm color scheme in tmux

### ISSUE THREAD

**Issue by b0x4it** [vifm/vifm#752]
I am getting this error when run vifm inside in tmux:

`"Default" color scheme is not supported by the terminal, restored "<built-in default>"`

Is there a workaround for this to use custom color scheme in tmux?

thanks

**Comment by xaizek** [comment]
You just need to make sure that `$TERM` is correct inside tmux, e.g. `tmux-256color`:
```
# setup default type of terminal
set-option -g default-terminal "tmux-256color"
```

**Comment by b0x4it** [comment]
This solved the problem. Thank you!
