### ISSUE TITLE
vifm was showing all hidden files except .tmux.conf

### ISSUE THREAD

**Issue by dalvand** [vifm/vifm#753]
Something strange just happened and I wanted to share it here.

I have vifm to show all hidden files and it does show hidden all hidden files, except `.tmux.conf`. I toggled show/hide hidden files, but vifm still was not showing `.tmux.conf`.  I killed vifm and executed it again, and it still was not showing `.tmux.conf`.

I could finally get vifm to show `.tmux.conf` by running FZFfind and finding/entering on `.tmux.conf`. After that vifm was showing `.tmux.conf` just fine. I killed it and re-executed it and it was still showing `.tmux.conf`.

Can you think of any setting/configuration that might be causing this?

I am running vifm inside tmux.

**Comment by xaizek** [comment]
You must have filtered it out. Next time check output of `:filter?` command.
