### ISSUE TITLE
use Ctrl-a for tmux leader 

### ISSUE THREAD

**Issue by dalvand** [vifm/vifm#754]
How can the increment number functionality ([count]Ctrl-A) be disabled? I would like to use it as tmux leader.

Thank you

**Comment by xaizek** [comment]
Please note that https://q2a.vifm.info/ is more suitable for questions about functionality.

You don't need to disable <kbd>Ctrl-A</kbd> in an application to use it in a terminal multiplexer. Multiplexers process keys *before* applications they host and can always handle whatever keys they want.

**Comment by dalvand** [comment]
Sorry, I didn't know about https://q2a.vifm.info/. Thank you.
