### ISSUE TITLE
Case insensitive searching using \c

### ISSUE THREAD

**Issue by mrsafalpiya** [vifm/vifm#755]
Unlike vim, vifm has no support for `\c` to search insensitively.

I know `set ignorecase` and `set smartcase` exists but the support of `\c` (and `\C`) in searching would be great.

**Comment by xaizek** [comment]
Unlike Vim, Vifm doesn't contain implementation of regular expressions and can't simply add such modifiers. It can be added at the cost of adding another layer of escaping, but it doesn't seem to be worth it. A more viable option is to do it differently via a flag after `/` (where Vim has modifiers like `e+4`) to do not disrupt search pattern.
