### ISSUE TITLE
How to search files recursively in Vifm for Windows?

### ISSUE THREAD

**Issue by homie-desktop** [vifm/vifm#759]
I use Vifm for both my Linux laptop and Windows pc, and searching files recursively in Vifm in my linux laptop works fine using the `:find` command and the results are as intended. However, on Vifm for Windows `:find` doesn't work because it's different from the linux's `find `command. 

So, I then set an alias to replace the native find.exe of Windows with the `find` included from installing `Git` for windows in my powershell profile `Set-Alias -Name find -Value 'C:\Program Files\Git\usr\bin\find.exe`. Now the `find` command from Git is working in my powershell similar to my Linux system and I am assuming it can now be called and use by Vifm as the external `find` command? 

But when I try to find a file `:find -name "*test*"` or  `:find -iname "*test*"` it outputs the following errors: 

```
Access Denied - .
File not found - -NAME
```

I've tried adding `set findprg="where /R %s %A"` in my `.vifmrc` file. It kinda works, but doesn't include the directory itself unlike from the `find` result in my Vifm for linux. And the same error occurs when I try to add the alternative method `set findprg="find %s %a"`. 

Is there any way to search files recursively in my Vifm for Windows (that includes the directory , not just the file contents) similarly to my Vifm for Linux? Thanks!

**Comment by xaizek** [comment]
Aliases usually work only in interactive shells and aren't accessible otherwise. Specifying full path to `find.exe` in `'findprg'` should work.

**Comment by homie-desktop** [comment]
@xaizek Hi, thanks for the quick response. I've tried specifying the full path in my `vifmrc` file `set findprg="C:\Program Files\Git\usr\bin\find.exe %s %a"`. 

But then it outputs the following error:
```
'C:/Program' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by xaizek** [comment]
Need quotes around the path because of spaces:
```
set findprg='"C:\Program Files\Git\usr\bin\find.exe" %s %a'
```

**Comment by homie-desktop** [comment]
@xaizek thanks! at first it didn't work saying `C:\Program is not recognized,` I guess it breaks when a space is recognize so I just added another `"` before the `Program`.  `set findprg='"C:/Program" Files/Git/usr/bin/find.exe" %s %a'` and now its working the way I want to. Thanks! 

Another thing though, do you have any idea how to search multiple string using find? I can now search recursively and search ignoring case-sensitivity, however the last thing I needed to completely migrate to VIFM and ditch Windows File Explorer  is to find multiple string in a single `file command`. Something like this `:find -iname "*string1*","*string2*"` but it doesn't work. 

In Windows explorer I can do it using the `AND` & `OR` . For example, if I want search results that includes both `foo` and `bar` (different files) I'd do `*foo* OR *bar*` and the result would show files that contains `foo` and `bar` in their filenames. 

But if I want to search for files that strictly contains `foo` and `bar` in their filenames (files that has both foo and bar in their filenames only) I'd do `*foo* AND *bar*`. 

Thanks for your time!

**Comment by xaizek** [comment]
> `"C:/Program" Files/Git/usr/bin/find.exe"`

I'd not expect this to work, but that's Windows...

> `:find -iname "*string1*","*string2*"`

Have you tried `:find -iname "*string1*" -or -name "*string2*"`? That's the syntax for `find`.

**Comment by homie-desktop** [comment]
> Have you tried `:find -iname "*string1*" -or -name "*string2*"`? That's the syntax for `find`.

@xaizek thanks! that's the last thing I needed to fully migrate to Vifm. Thank you so much for your time and the responsiveness. Appreciate your work and efforts! 👍👍👍
