### ISSUE TITLE
in windows version :volumes menu does not show Z volume

### ISSUE THREAD

**Issue by obtroston** [vifm/vifm#76]
As far as i can see in  "src/menus/volumes_menu.c"
volume scanning loop excludes Z letter:
```c
for(c = TEXT('a'); c < TEXT('z'); c++)
```

**Comment by xaizek** [comment]
Thanks, apparently it was this way from the start and went unnoticed.

[Here are binaries](http://vifm.info/vifm-win-f3df1212.zip) with the fix. I didn't test them yet (not on Windows host), but the change is quite obvious.

**Comment by obtroston** [comment]
Thanks for the binaries, tested it, "Z" drive appears.
