### ISSUE TITLE
tree preview is not displaying properly

### ISSUE THREAD

**Issue by RayZ0rr** [vifm/vifm#760]
<details>
<summary>
~$ vifm --version
</summary>

```
Version: 0.12
Git info: built out of repository
Compiled at: Oct  3 2021 09:59:56

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
Without X11 library
Without dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```
</details>

<details>
<summary>
~$ tree --version
</summary>

```
tree v2.0.1 (c) 1996 - 2022 by Steve Baker, Thomas Moore, Francesc Rocher, Florian Sesser, Kyosuke Tokoro
```
</details>

OS : Arch Linux

**Description**

The folder preview tree is suddenly not showing in the desired manner (shown below). The preview command used is : 
```vim
fileviewer */,.*/ tree %c -L 1 --dirsfirst
fileviewer ../ tree %c -L 1 --dirsfirst
```

![tree_bug](https://user-images.githubusercontent.com/96843787/150802028-68229e3e-1f2c-4759-9fdc-edb1376ec7c2.png)

**Comment by xaizek** [comment]
`tree` produces such output if `-J` option is passed. Run `:fileviewer .local/` and look for another definition. Maybe you have more than 2 in your `vifmrc`.

**Comment by RayZ0rr** [comment]
I don't actually have any other settings for previewing folder. Just checkout and edited.
```vim
:fileviewer folder/
[present] tree %c
```

Don't know why this happened. Anyway switched to [exa](https://github.com/ogham/exa) for the time being : 
```vim
fileviewer */,.*/ exa --icons %c
fileviewer ../ exa --icons %c
```

Okay to close?

**Comment by xaizek** [comment]
Try specifying full path to `tree`, maybe you're running some wrapper script. Doing `fileviewer */ which tree  #` might show which command gets used (comment at the end is to ignore appended file path).

> Okay to close?

Yes, Vifm is unlikely to be the cause, something about `tree` and how it's invoked.
