### ISSUE TITLE
delete to home/end using dgg/dG does not work

### ISSUE THREAD

**Issue by dalvand** [vifm/vifm#763]
When I press `dG`, I get a message to confirm deleting all the files and folder to the end and I press `y`, but it only deletes the file/folder under cursor. Here is the confirmation message showing all the files from cursor to the end:

https://ibb.co/27XM66n

The same issue exists for `dgg`. The confirmation panel shows the right files/folders, but it only deletes the file/folder under cursor.

**Comment by xaizek** [comment]
Thanks for reporting, looks like https://github.com/vifm/vifm/issues/604 happens again. `%{ ... expand() ... }` in `'statusline'` is causing this.
