### ISSUE TITLE
No merge option in file conflict menu for file/folder combinations

### ISSUE THREAD

**Issue by dalvand** [vifm/vifm#764]
I have two two folders with identical content except one of the folders:
https://ibb.co/2PWSL2P

As shows in the above snapshot, the folder `Profile 3` in right panel is larger in size than the one in left panel. I select the 3 folders in right and hit `cp`. Here is the file conflict menu with merge option:
https://ibb.co/fpZt64s

However, if I select one/several of the files on the right as well as the three folders and then hit `cp`, the file conflict menu does not have the merge option anymore:
https://ibb.co/brgmCp3

Overwrite can still be used, but it would be much more efficient to just merge the folders and copy only the differences instead of everything. This also follows the logic in other file managers like TC and DC.

Is this a intended or a bug?

Thank you

**Comment by xaizek** [comment]
Options are displayed for current conflicting path. Files can't be merged, so you don't see the option. If you pick to overwrite the file, you'll get another dialog for directory later unless you one of choose "* all" options.

**Comment by dalvand** [comment]
Two comments:
1. The file conflict options are for the files first and then folders. Would it be more intuitive to have the order matches what we see in the panels that is folders first and then files?
2. The current logic doesn't allow you to overwrite all files and then merge all folders. Like you said, if you select Overwrite all, then it will apply it to the folders as well and you don't get any merge option for the folders. 

Right now, the ways I know to overwrite all files/folders are:
- Overwrite all
- Overwrite the files one by one until it gets to the folders and then select Merge all
- Copy files and folders separately to select Overwrite all for files and Merge all for folders

I think this can be done in slightly more efficient way to involve less manual work by **performing the folder operations first**. This way it would provide the user with Merge all option for the folders and also Overwrite all option later when it gets to the files. This is exactly how this is implemented in TC and DC. Don't get me wrong, vifm is my main file manager and, I believe, it is the best FM out there.

Thank you

**Comment by xaizek** [comment]
Simply

> performing the folder operations first

will make some operations fail. Consider moving `/dir` and `/dir/a` to some location. If you don't move `/dir/a` first, the operation as a whole will fail, hence the reordering (it's more complicated than that, but processing files first is part of it). Displaying directory options for files if there are some directories to be processed is probably how this should be addressed.
