### ISSUE TITLE
Feature request: Macros for filenames with full path

### ISSUE THREAD

**Issue by Grueslayer** [vifm/vifm#765]
We've macros for 

%c - current file
%d = current directory
%f = selected files

and  the correspondenting ones (%"c, %"d, %"f) with enclosing quotes and non escaped spaces (used extensivly unter Windows)

But there are some situations where the external programs do not work quite right in the current directory and we'll need to have the file with its absolute path. This can be "faked" on *nix using `%d/%c` but on Windows (if not using Powershell) you'll need the quote enclosed version. `%"d\%"c` doesn't work because you'll get both parts enclosed and not the concatenated ones.

Furthermore %f can't be completed on *nix either.

**Comment by xaizek** [comment]
See docs on filename modifiers [here](https://vifm.info/vimdoc.shtml#vifm-filename-modifiers). You just add `:p` after a macro like in `%f:p` and get list of full paths.
