### ISSUE TITLE
How to get syntax highlighting in preview window

### ISSUE THREAD

**Issue by tthkbw** [vifm/vifm#766]
I have looked around a lot to find out how to enable syntax highlighting in the preview window of vifm and have not found anything that works. I have looked at issue #437  which says use this:

>If you have highlight installed, you can add something like this to your vifmrc:
>```
>fileviewer *.html,*.go,*.css highlight -O xterm256 -s dante %c
>```
>Modify list of patterns as suits you and change the command to invoke highlighter you prefer.

However, I have had no success at all in getting this to work. My preview window remains black and white and unhighlighted. I installed highlight using Homebrew. I am running on a Mac and using iterm.

I have also not been able to find any documentation on the fileviewer command, and no howto's other than that referenced above. 

My goal is to have syntax highlighting on the preview files, specifically python and xml.

Any help or pointers to examples and/or documentation would be appreciated.

**Comment by xaizek** [comment]
`:fileviewer` is documented [here](https://vifm.info/vimdoc.shtml#vifm-%3Afileviewer). Mind that order of `:fileviewer` commands in `vifmrc` matters, maybe you have other viewers that match those files. See `:fileviewer file.go` menu for the list of commands Vifm will try to use in top down order.

**Comment by tthkbw** [comment]
I finally got this to work. Thanks for the help. One problem was that on my Mac, run-in 12.2, zsh, and iterm2, vifm was not finding my vifmrc file in ~/.config/vifmrc/vifmrc. I had to set $MYVIFMRC, then things started happening.

**Comment by xaizek** [comment]
> ~/.config/vifmrc/vifmrc

It should be `~/.config/vifm/vifmrc` (no "rc" for directory name) and `~/.vifm` shouldn't exist, then you won't need to define `$MYVIFMRC`.

**Comment by tthkbw** [comment]
Thanks for commenting about `~/.vifm`. That was the reason I had to set $VIFMRC.

**Comment by BMomani** [comment]
I'm not sure what to change, could someone elaborate on this 
I have mac and vi v9 is installed and I got systax highlighting when I :e[dit] the files but not in preview

**Comment by tthkbw** [comment]
Be sure that you have your vifmrc file in ~/.config/vifm and that it is named "vifmrc". I don't remember any details about what the original vifmrc contains after install, but I think that the relevant syntax preview stuff is this from my vifmrc:

```
" Syntax highlighting in preview
"
" Explicitly set highlight type for some extensions
"
" 256-color terminal
" fileviewer *.[ch],*.[ch]pp,*.py highlight -O xterm256 -s dante --syntax c %c
fileviewer *.py highlight -O xterm256 --syntax python
fileviewer *.json highlight -O xterm256 --syntax json
fileviewer *.xml highlight -O xterm256 --syntax xml 
fileviewer *.xhtml highlight -O xterm256 --syntax html
fileviewer *.opf highlight -O xterm256 --syntax xml 
fileviewer *.md highlight -O xterm256 --syntax markdown
" fileviewer Makefile,Makefile.* highlight -O xterm256 -s dante --syntax make %c
fileviewer *.html,*.go,*.css,*.c highlight -O xterm256 -s dante %c
```
You will need to have highlight installed as well. I installed highlight using homebrew.
