### ISSUE TITLE
"assignment of read-only member ‘__in’" error building vifm

### ISSUE THREAD

**Issue by jeetsukumaran** [vifm/vifm#77]
Error during `make`:

    make[2]: Entering directory `/home/jeet/Environment/common-ecosystem/opt/vifm/src'
    depbase=`echo background.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
        gcc -DHAVE_CONFIG_H -I. -I..   -I/usr/include/ncursesw  -g -O2 -Wall -D_FILE_OFFSET_BITS=64   -include ../config.h -MT background.o -MD -MP -MF $depbase.Tpo -c -o background.o background.c &&\
	mv -f $depbase.Tpo $depbase.Po
    In file included from /usr/include/stdlib.h:43:0,
                 from background.c:35:
    background.c: In function ‘background_and_wait_for_errors’:
    background.c:340:13: error: assignment of read-only member ‘__in’
        result = WEXITSTATUS(status);

Configured with:

    ./configure --prefix=/home/jeet/Environment/local --without-gtk --without-libmagic --without-dyn-X11

Platform:

    Linux kwyjibo.cc.ku.edu 2.6.18-308.4.1.el5xen #1 SMP Tue Apr 17 17:49:15 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

Tried both latest revision (b411dbd) as well as release 0.7.7.

**Comment by xaizek** [comment]
Please try `master` branch once again. I couldn't reproduce it, but on your system `__USE_BSD` flag seems to be defined, which switches implementation of `WEXITSTATUS` to something that causes the issue if passed constant parameter.

**Comment by jeetsukumaran** [comment]
Yes, this now works fine! Thank you!
