### ISSUE TITLE
open external application

### ISSUE THREAD

**Issue by azinsharaf** [vifm/vifm#770]
Hi, I am new to vifm. I want to open an Excel file from vifm so i added the following line to vifmrc file:
`filetype *.xlsx,*.xls "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE" %"f,`

It works fine and it launches MS Excel when i hit enter on the selected xlsx file. But the problem is that when the Excel (or any external application is open) the vifm interface locks and changes to a blank screen. I still need to use vifm interface again to browse to different location without closing the external app.

**Comment by xaizek** [comment]
Hello,

Unless it's broken again, Vifm shouldn't wait for Excel to finish. It normally detects graphical applications on Windows and avoids waiting. Try adding ` &` at the end:
```vim
filetype *.xlsx,*.xls "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE" %"f &,
```
Also can switch to using forward slashes in case this will make any difference (I think it did in a similar situation).

**Comment by azinsharaf** [comment]
thank you @xaizek . Adding `&` fixed the issue. Can you please point me to the `&` documentation?

**Comment by azinsharaf** [comment]
"If you would like to continue using Vifm while the program runs, which is most likely the case if it runs in its own window, run the task in the background by appending &." 
vimf help page
