### ISSUE TITLE
setting a color-scheme permanently

### ISSUE THREAD

**Issue by azinsharaf** [vifm/vifm#771]
Hi,
I have set the color scheme in `vifmrc` file as below but anytime I relaunch `vifm` the `Default`color-scheme will be used.

```
" List of color schemes to try (picks the first one supported by the terminal)
colorscheme zenburn
```
this is color folder:

![image](https://user-images.githubusercontent.com/10101468/155183944-1142aabd-b8e8-4dd9-80ee-581fc9c6dbb1.png)

**Comment by xaizek** [comment]
Hi,

I assume it works if set interactively. Check that you edit the right configuration file (`:echo $MYVIFMRC` should print its path) and that you don't have other `colorscheme` commands in it.

**Comment by azinsharaf** [comment]
interesting! It seems there are two `vifmrc` files on my system! Can I force `vifm` to use one of them that I want?

**Comment by xaizek** [comment]
You can define `$MYVIFMRC` to pick one or maybe remove the other one. See [here](https://vifm.info/vimdoc.shtml#vifm-startup) for how configuration is discovered.

**Comment by azinsharaf** [comment]
perfect! It worked. Thanks for your help.
