### ISSUE TITLE
Unexpected behaviour with underscore in directory name

### ISSUE THREAD

**Issue by 0xDP** [vifm/vifm#773]
Given the following directory structure:

```
.
├── "testdir"
│   └── "testfile-1.txt"
└── "testdir_new"
    └── "testfile-2.txt"
```

Start vifm with testdir in the left pane and testdir_new in the right pane:

`vifm --no-configs testdir testdir_new`

Then execute:

`:echo expand('%C:.')`

The result is `new/..`, which is unexpected, at least for me. If the cursor is on testfile-2.txt in the inactive pane, the result is `new/testfile-2.txt`. I would expect `testdir_new/..` and `testdir_new/testfile-2.txt` respectively.

It seems that the underscore in the directory name confuses vifm.

**Comment by xaizek** [comment]
Thanks, it is a bug, but it's not because of underscore. It's because `.../testdir` is a prefix for `../testdir_new`.

**Comment by 0xDP** [comment]
Confirmative. The issue cannot be reproduced anymore.
