### ISSUE TITLE
bash vs fish --choose-files

### ISSUE THREAD

**Issue by gitx-xx** [vifm/vifm#774]
**Edit** _After compiling the latest version the problem disappeared._

I get different behaviour in bash and [fish](https://fishshell.com/). 
Here's an example:

`/usr/bin/bash -c 'vifm --choose-files -'`
> **Returns the selected file as expected.**

`/usr/bin/fish -c 'vifm --choose-files -'`
> **Opens the selected file in new vim instance.**

The same happens on default configuration. It also effect the usefulness of [vifm.vim](https://github.com/vifm/vifm.vim) as it creates new nested vim instances instead of opening in a buffer.
**Any idea on how to make fish behave as bash?**

fish, Version 3.1.2
vifm, Version: 0.10.1

Thank you for all your amazing work. I love it!

**Comment by xaizek** [comment]
I suspect you might have an alias/function in fish called `vifm`. `type vifm` inside fish indicate if that's the case (don't know for sure).

**Comment by gitx-xx** [comment]
That's impressive. That seemed to be the problem.
Running `type vifm` in fish will tell if there's any loaded/cached alias or function.
Thanks
