### ISSUE TITLE
Feature: set title option by default if $TERM is foot*

### ISSUE THREAD

**Issue by nobodyatandnothing** [vifm/vifm#777]
foot supports OSC 0<sup>1</sup> and 2

1. only title, no icon

**Comment by nobodyatandnothing** [comment]
https://github.com/vifm/vifm/blob/d6e185a8a723dd619afd0cef09cecbaf55e62cfa/src/int/term_title.c#L252

**Comment by xaizek** [comment]
I see `tsl` and `fsl` defined in its [terminfo file](https://codeberg.org/dnkl/foot/src/branch/master/foot.info) (added in [this commit](https://codeberg.org/dnkl/foot/commit/fa93a97a084c458eb70c371bca4da425127b3d13)), so determining support using `$TERM` shouldn't be necessary: https://github.com/vifm/vifm/blob/d6e185a8a723dd619afd0cef09cecbaf55e62cfa/src/int/term_title.c#L209-L227

**Comment by xaizek** [comment]
Actually, looks like terminfo distributed with ncurses doesn't have either of the attributes.
