### ISSUE TITLE
Feature: nicer tree view

### ISSUE THREAD

**Issue by nobodyatandnothing** [vifm/vifm#783]
use '│, ─, └, ├, ' instead of '|, -, `-, |-,'

reference: https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by PRESFIL** [comment]
Does this require pre-installed fonts that support these characters? On Windows It will cause trouble, definitely ;)

**Comment by xaizek** [comment]
Duplicate of #716, see my answer there.

**Comment by xaizek** [comment]
> Does this require pre-installed fonts that support these characters? On Windows It will cause trouble, definitely ;)

It should depend on `u` in `'tuioptions'` and user should determine whether it can work.
