### ISSUE TITLE
Possible to remove trailing slashes on directory names?

### ISSUE THREAD

**Issue by sdushantha** [vifm/vifm#786]
Hey,

Is it possible to remove trailing slashed on directory names? Since I have icons and different colors to differentiate between normal files and directories, I find the trailing slashes to be unnecessary
![image](https://user-images.githubusercontent.com/27065646/163158833-08c2cbb1-1f3e-4464-a0e4-a30f2585966f.png)

**Comment by xaizek** [comment]
Hello,

Suffixes/prefixes are configured via [`'classify' option`](https://vifm.info/vimdoc.shtml#vifm-%27classify%27) and `/` is a suffix. If you're using vifm_devicons, change [this line](https://github.com/cirala/vifm_devicons/blob/abbcbbf4b98ce4125fb00d5eee95224eca47e78d/favicons.vifm#L5-L6).

**Comment by sdushantha** [comment]
Cheers, appreciate the help and quick reply!
