### ISSUE TITLE
[Feature Request] Ability to select search results all at once.

### ISSUE THREAD

**Issue by drazil100** [vifm/vifm#787]
It would be really cool if there was a way to search for say a file extension and press T to select the search results (or if there is no active search select all items in a directory). 

I suggest mapping this functionality to T since t is used to toggle selection of single files but any way in which search results could be selected all at once, regardless of how many non-matches are scattered between, would be cool.

**Comment by xaizek** [comment]
Take a look at [`'hlsearch'` option](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27) if you haven't seen it.

You can map <kbd>T</kbd> almost the way you want like this:
```vim
nnoremap <silent> :select //
```
It errors if there was no search. I don't think that no search pattern should match all files, it shouldn't match any.

Selecting all files is `:select *` or you can use <kbd>a</kbd> in shortcuts, like in <kbd>ya</kbd> to yank all files.

**Comment by drazil100** [comment]
Thanks!
