### ISSUE TITLE
Ability to manually enable truecolor

### ISSUE THREAD

**Issue by drazil100** [vifm/vifm#789]
I have searched every documentation and issue I was able to find referencing truecolor and as far as I can tell (and im assuming here) it was added but it only enables if it detects the terminal you are using has truecolor? I know for a fact my current terminal supports truecolor since I am able to enable it in vim with `set  termguicolors` however there is no such setting in vifm nor any reference to any similar setting in any of the documentation that I was able to find.

Why I need this:
As of the past couple days I have implemented chafa as part of my vifmrc as a way to preview and view images in my terminal.

Using chafa to preview image:
![Screenshot from 2022-04-25 23-54-35](https://user-images.githubusercontent.com/17794391/165224594-35d44b0d-1646-433b-92b6-ffc1963ce6a4.png)

Opening same image in same terminal with chafa outside of vifm:
![Screenshot from 2022-04-25 23-54-54](https://user-images.githubusercontent.com/17794391/165224535-996855c2-491a-4081-9e78-bc350b7e8007.png)

It would be REALLY nice if there was a way I can manually force vifm to try to render using truecolors so I can get this working fully without color distortions.

**Comment by xaizek** [comment]
The only way you can do this is by supplying a terminal database entry with direct colors and pointing `$TERM` to it. Unlike Vim Vifm uses `libcurses` for UI, so you need to convince `libcurses` that your terminal supports truecolors and I don't think Vifm can edit terminal database at runtime.

You can try this:
1. Pull current entry: `infocmp $TERM > $TERM-direct.info`
2. Find and update relevant entries to something like this:
  ```
  colors#0x1000000
  setab=\E[%?%p1%{8}%<%t4%p1%d%e48:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;m
  setaf=\E[%?%p1%{8}%<%t3%p1%d%e38:2::%p1%{65536}%/%d:%p1%{256}%/%{255}%&%d:%p1%{255}%&%d%;m
  ```
  Maybe use `;` instead of `:` for separator:
  ```
  setab=\E[%?%p1%{8}%<%t4%p1%d%e48;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%d%;m
  setaf=\E[%?%p1%{8}%<%t3%p1%d%e38;2;%p1%{65536}%/%d;%p1%{256}%/%{255}%&%d;%p1%{255}%&%d%;m
  ```
3. Install version for direct colors: `tic -sx $TERM-direct.info`

Then try running `$TERM=$TERM-direct vifm`.

**Comment by drazil100** [comment]
Thank you!. The instructions you gave me didn't work (vifm wouldn't even open cause it didn't recognize the terminfo) however your instructions did lead me to try setting `TERM=xterm-direct` which works just fine.

I would still love to see an option built directly into vifm someday but this workaround works for me :)

**Comment by xaizek** [comment]
It's not a workaround, this is how curses and terminfo is supposed to be used. Unless one day I'll be proven wrong about editing capabilities at runtime, truecolors can't be supported in any other way as long as curses is used.

**Comment by drazil100** [comment]
Intended or not it's a workaround compared to what I was requesting which would be something I could add to my vifmrc. Completely understand if it can't or shouldn't be done that way. Thanks again for your help :)
