### ISSUE TITLE
Start-up flags to make vifm echo or write selected file/directories

### ISSUE THREAD

**Issue by jeetsukumaran** [vifm/vifm#79]
The Ranger file manager has got a nice set of options that allow it to be used as a general-purpose file/directory selector in any context:

    --choosefile=TARGET   Makes ranger act like a file chooser. When opening a
                          file, it will quit and write the name of the selected
                          file to TARGET.
    --choosefiles=TARGET  Makes ranger act like a file chooser for multiple
                          files at once. When opening a file, it will quit and
                          write the name of all selected files to TARGET.
    --choosedir=TARGET    Makes ranger act like a directory chooser. When ranger
                          quits, it will write the name of the last visited
                          directory to TARGET

This makes it easy to use ranger to act as a file-selector in wide variety of contexts. Is it possible to implement support for these options into `vifm` ? If ``TARGET`` is '`-`', then it writes to standard output.

As a corollary of the above, it would be necessary to natively implement the command "`:cq`" or something like that to quit *without* writing the selected dirs/files, so user has option to cancel foray.

In just a couple of days of trying vifm out, I find I faaaaaaaar prefer it to ranger for its UI, and would love to replace all my ranger uses with vifm!

**Comment by xaizek** [comment]
There is undocumented `-f` option that makes vifm store selection into `~/.vifm/vimfiles` file on exit, which you can use for now (it's empty if you don't choose any file), but choosing directory is not that straightforward (I really like dedicated option more than [this](http://wiki.vifm.info/index.php?title=How_to_set_shell_working_directory_after_leaving_Vifm)).

There is also #60, which seems to be complementary to these flags.

Judging from experience of using `-f` option, `--choosefile` and `--choosefiles` can be fused together. Having them separated is probably something ranger-specific.

Thanks, that's something that would be useful to add.

**Comment by jeetsukumaran** [comment]
Yes, I think that `-f`, `--choosefile` and `--choosefiles` can be combined. 

Maybe coupled with a dedicated `--choosedir`, the full range of flexibility could be offered. It is precisely for the changing of directory command that I use `--choosedir`. The approach described [here](http://wiki.vifm.info/index.php?title=How_to_set_shell_working_directory_after_leaving_Vifm) is nice, but the problem is that there many different ways to quit vifm/vim, and it is awkward to have a specific command that is only used when you change a directory.

Also, with the discussion linked to, maybe "`--exec`" would work, like for `find`?

**Comment by xaizek** [comment]
> it is awkward to have a specific command that is only used when you change a directory

Yes, I agree on this.

> Also, with the discussion linked to, maybe "--exec" would work, like for find?

This might be a good name for a bit different thing, note that `find` executes command per found file (unless `+` is specified), this might be useful to make vifm process each of selected files in a loop (no particular use case on my mind); #60 is more about single command that would operate on whole selection, or at least that's how I understood it.

If we go with the word "choose", it makes sense to use it in all similar options, so maybe something like:

* `--choose-files`;
* `--choose-dir`;
* `--on-choose` (`--choose-cmd` can be confusing, as if a command is chosen);
* leave `-f` as a predefined form of `--choose-files` (at least for compatibility for now).

**Comment by jeetsukumaran** [comment]
>    --choose-files;
>    --choose-dir;
>    --on-choose (--choose-cmd can be confusing, as if a command is chosen);

Yes, I like this, and think it will be useful. You are right that the '`exec`' option acts on each selection individually, and thus `--on-choose` is something different. 

For the `--choose-files` options, I suggest a supplementary option that allows users to pick the file separator (like `-print0`/`-print` in find allows users to decide whether to use null or newline), with default being newline. 

> leave -f as a predefined form of --choose-files (at least for compatibility for now).

I think so, too. It is usual for some options to have a short-flag option, and `-f`/`--choose-files` makes sense.

**Comment by xaizek** [comment]
> For the --choose-files options, I suggest a supplementary option that allows users to pick the file separator (like -print0/-print in find allows users to decide whether to use null or newline), with default being newline.

OK, adding `--delimiter` option for this (name as in `cut`), with empty value (`--delimiter ""`) denoting null character separator.

**Comment by xaizek** [comment]
> If TARGET is '-', then it writes to standard output.

Won't work, you can't redirect output without breaking UI, we can use standard error stream though. Another option would be to reopen real terminal before initializing ncurses, can try that, but not sure how well it will work yet (probably worth trying).

**Comment by jeetsukumaran** [comment]
> Won't work, you can't redirect output without breaking UI, we can use
> standard error stream though. Another option would be to reopen real terminal
> before initializing ncurses, can try that, but not sure how well it will work
> yet (probably worth trying).


Yes, this will work! I have done something pretty much this [before](https://github.com/jeetsukumaran/fuzzysnake/blob/master/bin/fz#L233-L255), i.e. opening up another tty as standard output before starting up ncurses. But it *is* quite a bit of a hassle and probably is not worth it if  simply writing to a regular file specified in `$TARGET` will do most of the time.

**Comment by jeetsukumaran** [comment]
Incidentally, I do not know if the latest revision is for public consumption yet, but the build failed on my OSX system due to missing header file `gettext.h`.

**Comment by xaizek** [comment]
> But it is quite a bit of a hassle and probably is not worth it if simply writing to a regular file specified in $TARGET will do most of the time.

Looks like worth giving it a try. Printing to standard output seems to be cleaner solution as querying files "correctly" with files would require using temporary files or at least ensuring that target directory exists.

> Incidentally, I do not know if the latest revision is for public consumption yet

`master` branch is expected to work for everyone, but occasionally I break build on non-GNU/Linux systems.

> the build failed on my OSX system due to missing header file gettext.h.

Thanks, removed that dependency.

**Comment by jeetsukumaran** [comment]
Now the build fails on my OSX system due to missing header file "malloc.h".

**Comment by xaizek** [comment]
Hm, thanks, second try should work.

**Comment by xaizek** [comment]
It's all there. Redirection on `-` seems to work, and it turned out to be possible to implement the same on Windows, which was a bit of surprise to me.

I'm not sure if I tested all combinations yet, so don't hesitate to let me know if something doesn't work well.

**Comment by jeetsukumaran** [comment]
Thanks!

Works like a charm on my OSX system. Really nice!  

I have one more feature request related to this, but will submit it as an independent issue. The new version also fails to build on (my very old) linux cluster, but will submit that as independent issue.
