### ISSUE TITLE
Filetype for Windows (Create list rather than by file-extension)

### ISSUE THREAD

**Issue by fohrums** [vifm/vifm#790]
I would like to simply create my own list of applications to choose from when attempting to open up a file via `:file`. I tried but doesn't show the whole list, just the first entry *(e.g. App No. 1)*. Besides how it's being listed, the other issue is that it doesn't open properly resulting me to a cmd window with the first word from the filename as if it's not being quoted properly by vifm to file-associate for Windows.

There is barely any info regarding Vifm File Association for Windows just only Linux oriented help. Any ideas?

By default `Vifm-for-windows` opens up files using an installed variant of Vim, because the installer places the vim executable in `Windows-environmentvariables-system`

# PROBLEM

I am unable to make my own Filetype Association work by the following - titling it as **General Filetype**:

```
" General Filetype
filextype *
        \ {App No. 1}
        \ "C:\Foo\bar\app1exe" %"f
        \ {App No. 2}
        \ "C:\Foo\bar\app2exe" %"f
        \ {App No. 3}
        \ "C:\Foo\bar\app3exe" %"f
        \ {App No. 4}
        \ "C:\Foo\bar\app4exe" %"f
        \ {App No. 5}
        \ "C:\Foo\bar\app5exe" %"f
```

## NOTE

* Vifm Configuration File
  + `vifmrc`
    - located: `:echo $MYVIFMRC` prompted within `vifm.exe`
    - make modifications by editing "the vifmrc file" using a text editor
* View Windows Environtment Variables
  + `sysdm.cpl -> advanced-tab -> environmentvariables -> systemvariables-group -> path`

**Comment by xaizek** [comment]
You forgot commas:
```vim
" General Filetype
filextype *
        \ {App No. 1}
        \ "C:\Foo\bar\app1exe" %"f,
        \ {App No. 2}
        \ "C:\Foo\bar\app2exe" %"f
        \ {App No. 3}
        \ "C:\Foo\bar\app3exe" %"f,
        \ {App No. 4}
        \ "C:\Foo\bar\app4exe" %"f,
        \ {App No. 5}
        \ "C:\Foo\bar\app5exe" %"f
```

In case of `*` pattern, this equivivalent is more readable:
```vim
" General Filetype
filextype * {App No. 1} "C:\Foo\bar\app1exe" %"f
filextype * {App No. 2} "C:\Foo\bar\app2exe" %"f
filextype * {App No. 3} "C:\Foo\bar\app3exe" %"f
filextype * {App No. 4} "C:\Foo\bar\app4exe" %"f
filextype * {App No. 5} "C:\Foo\bar\app5exe" %"f
```

Escaping should work, although it depends on the shell.

**Comment by fohrums** [comment]
That fixed the listing issue when `:file`. the single line equivalent is easier to read. Would you be able to help with how opening a file only results in the following message in cmd referring back to "as if it's not being quoted properly".

```
'firstword' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .
```

**Comment by xaizek** [comment]
Sorry, one of my Windows VMs didn't work and I forgot to return to this issue.

I won't give a speech on how much I hate Windows, just know that I do...  Apparently I believed that everything worked because it works if you add ` &` (with a space before ampersand).  This is basically normal behaviour for graphical applications anyway (they are auto-detected by Vifm, so not much difference, just more explicit):

```vim
" General Filetype
filextype * {App No. 1} "C:\Foo\bar\app1exe" %"f &
filextype * {App No. 2} "C:\Foo\bar\app2exe" %"f &
filextype * {App No. 3} "C:\Foo\bar\app3exe" %"f &
filextype * {App No. 4} "C:\Foo\bar\app4exe" %"f &
filextype * {App No. 5} "C:\Foo\bar\app5exe" %"f &
```

I'll have to investigate why-the-hell-this-damn-thing-doesn't-work-again-this-time...  Thanks for reporting this though :)

**Comment by xaizek** [comment]
I think this is fixed. Hopefully, the fix doesn't break anything else, but this is Windows...

With the fix ` &` isn't necessary for correct escaping with `cmd.exe` or `bash` (with `&` works too). In case you'd like to use/test fixed version, development builds are available at https://builds.vifm.info/.
