### ISSUE TITLE
[Question] Associate program list to user vifm defined commands

### ISSUE THREAD

**Issue by jonnieey** [vifm/vifm#792]
For example, can I do this?

```vim
filetype` *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus,*.aif 
    \ {User defined command}
    \ mpcinsert; mpcnext, mpcplay

command mpcinsert :let $IGNORE = system(expand('realpath -s  ""%f"" | mpc insert'))
command mpcnext :let $IGNORE = system('mpc next')<cr>
command mpcplay :if system('mpc | sed -ne 2p -- | cut -d " " -f 1') == '' | execute '!mpc toggle &' | else | execute '!mpc next &' | endif
```

**Comment by xaizek** [comment]
`filetype` doesn't process :commands. You either need to call `vifm  --remote ...`:
```vim
let $VIFM_SERVER = v:servername
filetype *.wav vifm --server-name $VIFM_SERVER --remote +mpcinsert +mpcnext +mpcplay %n
```
or rewrite interactions with `mpc` in Lua ([example](https://github.com/vifm/vifm/blob/master/data/plugins/ueberzug/init.lua)) and use it like:
```vim
filetype` *.wav,*.mp3,*.flac,*.m4a,*.wma,*.ape,*.ac3,*.og[agx],*.spx,*.opus,*.aif 
    \ {User defined command}
    \ #mpc#run insert next play
```

**Comment by jonnieey** [comment]
Thanks. Currently I have this,       ` \ mpc insert ""file:///%f:p"" 2>&1 >/dev/null &; sleep 0.2; mpc next &; mpc play 2>&1,` , I'm going to stick with it for a while. ugly but works.

**Comment by jonnieey** [comment]
Thanks for the script. Unfortunately it doesn't work. The hello script does work
![2022-08-22-020857](https://user-images.githubusercontent.com/47189744/185814765-5ad72d50-a18c-4408-ac4d-bcedc57d904d.png)
![2022-08-22-020837](https://user-images.githubusercontent.com/47189744/185814768-cde959b7-9441-46d6-9a28-6f7f0a1dd805.png)
