### ISSUE TITLE
[question]Switch between `fileviewer`s

### ISSUE THREAD

**Issue by explosion-mental** [vifm/vifm#794]
Is it possible to 'switch' between these? rather, re-define them in a function? I haven't dive that deep but just asking in case someone already thought of this..

I'm thinking to preview images by default, but sometimes I need to know some details about the file or the contents of it so I would like to switch to a 'text' type of view.

**Comment by xaizek** [comment]
You can cycle through them via <kbd>a</kbd>/<kbd>A</kbd> in view mode ([docs](https://vifm.info/vimdoc.shtml#vifm-q_a)), but will have to map it in normal mode (switch to view mode, do a command, return):
```vim
nnoremap <silent> <c-p> <c-w><c-w>A<c-w><c-w>
nnoremap <silent> <c-n> <c-w><c-w>a<c-w><c-w>
```

**Comment by explosion-mental** [comment]
Wow thanks. I found a combination like this

```
   fileviewer *.bmp,*.jpg,*.jpeg,*.png,*.xpm,*.webp
        \ vifmimg draw %px %py %pw %ph %c %pc
        \ vifmimg clear,
        \ vifmimg clear ; mediainfo %c
```

**Comment by explosion-mental** [comment]
Anyway, thank you very much. I couldn't live without vifm..

**Comment by xaizek** [comment]
> Edit: This seems to not be persistent

These keys are only part of #330. You can subscribe to that issue and mention how you see the persistence, because there is no one straightforward way of implementing it and it might need to be customizable with `'previewoptions'`.
