### ISSUE TITLE
Adding custom depth to folder view

### ISSUE THREAD

**Issue by AfzGit** [vifm/vifm#795]
There is currently `:tree depth=N` present but this only applies to the working plane. it would be convenient to add this functionality to folder view (triggered with W or E key on a folder). Folder view can be confusing if there are many files in the folder.

Here it would be convenient if i could only view the current sub-folders and sub-files, (ignoring the sub-sub-folders and sub-sub-files). basically making _.vscode/_ and _C/_ visible while hiding their contents (equivalent to `:tree depth=2` but for view)

![image](https://user-images.githubusercontent.com/63847494/170909776-e49c6d56-da63-47e6-b4d2-77cc7663b585.png)

**Comment by xaizek** [comment]
Can be added as a new value in `'previewoptions'`.
