### ISSUE TITLE
Consider a missing file as a mismatch in compare view

### ISSUE THREAD

**Issue by qsmodo** [vifm/vifm#796]
In the `:compare` view, a missing file is denoted as `.....`, but it is not considered a mismatch. As such, `]c` will skip past them.

This is unfortunate when comparing large directories between which there are only a few differences. If I want to take note of each single aspect in which they differ, I need to scroll the panes carefully enough so that I won't overlook a missing file.

Currently, then, `diff -rq` is a necessary complement, but I believe making `[c` catch missing entries would be ideal. Applying `CmpMismatch` to them also looks appropriate to me.

**Comment by xaizek** [comment]
Seems to make sense, addition/removal is also a change. `CmpMismatch` sounds less applicable though, mismatch implies two files to differ. Adding `CmpAddition`/`CmpRemoval` seems more appropriate (no idea why names differ from Vim here, by the way).
