### ISSUE TITLE
make find result pane more usable

### ISSUE THREAD

**Issue by halturin** [vifm/vifm#797]
It would be great to make the find result pane the same as the main ones - making a selection, copying them, and showing item details (permissions, group:owner, size etc.). Is there any chance?

**Comment by xaizek** [comment]
[Press <kbd>b</kbd>](https://vifm.info/vimdoc.shtml#vifm-m_b) while in `:find` menu.  Or add [`%u`](https://vifm.info/vimdoc.shtml#vifm-%27findprg%27) to `'findprg'` to automatically redirect results of `:find` to a view.

**Comment by halturin** [comment]
Wow! what a feature!!! Thanks a lot for the best FM ever 👍👍👍
