### ISSUE TITLE
Fail to build on older system

### ISSUE THREAD

**Issue by jeetsukumaran** [vifm/vifm#80]
I have a rather old linux cluster that I use a lot. Trying to build fcfca76, I get:

    $ make
    CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/jeet/Environment/common-ecosystem/opt/vifm/missing --run autoconf
    aclocal.m4:21: warning: this file was generated for autoconf 2.69.
    You have another version of autoconf.  It may work, but is not guaranteed to.
    If you have problems, you may need to regenerate the build system entirely.
    To do so, use the procedure documented by the package, typically `autoreconf'.
    configure.ac:4: error: Autoconf version 2.62 or higher is required
    aclocal.m4:563: AM_INIT_AUTOMAKE is expanded from...
    configure.ac:4: the top level
    autom4te: /usr/bin/m4 failed with exit status: 63
    make: *** [configure] Error 1

Previous revision of vifm built OK. Is it possible to support an older version of autotools, like the previous vifm?

**Comment by xaizek** [comment]
I didn't update anything, this is a side affect of committing changes to `configure.ac`/`configure` scripts. When you did `git pull ...`, it updated modification of those files and now `make` thinks they should be regenerated. Try running `touch aclocal.m4` or if it won't work, `autoreconf -if` to force rebuild with your version of autotools.

Everything worked for you before as when you checkout repository all files have roughly same modification date. I used to add dummy commits for `aclocal.m4` to force git updating its timestamps, but I forgot about this issue and don't do this anymore (should automate this).

**Comment by jeetsukumaran** [comment]
Hmm. Ok, I did a `git clean -fxd` and then ran `./configure` and `make`, with the above.

So then I did a `autoreconf -if` and got:

    configure.ac:13: error: possibly undefined macro: AC_USE_SYSTEM_EXTENSIONS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
    autoreconf: /usr/bin/autoconf failed with exit status: 1

Run it again with no messages. 

Now `/.configure` fails with:

   configure: error: cannot find macro directory `m4'

After `mkdir m4`, I run `\.configure` and `make` again.
On the `make`, I get:


    make  all-recursive
    make[1]: Entering directory `/home/jeet/Environment/common-ecosystem/opt/vifm'
    Making all in src
    make[2]: Entering directory `/home/jeet/Environment/common-ecosystem/opt/vifm/src'
    depbase=`echo vim.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; \
        if gcc -DHAVE_CONFIG_H -I. -I. -I..   -I/usr/include/ncursesw  -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -include ../config.h -MT vim.o -MD -MP -MF "$depbase.Tpo" -c -o vim.o vim.c; \
        then mv -f "$depbase.Tpo" "$depbase.Po"; else rm -f "$depbase.Tpo"; exit 1; fi
    vim.c: In function ‘vim_format_help_cmd’:
    vim.c:59:60: error: expected expression before ‘,’ token
    char *const escaped_rtp = escape_filename(PACKAGE_DATA_DIR, 0);
                                                                ^
    make[2]: *** [vim.o] Error 1
    make[2]: Leaving directory `/home/jeet/Environment/common-ecosystem/opt/vifm/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/home/jeet/Environment/common-ecosystem/opt/vifm'
    make: *** [all] Error 2

**Comment by xaizek** [comment]
Maybe try running `rm -rf * && git checkout . && ./configure && make` at the root.

**Comment by jeetsukumaran** [comment]
Yep! That works. Thanks again!
