### ISSUE TITLE
Default value for timefmt should include the year

### ISSUE THREAD

**Issue by mattalexx** [vifm/vifm#801]
I suggest that the default value for the `timefmt` setting be changed from:

```
%m/%d %H:%M
```
to
```
%m/%d/%Y %H:%M
```

It would be less confusing to those users that have been collecting files for more than a year :)

**Comment by xaizek** [comment]
Changed values in sample `vifmrc` files to ISO-style `%Y/%m/%d %H:%M`, US-style dates would probably add to the  confusion :)

**Comment by mattalexx** [comment]
> US-style dates would probably add to the confusion :)

Haha, we do like to make things needlessly unintuitive. And unsortable.

**Comment by mattalexx** [comment]
I'm ok with the format string, myself.

Thanks for the info. And the tool itself.
