### ISSUE TITLE
No command exists for swapping the panes

### ISSUE THREAD

**Issue by jose1711** [vifm/vifm#802]
In `mc` one can hit <kbd>Ctrl</kbd>+<kbd>U</kbd> and contents of both panes is swapped. I could not find a similar feature in `vifm` (without going into scripting). Could you please consider making a separate function that would allow this?

**Comment by xaizek** [comment]
Sounds like you're looking for [<kbd>Ctrl+W</kbd><kbd>X</kbd> key](https://vifm.info/vimdoc.shtml#vifm-CTRL-W_x). It also exists in Vim.

**Comment by jose1711** [comment]
Thank you, totally missed that. Also in:
https://github.com/vifm/vifm/blob/c94a05ff51074b1576a2574f1c655d02ec54b55b/data/vifmrc#L505
