### ISSUE TITLE
remap keybinding for /

### ISSUE THREAD

**Issue by internet-police** [vifm/vifm#806]
Hi
is there a way to bind a key - lets say "f" to the same function as pressing /
on the german keyboard layout "/" is Shift+7 which is a huge pain compared to the us layout

**Comment by MuhammedZakir** [comment]
Type this in the command-line, or add this to your `vifmrc`. Replace `f` with whatever key you want.
```vim
nnoremap f /
```

**Comment by xaizek** [comment]
Hi,

The above command is the one to use, however it adds a delay which shouldn't be there. I'll need to fix the delay, you can use a different key which doesn't expect a character after it.

You can run `:echo $MYVIFMRC` to find out where your `vifmrc` file is.

**Comment by xaizek** [comment]
No, no bug there. I forgot I have <kbd>f/</kbd> mapping which caused the delay.
