### ISSUE TITLE
Open files and folders with a mouse click

### ISSUE THREAD

**Issue by user451421541757324** [vifm/vifm#807]
Currently, with the mouse wheel, we can scroll the files and directories list.

Is it possible to open them with a mouse click like `ranger`?

**Comment by xaizek** [comment]
> we can scroll the files and directories list

You must be scrolling terminal buffer, Vifm doesn't handle mouse in any way.

There were multiple tries to enable mouse in the past, but it barely worked and felt like someone else is controlling the mouse randomly, not you. It only worked fine on Windows and maybe in some particular terminal. I think I saw the same in `ncmpcpp` and concluded that ncurses has trouble with the mouse. I might give it another try.

**Comment by user451421541757324** [comment]
> I might give it another try.

In `ranger` you can open files and directories with a right click. It's very useful in situations where you are away from the keyboard but not from the mouse (think of a laptop with a wireless mouse).

Thanks for the reply and for your interest.
