### ISSUE TITLE
Use Vifm function in filetype program

### ISSUE THREAD

**Issue by mb720** [vifm/vifm#808]
Hi and thanks again for Vifm!

I'd like to use a Vifm function like `layoutis('only')` in a program associated with a filetype.

Currently, I have ffmpeg associated with some video files:

    filetype *.avi,*.mp4
          \ {view with VLC}
          \ vlc %f %i &,
          \ {Reencode with CRF 26}
          " If the other pane shows directory "dir2" and the input file is vid.mp4", the target file is "dir2/vid_crf_26.mp4"
          \ ffmpeg -i %c -crf 26 %D/%c:r_crf_26.%c:e

This works fine but I want to discern two cases:

  1. There is only one pane open in Vifm → Save the reencoded file to the current directory
  2. There are two panes opened in Vifm → Save the reencoded in the directory of the other pane, just as the program does now

I'd like to do something like this:

    filetype *.avi,*.mp4
          \ {view with VLC}
          \ vlc %f %i &,
          \ {Reencode with CRF 26}
          \ if layoutis('only'); target_dir=%d; else target_dir=%D; endif; ffmpeg -i %c -crf 26 target_dir/%c:r_crf_26.%c:e

Is this possible with Vifm?

Thanks a lot for your help!

**Comment by xaizek** [comment]
Hello!

:commands and expressions aren't available in :filetype handlers, so can't use it that way. It actually looks more like a command than a handler and in a custom command you can do it. This should work:

```vim
command! convert : if layoutis('only')
                \|     let $target_dir = '%%d'
                \| else
                \|     let $target_dir = '%%D'
                \| endif
                \| execute 'ffmpeg -i %%c -crf 26 '.$target_dir.'/%%c:r_crf_26.%%c:e'
```

**Comment by mb720** [comment]
Thanks, that was very helpful!

To call FFmpeg, I prepended two exclamation marks:

    \| execute '!!ffmpeg -i %%c -crf 26 '.$target_dir.'/%%c:r_crf_26.%%c:e'

I took the command one step further to make it convert all currently selected files:

    " Reencode the selected video or audio files using a constant rate factor
    " (CRF). This often reduces file size while keeping video and audio quality
    " the same.
    "
    " If the other pane shows directory "dir2" and the input file is vid.mp4", the target file is "dir2/vid_crf_26.mp4"
    command! convert :if layoutis('only')
                    \|     let $target_dir = '%%d'
                    \| else
                    \|     let $target_dir = '%%D'
                    \| endif
                    " We need the quotes and dots around the target_dir variable to resolve it
                    " to the actual path, otherwise we'd just get "%D" or "%d"
                    \| execute '!!bash -c "crf=26; for cur_file in %f; do \$XDG_CONFIG_HOME/scripts/reencode.sh \"\$cur_file\" '.$target_dir.' \$crf; done"'

I put the logic for reencoding into a script since I had issues getting parameter substitution such as `"${input_file%.*}"` to work inside vifmrc. The contents of `reencode.sh`:

    #!/usr/bin/bash

    # Reencodes a video or audio file using the given constant rate factor (CRF).

    input_file="$1"
    target_dir="$2"
    crf="$3"

    echo "Input file: $input_file"

    file_ext="${input_file##*.}"

    base_name="${input_file%.*}"

    output_file="$target_dir/${base_name}_crf_$crf.${file_ext}"

    echo "Output file: $output_file"

    # Use movflags and map_metadata to copy the input file's metadata to the output file
    ffmpeg -i "$input_file" -movflags use_metadata_tags -map_metadata 0 -crf "$crf" "$output_file"


I'm happy to hear your feedback if you have any and thanks again for your advice!

**Comment by xaizek** [comment]
Calling `bash` explicitly shouldn't be necessary.

> I had issues getting parameter substitution such as `"${input_file%.*}"` to work inside vifmrc

Probably because `%` needs to be doubled to prevent macro expansion.

> I put the logic for reencoding into a script

It's more manageable there then in a command. I'll expose layout information to Lua and then it will be possible to do the operation there (from both custom command and filetype handler).

**Comment by mb720** [comment]
> Calling `bash` explicitly shouldn't be necessary.

Great, this way I can also get rid of some escaping and reduce the line down to this:

    \| execute '!!crf=26; for cur_file in %f; do $XDG_CONFIG_HOME/scripts/reencode.sh "$cur_file" '.$target_dir.' $crf; done'

> I'll expose layout information to Lua and then it will be possible to do the operation there (from both custom command and filetype handler).

Oh wow, let me know if I can help testing that.

**Comment by xaizek** [comment]
It's on the master branch already if you want to use it. The plugin could look like this:

```lua
--[[

Usage example:

    filetype *.avi,*.mp4
           \ {view with VLC}
           \ vlc %f %i &,
           \ {Reencode with CRF 26}
           \ #plugindirname#convert

    :convert
    :convert 30

--]]

local function convert(info)
    local only_layout = vifm.tabs.get():getlayout().only
    local crf = info.argc == 1 and info.argv[1] or 26
    local target_dir_macro = only_layout and '%d' or '%D'
    local cmd = 'ffmpeg -i %c -crf '..crf..' '..target_dir_macro..'/%c:r_crf_26.%c:e'

    vifm.run { cmd = vifm.expand(cmd) }
end

-- this does NOT overwrite pre-existing user command
local added = vifm.cmds.add {
    name = "convert",
    description = "Reencode with CRF 26 by default",
    handler = convert,
}
if not added then
    vifm.sb.error("Failed to register :convert")
end

local added = vifm.addhandler {
    name = "convert",
    handler = convert,
    maxargs = 1,
}
if not added then
    vifm.sb.error(string.format("Failed to register #%s#convert", vifm.plugin.name))
end

return {}
```

**Comment by xaizek** [comment]
"plugindirname" is a placeholder for plugin directory name. Plugins go to `plugins/` directory next to your `vifmrc`, so if you put it in `~/.config/vifm/plugins/convert/init.lua`, you'll need to use `#convert#convert` for filetype. `[present]` should appear if everything is done right.

**Comment by mb720** [comment]
Oh, I thought the plugins had to be compiled together with Vifm 😊 Having plugins load during runtime is much more convenient.

I've tested the `convert` function both as a command (`:convert`) and as a file handler. Being able to reuse the function and have access to functions like `getlayout().only` in file handlers is really nice 👍

I think the block where we add `convert` as a command needs to have `maxargs = 1`, otherwise I get "Trailing characters" when calling the command. Afterwards, I saw that `info.argc` is nil, which leads to the actually passed argument in `argc[1]` to be ignored.
`
But I can fix this by myself, you've done enough work already. BTW, what do you use for writing Lua? Neovim with LSP? Maybe IntelliJ or VS Code?

**Comment by xaizek** [comment]
> I think the block where we add `convert` as a command needs to have `maxargs = 1`

Right, I put it in the wrong invocation.

> BTW, what do you use for writing Lua? Neovim with LSP? Maybe IntelliJ or VS Code?

Vim, of course :) With Lua docs opened in Zeal. I'm thinking of giving LSP a try, but that hasn't happened yet.

**Comment by mb720** [comment]
I noticed that depending on whether `convert` is called via a filehandler or a command, the `info` table is different. Most notably, `info.argv` is nil when using the filehandler but when using the command `:convert`, the table `info.argv` is not nil (but `info.argv[1]` is, but that's expected since we didn't pass an argument).

Getting the argument count with `info.argc` never works, it's always nil.

I don't know if that behavior is normal.

To get the CRF value, I use this currently:

    local crf = info.argv and info.argv[1] or 26
