### ISSUE TITLE
Option to suppress saving tui/history/etc state

### ISSUE THREAD

**Issue by jeetsukumaran** [vifm/vifm#81]
Currently, the only control we have on what gets saved is through the setting of the `vifminfo` variable in `vifmrc`. This works great for the typical use of `vifm` as a file manager.

However, when using `vifm` as a file-selector, using the [newly-added "choose" family of options](https://github.com/vifm/vifm/issues/79), the configuration of the `vifm` can be desired to be very different from the configuration of `vifm` as a file manager. For example, we may want only a single-panel view as a two-panel view does not make sense when selecting a file or directory. So we may invoke `vifm` like this:

~~~
    # vifm change directory
    vcd() {
        selection=$(vifm -c "only" --choose-dir -)
        if [[ -n $selection ]]
        then
            echo $selection
            echo
            cd -- "$selection"
        fi
        unset selection
    }
~~~

But then when we open `vifm` for "normal" use as a file-manager instead of a selector, we get one window instead of the usual two. One work around is to remove `tui` from the `vifminfo` variable.

But maybe we might be able to invoke `vifm` with, e.g., a `--no-save-info` flag, that suppresses saving of all state. That way we can save state, including the TUI normally, when using `vifm` as a standalone program, but suppress it when using it in special cases. Note that we still want to source `vifmrc` in all cases, as many commands/key-maps and other configurations are defined there. We just do not want to persist the state/info.

**Comment by xaizek** [comment]
You could as well do `vifm -c "only" -c 'set vifminfo=' --choose-dir -` or maybe even `vifm -c 'source ~/.vifm/chooserc' --choose-dir -` to have all choose-specific settings in one place.

`--no-save-info` would actually be useful for me for testing so I don't have to worry about loosing my settings, but I don't like that it works kinda behind users back. There are still `:q`/`:q!`/`'vifminfo'`, but their semantics is different depending on command-line arguments, this makes one have to remember how vifm was run while using it.

**Comment by jeetsukumaran** [comment]
Yes, 

    vifm -c "only" -c 'set vifminfo=' --choose-dir -

works fine! 

And 

   vifm -c 'source ~/.vifm/chooserc' --choose-dir -

is even better, allowing for many custom settings for using `vifm` as a file selector.

THANKS!
