### ISSUE TITLE
In preview getting "highlight: Could not read input file" 

### ISSUE THREAD

**Issue by mkastner** [vifm/vifm#810]
First of all: thanks for vifm. Best thing since sliced bread!

I'm on MacOS 12.5 Monterey, Terminal kitty 0.25.2, fish shell 3.5.1,  Vifm 0.12, highlight 4.2.

The following problem has only started a few days ago. Before, I had highlighting working like a charm.

I don't know, why all of a sudden I get an error in my preview.

This is my explicit fileviewer definition for *.sh script files: 

```
fileviewer *.sh highlight -O xterm256 -s dante %c
```

But when I hit .sh file within vifm the preview gives me:

```
highlight: Could not read input file:    
startup.sh 

```

Here's what I've checked or tried:

Checked, if I have *highlight* installed. It works on the command line on shell script files.

Tried to set the full location path to *highlight* application:

```
fileviewer *.sh /usr/local/bin/highlight -O xterm256 -s dante %c
```

I've also tried vifm in bash and zsh and in macos' original terminal. It's always the same above error message when hitting a sh-file.

**Comment by xaizek** [comment]
> Best thing since sliced bread!

Pleased to hear that :)

> I don't know, why all of a sudden I get an error in my preview.

It looks like you want to try using full path to the file:
```
fileviewer *.sh highlight -O xterm256 -s dante %c:p
```
Maybe you've added `cd`/`pushd` to some shell configuration file recently so that current working directory isn't inherited from Vifm anymore? Try printing it as well:
```
fileviewer *.sh highlight -O xterm256 -s echo $PWD; dante %c:p
```

**Comment by mkastner** [comment]
@xaizek Thanks very much for your help.

Upon entering

```
fileviewer *.sh highlight -O xterm256 -s echo $PWD; dante %c:p
```
I get the following printout

```
highlight: cannot open themes/echo.theme: No such file or directory             
fish: Unknown command: dante                                                    
fish:                                                                           
highlight -O xterm256 -s echo $PWD; dante /my/home/startup.sh                                    ^                                           
```

So, most likely I've screwed something up. I have no clue where themes/echo.theme comes from and I've explicitly installed dante via homebrew.

So I don't think this a problem with wifm but with my shell. Though it's the same in bash an zsh.

**Comment by mkastner** [comment]
Most likely this is a problem with my local machine.

**Comment by xaizek** [comment]
The last command should have been this:
```
fileviewer *.sh echo $PWD; highlight -O xterm256 -s dante %c:p
```

I put `echo $PWD;` in the wrong place.

**Comment by mkastner** [comment]
@xaizek Thanks a lot. It was actually my fault. Some config is really messing with the user path at login time.

Thank you very much for helping me. That line actually put me on the right track:

`fileviewer *.sh echo $PWD; highlight -O xterm256 -s dante %c:p`

And again: thanks for _vifm_. It's clean, it's lean and I can always count on my vim muscle memory. Simply awesome, Kudos!
