### ISSUE TITLE
.Xresources support for colors

### ISSUE THREAD

**Issue by speediegq** [vifm/vifm#811]
Right now, Vifm requires you to manually define a color scheme. This is kind of time consuming and while this is also the case for .Xresources, you can write it for use with multiple programs at once. 

With tools like Pywal you can generate color schemes on the fly based on the set wallpaper which would save time for the user.

Right now, the solution for Pywal in vifm is to use the vifm Vim plugin and `:VifmCs` but this is not very clean, requires the use of Vim and external plugins.

.Xresources options could look something like this:

```
vifm.color1: #000000
vifm.color2: #FFFFFF  
*.color1: #123456
```
And so on. An alternative would be to use the terminal colorscheme as then the user can simply theme his terminal and it would also set colors in Vifm.

**Comment by xaizek** [comment]
> An alternative would be to use the terminal colorscheme as then the user can simply theme his terminal and it would also set colors in Vifm.

Which is how it work at the moment. Just use a colorscheme with 16 colors and something like Pywal will affect it.

Support for `.Xresources` makes little sense for a terminal application.

**Comment by speediegq** [comment]
You are indeed correct. it was apparently a configuration thing causing it to not use 16 colors.
Thank you for letting me know about this!
