### ISSUE TITLE
vifm flashes all theme changes

### ISSUE THREAD

**Issue by mustaqimM** [vifm/vifm#813]
Hello, I don't quite know how to word the title, please see the attached video below.

https://user-images.githubusercontent.com/24436622/185049677-e40d36ff-73a6-45a5-98f7-3bbb92805609.mp4

I have a `zsh` script that switches the theme; here's the relevant vifm part:
```zsh
vifm_servers=("${(@f)$(vifm --server-list)}")
for server in $vifm_servers; do vifm --server-name $server --remote +'colorscheme light'; done \# light theme
for server in $vifm_servers; do vifm --server-name $server --remote +'colorscheme dark'; done \# dark theme
```

If I start a `:shell`, and switch the theme, when closing the shell and going back to vifm, it would cycle through the themes instead of just showing the last set theme.

EDIT.

I don't know why GitHub is corrupting the video, here's a link: https://streamja.com/OGk4X

**Comment by xaizek** [comment]
Hi,

The video seems to work fine for me on GitHub.

The behavious is expected:
1. After `:shell` Vifm doesn't do anything except for waiting for shell to exit and stop using the terminal.
2. You're sending multiple commands and they are accumulating in the pipe.
3. You exit the shell.
4. Vifm gets back control and processes the commands one by one.

I don't see a sensible way of changing the implementation, but you might get the desired behaviour by writing `colorscheme light/dark` command to a file and sending `source path/to/that/file` to Vifm instances. The command will still be run multiple times, but it shouldn't be very noticeable.

**Comment by mustaqimM** [comment]
Okay, thank you for that. I don't come across it often enough, I just thought I'd report it. Please open this issue if you wish
