### ISSUE TITLE
Hide file size in view, Disable delete pop-up

### ISSUE THREAD

**Issue by rickq14** [vifm/vifm#816]
Hi guys. Thanks for vifm.
I want to disable the the delete pop-up every time I want to move files. I couldn't find an option for it.
I also want to hide file and directory sizes in view. I searched the manual for "size", "filesize" etc. I only found "dirsize" but that only changes to showing number of files, there is no
disabling it.
file sizes are a little annoying. if I wanted to see file size, I would just press ctrl+g.

**Comment by xaizek** [comment]
Hello.

Set [`'viewcolumns'`](https://vifm.info/vimdoc.shtml#vifm-%27viewcolumns%27) to remove file size column:
```
set viewcolumns=*{name}..
```

Adjust [`'confirm'`](https://vifm.info/vimdoc.shtml#vifm-%27confirm%27) to not ask about regular deletion:
```
set confirm-=delete
```
