### ISSUE TITLE
Edit Registers with Vim

### ISSUE THREAD

**Issue by BioBox** [vifm/vifm#819]
I believe it would be very useful if there was a way to edit a given register with $EDITOR and save it. Could you add it to `TODO`?

**Comment by xaizek** [comment]
Can you provide a use case? Do you want to load registers and append to them? Just editing can produce useless registers which don't list paths to actual files.

**Comment by BioBox** [comment]
Okay sure. I like to use registers for making playlists of videos, because vifm makes it really easy to grab an arbitrary selection of files.

But wait! I want to remove an entry, or I want to reorder it...
Another problem is that when I move my data to a computer that has different mount points it breaks them all. This could be easily fixed with vim's block line mode if I had the ability to edit regiesters.

**Comment by xaizek** [comment]
Thanks, that sounds like it should be added. Probably need a new command like `:regedit`.
