### ISSUE TITLE
How to hide the two sides of the border?

### ISSUE THREAD

**Issue by liaohui5** [vifm/vifm#821]
![image](https://user-images.githubusercontent.com/29266093/189541260-c545b962-f890-47bb-8e62-33a5b1238275.png)

I only want the middle border, not the two sides,
Because there is no border on the top and bottom, so it looks a bit strange
Is it possible to add an option to control which borders are shown?
For example:
```
borders = 'top,right,bottom,left,middle'
```

**Comment by xaizek** [comment]
Visibility of side-borders is controlled by [`'tuioptions'`](https://vifm.info/vimdoc.shtml#vifm-%27tuioptions%27), do:

```vim
set tuioptions-=s
```

**Comment by liaohui5** [comment]
> Visibility of side-borders is controlled by [`'tuioptions'`](https://vifm.info/vimdoc.shtml#vifm-%27tuioptions%27), do:
> 
> ```viml
> set tuioptions-=s
> ```

ok, thanks you very much!
