### ISSUE TITLE
Prompt user for inserting text

### ISSUE THREAD

**Issue by arturfabriciohahaedgy** [vifm/vifm#824]
Don't really know if this is the best place to make a request/ask a question, if I should make a post about this in another place I say sorry in advance!

Basically I wanted to ask if there's a way to prompt the user for a response, for example, you have the :mkdir command:
`:mkdir <foldername>`
I want to know if there's a way to bind it to a hotkey, and then when I press it, prompts me for the name of the folder to be created on the :command mode in the botton of the screen, and if it there isn't a way to do it, it could become a feature?

Again, if I'm posting about it on the wrong place, I apologize in advance.

**Comment by xaizek** [comment]
I was thinking about this, but it was never implemented. At the moment, the best you can do is a mapping like this one:
```vim
nnoremap ,d :mkdir<space>
```

I wanted to have a macro for a prompt, but the problem is that you can't specify a message then. It probably should be a function instead, which could be used like this:
```vim
nnoremap <silent> ,d :execute 'mkdir' fnameescape(prompt('Enter directory name: '))<cr>
```

**Comment by arturfabriciohahaedgy** [comment]
I see, thanks for the quick reply!

As you said, it could be cool it have an implementation like what I described, since it could be then used for anything you want, but the mapping you showed is already pretty close to what I wanted, so thanks!

**Comment by xaizek** [comment]
Usage example:
```vim
nnoremap ,d : let $DIR_NAME = input('mkdir: ', '', 'dir')
           \| if $DIR_NAME != ''
           \|     execute 'mkdir' fnameescape($DIR_NAME)
           \| endif<cr>
```
