### ISSUE TITLE
consider supporting additional plugin search path

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#825]
vifm only finds plugins from $VIFM directory, but what if i want to load a lua plugin outside $VIFM dir?

so currently i have two option:
* change $VIFM to that plugin's parent dir, but this will disable all plugins in $HOME/.config/vifm/plugins
* `ln -s myplugin ~/.config/vifm/plugins`, that's what i planned to do at now.

would you consider adding additional plugin-search-path on the fly? for example accept a cli flag

**Comment by haolian9** [comment]
ah, i found some std lua modules are not available in lua plugin at now: os, math. maybe issues like this one are too early to consider.

**Comment by xaizek** [comment]
> would you consider adding additional plugin-search-path on the fly? for example accept a cli flag

A CLI flag for this can be added.
