### ISSUE TITLE
vifm.plugin.require is not available in plugin/not-init.lua files

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#827]
hi, i found that the `vifm.plugin.require` is only exposed to some-plugin/`init.lua`,
for example, in the `data/plugins/hello` plugin, i can not use this require in `command.lua`.

is that intended? i currently use a workaround like this:

```lua
-- init.lua
local commands = vifm.plugin.require('commands')(vifm.plugin.require)

-- commands.lua
return function(require)
    local foo = require('another-module-in-same-dir')
    ....
end
```

**Comment by xaizek** [comment]
Hi. This wasn't intented. I probably messed up with Lua environment. Thanks for the report.
