### ISSUE TITLE
is there a way to inform plugins that vifm is going to exit?

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#828]
i noticed there is `:autocmd`, but i failed to find an event like `VimLeave`.

my usecase is that: i will open some files in a plugin, and want to close them before vifm exited.

**Comment by xaizek** [comment]
There isn't, there is no `VimLeave`-like event and there are no events in Lua as of now.

**Comment by haolian9** [comment]
oh, thanks for the reply.
has this feature been planned for lua plugins? though there are other ways i can take.

**Comment by xaizek** [comment]
> has this feature been planned for lua plugins?

Yes, there will be some kind of hooks.
