### ISSUE TITLE
OSX config options

### ISSUE THREAD

**Issue by larryhynes** [vifm/vifm#83]
I have, at this stage, a fairly complete set of OSX-specific config options in my vifmrc, mostly for file launching / viewing, with a few additional bits. If I tidy it up it might make a good starting point for a 'base' example OSX config. Would you have any interest in including OSX options, either commented out in the existing sample vifmrc or as an additional example file? I would be very happy to maintain it, or contribute to it in any way that makes life easier for you! ;)

**Comment by xaizek** [comment]
> Would you have any interest in including OSX options, either commented out in the existing sample vifmrc or as an additional example file?

Definitely! I'd probably choose separate file like `vifmrc-osx`. I already thought about adding Windows-specific one, so there might be three versions: GNU/Linux, Windows and OSX. It should be possible to pick the correct automatically one on the first run and leave the rest for reference (might be easier than going through documentation).

**Comment by larryhynes** [comment]
Excellent! I'll start from your existing example vifmrc, add the OSX specific options where applicable, add any 'extra' ones and make a pull request for you to review.
