### ISSUE TITLE
View comparing results (Identical, Different, Unique left, Unique right)

### ISSUE THREAD

**Issue by IAmKapuze** [vifm/vifm#832]
Information about comparing results (Identical, Different, Unique left, Unique right) can be easy got from _fill_side_by_side_ funcs. It can be printed, for example, in _status_bar_.
I would like to help with implementation, but after returning from comparing func _status_bar_ is reset (I tried using _ui_sb_msg_ func at the end of _compare_two_panes_), and I can't understand how to set status bar message to comparing window.

Also, may be there is a way to show only files from single list (Identical/Different/Unique left/Unique right) without reexec comparing (for example, make additional separated list (views) for each result type and switch between them with commands (_showall_, _showidentical_, _showdifferent_, _showuniqueleft_, _showuniqueright_))?

**Comment by xaizek** [comment]
> Information about comparing results (Identical, Different, Unique left, Unique right) can be easy got from _fill_side_by_side_ funcs. It can be printed, for example, in _status_bar_.

You mean printing statistics? You need to return non-zero from `compare_two_panes()` to preserve status bar message.

> Also, may be there is a way to show only files from single list (Identical/Different/Unique left/Unique right) without reexec comparing (for example, make additional separated list (views) for each result type and switch between them with commands (_showall_, _showidentical_, _showdifferent_, _showuniqueleft_, _showuniqueright_))?

That would require always doing the full diff and preserving it to process later. Current implementation throws averything away when it's done and might not even build the full state at any point if it wasn't needed to execute the command (don't know if it saves much resources though).

**Comment by IAmKapuze** [comment]
> You mean printing statistics? You need to return non-zero from `compare_two_panes()` to preserve status bar message.

Yes, it works. Thanks
I did some draft implementation, but I have some difficulties (questions). I will create draft PR

Also I think about switching between result lists. For best user-experience it should be toggled (for example, only Unique Left/Unique Right lists can be displayed). What do you think about it?

**Comment by xaizek** [comment]
> Also I think about switching between result lists. For best user-experience it should be toggled (for example, only Unique Left/Unique Right lists can be displayed). What do you think about it?

This probably needs a set of `show*` arguments for `:compare` to specify initial state or switch to the desired one of the last comparison.

**Comment by IAmKapuze** [comment]
May be diff can be stored fully, while comparison window is open? It can be threw after closing comparison

**Comment by xaizek** [comment]
`:compare listunique` doesn't create a compare view at all, so that would take a bit more tracking to find out when to free comparison results.

**Comment by xaizek** [comment]
Stats were handled in #833 (1f13438c47d240bfa1acc7379be8435934a1f020).
