### ISSUE TITLE
[Feature request] Fixed column count option for transposed lsview

### ISSUE THREAD

**Issue by loki1368** [vifm/vifm#835]
I have a habit from the past what file commander should have a two columns on a pane. I've configured vifm to make behavior like old-school file commanders using lsview and lsoptions=transposed. 
And it's almost what i want. But I'm used to columns on a pane should always be a same size, for example, two columns on a pane with same size. 
Currently vifm automatically calculates size of first pane from size of max file length in the catalogue and often i'm getting columns with different sizes or even only one column for a catalogue. 
Could you please add an option to lsoptions with ability to lock column count(with same sizes)? 
Something like :set lsoptions+=twofixedcolumns.

**Comment by xaizek** [comment]
So it should work the same (no scrolling down), but always layout files in two columns? From the title alone I thought you want to limit maximum number of columns and have them scrolling down.

**Comment by loki1368** [comment]
Now columns size calculates from max length of filename in the current catalogue. I want a two columns on the panel with the same size. I've added a screenshot(takes from far2l commander) what i want to see in the panel: 
![Screenshot_20221031_105140](https://user-images.githubusercontent.com/11331117/198958306-eb448d54-f1f4-4c0a-9ae3-10e772608fa9.png)

**Comment by loki1368** [comment]
static size_t
 get_max_filename_width(const view_t *view)
 {
+       size_t max_max_len = panel_size / 2;
        size_t max_len = 0UL;
        int i;
        for(i = 0; i < view->list_rows; ++i)
@@ -1894,6 +1895,9 @@ get_max_filename_width(const view_t *view)
                        max_len = name_len;
                }
        }
+       if(max_len > max_max_len)
+               max_len = max_max_len;
+
        return max_len;
 }

I've made it for myself with the dirty code like this. But i think i couldn't prepare good PR for the vifm.

**Comment by xaizek** [comment]
Usage:
```
:set lsoptions+=columncount:2
```

**Comment by loki1368** [comment]
I've just tried new feature! Awesome! Thank you very much!
