### ISSUE TITLE
Cannot open files with spaces in filename

### ISSUE THREAD

**Issue by PhilRunninger** [vifm/vifm#836]
When using the default key <kbd>l</kbd> or <kbd>Enter</kbd> on a file that has spaces in its name, **vifm** is not escaping the spaces in a way Windows understands them. That results in **vim** treating the arguments as separate files. It also happens when running this command inside **vifm**: `:e foo bar.txt`

I'm using version 0.12.1 on Windows 10. It doesn't matter if I use Powershell or CMD. Here is a screenshot of the process tree, showing the resulting command: `vim file\ with\ spaces2.md`.

![image](https://user-images.githubusercontent.com/5598066/200001679-3036c8f6-05ab-430e-bf5c-37ed09e87fa9.png)

**Comment by xaizek** [comment]
Damn it, looks like it was always partially broken on Windows for cmd/powershell, but then I made working code reuse non-working code :) It incorrectly always uses POSIX escaping and works for bash on Windows just fine.

It should be possible to workaround this by using something similar to `filetype * vim %"f` (depends on your `'vicmd'`) after all other `filetype` lines in `vifmrc`.

By the way, `:e foo bar.txt` tries to open two files, use `:e foo\ bar.txt`, `:e "foo bar.txt"` or `:e 'foo bar.txt'` to open only one. 

Thanks for the report.

**Comment by PhilRunninger** [comment]
Thanks for the quick response. That workaround does the trick. I can also confirm that **vifm** is working as expected in my Git bash shell without the workaround. I'll close the issue.

**Comment by SpatialSymmetry** [comment]
I'm using powershell with `set shell=pwsh` which works fine. But I can't open files which contain spaces inside vifm with `nnoremap o :!Start-Process "%f"<CR>`. Why is that? double quotations doesn't work. @xaizek is there a way to work around this?

**Comment by xaizek** [comment]
> The command `Start-Process` and `Invoke-Item` commands can handle spaces, there is no need for escaping, all vifm needs to do is to pass the name of the file as is.

But you're adding quotes in `nnoremap o :!Start-Process "%f"<CR>` as if they are necessary.  If you mean that they aren't needed with quotes, then try using `nnoremap o :!Start-Process %"f<CR>` instead to let Vifm expand file names in double quotes.

**Comment by SpatialSymmetry** [comment]
@xaizek `nnoremap o :!Start-Process %"f<CR>` works! Thanks! I thought `%f` expands to the file name under cursor, never thought of `%"f`.

**Comment by xaizek** [comment]
> I thought `%f` expands to the file name under cursor, never thought of `%"f`.

They are equivalent in meaning, but the first one will expand to something like `file\ with\ spaces` and the second one to `"file with spaces"`.  "-variant is more suitable for Windows-specific shells which don't get backslash-escaping.  Basically, all macros that expand to paths have two versions of escaping.
