### ISSUE TITLE
Some Folders or files missing in the orginal folder after yanking and pasting

### ISSUE THREAD

**Issue by OneGuyonMars** [vifm/vifm#841]
**Y** or **yy** copies the directory (It works fine) but pasting it resulted in "Directory Check" error. Also some files and folders in the orginal folder was missing.
However **dd** works fine.
Tested with *~/.mozilla* folder

**Comment by xaizek** [comment]
This sounds like you've moved a directory which was opened in one of the panes. Please explain what you're doing in more detail, e.g. what is the location of panes when you move `~/.mozilla` folder.

**Comment by OneGuyonMars** [comment]
~/ and ~/Documents at the time of pasting however I used the same pane for both the operations.

**Comment by xaizek** [comment]
So, like this?
1. You did <kbd>yy</kbd> on `.mozilla` while in `~`
2. Changed to `~/Documents`
3. Pressed <kbd>P</kbd>?

Do you mean that files in `~/Documents/.mozilla` are missing after that?

**Comment by xaizek** [comment]
And are now in `~/Documents`? Mind that <kbd>P</kbd> (upper case) **moves** files, while <kbd>p</kbd> (lower case) copies them.

**Comment by OneGuyonMars** [comment]
I thought p and P did the same thing. Thanks for correcting me.
