### ISSUE TITLE
i/o operations under background

### ISSUE THREAD

**Issue by og900aero** [vifm/vifm#842]
How can map keybindings to copy, move in background?

I use now the following mapping (F5 copy, F6 move)

`nnoremap <f5> yy<tab>p<tab>`
`nnoremap <f6> yy<tab>P<tab>`

**Comment by xaizek** [comment]
Either variant should do (roughly equivalent in background):

```vim
nnoremap <silent> <f5> :copy &<cr>
nnoremap <silent> <f6> :move &<cr>
```

```vim
nnoremap <silent> <f5> :yank | winrun , put &<cr>
nnoremap <silent> <f6> :yank | winrun , put! &<cr>
```

**Comment by og900aero** [comment]
Works like a charm, thank u! I dont use silent, because I want progress bar.

Is it possible to change the background color of the progress bar that appears at the bottom when copy/move in the background? I try my colors configuration (custom Molokai), but I can't find such an option

**Comment by xaizek** [comment]
> Is it possible to change the background color of the progress bar that appears at the bottom when copy/move in the background? I try my colors configuration (custom Molokai), but I can't find such an option

It's controlled by `JobLine` highlight group.
