### ISSUE TITLE
Enter passphrase for key is not interactive

### ISSUE THREAD

**Issue by mark2185** [vifm/vifm#843]
When trying to use `fuse` by "executing" a file with the content of `user@hostname:/`, the `cmd` line shows the text `Enter passphrase for key /home/user/.ssh/key`, but it's not interactive.

Is there a way to insert it somehow? I tried using a `ssh-agent` but it doesn't seem to work, it still asks me for the passphrase.

**Comment by xaizek** [comment]
From the [docs](https://vifm.info/vimdoc.shtml#vifm-FUSE_MOUNT3):
```
   - %FOREGROUND means that you want to run mount command as a regular
     command (required to be able to provide input for communication with
     mounter in interactive way).
```
Like in:
```
filetype *.ssh
       \ {Mount with sshfs}
       \ FUSE_MOUNT2|sshfs %PARAM %DESTINATION_DIR %FOREGROUND,
```

**Comment by mark2185** [comment]
Ah, great. Thanks and sorry for the noise!
