### ISSUE TITLE
Help pages seem broken

### ISSUE THREAD

**Issue by infinitewhileloop** [vifm/vifm#844]
First of all, thanks for this great file manager.

Entering `:h` or `:help` in Command-line mode leads to this error:

```
Error detected while processing command line:
E149: Sorry, no help for vifm-app.txt
Already only one window
```

This error message is shortly visible, then I am redirected to an empty vim file.

`:set novimhelp` seems to fix this issue, but this has the side effect that e.g. `:h vifm-colors` returns the error `No arguments are allowed when 'vimhelp' option is off`.

**Comment by xaizek** [comment]
How did you obtain Vifm? If you've built it manually, using help will need installation as well. If it's a prebuilt package, then it might be incomplete.

**Comment by infinitewhileloop** [comment]
I tried both `sudo apt install vifm` and the AppImage. Both times, this issue occurred.

**Comment by xaizek** [comment]
What does `set vicmd? vixcmd?` show in Vifm and what does `:echo v:argv` print in Vim instance after that error?

**Comment by infinitewhileloop** [comment]
```
vicmd=vim
vixcmd=
```
and

```
['vim', '-c', 'set runtimepath+=/usr/share/vifm/vim-doc', '-c', 'help vifm-app.txt', '-c', 'only']
```

I found [one other user](https://github.com/NixOS/nixpkgs/issues/151841) who experienced the same issue.

**Comment by xaizek** [comment]
It doesn't work from AppImage, because it incorrectly also produces `/usr/share/vifm/vim-doc` (without AppImage root prepended).

NixOS likely changes path in some way that help file isn't found.

I suspect that contents of your `/usr/share/vifm/vim-doc` is different from what it should be. Here's listing of mine:
```
$ find /usr/share/vifm/vim-doc
/usr/share/vifm/vim-doc
/usr/share/vifm/vim-doc/doc
/usr/share/vifm/vim-doc/doc/tags
/usr/share/vifm/vim-doc/doc/vifm-app.txt
/usr/share/vifm/vim-doc/doc/vifm-lua.txt
```

If `tags` isn't present, Vim might not be able to use this directory for `:help`. One more version is that your local Vim settings interfere, but let's check all files are there first. If they are, doing `cd /usr/share/vifm/vim-doc/doc && vim` and then something like `:help vifm-gg` should work if their contents is correct.

**Comment by infinitewhileloop** [comment]
On the system where I used the AppImage, there is no `/usr/share/vifm` directory.

On the system where I installed Vifm using apt, there is a `/usr/share/vifm` directory, but no `vim-doc` subdirectory.

```
$ ls /usr/share/vifm
colors  vifm-help.txt  vifm-media  vifmrc
```

**Comment by xaizek** [comment]
> On the system where I installed Vifm using apt, there is a `/usr/share/vifm` directory, but no `vim-doc` subdirectory.

The installation is incomplete. I confirm lack of files on Debian 11 and the same at https://packages.debian.org/sid/amd64/vifm/filelist (`tags` files removed and other files moved). It's an issue with packaging and should be reported to maintainer of the package.

As a workaround, if you install https://github.com/vifm/vifm.vim, `:help` will start working. You can remove everything but `doc` directory there if you don't need it.

**Comment by infinitewhileloop** [comment]
I'm glad to hear the cause wasn't my Vim configuration :smiley: 

Thanks again for creating Vifm, I really like it.

**Comment by xaizek** [comment]
> I guess this means a lot of systems are affected by this bug, I noticed it both on Linux Mint, Raspberry Pi OS and Kali Linux.

All distributions that reuse Debian packages are likely to be affected. Will you report it there?

> Thanks again for creating Vifm, I really like it.

Thank you too, I'll fix AppImage.

**Comment by infinitewhileloop** [comment]
> All distributions that reuse Debian packages are likely to be affected. Will you report it there?

I have reported the bug to `submit@bugs.debian.org` and I also notified the package maintainer.

**Comment by xaizek** [comment]
Thanks for reporting it, I'm not very familiar with Debian and derivatives and this should somehow be tracked in upstream. 

@onovy, basically:
 * `tags` files should be preserved (non-root Vim won't be able to generate them) or `:help tag` won't work
 * files from `vim-doc` should not be moved (can be copied), that path is used internally
 * I'm not sure whether addon manager is necessary, one can enable the plugin manually via `set rtp+=/usr/share/vifm/vim` if desired (addon manager probably loads it unconditionally, which I think is a disadvantage)

**Comment by infinitewhileloop** [comment]
Hello @xaizek and @onovy, I just wanted to let you know that this bug is still present in the recently released Debian 12 'Bookworm', when installed through `apt`, so it will affect a lot of distributions in the years to come.

**Comment by xaizek** [comment]
Hi.

Well, given that in the previous years only you have reported it, it doesn't seem to bother many people.  For comparison, a bug with inverted highlighting of the inactive pane affected a single release and was reported at least 5 times if I remember it correctly.

But I agree that the package should be updated.  The good news is that since this a packaging issue, I think the fix can get into any distribution no matter how stable it is.

**Comment by tunaflsh** [comment]
Hi. I installed https://github.com/vifm/vifm.vim as per instructions there and `:help` is still not working. However, it works when I installed through `vim-addons-manager`.

**Comment by tunaflsh** [comment]
No I don't generate help tags, I don't know how to do that either. Is there a recommended way to make tags? I've given up on using `vim-addons-manager` because it broke something else.

**Comment by xaizek** [comment]
It's done via [:helptags](https://vimhelp.org/helphelp.txt.html#%3Ahelptags) command.  Which in this case could be done as
```bash
vim +'helptags ~/.vim/pack/bundle/start/vifm/doc' +q
```
