### ISSUE TITLE
`/` will cause selection error

### ISSUE THREAD

**Issue by NEX-S** [vifm/vifm#849]
![image](https://user-images.githubusercontent.com/97107165/205075613-e0a847f3-704d-419f-adc7-cf7587cd8224.png)
if i use `/` to search `.config` and it will cause this error randomly, I don't know why, is there any option can make `/` not select dir or files thx!

**Comment by xaizek** [comment]
Turn off [`'hlsearch'`](https://vifm.info/vimdoc.shtml#vifm-%27hlsearch%27):
```vim
set nohlsearch
```
