### ISSUE TITLE
quickly move in preview pannel will cause character blinking on other panel 

### ISSUE THREAD

**Issue by NEX-S** [vifm/vifm#850]
![image](https://user-images.githubusercontent.com/97107165/205076494-fcad6f6d-a720-40ce-bdb8-7378abc1d0b3.png)
if I move the cursor in the right panel the left panel will have some redraw problem no matter how I config the `previewoptions` option :sob:

**Comment by xaizek** [comment]
`'previewoptions'` doesn't have anything related to redrawing text. It might depend on the terminal and its double bufferring settings. If you're scrolling and the rest of the screen seems to scroll a bit and then go back, that's unlikely to have a fix, curses apparently does exactly that: scroll the whole screen and then redraw what doesn't need to be scrolled.
