### ISSUE TITLE
Feature request - search and change directory in one keystroke

### ISSUE THREAD

**Issue by hholst80** [vifm/vifm#853]
Maybe it is easier to show a video of the feature I would like to see in vifm

https://user-images.githubusercontent.com/6200749/208267857-bba34318-1db4-4e92-987e-8bd2f0a9a814.mp4

**Comment by xaizek** [comment]
> Maybe it is easier to show a video of the feature I would like to see in vifm

I don't think that worked :)

Do you want a (potentially builtin) mapping similar to this one?
```vim
cnoremap <c-e> <cr>l/
```
It stops search, enters directory under the cursor (or opens a file), then restarts search. Behaviour for files can be changed with a check for file type.

**Comment by hholst80** [comment]
I think if I knew already before the search what I wanted to do - find a single directory and change to it - I could augment the search in that way. I will try this.

This feels like a "find mode" in vi where instead of leaving find mode by pressing enter, I execute the default action (by pressing ctrl-e) and stay in find mode.

**Comment by xaizek** [comment]
I think it will be beneficial to have this builtin. It could for example:
 * go to previous directory for empty input to allow fixing a mistake
 * work for local filter as well

Builtin also won't use the mapping hack (it's not reliable in general case) and will only work in supported sub-modes of command-line mode.

Requests for ways to do quicker cd came up several times in the past and this seems like a nice way of doing it.

**Comment by dmocek** [comment]
I think there's a way to support an easier and faster navigation here and you hinted at it above with "find" mode (or maybe it should be called "navigation" mode).  Find/navigation mode like this isn't something that Vi supports, but vifm is using Vi modes and keystrokes in ways Vi never anticipated.

The suggestion is to put vifm in "find/navigation mode" (using '//'?).  When in this mode, characters that are typed highlight the first directory/file with that character and hitting 'Enter' traverses into that directory or selects the file.  Here's an example:

Directory/File listing:
..
Desktop/
Documents/
Downloads/
Pictures/
Temp/

Let's say Temp is currently highlighted.  You go into find/navigation mode '//'.  Typing 'D' highlights the first dir/file starting with D, Desktop.  Typing 'o' highlights Documents.  Typing 'w' highlights Downloads (search in vifm already does this).  Enter moves you into the Downloads directory and clears the 'Dow' you typed so you can start again (search already does this but you have to hit Enter twice to traverse into the directory from search mode).  Note: you are still in find/navigation mode (maybe this can be an option...Enter leaves you in that mode or takes you out).  'Esc' takes you out of find/navigation mode (again, search already does this).  Up/Down arrows still work (Up/Down doesn't work in search).

Using this you can much more easily and quickly navigate an entire directory structure.  As it stands now, I have to hit '/' and Enter (twice) to search and traverse into a directory.  I know there are text-based file managers that work similar to this.

**Comment by xaizek** [comment]
I've implemented this without adding a new mode on `cmdline-navigation` branch of this repository. If all we need is a couple of shortcuts in addition to search/filtering, a mode seems like too much. Moreover, you'd have to know whether you'll need navigation or not before starting a search.

An advantage of a mode could be more mode-specific shortcuts, but most existing shortcuts are used for editing which would remain in a new mode as well, so same conflicts.

@hholst80, @dmocek, anyone willing to try it out?

> using '//'?)

If only by special handling of `/` for empty prompt (similar to `less`), otherwise there would be a delay on starting normal search.

Given that both search/filtering could be useful, a would probably use a key from search/local filter to go into navigation rather than a separate shortcut from a normal mode.

> Up/Down doesn't work in search

It does, but it recalls history items with a matching leading part.

**Comment by dmocek** [comment]
Yes!...giving it a shot...

**Comment by dmocek** [comment]
This does work as advertised, but I feel it makes the keystroke experience worse.  It's easier to hit Enter twice than Ctrl-J, at least to me, and it still requires two key strokes.

From my perspective, it also doesn't address the general navigation issue that to move around the directory structure in vifm can be improved.  The major advantage of using vi keybindings is to not have to move your fingers much (read to the arrow keys in this case) and using search is cumbersome as it requires you to use '/' every time you move into a directory.  I suggested a mode to get rid of needing to use '/' when moving to every directory.  Think of trying to move to a directory 10 directories from where you currently are.

BTW, I suggested '//' as I thought it might be quick to activate find/navigate mode that way.  I can see how it will be a problem.  Any other quick set of keystokes is sufficient.

Thanks for the quick turn-around!

**Comment by hholst80** [comment]
I could not compile it on Ubuntu 22.04 LTS. Is it supposed to work out of the box?

```
$ ./configure
...
[no errors]
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating build-aux/config.h
config.status: build-aux/config.h is unchanged
config.status: executing depfiles commands
```

```
$ make
 cd . && /bin/bash /home/om/Documents/GitHub/vifm/build-aux/missing automake-1.16 --gnu
configure.ac:7: error: version mismatch.  This is Automake 1.16.5,
configure.ac:7: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:7: comes from Automake 1.16.2.  You should recreate
configure.ac:7: aclocal.m4 with aclocal and run automake again.
src/Makefile.am:403: warning: filter-out version.o, $(vifm_OBJECTS: non-POSIX variable name
src/Makefile.am:403: (probably a GNU make extension)
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:329: Makefile.in] Error 1
```

**Comment by xaizek** [comment]
> I could not compile it on Ubuntu 22.04 LTS. Is it supposed to work out of the box?

I should have mentioned running `scripts/fix-timestamps`.  Then you don't need to do anything with autoconf.  Git doesn't preserve timestamps which confuses autoconf.

> It's easier to hit Enter twice than Ctrl-J, at least to me, and it still requires two key strokes.

Ctrl-J can be remapped to something more convenient to you. It's the same number of keystrokes as in your comment or are you counting <kbd>Ctrl</kbd> and <kbd>J</kbd> separately? Using just Enter needs some kind of a submode, need to hack it to see how it will do.

**Comment by xaizek** [comment]
Pushed WIP commit with navigation "mode". Differences are as follows:
 - toggled via <kbd>Ctrl-y</kbd>
 - entering is via <kbd>Enter</kbd> or <kbd>Right</kbd>
 - <kbd>Ctrl-p</kbd>/<kbd>Up</kbd> move cursor up
 - <kbd>Ctrl-n</kbd>/<kbd>Down</kbd> move cursor down
 - <kbd>Left</kbd> goes to previous directory (same as <kbd>Ctrl-O</kbd>, which now can also be changed to go back in directory history)
 - no history saving or querying

Pressing <kbd>Enter</kbd> actually feels harder than pressing <kbd>Ctrl-m</kbd> or <kbd>Ctrl-j</kbd> when <kbd>CapsLock</kbd> acts as a <kbd>Ctrl</kbd>.

**Comment by dmocek** [comment]
@xaizek Ctrl-y doesn't do anything for me.  I verified the branch and see your changes in the logs.  I'm in the left pane and I hit Ctrl-y and expect to be in navigation mode, but I don't see anything.  What's the experience supposed to be here?

BTW, Worker (http://www.boomerangsworld.de/cms/worker/) is closer to the navigation experience I'm looking for.  Install and run it and go to your home directory.  You're always in what I call navigation mode.  Start typing 'D' (assuming the directories in the example in the previous message).  You will now only see the dirs/files that start with 'D'.  Continue typing 'o' and 'w', to choose the 'Downloads' dir and hit Enter.  You can keep doing this while traversing your whole file system.  Backspace takes you up to the parent dir.  Up/Down arrows also work.  A very easy and quick keyboard-focused navigation system.

I don't need the filtering as I type as I like selection like vifm does better.  However, I do think being in navigation mode as the default mode is better...navigation is the first thing I want to do and what I want to do most often.  However, I understand how much of a change this would be and being able to switch into and out of navigation mode is sufficient.

**Comment by hholst80** [comment]
The navmode addresses all the concerns I had with the first implementation. But can we make navmode a persistent mode? ctrl-y should act like a `set navmode!`? 

I want to be able to navigate with ctrl-{h,j,k,l} in navmode the only difference from normal navigation mode would be that I have to hold down CTRL. (or Caps)

**Comment by hholst80** [comment]
> Though Worker filters files and selects one instead of just selecting one, I don't need the filtering as I type as I like just the selection that vifm does better. However, I do think being in navigation mode as the default mode is better...navigation is the first thing I want to do and what I want to do most often. However, I understand how much of a change this would be and being able to switch into and out of navigation mode is sufficient.

exposing a "mode" would allow anyone to change their preference in what mode they would like to start vifm in.

**Comment by dmocek** [comment]
Being able to specify the mode to start in would be nice.

**Comment by xaizek** [comment]
Persistent navmode is something else. It would likely have to be decoupled from command-line mode and somehow deal with changes in underlying directories that can invalidate search/filtering results. Currently command-line mode doesn't update views when file system changes.

Mind that modes differ in their behaviour not just by the set of keys.  They form (quite flat) hierarchy, an arbitrary mode can't be just entered.  Normal mode is meant to be the root mode in Vim where you spend most of your time and implementation reflects that.

> I want to be able to navigate with ctrl-{h,j,k,l} in navmode the only difference from normal navigation mode would be that I have to hold down CTRL. (or Caps)

I may try adding a separate namespace for navigation so that you could map keys for navigation separately from command-line mappings.

**Comment by xaizek** [comment]
Pushed another WIP commit that separates `cmap`/`cnoremap`/`cunmap` from new `amap`/`anoremap`/`aunmap`.

**Comment by hholst80** [comment]
Works great! I am not sure this is the best way to do it, are the key bindings "hardcoded" into the source or is there function I can call directly instead of relying on the "default" keymappings for the functionality?

```
amap <c-h> <c-o>
amap <c-l> <c-m>
amap <c-k> <c-p>
amap <c-j> <c-n>
```

**Comment by hholst80** [comment]
We misunderstood each other on the persistent navmode. I do not expect vifm to fall back to navmode per se after each operation - say, open a file for edit, rename, etc.

But what I want is that when I press `/` to find, I use the `navmode` and do not have to press ctrl-y each time. 

I could map `/` in normal mode to `/<c-y>`. So I did, and it works great. :-)

**Comment by xaizek** [comment]
> Works great! I am not sure this is the best way to do it, are the key bindings "hardcoded" into the source or is there function I can call directly instead of relying on the "default" keymappings for the functionality?

That's the way to do it. There are no functions like in `mutt`/`readline` or elsewhere, user keybindings are defined in terms of sequences of keys.

> But what I want is that when I press `/` to find, I use the `navmode` and do not have to press ctrl-y each time.
> 
> I could map `/` in normal mode to `/<c-y>`. So I did, and it works great. :-)

You're right, I was thinking of something different there. At the moment `'navmode'` option looks basically equivalent to the mapping you've done, an option can be added later if there will be a use case where it makes noticeable difference in functionality.

Thanks for testing this out. If there will be no further corrections (@dmocek?), I'll clean up the implementation and commit the changes.

**Comment by dmocek** [comment]
How do you configure amap?

**Comment by xaizek** [comment]
> How do you configure amap?

Like in the comment above https://github.com/vifm/vifm/issues/853#issuecomment-1374891284, same as mappings for other modes.

**Comment by xaizek** [comment]
Yes, to `vifmrc` or type it in after <kbd>:</kbd>. `vifmrc` is a set of command-line commands. `amap` has the same syntax as any other `*map` command ([mappings docs](https://vifm.info/vimdoc.shtml#vifm-mappings)).

**Comment by dmocek** [comment]
The documentation doesn't give me enough information.  I tried adding this to vifmrc:
`amap / /<c-y>`
but I get an error when starting vifm.

**Comment by xaizek** [comment]
`amap` is available only on the branch used in this issue. `amap` defines user mappings which are available after you enter this navmode. You're hitting <kbd>/</kbd> in normal mode and thus need to use `nmap`.

**Comment by dmocek** [comment]
OK.  I'm able to get into nav mode.  Love it!, this is almost the experience I'm looking for (see below).  But the mapping isn't working for me (/ for /<c-y>).  I'm adding this to vifmrc:
`nmap / /<c-y>`
Am I missing something?

One additional question.  Using 'gg' to 'go home' (..) while in nav mode doesn't work and neither does hitting the 'HOME' key.  Seems like the only thing that does work is 'Esc'aping out of nav mode.  Anything that can be done go quickly/simply go to the top (where '..' is) while still in nav mode?

**Comment by dmocek** [comment]
nnoremap works, much better!

**Comment by xaizek** [comment]
> For some reason `nmap` variant doesn't work, will need to look into this.

Well, of course `nmap` is not supposed to work as it would cause infinite recursion :)

Force-pushed the branch with 4 more keys working. Will adjust and merge to `master` next.

**Comment by dmocek** [comment]
HOME/END works for me, thanks!  PgUp/Down isn't.

**Comment by xaizek** [comment]
> PgUp/Down isn't.

It works as in normal mode: cursor isn't moved if no scrolling is done.

**Comment by hholst80** [comment]
Great! The only downside is that now I have to start installing vifm from git as part of my local setups on my many dev machines. :-) #bleedingedge

**Comment by xaizek** [comment]
> The only downside is that now I have to start installing vifm from git as part of my local setups on my many dev machines.

Building with `./configure --sysconfdir=/etc --prefix=/usr` to reuse data from an existing package and making `vifm` binary available in `$PATH` is likely to be enough if you only need this for a single user. I can also build AppImage from `master` that should work in most systems.

**Comment by dmocek** [comment]
It's working, thanks.

**Comment by xaizek** [comment]
9b44c82661f3ee46339ddc17dd6d547a93e63c73 changed navmode to leave the mode instead of opening files on <kbd>Enter</kbd> by default.  Add this to your configuration to get the previous behaviour:
```vim
set navoptions=open:all
```

**Comment by davidsierradz** [comment]
Hi, I'm trying this new mode, `<C-n>` and `<C-p>` behavior is different from what I expected from being a search sub-mode. I expect `<C-n>` and `<C-p>` to behave as `n` and `p` after a search (going to next and previous matched item respectively) and not `<Down>` and `<Up>` (going to the next and previous item, even if is not matched by the  current query). Could this be configured with an `amap` mapping, or can I configure other mapping for this behavior? Hope it makes sense. Thanks!

**Comment by xaizek** [comment]
Hi, @davidsierradz.

Mind that navigation submode can also be used during filtering which is a different kind of search. By the way, <kbd>Ctrl-N</kbd>/<kbd>Ctrl-P</kbd> do traverse matches there.

The behaviour you're talking about will probably be implemented as <kbd>Tab</kbd>/<kbd>Shift-Tab</kbd> in search with and without <kbd>Ctrl-Y</kbd> (Vim uses <kbd>Ctrl-G</kbd> and <kbd>Ctrl-T</kbd> but they don't make much sense).

Until then, you can try (exiting to normal mode to run <kbd>n</kbd>/<kbd>N</kbd>):

```vim
anoremap <c-n> <c-y><esc>n/<c-p><c-y>
anoremap <c-p> <c-y><esc>N/<c-p><c-y>
```

**Comment by xaizek** [comment]
> The behaviour you're talking about will probably be implemented as <kbd>Tab</kbd>/<kbd>Shift-Tab</kbd> in search with and without <kbd>Ctrl-Y</kbd> (Vim uses <kbd>Ctrl-G</kbd> and <kbd>Ctrl-T</kbd> but they don't make much sense).

Committed in a546e3b.
