### ISSUE TITLE
in compare view make selection, yank and paste availabe or 'do' / 'dp' with selection

### ISSUE THREAD

**Issue by Markuzcha** [vifm/vifm#857]
...is this possible or availabe already?

**Comment by xaizek** [comment]
<kbd>do</kbd>/<kbd>dp</kbd> operate on current file only, should be possible to handle each file in selection. Yank&paste is problematic because yanking just stores list of paths and that's not enough in this case.

**Comment by Markuzcha** [comment]
`do` / `dp` for the whole selection (meaning several files) would be very handy, since I then wouldn't need to hit these keymaps for every single file.
To me it appears this still isn't possible.
