### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [vifm/vifm#860]
Would you like to add more error handling for return values from functions like the following?
- [fseek](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [read_file](https://github.com/vifm/vifm/blob/a703eed1fd2f6e23e89aa3ac468677e7f7af7fcf/src/utils/parson.c#L283)
- [pthread_mutex_lock](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html "Lock a mutex.") ⇒ [import_error_jobs](https://github.com/vifm/vifm/blob/165f64687b485ad407c0edca4ce9d483e1d5c281/src/background.c#L523)

**Comment by xaizek** [comment]
`parson.c` is from https://github.com/kgabis/parson :) However, this can affect functionality, so I can fix it locally even if upstream won't do anything about it/accept PR.

I guess `pthread_mutex_lock()` can at least fail due to a deadlock and that's worth checking on the off chance it will ever happen.

Thanks.

**Comment by elfring** [comment]
:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by elfring** [comment]
:thought_balloon: It seems that the maintenance can be unclear also for the software component “parson”.

**Comment by elfring** [comment]
:eyes: [Further update candidates were left over](https://github.com/vifm/vifm/blob/91f8b14dc6e8bac53966dacb24ab46f201c035bb/src/background.c#L154 "Update candidate: bg_init()").

:thinking: It is just safer to [handle more “exceptional” situations](https://wiki.sei.cmu.edu/confluence/display/c/EXP12-C.+Do+not+ignore+values+returned+by+functions "Do not ignore values returned by functions"), isn't it?

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by xaizek** [comment]
Did some more updates.

> It is just safer to handle more “exceptional” situations, isn't it?

Not necessarily, it doesn't always add value.

> How do you think about to improve static source code analysis also for this software?

Already using it.

> How will chances evolve to benefit any more also from the means of aspect-oriented software development?

It's not generally useful and is hardly useable in C.

**Comment by xaizek** [comment]
> Would you like to point any tools out accordingly?

cppcheck, analysis of GCC and Clang, coverity.

> Some development approaches are worth for another look, aren't they?

That's a separate language and not something an existing code can use.

**Comment by elfring** [comment]
>…, analysis of …

:thought_balloon: I imagine that such tools can be configured to point discarded/unused/ignored return values out.


>That's a separate language

:thinking: Additional languages are probably needed to [express desirable pointcuts and advices](https://en.wikipedia.org/wiki/Pointcut "Description for the usage of pointcuts").


>and not something an existing code can use.

:crystal_ball: Some efforts will evolve to become more familiar with possible code transformations.
