### ISSUE TITLE
Rename base name with move and copy

### ISSUE THREAD

**Issue by BioBox** [vifm/vifm#865]
The `move` and `copy` commands take a parameter to rename a single file, but typically when using them one would only want to rename the base of the filename so they don't have to type in the extension every time. Can you make a setting for that?

**Comment by xaizek** [comment]
Have you seen [<kbd>Ctrl+X</kbd> key](https://vifm.info/vimdoc.shtml#vifm-c_CTRL-X_c) in command-line mode?  You can paste extension of the current file with <kbd>Ctrl+X</kbd><kbd>e</kbd>.

A `:set` option doesn't look appropriate for this, maybe an option for the command, like `-skip` that `move` and `copy` already accept.

**Comment by BioBox** [comment]
Ah, I didn't think of that, thanks.
