### ISSUE TITLE
Upgrading from Debian's 0.12-1 to non-Debian 0.12.1: /etc/vifm/vifmrc is not loaded?

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#866]
I've been using the 0.12-1 package on Debian testing, but I want to try 0.12.1. When I start the AppImage file, it does not seem to be using `/etc/vifm/vifmrc`. Is it supposed to?

I cannot build from source, there are errors like:

```
configure:3382: $? = 0
configure:3371: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3382: $? = 1
configure:3371: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
```

```
configure:4144: gcc -E  conftest.c
conftest.c:14:10: fatal error: ac_nonexistent.h: No such file or directory
   14 | #include <ac_nonexistent.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
configure:4144: $? = 1
configure: failed program was:
```

```
config.status:1228: cd src       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
/tmp/GmOWhrZz:2049: *** target pattern contains no '%'.  Stop.
```

```
$ gcc --version
gcc (Debian 12.2.0-13) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
```

**Comment by xaizek** [comment]
> When I start the AppImage file, it does not seem to be using `/etc/vifm/vifmrc`. Is it supposed to?

Right, it looks only inside AppImage.  Should probably fix that, thanks.

> I cannot build from source, there are errors like:

The last one seems like a real error, the rest are compiler tests.  Is that `master` or 0.12.1?

**Comment by aleksejrs** [comment]
vifm-0.12.1.tar.bz2

**Comment by xaizek** [comment]
> Now, how do I make the built vifm use `/etc/vifm/vifmrc`?

Configure with `--sysconfdir=/etc`.

> 0.12.1, but it does not happen if I do it in `/tmp`. The mount it happens on has "nosuid,nodev,**noatime**", which `/tmp` does not have (I expected only a `noexec` issue, so I didn't notice that). I guess the error message could be improved.

`noatime` is not the issue.  I have it too.  Maybe something in the build path, like a space or another special character.  Depends on the line number 2049 of `sed -e '/# am--include-marker/d' src/Makefile`, I see
```make
install-nodist_vim_doc_DATA: $(nodist_vim_doc__DATA)
```
there, which might suggest a build path issue.

**Comment by aleksejrs** [comment]
> Configure with --sysconfdir=/etc.

Thanks.

> special character.

A colon "`:`".

**Comment by xaizek** [comment]
> A colon "`:`".

I managed to make the app build when colon is present, although tests won't.  Generally there is no way to escape things in Makefiles and build path should consist of `[-+.,@a-zA-Z0-9]` (and maybe a few other) characters which don't have a special meaning in Makefiles.
