### ISSUE TITLE
[Feature] Omit/cut the middle part of a long filename

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#868]
I've been using YouTube downloaders and now I have lots of files with very long names, with descriptions, subtitles and lyrics in different languages.

I've tried using `{fileext}`, but while there is important information at the beginning of the name, the end before the last extension often contains additional extensions, like language tag on a txt or subtitle file, which are hidden in long names and can become a confusing mess in short names (though it's partly because of #867):
```
x         .desc…
x         .desk…
x.en      .txt
x.info    .json
x         .jpg
x.nordlic….jpg
x.ru      .txt
x.ru.txt  .bak
x         .txt
x.txt     .bak
x         .webm
```

So I thought of the following, which is what mc does:

it does not touch the short names, and cuts the middle out of the long names to fit them:

![Screenshot_2023-01-30_19-02-00](https://user-images.githubusercontent.com/1025861/215528947-775103d6-10c0-4ec3-ad19-c8dfec0198c4.png)

If it's not resource-intensive (*maybe this and even some other features could be disabled optionally for directories with too many files?*), I would have something like this, a customizable amount of characters or percentage from the dot:

shorter_name.txt
very_very_extremely_overlong_file_name_that_does_not_fit.en.txt
⇓
shorter_name.txt
very_very_extremely_overlong_file_name_…not_fit.en.txt

**Comment by xaizek** [comment]
> If it's not resource-intensive [...]

No more than adding ellipsis on right/left and I don't think that's slow.  Moreover, strings are shortened only on displaying, so number of files that aren't visible doesn't matter.
