### ISSUE TITLE
[0.12.1] Merge the file conflict comparison dialog into the main conflict dialog and give it a better layout

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#869]
mc 4.8.28:

![Screenshot_2023-01-30_20-15-43](https://user-images.githubusercontent.com/1025861/215547436-bd50ece3-7c7b-4363-8607-d154152373b0.png)

KDE (Krusader 2.8.0, dolphin 22.12.0, Konqueror 22.12.1):
![Screenshot_2023-01-30_20-22-46](https://user-images.githubusercontent.com/1025861/215549038-dca2d12b-8a25-48de-ab16-d6e5d252ea61.png)

GNOME nautilus 43.2:
![Screenshot_2023-01-30_20-37-15](https://user-images.githubusercontent.com/1025861/215552113-ab32e06c-1939-4934-9b68-86ebdcc80ddb.png)

Thunar 4.18.2:
![Screenshot_2023-01-30_20-26-32](https://user-images.githubusercontent.com/1025861/215549884-401de0ab-ce9d-4d10-a6d7-7791d52e46da.png)

Vifm 0.12.1:

![Screenshot_2023-01-30_20-17-04](https://user-images.githubusercontent.com/1025861/215547702-cf155bc7-dff7-45f6-9f2a-86b315e7a6d7.png)

![Screenshot_2023-01-30_20-14-02](https://user-images.githubusercontent.com/1025861/215547045-ab04b8b6-3477-4682-a45d-8ea0a93319d8.png)

1. The destination/original/existing file is:
* top in Nautilus and Thunar
* right in any KDE file manager
* bottom in mc
2. All of those have labels near the corresponding data, for which there is plenty of space
    
    Someone switching from mc and possibly KDE would be confused.

4. Vifm requires two extra steps for each conflict, and you have to remember your choice.

**Comment by xaizek** [comment]
Definitely not a bug as there is no malfunction.

> 1. The destination/original/existing file is:
> 
> * top in Nautilus and Thunar
> * right in any KDE file manager
> * bottom in mc

In other words: all over the place.  What was your point, swap source and target?

**Comment by aleksejrs** [comment]
To use the current dialog, you have to press "c" and later "Enter", and know that the first line with the date and the first line with the size are the destination lines.

I can see why you grouped sizes and dates separately from the names: to put the data close to each other for comparison without a name between them. But there is a reason a table is not just a stack of lists: you can scan vertically or horizontally without the position occupying a chunk of your memory.

Although it might not occupy one when you always use the same file manager, it's not hard to make adapting quicker. In the current dialog, the only labels are in a different area than the important data; I had been using mc before I switched Vifm, and had to start it a few times since, so I expected the destination file to be "further" in the text (*i.e.*, down or to the right).

Also, *the file names are not aligned*. The name may be too long to fit the screen, which may make it worse, so maybe, if you still want to avoid putting a file name between the rows (in the main dialog):

```
Name conflict for "the_most_indispensible_file.txt" when moving
from /media/backups/
to   /home/my_useful_files_there_must_be_a_backup_somewhere/
What to do?

                Sizes       Modification dates
Target:  17 B (17)  Mon, 30 Jan 2023 20:13:34
Source:   2 B  (2)  Mon, 30 Jan 2023 20:13:42
```

Although I like "Destination"/"Dest" or "Existing file" better, for some reason. They are also easier to distinguish from "Source".

Maybe the file name could be nearer to the details, but I am too sleepy even to edit this post now.

**Comment by aleksejrs** [comment]
> `<`/`=`/`>` on the left are results of comparing properties of one file to another. Current dialog compares only for equality and prints different text on a match, which is part of the reason why it's organized top-down.

That's interesting. How about colors?

> I tried putting size/mtime horizontally, but they end up taking more space than paths and create a mess when screen is too narrow and lines start to wrap.

"Destination:  1024 T (1024000000000000)  Mon, 30 Jan 2023 20:13:34" takes 66 characters.

**Comment by xaizek** [comment]
> That's interesting. How about colors?

Dialogs don't have color and it's not easy to add.

> "Destination: 1024 T (1024000000000000) Mon, 30 Jan 2023 20:13:34" takes 66 characters.

If I split fullscreen terminal into four columns of equal size, each of them is 59 characters wide. And single pane mode is usable even for smaller terminal sizes.

**Comment by xaizek** [comment]
Final version:
![conflict](https://user-images.githubusercontent.com/459736/221421511-b35af8a3-5c9d-4049-9d87-e7789bb2ba49.png)
The info is split onto two lines if terminal is too narow.
