### ISSUE TITLE
Miller columns and files-only rpreview

### ISSUE THREAD

**Issue by aksr** [vifm/vifm#870]
Thank you for vifm — ***powerful tool***.

Very often, at least in `$HOME` directory, *usually* the *default* directory, we want to enable previews of files, but not of (already sorted, hierarchically structured) subdirectories, since this directory contains working files, downloaded files, all
kinds of misc files etc.
I think it would be useful to implement in addition to `all` and `dirs` value for `rpreview`, the value, for example, `files`.

If I'm not missing something, I think this ATM can't be emulated.

**Comment by xaizek** [comment]
Thanks for the suggestion. Will add `rpreview:files`.
