### ISSUE TITLE
sshfs mount: invalid argument `2'

### ISSUE THREAD

**Issue by iron-udjin** [vifm/vifm#871]
Hello,

OS: FreeBSD 13.1-STABLE
vifm-0.12

In `~/.vifm/vifmrc`:
`filextype *.ssh FUSE_MOUNT2|sshfs %PARAM %DESTINATION_DIR`

I'm trying to test sshfs mount. Created file: `iron@127.0.0.1.ssh` with content:
`iron@127.0.0.1:/`

When I hit Enter in `vifm` I'm getting:
```
FUSE MOUNT ERROR:
FUSE mounting selected file, please stand by..sshfs: invalid argument `2'
```
If I run from console: `sshfs iron@127.0.0.1:/ /mnt/tmp` - it mounts fine.

I couldn't find in documentation information regarding debug such problems. Is there any `--debug` flag ot something like that?

Thank you!

**Comment by iron-udjin** [comment]
Found log file: `~/.local/share/vifm/log`:
```
23.02.06 08:52 at int/fuse.c:237 (fuse_mount) in process #57733
               Load stage: 3
               FUSE mount command: `sshfs iron@127.0.0.1:/ /home/iron/.local/share/vifm/fuse//001_iron@127.0.0.1.ssh 2> /tmp//vifm.errors_5572857733_00`
23.02.06 08:52 at int/fuse.c:263 (fuse_mount) in process #57733
               FUSE mount command exit status: 1
```
File `/tmp//vifm.errors_5572857733_00` is empty.

If I run by hands:
```
mkdir /home/iron/.local/share/vifm/fuse//001_iron@127.0.0.1.ssh
sshfs iron@127.0.0.1:/ /home/iron/.local/share/vifm/fuse//001_iron@127.0.0.1.ssh
```
... it mounts fine.

**Comment by xaizek** [comment]
Hello.

> `2> /tmp//vifm.errors_5572857733_00`

```
$ sshfs test@127.0.0.1:/ tmp 2
sshfs: invalid argument `2'
```

So it seems like redirection isn't being recognized. What does `:set shell?` print?

**Comment by iron-udjin** [comment]
>What does :set shell? print?

`shell=/bin/tcsh`

I've changed to `set shell=/usr/local/bin/bash` and mount works fine.

It would be great to avoid `>2` and `>&` like constructions usage by default for any shell which doesn't support it because for exapmle _bash_ isn't installed by default on some systems. At least it has to be added to FAQ. At most - added shell type check before perform _STDERR_ redirrections.

Thank you!

**Comment by xaizek** [comment]
`2>` is not a bashism, it's [POSIX syntax](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html). I had no idea there are normal Unix shells that don't handle this syntax (even `fish` handles it and it's far from being normal).  `>&` is actually supported by `tcsh`.

FUSE code should just do redirection in C as the rest does. I guess `/bin/sh` is a POSIX shell and `2>` in scripts can be kept.

**Comment by iron-udjin** [comment]
>I had no idea there are normal Unix shells that don't handle this syntax (even fish handles it and it's far from being normal). >& is actually supported by tcsh

As far as I see, the problem only with `csh` and `tcsh` as they handle _STDOUT_ and _STDERR_ in other way then POSIX shell does:
`( command > stdout.log ) > & stderr.log`

If you run `cmd >& out.log` you'll capture only _STDERR_. [link]
(https://unix.stackexchange.com/questions/35715/stderr-redirection-not-working-in-csh)

Possibly the easiest way to avoid problems on systems which have `csh` or `tcsh` by default is to set variable `shell` to `/bin/sh`.

**Comment by xaizek** [comment]
> If you run `cmd >& out.log` you'll capture only _STDERR_.

Trying this out in `tcsh` captures both streams. The top answer in the link also states that:
> To redirect STDOUT and STDERR to a file:
>
>       pkg_add emacs-23.4,2.tbz > & stdxxx.log

**Comment by iron-udjin** [comment]
>Trying this out in tcsh captures both streams.

Ah, yes, you're right. It handles `>&` but not `2>` for our case.

**Comment by iron-udjin** [comment]
One more question regarding `sshfs`. Mount works fine when connection authenticates by keys. But when I'm trying to connect to host which asks for password, I'm getting:
`(iron@127.0.0.1) Password for iron@IRON:d by.. `
...at the bottom of the window. Nothing happens when I enter password and hit enter. All other input stop working. The only way to interrupt connection is to hit `Ctrl-c`.

As the minor and low priority enhantsment, it would be nice to have possibility to authenticate by password.

One more idea is to have command which allow connect `sshfs` dirrectly. For example, I press some key and at the bottom of the window I see: `Please enter host[:path] :` and after enter host + password it brings me into mounted folder. After I get back from that folder - `sshfs` unmounts automatically. Possibly for those operations `sftp` could be used instead of `sshfs`.

Thank you!

**Comment by xaizek** [comment]
> As the minor and low priority enhantsment, it would be nice to have possibility to authenticate by password.

Add `%FOREGROUND` to `:filetype` be able to use password prompt. It has a drawback that screen will flash even if keys are used for authentication.

> One more idea is to have command which allow connect `sshfs` dirrectly. For example, I press some key and at the bottom of the window I see: `Please enter host[:path] :` and after enter host + password it brings me into mounted folder. After I get back from that folder - `sshfs` unmounts automatically. Possibly for those operations `sftp` could be used instead of `sshfs`.

I wouldn't add a builtin command for `sshfs`, too specific. And `sftp` requires having VFS first.

I tested this custom command some years ago and it seems to work despite being quite ugly:
```vim
filetype .*.tssh FUSE_MOUNT2|sshfs %PARAM %DESTINATION_DIR %FOREGROUND
command! tssh
    \ : let $SSH_FILE = system('mktemp $PWD/.vifm-XXXX.tssh')
    \ | execute '!echo ''%a:'' > $SSH_FILE; ls $SSH_FILE %%U'
    \ | execute 'normal l'
    \ | execute '!rm $SSH_FILE %%i'
```
Usage example: `:tssh iron@127.0.0.1`.

**Comment by iron-udjin** [comment]
Please add somewhere to the wiki:

It's possible to use `vifm` for mount a huge list of [remotes](https://rclone.org/#providers) supported by [rclone](https://rclone.org/)

1. install [rclone](https://rclone.org/downloads/) _(preferably use package manager of your disto)_.
2. add _remote_ use `rclone config`
3. test connection by run in the console: `rclone mount <remote host>:<path> /path/to/mountpoint` and make sure _remote_ correctly mounted to defined `mountpoint`.
4. add to `vifmrc`:
`filextype *.rclone FUSE_MOUNT2|rclone %PARAM %DESTINATION_DIR`
5. create a file with _remote_ connection settings: `:touch <user@remote>.rclone` and add into it:
`mount <remote host>:<path> --daemon`


Sample configuration of `SFTP` connection to localhost:

`~/.config/rclone/rclone.conf` generated by `rclone config`:
```
[testuser_at_localhost]
type = sftp
host = localhost
user = testuser
pass = <password hash>
use_insecure_cipher = false
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

```
file: `testuser@localhost.rclone`:
`mount testuser_at_localhost:/ --daemon`

**Comment by iron-udjin** [comment]
>Add %FOREGROUND
>command! tssh

Both works, thank you!

**Comment by xaizek** [comment]
Wiki page about `rclone`: https://wiki.vifm.info/index.php/How_to_integrate_rclone_as_a_FUSE_mounter
