### ISSUE TITLE
[feature request] new filesystem change event types for lua plugins

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#872]
As discussed in [this issue](https://github.com/vifm/vifm.vim/issues/85), I feel like a feature request is needed here so that we can add more comments.

the usecase is that lua plugins may be interested in some filesystem changes and would take some actions.

currently, the needed event types are (speak in shell):
* after `mv foo bar`
* after `rm foo`

the lua plugins who subscribed to specific event may want to know more details about the `foo` and `bar`, the code i can imagine is like that:

<details>

```lua
-- the keywords were used for describing only, including: mv, rm, foo, bar, emit

vifm.events.listen({
  event = "mv",
  ---@param foo VifmEntry
  ---@param bar VifmEntry
  handler = function(foo, bar)
    if foo.isdir then
      -- inform nvim that all the files under `foo` were renamed to directory `bar`
    else
      -- inform nvim that the `foo` file were renamed to `bar`
    end
  end,
})

vifm.events.listen({
  event = "rm",
  ---@param foo VifmEntry
  handler = function(foo)
    if foo.isdir then
      -- inform nvim that all the files under `foo` were gone
    else
      -- inform nvim that the `foo` file were gone
    end
  end,
})

local foo_entry = { name = "foo", isdir = true }
vifm.events.emit("rm", foo_entry)
```

</details>

**Comment by xaizek** [comment]
I didn't think knowing whether it's a file or directory operation is important, but it is, thanks.  I was thinking of a single event that accepts operation type and paths.  No file list entries exist for destination paths internally during the operation.
<details>

```lua
vifm.events.listen({
  event = "app.fileop",
  ---@param info table
  ---info.op: "remove", "move" (although I like that shell commands are shorter)
  ---info.path: source/only file path (string)
  ---info.target: destination file path (string)
  ---info.isdir: (boolean)
  handler = function(info)
    if info.op == 'move' then
      if info.isdir then
        -- inform nvim that all the files under `foo` were renamed to directory `bar`
      else
        -- inform nvim that the `foo` file were renamed to `bar`
      end
    elseif info.op == 'remove' then
      if foo.isdir then
        -- inform nvim that all the files under `foo` were gone
      else
        -- inform nvim that the `foo` file were gone
      end
    end
  end,
})
```
</details>

**Comment by haolian9** [comment]
Nice improvement!
I forgot to mention `mv a b c d` and `rm a b c`, it'd be a common use: select multiple files/directories in the left pane then `:move` them to the right pane. since currently the info.path is not an array, Do you think generating a series of `info{event='app.fileop', op='move', path=item}`events for this one operation is ideal? On the receiving end, there is no big difference i think.

Able to trigger an event through a lua api would be useful. I currently have a mapping with rhs=`:!my_renaming.py %c:p 2>&1<cr>` and I'd like to turn it into a lua plugin.

**Comment by haolian9** [comment]
Nice improvement!
I forgot to mention `mv a b c d` and `rm a b c`, it'd be a common use: select multiple files/directories in the left pane then `:move` them to the right pane. since currently the info.path is not an array, Do you think generating a series of `info{event='app.fileop', op='move', path=item}`events for this one operation is ideal? On the receiving end, there is no big difference i think.

Able to trigger an event through a lua api would be useful. I currently have a mapping with rhs=`:!my_renaming.py %c:p 2>&1<cr>` and I'd like to turn it into a lua plugin.

**Comment by xaizek** [comment]
> I forgot to mention `mv a b c d` and `rm a b c`, it'd be a common use: select multiple files/directories in the left pane then `:move` them to the right pane. since currently the info.path is not an array, Do you think generating a series of `info{event='app.fileop', op='move', path=item}`events for this one operation is ideal? On the receiving end, there is no big difference i think.

Processing of a cumulative event would basically loop through that array, so it doesn't seem to be very important and also makes handlers more complex. If knowing that an operation is a part of a larger one will be necessary, some kind of an id can be added to identify related operations or a separate event for more high-level operations.

> Able to trigger an event through a lua api would be useful. I currently have a mapping with rhs=`:!my_renaming.py %c:p 2>&1<cr>` and I'd like to turn it into a lua plugin.

I think that a proper way is to expose Vifm's implementation of file operations to Lua, then that implementation could trigger the appropriate event on a successful operation.  Exposing file operations is necessary primarily to make plugins work on both Linux/Windows without changes and shell invocations.

**Comment by haolian9** [comment]
Hi, I had tried to listen on this new event in a lua plugin, but did not get any.
I think there might be a typo in [this line](https://github.com/vifm/vifm/blob/bbb7b0df2752c91ed2023c4fc2e415cf39370172/src/ops.c#L301), which could be `if(ops != NULL && ops->bg)` or `if(ops == NULL || ops->bg)` to match the following comment `Not reporting events from background jobs.`

**Comment by xaizek** [comment]
Thanks, I forgot to invert conditional after moving the code around. It should be `if(ops != NULL && ops->bg)`.

**Comment by haolian9** [comment]
Hi me again :).
I am trying to process the new fsop event, but found it's difficult to determine what a fsop event with op=move stands for. currently it is mixed by `:move` and `:delete` with &trash=1.
In practice, The latter equals to fsop.op=remove, but I failed to find a reliable way to tell if an operation is for "moving files into trash bin" using &trash and &trashdir and `.target`. Could you give me some advices?

**Comment by xaizek** [comment]
Why would that matter? From FS monitoring point of view, whether file was moved to a trash or renamed in place should look the same. Or you want to close a Vim buffer on file trashing instead of renaming it?

**Comment by haolian9** [comment]
> you want to close a Vim buffer on file trashing instead of renaming it

yeah, exactly. IMO there is no point to rename the vim buffer which has been trashed, I'd treat it as deleted.

**Comment by xaizek** [comment]
I can add flags like `fromtrash`/`totrash`, but mind that you can move a file either via <kbd>yy</kbd>...<kbd>P</kbd> or <kbd>dd</kbd>...<kbd>p</kbd> pair, undoing a deletion falls into the same category.

**Comment by haolian9** [comment]
Thanks, I'll note these cases. I too failed to find a better way to do it rather than passing more info to the event handler.

**Comment by xaizek** [comment]
Pushed flags and the fix to `master`.
