### ISSUE TITLE
`:help` does not work on fresh systems: 

### ISSUE THREAD

**Issue by trofi** [vifm/vifm#873]
Bisect says the help stopped working on commit 45bc5ad1d11509931c16ba6e11200c6b2249b68d `Enable 'vimhelp' in sample vifmrc file by default` which only flipped the default.

My reproducer is:

```
$ rm -rfv ~/.config/vifm/ ~/.vifm
$ vifm

<in vifm>:help
Error detected while processing command line:
E149: Sorry, no help for vifm-app.txt
```

I think it happens because the file is installed to `$prefix/share/vifm/vim-doc/doc/vifm-app.txt`, but `vifm` expects it to be in `$prefix/share/vifm/vim-doc/vifm-app.txt` (missing `/doc` nest).

**Comment by trofi** [comment]
Compared to the working systems my `$prefix/share/vifm/vim-doc/doc/tags` file is 0 bytes.

My build environment had neither `perl` nor `vim`. Failed at `src/Makefile.am`:

```
$(top_srcdir)/data/vim/doc/plugin/tags: \
                               $(top_srcdir)/data/vim/doc/plugin/vifm-plugin.txt
        $(AM_V_GEN)mkdir -p ../data/vim/doc/plugin/; \
        if [ -n "$(PERL)" ]; then \
                $(srcdir)/helpztags "$(top_srcdir)/data/vim/doc/plugin"; \
        elif [ -n "$(VIM)" ]; then \
                vim -e -s -c 'helptags $(top_srcdir)/data/vim/doc/plugin|q'; \
        else \
                touch $@; \
        fi
```

Adding `perl` helped building working `:help`.

Worth adding a warning when tags could not be built? Or maybe even turn it into a build failure?

**Comment by xaizek** [comment]
> Worth adding a warning when tags could not be built? Or maybe even turn it into a build failure?

I think the idea was that failure to generate `tags` file is not a big deal, but given that either `perl` or `vim` seems to be often present a configuration failure is probably more appropriate. Definitely better than to spend time figuring out why data of a successful built isn't complete. Thank you!
