### ISSUE TITLE
Powerline tab bar

### ISSUE THREAD

**Issue by SylEleuth** [vifm/vifm#875]
I was hard working on powerline tabline today and this is what I've achieved:

![powerline_vifm](https://user-images.githubusercontent.com/33354262/218336003-97881ded-3f91-4937-8dd1-56d6e397ae69.png)
```
highlight User1  ctermbg=7    ctermfg=0    cterm=none
highlight User2  ctermbg=0    ctermfg=7    cterm=none
highlight User3  ctermbg=237  ctermfg=7    cterm=none
highlight User4  ctermbg=0    ctermfg=237  cterm=bold
highlight User5  ctermbg=237  ctermfg=0    cterm=bold

let $PREFIX="%5*%[%1*%C%] %3*%[%1*%C%]%N: "
let $SUFFIX="%4*%[%2*%C%]"
let $TAB="%3*%[%1*%C%]%n "

execute 'set' 'tablabel="' . $PREFIX . $TAB . $SUFFIX . '"'
```

It look nice but not great. There are a few problems:
1. As You can see first tab has an indentation on the left side. Is there a way to get number of a first tab and give it a different prefix?
2. There is a double powerline symbol and the result of it is a space between them.
My goal would be something like this:
![kitty_tabbar](https://user-images.githubusercontent.com/33354262/218336583-42681abc-a4b2-4574-9a60-31b9c57f54f1.png)
It's Kitty terminal tab bar. Active tab suffix has an angled powerline symbol and inactive ones have just an arrow between them. Is it possible to get an information which tabs are adjacent to the active tab and use it somehow?
3. Tab bar utilize 5 different user highlight groups. That's a lot because I also use them to my powerline statusline. And it's utilize 9 different groups. Some overlap but even then I am missing one more group. Which is a bummer because I can't sacrifice just one to squeeze it more and had to simplify statusline and it doesn't look great.

If those things are difficult to implement is it possible to at least get more user highlight groups? It would make things much easier. 

Thank you.

**Comment by xaizek** [comment]
> 1\. As You can see first tab has an indentation on the left side. Is there a way to get number of a first tab and give it a different prefix?

It needs an introduction of a new macro (or rather two while at it: another one for the last tab).

> 2\. Is it possible to get an information which tabs are adjacent to the active tab and use it somehow?

Not at the moment. Need a new macro that tab is inactive? It seems like knowing that and dropping `` from `$PREFIX` should be enough to get the right look.

> 3\. Some overlap but even then I am missing one more group.

Vim has 9, which seemed enough.  I don't see an issue with adding 10 more, syntax allows it.

> If those things are difficult to implement is it possible to at least get more user highlight groups? It would make things much easier.

All of the above changes are quite trivial.

I was also thinking about allowing generating label/prefix/suffix format strings in Lua (and/or adding `'tabline'` that can use Lua as well). It might be easier to handle complex conditionals then.

**Comment by SylEleuth** [comment]
Creating tabline and statusline in lua would be awesome. 
One more question. Right now I can distinguish between active and inactive tabs and change they colors. Can I change content as well? Like text or a symbol?

**Comment by xaizek** [comment]
> Creating tabline and statusline in lua would be awesome.

`'statusbar'` can be formatted in Lua since v0.12.
<details>
<summary>Example (assumes the plugin is called "statusbar")</summary>

```lua
--[[

Example of displaying target of symbolic links on statusline.

Usage example for `vifmrc`:

    set statusline=#statusbar#fmt

--]]

local function fmt(info)
    local view = info.view
    local entry = view:entry(view.currententry)
    local format = " %t%=%A %10u:%-7g %15s %20d "
    if entry.type == 'link' then
        local target = entry.gettarget()
        target = string.gsub(target, "%%", "%%%%")
        format = " %t -> " .. target .. " %= %A %10u:%-7g %15s %20d "
    end
    return { format = format }
end

local added = vifm.addhandler {
    name = "fmt",
    handler = fmt,
}
if not added then
    vifm.sb.error("Failed to register #%s#fmt", vifm.plugin.name)
end

return {}
```
</details>

> One more question. Right now I can distinguish between active and inactive tabs and change they colors. Can I change content as well? Like text or a symbol?

`%[`/`%]` can contain anything, but if any enclosed macro expands, the whole optional block becomes visible.

**Comment by SylEleuth** [comment]
> `'statusbar'` can be formatted in Lua since v0.12.

Thank You. Somehow I missed it.

> %[/%] can contain anything, but if any enclosed macro expands, the whole optional block becomes visible.

That's the issue. In the example "%[test1%C%]test2", "test2" will be displayed when tab is inactive, and "test1test2" when active. In case of colors I assume %C overwrites inactive one, but "test2" is outside of that group. Is it possible to do something like that with text?

I took a look at ```colors.h``` and added new highlight groups. Also found HI_GROUPS in ```color_scheme.c``` and added there as well. It didn't work. Am I missing something.

**Comment by xaizek** [comment]
> That's the issue. In the example "%[test1%C%]test2", "test2" will be displayed when tab is inactive, and "test1test2" when active. In case of colors I assume %C overwrites inactive one, but "test2" is outside of that group. Is it possible to do something like that with text?

Not sure I understand. `%C` has no effect on colors by itself and `%*` only changes attributes, but not text. If you want a color to depend on a condition, do something like `%1*%[%*2test1%C%]test2` in which case `User1` will be in effect for inactive tabs, but it will be overwritten by `User2` for an active tab.

**Comment by xaizek** [comment]
I think I understand what you were asking now. I couldn't get powerline look with those conditionals, hence I didn't add new macros, there are 11 more user groups and a way to format tabline in Lua ([example](https://github.com/vifm/vifm/blob/52d5ecc29905ca6f6c09d904d95335c94345f5e0/data/plugins/tabline/init.lua#L1)):

https://user-images.githubusercontent.com/459736/222971655-d84731f1-e87a-4458-b5a0-b35ea7369213.mp4
