### ISSUE TITLE
vifm creates 'cat' file in each folder

### ISSUE THREAD

**Issue by iron-udjin** [vifm/vifm#876]
Hello,

vifm creates `cat` file with `0` inside in each folder where it opens file for edit (by hitting `Enter` or `Left Arrow` keys).

For example:
```
$ rm -rf ~/.vifm (to make sure there are no settings remain)
$ mkdir test
$ cd test
$ echo test > test.txt
$ ls -la
total 1
drwxr-xr-x   2 root  wheel   3 Feb 12 22:39 .
drwxr-x---  10 root  wheel  30 Feb 12 22:24 ..
-rw-r--r--   1 root  wheel   5 Feb 12 22:22 test.txt
$ vifm
...(edit file)...
$ ls -la
total 1
drwxr-xr-x   2 root  wheel   4 Feb 12 22:40 .
drwxr-x---  10 root  wheel  30 Feb 12 22:40 ..
-rw-r--r--   1 root  wheel   2 Feb 12 22:40 cat
-rw-r--r--   1 root  wheel   7 Feb 12 22:40 test.txt
$ cat cat
0
$
```
OS: FreeBSD 13-STABLE
vifm: 0.12

**Comment by iron-udjin** [comment]
Found where is the problem is. It seems some incompatibilities with `tcsh`, don't know where exactly yet. Changing to `sh` or `bash` solved problem.

**Comment by xaizek** [comment]
Hi.

I don't think that `cat` is used anywhere in the sources, so it might come from configuration.
