### ISSUE TITLE
[feature request] do not trash files across file systems

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#878]
Say i'm having this fstab, and using `&trashdir=%r/.vifm-Trash-%u,$XDG_DATA_HOME/vifm/Trash,%r/.vifm-Trash` for vifm.

```
# fstab, but sometimes I mount disks manually
/dev/sda1 /mnt/movies
/dev/sdb1 /home
```

a) When i trash `*/home*/john/file`, i'd like the &trashdir be `*/home/john*/.vifm-trash`;
b) While for `*/mnt/movies*/4k/wick.mkv`, it'd be `*/mnt/movies*/.vifm-trash`;

For b), i usually run vifm as a non-privileged user, when having insufficient
permissions to create `%r/.vifm-Trash-%u`, vifm will silently ignore it and
use the latter item, `$XDG_DATA_HOME/vifm/Trash`, and copy the file cross
filesystems/disks. that would be a time-consuming operation which i'd like to avoid.

Then I had tried to set `&trashdir=/%r/.vifm-trash` so that vifm can alert me
about the permission issue instead of silently falling through to
`$XDG_DATA_HOME/vifm/Trash`. It worked fine until I wanted to trash
a file in my home directory *a), the resolved trashdir was `/home/.vifm-trash`,
I definitely dont want to trash my personal files in there, and mix them with other users's.

I could not figure out a way to suffice a) and b) in the same time, so I think
maybe vifm can accept a callback for &trashdir, thus user can take over control of resolving &trashdir. Do you think that's a valid feature and worth to be added?

**Comment by haolian9** [comment]
One days later, another approach came into my mind: a pre-trash (or fsop{.op=pre-move, .totrash = true}) event. that's a non-invasive way requiring no change to existing functionality of &trashdir.

There are solutions outside vifm of course, I can simply wrap vifm in a shell script which checks and prepares trash dirs of all the mount points then `exec` vifm.

**Comment by xaizek** [comment]
> Two days later, another approach came into my mind: a pre-trash (or fsop{.op=pre-move, .totrash = true}) event. that's a non-invasive way requiring no change to existing functionality of &trashdir.

How would that work? A event handler would create trash directory via something like `sudo`? Not sure this can work if traversing list in `'trashdir'` isn't disabled, because otherwise you won't get to handle a path that doesn't exist. Also mind that events are not synchronous and can't really affect an operation.

Lua handler would also create directory or just fail?

Without Lua `b)` case can only be handled by asking for confirmation or creating trash in the writable parent directory that's closest to the mount point.

**Comment by haolian9** [comment]
>  events are not synchronous

Ah, thanks for the info. So handling this so-called `pre-trash` lua event will not work.

That's the code I thought to do the job: 
```
-- default &trashdir
assert(vifm.opts.global.trashdir == "%r/.vifm-trash")

vifm.events.listen({
    event = "app.fsop",
    handler = function(info)
        if not (info.op = "pre-move" and info.totrash) then return end

        local trashdir
        if startswith(info.path, "/home") then
            trashdir = resolve_homedir(info.path) .. "/.vifm-trash"
        else
            trashdir = "%r/.vifm-trash" 
        end

        vifm.opts.global.trashdir = trashdir
    end
})
```

**Comment by haolian9** [comment]
> Lua handler would also create directory or just fail?

If you were saying the lua handler for &trashdir, I think it can just return **only one** trashdir and let vifm deal with directory creating and permission checking agains the one.

for the wrapper script way, I'd really like to avoid. Because each time I start vifm, it will awake all mounted disks which could be in spin-down state.

**Comment by xaizek** [comment]
> If you were saying the lua handler for &trashdir, I think it can just return **only one** trashdir and let vifm deal with directory creating and permission checking agains the one.

This would mess up `:trashes` and `:lstrash` commands as well as updating registers' contents on moving files.  Moreover setting `'trashdir'` to bad value doesn't work.

Would it help if you could use `&trashdir=%r/.vifm-trash,$HOME/.vifm-trash` and get the following behaviour:
 * removing `/mnt/movies/4k/wick.mkv` when there is no `/mnt/movies/.vifm-trash` asks for confirmation to move across file-systems
 * removing `/home/john/file` silently uses `$HOME/.vifm-trash`, because that's on the same mount

?

`'confirm'` option could be extended to make the confirmation optional.

**Comment by haolian9** [comment]
> use &trashdir=%r/.vifm-trash,$HOME/.vifm-trash and get the following behaviour

that would be great!

**Comment by haolian9** [comment]
During trying to implement the new value of &confirm, I am now thinking: If we can treat "do or do not delete files acorss filesystem" as a new and special rule, why not just add a new option, say `trashnoacorssfilesystem`?

By adding a new option we get some benefits than new possible value of &confirm:
* no need to ask confirmation
* no new UI (though there could be reusable components for this purpose)
* less code: we just need to add some logic in `trash.c :: traverse_specs()`

**Comment by xaizek** [comment]
Confirmation can be enabled by default to make such moves more explicit, but that option can't. One can also decide differently depending on file size.

`traverse_specs` is for generic enumeration and changing its behaviour can break handling of files already in trashes.
I was thinking of adding the check to `fops_misc.c:delete_file()` after `trash_gen_path()`.

> no new UI

A call to `prompt_msg()` is all that's needed. In general, feel free to ask how to do something in the code base, this will save your time.

**Comment by haolian9** [comment]
Oh I see. And thanks for your kindness.

**Comment by haolian9** [comment]
sorry for being no response so long! i have not looked into the code, which mostly becauses `set notrash` made me happy in these days, also there is no others has such demand, so I think it can be closed as unplanned.
