### ISSUE TITLE
Typo in man-pages

### ISSUE THREAD

**Issue by phijor** [vifm/vifm#88]
I just read the docs and came across this typo:
On [line 620 in vifm.1](https://github.com/vifm/vifm/blob/master/data/vifm.1#L620), `double quoute` is mistakenly spelt as `double quite`.

PS: This is my first time reporting an issue. I hope I'm doing things the right way and not cluttering anything here with what seems like something trivial.

**Comment by xaizek** [comment]
> I hope I'm doing things the right way and not cluttering anything here with what seems like something trivial.

It might be trivial, but nonetheless useful. Thanks!
