### ISSUE TITLE
Ideas on file highlighting for the Default-256 color scheme 

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#880]
* Add webp to the image type list.

* Add these to the text type list:
```
*.description,*.list,*.log,*.log.old,syslog,syslog.1,
*.log.1,*.log.2,*.log.3,*.log.4,*.log.5,*.log.6,*.log.7,*.log.8
```

As my inspiration for the below, I had something like the following, where the text files' color (chosen without much attention) seems to conflict with that of the files with `+x` (so I decided to check if there are defaults):

```
highlight {*.mp4,*.webm,*.mkv,*.flv,*.wmv,*.gif,*.avi,*.mpeg,*.mpg,*.ogv,*.rm,*.m4v,*.mov,*.edl-mp2,*.unknown_video} ctermfg=163
highlight {*.ogg,*.flac,*.mp3,*.wav,*.aac,*.m4a} ctermfg=magenta
highlight {*.jpg,*.jpeg,*.png,*.bgra,*.xcf,*.ora,*.nef,*.cr2,*.svg,*.blender,*.webp,*.psd} ctermfg=168
highlight {*.zip,*.tar,*.gz,*.bz2,*.xz,*.rar,*.7z,*.7ze,*.dar} ctermfg=cyan
highlight {*.db,*.db2,*.sqlite,*.anki2} ctermfg=darkorange
highlight {*.txt,*.description,*.md,*.list,*.log,*.log.old,syslog,syslog.1} ctermfg=lightgreen
highlight {*.htm,*.html,*.mhtml,*.desktop,*.xml,*.pdf,*.epub,*.json,*.conf,*.fb2,*.djvu,*.vtt,*.srt,*.cbr,*.cbz,*.cbt} ctermfg=green
```

The idea is to separate really text-based types like `*.txt,*.md` (meant to be *read* in a text editor) and those that are either hard to view without a viewer, like `.html`, or are configuration and markup files not meant to be *viewed* with a text editor, like
`*.htm,*.html,*.mhtml,*.desktop,*.xml,*.pdf,*.epub,*.json,*.conf,*.fb2,*.djvu,*.cbr,*.cbz,*.cbt`

I had `*.vtt,*.srt,*.ass` in both. I guess they fit the markup group better.

I also had audio-only types separate.

**Comment by xaizek** [comment]
The biggest difficulty with adding more colors is finding colors which look distinct from the rest. I'm yet to find a tool to test for that easily.

**Comment by aleksejrs** [comment]
There are programs to calculate distance between two colors, although I don't know how many of them take color theory into account, rather than just using RGB, like https://plnkr.co/edit/ERaf37?p=preview&preview and probably http://www.perbang.dk/

When I switched from the above to Default-256, I didn't like the x049_MediumSpringGreen on black (it felt too garish), although I seem to have gotten used to it.
Also, red "evokes avoidance motivation and undermines intellectual performance", according to a study (at least in its context) https://journals.sagepub.com/doi/10.1111/j.1467-8721.2007.00514.x

**Comment by xaizek** [comment]
> There are programs to calculate distance between two colors, although I don't know how many of them take color theory into account, rather than just using RGB, like https://plnkr.co/edit/ERaf37?p=preview&preview and _maybe_ http://www.perbang.dk/

This doesn't juxtapose every color in the palette to every other color, which is what needed in this case. I've seen other tools like that, [some](https://colorbrewer2.org/) are closer, but work only for a very small number of colors or don't let select them. Might have to do it myself, it shouldn't be hard.

> Also, red "evokes avoidance motivation and undermines intellectual performance", according to a study (at least in its context) https://journals.sagepub.com/doi/10.1111/j.1467-8721.2007.00514.x

Even if that study was well done and replicated independently, it used red as a background color. Banning any color when there is not enough of them doesn't sound like a good idea anyway.

**Comment by aleksejrs** [comment]
I wouldn't ban a color completely, but use it for something less frequent than text files. I think twenty years ago red was used for .bak files on my computer. Default-256 uses `red` for broken links. Text files are `x217_LightPink1` though.

Orange seems to be completely unused. I think it is as good as green as fg on black.

**Comment by xaizek** [comment]
| before | after |
|--|--|
|![before]|![after]|

[before]: https://user-images.githubusercontent.com/459736/221999395-a4aaeca6-c2a1-46a2-9fe5-d1de710d1649.png
[after]: https://user-images.githubusercontent.com/459736/221999405-8888b716-24b7-4be9-a739-0256bac938c5.png

The difference might look barely noticeable, but it's there. Similar files still have similar color. And some of my colors in "before" are changed in terminal configuration, colors in "after" version should be the same everywhere.

> I wouldn't ban a color completely, but use it for something less frequent than text files. I think twenty years ago red was used for .bak files on my computer. Default-256 uses `red` for broken links. Text files are `x217_LightPink1` though.

Now pdf-files and alike are "LightCoral", which is darker pink. By the way, I don't count json and xml there, there are no presupposed way of viewing them apart from textual.

> Orange seems to be completely unused. I think it is as good as green as fg on black.

There is only one or two useable orange colors in the palette, the rest are too dark and are good only as a background.

**Comment by aleksejrs** [comment]
> The difference might look barely noticeable in this sampler, but it's there.

Pretty noticeable to me at 45% brightness and 42% contrast (an old IPS display). Thanks.

>  By the way, I don't count json and xml there, there are no presupposed way of viewing them apart from textual.

The json files saved by yt-dlp and another program have no line breaks and need json_pp to view easily.

> There is only one or two useable orange colors in the palette, the rest are too dark and are good only as a background.

I had tried to add a remark on it being less diverse, but wasn't sure.

**Comment by xaizek** [comment]
> The json files saved by yt-dlp and another program have no line breaks and need json_pp to view easily.

Yes, but you can also reformat files inside Vim in case their contents isn't pretty-printed.

> Is there a chance to support names like "x186_LightGoldenrod2" instead of numbers?

They are supported but without `x*_` prefix, see [`:help vifm-:highlight`](https://vifm.info/vimdoc.shtml#vifm-%3Ahighlight) (scroll down a screen or two).

**Comment by aleksejrs** [comment]
> They are supported but without x*_ prefix, see :help vifm-:highlight (scroll down a screen or two).

It would be helpful to use them in the theme instead of numbers, so people can find an entry by color.

**Comment by xaizek** [comment]
> It would be helpful to use them in the theme instead of numbers, so people can find an entry by color.

Most of the names are so obscure, I think they can only confuse. At least at the moment you can see color names in the output of `:highlight`, original form used in color scheme might be preserved in the future.

**Comment by aleksejrs** [comment]
> Most of the names are so obscure, I think they can only confuse.

The only names that would have been meaningless or confusing to me before I learned them intentionally (but after I learned the 16 colors, including magenta and cyan) were:
* Chartreuse
* Turquoise (I had no idea what color the Russian name meant)
* Aquamarine (I thought it was what turquoise was)
* Salmon (цвет красной рыбы)
* Orchid
* Thistle
* Tan
* Khaki
* Plum
* Honeydew
* LightCoral
* NavajoWhite (it is really not white)

I'd think most people know colors better than I did, judging by how much they were mentioned in books, even if some people think there is only one word for blue in English.

However, if you think it's easier to change colors with numbers, the x*_ prefix would have helped more than I expected: in https://vim.fandom.com/wiki/Xterm256_color_names_for_console_Vim, many colors have duplicate names!

```
hi  x019_Blue3              ctermfg=19   guifg=#0000af  "rgb=0,0,175
hi  x020_Blue3              ctermfg=20   guifg=#0000d7  "rgb=0,0,215
hi  x031_DeepSkyBlue3       ctermfg=31   guifg=#0087af  "rgb=0,135,175
hi  x032_DeepSkyBlue3       ctermfg=32   guifg=#0087d7  "rgb=0,135,215
hi  x054_Purple4            ctermfg=54   guifg=#5f0087  "rgb=95,0,135
hi  x055_Purple4            ctermfg=55   guifg=#5f00af  "rgb=95,0,175
```

> At least at the moment you can see color names in the output of :highlight,

That's helpful, although there is are no colors. And unfortunately, `color_demo.vim` does not generate names, nor foreground samples, and that webpage does not show examples of all the colors. So, I guess it's not really a solution…

**Comment by xaizek** [comment]
> many colors have duplicate names!

Also trailing numbers in names don't make any sense too me, which is why I don't think those names are generally useful.  The only reliable way to pick colors is to look at the palette itself, like [here](https://upload.wikimedia.org/wikipedia/commons/9/95/Xterm_color_chart.png) or [here](https://www.tweaking4all.com/software/linux-software/xterm-color-cheat-sheet/) (the two are basically the same), and then try using them.
