### ISSUE TITLE
Using exa for symbolically linked directories

### ISSUE THREAD

**Issue by GNOMES** [vifm/vifm#883]
I currently have the following vifmrc entry:

`fileviewer */,.*/ exa -T  --color=always %c`

This allows me to have a colored file tree instead of the standard white output for all directories with or without a leading dot.

The problem is this is not working for symlinked directories.

Manually running `exa -T --color=always "dir name"` in my terminal I am getting "dir name" -> path to real dir", which is identical to how it looks in Vifm.

If I manually run `exa -T --color=always "dir name"/` in my terminal I get the tree of files inside that symbolic directory. 

Example 1 `exa -T --color=always .config` shows the path the symlink is pointing towards
Example 2 `exa -T --color=always .config/` shows the tree inside the symlinked directory

What syntax can I use to run the command like this in Vifm?

I tried the following to no luck:
`fileviewer */,.*/ exa -T  $@ --color=always %c`
`fileviewer */,.*/ exa -T  $1 --color=always %c`
`fileviewer */,.*/ exa -T  */ --color=always %c`
`fileviewer */,.*/ exa -T  - --color=always %c`

**Comment by xaizek** [comment]
[`%c` macro](https://vifm.info/vimdoc.shtml#vifm-%25c) is what expands to the path, so add the slash after it:
```vim
fileviewer */,.*/ exa -T  --color=always %c/
```
