### ISSUE TITLE
:tree mode doesn't allow collapse / ommission of subtrees

### ISSUE THREAD

**Issue by tecfu** [vifm/vifm#889]
### Issue:

As a user in `:tree` mode 
I want to be able to 
- close subtrees after the initial render 
- or omit them from being populated in the initial render

So that I can hide files that I am not interested in viewing. 

### Background:

In NodeJS/Typescript we have a node_modules directory in the root level of a project folder.

If I run the `:tree` command at the root level, this expands all the folders in *all* the directories within the current directory. In my case, I have to skip past the expanded node_modules. This is clunky and should be avoidable.

### Proposed:

- When the cursor is on the line of an expanded folder, `zc` should collapse the node.
- When the cursor is on the line of a folder, `zo` should invoke `:tree` on the directory, expanding it into a tree view.

### Code To Reproduce:

- Run the tree command in any directory where you want to see only *some* of the subdirectories expanded.
```
:tree
```

**Comment by nullptr-deref** [comment]
You're able to specify tree depth. Have you tried using `:tree 1`?

**Comment by tecfu** [comment]
Hi @nullptr-deref. 

```
tree 1
```

Returns the following error:

> Invalid argument: 1

---

Even if that did work, what would it do? Set the depth of all the subdirectories to 1 level? 
If so, please note that's not the solution I'm looking for. The issue I'm reporting is that I want to collapse *some* subdirectories but not others. Please let me know if I'm misunderstanding. Thank you!

**Comment by tecfu** [comment]
@xaizek Thanks so much!
