### ISSUE TITLE
More extensions for vifmrc

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#891]
I don't know how many of these are still needed with `<audio/*>` etc:

* audio: .mpga, .aac
* video: .unknown_video (this has come from YouTube downloaders sometimes)
* .svg, .svgz: inkscape, inkview, others?
* .mid, .kar: timidity
* graphics: .tif, .tiff, .avif, .webp (not all viewers support these)
* .cr2 (RAW photos; viewers, rawtherapee, darktable)
* .xcf (gimp)
* .kra (krita)
* .blend (blender)

**Comment by xaizek** [comment]
> graphics: .tif, .tiff, .avif, .webp (not all viewers support these)

And I don't know which do support them. Better send PRs for things like that which require specific knowledge, I don't have sample files nor apps that can handle them for half the files you've listed.
