### ISSUE TITLE
add "chgrp"

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#892]

**Comment by xaizek** [comment]
From [`:help vifm-:chown`](https://vifm.info/vimdoc.shtml#vifm-%3Achown):
```
:[range]chown [user][:][group]
    change owner and/or group of files.  Operates on directories recursively.
```

There is also <kbd>cg</kbd> normal mode mapping.

**Comment by aleksejrs** [comment]
> :[range]chown [user][:][group]

I am used to chgrp.

> There is also cg normal mode mapping.

Thanks, this is better.
