### ISSUE TITLE
Homebrew: couldn't link without sudo 

### ISSUE THREAD

**Issue by howarddo2208** [vifm/vifm#900]
I tried to install vifm using Homebrew formulae: `brew install vifm`. Got an error in link phase:
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/icons/hicolor/128x128/apps/vifm.png
/usr/local/share/icons/hicolor/128x128/apps is not writable.

You can try again using:
  brew link vifm
```

I know that I can resolve using chown, but as Homebrew FAQ stated
> Homebrew is designed to work without using sudo. You can decide to use it but we strongly recommend not to do so.

I think it should be fixed to install without requiring the permission.

**Comment by xaizek** [comment]
You need to create an issue on the formulae as this is related to a third-party package. I think it's here: https://github.com/Homebrew/homebrew-core/issues. Maybe those icons should be excluded while packaging or your system actually has invalid permissions, I don't really know much about OS X. 

Vifm can adjust something for OS X, but you first need to figure out why this happens with people who know something about Homebrew.  Feel free to reopen this when more information is available.

**Comment by howarddo2208** [comment]
Thank you, I'll do that
