### ISSUE TITLE
Automatically Redraw on :move Operation

### ISSUE THREAD

**Issue by mthbrown** [vifm/vifm#902]
Hi,

Is there any way to have it automatically redraw the pane after I run a `:move` command? Thanks

**Comment by xaizek** [comment]
Hello,

There should be pane reload due to directory change detection.  However, it's possible that it doesn't work for some file-system or OS.  What Vifm version, file-system and OS are you using?

**Comment by mthbrown** [comment]
Hmm. That's odd. It now works. Not sure what happened. I'll re-open if I run into the behavior again. Thanks
