### ISSUE TITLE
slow navigating in directory with symbolic links which links to slow network storage

### ISSUE THREAD

**Issue by aca** [vifm/vifm#903]
Hi,

I have a slow network storage on `/mnt/nas`.
And I have folder X with links to files in that directory.
```
X/a -> /mnt/nas/a
X/b -> /mnt/nas/b
```

Navigating `X` is slow like navigating `/mnt/nas`. (with directory + file preview)
I don't see the reason vifm works so slow (compared to simpler file navigator like nnn).
Does it try to follow link and try to preview file? Is there a way to disable this behavior?

**Comment by xaizek** [comment]
Hello,

Symbolic links don't really have metadata, their metadata is the metadata of the target they point to and Vifm:
 - highlights broken symbolic links differently, so it needs to check that the target exists
 - needs to know whether the target is a directory or a file to handle them differently

You can try setting [`'slowfs'` option](https://vifm.info/vimdoc.shtml#vifm-%27slowfs%27):
```vim
set slowfs+=/mnt/nas
```
The side effect of this is that symlinks in `X` will act as directories as that's the assumption Vifm makes when you ask it to not check symlink target.

**Comment by aca** [comment]
Thanks for the quick response.
I've checked that it consider symbolic link as directory, but still slow when I move around (scroll down, scroll up). Directory contains 50000+ symbolic link.

**Comment by xaizek** [comment]
You're right, there is an access to target metadata on size querying even for slow targets (for displaying size in a column or on the status line).  Thanks, will fix that.
