### ISSUE TITLE
Settings for the position of dialogs/menus

### ISSUE THREAD

**Issue by Ingvix** [vifm/vifm#905]
I tried to look through all the settings for a possibility to limit the dialogs and menus to active pane so they wouldn't overlap with the other(s), but could not find a way. If it actually exists, please point me towards it. Otherwise I'd like to this to be implemented. My personal reason for this is to make it work with vifmimg which uses ueberzug to show image previews. All the dialogs and menus may get partially blocked dua to the preview images, so I'd like them to stay away from the quick view area. Limiting them to the active pane seems the smartest way to do it.

**Comment by xaizek** [comment]
There is no configuration like that and it might not be a very good idea in that dialogs/menus can be hard to read.

What version of Vifm are you using, older than v0.12.1? #739 was fixing the same issue with ueberzug, but by hiding the preview on openning menus or dialogs.  There is also unreleased 8eddfdee46ded8c13744abbee2a066776715890f related to graphics in view mode (after pressing <kbd>e</kbd>).
