### ISSUE TITLE
 ../deliver.sh -i vifm '/usr/local/bin' /bin/sh[24]: ../deliver.sh:  not found

### ISSUE THREAD

**Issue by arozehnal** [vifm/vifm#906]
I have successfully compiled vifm, but the installation ends with an error
```
make install
Making install in src
  GEN      ../data/vifm-help.txt
 /opt/freeware/bin/mkdir -p '/usr/local/bin'
  ../deliver.sh -i vifm '/usr/local/bin'
/bin/sh[24]: ../deliver.sh:  not found
make[2]: *** [Makefile:1138: install-binPROGRAMS] Error 127
make[1]: *** [Makefile:2641: install-am] Error 2
make: *** [Makefile:392: install-recursive] Error 1
```
---
AIX 7.2
gcc  10.3.0

**Comment by xaizek** [comment]
Sounds like you have environment variable `$INSTALL` defined to `../deliver.sh -i` and `Makefile` picks that up.  Try undefining it (setting to empty value probably won't be enough, need to remove it), maybe with `env -u INSTALL make install` or in some shell-specific way.  You probably should check it exists first (`env | grep deliver.sh`).

**Comment by xaizek** [comment]
No input for over a year, I consider this resolved.
