### ISSUE TITLE
[0.13] Merging directories with conflicts fails when moving but not when copying.

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#909]
### Steps to reproduce

1. `mkdir -p src/dir/subdir1 src/dir/subdir2 dest/dir/subdir1 dest/dir/subdir2 ; touch src/dir/subdir1/sd1f1 src/dir/subdir2/sd2f1 src/dir/subdir2/sd2f2  dest/dir/subdir1/sd1f1 dest/dir/subdir2/sd2f1`

```
├── dest
│   └── dir
│       ├── subdir1
│       │   └── sd1f1
│       └── subdir2
│           └── sd2f1
└── src
    └── dir
        ├── subdir1
        │   └── sd1f1
        └── subdir2
            ├── sd2f1
            └── sd2f2

9 directories, 5 files
```
(I am using `tree` instead of Vifm's tree view, because not only is it Vifm's panel hard to copy, it is also not updated when merging succeeds.)

2. Yank `src/dir`
3. go to `dest`
4. Put (move).

For `dir/`, choose `merge` or `Merge all`
for `dir/subdir1/sd1f1`, choose `no`.
Error while putting: `…/src/dir/subdir1`: Failed to remove directory
choose Ignore.
`src/dir/subdir1: Failed to remove directory (Directory not empty)`
```
tree                                                                                                                                                                      20:49
.
├── dest
│   └── dir
│       ├── subdir1
│       │   └── sd1f1
│       └── subdir2
│           └── sd2f1
└── src
    └── dir
        ├── subdir1
        │   └── sd1f1
        └── subdir2
            ├── sd2f1
            └── sd2f2

9 directories, 5 files
```

#### Steps not to reproduce

If at Step 4, I just "put" (copy), `dir/subdir2/sd2f2` is copied and no warning about the other two files shows up.

```
├── dest
│   └── dir
│       ├── subdir1
│       │   └── sd1f1
│       └── subdir2
│           ├── sd2f1
│           └── sd2f2
└── src
    └── dir
        ├── subdir1
        │   └── sd1f1
        └── subdir2
            ├── sd2f1
            └── sd2f2

9 directories, 6 files
```

#### Version

```
Version: 0.13
Git info: built out of repository
Compiled at: Jun 15 2023 21:05:54

Support of extended keys is on
Parsing of .desktop files is enabled
Without GTK+ library
With magic library
With X11 library
With dynamic loading of X11 library
With file program
With -n option for cp and mv
With remote command execution
```

**Comment by xaizek** [comment]
> it is also not updated when merging succeeds.

I see it being updated just fine.  Any unusual FS?

> Merging directories with conflicts fails when moving but not when copying.

The behaviour is inconsistent (copy silently overwrites files), but the error on move looks reasonable: a source file was preserved, so source directory can't be removed.

**Comment by aleksejrs** [comment]
> > it is also not updated when merging succeeds.
> 
> I see it being updated just fine. Any unusual FS?

btrfs with `noatime`. Try looking from outside the directory.

> > Merging directories with conflicts fails when moving but not when copying.
> 
> The behaviour is inconsistent (copy silently overwrites files), but the error on move looks reasonable: a source file was preserved, so source directory can't be removed.

I expect it to move sd2f2.

**Comment by xaizek** [comment]
> btrfs with `noatime`. Try looking from outside (above) the directory.

`noatime` should make no difference (never used for change detection).

I opened tree in the same directory where I ran `mkdir`/`touch` commands.  Using parent of that also works.  Is that what you meant?

> I expect it to move sd2f2. As I understand it, it does move _some_ files in more complex cases.

Yes, the result depends on where the first conflict happens.

`cp` overwrites existing files, hence copy in Vifm does.  `mv` refuses to merge directories, but I think move and copy in Vifm should be consistent.

**Comment by xaizek** [comment]
I thought you're talking about tree view (`:tree` command). Preview watches only the file under the cursor (directory in this case), not the whole subtree.

**Comment by aleksejrs** [comment]
> `cp` overwrites existing files, hence copy in Vifm does.

That was unexpected.

**Comment by xaizek** [comment]
> > `cp` overwrites existing files, hence copy in Vifm does.
> 
> That was unexpected.

Yes, I later realized that it was supposed to ask for confirmation, but didn't because of code changes made in 7383a41.  I don't remember what was it fixing, reverting didn't break any tests and couldn't reproduce any similar behaviour, so dropped that change.

Merge-moving should now work properly and not abort too soon.  Thanks.
