### ISSUE TITLE
Set directory where sessions should be stored.

### ISSUE THREAD

**Issue by TornaxO7** [vifm/vifm#910]
According to the help page in the `vifm-sessions` chapter you are not able to set the path of where the sessions should be stored:
```
Storage and naming 

`$VIFM/sessions/` directory serves as a storage for sessions.  Consequently
names should be valid filenames.  The structure of the storage is flat meaning
that there are no subdirectories, that's why names of sessions can't contain
slashes.
```
I'm using the [nix-home-manager] and I set it up to take care of my `vifm` configs. Sadly it always recreates my `~/.config/vifm` directory, hence the `sessions` directory gets removed everytime I update my system.

So it would be nice if there's an option where you can set the directory of where the sessions should be stored so I won't lose my bookmarks anymore :)

[nix-home-manager]: https://github.com/mjstewart/nix-home-manager

**Comment by xaizek** [comment]
This might be an overly generic solution for a particular use case.  If you want to store sessions in a different place and recreate `~/.config/vifm`, maybe provisioning should just create a symbolic link from `~/.config/vifm/sessions` to where sessions are actually stored?

**Comment by TornaxO7** [comment]
Hm... I'd need to recreate the symlink after every change ;-; welp. I'll look for another solution then.

Thanks!

**Comment by xaizek** [comment]
> I'd need to recreate the symlink after every change

Why not only when `~/.config/vifm` directory is created?

**Comment by TornaxO7** [comment]
that's a "feature" of home manager in this case. After every change of my config, I'd need to execute `sudo nixos-rebuild switch --flake  <system config name>` which will rebuild everything if needed but also means to recreate my configs because only after executing the command above, the changes which I made will be used.

**Comment by xaizek** [comment]
Can't home manager create the symbolic link for you?  I thought that's its responsibility.

**Comment by TornaxO7** [comment]
> Can't home manager create the symbolic link for you? I thought that's its responsibility.

as far as I know the answer for this would be "no". But I'm still new in nixos, so maybe I can find someting.

**Comment by xaizek** [comment]
Seems relevant: https://github.com/nix-community/home-manager/issues/676

**Comment by TornaxO7** [comment]
oh, interesting. Thanks!

**Comment by xaizek** [comment]
If solution from that issue won't work, feel free to reopen this one.
