### ISSUE TITLE
a long command (with %f with many files selected, length > 126k) makes fish say "Variables cannot be bracketed. In fish, please use "$0""

### ISSUE THREAD

**Issue by aleksejrs** [vifm/vifm#912]
vifm 0.13, fish 3.6.0

`touch xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18}{0,1,2,3,4,5,6,7,8,9}{0,1,2,3,4,5,6,7,8,9}`

This creates 1900 empty files with long names.
If I select 1856 or more of them and run `ls %f`, I get 
```
fish: Variables cannot be bracketed. In fish, please use "$0".
eval "${0}${1}"
       ^
```

If I select 1854 of them or make the file names shorter, it works.

Running the same command in fish works:
```
ls *|wc -c
126991
```
Even with twice as many files:
```
ls *|wc -c
260891
```

**Comment by xaizek** [comment]
There is a system limit on the length of an argument and a corresponding workaround.  Luckily, braces aren't actually necessary for it to work in POSIX shells and can be dropped to make it work even in something like fish.  Thanks, will adjust this.

Command are run like `bash -c 'whole command goes here'` outside of a shell, hence difference in behaviour when they are run manually.  [%Pl](https://vifm.info/vimdoc.shtml#vifm-%25Pl) or [%Pz](https://vifm.info/vimdoc.shtml#vifm-%25Pz) could be used to avoid constructing large argument list.
