### ISSUE TITLE
Install fails on Mac

### ISSUE THREAD

**Issue by reicheltd** [vifm/vifm#914]
Hey there,

I cloned the latest master and did my usual "make install".

Mac OS 13.4.1
iTerm 3.4.19

± % ./configure && make install
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for library containing strerror... none required
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for ANSI C header files... (cached) yes
checking whether make supports nested variables... (cached) yes
checking build system type... arm-apple-darwin22.5.0
checking host system type... arm-apple-darwin22.5.0
checking host... arm-apple-darwin22.5.0
checking alloca.h usability... yes
checking alloca.h presence... yes
checking for alloca.h... yes
checking malloc.h usability... no
checking malloc.h presence... no
checking for malloc.h... no
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking mntent.h usability... no
checking mntent.h presence... no
checking for mntent.h... no
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking for sys/stat.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for sys/sysmacros.h... no
checking for sys/param.h... yes
checking for sys/user.h... yes
checking for linux/binfmts.h... no
checking for uid_t... yes
checking for gid_t... yes
checking for mode_t... yes
checking for off_t... yes
checking for time_t... yes
checking for uint64_t... yes
checking for direntry_t... no
checking for getmntinfo... no
checking for stat... no
checking for FILE... yes
checking for wchar_t... yes
checking for access... yes
checking for atof... yes
checking for atoi... yes
checking for calloc... yes
checking for chdir... yes
checking for close... yes
checking for closedir... yes
checking for dup... yes
checking for dup2... yes
checking for execve... yes
checking for execvp... yes
checking for exit... yes
checking for fdatasync... yes
checking for fclose... yes
checking for fdopen... yes
checking for feof... yes
checking for fgetc... yes
checking for fgets... yes
checking for fork... yes
checking for fprintf... yes
checking for fputc... yes
checking for fputs... yes
checking for free... yes
checking for fwrite... yes
checking for getcwd... yes
checking for getenv... yes
checking for geteuid... yes
checking for getgrent... yes
checking for getgrgid... yes
checking for getgrgid_r... yes
checking for getgrnam... yes
checking for getpid... yes
checking for getppid... yes
checking for getpwent... yes
checking for getpwnam... yes
checking for getpwuid... yes
checking for getpwuid_r... yes
checking for ioctl... yes
checking for iswalnum... yes
checking for iswdigit... yes
checking for iswprint... yes
checking for iswspace... yes
checking for iswupper... yes
checking for kill... yes
checking for localtime... yes
checking for malloc... yes
checking for mbstowcs... yes
checking for memcmp... yes
checking for memcpy... yes
checking for memccpy... yes
checking for memmove... yes
checking for memset... yes
checking for mkdir... yes
checking for mkstemp... yes
checking for opendir... yes
checking for pathconf... yes
checking for pause... yes
checking for pclose... yes
checking for perror... yes
checking for pipe... yes
checking for popen... yes
checking for printf... yes
checking for puts... yes
checking for qsort... yes
checking for rand... yes
checking for read... yes
checking for readlink... yes
checking for realloc... yes
checking for realpath... yes
checking for rename... yes
checking for rmdir... yes
checking for select... yes
checking for setenv... yes
checking for setgrent... yes
checking for setlocale... yes
checking for setpgid... yes
checking for setpwent... yes
checking for setsid... yes
checking for setvbuf... yes
checking for sigaction... yes
checking for sigaddset... yes
checking for sigemptyset... yes
checking for signal... yes
checking for snprintf... yes
checking for sprintf... yes
checking for srand... yes
checking for strcasecmp... yes
checking for strcasestr... yes
checking for strcat... yes
checking for strchr... yes
checking for strcmp... yes
checking for strcpy... yes
checking for strdup... yes
checking for strerror... yes
checking for strftime... yes
checking for strlen... yes
checking for strncasecmp... yes
checking for strncat... yes
checking for strncmp... yes
checking for strncpy... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtok_r... yes
checking for strtol... yes
checking for strtoll... yes
checking for strverscmp... no
checking for sysconf... yes
checking for time... yes
checking for tolower... yes
checking for toupper... yes
checking for towupper... yes
checking for ungetc... yes
checking for unlink... yes
checking for unsetenv... yes
checking for utimes... yes
checking for vfprintf... yes
checking for vsnprintf... yes
checking for vswprintf... yes
checking for waitpid... yes
checking for wcscat... yes
checking for wcscmp... yes
checking for wcscpy... yes
checking for wcslen... yes
checking for wcsncmp... yes
checking for wcsncpy... yes
checking for wcstof... yes
checking for wcstol... yes
checking for wcstombs... yes
checking for wcswidth... yes
checking for wcwidth... yes
checking for futimens... yes
checking for random... yes
checking for srandom... yes
checking for reallocarray... no
checking whether _PC_CASE_SENSITIVE is declared... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking for regcomp... yes
checking for regerror... yes
checking for regexec... yes
checking for regfree... yes
checking for regex_t... yes
checking whether REG_EXTENDED is declared... yes
checking whether REG_ICASE is declared... yes
checking whether REG_NOMATCH is declared... yes
checking for struct stat.st_mtim... no
checking for struct dirent.d_type... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for off_t... (cached) yes
checking for file... 1
checking for groff... groff
checking for col... col
checking for awk... awk
checking for sed... sed
checking for perl... perl
checking for vim... vim
checking for git... git
checking whether C compiler accepts -Wall... yes
checking for pow in -lm... yes
checking for shm_open in -lrt... no
checking for a sed that does not truncate output... /usr/bin/sed
checking whether gcc is Clang... yes
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... unknown
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for pthread_create... yes
checking for pthread_getspecific... yes
checking for pthread_key_create... yes
checking for pthread_mutex_lock... yes
checking for pthread_mutex_unlock... yes
checking for pthread_setspecific... yes
checking for pthread_detach... yes
checking for pthread_self... yes
checking for pthread_t... yes
checking for pthread_key_t... yes
checking for pthread_mutex_t... yes
checking for pthread_cond_t... yes
checking whether PTHREAD_MUTEX_INITIALIZER is declared... yes
checking whether PTHREAD_COND_INITIALIZER is declared... yes
checking for initscr in -lncursesw... no
checking for initscr in -lncurses... yes
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking whether A_ITALIC is declared... no
checking whether COLORS is declared... yes
checking whether TABSIZE is declared... yes
checking for curs_set... yes
checking for def_prog_mode... yes
checking for doupdate... yes
checking for endwin... yes
checking for flushinp... yes
checking for getcchar... yes
checking for has_colors... yes
checking for init_pair... yes
checking for initscr... yes
checking for isendwin... yes
checking for keypad... yes
checking for mvwin... yes
checking for mvwprintw... yes
checking for newwin... yes
checking for noecho... yes
checking for nonl... yes
checking for raw... yes
checking for reset_prog_mode... yes
checking for resize_term... yes
checking for resizeterm... yes
checking for scrollok... yes
checking for set_escdelay... yes
checking for setcchar... yes
checking for start_color... yes
checking for use_default_colors... yes
checking for waddch... yes
checking for waddnstr... yes
checking for waddnwstr... yes
checking for wattr_set... yes
checking for wbkgrndset... yes
checking for wborder... yes
checking for wclrtoeol... yes
checking for werase... yes
checking for wget_wch... yes
checking for wgetch... yes
checking for wmove... yes
checking for wnoutrefresh... yes
checking for wprintw... yes
checking for wredrawln... yes
checking for wrefresh... yes
checking for wresize... yes
checking for wtimeout... yes
checking for wtouchln... yes
checking for extended_pair_content... no
checking for pair_content... yes
checking sys/inotify.h usability... no
checking sys/inotify.h presence... no
checking for sys/inotify.h... no
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for lgetxattr... no
checking for llistxattr... no
checking for lsetxattr... no
checking for gio/gio.h... yes
checking for glib.h... yes
checking for g_file_info_get_content_type... yes
checking for g_file_new_for_path... yes
checking for g_file_query_info... yes
checking for g_object_unref... yes
checking for magic_open in -lmagic... no
checking for dlopen in -ldl... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for dlsym... yes
checking for dlclose... yes
checking for XOpenDisplay in -lX11... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating build-aux/config.h
config.status: build-aux/config.h is unchanged
config.status: executing depfiles commands
./configure  10.52s user 7.18s system 93% cpu 18.888 total
Making install in src
  CC       ui/color_manager.o
ui/color_manager.c:186:26: error: call to undeclared function 'bsearch'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                pair_cache_t *needle = bsearch(&key, pair_cache, pair_cache_sorted,
                                       ^
ui/color_manager.c:186:17: warning: incompatible integer to pointer conversion initializing 'pair_cache_t *' with an expression of type 'int' [-Wint-conversion]
                pair_cache_t *needle = bsearch(&key, pair_cache, pair_cache_sorted,
                              ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make[1]: *** [ui/color_manager.o] Error 1
make: *** [install-recursive] Error 1

**Comment by xaizek** [comment]
Hi. Thanks, forgot an `#include`.
