### ISSUE TITLE
Segfault with --remote-expr when the server is not running

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#916]
Running the following command:

```console
$ vifm --server-name vifm --remote-expr 'expand("%f")'
```

yields the error as follows:

```
vifm: engine/parsing.c:207: vle_parser_eval: Assertion `initialized && "Parser must be initialized before use."' failed.
zsh: IOT instruction (core dumped)  vifm --server-name vifm --remote-expr 'expand("%f")'
```

What's weird is that when I substitute `server-name` with something that obviously does not exist, and I haven't ever launched, such as `vifmx`, the command exits gracefully.

Version: `v0.13-149-gc284fbb85df8`

**Comment by xaizek** [comment]
Thanks.  Looks like `/tmp/vifm-ipc-vifm` pipe exists, but is unused. New instance takes this name and then sends expression to itself :)
