### ISSUE TITLE
Feature request: ability to pass active filelist to a subprocess

### ISSUE THREAD

**Issue by rr-** [vifm/vifm#917]
My use case: I use vifm to browse and manage my photos and mpv to view them. In order to be able to navigate inside of mpv to the previous/next photo, I added a Python wrapper that composes and passes the playlist from the current directory to mpv. This works well.

However, this approach falls apart when I play with `:sort`, `:filter`, `za` `zb` etc. It'd be great to have something like `%Pl` but for all files _shown_ by vifm, not _selected_, so that I don't have to reverse engineer the playlist in that Python wrapper from `%f` and the family alone.

The behavior I want from my setup is well illustrated by Windows Explorer and Windows Photo Viewer – they're two distinct programs, however sorting the files in Explorer or filtering them causes the photo viewer to also respect the active filters in its internal navigation. I don't think there's a way to emulate this with the current feature set, hence this feature request.

Thanks

**Comment by xaizek** [comment]
So you want to feed an already running `mpv` current list of files for which you use something like `:!wrapper %Pl`? If so, ranges override selection and `:%!wrapper %Pl` should send all files to `mpv`.

**Comment by rr-** [comment]
This is amazing! Thanks!

**Comment by rr-** [comment]
@xaizek is there a way to use this way of running third party programs with `:fileviewer`? For now I can do `vifm --server-name vifm --remote '+%!cat %Pl >TEMPFILE'` however this needs me to poll TEMPFILE for changes from inside the wrapper to ensure it's fully written to.

**Comment by xaizek** [comment]
There are no ranges in `:filetype` (`:fileviewer` wouldn't display anything).  I can suggest use of Lua plugin though ([how to install](https://wiki.vifm.info/index.php/Using_Lua_plugins#Installation)):
```lua
--[[

Usage example (replace "send" with the plugin directory name of your choice):
    filetype {*.png} #send#run

--]]

local M = {}

local function run(info)
    local view = vifm.currview()

    local job = vifm.startjob {
        cmd = 'cat > ~/test',
        iomode = 'w',
    }

    local pipe = job:stdin()
    for i = 1, view.entrycount do
        local entry = view:entry(i)
        pipe:write(entry.location, '/', entry.name, '\n')
    end

    pipe:close()
    job:wait()
end

local added = vifm.addhandler {
    name = "run",
    handler = run,
}
if not added then
    vifm.sb.error(string.format("Failed to register #%s#run", vifm.plugin.name))
end

return M
```
Here it runs `cat > ~/test` feeding it all files in the current view. If you need macro expansion, use `vifm.expand('wrapper %d')` in place of the command.
