### ISSUE TITLE
Archivemount - slow extraction of mounted archive

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#92]
I'm wondering, I tried to extract files from [tar.gz](https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz) archive  (I used vifm's `:copy` cmd) after mounting it via `archivemount` in vifm. After five minutes of waiting, Vifm was still copying files from the archive, I lost patience and terminated the process.
It took insanely long time in comparison of using ubuntu's buildin `Archive Manager` to extract 60MB archive.

I'm not sure on which side is problem caused and by what. I'm probably just doing something wrong way.

I've following simple configuration in my vifmrc:

```
filetype *.tar,*.tar.bz2,*.tbz2,*.tgz,*.tar.gz,*.tar.xz,*.txz
       \ {Mount with archivemount}
       \ FUSE_MOUNT|archivemount %SOURCE_FILE %DESTINATION_DIR,
```

**Comment by xaizek** [comment]
The command is fine, it's just that archivemount doesn't seem to be optimized for such operations. I'm not sure if it's inherent to FUSE or this particular interface implementation. vifm is just a client in this case and doesn't really affect performance (I see multiple threads of archivemount, one of which is constantly at 99-100% load, so it must be the bottleneck).

**Comment by fogine** [comment]
It doesn't looks like there is some easy solution for that. I was thinking I could use archivemount only for browsing compressed archives and selecting files I want to extract and for decompression of selected files in mounted archive use another external tool. This could be then wrapped into some bash script.
The problem is that there is no way (as far as I know) how to get easily back from mounted archive directory to original archive location (e.g. via command).

Here is an idea how it could work:
1.Mount archive via archivemount
2.Select  files that should be extracted and save their's names to register (save output of %f macro)
3. Unmount - return back to archive file in filesystem (here I see possible problem)
4. Call external tool to extract files (only those stored in register) from the archive

I know that it's a little "hardcore" solution but in current state, archivemount is pretty useless (with extremely slow extraction time). One rarely want to do anything else then fast extract files from the archive to desired location. Only thing archivemount could be used for nowadays is edit files within archive, which people use very rarely I think...

Temporary, I end up with use of cmd: ":!file-roller -h %f %i" but it's far from desired functionality as it "only" extract all archive into current dirrectory

**Comment by xaizek** [comment]
> I know that it's a little "hardcore" solution but in current state, archivemount is pretty useless (with extremely slow extraction time).

I profiled it a bit and it looks like it seriously lacks caching, a lot of identical queries are performed again and again, resulting in millions (one of samples included more than *half of a billion calls*).

> One rarely want to do anything else then fast extract files from the archive to desired location.

I usually browse archives just to look up their structure, grep some files and view a couple of them.
There is really not much sense in browsing archive if all you want is to extract it, but this doesn't hold if you want only some subtree of it.

> Only thing archivemount could be used for nowadays is edit files within archive, which people use very rarely I think...

Yeah, I did this only a couple of times on purpose (sometimes do it accidentally).

> Temporary, I end up with use of cmd: ":!file-roller -h %f %i" but it's far from desired functionality as it "only" extracts all data from archive into current dirrectory

If you're using vifm from code repository (for `$VIFM_FUSE_FILE`), try the following script (`extract-files`):

```bash
#!/usr/bin/env bash

if [ -z "$VIFM_FUSE_FILE" ]; then
    echo "error: this command is meant to be run inside vifm FUSE mount"
    exit 1
fi

archive="$VIFM_FUSE_FILE"
fusehome="$1"
shift
destination="$1"
shift

files=
for f; do
    # obtain relative path inside archive
    f="${f#$fusehome}"
    f="${f#/}"
    f="${f#*/}"

    files=( ${files[@]} "$f" )
done

exec aunpack "$archive" --quiet --extract-to="$destination" "${files[@]}"
```

here is part to put into vifmrc:

```
" extract selected files from archive we're exploring right now
command! extractfiles :execute '!%%n extract-files' &fusehome expand('%D') expand('%f:p')
```

I used `aunpack` from `atool` which preserves parent directories (I don't really like this, but don't see an option to change this), but you should be able to plug in `file-roller` or anything else instead of `aunpack`.

(P.S. don't use `%S` or other similar macros in the command, just noticed that `VIFM_FUSE_FILE` isn't set for those macros, will address that.)

**Comment by fogine** [comment]
`If you're using vifm from code repository (for $VIFM_FUSE_FILE), try the following script (extract-files):`

That's exactly what I wanted to do, thank you @xaizek for sharing !

` I used aunpack from atool which preserves parent directories (I don't really like this, but don't see an option to change this)`

I've been trying from yesterday to find a way for extraction process not preserving parent directories. Just copy files/directories which are selected to second pane's path and don't manipulate in any way with directory tree. Surprisingly, it was harder than I expected.

I had to use another temporary middleware destination to which selected files are extracted and then moved to original destination with unwanted path tree excluded.
Here is edited script:


````bash
#!/usr/bin/env bash

if [ -z "$VIFM_FUSE_FILE" ]; then
    echo "error: this command is meant to be run inside vifm FUSE mount"
    exit 1
fi

archive="$VIFM_FUSE_FILE"
filename="${archive##*/}"

#Because 7z can't extract these files in one call:
doubleExtraction=0
if [[ $filename =~ ^.*(tar\.gz|tar\.bz2)$ ]] ;
then
    doubleExtraction=1
fi

fusehome="$1"
shift
destination=$1
shift

tempDest=`mktemp -d`

files=
for f; do
    # obtain relative path inside archive
    f="${f#$fusehome}"
    f="${f#/}"
    f="${f#*/}"

    files=( ${files[@]} "$f" )
done

firstFile=${files[@]:0:1}
IFS='/' read -ra ADDR <<< $firstFile
unset ADDR[${#ADDR[@]}-1]

movePath=$tempDest/
for i in "${ADDR[@]}"; do
    movePath=$movePath$i/
done
movePath=$movePath*

if [[ $doubleExtraction = 1 ]] ;
then
    exec 7z x -so "$archive" | 7z x -si -ttar -o$tempDest "${files[@]}" > /dev/null 2>&1 && mv -i $movePath $destination && rm -r $tempDest
else
    7z x -o$tempDest "$archive" "${files[@]}" > /dev/null 2>&1 && mv -i $movePath $destination && rm -r $tempDest
fi

````

**Comment by xaizek** [comment]
Finally (after two years) added the script to [the wiki](https://wiki.vifm.info/index.php?title=How_to_extract_files_from_archives_efficiently).
