### ISSUE TITLE
Emacs says "Symbol's function definition is void" whenever trying to bulk rename

### ISSUE THREAD

**Issue by Gregaras** [vifm/vifm#920]
My `vicmd` is `emacs\ -nw`. Bulk renaming works in Ranger with `emacs -nw`.

**Comment by xaizek** [comment]
External editing passes `-f` to the editor, which is probably causes this.  You need something like https://github.com/vifm/vifm/blob/master/data/plugins/editor/vim.lua but for `emacs` and then set:
```vim
set vicmd='#editor#run emacs'
```
A plugin like that handles various ways in which Vifm invokes an editor (sometimes passing Vim :commands), they are documented in https://github.com/vifm/vifm/blob/3dd61589e85a325aabd24f9147e0c14746ebc7bf/data/vim/doc/app/vifm-lua.txt#L305

In this case copying `vim.lua` to `emacs.lua` to replace `vim` with `emacs -nw` will avoid passing `-f` (also need to add a line to `init.lua`).  The rest of cases need other adjustments and I don't really know how to do those things in Emacs. Quick plugin overview is [here](https://wiki.vifm.info/index.php/Using_Lua_plugins).

**Comment by Gregaras** [comment]
By the way, my OS is GNU/Linux and my distribution is Manjaro.

I haven't programmed in Lua and I'm not very familiar with Vifm. I downloaded `vim.lua` and `init.lua` from [there](https://github.com/vifm/vifm/tree/master/data/plugins/editor). Then I put those files to `~/.config/vifm/plugins` (there wasn't plugins folder so I made one). I copied `vim.lua` and renamed it to `emacs.lua`. I added a line `emacs = vifm.plugin.require('emacs')` under this line:
https://github.com/vifm/vifm/blob/3dd61589e85a325aabd24f9147e0c14746ebc7bf/data/plugins/editor/init.lua#L18C33-L18C33
Then I exited Vifm, launched It again and executed `set vicmd='#editor#run emacs'`. I selected files to rename, hit `cw` and Vifm said '`Failed to view file via handler`'. I pressed Enter and then Vifm said '`Editing of file failed`'. Also I got errors when I tried to open text files ('`Failed to view file via handler`' and '`Can't edit selection`').

**Comment by xaizek** [comment]
If you don't have `gvim.lua`, remove this line:
```lua
    gvim = vifm.plugin.require('gvim'),
```
It tries to load `gvim.lua` and that fails operation of the plugin.  You can view Lua errors via `:messages` and status of the plugin is displayed in `:plugins` (pressing <kbd>e</kbd> will open its log).

**Comment by Gregaras** [comment]
> If you don't have `gvim.lua`, remove this line:
> 
> ```lua
>     gvim = vifm.plugin.require('gvim'),
> ```
> 
> It tries to load `gvim.lua` and that fails operation of the plugin. You can view Lua errors via `:messages` and status of the plugin is displayed in `:plugins` (pressing e will open its log).

I removed the line but I get same results. When I execute `plugins` command Vifm says '`There are no plugins`'.

**Comment by xaizek** [comment]
> I removed the line but I get same results. When I execute `plugins` command Vifm says '`There are no plugins`'.

I missed that you didn't create `~/.config/vifm/plugins/editor` directory for the plugin files.  Directory tree should look like this:
```
~/.config/vifm/plugins
└── editor
    ├── emacs.lua
    ├── init.lua
    └── vim.lua
```

**Comment by Gregaras** [comment]
> > I removed the line but I get same results. When I execute `plugins` command Vifm says '`There are no plugins`'.
> 
> I missed that you didn't create `~/.config/vifm/plugins/editor` directory for the plugin files. Directory tree should look like this:
> 
> ```
> ~/.config/vifm/plugins
> └── editor
>     ├── emacs.lua
>     ├── init.lua
>     └── vim.lua
> ```

I did this and now it opens Vim not Emacs.

**Comment by Gregaras** [comment]
> > I removed the line but I get same results. When I execute `plugins` command Vifm says '`There are no plugins`'.
> 
> I missed that you didn't create `~/.config/vifm/plugins/editor` directory for the plugin files. Directory tree should look like this:
> 
> ```
> ~/.config/vifm/plugins
> └── editor
>     ├── emacs.lua
>     ├── init.lua
>     └── vim.lua
> ```

I did this and it now opens up Vim instead of Emacs.

**Comment by Gregaras** [comment]
> > I removed the line but I get same results. When I execute `plugins` command Vifm says '`There are no plugins`'.
> 
> I missed that you didn't create `~/.config/vifm/plugins/editor` directory for the plugin files. Directory tree should look like this:
> 
> ```
> ~/.config/vifm/plugins
> └── editor
>     ├── emacs.lua
>     ├── init.lua
>     └── vim.lua
> ```

I did this and also I thought I didn't have to edit `emacs.lua`. I replaced all `vim` words with `emacs` and now it seems to work.

**Comment by xaizek** [comment]
You might also want to add `set novimhelp` to `vifmrc` to disable help with tags.  I think Emacs supports tags, but it needs to be done differently and I don't know how.

Here is a bit better `emacs.vim` which supports navigation to line&column and errors nicely when something isn't supported:
```lua
--[[

Wraps console emacs for handling basic editor use cases within Vifm.

Unimplemented actions:
 * open-help (:help when 'vimhelp' is set):
   can probably be done, it's regular tags after all
 * edit-list ("v" key in navigation menus):
   don't know if there is a builtin notion of a quickfix list in Emacs

--]]

local M = {}

M.handlers = {}

M.handlers["open-help"] = function(info)
    vifm.errordialog("Unimplemented", "Can't view Vim-style help via Emacs.")
    return false
end

M.handlers["edit-one"] = function(info)
    local posarg = ""
    if info.line ~= nil and info.column == nil then
        posarg = '+' .. info.line
    elseif info.line ~= nil and info.column ~= nil then
        posarg = string.format("+%d:%d", info.line, info.column)
    end

    local exitcode = vifm.run {
        cmd = string.format("emacs -nw %s %s", vifm.escape(posarg),
                            vifm.escape(info.path)),
        usetermmux = not info.mustwait,
    }

    return exitcode == 0
end

function map(table, functor)
    local result = {}
    for key, value in pairs(table) do
        result[key] = functor(value)
    end
    return result
end

M.handlers["edit-many"] = function(info)
    local exitcode = vifm.run {
        cmd = string.format("emacs -nw %s",
                            table.concat(map(info.paths, vifm.escape), ' '))
    }

    return exitcode == 0
end

M.handlers["edit-list"] = function(info)
    vifm.errordialog("Unimplemented", "Can't view quickfix via Emacs.")
    return false
end

return M
```

I'll add the file to repository, so I guess this issue can be closed because using Lua is the way to accomodate foreign (non-Vim) editors as doing this without writing code is problematic.
