### ISSUE TITLE
BUG: Project builds with -Wall

### ISSUE THREAD

**Issue by ahesford** [vifm/vifm#923]
In `configure.ac`, [`-Wall` is added to `$CFLAGS`](https://github.com/vifm/vifm/blob/master/configure.ac#L391-L397) whenever the compiler supports it. Although I recognize that building with `-Wall` is a good way to catch unintended uses *in a test environment*, leaking this into the routine build process causes havoc for users who may not be interested in debugging the build system [just to compile the project](https://github.com/void-linux/void-packages/pull/44870/files#diff-05ea1be90d32f3e965d0c2f4118dff44daaccc26584b16683561306671a0a719R17). The right way to build with `-Wall` is to export `CFLAGS` before configuring, or add an opt-in flag to `configure` that gates this behavior.

**Comment by xaizek** [comment]
> causes havoc

How?  It's `-Wall`, not `-Wall -Werror`.

**Comment by ahesford** [comment]
*Mea culpa*! This was predicated on a misunderstanding of the change to the Void template, which 1) only causes warning messages when building tests (where those warnings would be wholly appropriate) and 2) doesn't actually seem to change the test behavior. Sorry for the trouble!
