### ISSUE TITLE
Helix as the default editor

### ISSUE THREAD

**Issue by mahor1221** [vifm/vifm#925]
I had trouble using [Helix](https://github.com/helix-editor/helix) as the default editor, AFAIK everything works fine except the `:rename` command. I just wanted to share my script that allows doing it:

`~/.local/bin/helix-vifm`:
```bash 
#!/bin/bash

arg1="$1"
shift

if [ "$arg1" = "-f" ]; then
  helix "$@"
else
  helix "$arg1" "$@"
fi
```

`~/.config/vifm/vifmrc`:
```bash
...
set vicmd=helix-vifm
...
```

**Comment by xaizek** [comment]
`-f` on `:rename` is just easy to hit, there are more use-cases that probably won't work (never heard of Helix before but it doesn't look Vim-compatible).  There are instructions in https://github.com/vifm/vifm/issues/920#issuecomment-1646544983 on how to support a new editor through Lua API, it will probably look something like [for Emacs](https://github.com/vifm/vifm/blob/master/data/plugins/editor/emacs.lua) with several cases disabled.

A simpler version of your script:
```bash
#!/bin/bash

if [ "$1" = "-f" ]; then
  shift
fi
exec helix "$@"
```
