### ISSUE TITLE
behaviour of :locate

### ISSUE THREAD

**Issue by svenn71** [vifm/vifm#93]
I use :locate a lot to find files. I observe that, when locate is finished, the file list menu is taking both panes and selecting one of the located files, brings me to the location of that file in the left pane. I also find that there is no way to get back to the result file menu without running the :locate command again.

Would it be a qualified feature wish to have the left pane show the result of the :locate run and the right pane show the content of whatever file currently selected in the file menu? Just like the :view command makes the right pane show the content of the file in the left pane in regular file browsing mode?

**Comment by xaizek** [comment]
> I observe that, when locate is finished, the file list menu is taking both panes and selecting one of the located files, brings me to the location of that file in the left pane.

It should be previously active pane, so if you do `:locate ...` while right pane is active, file will be selected there.

> I also find that there is no way to get back to the result file menu without running the :locate command again.

I was planning to address this by storing results of last menu the same way Vim does for error lists or search results, with `:cnext`, `:cprev` commands and such.

> Would it be a qualified feature wish to have the left pane show the result of the :locate run and the right pane show the content of whatever file currently selected in the file menu? Just like the :view command makes the right pane show the content of the file in the left pane in regular file browsing mode?

You should be able to do almost that (one extra step) on the `master` branch by hitting <kbd>b</kbd> in `:locate` menu, which will load menu list into pane where you will be able to use `:view`, delete files, copy them, almost anything else (operations like putting don't make sense for such views).

I was thinking about command prefix to remove this extra step, something like `:cv locate ...` and results are directly loaded into view.

**Comment by svenn71** [comment]
I have now tried out hitting the b-key in the :locate menu, and it works exactly the way I would like it to do. I can view them, but actually more important, I can open with vim and come back to the result list after vim is closed. And the title of the pane is actually filled in with the locate command I run to create the list, just in case I forgot how I found them in the first place. Excellent feature. I have no problem with pressing an extra key. It happens only once to push the found files into the view anyway.

Is it possible to read the contents of a file into such a buffer? Like if I would have done a locate > filelist on the command line (to store the result) and read filelist into buffer for further work? Would make a nice session management. I do this a lot with vim and use 'gf' to go to file under cursor.

Otherwise the case is already closed from my point of view.

**Comment by xaizek** [comment]
> Is it possible to read the contents of a file into such a buffer?

There is no direct command for that so far, but you can form view from any external command via `%u` or `%U` macros, the latter one skips sorting in case you have files organized in some particular order. For reading list from a file it would be:

    :!cat file %u

it's easy to wrap it into a command

    command! load cat %a %u
    " usage
    load file
