### ISSUE TITLE
YAML/Jinja2 preview issues

### ISSUE THREAD

**Issue by GNOMES** [vifm/vifm#933]
I am troubleshooting an issue I am having with VIFM in 'view' mode (file preview on the right).

I am currently have `fileviewer *[^/],.*[^/] bat -f --wrap=never --pager=never %c` as my catch all at the end of my list of file viewer commands.

I am having a strange issue that when I j/k through files in a directory containing YAML files, my previews are not 100% clearing between some files, leaving partial artifacts from previous file previews. 

It seems I have no issues between files until I hit a file that contains Jinja (Ansible tasks), but it could be other syntax issues. 

Viewing each file individually using bat with similar flags shows no problem. 

After searching old questions I have tried "previewoptions+=graphicsdelay:0", but this doesn't seem to make an impact. 

I have also tried adding a `fileviewer *.yaml clear | bat -f --wrap=never --pager=never %c` or playing with `...%pc` to clear the screen at the end.

Is there a way I can escape the file preview, but still allow syanx highlighting from Bat to process?

**Comment by xaizek** [comment]
> After searching old questions I have tried "previewoptions+=graphicsdelay:0", but this doesn't seem to make an impact.

This isn't a graphics preview, so it won't make any difference.

> I have also tried adding a `fileviewer *.yaml clear | bat -f --wrap=never --pager=never %c` or playing with `...%pc` to clear the screen at the end.

`clear` is for terminals and previewing redirects output so it doesn't reach the terminal.  `%pc` is also only for graphics.

> I am having a strange issue that when I j/k through files in a directory containing YAML files, my previews are not 100% clearing between some files, leaving partial artifacts from previous file previews.

Can you save output of `bat -f --wrap=never --pager=never %c` as files and post here?  The issue should preserve when previewing those files without `bat`.  Maybe there are some encoding or parsing issues, otherwise it should be just colored text.  A screenshot of what it looks like could also be useful.

**Comment by xaizek** [comment]
> How do you want me to run that bat command? I tried running with ":", and get invalid command name. Running in shell with "bat -f --wrap=never --pager=never ", has no issue.

I meant running it via `:!` or in a shell and redirecting output to a file for further analysis, but given your findings that seems to be unnecessary.

> Issue is also seen if I run "vifm --no-configs", followed by ":view".

On a single file or still while switching between them?

> Terminal: Alacritty

What's your `$TERM`? Have you tried to reproduce the issue in other terminals?

So far it looks like either weird behaviour of Alacritty or possibly handling of tabulation in Vifm (assuming files contain tabs).

**Comment by xaizek** [comment]
> Using Alacritty, my $TERM = alacritty. I am also able to reproduce the issue using the default Mac terminal, in which $TERM = xterm-256color.

Then it doesn't look like a terminal quirk.  Might be curses implementation though.

Can you provide files which demonstrate the issue?

Vifm is v0.13 from Homebrew?

**Comment by xaizek** [comment]
Thanks.  I tested it on Monterey in default Terminal and in Alacritty and saw no artifacts.  You might be using a different OS X version, which points toward an issue with some library.  It still might be caused by incorrect interaction of Vifm with something, but given that Vifm just asks curses to print on a window this is not very likely.

**Comment by xaizek** [comment]
> What is the supported min version of VIFM?

There is no unsupported version.

Thanks for the versions, will try using them.

**Comment by xaizek** [comment]
Versions looks the same here:
```
~ user$ brew list --versions | grep ncurses
ncurses 6.4
~ user$ /usr/local/opt/ncurses/bin/ncurses6-config --version
6.4.20221231
~ user$ /usr/bin/ncurses5.4-config --version
5.7.20081102
```

With system's `ncurses` in use:
```
~ user$ brew uses ncurses --eval-all --installed
tig
~ user$ which vifm
/usr/local/bin/vifm
~ user$ otool -L /usr/local/bin/vifm
/usr/local/bin/vifm:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
        /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
```

Not sure what else can explain the issue.  Might be something non-obvious about configuration or interaction between different components.

**Comment by GNOMES** [comment]
Thank your for looking into this.

Is there any commands I could add to fileview *.<file extenion> to force clear prior to preview?

**Comment by GNOMES** [comment]
I was playing with the mac terminal to ignore any possible conflicts with Alacritty/Tmux, and see that if I use the Mac Terminal with TermInfo set to ANSI this issue doesn't happen. Once I set it to Xterm/Xterm-16color/Xterm-256color the issue does not appear. I am guessing this is due to the restricted character set.

**Comment by xaizek** [comment]
> Once I set it to Xterm/Xterm-16color/Xterm-256color the issue does not appear.

I guess "not" shouldn't be there.

> I am guessing this is due to the restricted character set.

Not *character* set but set of supported escape sequences.

This confirms that Vifm itself isn't causing it.  It's might be processing of some Xterm-specific escape sequences and the weird part is the identical behaviour of Alacritty and Mac Terminal.  I think Alacritty is supposed to draw everything via OpenGL while Mac Terminal probably does things differently, so maybe they both use a common parser but that would be weird given that one of them is OS X-specific and another one is written in Rust.  `curses` remains as a likely cause of this, maybe it messes up its buffer the same way in both cases.

**Comment by GNOMES** [comment]
So I have been attempting to use the native Mac Terminal w/o Tmux to simplify my config to isolate this. Oddly have noticed that the issue depends on the vertical size of my terminal.

I have returned the Mac terminal to Xterm-256color as it's terminfo

Using the dimensions listed in the menu bar, If I go 47 or lower rows the issue does not occur. Width does not seem to be a factor, as I can go the full 273 columns for my 1080p monitor. If I go to 273x48 the issue is occurring.

I can repeat this behavior in Alacritty as well (window size height can be a bit bigger it seems), both in/out of Tmux. 

I tried setting `set lines=47` in my config, but this didn't seem to make a difference on a larger (i.e. full screen window). I suspect this is due to this value only being the initial size. 
 
I also toyed with disabling any window resizing options such as `shopt -s checkwinsize` in my .bashrc.

Based on the docs the "%ph" options appears to be one of those options you mentioned previously for graphics, not plain text. Are there any options to statically set View dimensions?


Below video is of my Lua configs for Neovim:

https://github.com/vifm/vifm/assets/7462046/a97402ba-33c9-4a3c-8276-3ee9b258dc20

**Comment by xaizek** [comment]
> Are there any options to statically set View dimensions?

Setting `'lines'` and `'columns'` options requests terminal to resize, but it doesn't have to.  In particular it might not leave full screen mode to reduce its size.

Maybe try building Vifm youself?  If it picks up `ncurses` from Homebrew, the issue might go away.  Then you can argue that Homebrew's formulae should add `ncurses` dependency.

**Comment by GNOMES** [comment]
Marking this as resolved!

I did not have time to perform additional testing, but I discovered this issue was resolved for me. Dug a bit and found this:

https://github.com/Homebrew/homebrew-core/issues/155252
