### ISSUE TITLE
Find using fd yields error

### ISSUE THREAD

**Issue by ixzh** [vifm/vifm#934]
Hi,

I have set ` set findprg='fd %a %s'` in vifmrc. yet when I do `:find jazz` it gives :

```
error: unexpected argument '-n' found
note: to pass '-n' as a value, use '-- -n' 
Usage: fd [OPTIONS] [pattern] [path]...  
For more information, try '--help'.
```
f I try `:find -tf` it will list all the files found by fd. Seems it recognizes fd options but not pattern.

How can I specify findprg to search for a pattern?

Thanks!

**Comment by xaizek** [comment]
Hello,

Try using `%A` instead of `%a`:
```vim
set findprg='fd %A %s'
```

When you do `:find jazz`, this will expand to `fd jazz` while `fd %a %s` expands to `fd -name jazz`.

**Comment by ixzh** [comment]
Works and thank you! I should read through the manual more carefully.
