### ISSUE TITLE
Command for moving between panes (wincmd)

### ISSUE THREAD

**Issue by fogine** [vifm/vifm#94]
Hello,
Could I ask if there's a way how to move programmatically between panes?
In vim you can achieve this by `:wincmd` command..

**Comment by xaizek** [comment]
Hi,

currently only through `:normal` command, I think. And it's not that easy because spaces are skipped, so it should be a crutch like this:

```
:nnoremap zzz <space>
:normal zzz
```

`:wincmd` would definitely be a better way of doing this, will add it, thanks.

**Comment by fogine** [comment]
I thank you for the information

**Comment by fogine** [comment]
Are there some specific variables available, so I could determine which pane I'm in and If `vifm` is `splited `or `vsplited`?

What I'm trying to achieve is to get working movement between both `tmux` and `vifm` panes with same mappings.
Explicitly:`<c-h>`, `<c-j>` , `<c-k>` , `<c-l>` 
So I could move from a vifm pane to adjacent tmux pane...

Thank you for support.

**Comment by xaizek** [comment]
> Are there some specific variables available, so I could determine which pane I'm in and If vifm is splited or vsplited?

Not yet, also can't think of any implicit way that would give you such information right now.
It's probably better to have this as a function (and there is also no builtin variables at the moment), something like `layoutis(type)`: `split` -> `0`/`1`, `hsplit` -> `0`/`1`, `vsplit` -> `0`/`1`, `only` -> `0`/`1`.  This should be more flexible than set of variables. Thanks, this will be useful in other contexts (e.g. automatic splitting on toggling `:view`).

**Comment by fogine** [comment]
Thank you @xaizek for implementing `wincmd` and `layoutis` logic.

if I may you suggest few improvements, wincmd doesn't return any response code if operation was successful (if active pane has been actually switched or if there was no pane to switch to).

I still miss command which would return currently active pane (top, bottom, left, right), would it be possible to implement?

**Comment by xaizek** [comment]
> if I may you suggest few improvements, wincmd doesn't return any response code if operation was successful (if active pane has been actually switched or if there was no pane to switch to).

Not sure about this, command-line commands do not return anything by design. Maybe this will be possible to do only via checking current state before running `:wincmd`.

> I still miss command which would return currently active pane (top, bottom, left, right), would it be possible to implement?

Oups, sorry, I didn't remember that part of your comment. Sure, I'll add another similar function to examine position of current pane (and maybe the other one, not sure yet). Do I get it right that for single-pane mode, it's fine if answers for questions like `top?`/`bottom?`/`left?`/`right?` on the current pane all yield `true`?

**Comment by fogine** [comment]
>Not sure about this, command-line commands do not return anything by design. Maybe this will be possible to do only via checking current state before running :wincmd

I understand the problem and I think it's not necessary to implement this if there will be a way how to find out which pane is active.

>Do I get it right that for single-pane mode, it's fine if answers for questions like top?/bottom?/left?/right? on the current pane all yield true?

I don't see a problem in this behavior... make quite sense. 
(as you implemented `layoutis('only')` so we can check this output too)

Thank you

**Comment by fogine** [comment]
>I'll add another similar function to examine position of current pane (and maybe the other one, not sure yet)

It's possible to have only two panes opened, right? If so, why are you thinking about it ?

**Comment by xaizek** [comment]
> It's possible to have only two panes opened, right? If so, why are you thinking about it ?

Yes, but if it will be general enough, one could use it to check state like in ... hm, it might be better to keep window position separate from its content, in this case state of current window will be enough.

I was just trying to foresee other possible use cases of functions to make sure that they are reusable.

**Comment by xaizek** [comment]
Added `paneisat()` function. Following logic for `only` layout, on vertical split both panes are also "at the top" and "at the bottom", on horizon split at left/right.

**Comment by fogine** [comment]
Thank you @xaizek  for fast implementation, I'll test it tomorrow.

**Comment by fogine** [comment]
Ok, everything seem working just perfect, without any issues.

**Comment by xaizek** [comment]
Glad to hear that, thanks for testing it out.
