### ISSUE TITLE
Bug: attempts to open a markdown file in the browser if it contains an HTML table

### ISSUE THREAD

**Issue by benelan** [vifm/vifm#941]
## Description

When a markdown file contains an HTML table (which is [supported by GFM](https://github.github.com/gfm/#html-blocks)), launching it with `l` or `Enter` attempts to open the file URI in your browser. The markdown file is correctly opened in your editor after deleting the HTML table and trying again.

## Reproduction

This issue is reproducible with the example `vifmrc`:
https://github.com/vifm/vifm/blob/master/data/vifmrc

It reproduces with this markdown file:

```md
# Browser Support

The following browsers are supported:

<table>
  <thead>
    <tr>
      <th><h4>Chrome</h4></th>
      <th><h4>Firefox</h4></th>
      <th><h4>Safari</h4></th>
      <th><h4>Edge</h4></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="4">Last 2 versions ✔ </td>
    </tr>
  </tbody>
</table>

```

I have `text/markdown=nvim.desktop` in `~/.config/mimeapps.list` under `[Default Applications]`, in case that's required for reproducing the issue.

I added the following to my `vifmrc` but it doesn't help:

```vim
filextype {*.md,*.mdx,*.ts,*.tsx},<text/*>
        \ {Open in EDITOR}
        \ $EDITOR %f,
fileviewer {*.md,*.mdx,*.ts,*.tsx},<text/*> $EDITOR %f

```

## Environment

The latest vifm version on `apt` is 0.12, but I didn't spot anything in the 0.13 changelog that looked related. Feel free to close this if I missed something and it's already fixed.

- Vifm:

    ```text
    Version: 0.12
    Git info: built out of repository

    Support of extended keys is on
    Parsing of .desktop files is enabled
    Without GTK+ library
    With magic library
    With X11 library
    With dynamic loading of X11 library
    With file program
    With -n option for cp and mv
    With remote command execution
    ```

- Shell: bash 5.1.16
- OS: Pop!\_OS 22.04 LTS x86_64
- Kernel: 6.4.6-76060406-generic
- Terminal: gnome-terminal

---

Let me know if you need any additional information. I love vifm, thanks for all your work!

**Comment by xaizek** [comment]
I think that you have `filetype <text/html>` handler somewhere above Markdown handler which takes over when mimetype is determined incorrectly for the file.  In general you can check contents of `:file` menu when cursor is over the file to see which commands will be attempted and in which order.

I tried it locally and `file --mime` just consider the file to be `text/html` when the table is there.  Vifm doesn't do mimetype detection on its own and uses either `file`, `libmagic` or `gdk` for that.  One can only adjust matchers to avoid the situation.  You can match for HTML files which don't have Markdown-extention like this `!{*.md}<text/html>` (it means "(NOT *.md) AND text/html"; for completeness: comma between matchers acts as OR operator).

**Comment by benelan** [comment]
Thanks for the quick reply! 

> I think that you have filetype <text/html> handler somewhere above Markdown handler which takes over when mimetype is determined incorrectly for the file. 

I actually do have the markdown handler first:
https://github.com/benelan/dotfiles/blob/master/.config/vifm/vifmrc#L203-L207

> One can only adjust matchers to avoid the situation. You can match for HTML files which don't have Markdown-extention like this !{*.md}<text/html> (it means "(NOT *.md) AND text/html"; for completeness: comma between matchers acts as OR operator).

This fixed the issue, thank you!

**Comment by xaizek** [comment]
> I actually do have the markdown handler first: https://github.com/benelan/dotfiles/blob/master/.config/vifm/vifmrc#L203-L207

Your
```vim
filextype {*.md,*.mdx,*.ts},<text/*>
        \ {Open in EDITOR}
        \ $EDITOR %f,
```
rule is never processed, hence the behaviour is as if the order is swapped.

Vifm doesn't recognize `$EDITOR` as an existing command and skips it (no `[present]` mark in `:file` menu).  It should probably expand environment variables in this case, thanks.

Also, `<text/html>` after `<text/*>` will never match anything unless `<text/*>` gets skipped like in this case, so you might want to fix that.

**Comment by benelan** [comment]
Ahh, yeah I was just wondering why the `<text/*>` handler wasn't catching all the text files but that makes sense. Appreciate the help!
