### ISSUE TITLE
Viewcolumns string literal and problem in space

### ISSUE THREAD

**Issue by chelovechishko** [vifm/vifm#942]
(sic!)
// yea, 'tis still me and viewcolumns after so many years

With [ Add literal values to 'viewcolumns' option. ](https://github.com/vifm/vifm/commit/55366508aa57aafbf7582d9012f2c1b82f127e10)
here is an example `3{#},{#|},{# | }` which includes `<space>` in the last one.

However, one can't simply put a `<space>` into there:
- nor `set viewcolumns=5.1{fileext},{# }`
- nor `{# | }` (directly from example)
- nor `[<space>]абвгд[<space>]` (i mean here only one `<space>` out of two variants)

while escaping: `{#' '}` or `{#\ }` works
- ...but not `{#\ |}`  (`{#' | '_}` works)

And for clarity, yes, i'm aware of `1{#}`.

**Comment by xaizek** [comment]
The example you're referring to was an example of syntax, not of usage in `set` command.  The simplest way is to escape the whole value:
```vim
set viewcolumns='5.1{fileext},{# }'
set viewcolumns="5.1{fileext},{# | }"
```
Backslash-escaping works as well, but you have to escape `|` too in this case:
```vim
set viewcolumns=5.1{fileext},{#\ \|}
```

**Comment by chelovechishko** [comment]
> The example you're referring to was an example of syntax, not of usage in set command

Oh, i see. Who would have known.
So-o-o, additional note about escaping for this bug closing?
Nevertheless, hope, you will close it by yourself.

**Comment by xaizek** [comment]
> Who would have known.

Well, it says:
 > The syntax is `{#literal}`, for example

But I'll update the docs to be more clear and consistent, thanks.
