### ISSUE TITLE
A file not shown in vifm left pane but can be found in right pane and using `ls` 

### ISSUE THREAD

**Issue by ixzh** [vifm/vifm#943]
I noticed this problem when uploading files to cloud using my Macbook. My files are inside folder 2, and I notice the vifm file count (lower right number) equals Finder folder file count.  So I select all files and export names to a `vifiles` inside vifm  and did a `diff vifiles <(ls 2)` from commandline:

```
288d287
< Nicolas Gombert - Motets - Beauty Farm (2015) [FLAC] {2CD Fra Bernardo FB 1504211} Artwork Tray Inside.jpg
289a289
> Nicolas Gombert - Motets - Beauty Farm (2015) [FLAC] {2CD Fra Bernardo FB 1504211} Artwork Tray Inside.jpg
854a855
> Verdi - The Great Operas (1995) (25 CD) - Brilliant Classics 01-02 - La traviata [Pretre, 1967] 1 21 Ne rispondi.flac
```

The result shows that the jpg  filename is treated as different in vifm and ls. For the flac file, it is simply not shown in vifm (I did a search for the word `rispondi` in vifm, with no result returned)

Wonder why this happens and how to resolve it.

**Comment by ixzh** [comment]
Seems it only happens on the left pane:

left pane:
<img width="896" alt="image" src="https://github.com/vifm/vifm/assets/14981695/f5c55ba5-bbac-4795-a2b3-d4b346d432fc">

right pane:
<img width="894" alt="image" src="https://github.com/vifm/vifm/assets/14981695/ddd5a586-822a-4488-913a-8c2b452fda32">

**Comment by xaizek** [comment]
You must have filtered it out.  Run `:filter?` to see active filters of the current pane.

You probably pressed <kbd>zf</kbd> by accident at some point.  If you don't have `:filter` in your `vifmrc` and `'vifminfo'` includes `state` such filtering will persist across restarts of Vifm until you use `:filter` command or a key like <kbd>zO</kbd> to reset it.

**Comment by ixzh** [comment]
yeah how stupid I am. I never use filters. `zO` or `zR` solved the problem thanks.
