### ISSUE TITLE
implement method to terminate a job created by vifm.startjob

### ISSUE THREAD

**Issue by dacyberduck** [vifm/vifm#944]
once a job is created, there is no suitable way to stop it on demand. It will be useful to have a method that will return the pid of the child process so that it can be terminated on demand.

**Comment by xaizek** [comment]
There is already "terminate job" function in C which just isn't exposed to Lua.  It has advantage or working on Windows the same way.  Can add a method to get PID as well for some other purpose (`:terminate()` will do `kill -9`).

**Comment by xaizek** [comment]
Also, https://github.com/vifm/vifm/commit/6b55b92b2b081e5aef6791ff2d7c8c4b73ca5578 added `VifmJob:pid()`.
