### ISSUE TITLE
Warnings reported by Infer

### ISSUE THREAD

**Issue by zpxue** [vifm/vifm#948]
1. bug_type: NULL_DEREFERENCE, qualifier: pointer `record` last assigned on line 1153 could be null and is dereferenced at line 1155, column 2. severity: ERROR, line: 1155, column: 16, procedure: put_file_id, procedure_start_line: 1150, file: vifm/src/compare.c.
2. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from nitems_res.is_valid was never initialized., severity: ERROR, line: 1618, column: 7, procedure: fentry_get_dir_info, procedure_start_line: 1594, file: vifm/src/filelist.c
3. bug_type: NULL_DEREFERENCE, qualifier: pointer `part` last assigned on line 2131 could be null and is dereferenced by call to `split_and_get()` at line 2142, column 16., severity: ERROR, line: 2142, column: 16, procedure: fillchars_handler, procedure_start_line: 2127, file: vifm/src/opt_handlers.c
4. bug_type: NULL_DEREFERENCE, qualifier: pointer `result.attrs` last assigned on line 142 could be null and is dereferenced by call to `strlen()` at line 143, column 3., severity: ERROR, line: 143, column: 3, procedure: split_and_print_status_line, procedure_start_line: 122, file:vifm/src/ui/statusline.c
5. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from result was never initialized., severity: ERROR, line: 884, column: 2, procedure: retry_wrapper, procedure_start_line: 814, file: vifm/src/io/iop.c

**Comment by xaizek** [comment]
Thanks, will take a look (some entries look like false positives).  Is this on `master` or v0.13 sources?

**Comment by zpxue** [comment]
Yes, they are on `master`.

**Comment by xaizek** [comment]
`#2` is a false positive.  Infer doesn't seem to undersand independent branches covered by the same condition.

`#5` is also a false positive.  The variable is always assigned at least once.

Fixed the other 3 which are about running out of memory.  This situation is not uniformly handled in the code.
