### ISSUE TITLE
[Question] A better way to cut/paste?

### ISSUE THREAD

**Issue by mohabmetwalli** [vifm/vifm#950]
I've been using Vifm for almost two years now, and I love it. My only problem is how cut [`dd`] and paste [`p`] works. Combined with multiple opened instances sharing the same trash directory made me lose files on multiple occasions. What usually happens is the following:

1. I start a cut/paste operation with `dd`/`p` from one Vifm instance.
2. I start a delete operation from a second instance.
3. Forgetting a paste operation is ongoing, I proceed to empty the trash directory from the second instance with `:empty`, losing any file that hasn't been pasted yet from the first operation.

I understand I could use `DD` to permanently delete files, or I can `yy` files and go back to `dd` the originals, but I feel deleting files to the trash directory, instead of permanently, is a good habit to keep, and how cutting/pasting is implemented feels kind of odd when the `mv` command exists.

Is there a better way to cut/paste files, or prevent multiple open instances from simultaneously manipulating the same trash directory?

**Comment by xaizek** [comment]
> I can `yy` files and go back to `dd` the originals

Sounds like you're looking for <kbd>P</kbd> key ([docs](https://vifm.info/vimdoc.shtml#vifm-P)) as mentioned by @infinitewhileloop.

**Comment by mohabmetwalli** [comment]
This is exactly what I was looking for. Thank you, all.
