### ISSUE TITLE
[Question] How do I explicitly feed Neovim "+filename" files through Vifm?

### ISSUE THREAD

**Issue by mohabmetwalli** [vifm/vifm#951]
To open `*.ts` files in _Neovim_, I have the following line in my _Vifm_ config:

```
filetype *.ts nvim %f
```

Some _Svelte_ files begin with `+` which _Neovim_'s CLI understands as command, not filename. To overcome this using _Vifm_'s command line, I can execute:

```
:!nvim -- +page.server.ts
```

And it works; however, the following, in _Vifm_'s config, doesn't work:

```
filetype *.ts nvim -- %f
```

_Neovim_ still parses `+page.server.ts` as a command when I press `o`, `i`, or `l` in _Vifm_.

Is there any way I can get it to work so that I don't have to run the `:!nvim` command every time?

**Comment by xaizek** [comment]
Sounds like .ts-files aren't handled by your configuration the way you think.  Try running `:filetype test.ts` and see whether there is `[present]` marker on the same line with `nvim -- %f` and whether it's the first line in the list, otherwise something else (in top-down) order is being run.

**Comment by mohabmetwalli** [comment]
You're right, thank you.

I had the following line placed above `filetype *.ts nvim -- %f` in my config:

```
filetype <text/*> nvim
```

Once I reversed the order, it worked as intended.
