### ISSUE TITLE
slow media preview

### ISSUE THREAD

**Issue by aabbccddeeffggj** [vifm/vifm#954]
Hi, I'm using vifmimg (the image/pdf/etc preview script), but for some reason it gets extremely slow when scrolling through a list of images/videos.
I set "set previewoptions+=graphicsdelay:0" and it made things considerably faster, but still remains of it slowing down the scrolling.
In lf this issue doesn't occur, is anyone else having this problem? I think the issue is it trying to load the files entirely before letting me go to the next file, or something like that.

**Comment by xaizek** [comment]
Hi,

`vifmimg` does some processing before requesting Ueberzug to draw the result and Vifm waits for graphical previewers. You can try working around it by adding `&` after preview commands, but this will likely hide any textual output you might get from `vifmimg` like error message.

**Comment by aabbccddeeffggj** [comment]
I see, maybe there could be an optimization in the media preview mechanism someday, like the image previewer half loading (way less than half actually) the previews when scrolling through a list of files is detected.
I'll see if I can do something about it myself in the near future.

**Comment by xaizek** [comment]
> I see, maybe there could be an optimization in the media preview mechanism someday, like the image previewer half loading (way less than half actually) the previews when scrolling through a list of files is detected.

Doesn't sound doable, scrolling is just a subcase of navigation, so you can't really tell them apart.  If you scroll by <kbd>j</kbd> and <kbd>k</kbd> consider using <kbd>Ctrl-e</kbd>/<kbd>Ctrl-y</kbd>/<kbd>Ctrl-f</kbd>/<kbd>Ctrl-b</kbd>/<kbd>Ctrl-u</kbd>/<kbd>Ctrl-d</kbd>/<kbd>H</kbd>/<kbd>M</kbd>/<kbd>L</kbd>/<kbd>zb</kbd>/<kbd>zz</kbd>/<kbd>zt</kbd>, which are generally more optimal.

In my previous comment I meant doing something like this:
```vim
fileviewer <video/*>
         \ vifmimg video %px %py %pw %ph %c &
         \ %pc
         \ vifmimg clear

fileviewer <image/*>
         \ vifmimg draw %px %py %pw %ph %c &
         \ %pc
         \ vifmimg clear
```

However, images don't have any preprocessing in `vifmimg`, so if you experience slowdown for file lists that include nothing but images that's weird.

**Comment by aabbccddeeffggj** [comment]
> In my previous comment I meant doing something like this:
I had done it, but didn't work,  at least no visible difference.
I tested it again, now in another directory, and seems like the root cause is the video previews.

**Comment by xaizek** [comment]
Try like this (added `&>/dev/null` which is the same as `>/dev/null 2>/dev/null`):
```vim
fileviewer <video/*>
         \ vifmimg video %px %py %pw %ph %c &>/dev/null &
         \ %pc
         \ vifmimg clear
```
Seems to get rid of the delay.

https://github.com/thimc/vifmimg/pull/51 should also help with responsiveness.

**Comment by aabbccddeeffggj** [comment]
> Try like this (added `&>/dev/null` which is the same as `>/dev/null 2>/dev/null`):
> 
> ```viml
> fileviewer <video/*>
>          \ vifmimg video %px %py %pw %ph %c &>/dev/null &
>          \ %pc
>          \ vifmimg clear
> ```
> 
> Seems to get rid of the delay.
> 
> [thimc/vifmimg#51](https://github.com/thimc/vifmimg/pull/51) should also help with responsiveness.

It worked now, thanks.

**Comment by hholst80** [comment]
Thank you guys! This issue solved my problem completely.
