### ISSUE TITLE
Cannot get bat to work as previewer

### ISSUE THREAD

**Issue by aabbccddeeffggj** [vifm/vifm#957]
Hi, once again. 

I tried using `bat` to preview text files, but it seems to not work:
`fileviewer <pattern> bat %c`

When I use it to preview directories it does work, but since it is not intended to read directories it gives an error, but this error comes with the preview highlighted, which implies it's working inside vifm.

When I use `bat` to preview actual files, it goes as if I'm using `cat` to do it so, the preview (when I don't set `fileviewer`) works just like `cat`, so I think what is happening is just `bat` not working.

I have checked other issues, but couldn't find anything to solve my problem.

Thanks.

**Comment by xaizek** [comment]
Hi,

Check that `[present]` appears next to `bat %c` in the `:fileviewer file-name-matching-your-pattern` menu and that's it's on the first line or the first handler which is present.

**Comment by aabbccddeeffggj** [comment]
turns out it's working now, though I'm not sure what I did different after some days.
