### ISSUE TITLE
Image preview problem

### ISSUE THREAD

**Issue by bazuchan** [vifm/vifm#959]
I'm trying setup image preview with https://github.com/atanunq/viu
Viu works fine in terminal, but images get garbled in vifm preview mode.

plain terminal:
<img width="837" alt="terminal" src="https://github.com/vifm/vifm/assets/4991018/fd75ae87-11d1-4a38-b85a-57a929dfa717">

vifm:
<img width="789" alt="vifm" src="https://github.com/vifm/vifm/assets/4991018/6de90596-e5d4-4d7a-be84-105ffa9c1a87">

d.txt is made with same size as my vifm preview area:
[d.txt](https://github.com/vifm/vifm/files/13413316/d.txt)

**Comment by xaizek** [comment]
I can view `d.txt` file fine in Vifm from `master` and in v0.13.  The issue might be related to #907 unless you're seeing it right on the start with just one image.

Can you post bottom half of `:version` menu with terminal information?  There might be too few color pairs.

**Comment by bazuchan** [comment]
> in v0.13.
I'm using 0.13 on OSX Sonoma with Alacritty or built-in terminal app.

> right on the start with just one image.
Yes, right from the start and 100% reproducible

> Can you post bottom half of `:version` menu with terminal information? There might be too few color pairs.
```
│ Terminal name: screen-256color                                                                                                                                                           │
│ Max colors: 256                                                                                                                                                                          │
│ Max color pairs: 256                                                                                                                                                                     │
│ Extended colors: missing                                                                                                                                                                 │
│ RGB: -1                                                                                                                                                                                  │
│ Direct color: no                                                                                                                                                                         │
│                                                                                                                                                                                          │
│ Preview cache size: 116 K                                                                                                                                                                │
```

**Comment by xaizek** [comment]
> Max colors: 256
> Max color pairs: 256

Normally, 256 colors come with 32768 or 65536 color pairs.  Try running outside of `screen` and see whether the issue appears when you have larger number of color pairs (`tput pairs` on command-line also shows their count).

**Comment by bazuchan** [comment]
Outside of tmux in built-in OSX terminal I have same problem:

```
| Terminal name: xterm-256color                                                                                                                                                                                      
│
│ Max colors: 256                                                                                                                                                                                                    │
│ Max color pairs: 256                                                                                                                                                                                               │
│ Extended colors: missing                                                                                                                                                                                           │
│ RGB: -1                                                                                                                                                                                                            │
│ Direct color: no                                                                                                                                                                                                   │
│                                                                                                                                                                                                                    │
│ Preview cache size: 594 K                                                                                                                                                                                          │
│
```

**Comment by bazuchan** [comment]
Btw, `tput pairs` outputs 32767 in both terminal and alacritty

**Comment by xaizek** [comment]
> Btw, `tput pairs` outputs 32767 in both terminal and alacritty

That's weird.  How did you install Vifm?

**Comment by bazuchan** [comment]
> > Btw, `tput pairs` outputs 32767 in both terminal and alacritty
> 
> That's weird. How did you install Vifm?

from homebrew

**Comment by xaizek** [comment]
To exclude some environment variable interferring with curses/terminfo, please try running Vifm like this:
```
env -i - TERM="$TERM" HOME="$HOME" LANG="$LANG" vifm
```
If that doesn't help, the issue could be a regression of curses on OS X Sonoma.

**Comment by bazuchan** [comment]
> ```
> env -i - TERM="$TERM" HOME="$HOME" LANG="$LANG" vifm
> ```
Same problem.

**Comment by bazuchan** [comment]
Compiling against non-system ncurses solves problem

**Comment by xaizek** [comment]
> Compiling against non-system ncurses solves problem

Maybe report this to https://github.com/Homebrew/homebrew-core/issues as an argument for not using system-provided curses.

**Comment by bazuchan** [comment]
Reported
