### ISSUE TITLE
Merge creates duplicate subfolders

### ISSUE THREAD

**Issue by willemw12** [vifm/vifm#96]
When merging folders (feature https://github.com/vifm/vifm/issues/51), vifm does not always merge subfolders. Instead, it creates a duplicate subfolder in the subfolder with the same name.

Vifm 0.7.8, "syscalls" is not set.

Example: merge folder 'b'

```
$ mkdir -p A/b/c ; touch A/b/c/{1,2}                                                                                   
$ mkdir -p B/b/c ; touch B/b/c/3                                                                                       
$ tree A
A
└── b
    └── c
        ├── 1
        └── 2
$ tree B                        
B
└── b
    └── c
        └── 3
```
In vifm, merge folder B/b into folder A: navigate to B, focus on b, enter "yy", navigate to A, enter "P", enter "M".

```
$ tree A
A
└── b
    └── c
        ├── 1
        ├── 2
        └── c
            └── 3
```
There are now two folders "c". Expected:

```
$ tree A
A
└── b
    └── c
        ├── 1
        ├── 2
        └── 3
```

Have not checked other merge options.

**Comment by xaizek** [comment]
Right, nesting wasn't handled, don't know why I didn't notice this obvious (from code) limitation.

Already have a fix, which will be part of 0.8. Will write tests and close this.

Thanks!
