### ISSUE TITLE
Two minor problems I'm having.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [vifm/vifm#961]
Hi, again. Firstly, I would like to thank you for helping me with these issues, you're a gentle guy.

There're two problems I couldn't solve myself:

01) I defined a symbol to be displayed right before the names of executable files (classify='symbol :exe:') but others symbols matching specific patterns surpress the "executable symbol".
Example: There's a executable file named "abcd", the name of this file displayed in vifm is indeed prefixed with the executable character I assigned to executable files, but once I change the name from "abcd" to "abcd.c", the symbol changes to the one I assigned to "*.c" files.
Could you tell me if there's a way to make the "executable symbol" have the highest priority over the other patterns.

02) The other "problem" is associated with the status bar:
![image](https://github.com/vifm/vifm/assets/133555950/77243396-a9bb-4cff-ba4f-02eebe9f9dcc)
I was wondering if I can switch the cmdline and the statusbar places, or do something else, because a great part of the image previews invades the statusbar, which disturbs me a bit.

edit: I'm using this in my vifmrc:
```
set millerview
set milleroptions+=lsize:1,csize:2,rsize:3,rpreview:all
```

**Comment by xaizek** [comment]
Hello,

> Could you tell me if there's a way to make the "executable symbol" have the highest priority over the other patterns.

There isn't. Not sure whether it's documented, but name-based decoration has higher priority and type-based one is used only if name isn't matched agains any of the patterns.  Maybe relative position of patterns in `'classify'` should be taken into account to make this configurable.

> I was wondering if I can switch the cmdline and the statusbar places, or do something else, because a great part of the image previews invades the statusbar, which disturbs me a bit.

No option for swapping them, but this overlap shouldn't happen if previewer that you use computes placement and dimentions of the picture correctly.  Maybe it assumes that terminal has some margin which isn't actually there or just doesn't scale things  properly to fit into available space.
