### ISSUE TITLE
Using fzf on vifm

### ISSUE THREAD

**Issue by aabbccddeeffggj** [vifm/vifm#963]
Hi, by now I opened a lot of issues, sorry for the inconvenience, in case it is bothering you.

I checked [How to integrate fzf for fuzzy finding](https://wiki.vifm.info/index.php/How_to_integrate_fzf_for_fuzzy_finding).

It is said the following:
>fzf will pop up on the bottom and allow us to filter the output of the feeder command. To prevent artifacts, vifm's previews are switched off

I used the examples provided and the fuzzy finder opened in the terminal interface while hiding the vifm one; by reading the phrase I cited above, I suppose that the command would display right inside vifm (like a terminal window inside it), but it hides the vifm "window" and shows the terminal emulator prompt instead.

I'm not sure if I interpreted the wiki phrase wrongly and thus what I'm experiencing is the expected behavior or if there's something off with my vifm.

Thanks.

**Comment by xaizek** [comment]
> Hi, by now I opened a lot of issues, sorry for the inconvenience, in case it is bothering you.

Hi. If it's a usage-related question like this one, https://q2a.vifm.info/ is a more suitable place.

Hard to talk about this without screenshots.  Here's how it looks in `tmux` (bottom split is opened):
![vifm-fzf-tmux](https://github.com/vifm/vifm/assets/459736/e52faab0-a9a9-4fc3-97f2-1431abfb0e50)
And without `tmux`, UI is displaced like this:
![vifm-fzf-notmux](https://github.com/vifm/vifm/assets/459736/cd15b1ae-d211-460b-8b06-e0a4b0abea1b)

Does it look different for you?

**Comment by aabbccddeeffggj** [comment]
I see, next time I will acess https://q2a.vifm.info/

> Does it look different for you?

Yes, when I use the command, the vifm interface gets hidden and the fzf appears in the terminal prompt; here's a screenshot:
![image](https://github.com/vifm/vifm/assets/133555950/314b98fa-b827-4598-aa4b-27bc4f768ebb)

I used the command provided in the wiki page I mentioned above:
```
command! FZFlocate : set noquickview
                  \| let $FZF_PICK = term('find $HOME | fzf --height 10 2>/dev/tty')
                  \| if $FZF_PICK != ''
                  \|     execute system('[ -f "$FZF_PICK" ] && echo goto || echo cd') fnameescape($FZF_PICK)
                  \| endif
```

Maybe my command is not right, could you share yours?

**Comment by xaizek** [comment]
If you use `tmux` replace `fzf` with `fzf-tmux`.

That sentence was there before `system()` was replaced with `term()` in the command and describes how it used to work.  `term()` is a better choice (`system()` also needs `\| redraw` at the end) as Vifm's UI is not functional while `fzf` is open anyway and it's better to not share a terminal between multiple applications: `term()` turns off UI befor calling `fzf` and enables it back afterwards.

**Comment by aabbccddeeffggj** [comment]
I see, understood.
Thanks.
