### ISSUE TITLE
"open with" as popup

### ISSUE THREAD

**Issue by amigthea** [vifm/vifm#964]
it could be possible to choose the filextype program to be used with a matching file from an interactive popup? Right now the first entry configured is used, but I would like to bind a custom vifm shortcut to a command that let me choose those multiple entries from a vifm popup

**Comment by xaizek** [comment]
Have you seen [`:file` command](https://vifm.info/vimdoc.shtml#vifm-%3Afile)?  Without arguments it opens a menu from which you can pick a handler.

**Comment by xaizek** [comment]
I take it this is resolved.  Feel free to comment/reopen if not.

**Comment by amigthea** [comment]
I was thinking, instead of hardcoding multiple filextype program, could be possible to have a main program and a second entry where the program name is a placeholder code that ask the user for input, waiting for the program name he want to open the files with?
Doing so element are opened by default with the main program and in every other scenario it would ask the user for the program name.

**Comment by xaizek** [comment]
You can do
```vim
nnoremap ,p :execute '!'.input('Command: ') '%c'<cr>
```
or (for completion because `input` doesn't complete from `$PATH`):
```vim
nnoremap ,p :! %c<c-a><c-f>
```

It wouldn't integrate well into `filextype` given that it's not just program name, but possibly some program-dependent arguments.

**Comment by amigthea** [comment]
> ```viml
> nnoremap ,p :! %c<c-a><c-f>
> ```

that's perfect! thank you
would it support multi selection? or do I need some kind of loop cycle?
with a more complex command, there's a way to put the vifm command line cursor at the Nth line position (and not just after !) ?

**Comment by xaizek** [comment]
> would it support multi selection? or do I need some kind of loop cycle?

Just replace `%c` with `%f`.

> with a more complex command, there's a way to put the vifm command line cursor at the Nth line position (and not just after !) ?

There is no key to go to Nth column, but you can move by words with `<a-f>`/`<a-b>`.

**Comment by amigthea** [comment]
I'm trying to work on a command bind that use kde enviroment to let the user choose the applications to open files with. Until now I came up with this

`nnoremap gb :!su -c "$(zenity --list --text='Open with' --column='Applications' rhythmbox vlc mpv) %f" john &<cr>`

but I don't know how to go further and completing this replacing the hardcoded `rhythmbox vlc mpv` part. I tried unsuccessfully to come up with a command substitution that fetch the file mimetype and search for all installed executables that can open the mimetype, like

`nnoremap gb :!su -c "$(zenity --list --text='Open with' --column='Applications' $(grep -E "audio/mpeg=|audio/x-mp3=" ~/.config/mimeapps.list | ) %f" john &<cr>`

but it's an ugly wip, it's missing all the `/usr/share/applications/*.desktop` parsing and the quotes escaping is messed up. Am I spaghetting myself? Could be there another simpler way to achieve this?

**Comment by xaizek** [comment]
> Could be there another simpler way to achieve this?

I only see `gio mime image/png` for viewing list of handlers, but it's not very useful (just names of files without paths to them), other tools seem to only query default handler or just run it.

Vifm could provide list of commands, but it wasn't exposed to Lua API yet.

You either need to find a suitable tool or write a parser youself (maybe in AWK).

> altought the hardcoded command works, it spits out background errors on vifm, maybe because I didn't send the process in background correctly (with &)?

You can use `%i` to run in background silently.

**Comment by amigthea** [comment]
> You can use `%i` to run in background silently.

lovely!

> I only see `gio mime image/png` for viewing list of handlers, but it's not very useful (just names of files without paths to them), other tools seem to only query default handler or just run it.

sadly it's what I've faced

> Vifm could provide list of commands, but it wasn't exposed to Lua API yet.

can you please elaborate how Lua API could be useful? I'm just trying to wrap my head around something I'm new to
 
> You either need to find a suitable tool or write a parser youself (maybe in AWK).

I'll try to go down that route, thank you!

**Comment by xaizek** [comment]
> can you please elaborate how Lua API could be useful? I'm just trying to wrap my head around something I'm new to

You could handle <kbd>gb</kbd> in Lua, query handlers (if there was an appropriate API), then format and run an external command.

**Comment by amigthea** [comment]
I got a working snippet! I think it could be achieved with a better syntax but I'm so glad i got it working, leave it here:

```
nnoremap gb :!
  \  filetype="$(xdg-mime query filetype %f)";
  \  applist=($(grep -l "$filetype" /usr/share/applications/*));
  \  appcmd=($(for app in $applist; do cat "$app" | awk -F '=' '/^Exec=/ {split($2, a, " "); print a[1]}'; done | sort -u));
  \  openapp=$(zenity --list --title='Open with' --column='Applications' --ok-label='Open' --height=350 "${appcmd[@]}");
  \  "$openapp" %f %i<cr>
```

Could it be possible to replicate that in vifm with a popup somehow?

**Comment by xaizek** [comment]
Don't see any significant improvements to make to your commands.

> Could it be possible to replicate that in vifm with a popup somehow?

What you don't like about `:file` menu in this regard?  It should display essentially the same list unless your Vifm is built without support of .desktop-files.

**Comment by amigthea** [comment]
Didn't know that, I installed it through arch repository and right now `:file` shows me only what's configured in vifmrc

**Comment by amigthea** [comment]
how could I remap `:file` to `gn` while opening selection as another user?

**Comment by xaizek** [comment]
It should be a menu mapping that puts menu item into the command-line with <kbd>c</kbd> key and then edits and runs it:
```vim
mnoremap <silent> gn c<c-a><c-f>su -c "$(printf %%q <c-e>)" john &<cr>
```

**Comment by amigthea** [comment]
that's a clever solution from a logic standpoint but that code do not seems to sort any effect nor errors, and I don't know how to fix it (tried and failed)

**Comment by xaizek** [comment]
Remove `<cr>` (and maybe `<silent>`) from the mapping to see the command/try to edit it.

**Comment by amigthea** [comment]
already tried that to no avail, it does not even appear in the command help (after pressing g before n)

**Comment by amigthea** [comment]
that was indeed the culprit, my bad.
I managed to get a working version like this
```
nnoremap gn :file<cr>
mnoremap <silent> gn c<c-a><c-f>su -c "<c-e>" john &<cr>
```
I don't know why but the `printf %%q` command substitution part was failing to execute the application. Why could that be?

Meanwhile I was able to improve the zenity snippet too, now it shows the application name correctly
```
nnoremap gb :!
  \  filetype="$(xdg-mime query filetype %f)";
  \  applist=($(grep -l "$filetype" /usr/share/applications/*.desktop));
  \  for appfile in $applist; do appname+=("$(cat "$appfile" | grep -oP "(?<=^Name=).*")"); done;
  \  for appfile in $applist; do appcmd+=("$(cat "$appfile" | grep -oP "(?<=^Exec=).*")"); done;
  \  app=(${appname:^appcmd}); sort;
  \  openapp=$(zenity --list --title="Open with" --ok-label="Open" --height=350 --column="Applications" --column="command" --hide-column=2 --print-column=2 "${app[@]}");
  \  $openapp %f %i<cr>
```

**Comment by xaizek** [comment]
I think if it expands to something like this
```
!su -c "$(printf %%q app %f &)" john
```
The `&` ends up affecting `printf`.
