### ISSUE TITLE
How to compare two files

### ISSUE THREAD

**Issue by jirka-h** [vifm/vifm#966]
Hello,

is there a convenient way how to compare two files? I'm aware of `compare` command to compare two directories. Is there a similar feature to compare two files, like "C-x C-d" in Midnight Commander? I think it would be beautiful to integrate it with `vimdiff` if this binary is available. 

Thanks a lot!
Jirka

**Comment by xaizek** [comment]
Hello,

There isn't anything builtin for that.  I'm not sure it's actually needed given that Vim handles it well:
```vim
command! diff vim -d %f %F
```
This is in sample `vifmrc`, so you might already have the command.

**Comment by jirka-h** [comment]
Thanks for the quick answer! 

You are right, it works wit the default `vifmrc`. Simply selecting files
```
"  %f for selected file(s)
"  %F for selected file(s) of inactive pane
```
and executing `:diff` does the trick. Very cool. Thank you!
