### ISSUE TITLE
set classify ignores name matching for the dirs

### ISSUE THREAD

**Issue by halturin** [vifm/vifm#968]
According to https://vifm.info/vimdoc.shtml#vifm-%27classify%27

"_file name patterns have priority over type patterns_", 

here is my config:
![image](https://github.com/vifm/vifm/assets/118860/2fe50cef-93bb-4db2-b641-64aa0ee9f004)

I'm expecting to see a custom icon for the `.git` directory. seems the second line is ignored. 
but works for a file with the name `.git` :)

basically, my idea is to use different icons for the specific set of directories.

**Comment by xaizek** [comment]
I think it's not stated explicitly, but the matching in `'classify'` is done the same as in other places (search, filters, `:file[x]type`, `:fileviewer`): directory names get a trailing slash to be able to differentiate between files and directories.  So you want to do something like this (also handles bare repositories):
```
    set classify+=' ::.git/,,*.git/::/'
```
