### ISSUE TITLE
Make Vifm work as Helix's file manager

### ISSUE THREAD

**Issue by mahor1221** [vifm/vifm#969]
For a long time, I've wanted to use Vifm as the project's file manager/tree viewer for Helix. Today, I've finally achieved this with the help of Tmux. It took me the entire day, but it was worth it, and I'm in love with the results!

However, there is a small issue that, once resolved, would make it perfect.

As you can see in the video, I can only open files that are inside Helix's working directory (It works fine in tree mode).

https://github.com/vifm/vifm/assets/73415437/a1608d7b-f6b3-49fe-8acc-6f7d32f380b4

The simplest fix I can think of is passing the full path to Helix, but I couldn't find how to do it.

## Details
This setup works with a combination of configs, scripts, and the new `helix-tmux.lua` plugin. It functions similarly to the `helix.lua` plugin but sends commands to a Helix instance inside Tmux instead of calling Helix directly.

```lua
-- helix-tmux.lua

M.handlers["edit-many"] = function(info)
  local id = "$(tmux display -p '#S')"
  local exitcode = vifm.run {
    cmd = string.format("tmux send-keys -t %s:editor.1 ':open %s' Enter",
      id, table.concat(map(info.paths, vifm.escape), ' '))
  }

  return exitcode == 0
end
```

I believe that if there were a way to convert `info.paths` to full paths, this issue would be resolved.

**Comment by xaizek** [comment]
Try this:
```lua
local function prepare_path(path)
  -- turn to full path and escape it for pasting into a shell command
  return vifm.escape(vifm.fnamemodify(path, ':p'))
end

M.handlers["edit-many"] = function(info)
  local id = "$(tmux display -p '#S')"
  local job = vifm.startjob {
    cmd = string.format("tmux send-keys -t %s:editor.1 ':open %s' Enter",
      id, table.concat(map(info.paths, prepare_path), ' '))
  }

  return job:exitcode == 0
end
```

I've also used `vifm.startjob()` instead of `vifm.run()` which should get rid of screen flickering when you open files because UI won't be shut down while external command is running.

**Comment by mahor1221** [comment]
Thanks! It's working flawlessly.

I've tried `vifm.startjob()` but it didn't run correctly:

![2023-12-18_07-50-52](https://github.com/vifm/vifm/assets/73415437/13f0fab5-c988-44ec-9779-4667b3c224f0)

I think the screen flickering problem you are seeing in the video is because of Helix's auto-completion pop-ups. Vifm is running smoothly.

**Comment by mahor1221** [comment]
For testing purposes, I changed `return job:exitcode == 0` to `return true`, and now `vifm.startjob()` works, and the flickering issue is gone. Great!

So, for the same command, `vifm.run()` with `return exitcode == 0` works, while `vifm.startjob()` with `return job:exitcode == 0` doesn't. I assume `job:exitcode` is incorrect, but I can't figure out why.

<details>
  <summary>helix-tmux.lua</summary>
  
```lua
--[[

Allows using Vifm as an IDE-like file-manager/file-tree for Helix

Unimplemented actions:
 * open-help (:help when 'vimhelp' is set):
 * edit-list ("v" key in navigation menus):

--]]

local M = {}

M.handlers = {}

M.handlers["open-help"] = function(info)
  vifm.errordialog("Unimplemented",
    "Can't view Vim-style help via Helix.\n" ..
    "Do `:set novimhelp` to make argumentless `:help` work.")
  return false
end

local function prepare_path(path)
  -- turn to full path and escape it for pasting into a shell command
  return vifm.escape(vifm.fnamemodify(path, ':p'))
end

M.handlers["edit-one"] = function(info)
  local posarg = ""
  if info.line ~= nil and info.column == nil then
    posarg = ':' .. info.line
  elseif info.line ~= nil and info.column ~= nil then
    posarg = string.format(":%d:%d", info.line, info.column)
  end

  local tmux_session_id = "$(tmux display -p '#S')"
  local job = vifm.startjob {
    cmd = string.format("tmux send-keys -t %s:editor.1 ':open %s%s' Enter",
      tmux_session_id, prepare_path(info.path), posarg),
    usetermmux = not info.mustwait,
  }

  return job:exitcode == 0
end

function map(table, functor)
  local result = {}
  for key, value in pairs(table) do
    result[key] = functor(value)
  end
  return result
end

M.handlers["edit-many"] = function(info)
  local tmux_session_id = "$(tmux display -p '#S')"
  local exitcode = vifm.startjob {
    cmd = string.format("tmux send-keys -t %s:editor.1 ':open %s' Enter",
      tmux_session_id, table.concat(map(info.paths, prepare_path), ' '))
  }

  return job:exitcode == 0
end

M.handlers["edit-list"] = function(info)
  vifm.errordialog("Unimplemented", "Can't view quickfix via Helix.")
  return false
end

return M
```

</details>

**Comment by xaizek** [comment]
I forgot parenthesis, should be:
```lua
  return job:exitcode() == 0
```
