### ISSUE TITLE
Create directories and files with a single command

### ISSUE THREAD

**Issue by mahor1221** [vifm/vifm#972]
I just wanted to share this command:

```vimscript
command create :
\|  let $last_char = expand(system("str=\"%a\"; echo \"${str: -1}\""))
\|  if $last_char == "/"
\|    mkdir "%a"
\|  else
\|    touch "%a"
\|  endif

nnoremap a :create<space>
```

Usage:
`:create test_file` will create a file named `test_file`
`:create test_dir/` will create a directory named `test_dir`

**Comment by haolian9** [comment]
thanks for sharing this! your code inspired and encouraged me to write a lua version (with some differences):

```
vifm.cmds.add({
  name = "new",
  description = "mkdir -p && touch",
  minargs = 1,
  maxargs = -1,
  handler = function(info)
    for _, path in ipairs(info.argv) do
      local dir = string.match(path, ".+/")
      if dir then assert(vifm.makepath(dir)) end
      if not (dir and #dir == #path) then assert(io.open(path, "a")):close() end
    end
  end,
})
```
it can be used like `:new a b/c/d e/f/`

(though i'm afraid such things can be an abuse of vifm issues)

**Comment by mahor1221** [comment]
Great! I've created this plugin based on your code and the `hello` plugin:

```lua
-- path: ~/.config/vifm/plugins/new-command/init.lua

--[[

Provides :new command

Usage examples:
    - Create a new file named test_file
        :new test_file
    - Create a new directory named test_dir
        :new test_dir/
    - Create multiple new files and directories
        :new a b/c/d e/f/

--]]

local M = {}

local function new(info)
    for _, path in ipairs(info.argv) do
      local dir = string.match(path, ".+/")
      if dir then assert(vifm.makepath(dir)) end
      if not (dir and #dir == #path) then assert(io.open(path, "a")):close() end
    end
end

-- this does NOT overwrite pre-existing user command
local added = vifm.cmds.add({
    name = "new",
    description = "create files and directories",
    minargs = 1,
    maxargs = -1,
    handler = new
})

if not added then
    vifm.sb.error("Failed to register :new")
end

return M
```

It works as intended. However, I am unable to undo or redo the changes unlike the `:create` command. If this functionality could be added to the `:new` command, it would be perfect.

> (though i'm afraid such things can be an abuse of vifm issues)

I totally agree. I usually share this kind of content on the project's Reddit, Discord, etc., but I couldn't find any specific channel for Vifm. This "issue" can be closed if there's nothing else to add.

**Comment by xaizek** [comment]
> It works as intended. However, I am unable to undo or redo the changes unlike the `:create` command. If this functionality could be added to the `:new` command, it would be perfect.

It needs #881 and then some.

> I totally agree. I usually share this kind of content on the project's Reddit, Discord, etc., but I couldn't find any specific channel for Vifm.

There is [Wiki](https://wiki.vifm.info/index.php/Main_Page).

**Comment by xaizek** [comment]
And now somebody created [r/vifm](https://www.reddit.com/r/vifm/).

**Comment by mahor1221** [comment]
Nice, I'll post there then.

I've also wanted to update the wiki but my account is auto banned due to inactivity.
