### ISSUE TITLE
cmds added via `vifm.cmds.add` are not visible to `:command {name}`

### ISSUE THREAD

**Issue by haolian9** [vifm/vifm#973]
hi, i found that cmds added by `vifm.cmds.add` are not visible to `:command {cmd}`.

to reproduce:
* `vifm.cmds.add({ name = "hello", description = "hello", handler = function() vifm.sb.info("hello!") end })`
* `:command` # the hello command can be seen in the output
* `:command hello` # while this says `No user-defined commands found`

after read some code, i learnt that `vifm.cmds.add` adds `FOREIGN_CMD`, `:command {cmd}` recognizes `USER_CMD` only, and returns the `cmd_t->cmd`. regarding to the output of `:command`, it treats FOREIGN_CMD as user defined commands already, so i think it'd be better to make `:command {cmd}` be aware of FOREIGN_CMD to be more consistent.

if the above support can be added, then what should be showed for `FOREIGN_CMD`s?
* `cmd_t->description` gives less infomation than `cmd_t->cmd`
* `cmd_t->handler` gives no info

**Comment by xaizek** [comment]
Hello,

Thanks for finding the bug.

> i think it'd be better to make `:command {cmd}` be aware of FOREIGN_CMD to be more consistent.

Yes.  I remember making  `:command` work, but apparently forgot to update `:command prefix` at the same time.

> if the above support can be added, then what should be showed for `FOREIGN_CMD`s?

Description.
