### ISSUE TITLE
Update `config.{guess,sub}` to build on new architectures like RISCV64

### ISSUE THREAD

**Issue by phanen** [vifm/vifm#974]
Currently, build on RISCV64 failed due to outdated `config.{guess,sub}`:
```
config.guess timestamp = 2013-04-24

uname -m = riscv64
uname -r = 6.6.4-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Mon, 04 Dec 2023 00:29:19 +0000

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              =
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = riscv64
UNAME_RELEASE = 6.6.4-arch1-1
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP PREEMPT_DYNAMIC Mon, 04 Dec 2023 00:29:19 +0000
configure: error: cannot guess build type; you must specify one
```
Consider updating them using latest autotools?

**Comment by xaizek** [comment]
Thanks, I didn't notice that.  I don't know if using latest versions of those files with older autoconf/automake stuff is a good idea, but I can definitely take them from `automake-1.16` with `timestamp='2020-01-01'`.

**Comment by phanen** [comment]
That would be sufficient. I build it again sucessfully with `timestamp=2018-03-08` on RISC-V and it works fine. 
Thanks a lot for your great work on this software. :)
