### ISSUE TITLE
Can't create a shortcut for <C-S-f1> and F13+ keys

### ISSUE THREAD

**Issue by MikeLemo1** [vifm/vifm#978]
I'm using the extra F12+ keys that are initiates with a combination of ctrl, shift and alt key with the regular F1-12 keys

My problem is that when mapping <C-S-f1> vifm doesn't work correctly with the shift (it does with combination ctrl+f keys without the ctrl+shift)

Any idea how to fix that and allow vifm to recognize F13+ keys is config file  like in nvim ? 
'<F25>' etc...

**Comment by xaizek** [comment]
Closing given [this comment on Q&A](https://q2a.vifm.info/1680/how-to-map-ctrl-shift-a-key-c-s-a-and-f13-keys-in-vifm?show=1684#c1684).  Some follow-up per [this](https://q2a.vifm.info/1680/how-to-map-ctrl-shift-a-key-c-s-a-and-f13-keys-in-vifm?show=1685#c1685) might be necessary.
