### ISSUE TITLE
Warnings reported by Infer

### ISSUE THREAD

**Issue by ZhipengXue97** [vifm/vifm#979]
1. bug_type: NULL_DEREFERENCE, qualifier: pointer `vifm_entry` last assigned on line 161 could be null and is dereferenced at line 163, column 38. procedure: vifmentry_mimetype, procedure_start_line: 158, file: vifm/src/lua/vifmentry.c
2. bug_type: UNINITIALIZED_VALUE, qualifier: The value read from name[_] was never initialized. line: 668, column: 6, procedure: unlet_variables, procedure_start_line: 619, file: vifm/src/engine/variables.c
3. bug_type: NULL_DEREFERENCE, qualifier: pointer `narrow` last assigned on line 320 could be null and is dereferenced at line 322, column 26. procedure: transform_wide_str, procedure_start_line: 296, file: vifm/src/utils/str.c
4. bug_type: NULL_DEREFERENCE, qualifier: pointer `expanded_path` last assigned on line 3703 could be null and is dereferenced by call to `is_path_absolute()` at line 3704, column 6.. procedure: mark_cmd, procedure_start_line: 3674, file: vifm/src/cmd_handlers.c
5. bug_type: NULL_DEREFERENCE, qualifier: pointer `wide_input` last assigned on line 2367 could be null and is dereferenced at line 2371, column 2. procedure: escape_cmd_for_pasting, procedure_start_line: 2364, file: vifm/src/modes/cmdline.c

**Comment by ZhipengXue97** [comment]
They are detected based master. 
#2 Looks like a false positive, and the rest NULL_DEREFERENCE related to the method defined by developers.
So I think it will be better checked by developers

**Comment by xaizek** [comment]
Thanks. Second warning looks nonsensical.  Added some checks for other warnings.  `NULL` from the first one should actually signify a programming error instead of a runtime one, but it won't hurt to check for it as other similar things do get checked.
