### ISSUE TITLE
ERROR: Unknow key for 'fillchars' option: millersep

### ISSUE THREAD

**Issue by ShailMurtaza** [vifm/vifm#980]
Hi!
I'm trying to add separator between miller columns using this command: `set fillchars+=millersep:'|'` but it is not working and returning error: `Unknow key for 'fillchars' option: millersep`.

> $ vifm --version
> Version: 0.13
> Git info: built out of repository
> Compiled at: May 10 2023 21:21:48
> 
> Operating System: Arch Linux                      
> Kernel: Linux 6.6.15-1-lts
> Architecture: x86-64

**Comment by xaizek** [comment]
Hi, 3020251 implements it.  Will be in the next release.

**Comment by ShailMurtaza** [comment]
Can you please tell me when next release will be available? Any estimation?
And is it fine for me to build it by myself without any stability issues?

**Comment by xaizek** [comment]
> Can you please tell me when next release will be available? Any estimation?

Should be in the spring.

> And is it fine for me to build it by myself without any stability issues?

Sure.  Probability of hitting a bug isn't much higher and you get fixes accumulated since the last release.  You could also cherry-pick 3020251 on top of `v0.13` tag and use that, all conflicts that arise in this case are related to documentation.
