### ISSUE TITLE
how does one configure vifm to have transparent background

### ISSUE THREAD

**Issue by iambumblehead** [vifm/vifm#981]
I have read the wiki color page https://wiki.vifm.info/index.php/Color_schemes and have reviewed and experimented with `.config/vifm/colors/Default.vifm` but am unable to achieve transparent background with vifm, would you tell me how to do this?

```bash
$ echo $TERM
xterm-256color
$ vifm --version | grep Version
Version: 0.13
```

**Comment by xaizek** [comment]
Is your terminal transparent when you're in a shell, but not once Vifm is started?  If not, then there is nothing Vifm can do: it can't make terminal transparent, it at most might not interfere with transparency (not sure if there were cases of interference, but it might be possible if it depends on colors in use).

**Comment by iambumblehead** [comment]
@xaizek yes the shell is transparent then vifm starts and transparency goes away. I've tried using foot, gnome terminal and blackbox terminal. Other terminal tools have transparency in these terminals such as moc, ranger, emacs, musikcube

**Comment by Parilia** [comment]
You could try using kitty, works fine in that

**Comment by iambumblehead** [comment]
vifm is installed here on two devices. One is a vanilla arch linux gnome setup and the other is a guix sway setup. vifm transparency does not seem to work for either of them. Other potential users who try vifm probably experience the same issue.

**Comment by iambumblehead** [comment]
**summary: transparency is working, but there might be some issue** with the default configuration or maybe some missing information in the guide or wiki

---------------------------------------

Transparency is seen after adding this to `~/.config/vifm/vifmrc`
```ini
highlight Win cterm=none ctermfg=white ctermbg=none
```
Based on [reading,](https://github.com/vifm/vifm-colors) vifm should load and use the theme file `~/.config/vifm/colors/Default.vifm` but it appears the file is not loaded, even when `:colorscheme Default-256` is explicitly called. By default `~/.config/vifm/colors/Default.vifm` uses "black" for the Win hightlight, however editing this value does not affect future vifm sessions, leading me to believe there is some problem around loading or applying that file

For now, I can write highlight definitions directly to the main config file at `~/.config/vifm/vifmrc` and I'll play around with things and try downloading and applying some themes here https://vifm.info/colorschemes.shtml

**Comment by iambumblehead** [comment]
I am happy if this issue is closed or not -- thank you

**Comment by iambumblehead** [comment]
perfect! thank you @xaizek vifm is the main file manager now
