### ISSUE TITLE
Feature request: persistent tabs

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [vifm/vifm#982]
Via `:tabnew` new tabs can be created. However, tabs are not persistent between vifm session, i.e. when I leave vifm and reopen it, my tabs are gone.
I would like to have the ability of having persistent tabs, so that they persist similarly like bookmarks between sessions.

**Comment by xaizek** [comment]
It's available since v0.11. ['vifminfo' option](https://vifm.info/vimdoc.shtml#vifm-%27vifminfo%27) controls what's preserved between restarts.  You can `tabs` value like this in your `vifmrc` file:
```
set vifminfo+=tabs
```

**Comment by xaizek** [comment]
I won't change option's default, but might add `tabs` to sample `vifmrc` which already sets `'vifminfo'` to preserve almost everything.
