### ISSUE TITLE
Wrong comparison results

### ISSUE THREAD

**Issue by IAmKapuze** [vifm/vifm#984]
I'm comparing large directories with long file names, and I get information that some files are different, however, when I go down a level to compare, these files are not different

Later I will investigate the problem to understand what exactly the problems are related to (number of files/their size/or names) or I will offer my solution, but for now I’ll just leave screenshots (sorry, I’m too tired for research today). The archive with all the files to reproduce is too large to attach

![image](https://github.com/vifm/vifm/assets/16070551/0fb054cf-02bc-47af-91b9-46578440581d)
![image](https://github.com/vifm/vifm/assets/16070551/5725dc71-bdfb-437a-b362-8ee50ee296bc)

**Comment by IAmKapuze** [comment]
After deleting all directories, except for one of those that showed differences in files, everything appears normal
![image](https://github.com/vifm/vifm/assets/16070551/b0c1f260-04bb-49e1-b46e-c3a5cf43acfb)

**Comment by xaizek** [comment]
I've seen that twice as well and only when comparing large directory trees.  First time I thought it was a hardware issue, but second time indicated that a bug in Vifm is more likely.  Could be a memory-related bug.

**Comment by xaizek** [comment]
I reproduced it with 3 pairs of identical files, so don't spend time on that.  It's something about handling conflicts due to identical size.
