### ISSUE TITLE
Keybind with if/else

### ISSUE THREAD

**Issue by ManuGraiph** [vifm/vifm#987]
Hi!

I'm trying to make a conditional binding for the right arrow so when i'm over a folder it does one thing and when it's over a file it does another. Now, when it's over a file i'd like to keep the normal behaviour for files that it'd have if it's not remapped, but i haven't been able to do it.

Currently i have:

    nnoremap <Right>
          \ : if filetype('.') == 'dir'
          \ |     execute ':cd %c'
          \ |     <some stuff>
          \ | else
          \ |     execute ':!open %c'
          \ | endif<cr>

Which works flawless, but i have to basically config the xdg-open for all files and at the same time i lose all the vifm functionality to quickly set functions to run when i'm on a certain filetype.

Is there any way to set an if for the right arrow (or the key used to navigate) on folders to execute some random thing  and open them normally BUT to keep the default remap when over a file?

**Comment by xaizek** [comment]
Hello.

You can use [`:normal` command](https://vifm.info/vimdoc.shtml#vifm-%3Anormal) like this:
```vim
nnoremap <Right>
     \ : if filetype('.') == 'dir'
     \ |     cd %c
     \ |     echo 'opened a directory'
     \ | else
     \ |     execute 'normal l'
     \ | endif<cr>
```
There should really be `:open` though (#901).

**Comment by ManuGraiph** [comment]
Perfect, that's the command i was missing "'normal l", thanks a lot!
