### ISSUE TITLE
can vifm be configured to show file path and name together as one line?

### ISSUE THREAD

**Issue by iambumblehead** [vifm/vifm#990]
for example, `~/software/guix-artwork/logo/Guix-print.svg` rather than; `~/software/guix-artwork/logo/` with separated `File: Guix-print.svg`?

For example, this is how ranger does it (vifm seen to the right)

<img src="https://github.com/vifm/vifm/assets/2058705/f9e3fa32-ad6f-4e75-ad3a-1fb67275d721" height="220" /> <img src="https://raw.githubusercontent.com/iambumblehead/thu.sh/main/test/thu.sh.vifm.miller.png" height="220" />

Likely there are shortcut keys to copy the file path, however, having the full path together allows selecting and copying the text fullpath without hotkey.

**Comment by xaizek** [comment]
You have two panes open with each having its own title, common title for two panes seems to not make sense.  It would probably require an option for customizing view title to make it work for one tab.

As a crude workaround, could add this plugin (`$VIFM/plugins/tabline2/init.lua`):
```lua
--[[

Example of a tab line that just prints current path.

Usage example for `vifmrc`:

    set tabline=#tabline2#fmt

--]]

local function fmt(info)
    local view = vifm.currview()
    local entry = view:entry(view.currententry)

    local format = vifm.fnamemodify(entry.location .. '/' .. entry.name, ':~')

    format = string.gsub(format, '%%', '%%%%')
    return { format = format }
end

local added = vifm.addhandler {
    name = 'fmt',
    handler = fmt,
}
if not added then
    vifm.sb.error('Failed to register #%s#fmt', vifm.plugin.name)
end

return {}
```

And abuse pane tabs like this:
```vim
set milleroptions+=rpreview:all millerview
set tabline=#tabline2#fmt showtabline=always tabscope=pane
```

**Comment by iambumblehead** [comment]
thank you for the detailed reply
