### ISSUE TITLE
Default binding for `<C-u>` swaps panes instead of half-page up

### ISSUE THREAD

**Issue by midrare** [vifm/vifm#993]
According to [the manual](https://vifm.info/manual.shtml#Basic%20Movement), `<C-u>` should move half page-up. But by default, `<C-u>` swaps panes instead, which is non-standard and surprising behavior. Maybe half page-up should stay the default and swap pane be left up to user config instead?

**Comment by midrare** [comment]
Oh, I see. But might it be better to leave the Vim binding as the default? This was very confusing to me, especially as `<c-d>` was scrolling half page down like normal but `<c-u>` did not.

---

I can't seem to undo this keybind. I pressed `,c`, deleted the line, saved, and restarted `vifm`. But `<c-u>` still swaps panes. I know the config is being read because `nnoremap <c-u> :echo "here"<cr>` works fine.

This is with a fresh install of `vifm` version 0.13 (from scoop) on Windows 11. The config file I edited is at `~\AppData\Roaming\Vifm\vifmrc`.

**Comment by xaizek** [comment]
> Oh, I see. But might it be better to leave the Vim binding as the default? This was very confusing to me, especially as `<c-d>` was scrolling half page down like normal but `<c-u>` did not.

I might comment this one out, I think it was annoying me somewhere too and Vim is the focus here.

> I can't seem to undo this keybind. I pressed `,c`, deleted the line, saved, and restarted `vifm`. But `<c-u>` still swaps panes. I know the config file is being read because changing the line to `nnoremap <c-u> :echo "here"<cr>` works fine.

If there is `data/vifmrc` next to `vifm.exe`, then that file might be read before reading `~\AppData\Roaming\Vifm\vifmrc`, which is actually unintended behaviour.  Try editing that file or using `nunmap <c-u>`.

**Comment by midrare** [comment]
> If there is data/vifmrc next to vifm.exe, then that file might be read before reading ~\AppData\Roaming\Vifm\vifmrc

Thank you, that was in fact the problem. I deleted `%ProgramData%/scoop/apps/vifm/current/data/vifmrc` and everything is working normally again.
