### ISSUE TITLE
ueberzug regression in c470960 (fish?)

### ISSUE THREAD

**Issue by AERDU** [vifm/vifm#994]
When using the ueberzug lua plugin with fish I get ```attempted to use a closed file```. 

Bisecting got me to c470960, and I suspect that ```args[i++] = "--";```  is incompatible with fish. I haven't tested with bash/zsh but I'm pretty confident it'd work on posix compliant shells.

**Comment by xaizek** [comment]
Thanks for the report and bisecting. You're right, `-c` in fish accepts a parameter unlike in normal shells.  This way it doesn't need `--` for commands starting with a dash. On the other hand bash&zsh don't need `--` for commands without it, so adding `--` only when needed is an option.  This approach breaks fish for weirdly named commands, but don't have a better idea at the moment.
