### ISSUE TITLE
coupled marks: mark for both panes

### ISSUE THREAD

**Issue by sazam0** [vifm/vifm#996]
Hi, 
I have `mark`'s like following:
```
    mark d ~/.dotfiles ..
```
I want to do like that for both panes:
```
    <function/command> <key> <dir in pane 1> <dir in pane 2>
```
Can you please guide me, how to do that and also what will be the prefix key for these coupled marks?

Thank you for your time.

**Comment by xaizek** [comment]
Hello,

Marks are associated with a single directory path, but you could emulate pairs of paths using [`:cd` command](https://vifm.info/vimdoc.shtml#vifm-%3Acd):
```
" with a custom command
command! cfg :cd /etc /var
" or with a mapping
nnoremap <silent> `c :cd /etc /var<cr>
```

**Comment by sazam0** [comment]
Thank you. The Keymapped solution is what I was looking for.
