### ISSUE TITLE
Open multiple selected files in Windows

### ISSUE THREAD

**Issue by smoothdad** [vifm/vifm#998]
I've tried various commands in vifmrc but cannot get Windows to open multiple selected files.

filetype * explorer %"f &

works if one file is selected, but if more than one file is selected, Windows just opens an explorer window.

**Comment by xaizek** [comment]
I think that's just how `explorer` or `start` commands work, they don't handle multiple files.

There is special handling of selection in Vifm described in https://vifm.info/vimdoc.shtml#vifm-selection. However,  the documentation is correct in that code really handles `%c` and `%f` but it doesn't to the same for `%"c`/`%"f`, which is an omission.  The behaviour was probably never tested on Windows.

```
filetype * explorer %c &
```
does invoke `explorer` for every file in the selection for me, but it can have escaping issues until `%"c`" is handled as well.

**Comment by xaizek** [comment]
If you want to use fixed handling of `%"c`, you can grab latest binaries from https://builds.vifm.info/.

**Comment by smoothdad** [comment]
Awesome.  Thank you so much.
